### ISSUE TITLE
DataTable NumberFormatter text_align='right',language='it' do not work

### ISSUE THREAD

**Issue by mauropu** [bokeh/bokeh#7124] opened 2017-10-29 21:05 UTC
Good morning.
I work with this software:
o.s.= windows 10
python 3.5,1
bokeh 0.12.10

I wish to set in a DataTable for a colunn:
- right alignement
- currency euro
- using for the number the european convention:  dot for commas

This is the example that do not work:

```
# mauro
# 29 ottobre 2017
# bokeh serve testAlignment.py
# http://localhost:5006/testAlignment
# bokeh: 0.12.10
from datetime import date
from random import randint
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, NumberFormatter,TableColumn
from bokeh.plotting import curdoc
data = dict(
        dates=[date(2014, 3, i+1) for i in range(10)],
        downloads=[randint(0, 100)*90.5 for i in range(10)],
    )
source = ColumnDataSource(data)
columns = [
        TableColumn(field="dates", title="Date", formatter=DateFormatter()),
        TableColumn(field="downloads", title="Downloads",formatter=NumberFormatter(format='0,0[.]00 $',text_align='right',language='it')),
    ]
data_table = DataTable(source=source, columns=columns, width=400, height=280)
curdoc().add_root(data_table)
```
![immagine](https://user-images.githubusercontent.com/33205885/32148305-2a087846-bcf5-11e7-9215-095065e3c496.png)

Kind Regards

Mauro

**Comment by bryevdv** [comment] 2017-10-29 21:27
@mattpap it doesn't look like we are bundling Numbro's `languages.js` with `bokeh-tables`?  

As for the alignment, the CSS is being properly set  but the span that is also shrunk to only be just as big as the text, so alignment is essentially a no-op

**Comment by mauropu** [comment] 2017-11-01 21:37
Hi,
Do you have any idea when the change will be available?
Kind regards
Mauro

**Comment by tomanizer** [comment] 2018-01-29 11:35
This appears to be a duplicate of
#5721

**Comment by bryevdv** [comment] 2018-01-29 15:23
Thanks @tomanizer

**Closed by bryevdv** 2018-01-29 15:23 UTC
Labels: tag: widgets, type: bug

**Comment by mauropu** [comment] 2018-01-29 21:58
Sorry
but the #5721 is NOT solved from 13 Jan 2017  and the #7124 is NOT solved at today.
This means that when a bugs is report two time the bug is closed and not correct?
Kind regards
Mauro

**Comment by bryevdv** [comment] 2018-01-29 22:11
@mauropu I am not sure what you asking. There is no claim about #5721 being fixed, only that that issue and this issue appear to describe the exact same problem. We do not keep duplicate issues open, because it is clutter on the the tracker, so this second (duplicate) issue has been closed as redundant.

**Comment by mauropu** [comment] 2018-01-29 22:21
I'm sorry.
I had understood that it had been removed from the list of fixes of the next releases.
Thank you for your quick response.
Greeting
Mauro

**Comment by bryevdv** [comment] 2018-01-29 22:34
FYI I doubt this will be fixed for `0.12.14` we are underwater with other work right now.

**Comment by mauropu** [comment] 2018-01-29 23:45
Thanks for the update about the 0.12.14 release
We hope the fix in the next.
Kind regards
Mauro

**Comment by mauropu** [comment] 2018-10-17 13:48
Good Morning
at today the bug  #5721, that is not fixed.
In wich release is planned to fix?
Kind reagrds
Mauro Putzu
