### ISSUE TITLE
[BUG] datetime formatting leading zero

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#13183] opened 2023-06-07 21:03 UTC
### Software versions

Tornado version     :  6.3.2
Bokeh version       :  3.1.1

### Expected behavior

Day numbers should be formatted with leading zero: 01 instead of 1 (as described in the docs).

### Observed behavior

Leading zero is omitted. Note: The default MM/DD format does have this issue.

### Example code

```Python
import pandas as pd
from bokeh.io import curdoc
from bokeh.models import DatetimeTickFormatter
from bokeh.plotting import figure

import numpy as np

t = pd.date_range("2023-06-01", periods=11)
y = np.linspace(0, 10, 11)

fig = figure(x_axis_type="datetime")
fig.line(t, y)
fig.xaxis.formatter=DatetimeTickFormatter(
        minutes =["%H:%M"],
        hours=["%d-%m-%Y %H:%M"],
        days=["%d-%m-%Y %H:%M"],
        months=["%d-%m-%Y %H:%M"],
        years=["%d-%m-%Y %H:%M"],
    )

doc = curdoc()
doc.add_root(fig)
```

### Screenshots

![bokeh_bug_dt](https://github.com/bokeh/bokeh/assets/71090451/b300dcf4-f3f4-49cc-bca0-ecfa34edce45)

**Comment by bryevdv** [comment] 2023-06-07 21:32
I have to assume that the check for `strip_leading_zeros`:

https://github.com/bokeh/bokeh/blob/3a6d59588aadc7ddd26dd3359be6e9e2b03b1ca1/bokehjs/src/lib/models/formatters/datetime_tick_formatter.ts#L199-L209

is misfiring, because javascript is gonna javascript:

<img width="166" alt="Screenshot 2023-06-07 at 14 30 47" src="https://github.com/bokeh/bokeh/assets/1078448/2340acac-2cfc-4ca4-a073-b2ce62b99bb2">

**Comment by bryevdv** [comment] 2023-06-07 21:39
Maybe we could use `Number` here instead?

<img width="143" alt="Screenshot 2023-06-07 at 14 37 11" src="https://github.com/bokeh/bokeh/assets/1078448/4f776222-2099-486b-a3f7-a0f4cb85ca6f">

I guess doing *just* that would result in "0.00123" becoming ".00123" which is also not good... `Number.isInteger(Number(ss))` then?

**Comment by mattpap** [comment] 2023-06-07 21:46
Isn't this a duplicate of issue #12870?

**Comment by bryevdv** [comment] 2023-06-07 21:48
yes, it seems to be. I don't think we got to the root cause in that issue yet, so I'll mention the link here

**Closed as completed by bryevdv** 2023-06-07 21:48 UTC
Labels: reso: duplicate, type: discussion
