### ISSUE TITLE
Result of bokeh.util.compiler.bundle_all_models should be cached

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#6566] opened 2017-06-30 08:31 UTC
It takes about 2-3 seconds for `bokeh.util.compiler.bundle_all_models` to run on my machine.
Its result doesn't seem to be dependent on anything other than the set of already defined bokeh models.

Perhaps it makes sense to cache the result of this function? Or rather, memoize `bokeh.util.compiler.bundle_models` - this way, newly defined models will be taken into account.

**Comment by bryevdv** [comment] 2017-06-30 14:03
This is a dupe of https://github.com/bokeh/bokeh/issues/5101 I'm going to change the title there to reflect that better. Please continue the discussion there

**Closed by bryevdv** 2017-06-30 14:03 UTC
Labels: type: discussion
