### ISSUE TITLE
No fill for background and border doesn't work

### ISSUE THREAD

**Issue by MikaS** [bokeh/bokeh#4855] opened 2016-07-21 19:19 UTC
Hi,

I'm trying to embed a bokeh plot into a web application that has a gradient background defined in its CSS. I would like my bokeh plot being drawn above that gradient background, without masking it, as if I had "transparent" background and border.

So I set:
fig.background_fill_color = None
fig.border_fill_color = None

But instead of having no fill for the background and the border, I have a ugly gray color that hides my web application's background.

I tried the following trick:
fig.background_fill_color = "#000000"
fig.border_fill_color = "#000000"
fig.background_fill_alpha= 0.0
fig.border_fill_alpha = 0.0

It works, but have a bad side effect: when panning or zooming the plot, previous positions of axis values and ticks are not erase, but drawn above each other.

So, it shall be possible to easily define "no color fill" for background and border (and outline).

Cheers
Mikaël

**Comment by birdsarah** [comment] 2016-07-21 20:43
@bryevdv "It works, but have a bad side effect: when panning or zooming the plot, previous positions of axis values and ticks are not erase, but drawn above each other." We were talking about this today - do you know what the cause of this is

@MikaS - thanks for the report. You have two separate bugs here

1. `fig.background_fill_color = None` - `fig.border_fill_color = None` - should just cause nothing to be drawn not set to the default of gray.
2. The weird echos of previously drawn axes

The first one does have a workaround as you have seen - which is to set the `*_fill_alpha=0`; the second one however doesn't and I first noticed it about 4 months ago so its been around for a while - although I don't think I opened an issue for it.

**Comment by birdsarah** [comment] 2016-07-22 23:50
@canavandl, I believe you've fixed things like this before - do you remember a PR?

**Comment by canavandl** [comment] 2016-07-29 20:49
Hi @MikaS 

The issue is (hopefully) resolved in #4908 . If you're able to test that PR, it'd be great.

**Closed** 2016-08-03 18:52 UTC
Labels: type: bug
