### ISSUE TITLE
Drawing many Line glyphs with webgl enabled gives bad performance

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#4888] opened 2016-07-26 23:04 UTC
Code to reproduce:

``` python
import numpy as np
from bokeh.plotting import output_file, show, figure

output_file('line.html')

webgl = True
plot = figure(title='WebGL = {}'.format(webgl), webgl=webgl)

for i in range(50):
    data = np.random.rand(2,10)
    plot.line(x=data[0], y=data[1])

show(plot)
```

It appears that drawing many Line glyphs (very noticeable above 50) with webgl=True causes poor rendering performance (~5 second page render). Using the Chrome profiler dev tool, it appears that many CPU cycles are spent inside of core webgl calls (`getProgramParameter` and `getShaderParameter`).

<img width="1434" alt="screen shot 2016-07-26 at 5 56 31 pm" src="https://cloud.githubusercontent.com/assets/2198981/17158273/d8a4da8a-535a-11e6-9612-e29fab0eb3a8.png">

Here's the profiler output with webgl disabled:

<img width="1437" alt="screen shot 2016-07-26 at 5 56 44 pm" src="https://cloud.githubusercontent.com/assets/2198981/17158282/e7843460-535a-11e6-86ac-40701f1c7ddc.png">

It's worth discussing if these webgl calls could potentially be aggregated into fewer calls or cached.

**Comment by canavandl** [comment] 2016-07-26 23:06
ping @almarklein

**Comment by almarklein** [comment] 2016-07-26 23:16
Is the performance of WebGL worse than that of the canvas in this case?

**Comment by bryevdv** [comment] 2016-07-27 13:36
@almarklein yes it seems as thought "many individual lines" starts accumulating some fixed overhead cost possibly? If so it would make sense to try and aggregate work to reduce that overhead cost, but then `MultiLine` seems like an already made place for such an aggregation.

**Comment by jbednar** [comment] 2016-07-27 13:45
Yes, the WebGL performance is much, much worse, causing it to take tens of seconds to display the "edit_compounds" plot that you (Almar) wrote for us in December, whereas it's a second or so for the Canvas version (roughly counted).  

In the above simpler example, the profiling suggests that the WebGL version takes 2.4 seconds and the Canvas version takes 0.26 seconds.

**Comment by almarklein** [comment] 2016-07-27 13:54
@jbednar Oh wow. Since when did it get worse? Could that be since I made it working on Safari?

**Comment by philippjfr** [comment] 2016-07-27 14:31
@almarklein No we've been encountering this for a few months now, so my assumption would be that it has been this way since the beginning.

**Comment by almarklein** [comment] 2016-07-27 14:52
So if I understand correctly, the slowness in in page loading, not during interaction? @canavandl same for you?

**Comment by almarklein** [comment] 2016-07-27 15:13
For the record: making multiline work with WebGL is definitely a useful thing to do (regardless of this issue). But there might also be a bug that causes the initialization to take overly long, so I'd like to have a look at that too.

**Comment by jbednar** [comment] 2016-07-27 15:21
The worst slowness is during the initial display of the figure, which is both very slow and also hangs the browser, which makes people think their computer has crashed, even though if one is very patient the browser comes back to life eventually.  But interaction is also slow, taking a second or two to click on a line and have the results be visible.  I'm not sure if interaction speeds up when webgl=False, but the initial display certainly does.

I don't remember it being quite so slow with Bokeh 0.10, but that particular plot broke with Bokeh 0.11.1, and we weren't able to run it until 0.12, at which point we noticed the extreme slowness.  The slowdown is definitely _not_ due to the fixes for Safari, as we are still using 0.12.0 for most of our testing.

**Comment by philippjfr** [comment] 2016-07-27 15:23
>I don't remember it being quite so slow with Bokeh 0.10, but that particular plot broke with Bokeh 0.11.1, and we weren't able to run it until 0.12, at which point we noticed the extreme slowness.

Reasoning about that is complicated by the fact that we only enabled webgl properly at some later point. It's perfectly possible that it was slow all along but we didn't reveal it until I properly enabled webgl in holoviews.

**Comment by jbednar** [comment] 2016-07-27 15:29
That makes sense; probably we enabled webgl and didn't see any effect on this plot because it was broken, and then once the plot was working again enabling webgl was long enough ago that we didn't see the connection.

**Comment by almarklein** [comment] 2016-07-28 14:47
I had a look, and it seems the bottleneck is in the `gloo2.Program.set_shaders()` function, which performs the compiling and linking of the GLSL code for the line. The GLSL for the line glyph is pretty big, but I am surprised to see it this big. I can imagine there are ways to improve this though, e.g. by sharing the compiled shader objects between the different shader programs. Will have a better look after I'm back.

**Comment by bryevdv** [comment] 2022-11-03 02:31
@ianthomas23 do you have any indication that this might still the case? If not, then given the age of the issue and the complete re-impementation of webgl in the intervening years, I am inclined to close this as stale

**Comment by ianthomas23** [comment] 2022-11-03 09:49
This cannot occur any more. Use of ReGL and the new implementation means that there can only ever be a maximum of 2 of each of the vertex and fragment shaders for line, one for solid lines and one for dashed lines.

I am going to close it and classify it as fixed by PR #10861 (WebGL via ReGL).

**Closed by ianthomas23** 2022-11-03 09:49 UTC
Labels: type: discussion, tag: webgl

**Comment by mattpap** [comment] 2022-11-03 10:00
It wouldn't hurt to a add regression test or a benchmark of some sort for this.

**Comment by ianthomas23** [comment] 2022-11-03 15:58
A test checking that different calls to webgl-backed `figure.line()` use the same compiled shaders sounds initially like a good regression test, but I hesitate to do that as it is all hidden implementation within ReGL so we'd have to access private ReGL attributes.

**Comment by bryevdv** [comment] 2022-11-03 16:03
I am also 👎 on testing ReGL internals. I think we can address any future issues as new issues with the new implementation, when or if any such issues ever arise.

**Comment by mattpap** [comment] 2022-11-07 12:05
I meant some kind of regression test, not specifically testing internals of regl. Something like this #12573, not ideal but somewhat helpful to understand performance of various backends.
