### ISSUE TITLE
Datatable last row

### ISSUE THREAD

**Issue by Pierretherenard** [bokeh/bokeh#6794] opened 2017-08-21 22:32 UTC
Hello,
I am not sure if this is already fixed (#5207). All the DataTable on my project do not display the last row when they are built and updated on the same tab. Same problem if I open the file in a new window or if the file open in a maximum size window.
The only way to get to display the last line is to resize (MAXIMIZE) the window. If you downsize from this action, the last row is still displayed. 
I still have this problem but I tried to recreate it with a single 1000 rows Table for a test code and I could not make it yet, even though this is the same code. If I find the difference I will add the code later.

0.12.6
mac OS X Yosemite
Safari, Firefox

Thank you,
Pierre

**Comment by Pierretherenard** [comment] 2017-08-21 22:35
I did mention #5207 because it helped me to find the temporary solution by resizing the window. The datatable right now gave me the row label perfectly which was the issue with #5207.

**Comment by bryevdv** [comment] 2017-08-21 22:38
@Pierretherenard apologies but I don't understand exactly what is happening from your description. Please provide a complete test script to reproduce any problems. Until a problem can be isolated and reproduced there is very little chance that we can do anything about it.

**Comment by Pierretherenard** [comment] 2017-08-21 22:58
I understand.
My test script right now could not replicate and isolate the issue but my code in the project is creating the issue. But it seems to be the same code. Yes I will try harder in getting this issue recreated and post here.
 
Here are 2 pictures of the same datatable from my project, last 4 rows:
1: loading the project not resizing, I cannot see the last row. Impossible, the cursor disappears as well.
![screen shot 2017-08-21 at 3 41 24 pm](https://user-images.githubusercontent.com/23002446/29541220-8edae032-8687-11e7-9e37-ef5ee02507e6.png)

2: after resizing the window, I can see the last row, which was previously unreachable.
![screen shot 2017-08-21 at 3 42 14 pm](https://user-images.githubusercontent.com/23002446/29541302-00312d7c-8688-11e7-8d74-4e180eec5d3c.png)

**Comment by crashMOGWAI** [comment] 2017-08-22 01:20
At first glance this reads like a subtle layout problem

**Comment by Pierretherenard** [comment] 2017-08-28 13:12
here I found it:
I use one table where the last row is 100. I use tab. if your table is in the first tab then you can see the last row. But if your table in any other tab than the first tab then you cannot see the last row unless you resize the window.

`    def test31():
        from bokeh.models import ColumnDataSource, WidgetBox, HoverTool, Label
        from bokeh.models.widgets import DataTable, Tabs, DateFormatter, TableColumn, Div

        word = []
        for i in range(0, 101):
            j = "{}abcdefghijklmnopqrstuvwxyz".format(str(i))
            word.append(j)
        rword = word[::-1]
        sopeople = ColumnDataSource(data=dict(rword=rword))

        columns1 = [
            TableColumn(field="rword", title="people", default_sort="descending"),

        ]

        print(word[-1])
        dttbl1 = DataTable(source=sopeople, columns=columns1, width=200, height=620)

        wdgtdt1 = WidgetBox(dttbl1)


        divtest = Div(
            text="""test test test test """,
            width=200)
        divtest0 = Div(text="""0""")


        l5 = row(column([wdgtdt1, divtest]))
        l0 = column([divtest0])
        tab0 = Panel(child=l0, title='0')
        tab1 = Panel(child=l5, title='1')

        tabs = Tabs(tabs=([tab0,tab1]))
        show(tabs)`
![screen shot 2017-08-28 at 6 10 44 am](https://user-images.githubusercontent.com/23002446/29774807-bd72d5be-8bb7-11e7-82ca-98966c153793.png)

ok I have to go, I am going to be late

**Comment by cutright** [comment] 2017-09-05 03:45
I have the same issue and it manifested itself once I switched to tab layouts.  If I click what appears to be the last row, I can hit the down arrow to select the final row.  This is verifiable when using a plot connected with the same source.

I'm happy to provide some code if the above is insufficient.

**Comment by Pierretherenard** [comment] 2017-09-06 03:57
I will try your solution. Thank you.

**Comment by Pierretherenard** [comment] 2017-09-09 16:47
I just run my code changing nothing except using 0.12.7 and the last row is displaying. I don't have this issue anymore.
Thank you,
Pierre

**Comment by cutright** [comment] 2017-09-11 23:15
0.12.7 fixes this issue for me well, but now sometimes tables are not displayed at all until scrolling and sometimes a figure reset is required before that too.

**Comment by Pierretherenard** [comment] 2017-09-12 03:03
I am going to test it on 0.12.8, just released, and see if this is fixed.

**Comment by bryevdv** [comment] 2017-09-12 03:21
Not announced until morning, but it is built and available. With two big important features out of the way, I plan to spend the next release on bug fixes like this and stability.

**Comment by Pierretherenard** [comment] 2017-09-12 03:27
Something broke, still looking into it
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5 /Users//PycharmProjects/TextPlot/TxtPlt.py
Traceback (most recent call last):
  File "/Users//PycharmProjects/TextPlot/TxtPlt.py", line 29, in <module>
    from bokeh.plotting import figure, output_file, show
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bokeh/plotting/__init__.py", line 7, in <module>
    from ..io import curdoc; curdoc
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/bokeh/io.py", line 29, in <module>
    from IPython.display import publish_display_data
ImportError: No module named 'IPython'

Process finished with exit code 1

**Comment by bryevdv** [comment] 2017-09-12 03:31
@Pierretherenard that message is saying you don't have the notebook installed in whatever environment you are using

**Comment by bryevdv** [comment] 2017-09-12 03:34
@Pierretherenard this is a serious bug, we all always have the notebook installed, so we missed this regression.

**Comment by bryevdv** [comment] 2017-09-12 03:38
Thanks for catching this, I will fix it tonight, not sure if there will be a `0.12.9` early or if I can roll back this release.

**Comment by bryevdv** [comment] 2017-09-12 03:57
@Pierretherenard FYI since you discovered this before 10 minutes was out and I had not announced anything, I am doing something probably ill-advised, and attempting to roll-back and re-release

**Comment by Pierretherenard** [comment] 2017-09-12 04:00
OK just to let you know bryevdv, until 0.12.7 I did not have to install Ipython, with 0.12.8 I had to install Ipython. This is running now. I will report in 25 minutes. I know I should not continue on this thread.

**Comment by bryevdv** [comment] 2017-09-12 04:06
@Pierretherenard here is the thread https://github.com/bokeh/bokeh/issues/6922 for the issue. I have deleted the brief release, and am working a new one.

**Comment by bryevdv** [comment] 2017-09-12 06:10
@Pierretherenard I deleted the old comments unrelated to this issue but if you still can comment about whether the (new) 0.12.8 build works wrt to this data table issue that'd be useful

**Comment by bryevdv** [comment] 2017-09-12 06:25
PyPI will not allow re-using versions,buildng 0.12.9 now.

**Comment by Pierretherenard** [comment] 2017-09-14 16:08
Yes cutright I have the same issue. The Tables are blank until you scroll.

**Comment by cutright** [comment] 2017-09-14 16:18
Thanks @Pierretherenard.  Any clues on your end as to the cause?

My tables are filled with data from a SQL query.  Behavior is consistent if I make the same query, but I cannot predict when the table will be blank at first (i.e., some queries do not prompt this issue).  It does not appear to be related to the number of rows, and it doesn't seem to happen for data tables with at static source of data.

**Comment by Pierretherenard** [comment] 2017-09-14 16:37
I just tested the difference when the table is in the first tab or in the tabx. It seem that there is no issue when the table is in the first tab. But as soon as your table is in another table then it becomes blank until you scroll. I tested with 2 tabs and 1 Table.

**Comment by cutright** [comment] 2017-09-14 16:38
That is consistent with code as well.

**Comment by Pierretherenard** [comment] 2017-10-25 04:21
Checked with 0.12.10, the table stay blank until you scroll.

**Comment by bryevdv** [comment] 2017-11-08 22:48
closing as a dupe of #7120 (as best I can tell, no complete MRE was ever provided)

**Closed by bryevdv** 2017-11-08 22:48 UTC
Labels: type: discussion

**Comment by Pierretherenard** [comment] 2017-11-08 23:04
I forgot about this one. I have no problem anymore. Using 0.12.10 right now.
Thank you,
Pierre
