### ISSUE TITLE
HoverTool() mode 'vline' produces double labels

### ISSUE THREAD

**Issue by brcnblc** [bokeh/bokeh#8559] opened 2019-01-11 12:26 UTC
Mac Os Mojave 10.14.2

Python 3.6.3 |Anaconda, Inc.| (default, Oct  6 2017, 12:04:38) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin

Bokeh '1.0.3'

Google Chrome Version 71.0.3578.98 (Official Build) (64-bit)

Problem:

HoverTool()

mode='vline' produces double hover labels on some arbitrary points. Problem occurs on all fixed, stretched, scaled glyphs.

If scale is used, after resizing the double label points change arbitrarily. If resized to smaller window then the arbitrary double label points tend to increase.
![normalhover](https://user-images.githubusercontent.com/29043834/51033620-12c9f500-15b5-11e9-99f7-997268b3b326.jpg)

```
p = figure(x_axis_type='datetime', plot_width = self.__plotWidth, plot_height = plotHeight, title = title, toolbar_location=None)
lineGraph = p.line('date', 'values', source = source, name=plotName, **params)
hover = {
                'tooltips' : [['Price','@values{%0.2f}']],
                'formatters' : {'values':'printf'},
                **'mode' : 'vline',** 'renderers' : ['self'], 'attachment' : 'below', 'anchor' :'center',
                'line_policy' : 'nearest', 'point_policy' : 'snap_to_data', 'show_arrow' : True}

```
Note: self is replaced with the glyph instance of the line in runtime
#### Screenshots or screencasts of the bug in action
![abnormalhover](https://user-images.githubusercontent.com/29043834/51033288-f8434c00-15b3-11e9-91fc-cf5f916492c9.jpg)

**Comment by bryevdv** [comment] 2019-01-11 17:16
This is a dupe of https://github.com/bokeh/bokeh/issues/1512

(If you have very dense points on a line, i.e. more than number of pixels but possibly with less, then the single vline will hit multiple points, resulting in multiple tooltips)

**Closed by bryevdv** 2019-01-11 17:16 UTC

**Comment by brcnblc** [comment] 2019-01-13 13:52
Isn't it possible to eliminate abnormal double view of same exact data point  by checking if the hit point refers to same data with the previously found hit point in y axis ?

**Comment by bryevdv** [comment] 2019-01-13 15:34
It's possible this is not a duplicate, if it is truly the same point.  I will consider reopening this is if you provide a complete minimal script to reproduce.
