### ISSUE TITLE
Cannot modify column width of datatable/tablecolumn

### ISSUE THREAD

**Issue by davidleo4313** [bokeh/bokeh#4768] opened 2016-07-07 17:20 UTC
I have a column with various long values. When I use datatable to visualize, the column width is too narrow to display the value. I have tried setting individual width of TableColumn but my setting widths do not applied. Is there anything wrong with the width settings?
`columns.append(TableColumn(field=col, title=col, width=600))`
`columns.append(TableColumn(field=col1, title=col1, width=150))`
`columns.append(TableColumn(field=col2, title=col2, width=150))`
`data_table = DataTable(source=source, columns=columns, height=450)`
`output_file(data_table)`

**Comment by andreidi** [comment] 2017-02-23 12:23
Any feedback !?

**Comment by chreman** [comment] 2017-05-03 11:53
it worked for me after I set "fit_columns" to False, e.g.
`DataTable(source=data_source, columns=data_columns, fit_columns=False)`

**Comment by bryevdv** [comment] 2018-05-10 19:36
Since a potential workaround was given, and there is not complete minimal reproducer provided to test with, I am going to close this. If an issue persists, please provide a complete script to reproduce the problem for us to be able to investigate.

**Closed by bryevdv** 2018-05-10 19:36 UTC
