### ISSUE TITLE
[BUG] Bokeh change data_source aren't updated by push_notebook

### ISSUE THREAD

**Issue by uduse** [bokeh/bokeh#11256] opened 2021-05-10 20:57 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.3.1
python 3.7.4
macOS 11.2.3
chrome
jupyter 1.0.0

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np

import bokeh
from bokeh.io import push_notebook, show, output_notebook
from bokeh import layouts
from bokeh.plotting import figure

output_notebook()


# In[2]:


def to_data_source(y):
    y = np.array(y)
    x = np.arange(y.size)
    return bokeh.models.ColumnDataSource({
        'x': x,
        'y': y
    })


# In[3]:


# this will plot an empty figure
vis = figure()
handle = show(vis, notebook_handle=True)


# In[4]:


# this will plot on the empty figure
line = vis.line()
line.data_source = to_data_source(np.random.randn(30))
push_notebook(handle=handle)


# In[5]:


# this will not update the figure
line.data_source.data['y'] += np.arange(30)
push_notebook(handle=handle)


# In[6]:


# this will not update the figure
line.update(data_source=to_data_source(line.data_source.data['y'] + np.arange(30)))
push_notebook(handle=handle)


# In[7]:


# this will plot the correct figure that should've been updated to the previous `show`
show(vis)
```

I tried removing the old glyph and adding a new one every time, and it actually works. However, I don't understand why this simple usage that I see everywhere doesn't work here.

Also gist of the notebook [here](https://gist.github.com/uduse/f2b17bc67de8fd0ee32f34a87849c8b6). I also [posted a question on stackoverflow](https://stackoverflow.com/questions/67394836/bokeh-change-data-source-arent-updated-by-push-notebook) and if you would like some bounty you could answer there too.

**Comment by bryevdv** [comment] 2021-05-10 21:05
@uduse best practice in Bokeh is to update the `.data` field of an existing data source, not replace data source itself wholesale. I would go so far as to say the latter is simply unsupported (and perhaps that needs to be documented better)

**Comment by uduse** [comment] 2021-05-10 23:27
> @uduse best practice in Bokeh is to update the `.data` field of an existing data source, not replace data source itself wholesale. The former pattern is well-established and what is demonstrated in all the official examples. I would go so far as to say the latter is simply unsupported (and perhaps that needs to be documented better)

The code `# In[5]` is doing what you suggested, right?

**Comment by bryevdv** [comment] 2021-05-10 23:29
@uduse I mean:
```
source.data = new_data_dict
```

**Comment by uduse** [comment] 2021-05-11 02:48
I tried:
`
line.data_source.data = {'x': line.data_source.data['x'], 'y': line.data_source.data['y'] ** 3}
push_notebook(handle=handle)
`
This is what are you suggesting? It seems it doesn't have an effect either.

**Comment by bryevdv** [comment] 2021-05-11 03:07
I just tested this notebook with 2.3.1 and Python 3.7 on OS X, and it is working as aspected. So first things first, does this notebook function for you?

https://github.com/bokeh/bokeh/blob/branch-2.4/examples/howto/notebook_comms/Continuous%20Updating.ipynb

**Comment by uduse** [comment] 2021-05-11 03:50
These are the version numbers. I'm not exactly sure why `jupyter==1.0.0` exists. It seems other things are up to date.

```
(jax) > $ pip freeze | grep jupyter
jupyter==1.0.0
jupyter-bokeh==3.0.0
jupyter-client==6.1.13
jupyter-console==6.4.0
jupyter-core==4.7.1
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.0

(jax) > $ pip freeze | grep notebook
notebook==6.3.0
```
Also, yes, I'm using the classic notebook.

**Comment by bryevdv** [comment] 2021-05-12 03:32
> difference is that I create glyphs after the handle is created.

@uduse that was the missing observation. This is a known still-open bug, a dupe of https://github.com/bokeh/bokeh/issues/8244 (so closing this here)

**Closed by bryevdv** 2021-05-12 03:32 UTC
Labels: TRIAGE
