### ISSUE TITLE
Blurry rendering near edge on Internet Explorer 

### ISSUE THREAD

**Issue by Jacob-Barhak** [bokeh/bokeh#7001] opened 2017-10-02 21:44 UTC
Below is sample code to regenerate the problem and an image that got generated using this on Windows 7  - When I use internet explorer 11.  The image should show a bunch or small circles near the edge.

I run into the problem you see in the image  - it is blurry and gridlines seem to be broken and blended - it happens only when the circles are drawn close to the edge and only when there are many categories - then the circles become blurry. The problem does not exist on firefox or chrome. I use bokeh 0.12.6 and Python 2.7.11 |Anaconda 2.4.1 (64-bit) . 

Here is the code to generate the html file to view.

```
from __future__ import division 
from bokeh.plotting import figure

from bokeh.resources import CDN

from bokeh.embed import file_html

from bokeh.models import Range1d



Plot = figure(title = 'Title', x_axis_label = 'TitleX', y_axis_label = 'TitleY', tools='save', x_range = [str(Entry) for Entry in range(40)], y_range = Range1d(-0.1, 1.1))

Plot.xaxis.major_label_orientation = "vertical"

Vec = [Entry/100 for Entry in range(50,60)] 

Plot.circle(x = ['39']*len(Vec), y = Vec , fill_color = 'green', line_color="green", size = 1)

Plot.circle(x = ['39'], y = [0.55] , fill_color = 'black', line_color='black', size = 3)



Html = file_html(Plot, CDN, 'my plot')

OutFile = open('PlotTest.html','w')

OutFile.write(Html)

OutFile.close()


```

Here is an image that shows how this looks in the browser. 

![bokeh_plot](https://user-images.githubusercontent.com/1986155/31100634-dd8843e0-a78f-11e7-9840-06d5c138adf4.png)

Hopefully there is sufficient information here to reproduce and solve this.

**Comment by bryevdv** [comment] 2017-10-03 00:48
@Jacob-Barhak can you confirm if this is a problem with the latest bokeh version `0.12.9`? I cannot reproduce the problem on Win10 with IE11 and your script:

<img width="471" alt="screen shot 2017-10-02 at 19 46 47" src="https://user-images.githubusercontent.com/1078448/31105538-8b5e128c-a7aa-11e7-8008-43eae3d7f94b.png">

If the problem is fixed in newer versions then the only remedy I can offer is to upgrade.

**Comment by Jacob-Barhak** [comment] 2017-10-03 02:08
Sorry Bryan,

The latest version that installed on my machine is 0.12.7. I tried it with that version and the problem still persists.

I can try and spin a VM with Windows 10 to try to isolate this issue to a specific version. Yet I also suspect specific hardware issues. I solved this problem locally by adding blank columns to get the circles away from the edge. So this is not a critical issue. 

Unless someone else complains, you should not give it any further attention - especially since you cannot replicate it with higher windows version.

**Comment by bryevdv** [comment] 2017-10-03 02:49
@Jacob-Barhak The latest version is `0.12.9` not `0.12.7`

**Comment by bryevdv** [comment] 2017-10-03 02:57
Also worth nothing, after all the new categorical re-work:

https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html

The `FactorRange` now supports a few different kinds of padding, including at the ends

**Comment by Jacob-Barhak** [comment] 2017-10-03 03:43
Sorry Bryan,

Version 0.12.9 does not solve the issue on my machine. It may be specific to my configuration, so I will not bother any further. And the examples in the link you sent me are very nice. I wish I saw them earlier.

**Comment by bryevdv** [comment] 2017-10-03 15:43
OK, as there are workarounds, and as the problem is only exhibited on fairly old (at this point) OSes, I will mark as `wontfix` as you suggest. Thanks @Jacob-Barhak

**Closed by bryevdv** 2017-10-03 15:43 UTC

**Comment by mattpap** [comment] 2017-10-03 17:40
Just to note, there are major differences in behavior between different versions of IE11 as time progresses, so it's not uncommon that our code works in newer versions of IE11 (which correlates with newer versions of Windows) and doesn't in older. Keeping IE up-to-date may help, but certain changes may not be available on older platforms.

**Comment by Jacob-Barhak** [comment] 2017-10-03 20:33
So Mateusz,

To be very exact, the IE problematic version is: 11.0.9600.18792
Update Versions: 11.0.46
On windows 7

Microsoft replaced IE with Edge as a default browser on Windows 10 and there are many work abounds to avoid the issue that we documented here, so I think the wont fix tag is ok.

Lets leave this issue alone and hope it does not resurface.
