### ISSUE TITLE
Show a loading spinner while the charts are being loaded for the first time?

### ISSUE THREAD

**Issue by GildedHonour** [bokeh/bokeh#2150] opened 2015-04-06 04:46 UTC
Is there any way to show Loading Spinner while the charts are being on the page for the first time? Can I subscribe to the events 'begin" and "done" like I'd do if it were the plain javascript + ajax? Simple "document.ready" doesn't work.

**Comment by GildedHonour** [comment] 2015-04-07 01:02
Or rather, catch the event when the chart is loaded on the client? Doing this:

```
$('.bk-plot-wrapper').ready(function() {
       //Loaded!
      });
```

doesn't help because the chart isn't loaded yet when "bk-plot-wrapper" is.

**Comment by GildedHonour** [comment] 2015-04-10 06:05
Up

**Comment by bryevdv** [comment] 2015-04-14 02:41
Sorry, I was away on vacation. This would be a great feature, which has occurred to us in the past but never been captured in the issue tracker. I have re-labeled it as such. I have to focus on docs and an updated tutorial before an upcoming conference so I doubt I will be able to look at it this month. If you are proficient in JS I would be more than happy to help/answer questions if you were interested in working up a PR.

**Comment by GildedHonour** [comment] 2015-04-14 05:04
@bryevdv Maybe you know a an answer for this. I have a Django template and in it I have this:

```
<script>
    window._bokeh_onload_callbacks = [window.{{dash_name}}.main];
......
</script>
```

It sends an ajax request. Is there any easy way to show an ajax spinner during the ajax request? How to catch the beginning and end of it?

**Comment by GildedHonour** [comment] 2015-04-15 05:13
@bryevdv up

**Comment by bryevdv** [comment] 2015-04-16 14:46
Hi @GildedHonour just FYI "up" is not a terribly respectful way to attempt to grab someone's attention. In any case I am afraid I do not know the answer to the AJAX question.

**Comment by GildedHonour** [comment] 2015-04-16 15:42
Perhaps ignoring someone is.

**Comment by bryevdv** [comment] 2015-04-16 16:07
@GildedHonour Seriously? It is now at the point that I could spend all day, every day, just interacting with the community, and still not be able to completely address and answer the volume of questions and issues that are now coming in. That is obviously a good problem to have! But it is problem, nonetheless. I am not happy that we don't have the ability to offer complete snap responses to everyone, all the time. I truly wish that we could, but the reality of the situation is dictated by limited time and resources being competed for on many, many fronts. Maybe you should try considering that context before you accuse someone of willfully ignoring you.

**Comment by GildedHonour** [comment] 2015-04-16 16:12
Sorry then.

**Comment by bryevdv** [comment] 2015-04-16 16:18
To be completely clear: I very much appreciate input and contributions from *everyone* and I am grateful for this suggestion and this issue and your input. We probably won't get to it as soon as you'd like (I wish we could!) but we will get to it. Thanks.

**Comment by bryevdv** [comment] 2017-04-05 04:18
This is a dupe of #4272 although this issue is older, the other has more relevant current info.

**Closed by bryevdv** 2017-04-05 04:18 UTC
Labels: tag: component: server, type: feature
