### ISSUE TITLE
Slider callback doesn't occur on particular values

### ISSUE THREAD

**Issue by ivan-usov** [bokeh/bokeh#7250] opened 2017-11-25 21:47 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh/0.12.10 and bokeh/0.12.11rc2
Chrome/62.0.3202.94 and Firefox/57.0

#### Description of expected behavior and the observed behavior
A registered slider callback isn't executed on particular slider values

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import curdoc
from bokeh.models import Slider

def slider_test_callback(attr, old, new):
    print(new)

slider_test = Slider(start=0, end=9, value=0, step=1, title="Test")
slider_test.on_change('value', slider_test_callback)

curdoc().add_root(slider_test)
```

#### Stack traceback and/or browser JavaScript console output
Stopping on every value, while moving the slider left to right all the way, produces the following output in a console (note missing 3 and 6):
```
1
2
4
5
7
8
9
```

However, changing a number of possible slider values either to 9 (```end=8```), or to 11 (```end=10```) makes a slider to work correctly. Also, switching to floating point values, e.g. ```start=0, end=0.9, value=0, step=0.1``` works fine:
```
0.1
0.2
0.3
0.4
0.5
0.6
0.7
0.8
0.9
```

**Comment by p-himik** [comment] 2017-11-26 12:19
The root cause of the problem is how noUiSlider (it's used by Bokeh's `Slider` internally) calculates changes. Even if you provide it only integers, it still does some complex floating-point calculations based on percentages. In this case, where you should receive `3`, you receive `2.9999999999999996` or something like that. noUiSliders handles this by fixing the number in the labels, but the internal value is still this one.

The only thing that Bokeh does on top of that, is convert the value to an integer when `start`, `end`, and `step` are all integers. The problem here is that it does it by using `value | 0` which does not round the value but trims it.
I'd argue that it's the issue with noUiSlider, but it also can be fixed in Bokeh by just using `Math.round(value)` instead of `value | 0`.

**Comment by ivan-usov** [comment] 2017-11-26 16:34
Indeed, having consistency between slider labels and actual values is something one would expect.
+1 for this PR

**Closed** 2017-11-27 15:42 UTC
