### ISSUE TITLE
[BUG] WebGL regressions when setting alpha as an iterable

### ISSUE THREAD

**Issue by Haptein** [bokeh/bokeh#11217] opened 2021-04-28 04:08 UTC
I've noticed some performance and visual regressions since bokeh 2.3.0 when using WebGL as output backend. There seems to be alpha artifacts when passing alpha as an array (or as one in a ColumnDataSource) instead of a float. 

Reproduction code:
```
from bokeh.plotting import figure
from bokeh.layouts import row
from bokeh.io import show
import numpy as np

n = 1000
x = np.random.randn(n)
y = np.random.randn(n)
alpha = np.ones_like(x) * 0.8

fig1 = figure(output_backend="webgl")
fig2 = figure(output_backend="webgl")

fig1.scatter(x=x, y=y, alpha=alpha, marker='circle')
fig2.scatter(x=x, y=y, alpha=alpha[0], marker='circle')

show(row([fig1, fig2]))
```

Displaying the figures of this code (with n=100000) is an order of magnitude slower (~56s) than in 2.2.3 (~5s).

Testing setup info:
bokeh 2.3.0 & 2.3.1
Python 3.7.10
Chromium 90.0.4430.85 (Official Build)
Firefox 88.0 (64-bit)
CPU 9750h
OS Manjaro

**Comment by ianthomas23** [comment] 2021-04-28 07:08
There has been a lot of work done on the WebGL backend since 2.3.0 which has essentially involved a complete rewrite of the previous line and marker renderers. The plan is to extend WebGL coverage to all of our glyphs.  We have been concentrating on the correct visual appearance and getting our internal API right before improving the performance.  The work proceeds as fast as part-time volunteer contributions permit.  If you can bear with us, you can expect significant improvement in WebGL quality, coverage and performance over the next few months.

There are already some open issues about WebGL (#11050, #11051, #11052, #11053).  The performance issue is due to unnecessarily sending too much data from CPU to GPU, and is item 5 of issue #11052, so this is near the top of my todo list.

**Comment by Haptein** [comment] 2021-04-28 21:45
I'm honestly in no hurry to upgrade, I just thought I'd report the issue in case this had gone unperceived.

I'm aware of the work going with WebGL, thank you :smiling_face_with_three_hearts:  ! These developments sure make me excited for the future versions of bokeh.

**Comment by ianthomas23** [comment] 2021-04-29 10:18
> I'm aware of the work going with WebGL, thank you :smiling_face_with_three_hearts: ! These developments sure make me excited for the future versions of bokeh.

Always happy to receive positive feedback! :grin:

**Comment by bryevdv** [comment] 2021-08-11 15:26
@ianthomas23 we are looking at early Septembed for 2.4 release, should be move this issue to the `next` milestone?

**Comment by ianthomas23** [comment] 2021-08-11 15:59
@bryevdv I think this was fixed by #11277.  I'll check and report back, probably tomorrow.

**Comment by ianthomas23** [comment] 2021-08-12 16:15
I've confirmed this is fixed.  With Bokeh 2.3.1 and `n=100000` on Firefox 91.0 it takes ~34 s and the left-hand figure looks hideous.  On `branch-2.4` (commit 24a21c17) it takes 2.5 s and looks like this:
![Screenshot 2021-08-12 at 17-07-35 Bokeh Plot](https://user-images.githubusercontent.com/580326/129230931-f43ddc0c-c4d2-48ee-8c90-9b8470067e7d.png)

**Closed by ianthomas23** 2021-08-12 16:15 UTC
Labels: type: bug, tag: regression, tag: webgl

**Comment by bryevdv** [comment] 2021-08-12 16:23
Thanks @ianthomas23 !
