### ISSUE TITLE
Autocomplete widget value attribute does not reflect selected value , display entered value 

### ISSUE THREAD

**Issue by internshipdeco** [bokeh/bokeh#8886] opened 2019-05-02 17:58 UTC
Already have some discussion in #8877

bokeh info :
Python version : 3.6.7 (v3.6.7:6ec5cf24b7, Oct 20 2018, 12:45:02) [MSC v.1900 32 bit (Intel)]
IPython version : (not installed)
Tornado version : 6.0.2
Bokeh version : 1.1.0
BokehJS static path : C:\Users\shrikrishna_y\PycharmProjects\CaptialChart\venv\lib\site-packages\bokeh\server\static
node.js version : (not installed)
npm version : (not installed)

on_change('value', myfunc) does not seem to get triggered when you try to use autocompletion options. If you type what you want directly without using the arrow keys and then press enter, on_change triggers successfully.

from bokeh.models.widgets.inputs import AutocompleteInput
from bokeh.io import curdoc, show
def my_text_input_handler(attr, old, new):
print("Updated label: " + text_input.value)
text_input = AutocompleteInput()
text_input.completions = ["hello","good","target","helpful"]
text_input.on_change("value", my_text_input_handler)
curdoc().add_root(text_input)

hope all this information is enough

**Comment by bryevdv** [comment] 2019-05-03 21:53
This is a duplicate of  #8828 which was closed in #8829 and will be part of the 1.1.1 release

**Closed by bryevdv** 2019-05-03 21:53 UTC
Labels: TRIAGE
