### ISSUE TITLE
[BUG] [2.4.3] Plot glitches when using LabelSet in a bar chart

### ISSUE THREAD

**Issue by jandmeijer** [bokeh/bokeh#12189] opened 2022-06-22 11:52 UTC
### Software versions

Python version      :  3.8.12 (default, Oct 12 2021, 03:01:40) [MSC v.1916 64 bit (AMD64)]
IPython version     :  8.4.0
Tornado version     :  6.1
Bokeh version       :  2.4.3
BokehJS static path :  C:\miniconda2\envs\py38\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

Microsoft Edge, Chrome

### Jupyter notebook / Jupyter Lab version

N/A

### Expected behavior

I'm trying to add labels to my bar chart using LabelSet. I have tried this with my own data, and when that did not work, with an example snippet of code from [StackOverflow](https://stackoverflow.com/questions/64128183/bokeh-labels-dont-render-if-x-axis-values-are-categorical-after-version-update). (The example is slightly dated, using Bokeh 2.2.1.)

What is expected is the chart as provided in the post. A bar chart with labels at the top of each bar.

![image](https://user-images.githubusercontent.com/107999259/175021257-e7056fce-b7d1-43b8-bee0-4d8979e0f471.png)

### Observed behavior

However, both in my own case, and when using the example case, the chart is not rendered correctly and glitches out when interacted with. There is no output in the terminal.

![image](https://user-images.githubusercontent.com/107999259/175021372-6f21066b-1ea9-4608-9b00-a3e300e015f7.png)
![image](https://user-images.githubusercontent.com/107999259/175021398-d241813c-ffb8-433b-91a0-9eb7df7d7df8.png)

When commenting out the LabelSet attribute the problem is resolved, but obviously the labels are not rendered.

`#p.add_layout(labels)`

![image](https://user-images.githubusercontent.com/107999259/175021639-3b965212-11a0-4f65-94f5-e5682d28269a.png)

When leaving LabelSet but removing its contents, the issue partially remains (x-axis labels become visible but it still glitches out).

```
labels = LabelSet(
  #x='index', 
  #y='Sales', 
  #text='Sales', 
  #source=ds, 
  #level='glyph',
  #x_offset=5, 
  #y_offset=5, 
  #render_mode='canvas'
  )

p.add_layout(labels)
```

![image](https://user-images.githubusercontent.com/107999259/175022041-97aa7fcc-9388-4f91-9d90-413d85cacf20.png)
![image](https://user-images.githubusercontent.com/107999259/175021962-9c4c5099-2dba-45a0-9628-c7719a95d031.png)

When trying out a different example code snippet, the one on [the official Bokeh website](https://docs.bokeh.org/en/latest/docs/user_guide/annotations.html#labels), this problem does not arise. However, that is a scatter plot and not a bar chart.

```
from bokeh.models import ColumnDataSource, Label, LabelSet, Range1d
from bokeh.plotting import figure, output_file, show

output_file("label.html", title="label.py example")

source = ColumnDataSource(data=dict(height=[66, 71, 72, 68, 58, 62],
                                    weight=[165, 189, 220, 141, 260, 174],
                                    names=['Mark', 'Amir', 'Matt', 'Greg',
                                           'Owen', 'Juan']))

p = figure(title='Dist. of 10th Grade Students at Lee High',
           x_range=Range1d(140, 275))
p.scatter(x='weight', y='height', size=8, source=source)
p.xaxis[0].axis_label = 'Weight (lbs)'
p.yaxis[0].axis_label = 'Height (in)'

labels = LabelSet(x='weight', y='height', text='names',
              x_offset=5, y_offset=5, source=source, render_mode='canvas')

citation = Label(x=70, y=70, x_units='screen', y_units='screen',
                 text='Collected by Luke C. 2016-04-01', render_mode='css',
                 border_line_color='black', border_line_alpha=1.0,
                 background_fill_color='white', background_fill_alpha=1.0)

p.add_layout(labels)
p.add_layout(citation)

show(p)
```

![image](https://user-images.githubusercontent.com/107999259/175022402-f8d73107-fb29-4c63-80c1-2003d4eb18b7.png)

### Example code

```Python
import pandas as pd
from bokeh.models import LabelSet, ColumnDataSource, Range1d
from bokeh.plotting import figure, show, output_file

output_file("label.html", title="label.py example")

vals = pd.DataFrame({'weekday': ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                     'Sales': [15, 25, 36, 17, 4],
                     'index' : range(5)}
                   )

ds = ColumnDataSource(vals)

# extend the y-range a bit more to give space to top label
p = figure(y_range=Range1d(0, 42), x_range=vals['weekday'], height=300)
p.vbar(x='weekday', width=0.75, top='Sales', source=ds)

labels = LabelSet(x='index', y='Sales', text='Sales', source=ds, 
                  level='glyph',
                  x_offset=5, 
                  y_offset=5, 
                  render_mode='canvas')

p.add_layout(labels)

show(p)
```

**Comment by bryevdv** [comment] 2022-06-22 14:57
dupe of https://github.com/bokeh/bokeh/issues/12127

**Closed** 2022-06-22 14:57 UTC
Labels: reso: duplicate, type: discussion
