### ISSUE TITLE
DEFAULT_HELP_URL for HelpTool redirect

### ISSUE THREAD

**Issue by nathanielatom** [bokeh/bokeh#6201] opened 2017-04-27 00:04 UTC
Hi, we are sending reports out to non-technical users, and the default `HelpTool` redirects to 
http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html, which starts out with some code for developers creating the plots. 

For our reports we changed the link to http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#built-in-tools since it has excellent descriptions of how to use the tools themselves, even for reasonably non-technical users.

Thought others may find this useful as well, as the `DEFAULT_HELP_URL`.

**Comment by bryevdv** [comment] 2017-05-01 17:13
I'm going to close this as a dupe of #5430 

@nathanielatom if you'd like to submit a PR to change the default URL, it would be accepted.

**Closed by bryevdv** 2017-05-01 17:13 UTC

**Comment by nathanielatom** [comment] 2017-05-01 18:00
Sorry! I searched through the issues, but clearly my github search fu needs improvement. I'll make a PR referencing the pre-existing issue.
