### ISSUE TITLE
Table of contents is not scrolling properly on Bokeh website

### ISSUE THREAD

**Issue by nasedil** [bokeh/bokeh#3069] opened 2015-11-05 12:25 UTC
The table of contents on the left on the Bokeh website user guide (for example here: http://bokeh.pydata.org/en/0.10.0/docs/user_guide/styling.html ) cannot be scrolled independently of content.  It only scrolls at the bottom, together with content.  So when the table of contents is larger than browser height it is not possible to navigate to headers at the bottom part of the table of contents.
![toc-scrolling-trouble](https://cloud.githubusercontent.com/assets/3921196/10968204/fbff6006-83bf-11e5-8b9f-b37caba7b348.png)

**Comment by bryevdv** [comment] 2015-11-05 12:54
This is already fixed on master.

**Comment by bryevdv** [comment] 2015-11-05 14:04
(And it was was early and I was on my phone, o forgot to add: thank you for the report!)

**Comment by bryevdv** [comment] 2015-11-05 15:16
My apologies, this change got lost in the shuffle somewhere, I don't see it where I expected too. Just FYI we will be having a `0.11` release, around the end of the month. I'm not sure we will have a chance to re-deploy the existing docs with a patch to fix this before then, I'll be traveling for a few conferences. But there are dev doc available at http://bokeh.pydata.org/en/dev/index.html and these will be updated with this change soon.

**Comment by bryevdv** [comment] 2015-11-05 15:20
Hrmm, curious... this change is in master:

https://github.com/bokeh/bokeh/blob/master/sphinx/source/conf.py#L165

When I build locally, the TOC behaves well, as expected. But in the latest deployed dev docs, it still behaves badly. Maybe this is a sphinx theme problem. I'm not sure it will require some investigation.

**Comment by bryevdv** [comment] 2015-11-05 15:24
ping @bokeh/dev any ideas here from CSS or sphinx experts? The deployed TOC behaviour is pretty annoying, but I am not sure how to fix it since it works locally. Another option is to punt, and to reduce TOC depth to reduce the chance that it is too long

**Comment by damianavila** [comment] 2015-11-05 16:11
Can you specify all the sphinx related things in you local environments, so we can compare with things used by the build and try to isolate the discrepancy...

**Comment by bryevdv** [comment] 2016-01-27 03:51
confirmed this is fixed on new style deployed docs

**Closed by bryevdv** 2016-01-27 03:51 UTC
Labels: reso: completed, tag: docs, type: bug
