### ISSUE TITLE
Ray angle is wrong

### ISSUE THREAD

**Issue by aunderwood** [bokeh/bokeh#5173] opened 2016-09-15 22:00 UTC
Creating a ray with angle pi/4 radians or 45 degrees starting at point (0,0) should pass through the points (1,1), (2,2), etc. 

Bokeh version 0.12.2
Python version 3.5.1+
Browsers: Chromium Version 52.0.2743.116 Built on Ubuntu , running on Ubuntu 16.04
Firefox 48.0
Example:
```python
from math import pi
from bokeh.plotting import figure, output_file, show
p = figure()
p.ray(0, 0, angle=pi/4, length=0)
output_file('ray.html')
show(p)
```
![image](https://cloud.githubusercontent.com/assets/10430201/18569007/be7d8b56-7b65-11e6-8945-66a2161aed34.png)

**Comment by bryevdv** [comment] 2016-09-15 22:27
dupe of #517 

@aunderwood the problem is not the angle, the problem is that the aspect ratios between the data dimensions and pixel dimensions do not match. Or in other words, the "central" plot area is note square, even though the data x-y bound are equal. That's a fundamental mathematical issue, there's nothing to do about this except find a way to force the aspect ratios to be equal. Right now this has to be done fairly manually, by manipulating `min_border`, etc. and possibly rotating axis labels so that they take up less space. There is an open issue for being able to control aspect ratios more easily.

**Closed by bryevdv** 2016-09-15 22:27 UTC

**Comment by bjfar** [comment] 2024-03-14 22:31
Is this really a dupe? I would expect rays to be drawn in data space, not screen space. Was that an unreasonable expectation? I'm not sure why one would ever want rays directly in screen space. Anyway the docs don't say either way what to expect.

**Comment by bryevdv** [comment] 2024-03-14 23:37
@bjfar It's not clear what you expect. A 45 degree angle is a 45 degree angle. There is no "data space" or "screen space" to consider in that determination. But if the the aspect ratios do not match, then making the "45 degree angle ray" go to (1, 1) necessarily means drawing it at something that is absolutely not a 45 degree angle on the screen, which seems purely confusing and undesirable. 

If you are using rays, or *anything* that relies on radial measures really, then you almost certainly want to be using a matched aspect. Conversely if you really want or need unequal scales on different axes that result in unmatched aspects, then you should be drawing using explicit coordinates.

**Comment by bryevdv** [comment] 2024-03-14 23:53
In any event the current docs do describe *to me* exactly what is happening in a way that matches my expectations. So I am not sure in what way they could or should be edited for improvement. But in case you'd like to submit a PR with phrasing that makes more sense or seems more complete to you, the relevant location is here:

https://github.com/bokeh/bokeh/blob/96402185b08ef9313c70da5f88cb0327144acfbe/src/bokeh/models/glyphs.py#L1273-L1275

**Comment by bjfar** [comment] 2024-03-15 02:25
> @bjfar It's not clear what you expect. A 45 degree angle is a 45 degree angle. There is no "data space" or "screen space" to consider in that determination. But if the the aspect ratios do not match, then making the "45 degree angle ray" go to (1, 1) necessarily means drawing it at something that is absolutely not a 45 degree angle on the screen, which seems purely confusing and undesirable.

Yes there is, there is a cartesian coordinate system underlying the plot (assuming the axes aren't log scale; that would complicate things), you use it to specify the origin of the rays. I'd expect the ray angle to be computed according to that same coordinate system, not according to the screen pixel coordinates, which is entirely different. This appears to be what the OP expected also.

> If you are using rays, or anything that relies on radial measures really, then you almost certainly want to be using a matched aspect. 

I mean probably, but getting the pixel aspect ratio to perfectly match the data aspect ratio in bokeh is really a pain, in fact I have so far failed to get it to work perfectly. And in such cases it is usually more important that the ray angles match the underlying data from which they are computed rather than some arbitrary angles on the screen.

I suppose it depends why you are drawing the ray. If you are drawing the ray as part of some data visualisation then you are going to expect it to be in coordinates that match the data. But if you are drawing it for some other graphical sort of reason then you may reasonably be thinking about it in screen space. Some kind of argument to switch between either behaviour would be best.

I guess other Bokeh glpyhs also have this problem. Like if I draw circles as plot markers or something then I probably expect them to stay as circles regardless of aspect ratio, while if I am actually drawing circles with respect to my data then I would want the circles to deform to ellipses etc as the plot aspect ratio changes.

I mean it is not such a big deal, if I really want data-space rays I can draw lines using multi_line or some such, but I was quite surprised to find that Ray doesn't work like this.

> Conversely if you really want or need unequal scales on different axes that result in unmatched aspects, then you should be drawing using explicit coordinates.

Why? Angles are a perfectly valid part of a data coordinate system. theta = arctan(deltay / deltax).

Edit: yes this seems to be a general/fundamental problem with Bokeh glyphs:
 - https://stackoverflow.com/questions/61877110/how-to-plot-an-ellipse-with-bokeh-and-a-correct-orientation-angle
 - https://github.com/bokeh/bokeh/issues/7965
 - https://discourse.bokeh.org/t/ellipse-at-angle-buggy/9413/9
