### ISSUE TITLE
Feature: Hover Tool Inspector Default

### ISSUE THREAD

**Issue by crashMOGWAI** [bokeh/bokeh#5599] opened 2016-12-21 17:01 UTC
Need ability to set default behavior for hover tool inspector, currently it is always on. 
![capture](https://cloud.githubusercontent.com/assets/17650526/21397798/bcf11068-c76a-11e6-9d6c-d83202f3ea20.PNG)

Wanted to capture this, since I've seen it in group messages a handful of times now. I can see this being an issue where lots of meta is pushed to overlapping inspectors when exploring data. There is potential for the browser script to lag. @bryevdv Maybe combine with #5497 efforts?

**Comment by bryevdv** [comment] 2016-12-21 17:11
@crashMOGWAI I think these two issues probably deserver independent PRs, as they are somewhat orthogonal concerns. Hopefully not too difficult to extend the default activation to hover like tools in any case.

**Comment by timsnyder** [comment] 2017-04-03 13:00
Note,  #6004 was closed as a duplicate of this issue.

**Closed** 2017-04-20 02:52 UTC
Labels: tag: component: bokehjs, type: feature
