### ISSUE TITLE
Redirect from `/` to `/app_name`

### ISSUE THREAD

**Issue by danielfrg** [bokeh/bokeh#4412] opened 2016-05-31 18:53 UTC
In most cases I found myself just wanting to run one single bokeh server app like: `bokeh serve main.py`
This will host the app at: `localhost:8080/main` leaving `localhost` with a 404.

I think the root path (`/`) should redirect to the bokeh app path if there is only one bokeh app and if they are multiple maybe list all the possible applications with some links.

The jupyter notebook does something similar redirecting from `/` to `/tree`. See: https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L307-L313

**Comment by bryevdv** [comment] 2016-05-31 19:15
Hrm, I was about to mark this as a dupe of #322 but I think perhaps the intent has diverged. This seems like a reasonable feature, @danielfrg do you have any interest in working on this? It would be only be pure-python development, and fairly isolated in scope.

**Comment by bryevdv** [comment] 2016-06-02 16:38
Basic functionality added, follow on in #4425 to refine

**Closed** 2016-06-02 16:38 UTC
Labels: tag: component: server, tag: starter, type: feature
