### ISSUE TITLE
Add values to figure according to categorical y-axis

### ISSUE THREAD

**Issue by burmeisc** [bokeh/bokeh#5867] opened 2017-02-14 11:54 UTC
Adding glyphs to a figure by refering to a categorical axis works using:

```
  from bokeh.plotting import figure, output_file, show 
  factors = ["a", "b", "c", "d", "e", "f", "g", "h"]
  x = [50, 40, 65, 10, 25, 37, 80, 60]
  output_file("categorical.html")
  p = figure(y_range=factors)
  p.circle(x, factors, size=15, fill_color="orange", line_color="green", line_width=3)
  show(p) 

```
But when I try to add glyphs on specific coordinates, e.g. a triangle at (50,a), with the following code
```
  from bokeh.plotting import figure, output_file, show 
  factors = ["a", "b", "c", "d", "e", "f", "g", "h"]
  x = [50, 40, 65, 10, 25, 37, 80, 60]
  output_file("categorical.html")
  p = figure(y_range=factors)

  p.triangle(x=50, y = value(a))

  show(p)
```
It produces the following error:

> Number property 'y' given invalid value: a

**Comment by canavandl** [comment] 2017-05-31 12:36
To clarify:

in Bokeh 0.12.6dev6

```python
from bokeh.plotting import figure, show

factors = ["a", "b", "c", "d", "e", "f", "g", "h"]
x = [50, 40, 65, 10, 25, 37, 80, 60]

p = figure(y_range=factors)
p.triangle(x={"value": 50}, y={"value": "a"}) # setting x this way is ok, setting y doesn't

show(p)
```

Adding numeric values (like 50) works but adding categorical values (like "a") doesn't. You can add the 1 + index of the categorical value (so 1 for "a") but that's more of a side effect that desired solution.

Throws a NumberSpec error:

<img width="500" alt="screen shot 2017-05-31 at 9 32 14 am" src="https://cloud.githubusercontent.com/assets/2198981/26632005/395cebd4-45e4-11e7-87ff-38f05ac84b04.png">

**Comment by bryevdv** [comment] 2017-06-04 19:03
Right so this code in `glyph.coffee` is certainly the culprit:
```
    for [x, y] in coords
      result[x] = [ p.NumberSpec ]
      result[y] = [ p.NumberSpec ]

```
That is why putting categorical coords in a column in s CDS works (`Spec` always accepts a column name as valid) but a single value does not (validation is a against `Number`) 

So the workaround for now is to just put all categorical coords in CDS columns. This can be accomplished my creating a CDS by hand, or by passing lists, e.g. like this:
```
from bokeh.plotting import figure, show

factors = ["a", "b", "c", "d", "e", "f", "g", "h"]
x = [50, 40, 65, 10, 25, 37, 80, 60]

p = figure(y_range=factors)
p.triangle(x=[50], y=["a"])

show(p)
```
Given that there is a workaround, and also given tat to really fix, this intersects with some larger categorical refactor work, I'm moving to the next milestone.

**Comment by bryevdv** [comment] 2019-03-09 05:50
#6660 is a dupe of this one but I will leave the newer issue open

**Closed by bryevdv** 2019-03-09 05:50 UTC
Labels: tag: component: bokehjs, type: bug
