### ISSUE TITLE
Reference Guide completeness

### ISSUE THREAD

**Issue by jhdedrick** [bokeh/bokeh#7358] opened 2017-12-31 23:18 UTC
This issue is with regard to documentation, specifically the Reference Guide located at http://bokeh.pydata.org/en/latest/docs/reference/

As a new user trying to build a somewhat nontrivial visualization, I'm heavily dependent on the reference guide.  I'm finding that in many cases it's very incomplete and thought a noob's perspective might be helpful.

Unlike User Guides/Tutorials, the "Reference" section of product documentation should be complete and self contained, should specify legal syntax, enumerate all legal parameters/values and their effects, and should generally not depend on examples in lieu of explicit statements.  An example of a really good reference guide IMO is the Python standard library doc tree.  See e.g. https://docs.python.org/3/library/stdtypes.html#dict

By this standard http://bokeh.pydata.org/en/latest/docs/reference/ as currently constructed isn't really a reference guide.  The entries generally do not give legal syntax, and often just link to base classes which do not list the available elements of the class, and do not describe their behavior or options.  A couple of examples are below, but the comment applies to virtually all entries.

Figure/x_axis_type 	(Either ( Auto , Enum ( Enumeration(linear, log, datetime) ) )) :  The type of the x-axis. (default: ‘auto’)

"Enum" links to the base class for Enum, which in turn links to bokeh.core.enums.  While the general meaning of linear, log, and datetime are obvious, many questions remain unanswered, e.g.:
• What kind of axis will be used if "auto" is chosen, and how is that decision made?
• Bokeh handles categorical axes, but there's no mention of that here.  Why?  How do I specify a categorical axis?
• Does this parameter have to be a bokeh "enum" object, or can it be just a string?  What is the syntax?

Figure/x_range (Any ) :	Customize the x-range of the plot. (default: None)	
This is a tautology - it gives no information about what customizations are available and how to specify them.  Also doesn't say what happens in the default case.

Thanks,
-J

**Comment by bryevdv** [comment] 2018-01-01 01:10
A few prefatory words:

Bokeh is actually a cross-language, cross-runtime, cross-library project. Apart from `bokeh.server`, almost no actual work is done in python. All the work is done in the browser, by a JavaScript library BokehJS. The input to BokehJS is a "pile of JSON", really a bunch of nested dicts, that declaratively describe the visualization or app to create. For every dict in the "pile of JSON" there is a corresponding Python object (called a `Model`). The job of the python library is to:

* help ensure that individual model properties only get set to valid types (otherwise errors don't up until something goes wrong in the browser which can be incredibly obscure) 

* help ensure that collections of models are assembled in valid and meaningful ways. (again, so that errors show up in *python* instead of hidden in a browser JS console)

To this end we have our own "manifest typing" system (similar to traits, traitlets, Param, Struct, etc...) that is specific to Bokeh, that does:

* type validation of all properties on all models
* proper serialization for BokehJS
* integrate directly into automated documentation via per-property help strings.

I am sure that the help strings can be expanded up on in many cases, and in fact trying to find time to devote to just this has been on my mind recently. That said:

> The entries generally do not give legal syntax

For model properties, which is the vast bulk of what the reference guide will document, the syntax is always exactly the same: standard python assignment, e.g. `plot.title.text = "some title"`. There are (I would estimate) several thousand properties, and explicitly stating for every one that the intended use is to assign to them would bloat the reference so much as to impede comprehensibility, in my opinion. What is much more useful and valuable to convey is the answer to the question: *what are the **valid values** that can be assigned?* In some cases, especially and specifically enumerations, this might be a slightly convoluted. But:
 
* the vast majority of type values are much simple and intuitive (e.g. `Float`), and

* reference guides also have multiple audiences

The deep-dive links in the type descriptions are really there for either core developers of Bokeh, or for people developing custom extensions to Bokeh. As before, repeating the same statement that the type links are mostly a reference for that specific subset of people, thousands of times, would obscure the rest of the guide terribly. If you have an easily implementable organizational alternative I'd certainly be interested in hearing it. 

> By this standard http://bokeh.pydata.org/en/latest/docs/reference/ as currently constructed isn't really a reference guide. 

I'll just state that I don't think this is a fair assessment. In some cases, there is simply not much to say:

<img width="1010" alt="screen shot 2017-12-31 at 18 39 23" src="https://user-images.githubusercontent.com/1078448/34464882-fa23efe8-ee59-11e7-8907-d9bd69df3b3a.png">

I'm not sure what could be aded to those? They display the (much simpler but also much more typically simple) type (e.g. `Int`) And the descriptions, though brief, are complete. In other cases, there is enormous detail:

<img width="1206" alt="screen shot 2017-12-31 at 18 42 02" src="https://user-images.githubusercontent.com/1078448/34464888-6981b668-ee5a-11e7-9bce-67df697629e9.png">

I definitely appreciate that you have not been able to find some information that you have hoped to find, and that there are many help strings that could use improvement or expansion, but I think you have cherry picked a few examples and over generalized. 

---

I do definitely appreciate feedback from the "beginner mind" and regard it as valuable, so thank you for taking the time to express your thoughts. I will probably have more to say on this topic after some thought but I wanted to get initial thoughts out while they were fresh. I will say that part of the issue is the common OSS problem of far more work to do than people to do it, so given that you have strong and valuable opinions regarding documentation, I hope also that you might consider collaborating more directly to improve things.

**Comment by bryevdv** [comment] 2018-01-01 01:10
(also happy new year 🎊 )

**Comment by bryevdv** [comment] 2018-01-01 01:13
Also, in case your question about categorical axes was more than hypothetical, I'd direct you to the following resources:

https://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#categorical-axes

https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html (still missing intro section, on my todo...) 

https://bokeh.pydata.org/en/latest/docs/reference/models/ranges.html#bokeh.models.ranges.FactorRange

**Comment by jhdedrick** [comment] 2018-01-01 06:12
Bryan:

First, thanks for a rapid and thoughtful reply.
Second, thanks for the hard work you've put into a very capable graphics
package.

I'm on uncertain ground here - I'm very cognizant that complaining about
something that was freely given is gratuitous on the face of it. I persist
for two reasons:  First, our viewpoints remain very far apart, and I
believe it is in both our interest to understand why.  Second, bokeh
deserves both broad adoption and accolades, and both will be limited if
there are barriers to understanding it. I hope you'll forgive me for
pressing on..

I will take issue with a couple of conceptual points, and then (at the risk
of revealing myself as hopelessly uneducable) I'll try to give you a
"stream of consciousness" ride through a couple of the doc snippets you
included, as viewed through my eyes.

_________________________________________________________________
*"reference guides also have multiple audiences"*
No, they don't.  User guides do, and tutorials maybe.  But reference guides
are like (English language) dictionaries: They are not what you use to
learn English. They are not designed to be read from beginning to end. They
are a place where you go to find the answer to *one, specific, narrow
question*.

Corollaries of the above, (continuing the analogy to the English language
dictionary:)

   - The length of a dictionary doesn't impair its utility - the user isn't
   going to read it all - only a single entry.  But completeness matters a lot.
   - Repetitiveness is not a problem, for the same reason as above.
   - Each entry must be self contained, since you should assume it's the
   only part of the dictionary the user will ever read.
   - Organization matters a lot.  Being able to find the one, single thing
   you want to know quickly is a big deal.

_________________________________________________________________
For every [...] there is a corresponding Python object (called a Model).*
[...] *we have our own "manifest typing" system [...] that is specific to
Bokeh
Here is where risk losing 95% of potential users.
I'm trying to get something done in Python. I chose Bokeh based on the
premise that I can work in a familiar (sort of) tool, and I don't also have
to learn javascript and JSON. Constructs that are "our own", and "specific
to Bokeh" defeat that goal and IMO should be avoided at nearly any cost.
But if they're unavoidable they'd better be documented *incredibly* well.

Here's how Python documents methods of an object (in this case a string
object, named 'str'):
*str.index(sub[, start[, end]])*
Like find(), but raise ValueError when the substring is not found.
*str.isalnum()*
Return true if all characters in the string are alphanumeric and there is
at least one character, false otherwise. A character c is alphanumeric if
one of the following returns True: c.isalpha(), c.isdecimal(), c.isdigit(),
or c.isnumeric().
*str.isalpha()*
Return true if all characters in the string are alphabetic and there is at
least one character, false otherwise. Alphabetic characters are those
characters defined in the Unicode character database as “Letter”, i.e.,
those with general category property being one of “Lm”, “Lt”, “Lu”, “Ll”,
or “Lo”. Note that this is different from the “Alphabetic” property defined
in the Unicode Standard.

Note that they use the correct and complete syntax, str.method(), for *every
single one* of the dozens of methods applicable to string objects.

Bokeh OTOH lists properties, but doesn't show how they're used, nor explain
what they mean.
grid_line_alpha¶
<https://bokeh.pydata.org/en/latest/docs/reference/models/grids.html#bokeh.models.grids.Grid.grid_line_alpha>

*property type:* NumberSpec
<https://bokeh.pydata.org/en/latest/docs/reference/core/properties.html#bokeh.core.properties.NumberSpec>

The line alpha of the Grid lines.
*I'm not sure what could be added to those? They display the (much simpler
but also much more typically simple) type (e.g. Int) And the descriptions,
though brief, are complete.*

Really?

   - What is a NumberSpec?  Is that a bokeh-specific type or object?
   - Can I just use a float instead?
   - You imply above that an Int is admissible, but the alpha values I'm
   familiar with range from 0..1.  What is your definition of alpha?
   - What is its range?
   - Can I assign this property at creation of the grid (syntax?), or later
   (syntax?) or either?
   - What is the default?
   - Does grid_line_alpha apply to both horizontal and vertical grid lines?
   What if I want different alphas for each?
   - ...

The fact that you don't know what could be added means you know the code
really well, not that there's nothing left to add.  ;^)
_________________________________________________________________
Here is what I'm thinking as I read this:
class DatetimeTickFormatter(**kwargs)
Bases: bokeh.models.formatters.TickFormatter

A TickFormatter for displaying datetime values nicely across a range of
scales.
I'm vaguely familiar with pandas dataframes with time-valued indexes.  I
wonder if that's where datetime values have to come from, or if there's
some way to specify them directly...

DatetimeTickFormatter has the following properties (listed together with
their default values) that can be used to control the formatting of axis
ticks at different scales scales:

microseconds = ['%fus']   Hmmm.  this looks like a list containing a single
string.  Why a list?
milliseconds = ['%3Nms', '%S.%3Ns']  THese look vaguely like old-style
Python string formats.  I only use the new method - so I'll have to go look
up that syntax.  I wish this document either said explicitly that's what
these are, or said explicitly that they're something Bokeh specific...
seconds = ['%Ss']
minsec = [':%M:%S']
minutes = [':%M', '%Mm']

Each scale property can be set to format or list of formats to use for
formatting datetime tick values that fall in in that “time scale”. By
default, only the first format string passed for each time scale will be
used. OK, when would the others be used?  By default, all leading zeros are
stripped away from the formatted labels.
This list of supported *strftime *formats is reproduced below.  'strftime'?
This links to a LINUX man page. WTF?

_________________________________________________________________
Bryan, I regret that that's all the time I have - I hope it's been
helpful.  If I ever get to a state of knowledge where I think I could be
helpful, I'll consider taking you up on your challenge of helping to
improve the docs.

Happy New Year, and thanks again.
Joel

**Comment by bryevdv** [comment] 2018-01-01 16:46
Just as a heads up as to why I am closing this issue:

> Bryan, I regret that that's all the time I have - I hope it's been
helpful.  If I ever get to a state of knowledge where I think I could be
helpful, I'll consider taking you up on your challenge of helping to
improve the docs.

It is helpful, but discussions on GitHub should be *active*, or else they simply linger forever and become clutter on the tracker.  However, please feel free to re-open and continue this discussion at any point in the future when you do have time. 

---

> I chose Bokeh based on the premise that I can work in a familiar (sort of) tool, and I don't also have to learn javascript and JSON. Constructs that are "our own", and "specific
to Bokeh" defeat that goal and IMO should be avoided at nearly any cost.
But if they're unavoidable they'd better be documented *incredibly* well.

I was providing that additional detail *to you specifically*, because we are having this discussion here, on GitHub, and I assumed that a deeper explanation would be relevant and useful *here*, not because I believe that they are or need to be of interest to most users. 

FWIW we have by and large translated the problem of "make an interactive data vis app in a browser" down to "set properties on Python objects". And that is what most of the reference guide targets (but see below for some distinctions)

---
> No, they don't.  User guides do, and tutorials maybe.  But reference guides
are like (English language) dictionaries: They are not what you use to
learn English. They are not designed to be read from beginning to end. They
are a place where you go to find the answer to *one, specific, narrow
question*.

We definitely do disagree here. Continuing the analogy, there is not only one kind of English dictionary. A home dictionary and the complete OED are not at the same level of detail. The latter contains much more information about morphology and etymology and assumes background information, terminology, and theory that is probably not even familiar to the home dictionary user. I am suggesting that some of the information you have stumbled on falls into this latter category. I suppose the "proper" solution is to have both a *User Reference Guide* (analogous to home dictionary), and separate *Developer Reference Guide* (analogous to OED). We ten-thousand-percent do not have the person power for that. If I could pay three tech writers (or have their time volunteered) I'd love to to mount that effort, but that is simply not reality. Regardless, we *do* have to serve both audiences somehow, i.e. we are stuck with a single ref guide that contains some level of detail that is probably beyond the interest or use of most average users. 

>Corollaries of the above, (continuing the analogy to the English language
dictionary:)

>   - The length of a dictionary doesn't impair its utility - the user isn't
   going to read it all - only a single entry.  But completeness matters a lot.

I would never suggest a user would read all fo a ref guide. And I also agree that the *overall* length is unimportant. But I do disagree about the effect of length on *individual entries* (see below)

>   - Repetitiveness is not a problem, for the same reason as above.

Explicit textual repetitiveness is an enormous problem for overtaxed developers. It presents an unsustainable maintenance burden. Fortunately. since the documentation is presented in HTML, we have the ability to factor the information into manageable chunks, and to link between them as appropriate. I think hypertext links in reference documentation are perfectly and completely reasonable, in order to "factor" information.

But repetitiveness is also a problem for users. If I have to repeat 500 words for every one of 5000 properties, then every entry is now its own sub-haystack that users must navigate and that in itself is a problem. 

>  - Each entry must be self contained, since you should assume it's the
   only part of the dictionary the user will ever read.

This is never true in practice. A dictionary tells you that a word is a transitive verb. It does not explain what "transitive" and "verb" are. There is always some base level of knowledge that has to be assumed. A reasonable critique might be to suggest that the current ref guide assumes too high a level, and in fact this is largely a conclusion I had already come to on my own as I stated earlier. But again that's different from "is not a reference guide". 

>   - Organization matters a lot.  Being able to find the one, single thing
   you want to know quickly is a big deal.

Certainly. Given the foundational, fundamental, and ubiquitous "models with properties" structure of the library, I've chosen to arrange the reference guide as a list of models, each with a list of their properties.  I'm not sure what other organization there could be?

> Hmmm.  this looks like a list containing a single string.  Why a list?

I would argue that reference guides are for *what* and *how* and not *why*.

> THese look vaguely like old-style Python string formats.  I only use the new method - so I'll have to go look up that syntax.  I wish this document either said explicitly that's what
these are, or said explicitly that they're something Bokeh specific...

??? You *don't* have to look them up, there is literally a complete list of them, *immediately below.* 

>> This list of supported *strftime *formats is reproduced below.  'strftime'?

> This links to a LINUX man page. WTF?

FWIW this was merely an attempt to provide some additional context for users who might want it. Some people appreciate this sort of additional, optional context. This is akin to that "why" question you asked above.

**Closed by bryevdv** 2018-01-01 16:46 UTC
