### ISSUE TITLE
show(row(div,plot)) overlap

### ISSUE THREAD

**Issue by Pierretherenard** [bokeh/bokeh#8688] opened 2019-02-26 05:53 UTC
The div is hidden by the plot on the the right. I tried different width but I still get the same issue at the end of the line. This make no difference if I use a different sequence of rows or columns with function show()

first screenshot is firefox, the second is safari
macOS 10.13.6
Bokeh 1.0.4
#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.models.sources import ColumnDataSource
from bokeh.models.widgets import Div
from bokeh.plotting import figure, output_file, show
 
def test(self)      
    deg = [1]
    cnt = [10]
    sourcesdeg = ColumnDataSource(data=dict(deg=deg, cnt=cnt))
    pdeg = figure(plot_width=300, plot_height=400, tools="pan,wheel_zoom,reset")
    pdeg.vbar("deg", width=0.5, bottom=0, top="cnt", color="#f7e368", source=sourcesdeg)
    output_file("graphstest.html")  
    len_width = 300
    div_exp00 = Div(
            text="""The graph on the right show the number of edges by rounded gap to the first decimal. The maximum gap
             you can have between two nodes is 2 and the least is 0. Zero means that 2 nodes have the same sentiment 
             tone.""",
            width=len_width)
    show(row(div_exp00,pdeg))

```

#### Screenshots or screencasts of the bug in action
![firefox](https://user-images.githubusercontent.com/23002446/53389743-5b5f2700-3945-11e9-8f10-21cb38430f9b.png)
![safari](https://user-images.githubusercontent.com/23002446/53389757-64e88f00-3945-11e9-8f29-1cf7a9dc40c2.png)

**Comment by bryevdv** [comment] 2019-02-26 22:30
@Pierretherenard can you try with a dev build? Much layout work has been done in preparation for the upcoming 1.1 release, this may already be fixed.

**Comment by mattpap** [comment] 2019-02-26 22:33
It's fixed.

![image](https://user-images.githubusercontent.com/27475/53451372-ec560100-3a1e-11e9-911c-c483ec9946a6.png)

**Comment by mattpap** [comment] 2019-02-26 22:36
This is definitively a duplicate, but I can't find the issue right now.

**Comment by bryevdv** [comment] 2019-02-27 00:09
I'm not overly concerned with recording which it was a dupe of

**Closed by bryevdv** 2019-02-27 00:09 UTC

**Comment by Pierretherenard** [comment] 2019-02-27 01:55
Sorry I don't have a dev env.
Thank you for the resolution I will remove my blank div with a width of length +10 with the 1.1

**Comment by bryevdv** [comment] 2019-02-27 03:18
FYI Dev builds after published and are conda/pip installable
