### ISSUE TITLE
feature: add support for batched model updates in Bokeh server applications

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5438] opened 2016-11-03 00:44 UTC
Traitlets supports a batching model changes (before performing trait validation) using a `hold_trait_notifications` context manager.

http://traitlets.readthedocs.io/en/stable/using_traitlets.html#validation

```python
...
# Changing required parity and value together while holding cross validation
with parity_check.hold_trait_notifications():
    parity_check.value = 1
    parity_check.parity = 1
```

It would be nice to support a similar pattern in Bokeh, in order to support updating multiple models while only issuing one (1) on_change callback.

**Comment by bryevdv** [comment] 2017-06-22 03:53
I believe this will be necessary to re-implement `push_notebook` in some fashion with he bokeh server protocol under the hood.

**Comment by bryevdv** [comment] 2017-09-17 01:19
dupe of #4911

**Closed by bryevdv** 2017-09-17 01:19 UTC
Labels: reso: duplicate
