### ISSUE TITLE
[BUG] Regression for/on Bokeh 3.0.3; failed to validate StaticLayoutProvider(id='p1075', ...).graph_layout: expected an  element of Dict(Int, Seq(Any)), got {'A': array([-7.94707039,  3.45521447]), 'B': 

### ISSUE THREAD

**Issue by darahsten** [bokeh/bokeh#12702] opened 2022-12-28 20:04 UTC
### Software versions

Python version 3.9.16
Bokeh version 3.0.3
Network X 2.8.8

### Browser name and version

Brave 1.46.140

### Expected behavior

Expecting bokeh to show a graph from network x when using textural, string data as the data points for the node.

### Observed behavior

failed to validate StaticLayoutProvider(id='p1075', ...).graph_layout: expected an 
element of Dict(Int, Seq(Any)), got {'A': array([-7.94707039,  3.45521447]), 'B': 
array([-6.60505319,  4.31869148]), 'C': array([ 8.38746457, -6.26423001]), 'D': 
array([ 6.7178286 , -6.63523276]), 'E': array([-5.66671517,  5.25260372]), 'F': 
array([10.        , -6.53836091]), 'G': array([-4.88645443,  6.41131401])}

### Example code

```Python
import pandas as pd
import networkx as nx

data = {
    'source': ['A', 'C', 'B', 'F', 'G'],
    'target': ['B', 'D', 'E', 'C', 'E'],
    'weight': [5, 3, 10, 4, 7]
}
df = pd.DataFrame(data=data)
G = nxfrom_pandas_edgelist(df, 'source', 'target', 'weight')
# Choose a title!
title = 'Graph Network'

# Establish which categories will appear when hovering over each node
HOVER_TOOLTIPS = [("Character", "@index")]
# Create a plot — set dimensions, toolbar, and title
plot = figure(tooltips=HOVER_TOOLTIPS,
              tools="pan,wheel_zoom,save,reset", active_scroll='wheel_zoom',
              x_range=Range1d(-10.1, 10.1), y_range=Range1d(-10.1, 10.1), title=title)

network_graph = from_networkx(G, networkx.spring_layout, scale=10, center=(0, 0))

# Set node size and color
network_graph.node_renderer.glyph = Circle(size=15, fill_color='skyblue')

# Set edge opacity and width
network_graph.edge_renderer.glyph = MultiLine(line_alpha=0.5, line_width=1)

# Add network graph to the plot
plot.renderers.append(network_graph)
return plot
```

### Stack traceback or browser console output

  File "/home/user/PycharmProjects/nlgraph/nlgraph/insights/client.py", line 191, in test_sample_graph
    network_graph = from_networkx(G, nx.spring_layout, scale=10, center=(0, 0))
  File "/home/user/.virtualenvs/nlgraph/lib/python3.9/site-packages/bokeh/plotting/graph.py", line 123, in from_networkx
    graph_renderer.layout_provider = StaticLayoutProvider(graph_layout=graph_layout)
  File "/home/user/.virtualenvs/nlgraph/lib/python3.9/site-packages/bokeh/models/graphs.py", line 83, in __init__
    super().__init__(*args, **kwargs)
  File "/home/user/.virtualenvs/nlgraph/lib/python3.9/site-packages/bokeh/models/graphs.py", line 66, in __init__
    super().__init__(*args, **kwargs)
  File "/home/user/.virtualenvs/nlgraph/lib/python3.9/site-packages/bokeh/model/model.py", line 110, in __init__
    super().__init__(**kwargs)
  File "/home/user/.virtualenvs/nlgraph/lib/python3.9/site-packages/bokeh/core/has_props.py", line 298, in __init__
    setattr(self, name, value)
  File "/home/user/.virtualenvs/nlgraph/lib/python3.9/site-packages/bokeh/core/has_props.py", line 327, in __setattr__
    return super().__setattr__(name, value)
  File "/home/user/.virtualenvs/nlgraph/lib/python3.9/site-packages/bokeh/core/property/descriptors.py", line 288, in __set__
    value = self.property.prepare_value(obj, self.name, value)
  File "/home/user/.virtualenvs/nlgraph/lib/python3.9/site-packages/bokeh/core/property/bases.py", line 365, in prepare_value
    raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
ValueError: failed to validate StaticLayoutProvider(id='p1075', ...).graph_layout: expected an element of Dict(Int, Seq(Any)), got {'A': array([-5.65316498,  5.45483518]), 'B': array([-3.96831791,  5.90430576]), 'C': array([ 4.48091456, -8.29717112]), 'D': array([  3.53391884, -10.        ]), 'E': array([-2.70501426,  6.61458729]), 'F': array([ 5.90898383, -7.35862929]), 'G': array([-1.59732007,  7.68207218])}

I have determined that this is a regression. It does not appear on bokeh versions 2.4.3. The above example works on bokeh==2.4.3

**Comment by mattpap** [comment] 2022-12-28 20:05
This is a duplicate of #12651.

**Closed as completed by mattpap** 2022-12-28 20:05 UTC
Labels: reso: duplicate
