### ISSUE TITLE
Shared Interactive Legend: Invisible legend items and appearing plots

### ISSUE THREAD

**Issue by sjohnson5** [bokeh/bokeh#7672] opened 2018-03-21 20:28 UTC
I am trying to make a single interactive legend that controls multiple plots.

The idea (and expected outcome of my code) being that with the single legend you can hide different data on two separate plots that share the same key.

However I am getting a very unexpected outcome.

Here is my code:
```
import pandas as pd
from bokeh.palettes import Spectral4
from bokeh.plotting import Figure
from bokeh.sampledata.stocks import AAPL, IBM, MSFT, GOOG
from bokeh.layouts import column
from bokeh.io import show, output_file
from bokeh.models import Legend

#making first plot
p1 = Figure(plot_width=800, plot_height=250, x_axis_type="datetime", toolbar_location='above')
p1.title.text = 'First Plot'

#making second plot
p2 = Figure(plot_width=800, plot_height=250, x_axis_type="datetime", toolbar_location='above')
p2.title.text = 'Second Plot'

#making empty list for legend items
legend_its = []

for data, name, color in zip([AAPL, IBM, MSFT, GOOG], ["AAPL", "IBM", "MSFT", "GOOG"], Spectral4):
    df = pd.DataFrame(data)
    df['date'] = pd.to_datetime(df['date'])
    #data for first plot
    c = p1.circle(df['date'], df['close'], line_width=2, color=color, alpha=0.8)
    #data for second plot
    d = p2.circle(df['date'], df['volume'], line_width=2, color=color, alpha=0.8)
    #adding data to over-arching legend
    legend_its.append((name, [c,d]))

#creating legend outside of plot
legend = Legend(items = legend_its, location=(0,0))
legend.click_policy = 'hide'

#adding the legend to p1
p1.add_layout(legend, 'right')

#outputting a file and showing
output_file("shared_interactive_legend.html", title="shared_interactive_legend.py example")
show(column(p1,p2))

```

This is what the program initially outputs:
![initial_output](https://user-images.githubusercontent.com/36089304/37734190-b6444d62-2d07-11e8-8f45-083e364db3f3.png)

Notice:
-p2 doesn't show
-p1's title and tool-bar are missing
-the legend only shows the first legend item (in this case AAPL); I've tried shuffling the "legend_its" list right before I create my legend and it always only shows the first item in the list

After clicking on AAPL to hide it this is what happens:
![after_hiding_aapl](https://user-images.githubusercontent.com/36089304/37734198-bd590fca-2d07-11e8-97bf-a8a3bdf87c4b.png)

Notice:
-p2 now appears (with title and toolbar)
-AAPL hides on both graphs as expected, however the text in the key isn't muted as it normally would be

Now, if you click slightly below AAPL in the legend where the other legend items should be the corresponding data disappears on both graphs (i.e. the other legend items are in the legend and functional just invisible):
![hiding_still_works](https://user-images.githubusercontent.com/36089304/37734211-c534a830-2d07-11e8-940a-b46d42c260df.png)

#### My problems:
-Where is the title and tool-bar of p1?
-Why does p2 only appear after interacting with the legend?
-Why are the legend keys invisible but still functional?

#### Software versions:
-bokeh 0.12.13
-python 3.6
-Ubuntu 16.04
-Firefox Quantum 59.0.1

Also it should probably be noted that I am relatively new to using bokeh.

**Comment by bryevdv** [comment] 2018-03-21 20:35
Sharing legends between plots is not currently possible, this is a dupe of #7607

**Closed by bryevdv** 2018-03-21 20:35 UTC
