### ISSUE TITLE
Add more JS visual and integration tests

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#10834] opened 2021-01-11 18:26 UTC
cc @brendancol @mattpap 

This issue is to discuss Makepath adding more JS visual an integration tests. (@brendancol please tag in anyone else as appropriate)

Here is a reference PR that added many tests for Colorbar: https://github.com/bokeh/bokeh/pull/10779

@mattpap has suggested Legend as another area that would be good to add coverage for soon. I agree but might suggest finding a smaller area to use as an initial introduction. (@mattpap do you have any suggestions?)

Here is the current documentation on JS side tests: 

https://docs.bokeh.org/en/latest/docs/dev_guide/testing.html#javascript-unit-tests

One of the side-goals of this work should be to greatly expand the Testing docs in the dev guide to provide more of a ste by step guide on how to add these tests. @mattpap your support will be needed here

**Comment by brendancol** [comment] 2021-01-11 20:03
@bryevdv @marcozimmermannpm this sounds good.  Breaking down tasks a bit further:

- [ ] review colorbar tests: https://github.com/bokeh/bokeh/pull/10779
- [ ] Find good first area for increasing test coverage.  Consider improve Test coverage for Legend...
- [ ] Expand testing docs in the **Dev Guide** with step-by-step instructions on how to run and write new tests

**Comment by mattpap** [comment] 2021-01-13 10:45
- `examples/integration` should be transformed into visual and/or integration tests in bokehjs and later removed (they were created as poor man's visual integration tests). Some may be redundant at this point, so anything that we already test in bokehjs should be dropped. If some don't make sense being tested in bokehjs, then they should be transformed into selenium integration tests.
- `tests/integration` should be transformed into visuals and/or integration tests in bokehjs and later removed. The same as before, no duplication and only if it makes sense. Some integration tests are bokeh<->bokehjs integration tests, so the should stay in bokeh. Some tests make sense to be transformed, but it may not be possible for various reasons (e.g. require trusted browser events, which bokehjs' test framework doesn't support right now, however, most of such tests that require trusted events, can be rewritten without using them, i.e. using APIs instead, which would also improve robustness of such tests).
- some other examples, especially under `examples/models/file`, contain synthetic examples, that were poor man's integration tests (similar to `examples/integration`, but more leaning towards actual examples). Those should be filtered out, transformed and removed, if they don't serve value as examples.
- `examples/` and `sphinx/**/examples/*.py` should be scanned for cases that are only presented, but never actually tested. There are lots of less frequently used corners of bokehjs, that are either untested or barely tested, or were started to be tested just recently, but require further refinement.
- scan the issue tracker for bug/regression fixes that were merged without tests. A good starting point is this issue #10390. This may not be visual/integration test related, but important to get done nevertheless.
- orthogonal to testing, but bokehjs would need some more examples. Note that this will require improvements to the testing framework, because currently bokehjs' examples are not tested (visually).

**Comment by mattpap** [comment] 2021-01-13 10:53
Visual tests that would be useful immediately:

- all combinations of axis labels (different types of axes, label lengths, styling, alignment, standoff, orientation, etc.) (PR #10828)
- all annotation that have no or minimal visual tests (whisker, band, legend, span, slope, etc.)
- all combinations of glyphs and their attributes (use all types of scales, value ranges, unit types, rotations, visuals and other configuration options, e.g. dilation). Make sure to test at least canvas and svg backend, and webgl where it makes sense.

**Comment by IuryPiva** [comment] 2021-04-06 12:20
@mattpap How would one create these tests? Where to start?

**Comment by mattpap** [comment] 2021-04-07 09:40
> How would one create these tests? Where to start?

It depends on the particular types of tests. Start with exploring recent PRs with changes under `bokehjs/test/{unit,integration}` (`git log --stat bokehjs/test/{unit,integration}`), e.g. PR #11018, and observe the patterns. Familiarize yourself with 
https://docs.bokeh.org/en/latest/docs/dev_guide/bokehjs.html#testing. Pick one class of functionality of bokehjs that's either sparsely tested or not tested at all (e.g. `Legend` annotation, see PR #10779), and start writing tests. Then we can discuss particular issues that you may encounter (e.g. test robustness and performance, dealing with asynchronous nature of bokehjs' APIs (i.e. knowing when bokehjs is done), etc.). Keep the styling perfectly consistent with the surrounding code. Make tests minimal and isolate as many variables as possible. Whenever possible, e.g. regression tests, make sure you observe tests actually fail (test pre and post applying a fix), i.e. test your tests, and be able to prove that your tests do anything useful.

**Comment by mattpap** [comment] 2021-04-12 12:47
@IuryPiva, do you have any further specific questions or issues with this? I would like to see at least one PR soon.

**Comment by IuryPiva** [comment] 2021-04-12 13:37
@mattpap working on this today

**Comment by mattpap** [comment] 2022-07-29 18:50
I will close this, as there is no clear path for this issue to be ever considered completed. More tests and all the test-related improvements mentioned in this issue are still important to pursue at some point, and any contributions in this area are welcome.

**Closed by mattpap** 2022-07-29 18:50 UTC
Labels: tag: component: tests, type: discussion, tag: component: bokehjs
