### ISSUE TITLE
Jupyter notebook doesn't load plots until reload page

### ISSUE THREAD

**Issue by physinet** [bokeh/bokeh#5045] opened 2016-08-29 16:06 UTC
I've added some Bokeh plots to a Jupyter notebook the normal way (`output_notebook`, `show`), and if I shutdown the notebook and reopen it, the plots do not show initially. However, if I then reload the browser page, the plots will show up (and it does take a while to load). I've only tested this with Chrome on Windows 10. Not sure if it's a Bokeh issue, Jupyter issue, or Chrome issue. Although it is not a huge issue to reload the page, could someone look into this bug?

**Comment by bryevdv** [comment] 2016-08-29 16:10
This is probably a duplicate of #4987 fixed in #5014 and now in master. Please test with the `0.12.2dev8` build that will be available later today. Can re-open if that does not resolve your issue.

**Closed by bryevdv** 2016-08-29 16:10 UTC

**Comment by physinet** [comment] 2016-08-29 23:28
Thanks, this fixed two related problems I was having! As a side note, I wasn't able to get the `0.12.2dev8` build working on Win10, but had no problems on Mac.

**Comment by bryevdv** [comment] 2016-08-29 23:33
>  I wasn't able to get the 0.12.2dev8 build working on Win10

can you elaborate @physinet ?

**Comment by physinet** [comment] 2016-08-29 23:35
Yes, sorry, forgot to paste the error message.

```
C:\Anaconda3\lib\site-packages\bokeh-tag_.0.12.2dev8-py3.5.egg\bokeh\util\version.py in base_version()
     32     import re
     33     VERSION_PAT = re.compile(r"^(\d+\.\d+\.\d+)((?:dev|rc).*)?")
---> 34     return VERSION_PAT.search(__version__).group(1)
     35 
     36 __base_version__ = base_version()

AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by bryevdv** [comment] 2016-08-29 23:36
@physinet what is `bokeh.__version__` ?

**Comment by physinet** [comment] 2016-08-29 23:37
This error pops up when importing the module.

**Comment by bryevdv** [comment] 2016-08-29 23:43
Hmm I just tried a fresh conda environment install on a Win10 VM can you elaborate about how you installed, if there was a version installed previously, etc.

**Comment by physinet** [comment] 2016-08-29 23:46
I did have Bokeh previously installed, but I've since uninstalled that version. Don't remember the exact order I tried things unfortunately.

I now just noticed that I have both `bokeh-tag.0.12.2dev8-py3.5.egg` and `bokeh-tag_.0.12.2dev8-py3.5.egg` in `site-packages`. I'll try removing everything and do a fresh install with conda.

**Comment by physinet** [comment] 2016-08-29 23:53
Still no luck. Steps I did that worked on Mac and previously for dev7 on Windows were:

1. Download and extract zip
2. `npm install` in bokehjs directory
3. `python setup.py install`

I didn't have to uninstall previous versions of bokeh before, but doing so now does not help.

**Comment by bryevdv** [comment] 2016-08-30 00:40
@physinet wait you are building from source, not using `conda` or `pip`? Then for one you will need to add `--build-js` to your `setup.py` invocation. The source tarballs do not ship with a pre-build BokehJS. I'd also suggest removing the `bokeh` directory in addition to any `.egg` files from `site-packages`.  Really though, I'd recommend using `conda` or `pip`.

**Comment by physinet** [comment] 2016-08-30 02:50
Sorry, you can probably tell that I'm not very experienced dealing with package installation outside of letting `pip` do all the work for me. And building from source after doing `npm install` worked for dev7 on both Mac and Win10, so I thought my steps would have worked here. 

That said, dumb question: How exactly do I install via `pip`? I tried `pip install bokeh==0.12.2dev8` (only up to 0.12.1 were available) and `pip install https://github.com/bokeh/bokeh/archive/0.12.2dev8.tar.gz` (stuck after download completed), which is the most I knew `pip` could do up to this point. Had no clue you could use `pip` to install from local, although it makes sense in retrospect. But I still can't get it to work; it isn't obvious what command to use.

**Comment by bryevdv** [comment] 2016-08-30 02:52
Hi @physinet "dev builds" are not published on the main channels, you can find the instructions for installing with `conda` or `pip` on the docs site:

http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

**Comment by physinet** [comment] 2016-08-30 02:56
Completely missed that, thanks. I was looking in the wrong place ([here](http://bokeh.pydata.org/en/latest/docs/dev_guide/setup.html#devguide-setup)).
