### ISSUE TITLE
problem enabling zoom on Image_url object

### ISSUE THREAD

**Issue by epifanio** [bokeh/bokeh#4355] opened 2016-05-23 02:03 UTC
* Description of expected behavior and the observed behavior

Using bokeh from git master in a jupyter notebook, I'm trying to understand how to use the library to plot images and enable tools like ```BoxZoomTool``` with same zoom factor on both axes to avoid distortion of the image.

The code I'm using is:

```
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
from bokeh.models.tools import BoxZoomTool

output_notebook()

#img size in pixel
x,y=[3392.0,701.0]

TOOLS = 'pan,box_select,crosshair,resize,reset,hover,wheel_zoom'

p = figure(x_range=(0,3392), y_range=(701,0), tools=TOOLS)
p.add_tools(BoxZoomTool(match_aspect=True))
p.image_url(url=['http://epinux.com/bathy.png'], x=0.0, y=0.0, w=1.0, h=1.0)

show(p)
```

But seems that the parameters w,h are being ignored and the zoom doesn't respond as expected.

The same code works fine on last stable release of bokeh. The reason why I'm using git master is because I need the option:

```
match_aspect=True
```

JS console log:

https://gist.github.com/e543a51767dfe03d5a88673aa5773363

Bokeh info:

```
Python version      :  3.5.1+ (default, May  9 2016, 11:00:17) 
IPython version     :  4.2.0
Bokeh version       :  0.12.0dev8-422-g46704c2
BokehJS static path :  /usr/local/lib/python3.5/dist-packages/bokeh/server/static
```

**Comment by bryevdv** [comment] 2016-05-27 17:42
Confirmed as a bug, I believe from commit https://github.com/bokeh/bokeh/commit/dca5381ebd9c3a74269b0db49c5fa93cbb9a8fa1 

ping @mattpap

**Comment by bryevdv** [comment] 2016-05-27 17:51
@mattpap this diff appears to fix, but extra input welcome:
```
diff --git a/bokehjs/src/coffee/models/glyphs/image_url.coffee b/bokehjs/src/coffee/models/glyphs/image_url.coffee
index 6bdc0eb..7a1f21e 100644
--- a/bokehjs/src/coffee/models/glyphs/image_url.coffee
+++ b/bokehjs/src/coffee/models/glyphs/image_url.coffee
@@ -42,8 +42,8 @@ class ImageURLView extends Glyph.View
 
   _map_data: () ->
     # XXX: remove this when `null` handling is improved.
-    ws = (if w? then w else NaN for w in @_w)
-    hs = (if h? then h else NaN for h in @_h)
+    ws = (if @_w? then @_w else NaN for x in @_x)
+    hs = (if @_h? then @_h else NaN for x in @_x)
     @sw = @sdist(@renderer.xmapper, @_x, ws, 'edge', @mget('dilate'))
     @sh = @sdist(@renderer.ymapper, @_y, hs, 'edge', @mget('dilate'))

```

@epifanio with this change you also need to change your code. The `w` and `h` are 'data space" units. Right now you have ranges that span from 0 to 700 and 0 to 3000 but setting `w=1` and `h=1` means the entire image would only take up like one pixel of that space. I changed to 
```
p.image_url(url=['http://epinux.com/bathy.png'], x=0.0, y=0.0, w=3392, h=701)
```
and observe what seems to be reasonable behaviour, but you'd want to check that the position and range values are actually appropriate for your date. E.g if the boundaries correspond to lat/lon or something, you'd want to use those real "data space" units. But only you know about those details, this is just a reminder to consider this.

**Comment by bryevdv** [comment] 2016-05-27 17:54
As a concrete example, if I set:
```
p.image_url(url=['http://epinux.com/bathy.png'], x=0.0, y=0.0, w=400, h=100)
```
<img width="612" alt="screen shot 2016-05-27 at 12 53 31 pm" src="https://cloud.githubusercontent.com/assets/1078448/15616529/09c8395c-240a-11e6-8d72-d31c0fef667a.png">
 
That is the image takes up space between  (0,400) and (0,100) just as requested.

**Comment by epifanio** [comment] 2016-05-28 01:34
@bryevdv , thanks for the fix. I applied the changes. The zoom works properly now.
I use the code above. with the changes you suggested and I set ```x_range=y_range``` so to have the same aspect ratio of the original image.

```
p = figure(x_range=(0,3392), y_range=(3392,0), tools=TOOLS)
p.add_tools(BoxZoomTool(match_aspect=True))
p.image_url(url=['http://epinux.com/bathy.png'], x=0.0, y=0.0, w=3392, h=700)
```
Thank you!

**Comment by damianavila** [comment] 2016-05-31 18:40
I did not see any PR fixing this one, just @bryevdv diff... so reopening...

**Comment by damianavila** [comment] 2016-05-31 19:03
reopening again because the merge in your own fork close this issue...

**Comment by bryevdv** [comment] 2016-05-31 19:28
@damianavila it's surprising to me that merging into a fork closes the issue on the main repo. My guess is that's not actually intended, but I expect the times that PRs are merged into forks, intersected with the times the PR has "fixes #XYZ" is small enough that GH overlooked it..

**Comment by damianavila** [comment] 2016-05-31 19:38
@bryevdv, in his PR against his fork he referenced the our issue, so I guess the GH api is not intelligent enough to know that the PR comes from, or it was thoughts in this way because there are other projects that work in a fork-based basis, pushing PR against their own fork that the main "repo" can track and merge later...

**Closed** 2016-06-01 20:23 UTC
Labels: type: bug
