### ISSUE TITLE
bokeh serve hangs with tornado 4.5

### ISSUE THREAD

**Issue by dasGringuen** [bokeh/bokeh#6457] opened 2017-06-13 10:36 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

python 3.5
tornado 4.5
bokeh 12.5
Debian Jessie and Ubuntu 16.04

#### Description of expected behavior and the observed behavior
bokeh serve command runs but the application hangs, I downgraded tornado to 4.4.3 and it works again
sudo pip3 install tornado==4.4.3

#### Complete, minimal, self-contained example code that reproduces the issue
import numpy as np
from numpy import pi

from bokeh.client import push_session
from bokeh.driving import cosine
from bokeh.plotting import figure, curdoc

x = np.linspace(0, 4*pi, 80)
y = np.sin(x)

p = figure()
r1 = p.line([0, 4*pi], [-1, 1], color="firebrick")
r2 = p.line(x, y, color="navy", line_width=4)

session = push_session(curdoc())

@cosine(w=0.03)
def update(step):
    # updating a single column of the the *same length* is OK
    r2.data_source.data["y"] = y * step
    r2.glyph.line_alpha = 1 - 0.8 * abs(step)

curdoc().add_periodic_callback(update, 50)

session.show(p) # open the document in a browser

**Comment by bryevdv** [comment] 2017-06-13 11:31
dupe of https://github.com/bokeh/bokeh/issues/6152

Tornado 4.5 introduced a breaking incompatibility with Bokeh. This has been resolved in master, recent dev builds and release candidates.

**Closed by bryevdv** 2017-06-13 11:31 UTC
