### ISSUE TITLE
Tabs header doesn't update when layout recomputes

### ISSUE THREAD

**Issue by devmood** [bokeh/bokeh#8777] opened 2019-03-21 11:25 UTC
Bokeh version: `1.0.2`
OS: `Ubuntu 18.04.2 LTS`
python version: `3.7.1`

While trying to achieve a responsive layout (`tabs`, `plot` and `widgetbox`), I came across a bug, where a plot expands unexpectedly; even though `sizing_mode` on each step has been set to `scale_width`. In all the following code samples I tried to add / remove the least amount of code possible, so that examples remain alternative versions of the same code. 

This first code sample allows you to reproduce behavior I'm talking about.
```
import random
from bokeh.io import output_file, show
from bokeh.layouts import column, row, widgetbox
from bokeh.models import Range1d
from bokeh.models.widgets import Panel, Tabs, CheckboxGroup, Div
from bokeh.plotting import figure
output_file("issue.html")

def get_plot():
    p = figure(width=1000, height=500)
    xs = [x for x in range(20)]
    ys = [x * y for x, y in zip(xs, [random.randrange(-4, 4) for _ in range(len(xs))])]
    max_y = max(ys)
    min_y = min(ys)
    p.y_range = Range1d(0 + min_y * 1.1, max_y * 1.1)
    p.line(xs, ys)
    description = Div(text="""<h3>Choose something:</h3>""")
    checkbox_group = CheckboxGroup(labels=[f"pick option {x}" for x in range(5)],
                                   css_classes=["scrollable"])
    return column(row(p, widgetbox(description, checkbox_group, sizing_mode="scale_width"),
                      sizing_mode="scale_width"), sizing_mode="scale_width")

tabs = []
for ii, tab_name in enumerate([f"some_random_tab_name_{i}" for i in range(5)]):
    plot = get_plot()
    tabs.append(Panel(child=plot, title=tab_name, sizing_mode="scale_width"))

tabs = Tabs(tabs=tabs, sizing_mode="scale_width")
show(row(tabs, sizing_mode="scale_width"))
```

Screenshots presenting the bug:

![Screenshot from 2019-03-21 12-05-42](https://user-images.githubusercontent.com/32578489/54748720-b695d980-4bd2-11e9-8916-f5b50d2c7ab9.png)

![Screenshot from 2019-03-21 12-05-49](https://user-images.githubusercontent.com/32578489/54748721-b72e7000-4bd2-11e9-9c1e-ceffe4d99a74.png)

![Screenshot from 2019-03-21 12-05-58](https://user-images.githubusercontent.com/32578489/54748722-b72e7000-4bd2-11e9-8fc0-0a09699dc80a.png)

This second code sample doesn't cause the bug, but is still not responsive and the `sizing_mode` behaves like `fixed`.
```
import random
from bokeh.io import output_file, show
from bokeh.layouts import column, row, widgetbox
from bokeh.models import Range1d
from bokeh.models.widgets import Panel, Tabs, CheckboxGroup, Div
from bokeh.plotting import figure
output_file("issue.html")

def get_plot():
    p = figure(width=1000, height=500)
    xs = [x for x in range(20)]
    ys = [x * y for x, y in zip(xs, [random.randrange(-4, 4) for _ in range(len(xs))])]
    max_y = max(ys)
    min_y = min(ys)
    p.y_range = Range1d(0 + min_y * 1.1, max_y * 1.1)
    p.line(xs, ys)
    description = Div(text="""<h3>Choose something:</h3>""")
    checkbox_group = CheckboxGroup(labels=[f"pick option {x}" for x in range(5)],
                                   css_classes=["scrollable"])
    return column(row(p, widgetbox(description, checkbox_group, sizing_mode="scale_width")),
                  sizing_mode='scale_width')

tabs = []
for ii, tab_name in enumerate([f"some_random_tab_name_{i}" for i in range(5)]):
    plot = get_plot()
    tabs.append(Panel(child=plot, title=tab_name, sizing_mode="scale_width"))

tabs = Tabs(tabs=tabs, sizing_mode="scale_width")
show(row(tabs, sizing_mode="scale_width"))
```

Screenshots presenting fixed-like `sizing_mode`:

![Screenshot from 2019-03-21 12-15-47](https://user-images.githubusercontent.com/32578489/54748924-5a7f8500-4bd3-11e9-9967-999769b8e7d0.png)

![Screenshot from 2019-03-21 12-16-01](https://user-images.githubusercontent.com/32578489/54748926-5a7f8500-4bd3-11e9-8066-7bcc0a539e51.png)

![Screenshot from 2019-03-21 12-16-13](https://user-images.githubusercontent.com/32578489/54748927-5a7f8500-4bd3-11e9-9f91-3e5ac245cefc.png)

The last code sample is responsive, but doesn't include tabs in the layout, and shows the contents of a single `tab`. The `widgetbox` takes up a bit too much space to my liking and the `plot` itself shrank a bit.
```
import random
from bokeh.io import output_file, show
from bokeh.layouts import column, row, widgetbox
from bokeh.models import Range1d
from bokeh.models.widgets import CheckboxGroup, Div
from bokeh.plotting import figure
output_file("issue.html")

def get_plot():
    p = figure(width=1200, height=500)
    xs = [x for x in range(20)]
    ys = [x * y for x, y in zip(xs, [random.randrange(-4, 4) for _ in range(len(xs))])]
    max_y = max(ys)
    min_y = min(ys)
    p.y_range = Range1d(0 + min_y * 1.1, max_y * 1.1)
    p.line(xs, ys)
    description = Div(text="""<h3>Choose something:</h3>""")
    checkbox_group = CheckboxGroup(labels=[f"pick option {x}" for x in range(5)])
    return column(row(p, widgetbox(description, checkbox_group, sizing_mode="scale_width"),
                      sizing_mode="scale_width"), sizing_mode="scale_width")

plot = get_plot()
show(plot)
```

Screenshots presenting responsive `plot` with unwanted space on the right side of the `widgetbox`:

![Screenshot from 2019-03-21 12-18-54](https://user-images.githubusercontent.com/32578489/54749063-bcd88580-4bd3-11e9-9a32-1d82f7dab1a7.png)

![Screenshot from 2019-03-21 12-19-14](https://user-images.githubusercontent.com/32578489/54749064-bcd88580-4bd3-11e9-9e8d-7923f1d96ee5.png)

![Screenshot from 2019-03-21 12-19-25](https://user-images.githubusercontent.com/32578489/54749065-bcd88580-4bd3-11e9-8288-9c0c3e590994.png)

**Comment by bryevdv** [comment] 2019-03-21 15:29
@devmood please try with 1.1.0 dev build and report back. The layout system has been completely re-written and dozens of layout issues fixed, so we need to start from there as a basis. 

https://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

**Comment by bryevdv** [comment] 2019-03-22 04:46
So, I can't reproduce and growing problem. I do recall an issue for that before (though I can't find it now) and that it has been fixed. In 1.1 your plot does not scale because you have not set a sizing mode on it with the second code sample. But it does scale when a sizing mode is added. 

Note that `Panel` should not accept a `sizing_mode`, if it ever did, that itself was a bug, but it will not accept one in `1.1`. 

cc @mattpap or should we add a dummy do-nothing `sizing_mode` to `Panel`?

**Comment by bryevdv** [comment] 2019-03-22 04:55
@devmood note also that you have way overcomplicated things with many pointless intermediate layout objects. these will make it harder for you to reason about what should happen, but also muich harder for Bokeh to as well. I think this is closer to what you are trying to achieve (code for 1.1):

```
import random
from bokeh.io import output_file, show
from bokeh.layouts import column, row, widgetbox
from bokeh.models import Range1d
from bokeh.models.widgets import Panel, Tabs, CheckboxGroup, Div
from bokeh.plotting import figure
output_file("issue.html")

def get_plot():
    p = figure(width=1000, height=500, sizing_mode="scale_width")
    xs = [x for x in range(20)]
    ys = [x * y for x, y in zip(xs, [random.randrange(-4, 4) for _ in range(len(xs))])]
    max_y = max(ys)
    min_y = min(ys)
    p.y_range = Range1d(0 + min_y * 1.1, max_y * 1.1)
    p.line(xs, ys)
    description = Div(text="""<h3>Choose something:</h3>""")
    checkbox_group = CheckboxGroup(labels=[f"pick option {x}" for x in range(5)],
                                   css_classes=["scrollable"])
    return row(p, widgetbox(description, checkbox_group, width=200))

tabs = []
for ii, tab_name in enumerate([f"some_random_tab_name_{i}" for i in range(5)]):
    plot = get_plot()
    tabs.append(Panel(child=plot, title=tab_name))

tabs = Tabs(tabs=tabs, sizing_mode="stretch_both")
show(tabs, sizing_mode="stretch_both")
```

![ScreenFlow](https://user-images.githubusercontent.com/1078448/54801383-d7d2e600-4c23-11e9-908c-1b802670bcae.gif)

**Comment by bryevdv** [comment] 2019-03-22 04:57
@mattpap I am not seeing the tab expansion with the above, however

**Comment by devmood** [comment] 2019-03-22 16:10
@bryevdv Thanks a lot for Your response and help. It does indeed work with 1.1.0 dev build. And regarding the tabs extension... Is there a way to disable them and perhaps achieve something similar to the stable version, where all tabs were just stacked? It's way more convenient for me to have the tabs at the `tab_location="above` and I'd rather use scroll bar (added with custom css class) to look through them. I can achieve this behavior removing a few bokeh classes and overriding some styles, but it's not very elegant way to deal with the problem and it's not automated at all, unless I write some scraping script fixing html...

**Comment by bryevdv** [comment] 2019-03-22 18:51
@devmood improving tabs is still an area of active development. What there is now is probably the best we can deliver for 1.1 but it would be valuable to collect other ideas and use cases to inform follow on work. I'd suggest making an issue regarding tabs (after 1.1 is released in the near future)

**Comment by mattpap** [comment] 2019-03-22 19:08
@bryevdv, I went ahead and the issue with not updating tabs headers.

**Closed** 2019-03-22 21:52 UTC
Labels: tag: component: bokehjs, tag: layout, type: bug
