### ISSUE TITLE
Shared drag tools in grid plots only work on the last plot 

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#6921] opened 2017-09-12 03:06 UTC
Panning/Box Zoom on any of the first plots is ignored.

**Comment by bryevdv** [comment] 2017-09-12 03:08
See the "Linked Interactions" notebook e.g. Behaviour is weirder on two plot grid plot with lasso and box selection, one tool works on one and the other tool works on the other.

**Comment by rocheseb** [comment] 2017-09-12 21:38
I have that bug in an app with grid layouts, but it does not happen all the time. And when it happens, refreshing the page can fix it.

**Comment by bryevdv** [comment] 2017-09-12 21:56
That's useful information thanks @rocheseb, this one is on my short list to look at

**Comment by philippjfr** [comment] 2017-09-15 18:14
Seeing similar issues with the ``box_select`` tool, redisplaying or reloading the plot also makes it go away for me most of the time.

**Comment by bryevdv** [comment] 2017-09-20 10:28
This is important to fix soon

**Comment by bryevdv** [comment] 2017-09-20 12:09
Unfortunately I'm having serious trouble reproducing this. Until we can reliably reproduce for a bisection, my best guess (but that could be wrong) is that it was related to the changes to these files after `0.12.7`:
```
bokehjs/src/coffee/core/has_props.coffee
bokehjs/src/coffee/core/layout/layout_canvas.coffee
bokehjs/src/coffee/core/layout/side_panel.coffee
bokehjs/src/coffee/models/axes/axis.coffee
bokehjs/src/coffee/models/canvas/cartesian_frame.coffee
bokehjs/src/coffee/models/plots/plot_canvas.coffee
```

**Comment by philippjfr** [comment] 2017-09-20 12:14
Using this example I can reproduce it intermittently, it works about 50% of the time:

```python
from bokeh.plotting import figure, output_notebook, show
from bokeh.layouts import row, gridplot

output_notebook()

# output to static HTML file
p1 = figure(plot_width=400, plot_height=400, tools=['box_select'])

# add a circle renderer with a size, color, and alpha
p1.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)

p2 = figure(plot_width=400, plot_height=400)
p2.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)

# show the results
show(gridplot([[p1, p2]]))
```

**Comment by bryevdv** [comment] 2017-09-20 12:17
That's pretty much what I was trying

**Comment by bryevdv** [comment] 2017-09-20 12:23
OK I can actually repro a problem in 0.12.7, perhaps this goes back further than we think?

**Comment by bryevdv** [comment] 2017-09-20 17:09
Pretty sure this goes back, AFAICT tool merging in`ToolBarBox` is just broken, or its' not being used correctly.

**Comment by bryevdv** [comment] 2017-09-20 17:15
@philippjfr Tho, actually, that code is a mis-usage. All the plots really need to have the *same set of tools* I feel like we enforced this better in the past, but perhaps the warning is gone. Do you do things like that in HV?

**Comment by bryevdv** [comment] 2017-09-20 17:16
If I make sure the plots have the same set of tools then I can't seem to reproduce an error

**Comment by rocheseb** [comment] 2017-09-20 18:09
Might help, check this code:

```
import bokeh
from bokeh.io import show
from bokeh.models import Button, CustomJS
from bokeh.plotting import figure
from bokeh.layouts import gridplot

tools = "box_zoom"

fig_list = [figure(plot_height=150,plot_width=300,tools=tools) for i in range(3)]

for fig in fig_list:
	fig.scatter(x=range(10),y=range(10))

grid_list = [gridplot([[fig]],toolbar_location='above') for fig in fig_list]

grid_group = gridplot([[grid] for grid in grid_list],toolbar_location='left')

show(grid_group)
```
Initially the zoom wont work in some subgrids.
If the zoom does not work, deactivating and reactivating the tool fixes it

**Comment by bryevdv** [comment] 2017-10-01 19:28
@mattpap I'd appreciate if you could also take a look at this. This is important to fix but I did not make much headway, at least so far. Your perspective might suggest other ways to track the problem down.

**Comment by mattpap** [comment] 2017-10-09 17:23
I can't reproduce this in `file` output. I can in `notebook`, but just barely. I was about to comment that I can't reproduce at all until first failure happened. Interesting issue.

**Comment by philippjfr** [comment] 2017-10-09 17:28
At least when I originally tried this, this issue definitely also occurred in file output. I'll try to reproduce it again.

**Comment by bryevdv** [comment] 2017-10-09 17:31
@mattpap it was happening for me in `iris_splom` just yesterday

**Comment by mattpap** [comment] 2017-10-09 17:50
@bryevdv, @philippjfr, which web browser do you use?

**Comment by bryevdv** [comment] 2017-10-09 17:53
Safari usually

**Comment by bryevdv** [comment] 2017-10-09 17:54
I just tried this link:

https://bokeh.pydata.org/en/latest/docs/gallery/iris_splom.html

On Safari, FF, and Chrome and pan did not work on any of them

**Comment by bryevdv** [comment] 2017-10-09 17:55
The same link for `0.12.3` does work (other version have an unrelated docs deploy issue)

**Comment by mattpap** [comment] 2017-10-09 17:56
OK, that's useful info.

**Comment by philippjfr** [comment] 2017-10-09 18:41
I generally use chrome but can also reproduce it in FF and Safari.

**Comment by mattpap** [comment] 2017-10-09 19:08
This is an initialization order issue. A grid plot with `n` plots has `n + 1` toolbars, one for each plot (hidden) and the merged toolbar. Currently all toolbars are initialized in random (?; ids may matter here) order, and those initialized after the merged toolbar don't get gesture tools activated properly.

**Comment by bryevdv** [comment] 2017-10-09 19:17
This used to work (for several years) what changed?

**Comment by mattpap** [comment] 2017-10-09 19:35
> This used to work (for several years) what changed?

To name a few: signaling, default active tools, internals of model initialization.

**Comment by mattpap** [comment] 2017-10-09 20:01
Also, the reason I was unable to reproduce this for `file` examples, is because I use `BOKEH_DEV=true` which enables simple ids, and this results in stable initialization order.

**Comment by bryevdv** [comment] 2017-10-09 20:38
Unrelated but I've been wondering if we couldn't/shouldn't just switch to simple IDs all the time.

**Comment by mattpap** [comment] 2017-10-09 21:48
I have a fairly good idea what is going on, I should have a PR tomorrow.

**Comment by mattpap** [comment] 2017-10-09 21:54
> Unrelated but I've been wondering if we couldn't/shouldn't just switch to simple IDs all the time.

It would be nice, but I think there are reasons why we don't do this: server and sharing documents. Though there's a good reason to have randomized IDs, at least for testing, and this issue is a perfect example. Randomization helps with uncovering issues with initialization order, among other things.

**Closed** 2017-10-12 17:50 UTC
Labels: tag: component: bokehjs, tag: notebook, tag: regression, type: bug
