### ISSUE TITLE
Bad wheel zoom behavior

### ISSUE THREAD

**Issue by nleclercq** [bokeh/bokeh#6435] opened 2017-06-11 09:04 UTC
A wheel zoom bug seems to have been introduced in 0.12.6.rc4. While zooming, the glyphs  might cross the scales borders. See pictures below.

**Before zoom**
<img width="925" alt="capture d ecran 2017-06-11 a 10 58 55" src="https://user-images.githubusercontent.com/19185982/27009721-8f9188de-4e95-11e7-9f73-2a8c9fe02094.png">

**After zoom**
<img width="934" alt="capture d ecran 2017-06-11 a 10 59 23" src="https://user-images.githubusercontent.com/19185982/27009723-98d308c8-4e95-11e7-8b76-b83a672ddaa4.png">

**Comment by bryevdv** [comment] 2017-06-11 13:13
are you using svg output mode?

**Comment by bryevdv** [comment] 2017-06-11 13:26
I definitely can't reproduce this without out SVG mode enabled. That mode was added for, and only currently supported for, static image generation (ie. not general interactive use) Perhaps some day. @canavandl we should probably add a note to that effect in the `output_mode` doctring and the exporting plots user guide section.

**Comment by nleclercq** [comment] 2017-06-11 13:57
As far as I know, the SVG mode is not enabled. I didn't change my code at all. I simply installed 12.6.rc4. I didn't noticed the problem in rc3 but it might have been there already. I can downgrade to rc3 and let you know.

**Comment by bryevdv** [comment] 2017-06-11 14:00
Can you provide more information about platform, etc then? As I said I can't reproduce (on OSX)

**Comment by nleclercq** [comment] 2017-06-11 14:29
A downgrade to `0.12.6.rc3` reactivated the  `figure_options['output_backend'] = 'webgl'` bug. One 
commented out, everything works fine and the wheel zoom problem doesn't appear. I then switched back to `0.12.6.rc4` without reactivating the `webgl` option. I can't reproduce the problem is these conditions. Reenabling `webgl` makes wheel zoom problem reappear.

**Comment by bryevdv** [comment] 2017-06-11 14:38
This is why supplying example code is important, to avoid ambiguity. I would never assume that webgl is involved in an issue report unless explicitly mentioned. None of the time I spent testing was with webgl enabled. That said, I can't reproduce this problem on OSX with web enabled either.  Can you please provide:

* a complete code sample
* exact browser / OS version information

**Comment by nleclercq** [comment] 2017-06-11 15:36
Bryan, I'm doing my best to help. 
Attached is the code I use and a notebook that should help to reproduce the problem. See the first cell of the notebook for instructions. The only dependency you must satisfy to run the code is to have `ipywidgets` installed.

I'm running macOS Sierra 10.12.5 (Macbook Pro 13'' 2015). I can reproduce the problem with both Safari 10.1.1 and Chrome 58.0.3029.110. `Webgl` is enabled on the two browsers.  

[WheelZoomIssue6435.zip](https://github.com/bokeh/bokeh/files/1066545/WheelZoomIssue6435.zip)

**Comment by bryevdv** [comment] 2017-06-11 16:34
@nleclercq I appreciate your help, any frustrations are my own. I can reproduce this issue with your notebook, thank you. Perhaps there is something specific to the notebook that is the issue. None of the examples I tried that worked were in the notebook. 

"bokeh+webgl+notebook+server+ipywidgets" is pretty much the ultimate perfect storm of difficult to debug, so since this problem seems confined to a specific set of circumstances, and there is a workaround (don't use webgl) I am inclined to punt on this until after the upcoming release. Am hoping to have a focus on `webgl` for `0.12.7` anyway so that also fits well. 

ping @mattpap

**Comment by bryevdv** [comment] 2017-07-03 20:18
I had hoped to make WebGl a focus of `0.12.7` but it will have to be `0.12.8` cycle

**Comment by mattpap** [comment] 2018-03-26 20:02
Closing as a duplicate of issue #6867 (despite this being an earlier issue).

**Closed by mattpap** 2018-03-26 20:02 UTC
Labels: reso: duplicate, tag: component: bokehjs, tag: webgl, type: bug
