### ISSUE TITLE
Bug in lod_factor only affecting edges and not nodes when using Graph Network

### ISSUE THREAD

**Issue by David-Herman** [bokeh/bokeh#7249] opened 2017-11-24 16:51 UTC
Hello,

I noticed a possible bug in use of a largish graph network of the street network obtained from Open Street Map via the OSMNX library. Panning/Zooming is slow with the large network so I increased the lod_factor to 1000. It removes most of the edges improving the speed but leaves all of the node circles.

While it would be nice to be able to specify separate LOD settings per a glyph I assume that is behavior is a bug and the LOD should be applied uniformly across all glyphs.

I have included the source code, an image of the pan in progress showing most of the edges removed but nodes present, and an image of the graph network as plotted (zoomed in).

A zip file to the graph network file is attached below.

```
import osmnx as ox
import os 
from bokeh.models import Plot, HoverTool, TapTool, BoxSelectTool, BoxZoomTool, ResetTool,WheelZoomTool,PanTool,GraphRenderer
from bokeh.models.graphs import from_networkx
from bokeh.io import show
import networkx as nx
G = ox.load_graphml(os.path.join('..','data','Chicago.graphml')) # From OSM, bigger == Chicago_metro
print 'finished loading network, len=',len(G.nodes())
from bokeh.models import GraphRenderer, StaticLayoutProvider, Oval,Circle
from bokeh.plotting import figure

node_indices = [id for id, d in G.nodes(data=True)]
x = [float(d['x']) for _, d in G.nodes(data=True)]
y = [float(d['y']) for _, d in G.nodes(data=True)]

plot = figure(title="Graph Layout Demonstration", 
             x_range=(min(x),max(x)), y_range=(min(y),max(y)),
              tools="reset,wheel_zoom,pan,box_zoom,tap", 
              toolbar_location='above',output_backend="webgl",
              lod_threshold= 2000,lod_factor=1000)

graph = GraphRenderer()

graph.node_renderer.glyph = Circle(radius=0.00015, fill_color = 'grey', fill_alpha =0.5)
graph.node_renderer.data_source.data = dict(index=node_indices)

graph.edge_renderer.data_source.data = dict(
    start=[ids[0] for ids in G.edges()],
    end=[ids[1] for ids in G.edges()])

### start of layout code
graph_layout = dict(zip(node_indices, zip(x, y)))
graph.layout_provider = StaticLayoutProvider(graph_layout=graph_layout)
#Extract shapely xys
xs=[]
ys=[]
for s,e,d in G.edges(keys=False, data=True):
    if 'geometry' in d.keys():
        xs.append(d['geometry'].coords.xy[0].tolist()) #converty np array to list for  JSON encoding
        ys.append(d['geometry'].coords.xy[1].tolist())
    else:
        xs.append([graph_layout[s][0],graph_layout[e][0]])
        ys.append([graph_layout[s][1],graph_layout[e][1]])

graph.edge_renderer.data_source.data['xs'] = xs
graph.edge_renderer.data_source.data['ys'] = ys
plot.renderers.append(graph)

show(plot)
```

![image](https://user-images.githubusercontent.com/22305345/33218326-5389e604-d10a-11e7-89fb-0c198950a3e7.png)

![image](https://user-images.githubusercontent.com/22305345/33218529-5b2528fa-d10b-11e7-8fc2-34ed8085b61c.png)

[Chicago.zip](https://github.com/bokeh/bokeh/files/1502176/Chicago.zip)

**Comment by bryevdv** [comment] 2017-11-25 19:45
> While it would be nice to be able to specify separate LOD settings per a glyph I assume that is behavior is a bug and the LOD should be applied uniformly across all glyphs.

@David-Herman I think you are coming to the backward conclusion. It is *currently* the case that `lod_factor` applies uniformly across all glyphs. In particular, the generic glyph renderer does this for every glyph:
```
    lod_factor = @plot_model.plot.lod_factor
    @decimated = []
    for i in [0...Math.floor(@all_indices.length/lod_factor)]
      @decimated.push(i*lod_factor)
```
Offhand my guess is that you have <2000 edges, and so the `decimated` list ends up being empty. Can you confirm the number of edges/nodes in this data set?

**Comment by mattpap** [comment] 2017-11-25 20:06
One thing to point out is that this code uses `webgl` backend, which should disable LOD. However, it doesn't, so webgl isn't working and this can have negative effects whatever bokehjs does later (see e.g. #7211, which is also visible here).

**Comment by David-Herman** [comment] 2017-11-26 13:55
This network has 28,528 nodes and 78,765 edges.

**Comment by David-Herman** [comment] 2017-11-26 13:58
Here is the panning mode output when I comment out the webgl backend. Here the nodes and edges are being "decimated" due to the high lod_factor.

![image](https://user-images.githubusercontent.com/22305345/33240663-d0d67c02-d287-11e7-9eca-8609ab01940b.png)

**Comment by David-Herman** [comment] 2017-11-26 14:01
I do not see any error in the console with webgl enabled indicating a failure to load/use webgl.

**Comment by David-Herman** [comment] 2017-11-26 14:15
Please let me know what other information I can provide.

**Comment by David-Herman** [comment] 2017-11-26 14:21
another comment, the webgl also shows edges falling outside of the axis edge which is related to this bug, #6867

![image](https://user-images.githubusercontent.com/22305345/33240841-0c9e4c62-d28b-11e7-9f13-35a7a3a1a65e.png)

**Comment by mattpap** [comment] 2017-11-26 18:01
> I do not see any error in the console with webgl enabled indicating a failure to load/use webgl.

You may need to enable verbose logging in devtools, but there may be no indication at all (I presume; this is uncharted territory for us at this point).

> I also notice the rendering is much more responsive with webgl enabled rather than not.

That's the point. With webgl backend we can take advantage of hardware acceleration for not only painting, but also some other CPU heavy tasks, e.g. masking of data.

**Comment by mattpap** [comment] 2017-11-26 18:05
> I do not see any error in the console with webgl enabled indicating a failure to load/use webgl.

We may need to add an equivalent of youtube's "stats for nerds" to give users easy access to bokehjs' status.

**Comment by bryevdv** [comment] 2017-11-26 18:49
At this point I think we might want to add a warning to `webgl` usage that states that it has known issues. It may work for particular uses but this should be verified. I definitely want to reimplement webgl support from the ground up probably with ReGL but that's a project for next year.

**Comment by mattpap** [comment] 2017-11-26 19:41
We can at least make bokehjs initialize into a consistent state if webgl fails. Existing implementation must miss some failure modes, and proceeds with software renderer, but uses webgl code paths in some cases (e.g. clipping, which results with overdrawn axes).

**Comment by David-Herman** [comment] 2017-11-26 23:02
I enabled debug verbosity for the the BokehJS but did not see any further errors then the info mode.

![image](https://user-images.githubusercontent.com/22305345/33245270-6f6429be-d2d3-11e7-95cb-42cccf6e7874.png)

**Comment by mattpap** [comment] 2017-11-27 08:42
@David-Herman, if there will be any errors, it won't be from bokeh. You need to click on "default levels" (next to "filter"), and choose "verbose".

**Comment by David-Herman** [comment] 2017-11-27 13:10
Hello,

Thanks. Here is the console dump with some zooming and panning. It look like there may be an error thrown from Underscore.js 1.8.3 but it occurs with and without webgl enabled.

`eq.js:6 [Violation] 'requestAnimationFrame' handler took 244ms`


David

WebGL debug console log below.

```
logging.js:132 [bokeh] setting log level to: 'debug'
embed.js:215 [bokeh] embed: computed ws url: ws://localhost:5006/route_RevC/ws
connection.js:27 [bokeh] Creating websocket 0 to 'ws://localhost:5006/route_RevC/ws' session 'KRayKkNbNwnIzwJPf4xQtY40YQVSGpTCqGdDkJVVHUYG'
connection.js:192 [bokeh] Websocket connection 0 is now open
connection.js:152 [bokeh] Pulling session for first time
document.js:662 [bokeh] Creating Document from JSON
document.js:673 [bokeh] Library versions: JS (0.12.10)  /  Python (0.12.10)
toolbar_base.js:171 [bokeh] Toolbar: activating tool: PanTool (3365b1dd-97bc-4cd9-a9a6-e9ce67222d32) for event type 'pan'
toolbar_base.js:171 [bokeh] Toolbar: activating tool: TapTool (a75f0937-652f-435b-8d7b-56fd60d13565) for event type 'tap'
plot_canvas.js:957 [bokeh] PlotCanvas initialized
document.js:298 [bokeh] Adding root: Plot(8f663605-0918-4ebc-99e2-2edba13c6322)
plot_canvas.js:967 [bokeh] PlotCanvas attached to document
connection.js:166 [bokeh] Sending 9 changes from model construction back to server
connection.js:171 [bokeh] Created a new session from new pulled doc
canvas.js:57 [bokeh] CanvasView initialized
glyph_renderer.js:179 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): set_data finished in 60ms
glyph_renderer.js:179 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): set_data finished in 29ms
ui_events.js:141 [bokeh] Button tool: ResetTool
plot_canvas.js:137 [bokeh] PlotView initialized
embed.js:263 Bokeh items were rendered successfully
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 1559ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 59ms
plot_canvas.js:191 [bokeh] drawing with WebGL
plot_canvas.js:674 [bokeh] initial ranges set
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 1733ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 30ms
plot_canvas.js:191 [bokeh] drawing with WebGL
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 1796ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 42ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 1844ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 1816ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 34ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 1855ms
bokeh.min.js?v=ef6e00d155662bd375c6bec8886eba7f:1 [Violation] 'message' handler took 1106ms
bokeh.min.js?v=ef6e00d155662bd375c6bec8886eba7f:1 [Violation] 'message' handler took 1009ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 1544ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 12ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 1562ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 1613ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 10ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 1629ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 1513ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 4ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 1523ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 1486ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 3ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 1496ms
toolbar_base.js:167 [bokeh] Toolbar: deactivating tool: PanTool (3365b1dd-97bc-4cd9-a9a6-e9ce67222d32) for event type 'pan'
toolbar_base.js:171 [bokeh] Toolbar: activating tool: BoxZoomTool (972db847-a92d-47f9-8f90-9524aaccdd72) for event type 'pan'
bokeh.min.js?v=ef6e00d155662bd375c6bec8886eba7f:1 [Violation] 'message' handler took 223ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 684ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 26ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 789ms
toolbar_base.js:167 [bokeh] Toolbar: deactivating tool: BoxZoomTool (972db847-a92d-47f9-8f90-9524aaccdd72) for event type 'pan'
toolbar_base.js:171 [bokeh] Toolbar: activating tool: PanTool (3365b1dd-97bc-4cd9-a9a6-e9ce67222d32) for event type 'pan'
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 244ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 38ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 287ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 233ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 6ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 243ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 244ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 5ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 255ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 236ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 3ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 244ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 245ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 11ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 262ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 234ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 10ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 250ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 234ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 3ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 318ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 218ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 18ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 320ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 223ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 16ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 244ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 221ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 3ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 230ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 604ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 3ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 611ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 597ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 3ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 606ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 631ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 6ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 642ms
canvas.js:77 [bokeh] Rendering CanvasView with width: 600, height: 600, pixel ratio: 1.5
glyph_renderer.js:335 [bokeh] MultiLine GlyphRenderer (ee45b3eb-7a9b-4f04-ab73-c0446e36564c): render finished in 625ms
glyph_renderer.js:335 [bokeh] Circle GlyphRenderer (5795dce7-dcc2-492b-a33a-6479494e7683): render finished in 2ms
plot_canvas.js:191 [bokeh] drawing with WebGL
eq.js:6 [Violation] 'requestAnimationFrame' handler took 707ms
```

**Comment by David-Herman** [comment] 2017-11-28 03:32
A related webgl only behavior I recently encountered with the tap tool. If I zoom into a single node, tap the node, and then press reset the node's screen size matches the zoomed in size until I pan/unselect the node where it will return to the nominal size at the present zoom setting.

The image below demonstrates the behavior after pressing reset and the image on the right shows the nominal node size after panning.

![image](https://user-images.githubusercontent.com/22305345/33301195-6e1a16dc-d3c2-11e7-97a9-e95e776ec597.png)

**Comment by mattpap** [comment] 2018-03-26 15:17
Closing as a duplicate of #6867.

**Closed by mattpap** 2018-03-26 15:17 UTC
Labels: type: discussion
