### ISSUE TITLE
Rendering issues with webgl and google maps (bokeh-notebooks introduction)

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3652] opened 2016-01-13 23:07 UTC
From @pzwang: the Google Map underlay for the webgl plot no longer seems to render in Chrome.  

https://nbviewer.jupyter.org/github/bokeh/bokeh-notebooks/blob/master/tutorial/00%20-%20intro.ipynb
![image](https://cloud.githubusercontent.com/assets/1796208/12310673/6072dba4-ba06-11e5-93b2-60bca451f9f1.png)

Follow-ups:
-  The map underlayers render fine on Safari, but no webgl, so no points show.  But on Chrome, even incognito mode, I can't see anything. 
- @hsparra - I get the same as Peter using Chrome and Firefox. In Safari I get the map but not the points.
- @almarklein - On Windows, with FF, Chrome, and Edge, I see only points, no map. Note that you can add “?webgl=0” to disable webgl, which should make the visualization work on Safari (still no map though).
- @almarklein - Basically, our webgl does not work on Safari. We’ve been meaning to investigate this further, but we seem to not have gotten to it.

**Comment by bryevdv** [comment] 2017-06-07 14:14
maps stuff should be resolved, the rest is dupe of #5589

**Closed by bryevdv** 2017-06-07 14:14 UTC
Labels: tag: webgl, type: discussion
