### ISSUE TITLE
GMapPlot doesn't display anything in Jupyter v.4

### ISSUE THREAD

**Issue by Zebreu** [bokeh/bokeh#3737] opened 2016-01-25 18:35 UTC
Hi,

Just started using Bokeh more extensively and I wanted to display maps within a Jupyter notebook. I tried running the example provided in the repo (with the world_cities dataset) and while it displays when ran alone, it only displays a blank area in Jupyter (and I could only see the data once (without a map) when I refreshed, but this is not consistent). I have both latest versions for bokeh and Jupyter (from Anaconda). 

```
import bokeh
import bokeh.plotting as plotting
plotting.output_notebook()
from bokeh.io import push_notebook

from bokeh.resources import INLINE
from bokeh.models.glyphs import Circle
from bokeh.models import (
    GMapPlot, Range1d, ColumnDataSource,
    PanTool, WheelZoomTool, GMapOptions)
from bokeh.resources import INLINE
from bokeh.sampledata.world_cities import data


x_range = Range1d(-160, 160)
y_range = Range1d(-80, 80)

map_options = GMapOptions(lat=15, lng=0, zoom=10)

plot = GMapPlot(
    x_range=x_range,
    y_range=y_range,
    plot_width=1000,
    plot_height=500,
    map_options=map_options,
    title="Cities of the world with a population over 5,000 people.",
    webgl=True,
)
circle = Circle(x="lng", y="lat", size=5, line_color=None, fill_color='firebrick', fill_alpha=0.2)
plot.add_glyph(ColumnDataSource(data), circle)
plot.add_tools(PanTool(), WheelZoomTool())
plotting.show(plot)
```

**Comment by mattpap** [comment] 2016-01-25 19:00
I can confirm this, no map on first run, no map and no glyphs after kernel restart. Page refresh causes glyphs to reappear, but still no map. No meaningful error messages in JS console. There are some related to comms when there are no glyphs rendered. I presume those errors obscure relevant information.

**Comment by mattpap** [comment] 2016-01-25 19:05
I didn't investigate this in detail yet, but kernel restart is a problem on its own. Just removing output cells and restarting the kernel doesn't reset the state entirely, because bokehjs is still loaded on the page (until page reload).

**Comment by birdsarah** [comment] 2016-02-10 21:04
fwiw I'm finding this problem to be occurring more often than not, but definitely intermittently, sometimes the plot does render on first run:

<img width="631" alt="screen shot 2016-02-10 at 1 03 21 pm" src="https://cloud.githubusercontent.com/assets/1796208/12961679/b2e8bcea-cff6-11e5-8e71-b8d3f86d6bf9.png">

May be there's an event / ordering / callback problem?

**Comment by Qmage** [comment] 2016-02-12 09:47
I'm also facing this problem when using GMapPlot with jupyter notebook, it seems like the map will only appear when it is first loaded to the browser, any subsequent loads will result in a blank white map

**Comment by sanga** [comment] 2016-02-12 11:15
Same thing here. This is kind of a showstopper for me personally. Would love to see it fixed

**Comment by dangetman** [comment] 2016-03-16 15:39
Ditto. Is a solution expected for this issue anytime soon?

**Comment by bryevdv** [comment] 2016-03-16 17:00
Can everyone report what versions they are using / have tried. It is always important to report version information with every issue.

**Comment by dangetman** [comment] 2016-03-16 17:05
Updated per your request @bryevdv

**Comment by bryevdv** [comment] 2016-03-16 17:08
@mattpap I think the notebook comms are a red herring. I have issues even when comms succeed (which seems to happen on 0.11) and also when I put a `try` / `catch` around comms init to ignore errors. What about notebook versions? Perhaps something changed on the Jupyter side.

**Comment by bryevdv** [comment] 2016-03-16 17:27
Also observed with with Bokeh 0.10 and notebook version 4.0.6 so the notebook comms are definitely not the proximate cause. Have gmap plots in notebooks ever been demonstrated? (Honestly am not aware / don't remember) Can anyone provide a known working configuration?

**Comment by bryevdv** [comment] 2016-03-16 17:39
Also seems to happen with Bokeh 0.8. As far as I can tell this has either never worked, or something external to Bokeh has changed to make it not work.

**Comment by bryevdv** [comment] 2016-03-16 17:51
In any case, unfortunately it seems this will be non-trivial work to investigate (I was hoping I might find a quick fix on this flight).  Debugging in the notebook is already time-consuming, throw in a third party library and it will be a real effort. There are several other immediately pressing priorities so I can't say that we'll be able to devote attention to it anytime particularly soon. I very much wish I could say something more promising, but the reality of finite time and resources and human limits is what it is. As a workaround, you might try the new `TileRenderer`, which seems to work reliably for me:

<img width="1152" alt="screen shot 2016-03-16 at 10 48 09 am" src="https://cloud.githubusercontent.com/assets/1078448/13822932/ca7ce0f0-eb64-11e5-954d-01e1a652990b.png">

**Comment by sanga** [comment] 2016-03-16 19:16
Sorry this is so vague, but if it's of any value, gmap plots/jupyter used to work reliably for me. From memory that was before christmas and at a guess I'd say bokeh 0.10 (and possibly jupyter < 4).

**Comment by sanga** [comment] 2016-03-16 19:57
To me it seems like they load correctly if I refresh a notebook (i.e. F5) with embedded graphs, but if I execute a cell to generate a graph then that may or may not create an empty gmap.

**Comment by sanga** [comment] 2016-03-16 20:28
For the record it still seems to have the same broken behaviour in ipython notebook 4.0

**Comment by reyale** [comment] 2016-03-22 01:52
Same issue, no map, no glyphs in the notebook.  I can get map to render in notebook if I re-zoom the page (ctrl-+) but glyph still do not render. 

bokeh == 0.11.1
ipython == 4.1.2
python == 2.7.3
jupyter == 4.1.0

**Comment by rparrapy** [comment] 2016-04-20 18:47
Same issue here, with:
bokeh                     0.11.1
ipython                   4.1.2
python                    2.7.11

**Comment by jjardel** [comment] 2016-04-21 18:22
Same issue with 
bokeh 0.11.1
ipython 4.0.0
python 2.7.9
jupyter 1.0.0

I rolled back to bokeh 0.10.0 and the problem went away.

**Comment by bryevdv** [comment] 2016-04-21 20:18
Have not forgotten this, but there is currently some fairly heavy lifting refactoring going on on some of the BokehJS codebase and it does not make sense to get into this until that work is complete.

**Comment by colliand** [comment] 2016-07-17 00:05
I continue to experience problems that appear to be aligned with the issues highlighted in this thread.

**Comment by bryevdv** [comment] 2016-07-17 06:29
Please try the latest dev build

**Comment by colliand** [comment] 2016-07-19 05:46
I tried with 
>`pip install --upgrade --pre -i https://pypi.anaconda.org/bokeh/channel/dev/simple bokeh --extra-index-url https://pypi.python.org/simple/`  
but continue to experience the same issues.

**Comment by bryevdv** [comment] 2016-07-19 13:15
@colliand In general it is important to provide as much information as possible (to err on the side of too much). This is especially true in cases where the issue is not happening to everyone / is difficult to reproduce. What is really needed:

* a minimal complete code sample to reproduce the problem
* relevant version information (libraries, OS, browsers)
* any shell console or browser JavaScript console output

Also we need a precise accurate description of what happened. Is there no output at all? Is there a plot with glyphs but no map? Is there a plot but neither glyphs nor a map? 

Can you also first confirm that you have configured the GMap with an google API key? Google made a recent change (that we have no control over at all) requiring all usage of Google Maps to include an API key, which means that all users must supply their own API keys now for GMapPlot to function.

**Comment by colliand** [comment] 2016-07-24 19:23
Thanks @bryevdv. I appreciate your help. I've exposed my work here: [http://nbviewer.jupyter.org/github/colliand/public-notebooks/blob/master/google-maps/pims-map.ipynb](http://nbviewer.jupyter.org/github/colliand/public-notebooks/blob/master/google-maps/pims-map.ipynb).  I've made some progress but still have a few issues:  

1. The map does not load after executing the cell that generates the map. The frame appears around a white unfilled map area. I've observed that changing the size of the browser window triggers the appearance of the map.
2. The map that appears is not centered at the latitude, longitude pair requested `GMapOptions`.
3. The requested glyphs do not appear on the map when it first appears. I've observed that executing wheel zoom causes the glyphs to appear. 

Here is a [screen capture of my JavaScript console](https://wwejubwfy.s3.amazonaws.com/Developer_Tools_-_httpspims.jupyter.causerjcolliannotebookscolliand-publicgoogle-mapspims-map.ipynb-2016-07-24-12-22-03.jpg). I welcome your advice.

**Comment by bryevdv** [comment] 2016-07-24 19:36
@colliand Can you confirm that the version you are running in the notebook is actually the latest dev build? (printing `bokeh.__version__` will do) I would never expect to see that comms message anymore in the console with the latest dev build.

**Comment by colliand** [comment] 2016-07-24 19:48
0.12.1dev2

**Comment by bryevdv** [comment] 2016-07-25 12:51
does passing `resources=INLINE` to `output_notebook` have any effect?

**Comment by canavandl** [comment] 2016-07-25 16:21
I'm able to reproduce the issue described by @colliand and using his notebook from nbviewer.

With a hard-refreshed browser window (with the cache deleted), the gmap plot will load the first time. Rerunning the cell containing the `show` call causes a white window (containing the google watermark) to appear instead of the map:

<img width="943" alt="screen shot 2016-07-25 at 11 13 52 am" src="https://cloud.githubusercontent.com/assets/2198981/17108420/03c8bb9e-5259-11e6-8ccb-9a00db5b1b6c.png">

Opening the dev tools will cause the plot to be rendered (presumably doing so causes the page to reflow), but the map coords aren't the requested ones and the circle glyphs are missing:

<img width="938" alt="screen shot 2016-07-25 at 11 15 15 am" src="https://cloud.githubusercontent.com/assets/2198981/17108467/4a2136e8-5259-11e6-834d-01da7271de7a.png">

Inspecting the network activity tab in the dev tools, it seems that there isn't a gmap response payload when running the `show` method a second time even though AFAICT the request is happening. I would think that it's an issue of how we're interacting w/ the Google maps API, but it will require further investigation.

(thanks @colliand for the helpful notebook and bug description!)

**Comment by jakubLangr** [comment] 2016-08-17 21:34
I can confirm exactly the behaviour that @canavandl has described: 

1. Map does not show but points do
2. Opening dev tools makes map appear but points do

I'd also add that a brand new instance of IPython ntb creates the plot for about ~1 second correctly: map loads, points appear wrongly (1 sec), points move to the correct position (1 sec), map disappears as:
![screen shot 2016-08-17 at 10 30 17 pm](https://cloud.githubusercontent.com/assets/1884004/17753985/40006840-64ca-11e6-9168-54d861e44181.png)

(Code almost unchanged from here http://bokeh.pydata.org/en/0.11.1/docs/user_guide/geo.html, the only thing is output_file -> output_notebook)

<code> 
bokeh                     0.12.0                    <pip>
conda                     4.1.8                    py35_0  
conda-env                 2.5.2                    py35_0  
ipython                   5.0.0                    py35_0    conda-forge
ipywidgets                5.1.5                    py35_0    conda-forge
jsonschema                2.5.1                    py35_0    conda-forge
jupyter_client            4.3.0                    py35_0    conda-forge
jupyter_core              4.1.0                    py35_0    conda-forge
nbformat                  4.0.1                    py35_0    conda-forge
notebook                  4.2.1                    py35_0    conda-forge
numpy                     1.10.4          py35_blas_openblas_201  [blas_openblas]  conda-forge
openblas                  0.2.18                        3    conda-forge
pandas                    0.18.1              np110py35_0    conda-forge
</code>

**Comment by colliand** [comment] 2016-08-28 18:44
@bryevdv wrote:
>does passing resources=INLINE to output_notebook have any effect?

I changed the import calls as follows: 
```
## output_notebook(resources=INLINE)
from bokeh.resources import INLINE
output_notebook(resources=INLINE)
```
I observed no change in behavior. The map launches with a blank output panel. Resizing the browser causes a map to appear with no glyphs. Wheel zoom causes the glyphs to appear.

**Comment by Kevin-McIsaac** [comment] 2016-09-21 23:01
I also took the [example from the docs](http://bokeh.pydata.org/en/0.11.1/docs/user_guide/geo.html)
 and added by API key and set output_notebook(resources=INLINE)

On the first run the map is correct, on subsequent the map is blank. resizing the window refreshes the map but the dots are missing. Zooming with the wheel restores the dots. 

I also noticed the Wheel Zoom discards the first 10 wheel clicks, this make the zooming feel odd. 

bokeh.__version__ '0.12.2'
notebook server is 4.2.3
Python 3.5.2 
running on a linux (AWS) server from aChromOS Version 53.0.2785.103

**Comment by themrmax** [comment] 2016-11-21 21:55
I get the same behaviour as @Kevin-McIsaac however reloading the page restores the map and markers for me. I also am getting a `MISSING_GOOGLE_API_KEY` warning despite providing an `api_key` to the GMapPlot (and it is included in the call to the google maps API).

**Comment by benuklove** [comment] 2016-11-21 22:26
@themrmax I once accidentally used a browser key.  Make sure it is a Google *server* API key.
I also have the zoom by scrolling delay.

**Comment by themrmax** [comment] 2016-11-23 02:28
@benuklove I'm having trouble working out the different types of keys; i'm using the one from https://developers.google.com/maps/documentation/javascript/get-api-key is this the correct one?

**Comment by benuklove** [comment] 2016-11-23 04:37
@themrmax Yes that looks right.  Make sure the JavaScript API is actually *enabled*.
On your API Manager dashboard, for your project, it lists the APIs that are enabled.

**Comment by bryevdv** [comment] 2017-01-10 00:01
There's alot of cruft in this issue, I am not sure if this is a dupe of #4835 It seems like it might be.

**Comment by benuklove** [comment] 2017-01-10 02:49
@bryevdv it does look like the same/similar issue.  
Also, I can remove my replies to themrmax as they seem Google interface related.  Is that what you mean?

**Comment by bryevdv** [comment] 2017-01-10 02:51
@benuklove I just mean there have been various issues / possible issues and I think several of them got combined in this issue. It's fine, I am going to work off the other issue first and see if it solves the problems described here too.

**Closed** 2017-01-26 23:13 UTC
Labels: tag: regression, type: bug

**Comment by udothemath1984** [comment] 2017-08-04 01:27
Hi there,

Is there any update on the topic? I was trying the [tutorial](http://bokeh.pydata.org/en/latest/docs/user_guide/geo.html#google-maps-support), added by API key, and set output_notebook(resources=INLINE) but the issue remains. I am using 

bokeh 0.12.5
Python 3.6.0 :: Anaconda custom (x86_64)
IPython.__version__ '5.1.0'

Am I missing something? On top of that, is there a quick way (common script) to display the version of all the essential program (bokeh and Python etc)? Really appreciate your help.

**Comment by yrevar** [comment] 2019-05-03 23:26
I was seeing similar output as posted by @jakubLangr. It seems to be related to Google Maps API keys. I have often noticed that when I use wrong key (accidently) Google Maps rejects the request and gets annoyed for several minutes or hours and doesn't show map images even with the right key. Maybe such information is cached somewhere because when I switched the browser it starts working.

**Comment by bryevdv** [comment] 2019-05-04 05:32
> when I use wrong key (accidently) Google Maps rejects the request and gets annoyed for several minutes

If so that's an issue with google or the browser we have no control over. We simply pass the key to the api exactly as you provide it. The solution is not to use the wrong key.
