### ISSUE TITLE
DataTables overlapping when in row or gridplot

### ISSUE THREAD

**Issue by jackalack** [bokeh/bokeh#6025] opened 2017-03-20 18:23 UTC
I want to display two DataTables in one row.  When I do so, the two DataTables are not spaced apart and overlap.  Example Code and screenshot below. 
```
import numpy as np

from bokeh.io import show
from bokeh.models import ColumnDataSource, TableColumn, DataTable
from bokeh.layouts import widgetbox, row
from bokeh.plotting import figure

x = [1,2,3]
y1 = np.random.randn(3)
y2 = np.random.randn(3)

def create_data_table(x,y):
    source = ColumnDataSource(data=dict())
    source.data = {'index': x, 'value':y}
    columns = [TableColumn(field="index", title="index"),TableColumn(field="value", title="value")]
    data_table = DataTable(source=source, columns=columns)
    table = widgetbox(data_table)
    return table
table1 = create_data_table(x,y1)
table2 = create_data_table(x,y2)
show(row(table1,table2))

```

![screen shot 2017-03-20 at 11 22 04 am](https://cloud.githubusercontent.com/assets/7672771/24115091/7b8e484e-0d5f-11e7-9aaa-8ddeba02b13a.png)

**Comment by bryevdv** [comment] 2017-06-04 17:28
I updated the code with  missing imports. @jackalack please always leave *complete* test code. I know it probably seems like a small thing, but when you are on the side looking at hundreds of open issues, having to fill in the gaps actually adds up to a substantial burden. Since you already have all the code to reproduce at hand, the best thing is just to include it all so there are no missing details to fill in, that is actually a huge help to maintainers and is very much appreciated. 

This is still an issue as of `0.12.6.dev7` but setting the width on the data table (and not putting it in a widgetbox) seems to work around:
```
import numpy as np

from bokeh.io import show
from bokeh.models import ColumnDataSource, TableColumn, DataTable
from bokeh.layouts import widgetbox, row
from bokeh.plotting import figure

x = [1,2,3]
y1 = np.random.randn(3)
y2 = np.random.randn(3)

def create_data_table(x,y):
    source = ColumnDataSource(data=dict())
    source.data = {'index': x, 'value':y}
    columns = [TableColumn(field="index", title="index"),TableColumn(field="value", title="value")]
    data_table = DataTable(source=source, columns=columns, width=400)
    return data_table
table1 = create_data_table(x,y1)
table2 = create_data_table(x,y2)
show(row(table1,table2))
```
<img width="890" alt="screen shot 2017-06-04 at 12 27 23" src="https://cloud.githubusercontent.com/assets/1078448/26763877/2cc7113e-4921-11e7-939f-1cd7e67b0628.png">

Given that there is a potential workaround, I am moving to the next milestone since a release with the tornado fix needs to happen ASAP.

**Comment by mattpap** [comment] 2019-03-18 14:01
This was fixed by the new layout:
![image](https://user-images.githubusercontent.com/27475/54535338-a1c90400-498e-11e9-9078-6c41691b4f18.png)

**Closed by mattpap** 2019-03-18 14:01 UTC
Labels: tag: layout, tag: widgets, type: bug
