### ISSUE TITLE
[BUG] Hover tool over multi_line glyph spews errors to javascript console

### ISSUE THREAD

**Issue by j-carson** [bokeh/bokeh#10716] opened 2020-11-22 04:17 UTC
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.2.3
python 3.8.2
jupyter lab 2.0.1
macos big sur 

#### Description of expected behavior and the observed behavior
Hover tool spews lots of errors to javascript console with multi_line glyph. 

Expected behavior: bars change from blue to red on hover. Works, but spews errors. (I had been trying create a hover tool that displays the "label" column in df. That code is not necessary to produce error.)

Observed behavior: The color actually changes, but the errors are on the right side of the screen shot.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.io import output_notebook, show
from bokeh.plotting import figure

import pandas as pd

output_notebook()

some_data = dict(
xs=list(zip(range(10),range(10))),
ys=list(zip(range(10),range(1,11))),
label=list('abcdefghij')
)
df = pd.DataFrame(some_data)

plot = figure(
    plot_width=400, 
    plot_height=400, 
    tools = 'pan,save,reset,hover',
)

plot.multi_line(
    xs='xs',
    ys='ys',
    source=df, 
    color='blue',
    hover_color='red',
    line_width=5,
)
show(plot)

```

#### Stack traceback and/or browser JavaScript console output
Uncaught TypeError: y._xs[o] is undefined
    _update bokeh-2.2.3.min.js:569
    connect bokeh-2.2.3.min.js:240
    emit bokeh-2.2.3.min.js:181
    inspect bokeh-2.2.3.min.js:258
    _inspect bokeh-2.2.3.min.js:569
    _move bokeh-2.2.3.min.js:569
    r bokeh-2.2.3.min.js:497
    connect bokeh-2.2.3.min.js:240
    emit bokeh-2.2.3.min.js:181
    trigger bokeh-2.2.3.min.js:497
    _trigger bokeh-2.2.3.min.js:497
    _trigger bokeh-2.2.3.min.js:497
    _mouse_move bokeh-2.2.3.min.js:497
    d bokeh-2.2.3.min.js:497
    d bokeh-2.2.3.min.js:497
    lazy_initialize bokeh-2.2.3.min.js:495
    i bokeh-2.2.3.min.js:284
    build_view bokeh-2.2.3.min.js:284
    r bokeh-2.2.3.min.js:572
    add_document_standalone bokeh-2.2.3.min.js:572
    embed_items_notebook bokeh-2.2.3.min.js:579
    embed_document vendors~main.b00fa7524360b3b7a765.js line 154326 > eval:6
    <anonymous> vendors~main.b00fa7524360b3b7a765.js line 154326 > eval:10
    <anonymous> vendors~main.b00fa7524360b3b7a765.js line 154326 > eval:26
    evalInContext index.js:8
    renderJavascript index.js:16
    render index.js:39
    renderModel widgets.js:43
    createRenderedMimetype widget.js:429
    createOutputItem widget.js:401
    _insertOutput widget.js:384
    onModelChanged widget.js:216
    invokeSlot index.js:478
    emit index.js:435
    emit index.js:108
    _onListChanged model.js:231
    invokeSlot index.js:478
    emit index.js:435
    emit index.js:108
    push observablelist.js:135
    _add model.js:207
    add model.js:128
    _onIOPub widget.js:91
    _handleIOPub future.js:216
    handleMsg future.js:186
bokeh-2.2.3.min.js:569:4587

#### Screenshots or screencasts of the bug in action

![bokeh_error](https://user-images.githubusercontent.com/44308120/99893483-9f27b300-2c35-11eb-9b47-c678503e6400.gif)

**Comment by mattpap** [comment] 2020-11-22 10:53
This is a duplicate of issue #10458.

**Closed by mattpap** 2020-11-22 10:53 UTC
Labels: TRIAGE
