### ISSUE TITLE
datetime X axis shows ms with timestamp data that is separated by 4 hours

### ISSUE THREAD

**Issue by msarahan** [bokeh/bokeh#4056] opened 2016-03-23 19:32 UTC
![screen shot 2016-03-22 at 11 14 52](https://cloud.githubusercontent.com/assets/38393/13998031/df4558e8-f102-11e5-9023-730fe816a157.png)

This plot was built with close to Bokeh master: https://github.com/msarahan/bokeh/commit/c1dda0f2861355ab2189f6b7e8b2d1da2751b7f9

Data attached.  

[sentiment_data.txt](https://github.com/bokeh/bokeh/files/186706/sentiment_data.txt)

Command to plot (with modified Bokeh codebase):

```
f = bokeh.charts.Area(input_data[::-1], xlabel="post timestamp", stack=True,
     legend="top_left", x_mapper_type="datetime")
show(f)
```

Dates should ideally be something like days (2016-03-16), potentially with hour values as zoom increases.

For reference, this works OK - so it appears to be an issue with the charts API:

```
f=figure(width=640, height=480, x_axis_type="datetime")
f.line(pd.to_datetime(["2016-01-25 13:04:22.919370", "2016-01-25 14:04:22.919370", "2016-01-25 15:04:22.919370"]), [1, 2, 3])
show(f)
```

**Comment by bryevdv** [comment] 2016-03-23 19:45
Maybe, do we know what the actual type of the datetime data column is? My guess is that it is some type we are not handling, that needs to be converted to milliseconds since epoch. This is the code block in our encoder that does all the conversions:

https://github.com/bokeh/bokeh/blob/master/bokeh/core/json_encoder.py#L32-L57

Is there some pandas specific type that is missing there?

**Comment by msarahan** [comment] 2016-03-23 19:47
Sadly, I wish it was that easy.  It lines up with the trivial plot example I posted:

    dtype='datetime64[ns]', name=u'post_timestamp', length=296, freq=None)

**Comment by bryevdv** [comment] 2016-03-23 20:07
Will require tracing through some code I think, a little tentative `grep`ing for possibly suspicious things did not turn up anything. @msarahan if you can attach a minimal example that produces this problem with non-modified Bokeh (I assume its a problem with a regular `Area` chart too) that would be very helpful.

**Comment by msarahan** [comment] 2016-03-23 20:30
Here's python code converted from a notebook - if there's a better format, let me know.

```

# coding: utf-8

import pandas as pd
from bokeh.io import output_notebook, show
import bokeh.charts
from bokeh.plotting import figure
output_notebook()

# load data and make index into datetime
df = pd.read_csv("sentiment_data.txt")
df["post_timestamp"] = pd.to_datetime(df["post_timestamp"])
df.set_index("post_timestamp", inplace=True)

# ground truth - what things should look like.
f=figure(x_axis_type="datetime")
f.line(df.index, range(len(df.index)))
show(f)

# The area chart
f2=bokeh.charts.Area(df)
show(f2)
```

The area chart here shows the same issue, as you suspected.

**Comment by msarahan** [comment] 2016-03-30 16:08
I don't need this fixed on any immediate time scale.  I have switched to using the plotting API, which works fine.

**Comment by anoother** [comment] 2016-04-11 15:04
This is affecting me, too. Example on the way.

**Comment by anoother** [comment] 2016-04-11 15:51
Here's an example; 1 minute turns into 1000us:

```
#!/usr/bin/env python
 
from bokeh import charts
from pandas import DataFrame
 
t0 = datetime.now()
t1 = t0 + timedelta(minutes=1)
 
data = {
    'class1': {
        t0: 1,
        t1: 2,
    },
    'class2': {
        t0: 1.5,
        t1: .333,
    }
}
 
frame = DataFrame.from_dict(data)
 
charts.output_file('example.html')
c = charts.Area(frame)
charts.show(c)
```

**Comment by bryevdv** [comment] 2016-04-11 18:29
ping @fpliger I think we ought to try and fix this for `0.12`, thoughts? My impression is that there is something in `bokeh.charts` that is causing a scaling factor to be misapplied, or perhaps more likely: there is a pandas-specific column type that is only used with `bokeh.charts` typically, that is not getting handled correctly.

**Comment by chefren** [comment] 2017-03-15 06:39
I tested with pandas==0.19.2 and bokeh==0.12.4

It looks ok now

![screen shot 2017-03-15 at 5 37 05 pm](https://cloud.githubusercontent.com/assets/2918150/23936435/4780f130-09a6-11e7-8f75-cd64b6322611.png)

**Comment by bryevdv** [comment] 2017-03-15 13:18
That's good to hear. I will close this then, please feel to re-open if it is still somehow reproducible with >= `0.12.4`

**Closed by bryevdv** 2017-03-15 13:18 UTC
Labels: type: bug

**Comment by beRto-** [comment] 2017-04-06 03:34
I am having what appears to be this very same problem (that is, plotted data is "off" by 4 hours). I am running bokeh 0.12.4, Python 2.7.12, Windows 7.

The minimal example code I am using manually converts two strings to datetime objects, and then attempts to plot them in bokeh. I am using strings, because I eventually plan to extract this data from an SQLite database, and the datetime library because I already use that it my main code (would rather not introduce numpy just for this).

My example attempt to plot data at 08:00 and 15:00, but they instead come out shifted 4 h ahead; 12:00 and 19:00, respectively.

**CODE**
```
import datetime as dt
from bokeh.plotting import figure, output_file, show

def plotTheData(xvals, yvals, filename="datetime.html", title="boom!"):
    output_file(filename, title=title)
    p = figure(width=800, height=500, x_axis_type="datetime")
    p.circle(xvals, yvals, size=6)
    show(p)

if __name__ == '__main__':
    datetimes = [
        dt.datetime.strptime("2017-03-30 15:00:05","%Y-%m-%d %H:%M:%S"),
        dt.datetime.strptime("2017-03-30 08:00:05","%Y-%m-%d %H:%M:%S")
        ]
    doorstates = [0,1]
    plotTheData(datetimes,doorstates)
    for r in zip(datetimes, doorstates):
        print r
        print r[0].strftime("%Y-%m-%d %H:%M:%S"), r[1]
```

**OUTPUT** (datetimes at 08:00 and 15:00, as expected)
```
(datetime.datetime(2017, 3, 30, 15, 0, 5), 0)
2017-03-30 15:00:05 0
(datetime.datetime(2017, 3, 30, 8, 0, 5), 1)
2017-03-30 08:00:05 1
```

**bokeh plot** (points shown shifted ahead by 4h, at 12:00 and 19:00)
![bokeh_plot_off_by_4h](https://cloud.githubusercontent.com/assets/10589057/24736806/5b3b7160-1a58-11e7-989e-642d517e0428.png)
