### ISSUE TITLE
SVG output bleeds past axis

### ISSUE THREAD

**Issue by ColinOrionChandler** [bokeh/bokeh#6787] opened 2017-08-19 23:12 UTC
Bokeh: 0.12.6
Python: 3.6.0
OS: MacOS 10.12.6
Browser: Safari 10.1.2 (12603.3.8) (also tried Chrome 60.0.3112.101 (Official Build) (64-bit) and FireFox 55.0.2 (64-bit))
Selenium: 3.5.0 (same issue in 3.3.3)
Pillow: 4.2.1-py36_0 (same issue with 4.0.0-py36_0)
phantomjs: 2.1.1
olefile: 0.44-py36_0

Description:
Items like lines and annuli(? plural of annulus) stay within axes normally, but they don't respect my boundaries with the svg backend. I've tried playing with background and border colors to no avail.

Possibly related, but in more elaborate examples the order of rendering is reverse from how I added things to the plot.

Minimal working example:
```
from bokeh.plotting import figure, show

p = figure(plot_width=400, plot_height=400, output_backend = 'svg')
p.annulus(x=[1, 2, 3], y=[1, 2, 3], inner_radius=0.1, outer_radius=0.25,
					color="orange", alpha=0.6)
show(p)
```

With backend='svg':
<img width="424" alt="rogueannuli" src="https://user-images.githubusercontent.com/26759579/29490698-698560e0-84f8-11e7-9266-849881d523e1.png">

With backend='canvas':
<img width="409" alt="containedannulicanvasbackend" src="https://user-images.githubusercontent.com/26759579/29490714-fec5017e-84f8-11e7-918b-d68782456571.png">

**Comment by ColinOrionChandler** [comment] 2017-08-20 00:27
Supporting my order-of-rendering as (part of?) the source of the issue, some of my more complex plots come out like this: 
[24 Sex.pdf](https://github.com/bokeh/bokeh/files/1236743/24.Sex.pdf)
The annuli should be under the lines too. If I set each annulus to level='underlay' then that part is corrected. It just looks like the annuli, lines, and what not are possibly being rendered at the wrong time.

**Comment by kvnjng** [comment] 2018-01-22 19:50
I am running into the same issue -glyphs, text, and line elements seem to be appearing outside of the axis when output_backend = 'svg' .

Bokeh 0.12.13 / Selenium 3.8.1 / PhantomJS 2.1.1

Any updates?

**Comment by mattpap** [comment] 2018-02-28 21:51
This is a duplicate of #6345.

**Comment by mattpap** [comment] 2018-03-26 15:28
Reopening to have a reference issue.

**Closed** 2018-03-26 20:38 UTC
Labels: tag: component: bokehjs, type: bug
