### ISSUE TITLE
Add interval to bokeh.models.tickers notebook documentation

### ISSUE THREAD

**Issue by ahuang11** [bokeh/bokeh#7945] opened 2018-05-31 16:23 UTC
bokeh == 0.12.16

Would like that the documentation at least show `interval` as one of the arguments instead of just `**kwargs`.

![image](https://user-images.githubusercontent.com/15331990/40794363-c44d253a-64b3-11e8-86ef-913120b55489.png)

```
from bokeh.models.tickers import SingleIntervalTicker
SingleIntervalTicker()
```

Or perhaps make `interval` as the first keyword argument so this would work.
```
from bokeh.models.tickers import SingleIntervalTicker
SingleIntervalTicker(2.592e+8)  # 2.592e+8 == 3 days
```

(This currently raises an error):
`TypeError: __init__() takes 1 positional argument but 2 were given`

Thanks!

**Comment by bryevdv** [comment] 2018-05-31 16:39
dupe of https://github.com/bokeh/bokeh/issues/6372

Until Python 2 support is dropped (which is years away) we are not going to be able to generate a proper function signature dynamically. We could consider adding all the properties to the docstring body. But with hundreds of models and thousands of properties, I worry about import times if that is done at dynamically at runtime, and I worry about spiraling build complexity if we try to do it somehow at packaging time. 

> Or perhaps make interval as the first keyword argument so this would work.

That's not going to happen. Passing properties as keyword (not positional) arguments is completely consistent across all Bokeh models. This consistency is a good thing, because it makes expectations and practice uniform and predictable and explainable. There are *very* few exceptions to support positional args (the only one I can thing of offhand is `Range1d`).

**Closed by bryevdv** 2018-05-31 16:39 UTC
