### ISSUE TITLE
[BUG] PolyDrawTool not working with gmap

### ISSUE THREAD

**Issue by codebeard1** [bokeh/bokeh#12427] opened 2022-09-27 05:01 UTC
### Software versions

Python version      :  3.8.10 (default, Jun  2 2021, 10:49:15) 
IPython version     :  8.3.0
Tornado version     :  6.1
Bokeh version       :  2.4.3
BokehJS static path :  /home/mk8s/.local/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.29

### Expected behavior

Independtly the gmap and PolyDrawTool work as expected. So I would expect them to work together especially of the data source is still a ColumnDataSource or a GeoJsonDataSource. Meaning if I render a gmap with the PolyDrawTool added, I would expect the user to be able to draw a Polygon on top of a geographic area within the gmap. 

### Observed behavior

When I try to use the PolyDrawTool to draw a polygon on the gmap no user drawn polygon is displayed.

### Example code

```Python
# set google map api
api_key = "..."

# Create GeoCoder class from Google Maps
geolocator = GoogleV3(api_key=api_key)

# Create test data
lat, lng = 37.871666, -122.272781
bokeh_width, bokeh_height = 500,400
zoom = 14
map_type='satellite'
    
# Create data source for callback function
source = ColumnDataSource(data=dict(x=pd.Series([lat]), y=pd.Series([lng])))

# Create and initialize gmap object
gmap_options = GMapOptions(lat=lat, lng=lng, map_type=map_type, zoom=zoom)
p = gmap(api_key, gmap_options, title='Land Selection', width=bokeh_width, height=bokeh_height, tools=['hover', 'reset', 'wheel_zoom', 'pan'])

# Create empty patch for user to draw polygon
poly_empty = p.patches([], [], fill_color='green', fill_alpha=0.5, line_width=0.05)
c1 = p.circle([], [], size=10, color='red')

# Create Polygon tools
draw_empty = PolyDrawTool(renderers=[poly_empty])
edit_tool = PolyEditTool(renderers=[poly_empty], vertex_renderer=c1)

# Add tools to Bokeh visualization/gmap
p.add_tools(draw_empty, edit_tool)
p.toolbar.active_drag = edit_tool

curdoc().add_root(p)
curdoc().title = "Polygon Selection"
```

**Comment by bryevdv** [comment] 2022-09-27 05:18
I'm not sure there is anything we will be able to do about this. In every other kind of plot, Bokeh has an invisible DOM element for capturing events. But this interferes with GMaps, since GMaps insist on handling all the events itself. To get things like the pan and zoom tools to "work" with GMaps, we have to jump through hoops to to register to respond to events from the GMap API, instead of being able to handle them directly. I am not sure that the same tricks will work for the edit tools, however, due to their complexity. If so, all we will be able to do is document this incompatibilty. 

As an immediate workaround, I would suggest using a `TileProvider` on a regular Bokeh plot, instead og a GMap.

https://docs.bokeh.org/en/dev-3.0/docs/user_guide/geo.html#tile-provider-maps

cc @bokeh/dev

**Comment by mattpap** [comment] 2022-09-27 20:31
This is a duplicate of issue #7775. This is perfectly fixable, but needs quite a bit of work, i.e. projections, that are required by GMaps need to be invertible, so that correct data can be stored back in the data source when using any kind of draw/edit tools.

**Closed** 2022-09-27 20:32 UTC
Labels: reso: duplicate, type: discussion

**Comment by bryevdv** [comment] 2022-09-27 20:34
>  This is perfectly fixable, but needs quite a bit of work 

Of course, I should have been more clear: I am not sure the work would justified, especially when these days I would generally advocate for people to use `TileProvider` over `GMapPlot`, regardless.

**Comment by codebeard1** [comment] 2022-09-27 20:43
Thanks @mattpap and @bryevdv for the feedback. I will take a look at the TileProvider and revert back. If you could point me to examples of TileProvider to draw Polygons (or other shapes) to select an area on a map that would be greatly appreciated.

**Comment by bryevdv** [comment] 2022-09-27 21:41
I am not aware of any specific examples, but I would also expect the edit tools to "just work" on a regular plot with a tile provider renderer.
