### ISSUE TITLE
CoffeeScript validation for Dialog widget content property

### ISSUE THREAD

**Issue by schaunwheeler** [bokeh/bokeh#4780] opened 2016-07-09 15:48 UTC
In trying to use the Dialog widget, I'm running into javascript errors. The documentation at http://bokeh.pydata.org/en/latest/docs/reference/models/widgets.dialogs.html states that the `content` property of the widget can take `Either(String, Instance(Box))`, and the code below bears that out:

```
from bokeh.layouts import Column
from bokeh.models.widgets.dialogs import Dialog
from bokeh.plotting import output_file, show

output_file('test.html')

column = Column()
dialog_column = Column()
dialog = Dialog()
dialog.content = dialog_column
column.children = [dialog]

show(column)
```

I don't run into any validation errors in `dialog.content = dialog_column`, but when I try to display the above in the browser, I get the following error in the console:

`Uncaught Error: String property 'content' given invalid value: Column(19d85509-e019-4128-b71d-f57dddc67b5b)`

When I look at https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/widgets/dialog.coffee, it looks like the CoffeeScript validation for the `content` property does not match the Python validation:

```
  @define {
      visible:     [ p.Bool,    false ]
      closable:    [ p.Bool,    true  ]
      title:       [ p.String,  ""    ]
      content:     [ p.String,  ""    ]
      buttons:     [ p.Array,   []    ]
      buttons_box: [ p.Instance       ]
    }
```

I don't know much about CoffeeScript, but it seems like the definition of the content property should read something like:

`content:     [p.Either(p.Instance, p.String)]`

Am I on the right track? If the change I guessed at above would work, I'm happy to submit a pull request.

**Comment by bryevdv** [comment] 2016-07-09 17:27
`Dialog` currently has some known issues. This is a duplicate of https://github.com/bokeh/bokeh/issues/4652 so I am closing in favor of that issue. 

Regarding the properties on the BokehJS side, the property system there is not yet quite as developed as on the Python side. There's no `Either` (yet) for instance. I think it would have to just be `p.Any` for now. I'm not sure if this is the only issue with `Dialog`, though

**Closed by bryevdv** 2016-07-09 17:27 UTC
