### ISSUE TITLE
Sliders fail to render (They have no dimension)

### ISSUE THREAD

**Issue by justacec** [bokeh/bokeh#3989] opened 2016-03-03 12:23 UTC
After updating to the most recent version of master I found that the sliders were not rendering.  I have tracked the issue introduction to commit 33ec2c9.  The slider elements are in the HTML but have no dimension.  This issue can be reproduced by executing the "color_sliders.py" example in "examples/plotting/file".  I believe this has something to do with the css not being correctly associated with the tags in the HTML and therefore not getting all of the properties that they need.

**Comment by bryevdv** [comment] 2016-03-03 16:28
ping @mistakevin @mattpap @birdsarah any ideas?

**Comment by mistakevin** [comment] 2016-03-03 17:05
May be due to a class name clash `.bk-plot` is being used as the overall bokeh style wrapper and as an inner utility class. https://github.com/bokeh/bokeh/pull/3964 is supposed to better namespace, but it's hung up on selenium test failures.

**Comment by canavandl** [comment] 2016-03-07 16:59
@justacec I think this issue was resolved by PR #3964 . Can you merge in master and confirm?

**Comment by justacec** [comment] 2016-03-07 17:21
@canavandl I have merged this already in my WIP branches (PR #3958) and can confirm that it does fix the issue.  It also fixes an issue with the DataTable rendering.

**Comment by canavandl** [comment] 2016-03-07 17:23
Awesome - I'm going to close this issue as 'completed' then. If you find any other regressions, don't hesitate to reopen it. Thanks!

**Closed by canavandl** 2016-03-07 17:23 UTC
