### ISSUE TITLE
"embed a Bokeh Server in the notebook" demo code does not run

### ISSUE THREAD

**Issue by mike-el** [bokeh/bokeh#8809] opened 2019-04-02 14:13 UTC
I tried running the python 3.0 bokeh code at  
 examples/howto/server_embed/notebook_embed.ipynb    in my jupyter notebook in Chrome and it generates this error message:

AttributeError: 'function' object has no attribute 'references'

**Comment by bryevdv** [comment] 2019-04-02 14:37
I just tested it locally and it runs fine. @mike-el The issue template requests a specific kinds of information for a reason: we cannot fix or comment reasonably on things we cannot reproduce. Closing this as `norepro` Will be happy to re-open if all the requested information is added.

**Closed by bryevdv** 2019-04-02 14:37 UTC
