### ISSUE TITLE
bokeh.charts.Histogram breaks when there are outliers in data & bins = lots

### ISSUE THREAD

**Issue by Kharms** [bokeh/bokeh#4357] opened 2016-05-23 23:07 UTC
The charts histogram makes outliers look much more prevalent. 

```
import numpy as np
import pandas as pd
import booked
from bokeh.charts import Histogram
from bokeh.io import show, output_notebook

bokeh.charts.output_notebook()
%matplotlib inline

normal_dist = pd.Series(np.random.normal(365, 150, 6000))
outliers = [1754,1803]
adjusted_dist = normal_dist.append(pd.Series(outliers, index=[7000,7001]))
adjusted_dist.hist(bins=60)

tops, edges = np.histogram(adjusted_dist, bins=60)
expected_behavior = figure(title="expected bokeh behavior")
expected_behavior.quad(top=tops, bottom=0, left=edges[:-1], right=edges[1:])
show(expected_behavior)

actual_behavior = Histogram(adjusted_dist, title="actual bokeh behavior", bins=60)
show(actual_behavior)
```
<img width="611" alt="screen shot 2016-05-23 at 7 06 58 pm" src="https://cloud.githubusercontent.com/assets/7454464/15487239/9761a1a2-2119-11e6-8ca7-2300c2ae4db3.png">

```

Bokeh Info:
Python version      :  3.5.1 |Anaconda 4.0.0 (x86_64)| (default, Dec  7 2015, 11:24:55) 
IPython version     :  4.1.2
Bokeh version       :  0.11.1
```

**Comment by bryevdv** [comment] 2016-05-23 23:10
This appears to be duplicate of #3875, addressed by PR #3988

**Closed by bryevdv** 2016-05-23 23:10 UTC
