### ISSUE TITLE
GMapPlot not constrained by Bokeh frame

### ISSUE THREAD

**Issue by CFM90** [bokeh/bokeh#5923] opened 2017-02-27 16:18 UTC
Hello, 
I am using:
Python 3.6,
Anaconda Navigator 1.4.3
Spyder 3.1.3 and
Bokeh 0.12.4
Mozilla Firefox 51.0.1 on a Mac with Sierra 10.12.3 (16D32)

I want to create a GMapPlot using the awesome Bokeh lib. I attached a code below (you need to insert your GMapAPI key.) The issue is the map itself. It is not constraind by the  "bokeh frame", but crosses it in every dimension overlapping the slider (see screenshot). Changing the plot_height and width does not help.

```
import pandas as pd
from bokeh.io import curdoc
from bokeh.models.glyphs import Circle 
from bokeh.models import(Range1d, ColumnDataSource, PanTool, WheelZoomTool, HoverTool, GMapPlot, GMapOptions, Slider)
from bokeh.layouts import column
import numpy as np

GMAP_API = "YourGMapAPIKey"

plot = GMapPlot(
    x_range = Range1d(-160, 160),
    y_range = Range1d(-80, 80),
    plot_width=1000,
    plot_height= 500,
    map_options = GMapOptions(lat=53.57532, lng = 10.01534, zoom = 10),
    api_key = GMAP_API,
    webgl= True
)


lat = pd.Series([
53.575973,
53.576395,
53.575984,
53.576417,
53.576511,
53.57622,
53.575827,
53.576523,
53.575958,
53.576539,
53.576123,
53.576703,
])

long = pd.Series([
9.849907,
9.850376,
9.850205,
9.850515,
9.850753,
9.847413,
9.85242,
9.851056,
9.851206,
9.85114,
9.851809,
9.851636
])


test = pd.Series(np.random.random(len(long)))
test.columns = ["stuff"]

Df = pd.DataFrame(
    {'lat': lat,
     'long': long,
     'stuff': test
    })


circle = Circle(x= "long", y="lat", size = 10, line_color= None, fill_color = "stuff")
datasource = ColumnDataSource(Df)

plot.add_glyph(datasource, circle)
plot.add_tools(PanTool(), WheelZoomTool())

slider = Slider(title = "Probs", value = 0, start = 0.00, end= 1.00, step= 0.1)
curdoc().add_root(column(slider, plot))
curdoc().title = "Stuff"

def update(attr, old, new):
    cutoff= slider.value
    datasource.data= ColumnDataSource.from_df(Df[Df["stuff"]>= cutoff])

slider.on_change("value", update)
```

Running it with 
`bokeh serve --show /xxx/xxx/thisPlot.py in terminal`

<img width="1244" alt="bokehbug" src="https://cloud.githubusercontent.com/assets/24831579/23369080/6cec5e8e-fd10-11e6-88c1-d0e2e6cd97d7.png">

**Comment by CFM90** [comment] 2017-02-27 16:35
I am actually experiencing the same bug using Safari and Firefox on your website.

http://bokeh.pydata.org/en/latest/docs/user_guide/geo.html

**Comment by bryevdv** [comment] 2017-02-27 17:34
This is a dupe of #5801 As stated there, the fix is already in master, and an be viewed on the latest "dev build" docs:

http://bokeh.pydata.org/en/dev/docs/user_guide/geo.html

Due to lack of resources, old docs cannot be custom-redeployed at this time.

**Closed by bryevdv** 2017-02-27 17:34 UTC
