### ISSUE TITLE
[BUG] Step glyphs render poorly when LOD downsampled

### ISSUE THREAD

**Issue by somguyth** [bokeh/bokeh#12136] opened 2022-05-20 11:59 UTC
### Software versions

Python version      :  3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)]
IPython version     :  7.16.1
Tornado version     :  6.0.4
Bokeh version       :  2.4.3
BokehJS static path :  c:\users\isaac\appdata\local\programs\python\python38-32\lib\site-packages\bokeh\server\static
node.js version     :  v14.17.3
npm version         :  7.19.1
Operating system    :  Windows-10-10.0.19041-SP0

### Expected behavior

Plot doesn't disappear when panning/zooming.

### Observed behavior

Plot disappears when panning/zooming with mouse.

### Example code

```Python
from bokeh.plotting import figure, curdoc
from bokeh.driving import linear
from bokeh.models.tools import PanTool, WheelZoomTool

p = figure(sizing_mode="stretch_both", y_axis_location="right", x_axis_type="datetime")
pan_tool = p.select(dict(type=PanTool))
pan_tool.dimensions="width"
zoom_tool = p.select(dict(type=WheelZoomTool))
zoom_tool.dimensions="width"
p.x_range.follow = "end"
p.x_range.range_padding = 0.01
p.xaxis.ticker.desired_num_ticks = 8
r1 = p.step(range(3000), range(3000), color="red", line_width=0.4)
curdoc().add_root(p)
```

**Comment by bryevdv** [comment] 2022-05-20 13:59
You are probably hitting the default Level-of-Detail downsampling during cuts in during interactive movements. 

https://docs.bokeh.org/en/latest/docs/user_guide/tools.html?highlight=lod#controlling-level-of-detail

You can either turn off LOD downsampling by setting `lod_threshold=None`

Unless you are saying the line does not come back with full opacity after the interaction ends, this is `reso: working as intended`. Please elaborate on exactly what actions you take, and exactly what results you see, and when.  

All that said, LOD does not work all that well with line-like glyphs, and making it work better on canvas would be a big lift. The best solution here would probably be to extend webgl support to `step` glyphs, but I am not sure how much work that would be. cc @ianthomas23

**Comment by ianthomas23** [comment] 2022-05-20 19:35
@bryevdv It should be reasonably straightforward to implement WebGL `step` glyphs I think.

**Comment by bryevdv** [comment] 2022-06-23 06:59
Absent more information, closing.

**Closed by bryevdv** 2022-06-23 06:59 UTC
Labels: type: discussion
