### ISSUE TITLE
hover improvements

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#1402] opened 2014-11-14 22:02 UTC
The hover tool is great.  It would be awesome to also have a mouseclick event that could be associated with a glyph that would return, e.g. a mini popup page with more details about a data point (ideally including graphics).

But regarding hover, some requests:

* better formatting options for the hover output (maybe this is possible and I just don't know how), e.g. an html template fragment
* be able to fix the location of the hover "bubble" that appears.  I don't really want it following my cursor around.  Some ideas:
    * centered on the object/data point that is creating the bubble
    * fix "x", use "y" from the data point (or vice-versa)
    * have "info" bubble in fixed location specified by (x,y), (cx,cy), or relative "topright", etc.

**Comment by bryevdv** [comment] 2015-01-23 15:23
I"m adding these ideas to #1189 and closing this as a dupe. BTW @ijstokes you can already have hover tool snap to marker/circle/rect centers, is that what you mean "centered on the object/data point that is creating the bubble"?

**Comment by bryevdv** [comment] 2015-01-23 15:24
dupe of #1189

**Closed by bryevdv** 2015-01-23 15:24 UTC
Labels: reso: duplicate, type: feature
