### ISSUE TITLE
Graph will be blank if output_backend is webgl

### ISSUE THREAD

**Issue by Dorothy-hyy** [bokeh/bokeh#7706] opened 2018-03-27 21:56 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
OS:  MacOS 10.12.6 
Browser: Safari

iPython==5.2.1
bokeh==0.12.10

#### Description of expected behavior and the observed behavior
My graph is blank even if not using a log scale.. The output is generated, if I used box zoom, the points will be shown.. But with output_backend = "webgl", the graph is blank. I am going to plot a huge number of points with bokeh, I might need to use webgl option..

#### Complete, minimal, self-contained example code that reproduces the issue
```
import numpy as np
import pandas as pd

import bokeh.io
from bokeh.layouts import row, widgetbox
from bokeh.models import Select
from bokeh.palettes import Spectral6
from bokeh.plotting import curdoc, figure,show, output_file
from bokeh.sampledata.autompg import autompg_clean as df
from bokeh.palettes import Spectral4
bokeh.io.output_notebook()


TOOLS="hover,crosshair,pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,"
p = figure(tools=TOOLS, output_backend="webgl")
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)
show(p)

```

#### Screenshots or screencasts of the bug in action
With output_backend="webgl":
The output:
![51522187225_ pic](https://user-images.githubusercontent.com/19887185/37996991-939006a0-31e7-11e8-8a34-6bd8f21687b3.jpg)

If I use 'box select' to select it:
![41522187210_ pic](https://user-images.githubusercontent.com/19887185/37997015-a5b9ed3c-31e7-11e8-982f-9ca504c706db.jpg)

And without output_backend="webgl" option:
![61522187243_ pic_hd](https://user-images.githubusercontent.com/19887185/37997026-b08e8fb0-31e7-11e8-8029-c030d4ac9e07.jpg)

Any idea of how to solve it?
Thanks a lot.

**Comment by bryevdv** [comment] 2018-03-27 22:02
This is a duplicate of #5589 (e.g. code above works on chrome)

**Closed by bryevdv** 2018-03-27 22:02 UTC

**Comment by bryevdv** [comment] 2018-03-27 22:10
@Dorothy-hyy WebGL has some current known issues on Safari.  There is no workaround (except not to use webgl in those scenarios) and I don't know offhand when it might be fixed.

**Comment by Dorothy-hyy** [comment] 2018-03-28 00:26
@bryevdv Thank you, it works on chrome.
