### ISSUE TITLE
Add jupyter-bokeh extension support for jupyterlab 3.0.0

### ISSUE THREAD

**Issue by pythonic2020** [bokeh/bokeh#10811] opened 2021-01-01 17:49 UTC
In conda environment running python 3.7 or 3.8 and jupyterlab 3.0.0:

```
> jupyter labextension install @bokeh/jupyter_bokeh --no-build
An error occured.
ValueError: The extension "@bokeh/jupyter_bokeh" does not yet support the current version of JupyterLab.


Conflicting Dependencies:
JupyterLab                        Extension      Package
>=3.0.0 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/application
>=3.0.0 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/apputils
>=3.0.0 <3.1.0                    >=2.0.2 <3.0.0 @jupyterlab/notebook
>=3.0.0 <3.1.0                    >=2.0.1 <3.0.0 @jupyterlab/rendermime-interfaces
>=6.0.0 <6.1.0                    >=5.0.2 <6.0.0 @jupyterlab/services
See the log file for details:  C:\Users\Me\AppData\Local\Temp\jupyterlab-debug-w0l76j9l.log
```

**Comment by mattpap** [comment] 2021-01-01 20:56
Duplicate of issue #10569.

**Closed by mattpap** 2021-01-01 20:56 UTC
Labels: TRIAGE
