### ISSUE TITLE
Bokeh Layout Unexpected Behaviour

### ISSUE THREAD

**Issue by schlichtanders** [bokeh/bokeh#5397] opened 2016-10-24 07:38 UTC
Thanks for actively building this awesome library.
Working with bokeh I found a couple of things related to the layout which I condensed in this kind of minimal working example: https://gist.github.com/schlichtanders/3e41890dcd20fbc3a1db2a675df6ce51
in there a html page gets constructed via jinja2 and bokeh `components` method.

In the python file are two important Variables, a `RESPONSIVE` flag which directly corresponds to the responsive kwarg of the `column` layout function. And `EXTRA_HEIGHT_REL` which denotes the height of a subplot in respect to its width.

Now the points I want to note:
1. (in the python file) if `EXTRA_HEIGHT_REL < 0.08`, then no plot is printed at all (for `RESPONSIVE=False`). For `RESPONSIVE=True` it is slightly lower `EXTRA_HEIGHT_REL < 0.07`
2. `Spacer` disappear entirely if `RESPONSIVENESS=True` (same holds for spacing with `VBox` and the like)
3. resizing (making the window smaller) the extra plots, they stay too big (occasionally leading also to overlapping)
4. resizing (making the window bigger) the extra plots, they stay too small (occasionally leading also to overlapping)
5. updating webpage (F5) has different behaviours: usually it makes plot bigger (but still false), sometimes it fits it as one would expect for responsiveness

In the example bootstrap was used as a standard css framework for responsive webpages. A short test with commented bootstrap CSS showed that this behaviour is not due to bootstrap.

I hope this minimal working example can help to clarify / fix these issues.

Python version      :  2.7.6 (default, Jun 22 2015, 17:58:13) 
IPython version     :  4.0.1
Bokeh version       :  0.12.3

**Comment by birdsarah** [comment] 2016-10-24 08:01
Please ask support questions on the mailing list: https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by schlichtanders** [comment] 2016-10-24 08:11
Sorry for confusion. This is a BUG report, not a support question. The gist is just my minification of an example code where the bug/bugs occur

**Comment by mattpap** [comment] 2016-10-24 09:19
@schlichtanders, does bokeh work properly in this case without bootstrap?

**Comment by birdsarah** [comment] 2016-10-24 19:26
I'm not sure it's a BUG report @schlichtanders. 

Using `sizing_mode` with `components` is tricky and I'm not sure you're doing it correctly. Unfortunately I won't have a chance to look at this carefully until later this week.

Have you managed to successfully embed one plot using components and have it resize accordingly?

**Comment by birdsarah** [comment] 2016-10-24 19:27
(I think this conversation is better had on the mailing list and then we can pull out specific issues if there are any).

**Comment by schlichtanders** [comment] 2016-10-25 18:28
No, it gives the same errors.
the Bootstrap columns make it possible to see more sides of this Buggy
behaviour (those described above). Therefore I used it.

**Comment by schlichtanders** [comment] 2016-10-26 12:00
Now I tested it with one plot only and indeed I get the very same behaviour. I could have thought before about this.
The gist https://gist.github.com/schlichtanders/3e41890dcd20fbc3a1db2a675df6ce51 is updated accordingly and now includes only a single plot.

It really seems to be an issue of the size,
remember if the height is too small (relative to width somehow), then the plot disappears. I tried a little bit more and found that for e.g. REL_HEIGHT=0.06 nothing is plotted as said before however then after resizing the window to very small, it is plotted again.

It seems like there is a minimal (relative) height after which there is no responsiveness any longer.

**Comment by bryevdv** [comment] 2016-12-10 20:38
Marking this as a `bug` for now tho I think it may be a dupe of other issues.

**Comment by bryevdv** [comment] 2017-06-01 01:17
Just confirming this still seems to be an issue as of `0.12.6dev7` Also here is a link to the gist with the code for easier reference:

https://gist.github.com/schlichtanders/3e41890dcd20fbc3a1db2a675df6ce51

**Comment by bryevdv** [comment] 2019-04-13 08:06
There is a high chance this was resolved in the complete layout refactor for 1.1 which closed dozens of layout issues. Also the original code is not really comparable anymore since APIs have changed since two years ago. So, I will close out this issue now. Please open a new issue with an MRE for any problems with 1.1+

**Closed by bryevdv** 2019-04-13 08:06 UTC
Labels: tag: component: bokehjs, tag: layout, type: bug
