### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ItamarShDev** [bokeh/bokeh#10574] opened 2020-10-14 07:00 UTC
I have a rect based heatmap
create on top of the following figure:
```
fig = figure(title="Detailed view",
                 x_axis_type="datetime",
                 y_range=FactorRange(),
                 y_axis_location='right',
                 tools="xpan,reset,undo",
                 min_border=0,
                 active_drag='xpan',
                 plot_height=height,
                 output_backend="webgl",
                 **theme['plot'])
```

the tect is defined as follows:
``` 
rect = fig.rect(x=x,
                    y='Tags',
                    width=glyph_size,
                    height=1,
                    source=source,
                    line_color={
                        'field': 'value',
                        'transform': mapper
                    },
                    fill_color={
                        'field': 'value',
                        'transform': mapper
                    },
                    selection_color={
                        'field': 'value',
                        'transform': selected_mapper
                    },
                    hover_line_color=theme['heatmap_colors']['hover'],
                    nonselection_fill_alpha=1,
                    nonselection_line_alpha=1)
```
Where `glyph_size` is a float representing the size in milliseconds.
The chart has a green background and paints white rect glyphs where the data frame is not NaN.

For some reason I see the following:
![8200744f7378ba06a175af90e636eb1e5bfe8cca](https://user-images.githubusercontent.com/953371/95954452-00bd5c00-0e04-11eb-9fa2-0aabc7054320.png)

Notice the random green columns in the chart.
These are not real, there is data there!
![7ff24657042590bd65e30f8835c6483e17fd4514_2_576x500](https://user-images.githubusercontent.com/953371/95954475-0adf5a80-0e04-11eb-87e2-1e36396210c8.png)

Here we can see that we have a data point at 00:00 that should be 3 minutes size (180000ms glyph size).
![Screenshot from 2020-10-13 16-41-40](https://user-images.githubusercontent.com/953371/95954508-17fc4980-0e04-11eb-988e-93f9ef77eac5.png)

For some reason, 2 errors occur in this chart:
1. the glyphs are not center around the correct time (or the x_range is not aligned, who knows)
2. the size of the glyphs seems to be incorrect.

We can see here, that the point should be at 00:03 but it's positioned somewhere around 00:01!
![Screenshot from 2020-10-13 16-53-18](https://user-images.githubusercontent.com/953371/95954526-1d599400-0e04-11eb-86cc-52600a764ac8.png)

What I was originally trying to achieve:
draw a time-series based heatmap with the glyphs starting from their respective timestamps and in the size of the sample rate (in this case 3 minutes)

Thank you!

**Comment by mattpap** [comment] 2020-10-14 10:08
Most likely a duplicate of #10488, but without at least bokeh version and preferably a minimal reproducible example, it's only a guess.

**Comment by bryevdv** [comment] 2020-10-14 15:58
@ItamarShDev just to amplify what @mattpap said: without a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) including ***any data necessary to run the code***, there is no way for us to investigate, and this issue will be closed.

**Comment by bryevdv** [comment] 2020-10-16 01:41
I am going to assume this is a duplicate and close. @ItamarShDev if you can provide an MRE that demonstrates this is a different issue than #10488 we can re-open.

**Closed by bryevdv** 2020-10-16 01:41 UTC
Labels: NEEDS MORE INFO, type: discussion

**Comment by ItamarShDev** [comment] 2020-10-16 11:44
Thank you @bryevdv.
It does seems like a duplicate of #10488

**Comment by ItamarShDev** [comment] 2020-10-16 11:47
BTW, for future reference, i shifted to use `quad` with a distinctive left right values, which made it correct, and even faster on larger data sets.


Thanks you all for the responses
