### ISSUE TITLE
Problems with autoload_server

### ISSUE THREAD

**Issue by sandrarum** [bokeh/bokeh#5993] opened 2017-03-14 08:39 UTC
Hello everyone, 
I have some problems using the autoload_server-function to combine nginx, flask and bokeh. I have bokeh-server on `127.0.0.1:5006`. Nginx is used to map it to `193.239.28.156:8020`. Now I use the autoload_server-command: 
```
script = autoload_server(model=None, app_path="/sliders", url='http://193.239.28.156:8020'). 
```
The problem is, it adds the following lines to the page-html:
```
<link type="text/css" rel="stylesheet" href="http://193.239.28.156:8020/static/css/bokeh-0.12.4.min.css">
<link type="text/css" rel="stylesheet" href="http://193.239.28.156:8020/static/css/bokeh-widgets-0.12.4.min.css">
<script src="http://127.0.0.1:5006/static/js/bokeh.min.js?v=9d3af13f493d36073a89714f6a5240c6">
<script src="http://127.0.0.1:5006/static/js/bokeh-widgets.min.js?v=1af1302b8bd7fcc88c7bcafb8771497b">
```
As you can see, the css-files are using the given url which works perfectly, but the js-files are using the internal bokeh-server ip, which cannot be found.
```
Nginx config:
map $http_upgrade $connection_upgrade {
default upgrade;
'' close;
}

upstream websocket {
    server 193.239.28.156:8010;
}

server {
    listen 8020;
    location / {
        proxy_pass http://127.0.0.1:5006;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
        sub_filter "127.0.0.1:5006" "193.239.28.156:8020";
        sub_filter_once off;
    }
    location /static {
         proxy_pass http://127.0.0.1:5006;
         alias /home/flask/workspace/flask_demo/lib/python3.4/site-packages/bokeh-0.12.4-py3.4.egg/bokeh/server/static;
         sub_filter "127.0.0.1:5006" "193.239.28.156:8020";
         sub_filter_once off;
    }
}
```
The sub_filters are added for calling the bokeh server directly. They do not work with flask.

And this is the serve command to start the bokeh-server: 
```
/home/flask/workspace/flask_demo/bin/bokeh serve --host 10.1.0.64:5000 --host 127.0.0.1:5006 --allow-websocket-origin=193.239.28.156:8020 /home/flask/workspace/flask_demo/inqbus.gendata_viewer/src/inqbus/gendata_viewer/sliders.py
```

How can I solve the url-problem with the scripts?

**Comment by bryevdv** [comment] 2017-03-14 14:30
(issue was requested) Marking `discussion` for now. Need to figure out how it's possible for CSS and JS URLs to ever be different at all.

**Comment by bryevdv** [comment] 2018-09-11 01:04
So, I don't think this is an issue anymore with `server_document` and `server_session`. If need be these can be configured with an explicit `Resources` object for full control. Since the issue is so old, closing (can be re-opened if need be)

**Closed by bryevdv** 2018-09-11 01:04 UTC
Labels: type: discussion
