### ISSUE TITLE
Problem with Reset in gmap taxi example

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#2007] opened 2015-03-02 18:14 UTC
Pressing the Reset button at any time in this example causes the plot to point somewhere in the South Atlantic Ocean.  

I've illustrated this with a little Indiana Jones 'travel montage' map to make this issue into an adventure.

![issue](https://cloud.githubusercontent.com/assets/1417520/6447110/6be55c9e-c0d5-11e4-9a7e-73a0316a3f26.png)

**Comment by dsoto** [comment] 2015-06-26 08:03
Is there a way to reset around the lat and lng specified in GMapOptions?  Does reset_tool.coffee need to have that information?  Absent that, my plot resets to the "origin" which causes the voyage to the Gulf of Guinea.

**Comment by birdsarah** [comment] 2015-07-10 20:00
Marking this as a duplicate of #1196, but copying over your nice example @Maggie-M.

**Closed by birdsarah** 2015-07-10 20:00 UTC
Labels: type: bug
