### ISSUE TITLE
Hover not respond when a line above is hidden

### ISSUE THREAD

**Issue by Joshua1989** [bokeh/bokeh#7872] opened 2018-05-08 20:02 UTC
For defects or deficiencies, please provide ALL OF THE FOLLOWING:
Python Version: 3.6.4
Bokeh Version: 0.12.15
OS: MacOS Sierra 10.13.4
Browser: Chrome v66.0.3359.139 (Official Build) (64-bit)

Use Case:
I want to create a plot with multiple lines, with interactive legend to hide selected lines.
Besides, I want to turn on the hover tool so that when I point at a point, it will show the tooltip containing the x, y values.

Expected Behavior:
Say I have four curves, `A, B, C, D`, with their legend ordered from top to bottom.
If I click on the legend of `B`, I want the hover tool still works for the rest three curves.

Observed Behavior:
When I click on the legend of `B`, all the curves above `B` (in this case is `A`) in the legend order response to the hover, but all curves below `B` (in this case are `C, D`) do not response.

Below is the minimal, self-contained example code that reproduces the issue
```
import pandas as pd
from bokeh.io import show, output_notebook
from bokeh.palettes import Spectral4
from bokeh.plotting import figure
from bokeh.sampledata.stocks import AAPL, IBM, MSFT, GOOG

p = figure(plot_width=800, plot_height=250, x_axis_type="datetime", tools='hover')
p.title.text = 'Click on legend entries to hide the corresponding lines'

for data, name, color in zip([AAPL, IBM, MSFT, GOOG], ["AAPL", "IBM", "MSFT", "GOOG"], Spectral4):
    df = pd.DataFrame(data)
    df['date'] = pd.to_datetime(df['date'])
    p.line(df['date'], df['close'], line_width=2, color=color, alpha=0.8, legend=name)

p.legend.location = "top_left"
p.legend.click_policy="hide"

output_notebook()
show(p)
```

In the browser console, I found the following error:
```
Uncaught TypeError: Cannot read property 'is_empty' of null
    at e.inspect (bokeh-0.12.15.min.js:1)
    at e._inspect (bokeh-0.12.15.min.js:1)
    at e._clear (bokeh-0.12.15.min.js:1)
    at e._move_exit (bokeh-0.12.15.min.js:1)
    at e.<anonymous> (bokeh-0.12.15.min.js:1)
    at t.emit (bokeh-0.12.15.min.js:1)
    at t.trigger (bokeh-0.12.15.min.js:1)
    at bokeh-0.12.15.min.js:1
    at Array.map (<anonymous>)
    at t._trigger (bokeh-0.12.15.min.js:1)
e.inspect @ bokeh-0.12.15.min.js:1
e._inspect @ bokeh-0.12.15.min.js:1
e._clear @ bokeh-0.12.15.min.js:1
e._move_exit @ bokeh-0.12.15.min.js:1
(anonymous) @ bokeh-0.12.15.min.js:1
t.emit @ bokeh-0.12.15.min.js:1
t.trigger @ bokeh-0.12.15.min.js:1
(anonymous) @ bokeh-0.12.15.min.js:1
t._trigger @ bokeh-0.12.15.min.js:1
t._mouse_move @ bokeh-0.12.15.min.js:1
(anonymous) @ bokeh-0.12.15.min.js:1
```

**Comment by mattpap** [comment] 2018-05-08 20:05
This is a duplicate of #7705. The fix will be available in upcoming bokeh 0.12.16.

**Closed by mattpap** 2018-05-08 20:05 UTC
