### ISSUE TITLE
Do not change the parameters of the legend

### ISSUE THREAD

**Issue by yagafarova** [bokeh/bokeh#7445] opened 2018-01-23 10:08 UTC
#### Hello! 
I have an issue with changing the font size for legend.
Using Jupyter Notebook (v.5.0.0-8734a01), running on Python 3.6.2 |Anaconda custom (64-bit)|, Bokeh (v.0.12.13).

I run this code, but the legend's font size doesn't change:
```
p = figure(x_axis_label='Radius of compression, nm', y_axis_label='Pressure, atm', 
           plot_width=800, plot_height=600,
           x_range = (9.6, 20.4), y_range = (-20, 520))
output_file('lan_nh.html', title="lan_nh")
p.xaxis.axis_label_text_font_size = "22pt"
p.xaxis.major_label_text_font_size = "18pt"
p.yaxis.axis_label_text_font_size = "22pt"
p.yaxis.major_label_text_font_size = "18pt"
p.legend.label_text_font_size = "18pt"

files = ['VelocityVerlet_Langevin/dsDNA_4000bp_mM50/push/0.1/dsDNA_4000bp_mM50_pressure_push.dat', 
         '4000bp_concentration/dsDNA_4000bp_mM50/push_10k_steps/dsDNA_4000bp_mM50_pressure_push.dat',
         '4000bp_concentration/dsDNA_4000bp_mM50/push_100k_steps/dsDNA_4000bp_mM50_pressure_push.dat']
labels = ['Langevin',
          'Nose-Hoover: 10 M steps',
          'Nose-Hoover: 100 M steps']
colors = inferno(len(labels)+1)

for fname,l,c in zip(files, labels, colors):
    fname = path + fname
    radius = [float(i.split('\t')[1].strip()) for i in open(fname)]
    pressure = [float(i.split('\t')[2].strip())*1.6*9.87 for i in open(fname)]
    p.line(radius, pressure, color = c, legend=l, line_width=2)

show(p)
```
![bokeh_plot 4](https://user-images.githubusercontent.com/26544508/35269886-7928969a-003e-11e8-9f18-e1012d44730c.png)

**Comment by mattpap** [comment] 2018-01-23 10:29
The reason this doesn't work is because `p.legend.label_text_font_size = "18pt"` is a no-op, because `p.legend` is a proxy object that doesn't refer to anything at this point. `p.legend` becomes useful after first glyph is created with `legend` option. If you move this line after the `for` loop and before `show(p)`, it will work as expected. I'm pretty sure this isn't the first time this is reported, because this behavior is extremely confusing.

**Comment by mattpap** [comment] 2018-01-23 14:33
Closing this as a duplicate of issue #5632.

**Closed by mattpap** 2018-01-23 14:33 UTC
Labels: reso: duplicate
