### ISSUE TITLE
Testing bokeh server

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3284] opened 2015-12-09 17:13 UTC
The new bokeh server is alive - yay!

We need to get some metrics of how well it scales handles loads. In particular when there are x number of changes going back and forth between the plot and the server on the websocket.

**Comment by birdsarah** [comment] 2015-12-09 17:14
My first idea.

Spin up a bokeh server that has a streaming data component, so it's always pushing new data down to the client. Use a normal web testing service to hit it at scale. The main thing that we would need to check is whether normal web testing services actually load a page with javascript - otherwise this would be redundant.

**Comment by birdsarah** [comment] 2015-12-09 17:23
@spang @davehunt I thought you might have ideas (Christine, I know you've played with websockets; Dave, I know you know test).

It's a tornado server at its core if that helps.

The main challenges in my mind is that we need the clients to be interacting with the page to really get a solid idea of how the server will hold up


Also, I'm wondering if it would be good to get an idea of plot update/response time (which is a culmination of a ws data going up and down the pipe, and then js rendering client side)

**Comment by davehunt** [comment] 2015-12-14 14:45
If the server you spin up is publicly accessible then you could use something like neustar's [load testing platform](https://www.neustar.biz/services/web-performance/load-testing). The problem is that if you're using real browsers to simulate high load, you need to resources that it takes to spin up a **lot** of browsers. If possible, I'd look into seeing if you can simulate high load at the protocol level instead.

**Comment by bryevdv** [comment] 2017-09-12 17:16
We re-enabled at least examples test. Will close this issue for that (more to do but in new issues)

**Closed by bryevdv** 2017-09-12 17:16 UTC
Labels: tag: component: tests, type: discussion
