### ISSUE TITLE
Hovertool display pops under shaded portion of slider

### ISSUE THREAD

**Issue by magee256** [bokeh/bokeh#7991] opened 2018-06-12 23:08 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 0.12.16
python 3.6
MacOS 10.12.6
Chrome Version 66.0.3359.181 (Official Build) (64-bit)

#### Description of expected behavior and the observed behavior
I'd expect the hovertool info box to appear above all other widgets. Instead it pops under the slider, but only the shaded portion of the slider as demonstrated below. 

#### Screenshots or screencasts of the bug in action
<img width="1147" alt="screen shot 2018-06-12 at 4 06 52 pm" src="https://user-images.githubusercontent.com/13019270/41321850-ae7d1c78-6e5a-11e8-9a7d-13ae88f80d22.png">

**Comment by bryevdv** [comment] 2018-06-14 17:14
@magee256 please provide a compete minimal script to reproduce the issue

**Comment by bryevdv** [comment] 2018-07-05 17:23
@magee256 It is not a bug, that functionality has simply not been implemented yet. There is an open PR now that will be merged soon that adds oval/ellipse hit testing support.

**Closed** 2019-03-06 19:39 UTC
Labels: tag: component: bokehjs, type: bug
