### ISSUE TITLE
Subplots vertical axes don't line up

### ISSUE THREAD

**Issue by rocheseb** [bokeh/bokeh#5572] opened 2016-12-15 18:25 UTC
![image](https://cloud.githubusercontent.com/assets/22297924/21236264/56513d84-c2c8-11e6-8f85-6e0716b2295a.png)

In the above figure you can see that the vertical axes of the subplots are not aligned because the labels have different lengths, which in turns also changes the scale of the horizontal axis differently for each plot, which is troublesome when those horizontal axes are supposed to be shared.

Is there a way to force subplots in a column to have their actual graph window exactly aligned even if it means the plot_width won't be fixed when the length of labels changes?

**Comment by bryevdv** [comment] 2016-12-15 18:28
@rocheseb please provide a complete, minimal, runnable test case to reproduce the issue you are seeing.

**Comment by rocheseb** [comment] 2016-12-15 19:26
```
from bokeh.plotting import Figure, output_file
from bokeh.layouts import gridplot
from bokeh.resources import CDN
from bokeh.embed import file_html

import numpy as np

X = np.arange(100)

Y = [X*coef for coef in [1,100,1000]*2]

figs = []

for i,ydata in enumerate(Y):
	figs.append(Figure(plot_height=75,plot_width=200))
	figs[i].scatter(X,ydata)

grid = gridplot([[figs[j],figs[j+3]] for j in range(3)],toolbar_location='left')

outfile=open('align_TEST.html','w')
outfile.write(file_html(grid,CDN,'TEST'))
outfile.close()
```
which produces:
![image](https://cloud.githubusercontent.com/assets/22297924/21238735/1da90db8-c2d2-11e6-87de-fbbcc14e6221.png)

Vertical axes are aligned in the first column, but not in the second

bokeh.__version__ = 0.12.1

**Comment by bryevdv** [comment] 2016-12-15 20:04
Can confirm on Bokeh `0.12.3`. Note if all plots put in a `column` instead, then axes do all initially line up (but do not remain so if zooming changes axes size)

This might be a duplicate, but marking `bug` for now. 

ping @birdsarah do you know of any other issues off hand that this might be a dupe of?

**Comment by bryevdv** [comment] 2017-06-01 00:37
Just confirming that this is not fixed by any work up to 0.12.6dev7

**Comment by birdsarah** [comment] 2017-06-01 01:11
also note: https://github.com/bokeh/bokeh/issues/4394

**Comment by birdsarah** [comment] 2017-06-01 01:12
and: https://github.com/bokeh/bokeh/issues/4579

**Comment by birdsarah** [comment] 2017-06-01 01:14
and: https://github.com/bokeh/bokeh/issues/4608

**Comment by mattpap** [comment] 2017-08-11 14:14
TolbarBox is responsible for this. Removing toolbar restores properly alignment of vertical axes. This is related to issue #4579 (referenced earlier).

**Comment by bryevdv** [comment] 2019-01-31 02:58
Output with this code with #8085:
```
from bokeh.plotting import Figure, output_file
from bokeh.layouts import gridplot
from bokeh.resources import CDN
from bokeh.embed import file_html
from bokeh.io import show

import numpy as np

X = np.arange(100)

Y = [X*coef for coef in [1,100,1000]*2]

figs = []

for i,ydata in enumerate(Y):
	figs.append(Figure(plot_height=75,plot_width=400))
	figs[i].scatter(X,ydata)

grid = gridplot([[figs[j],figs[j+3]] for j in range(3)],toolbar_location='left')

show(grid)
```

<img width="865" alt="screen shot 2019-01-30 at 18 58 12" src="https://user-images.githubusercontent.com/1078448/52027665-0ef90680-24c1-11e9-8549-91aab732cb0d.png">

**Closed** 2019-02-01 16:18 UTC
Labels: tag: layout, type: bug
