### ISSUE TITLE
Javascript error when using image glyph that has a data source with custom column name

### ISSUE THREAD

**Issue by nathanielatom** [bokeh/bokeh#5769] opened 2017-01-19 19:38 UTC
Slightly modifying the `image.py` example to use a data source with the column name `custom_name` produces a Javascript error:

```
import numpy as np
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, show, output_file

N = 500
x = np.linspace(0, 10, N)
y = np.linspace(0, 10, N)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx)*np.cos(yy)

p = figure(x_range=(0, 10), y_range=(0, 10))

# must give a vector of image data for image parameter
source = ColumnDataSource(data=dict(custom_name=[d], x=[0], y=[0], width=[10], dh=[10]))
p.image(image='custom_name', x='x', y='y', dw='width', dh='dh', palette="Spectral11", source=source)

output_file("image.html", title="image.py example")

show(p)  # open a browser
```
results in 
```
TypeError: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The provided double value is non-finite.
    at e.r.ImageView.e._set_data (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:13)
    at e.r.GlyphView.e.set_data (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:13)
    at e.r.GlyphRendererView.e.set_data (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:19)
    at e.r.GlyphRendererView.e.initialize (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:19)
    at e.r.View (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:4)
    at e [as constructor] (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:4)
    at e [as constructor] (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:19)
    at new e (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:19)
    at Object.r.build_views (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:4)
    at e.r.PlotCanvasView.e.build_levels (cdn.pydata.org/bokeh/release/bokeh-0.12.4.min.js:18)
```
but the error goes away when `custom_name` is replaced with `image` (even if `width` is left as is).

I don't know if the same problem exists for `image_rgba`.

Python version      :  3.6.0 | packaged by conda-forge | (default, Jan 14 2017, 03:13:00) 
IPython version     :  5.1.0
Bokeh version       :  0.12.4
BokehJS static path :  /Users/Atom/.anaconda/envs/py3/lib/python3.6/site-packages/bokeh/server/static
node.js version     :  v4.5.0
npm version         :  2.15.9

This was not an issue in 0.12.3.

**Comment by bryevdv** [comment] 2017-01-19 19:52
This is a duplicate of https://github.com/bokeh/bokeh/issues/5706

**Closed by bryevdv** 2017-01-19 19:52 UTC
