### ISSUE TITLE
Data table rendering does not update with ColumnDataSource change in >0.12.6 when used in tabs

### ISSUE THREAD

**Issue by cutright** [bokeh/bokeh#6925] opened 2017-09-12 16:12 UTC
I recently upgraded from bokeh 0.12.6 and discovered different behavior in data table rendering.  This happened for me 0.12.7 and 0.12.9.  It seems as though changes to the source data do not instigate a change in the data table rendering in the same way bokeh 0.12.6 did.

I do have code below illustrating a bug, which I believe is related to the following comments.  So please bare with me through the less concrete examples.

In the following example the data in the plot and table share the same ColumnDataSource.  The data table appears empty until I scroll the table view.  I created a very short .mpg showing the behavior, I'm not sure how to show this bug with minimal code.   https://www.dropbox.com/s/64q8itqux5pf4hv/data_table_bug.mp4?dl=0

In some cases, only one row of data are displayed even when a 2nd table with the same ColumnDataSource is used which displays the full dataset (see attached image).
table_bug

And finally, this one I was able to create some minimal code.  Please compare running it on 0.12.6 and 0.12.9.  When you click the checkbox, the value from the dropdown should be added to the table on the right.  However, in 0.12.7 through 0.12.9, the table is not updated until the '<' button is clicked.  You can verify that the ColumnSourceData has changed by the line printed to the terminal, as well as unchecking the box if it's correlated variable is in the table... this results in the data being removed but the table still has the same number of rows.

I'm using Chrome v60 on Mac OS 10.12.6 and Ubuntu 16.  Python 2.7.10 and 2.7.12

```
from __future__ import print_function
from future.utils import listitems
from bokeh.layouts import column, row
from bokeh.models import ColumnDataSource
from bokeh.io import curdoc
from bokeh.models.widgets import Select, Button, TableColumn, DataTable, CheckboxGroup

source_multi_var_include = ColumnDataSource(data=dict(var_name=[]))
variables = ['a', 'b', 'c']

multi_var_reg_vars = {name: False for name in variables}


def update_check_box():
    if multi_var_reg_vars[corr_chart_x.value]:
        corr_chart_x_include.active = [0]
    else:
        corr_chart_x_include.active = []


def corr_chart_x_prev_ticker():
    current_index = corr_chart_x.options.index(corr_chart_x.value)
    corr_chart_x.value = corr_chart_x.options[current_index - 1]
    update_check_box()


def corr_chart_x_ticker(atrr, old, new):
    update_check_box()


def corr_chart_x_include_ticker(attr, old, new):
    if new:
        multi_var_reg_vars[corr_chart_x.value] = True
    if not new:
        multi_var_reg_vars[corr_chart_x.value] = False
    included_vars = [key for key, value in listitems(multi_var_reg_vars) if value]
    included_vars.sort()
    source_multi_var_include.data = {'var_name': included_vars}
    print(source_multi_var_include.data['var_name'])


corr_chart_x_include = CheckboxGroup(labels=["Include"], active=[], width=400)
corr_chart_x_prev = Button(label="<", button_type="primary", width=50)
corr_chart_x_prev.on_click(corr_chart_x_prev_ticker)
corr_chart_x_include.on_change('active', corr_chart_x_include_ticker)

corr_chart_x = Select(value=variables[0], options=variables, width=300)
corr_chart_x.title = "Select a Variable"
corr_chart_x.on_change('value', corr_chart_x_ticker)

columns = [TableColumn(field="var_name", title="Variables for Multi-Var Regression", width=100)]
data_table_multi_var_include = DataTable(source=source_multi_var_include, columns=columns,
                                         height=175, width=275, row_headers=False)


layout_correlation = column(row(column(corr_chart_x_include,
                                       row(corr_chart_x_prev, corr_chart_x)),
                                data_table_multi_var_include))

# Create the document Bokeh server will use to generate the webpage
curdoc().add_root(layout_correlation)
curdoc().title = "DVH Analytics"


```

**Comment by cutright** [comment] 2017-09-12 16:21
<img width="1105" alt="table_bug" src="https://user-images.githubusercontent.com/4778878/30336990-881024b6-97ac-11e7-9419-16d1611029f5.png">

**Comment by bryevdv** [comment] 2017-09-12 16:34
I think this probably has to do with the recent CDSView feature. cc @clairetang6

**Comment by DuCorey** [comment] 2017-09-12 17:37
Hi @cutright I've also been having some issues with DataTables not being updated properly. I'm managed to fix the issue using a [hack ](https://github.com/bokeh/bokeh/issues/6863#issuecomment-328926129) that I've posted in a similar issue #6863. I have a feeling these two issues are duplicates. Please let us know if that fixes your issue.

**Comment by ashern** [comment] 2017-09-12 17:40
I can confirm this issue, and also confirm that @DuCorey fix from #6863 is an effective work-around.

**Comment by bryevdv** [comment] 2017-09-12 17:51
OK I will mark this as a dupe of #6863 If someone makes a PR we can get it merged ASAP

**Comment by cutright** [comment] 2017-09-12 18:16
This work-around does not resolve the first issue demonstrated in the linked video.

However, it does resolve the other issues.  Thanks!  I'll see if I can come up with some code for this, but I'm not sure where to focus my search yet.

**Comment by bryevdv** [comment] 2017-09-12 18:29
OK I will re-open. I have not seen this failing to rend initially behavior, will have to try to reproduce it when I get time.

**Comment by cutright** [comment] 2017-09-12 18:59
Thanks.  Just to give some context.  The tables are initially empty.  Then user specifies a SQL query and then the data is updated.  Sorry I can't provide code explicitly showing this yet, I can't really track down the issue.  Here is another screenshot showing a partial table render.  After scrolling, the rest of the data is rendered.

I'll keep working on finding some code to better demonstrate this.

<img width="1072" alt="data_table_bug_3" src="https://user-images.githubusercontent.com/4778878/30343195-276a9f72-97c2-11e7-89da-5f0b9277b721.png">

**Comment by cutright** [comment] 2017-09-20 15:45
Sorry for the delay, but i finally have some simple code to demonstrate this.  If you run the following code and click on Tab 2, you'll see no data in the table (as there is no data yet.  Click back on Tab 1, click the blue button/arrow, uncheck the check box... then go to Tab 2, the table appears empty until you scroll in it.

```
from __future__ import print_function
from future.utils import listitems
from bokeh.layouts import column, row
from bokeh.models import ColumnDataSource
from bokeh.io import curdoc
from bokeh.models.widgets import Select, Button, TableColumn, DataTable, CheckboxGroup, Tabs, Panel

source = ColumnDataSource(data=dict(var_name=[]))
variables = [str(i) for i in range(0, 100)]

include = {name: True for name in variables}


def update_check_box():
    if include[selector.value]:
        include_checkbox.active = [0]
    else:
        include_checkbox.active = []


def corr_chart_x_prev_ticker():
    current_index = selector.options.index(selector.value)
    selector.value = selector.options[current_index - 1]
    update_check_box()


def corr_chart_x_ticker(atrr, old, new):
    update_check_box()


def check_box_action(attr, old, new):
    if new:
        include[selector.value] = True
    if not new:
        include[selector.value] = False
    included_vars = [key for key, value in listitems(include) if value]
    included_vars.sort()
    source.data = {'var_name': included_vars}


include_checkbox = CheckboxGroup(labels=["Include"], active=[], width=400)
prev = Button(label="<", button_type="primary", width=50)
prev.on_click(corr_chart_x_prev_ticker)
include_checkbox.on_change('active', check_box_action)

selector = Select(value=variables[0], options=variables, width=300)
selector.title = "Select a Variable"
selector.on_change('value', corr_chart_x_ticker)

columns = [TableColumn(field="var_name", title="Title", width=100)]
data_table_multi_var_include = DataTable(source=source, columns=columns, height=175, width=275, row_headers=False)

layout_1 = row(column(include_checkbox,
                      row(prev, selector)))
layout_2 = column(data_table_multi_var_include)

tab1 = Panel(child=layout_1, title='tab1')
tab2 = Panel(child=layout_2, title='tab1')

tabs = Tabs(tabs=[tab1, tab2])

# Create the document Bokeh server will use to generate the webpage
curdoc().add_root(tabs)
curdoc().title = "Bug Test"

```

**Comment by cutright** [comment] 2017-10-15 17:46
Is there any update on this? Should this be considered a bug and not a discussion?

**Comment by bryevdv** [comment] 2017-10-15 19:40
This seems to work for me when I remove the tabs (put everything in a column). There are currently lots of problems with tabs, unfortunately. This is probably a dupe but I don't have the ability to track it down at the moment so I'll make as a `bug` at least for now.

**Comment by kasuteru** [comment] 2019-05-29 13:40
I am having the same issue, this is still open if I understand correctly? The current workaround is to not use tabs?

**Comment by bpostance** [comment] 2019-05-30 15:24
> I am having the same issue, this is still open if I understand correctly? The current workaround is to not use tabs?

Yes same here.

**Comment by bryevdv** [comment] 2020-08-25 03:48
This was fixed at some point, the example in https://github.com/bokeh/bokeh/issues/6925#issuecomment-330894142 is working for me with 2.2 (table shows immediately without needing any scrolling)

**Closed by bryevdv** 2020-08-25 03:48 UTC
Labels: tag: component: bokehjs, tag: widgets, type: bug
