### ISSUE TITLE
Figure clearance bug related to row, column, Tabs, Panel, between versions 0.12.10 and 0.12.11

### ISSUE THREAD

**Issue by zpz** [bokeh/bokeh#7328] opened 2017-12-17 05:30 UTC
The issue is described in this StackOverflow question post:

https://stackoverflow.com/questions/47851561/bokeh-tabs-does-not-clear-for-subsequent-figure

The first answer post on the same page tracks the issue down to the 0.12.10 -> 0.12.11 upgrade:

https://stackoverflow.com/questions/47851561/bokeh-tabs-does-not-clear-for-subsequent-figure/47852233#47852233

**Comment by bryevdv** [comment] 2018-05-11 01:26
There is not a complete test script to run, even in the SO link, so I am closing this as `norepro` for now. If you are able to provide a *complete* minimal reproducer that we can run to investigate, this can be re-opened.

**Closed by bryevdv** 2018-05-11 01:26 UTC

**Comment by zpz** [comment] 2018-05-11 02:33
I think a better action on your part would have been a comment about what's needed, as opposed to closing the issue as the very first action. The linked post, although lacking runnable code, is quite clearly trying to help the project with detailed descriptions of the problem.

**Comment by bryevdv** [comment] 2018-05-11 02:46
@zpz I am sorry if you took closing as some sort of personal slight, it was not. I am closing all un-actionable issues because, to be completely frank, I am more than overwhelmed. While appreciate your intentions to help the project, the fact of the matter is that without complete, runnable test cases, it is simply not really possible for us to meaningfully act. Additionally, although I should have stated so, I also believe this issue is probably duplicated in several others. In any case, closure is not necessarily a permanent resolution, and as I said I'd be happy to re-open with a complete minimal reproducer (which, for the record *was specifically asked for* in the issue template).
