### ISSUE TITLE
[BUG] Incorrect position of image with SVG backend

### ISSUE THREAD

**Issue by phausamann** [bokeh/bokeh#10731] opened 2020-11-26 14:03 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

* ubuntu 18.04
* Python 3.6.10
* bokeh 2.2.3
* Chrome 86 / Firefox 83

#### Description of expected behavior and the observed behavior

When plotting an `image` with `output_backend="svg"`, the image is shifted downwards, i.e. the top edge of the image is where the bottom edge should be.

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np

from bokeh.plotting import figure, output_file, show

N = 500
x = np.linspace(0, 10, N)
y = np.linspace(0, 10, N)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx)*np.cos(yy)

p = figure(tooltips=[("x", "$x"), ("y", "$y"), ("value", "@image")])
p.x_range.range_padding = p.y_range.range_padding = 0

# must give a vector of image data for image parameter
p.image(image=[d], x=0, y=0, dw=10, dh=10, palette="Spectral11", level="image")
p.grid.grid_line_width = 0.5

p.output_backend = "svg"

output_file("image.html", title="image.py example")

show(p)
```

#### Screenshots or screencasts of the bug in action

![screenshot](https://user-images.githubusercontent.com/4687996/100359540-ff34a580-2ff7-11eb-86e1-0568c8067e39.png)

**Comment by mattpap** [comment] 2020-11-26 14:29
This is a duplicate of issue #10725.

**Closed by mattpap** 2020-11-26 14:29 UTC
Labels: TRIAGE

**Comment by phausamann** [comment] 2020-11-26 15:46
Whoops, my bad. Did a search in the issues but didn't think to look in the closed issues. Thanks @mattpap for the recent work regarding SVG support.
