### ISSUE TITLE
Multicolors missing for non-circle glyphs with SVG Backend/Legends

### ISSUE THREAD

**Issue by Pelonza** [bokeh/bokeh#6836] opened 2017-08-29 16:53 UTC
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 0.12.6
Python 3.6.2
Spyder 3.2.1 (using it's installed ipython stuff)
Ipython 6.1.0
Displaying in Chrome, and Win10

#### Description of expected behavior and the observed behavior
When using the SVG backend, I'm trying to plot multiple glyphs, with multiple colors.

Current Behavior:
circle glyph correctly plots multiple colors, and shows them in the legend properly.
glyphs tested that do not:
triangle, diamond, asterisk, cross, square, inverted_triangle
Note that it does NOT matter which glyph is plotted first.
Adding multiple colors to legend only works if it's the FIRST thing plotted (it seems).
Legend color also seems to match last object added, while plotted color seems to match first color plotted.

Expected Behavior:
All the glyphs to work like circle... 

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import show
from bokeh.models import ColumnDataSource
from bokeh.palettes import RdBu3
from bokeh.plotting import figure

# code goes here between backticks
c1 = RdBu3[2] # red
c2 = RdBu3[0] # blue
x=[1, 2, 3, 4, 5, 6]
source8 = ColumnDataSource(dict(
    x=[1, 2, 3, 4, 5, 6],
    y=[2, 1, 2, 1, 2, 1],
    y1 = [2**i for i in x],
    color=[c1, c2, c1, c2, c1, c2],
    label=['hi', 'lo', 'hi', 'lo', 'hi', 'lo']
))

p2 = figure(x_range=(0, 7), y_range=(0, 35), plot_height=300, tools='save')

# Note legend field matches the column in `source`
p2.circle( x='x', y='y', radius=0.1, color='color', source=source8)
#Legend for circle turned off for example, since it overlays with triangle labels.
p2.triangle( x='x', y='y1', color='color', legend='label', source=source8)
output_file('tmp.html')
p2.output_backend="svg"
show(p2)
```

#### Stack traceback and/or browser JavaScript console output
N/A  -- No error is generated.

**Comment by bryevdv** [comment] 2017-08-29 18:52
Here's a screenshot

<img width="524" alt="screen shot 2017-08-29 at 13 51 41" src="https://user-images.githubusercontent.com/1078448/29838584-3336b8a6-8cc1-11e7-8571-03fec320079b.png">

@canavandl Do you think this is definitely an upstream problem with `canvas2svg` ?

**Comment by kratzert** [comment] 2018-04-16 11:01
It's still an issue in bokeh version 0.12.15. Are there any news related to this topic?

**Comment by bryevdv** [comment] 2018-04-16 13:43
No, if there was any news, you would see it here. There are simply many more issues than core contributors, so some things will take awhile. If anyone new wants to pitch in and look into this issue the help is certainly appreciated.

**Comment by bryevdv** [comment] 2018-05-10 16:30
This is actually a dupe of #6775

**Closed by bryevdv** 2018-05-10 16:30 UTC
Labels: tag: component: bokehjs, type: bug
