### ISSUE TITLE
Examples for ver 0.12.9: notebook_embed.ipynb

### ISSUE THREAD

**Issue by Nemecsek** [bokeh/bokeh#6959] opened 2017-09-20 12:32 UTC
examples/howto/server_embed/notebook_embed.ipynb:

even if the plot is updated, an error is returned at every slider change: 
`ERROR:bokeh.server.protocol_handler:error handling message Message 'PATCH-DOC' (revision 1): ValueError('passed window 5.0D in not compat with a datetimelike index',)`

**Comment by bryevdv** [comment] 2017-09-27 13:28
possibly related or dupe of #6831

**Comment by bryevdv** [comment] 2018-03-17 04:13
I am not able to reproduce any problem in recent versions. Please re-open with more information if there is still a reproducible issue.

**Closed by bryevdv** 2018-03-17 04:13 UTC
Labels: type: bug
