### ISSUE TITLE
HoverTool not working as expected with multi_line

### ISSUE THREAD

**Issue by Restmon** [bokeh/bokeh#8185] opened 2018-08-24 09:32 UTC
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
conda list:
# Name                    Version                   Build  Channel
bokeh                     0.13.0                   py36_0
#### Description of expected behavior and the observed behavior
When I use p.line(), I can get hover tools to **data(x,y): (2,2)**
When I use p.multi_line(), when I hover over the data points, it shows data(x,y): (1,2,3,4,5,6,7,8,9,10,9,8,7,6,5,4,3,2,1,0)
#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import output_file, show
from bokeh.layouts import gridplot
from bokeh.palettes import Viridis3
from bokeh.plotting import figure, show, ColumnDataSource, save, output_notebook, output_file, reset_output
from bokeh.palettes import plasma
from bokeh.models import HoverTool

colors = plasma(3)
hover = HoverTool(tooltips=[("data (x,y)", "($x, $y)")])
hover = HoverTool(tooltips=[("data (x,y)", "(@x, @y)")])
TOOLS=[hover]

### hover tool with line
p0=figure(width=400, height=200, tools=TOOLS)
p0.line([1,2,3],[1,2,3])
reset_output()
output_notebook()
show(p0)
xx = [x+1 for x in range(0,10)]
y0 = xx
y1 = [10 - i for i in xx]
y2 = [abs(i - 5) for i in xx]
y=[y0,y1,y2]        

### hover tool with multi_line
x_list, y_list, legs = [], [], []
hover = HoverTool(tooltips=[("data (x,y)", "($x, $y)")])
hover = HoverTool(tooltips=[("data (x,y)", "(@x, @y)")])
TOOLS=[hover]
p1 = figure(width=400, height=200, tools=TOOLS)
for i in range(0,3):
    x_list.append( xx )
    y_list.append( y[i] )
    legs.append( str( xx[i] ) )

source = ColumnDataSource( dict(x=x_list,y=y_list,legs=legs,colors=colors) )    
l = p1.multi_line( xs='x', ys='y', legend='legs', color='colors', source=source )

hover = HoverTool(tooltips=[("data (x,y)", "($x, $y)")])
hover = HoverTool(tooltips=[("data (x,y)", "(@x, @y)")])
TOOLS=[hover]
p2 = figure(width=400, height=200, tools=TOOLS)
source = ColumnDataSource( dict(x=x_list,y=y_list,legs=legs,colors=colors) )    
l = p2.multi_line( xs='x', ys='y', legend='legs', color='colors', source=source )

hover = HoverTool(tooltips=[("data (x,y)", "($x, $y)")])
hover = HoverTool(tooltips=[("data (x,y)", "(@x, @y)")])
TOOLS=[hover]
p3 = figure(width=400, height=200, tools=TOOLS)
source = ColumnDataSource( dict(x=x_list,y=y_list,legs=legs,colors=colors) ) 

l = p3.multi_line( xs='x', ys='y', legend='legs', color='colors', source=source )
# make a grid
grid = gridplot([[p1, p2], [None, p3]])

# show the results
reset_output()
output_notebook()
#show(p1)    
show(grid)

```

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/38109823/44577407-56040280-a791-11e8-80bb-eafc33dab382.png)
![image](https://user-images.githubusercontent.com/38109823/44577435-62885b00-a791-11e8-8f09-c0cac10ffb74.png)

**Comment by bryevdv** [comment] 2018-08-24 16:59
This is a dupe of #7969

**Closed by bryevdv** 2018-08-24 16:59 UTC
