### ISSUE TITLE
BokehJS incorrect height calcs of Boxview

### ISSUE THREAD

**Issue by Hanterdro** [bokeh/bokeh#5716] opened 2017-01-13 10:24 UTC
I found an layouting issue with BokehJS:
If a Boxview is above a plot the height of the bokeh container is too small and bokeh is overlapping the container. Elements outside the bokeh container may be overlapped by bokeh.

Basically the issue is that `BoxView.prototype.get_height` ignores margins.

An easy bugfix for this would be

`height += $(child_view.el).outerHeight(true);`
and remove the silly magic `+ 20` for the height.

```
  WidgetBoxView.prototype.get_height = function() {
    var child_view, height, key, ref1;
    height = 0;
    ref1 = this.child_views;
    for (key in ref1) {
      if (!hasProp.call(ref1, key)) continue;
      child_view = ref1[key];
      height += $(child_view.el).outerHeight(true);
    }
    return height;
  };
```

instead of

```
  WidgetBoxView.prototype.get_height = function() {
    var child_view, height, key, ref1;
    height = 0;
    ref1 = this.child_views;
    for (key in ref1) {
      if (!hasProp.call(ref1, key)) continue;
      child_view = ref1[key];
      height += child_view.el.scrollHeight;
    }
    return height + 20;
  };
```

With this fix `get_height()` returns the expected value. But this value is not used for the container box in `LayoutDOMView.prototype.render`.
![bildschirmfoto 2017-01-13 um 11 15 21](https://cloud.githubusercontent.com/assets/7668392/21926615/cfe11734-d982-11e6-9a8b-e27fe4d04582.png)

**Comment by bryevdv** [comment] 2017-01-13 21:14
@Hanterdro would you mind submitting a PR with this change? I'd be happy to test it out

**Comment by Hanterdro** [comment] 2017-01-16 08:39
Yeah... I could do that... but why? :-)
My changes did not fix the issue with the incorrect height calculation of the container box.
I expected that it would.
The bokehJS API function call `get_height` returns with my changes the correct value, but internally this functions seems not to be used to set the height for the container.

**Comment by Hanterdro** [comment] 2017-01-16 09:11
However, I created the pull request.
I hope this will help.

https://github.com/bokeh/bokeh/pull/5739

**Comment by Hanterdro** [comment] 2017-01-16 13:54
Good news, my bugfix is working.

I was initially lazy and did my changes directly in the build files.
After I added the bugfix it in the source file and started the build tasks the fix is working as expected.

**Comment by Hanterdro** [comment] 2017-01-16 14:41
Okay... I don't get it..

I reinstalled the original bokeh (we are using 0.12.3) and it's still working. I documented in  the screenshot above the height was 538px of the bokeh container box. After reinstalling bokeh 0.12.3 it's always 558px (it should be 568px).

It's no cache issue. I tried it in different browsers and cleared the cache.

That means my bugfix has still only an impact for the api function to get the correct height, but it's not used for the styling of the container box.

**Comment by bryevdv** [comment] 2018-05-10 18:58
I am closing this because I am not sure what the current status is (there has been alot of layout work in the interim) and because there is not a complete reproducer here for me to try and find out. If there is still an issue, please post a complete test script and we can re-open.

**Closed by bryevdv** 2018-05-10 18:58 UTC
