### ISSUE TITLE
Bokeh Wedge Chart: Hover Tooltip Showing All Values

### ISSUE THREAD

**Issue by gg315** [bokeh/bokeh#7471] opened 2018-01-29 18:31 UTC
Bokeh Version: 0.12.13
Python Version: 3.6.3
OS: Microsoft Windows 10 Pro

I'm trying to add a hover tooltip to a Bokeh pie chart made using wedge glyphs, but the hover tool shows multiple values for a given wedge.

```
import numpy as np
from bokeh.plotting import figure
from bokeh.io import show, output_file
from bokeh.models import HoverTool, ColumnDataSource
from math import pi

percents = [0, 5/143, 51/143, 88/143, 108/143, 141/143, 1.0]
category = ['A ', 'B ', 'C ', 'D ', 'E ', 'F']
counts = [5, 46, 37, 20, 33, 2]
starts = [1/2*pi-(p*2*pi) for p in percents[:-1]]
ends = [1/2*pi-(p*2*pi) for p in percents[1:]]
colors = ['#889dba', '#1f356f', '#1e92b8', '#33748a', '#a5d3e3', '#bbc2d4']
# create source
source = ColumnDataSource(
    data=dict(
        x=[0 for x in percents],
        y=[0 for x in percents],
        radius = [0.5 for x in percents],
        percents=percents,
        category= category,
        starts=starts,
        colors=colors,
        ends=ends,
        counts = counts
    )
)

TOOLS = "hover"

p = figure(plot_width = 500, plot_height = 500, x_axis_label = None, y_axis_label = None,
title = 'Type', tools = TOOLS)

p.title.align = 'center'
p.title.text_font = 'arial narrow'

p.wedge(x='x', y='y',  radius = 'radius', direction="clock",
                start_angle='starts', end_angle='ends', color='colors', source=source)

hover = p.select(dict(type=HoverTool))
hover.tooltips = [
    ('category', '@category'),
    ('percents','@counts')
]

p.axis.visible = False
p.ygrid.visible = False
p.xgrid.visible = False

output_file('pie.html')
show(p)

```

![bokeh_pie](https://user-images.githubusercontent.com/35930875/35527410-a6b81428-04f8-11e8-81f7-2ec6ce036787.png)

**Comment by bryevdv** [comment] 2018-01-29 18:35
This is a dupe of https://github.com/bokeh/bokeh/issues/7428

**Closed by bryevdv** 2018-01-29 18:35 UTC
