### ISSUE TITLE
Python event callback not called if no JS event callback is registered

### ISSUE THREAD

**Issue by kevinsa5** [bokeh/bokeh#6059] opened 2017-03-23 22:33 UTC
I am using the latest github release, 0.12.5rc1, which has the new generalized event callback system.  If I register a javascript callback, then the corresponding python callback is called correctly, but if the javascript callback is omitted, the python callback isn't called.  Example code:

    from bokeh.io import curdoc
    from bokeh.plotting import figure
    from bokeh import events
    from bokeh.models import CustomJS  

    x = range(1,10)
    y = range(1,10)
    p = figure(tools="pan,wheel_zoom,zoom_in,zoom_out,reset")
    p.scatter(x, y)

    def callback(attrs):
        print "python callback"

    # uncomment this line:
    #p.js_on_event(events.Tap, CustomJS(code="",args={}))
    p.on_event(events.Tap,  callback)

    curdoc().add_root(p)

If you uncomment `p.js_on_event(events.Tap, CustomJS(code="",args={}))`, then the python callback runs as expected.  If the `js_on_event` line is left commented, then the python callback is not called.  

System info, can provide more if desired:

    webdashboard@dash:~$ bokeh --version
    0.12.5rc1
    webdashboard@dash:~$ python --version
    Python 2.7.12
    webdashboard@dash:~$ cat /etc/lsb-release 
    DISTRIB_ID=Ubuntu
    DISTRIB_RELEASE=16.04
    DISTRIB_CODENAME=xenial
    DISTRIB_DESCRIPTION="Ubuntu 16.04.2 LTS"

Browser:  Chrome `Version 56.0.2924.87 (64-bit)` on Windows 7.

**Comment by bryevdv** [comment] 2017-03-24 00:48
can reproduce, @jlstevens the `events_app.py` example only works because it also happens to have `js_on_event` calls.

**Comment by jlstevens** [comment] 2017-03-24 02:01
Thanks for reporting this issue! I'll be investigating it shortly.

**Comment by jlstevens** [comment] 2017-03-24 12:27
This issue should be fixed by the PR referenced above.

**Comment by canavandl** [comment] 2017-04-05 14:22
resolved by #6062

**Closed by canavandl** 2017-04-05 14:22 UTC
Labels: CRITICAL, tag: component: server, type: bug
