### ISSUE TITLE
Plot tools not working correctly on slides created with ipython

### ISSUE THREAD

**Issue by zelite** [bokeh/bokeh#2826] opened 2015-09-09 09:46 UTC
I'm using bokeh 0.9.3.
I created a plot inside a IPython Notebook and the box zoom tool shows up a green square around the region I am selecting:

![image](https://cloud.githubusercontent.com/assets/9040070/9758593/ec12a950-56e7-11e5-9fd8-a29bcff63aa6.png)

When converting the IPython Notebook to a slideshow using nbconvert, the tools do not work correctly for the plot. The box zoom still makes the zoom, but does not show the green square, so I don't know exactly where I am zooming. 

I am using Google Chrome Version 45.0.2454.85 m (64-bit) on Windows.

**Comment by bryevdv** [comment] 2015-09-09 12:59
@damianavila thoughts? I thought this was a duplicate of an upstream issue (recently remember something about nbcovert slides not working, and it being a problem on the IPython side) but I can't find the issue I was thinking of.

**Comment by bryevdv** [comment] 2015-09-09 12:59
@zelite can you confirm this is a problem on other browsers/platforms?

**Comment by zelite** [comment] 2015-09-09 13:04
I see the same problem on internet explorer 10.

**Comment by damianavila** [comment] 2015-09-09 18:16
Yes, this is a problem in nbconvert, I will report back here when the upstream issue is solved.

**Comment by bryevdv** [comment] 2015-12-29 04:16
@damianavila any updates?

**Comment by damianavila** [comment] 2015-12-29 21:33
>@damianavila any updates?

Not yet... 
I guess I will re-explore the issue and submit a fix some time over next week (as time permits)

**Comment by bryevdv** [comment] 2016-01-27 05:37
@damianavila do you have a reference to the upstream issue so that we can monitor it here?

**Comment by damianavila** [comment] 2016-01-28 13:53
https://github.com/jupyter/nbconvert/issues/29 and somewhat related: https://github.com/jupyter/nbviewer/issues/484

**Comment by bryevdv** [comment] 2016-07-03 04:24
working fine now with `nbconvert 4.2.0`, closing

**Closed by bryevdv** 2016-07-03 04:24 UTC
Labels: reso: upstream, type: bug

**Comment by damianavila** [comment] 2017-05-31 20:46
> working fine now with nbconvert 4.2.0, closing

Some additional info, I tried with latest nbconvert 5.2.1 and Bokeh 0.12.5 and it works OK.
