### ISSUE TITLE
[BUG] nan_color argument in LinearColorMapper is not used

### ISSUE THREAD

**Issue by harmbuisman** [bokeh/bokeh#9174] opened 2019-08-19 13:59 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh.version: 1.3.0
python: 3.7.3
OS: Windows 10
browser: all

#### Description of expected behavior and the observed behavior
LinearColorMapper has the option to set nan_color. It is however not used. Instead it sets the color of the nan entry to be the lowest color in the range.

In the example below you should see the center region as black, but instead it shows as lowest color in the range.

#### Complete, minimal, self-contained example code that reproduces the issue
To run, download this file: [provinces.zip](https://github.com/bokeh/bokeh/files/3516224/provinces.zip)

```
import geopandas as gpd 
import numpy as np
from bokeh.palettes import Reds
from bokeh.models import GeoJSONDataSource, LinearColorMapper
from bokeh.plotting import figure, show

geodf = gpd.read_file("provinces.geojson")
geodf.loc[6, 'index'] = np.nan
print(geodf)
color_mapper = LinearColorMapper(palette=Reds[9][::-1], nan_color='black')

p = figure()
geo_source = GeoJSONDataSource(geojson=geodf.to_json())
p.patches('xs', 'ys', fill_alpha=1, 
              fill_color={'field': 'index', 'transform': color_mapper}, 
              line_color='white', line_width=0.5, 
              source=geo_source)

show(p)

```

#### Stack traceback and/or browser JavaScript console output
Data frame that is plotted
![image](https://user-images.githubusercontent.com/7702207/63271195-e6d4c780-c299-11e9-8783-6c37575b57de.png)

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/7702207/63375838-d0f3ff00-c38c-11e9-8d01-d54942ccbb1d.png)

**Comment by mattpap** [comment] 2019-08-19 14:15
This is broken by design, because the color mapper you configured is only used to compute the scale (used for label placement) of the color bar, but actual color mapping is done by an internal linear color mapper created by the color bar. There's ongoing effort to improve color bar annotation in general, so this should be fixed in near future.

**Comment by harmbuisman** [comment] 2019-08-20 18:57
> This is broken by design, because the color mapper you configured is only used to compute the scale (used for label placement) of the color bar, but actual color mapping is done by an internal linear color mapper created by the color bar. There's ongoing effort to improve color bar annotation in general, so this should be fixed in near future.

@mattpap, thanks for your reply. I updated the example, this is not about the colorbar, but about the color in the patches. With this example without a colorbar I expect the center region (Utrecht) to be black, as it has a NaN value, but instead it shows almost white.

**Comment by bryevdv** [comment] 2019-08-20 19:26
I don't actually know much about `GeoJSONDataSource`. I wonder if it doesn't apply the base64 encoding for arrays? Although things accidentally work in other cases, NaN values are only truly faithfully reproduced in JS typed arrays over the Bokeh server's binary array protocol or the base64 encoded CDS columns in standalone output (this is due to the glaring omission of nan/inf values in the JSON Standard)

Thanks for he complete MRE @harmbuisman we will take a closer look with it.

**Comment by bryevdv** [comment] 2019-08-20 19:37
This is definitely the issue, this ends up as `null` (not `NaN`) on the JS side:

 > {\"Regio\": \"Utrecht\", \"index\": null}, 

Offhand I am not sure what good solution there would be. If forgot the GeoJSON data is record oriented, the base64 encoding is not really going to work here. JSON does not have a NaN value, there is nothing we can do about that. The only options that come to mind:

* allow color mappers to treat `null` equivelently to `nan`, relying on the accidental deserialization of `"nan"` the string into `null` here
* allow users to specify their own special sentinel value and add an option to supply a color for a user sentinel

**Comment by bryevdv** [comment] 2019-08-21 02:32
@mattpap something like `if (isNaN(d) || d == null)` does produce the expected plot:

<img width="425" alt="Screen Shot 2019-08-20 at 7 30 48 PM" src="https://user-images.githubusercontent.com/1078448/63397991-07c41800-c381-11e9-8cf6-3e7a38fe2128.png">

but also necessitates fixing up `max` and `min` at a start and then type gymnastics spiral out from there. Do you have any thoughts? We could also copy the data at the public interface and replace any `null` values with `NaN` which would spare any downstream code changes but at the expense of performance, of course.

**Comment by bryevdv** [comment] 2019-08-21 02:41
Tho it's also worth noting: this specific NaN must be getting converted to `None` somewhere? The only thing `json` serialization normally converts to `null` (which is what is in the actual JSON output) is None

**Comment by bryevdv** [comment] 2019-08-21 03:05
Yes, brilliant this small change fixes:
```
diff --git a/bokehjs/src/lib/models/sources/geojson_data_source.ts b/bokehjs/src/lib/models/sources/geojson_data_sourc
index a7918a425..aa532614c 100644
--- a/bokehjs/src/lib/models/sources/geojson_data_source.ts
+++ b/bokehjs/src/lib/models/sources/geojson_data_source.ts
@@ -31,6 +31,10 @@ export namespace GeoJSONDataSource {

 export interface GeoJSONDataSource extends GeoJSONDataSource.Attrs {}

+function _orNaN(v: number | undefined) {
+  return v != null ? v : NaN
+}
+
 export class GeoJSONDataSource extends ColumnarDataSource {
   properties: GeoJSONDataSource.Props

@@ -75,16 +79,12 @@ export class GeoJSONDataSource extends ColumnarDataSource {
     for (const property in properties) {
       if (!data.hasOwnProperty(property))
         data[property] = this._get_new_nan_array(item_count)
-      data[property][i] = properties[property]
+      data[property][i] = _orNaN(properties[property])
     }
   }

   private _add_geometry(geometry: GeoItem, data: GeoData, i: number): void {

-    function orNaN(v: number | undefined) {
-      return v != null ? v : NaN
```

`_add_properties` tried to handle this by pre-populating nan arrays for the values but it did not  all "orNan" on each value, so nulls that made it over would just overwrite the nans. I will add a PR for this later this week unless someone else gets to it first (needs a unit test)

**Comment by harmbuisman** [comment] 2019-08-21 08:16
@bryevdv, great to read you found a solution, thanks for the quick turnaround!

**Closed** 2019-08-22 22:49 UTC
Labels: tag: component: bokehjs, type: bug
