### ISSUE TITLE
Websocket error on patch_app.py in Safari

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#6611] opened 2017-07-13 15:18 UTC
Running bokeh 0.12.7.dev10
OS: OS X 10.12.5
Browser: Safari

When running the patch_app.py example, `bokeh serve patch_app.py`, nothing shows up in Safari. The console shows the error:

```
http://localhost:5006/static/js/bokeh.min.js?v=c031e66fc3ed77a3033024e2c61aaedeWebSocket connection to 'ws://localhost:5006/patch_app/ws?bokeh-protocol-version=1.0&bokeh-session-id=jiQ00Sjn1O7qmsLJVr0fteDB8hw4gaYNJdjUwmp4wy8v' failed: Failed to send WebSocket frame.
```

If I keep refreshing the page it will sometimes load. There is no error in the terminal.

The app runs as expected in Firefox and Chrome.

**Comment by bryevdv** [comment] 2017-07-13 15:20
This is a dupe of https://github.com/bokeh/bokeh/issues/6196

 The upstream issue in WebKit has been fixed in recent Safari Technology previews, there's unfortunately nothing we can do except wait for the next release of Safari and tell people to upgrade.

**Closed by bryevdv** 2017-07-13 15:20 UTC

**Comment by bryevdv** [comment] 2017-07-13 15:32
@hsparra new comment https://github.com/bokeh/bokeh/issues/6196#issuecomment-315113724
