### ISSUE TITLE
No longer able to load BokehJS in jupyter notebook

### ISSUE THREAD

**Issue by OrangeBoreal** [bokeh/bokeh#5351] opened 2016-10-14 11:23 UTC
I use bokeh to render plots in my jupyter notebook. As of this morning, the BokehJS extension is not loading anymore in my notebooks. 
![bokeh_bug](https://cloud.githubusercontent.com/assets/17804108/19385552/56d408ca-920f-11e6-8aaa-80765cfe2e55.png)
`import bokeh.io
bokeh.io.output_notebook()` 
prints "Loading BokehJS ..." as usual, but then does not move to the "BokekJS sucessfully loaded" expected. Trying to plot anything then results to nothing. 

Jupyter local server console logs are : 
[I 13:03:06.046 NotebookApp] Loaded extension jupyter_nbextensions_configurator
[I 13:03:06.048 NotebookApp] Serving notebooks from local directory: /home/sdg/Programmation
[I 13:03:06.048 NotebookApp] 0 active kernels 
[I 13:03:06.049 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 13:03:06.049 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[W 13:03:25.831 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20161014130305 (127.0.0.1) 6.30ms referer=http://localhost:8888/notebooks/librariesWKdatascience/projects/scores/Untitled.ipynb
[I 13:03:26.459 NotebookApp] Kernel started: 5d4b17a3-9612-4f4b-b886-bafbfc72f9ab
[I 13:05:26.322 NotebookApp] Saving file at /librariesWKdatascience/projects/scores/Untitled.ipynb
[I 13:06:18.058 NotebookApp] Kernel restarted: 5d4b17a3-9612-4f4b-b886-bafbfc72f9ab
[I 13:06:41.664 NotebookApp] Kernel restarted: 5d4b17a3-9612-4f4b-b886-bafbfc72f9ab
[I 13:07:26.345 NotebookApp] Saving file at /librariesWKdatascience/projects/scores/Untitled.ipynb

Both bokeh and jupyter notebook have been reinstalled and upgraded to lastest versions. I've tried on Mozilla Firefox (49.0) and Chromium (53.0.2785.143), including in private navigation to exclude caches problems.

I use a vex virtual env with pip, here's the result of `pip freeze` : 
azure-common==1.1.4
azure-nspkg==1.0.0
azure-storage==0.32.0
backports.shutil-get-terminal-size==1.0.0
bokeh==0.12.3
branca==0.1.1
Cython==0.24
dateutils==0.6.6
decorator==4.0.10
docopt==0.6.2
entrypoints==0.2.2
folium==0.2.1
influxdb==3.0.0
ipykernel==4.5.0
ipython==5.1.0
ipython-genutils==0.1.0
ipywidgets==5.2.2
Jinja2==2.8
jsonschema==2.5.1
jupyter==1.0.0
jupyter-client==4.4.0
jupyter-console==5.0.0
jupyter-contrib-core==0.3.0
jupyter-contrib-nbextensions==0.2.0
jupyter-core==4.2.0
jupyter-nbextensions-configurator==0.2.2
lxml==3.6.1
MarkupSafe==0.23
mistune==0.7.3
nbconvert==4.2.0
nbformat==4.1.0
nbgen==0.1.2
neo4jrestclient==2.1.1
notebook==4.2.3
numexpr==2.6.1
numpy==1.11.2
pandas==0.18.1
pexpect==4.2.1
pickleshare==0.7.4
pkgconfig==1.1.0
prompt-toolkit==1.0.7
psutil==4.3.1
ptyprocess==0.5.1
py==1.4.31
pygal==2.2.3
Pygments==2.1.3
pytest==2.9.2
python-dateutil==2.5.3
pytz==2016.6.1
PyYAML==3.12
pyzmq==16.0.0
qtconsole==4.2.1
requests==2.11.1
scikit-learn==0.17.1
scipy==0.17.1
simplegeneric==0.8.1
six==1.10.0
sklearn==0.0
tables==3.2.3.1
terminado==0.6
tornado==4.4.2
traitlets==4.3.1
ujson==1.35
wcwidth==0.1.7
widgetsnbextension==1.2.6

The OS is Ubuntu 16.04.1 LTS.

**Comment by ewjoachim** [comment] 2016-10-14 11:54
Do you have errors in the JS console ?

**Comment by OrangeBoreal** [comment] 2016-10-14 11:59
loaded custom.jsUntitled.ipynb:121:15
Default extension for cell metadata editing loaded.main.min.js:24136:9
Raw Cell Format toolbar preset loaded.main.min.js:24222:5
Slideshow extension for metadata editing loaded.main.min.js:24270:9
actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...main.min.js:29058:17
Bokeh: BokehJS not loaded, scheduling load and callback at Date 2016-10-14T11:52:29.361Zmain.min.js:61:5
Bokeh: injecting script tag for BokehJS library:  "https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js"main.min.js:78:7
Bokeh: injecting script tag for BokehJS library:  "https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.3.min.js"main.min.js:78:7
Bokeh: BokehJS is being loaded, scheduling callback at Date 2016-10-14T11:52:29.458Zmain.min.js:53:9
Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0main.min.js:33964:17
"failed to load library https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.3.min.js"main.min.js:76:9
"failed to load library https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.3.min.js"main.min.js:76:9
Session: kernel_created (dd95437e-c9ea-4631-ae58-a30b7e16bcee)main.min.js:23424:13
Starting WebSockets: ws://localhost:8888/api/kernels/297a8f7c-62ea-47bf-bb90-8452f74e3d25main.min.js:22710:9
Kernel: kernel_connected (297a8f7c-62ea-47bf-bb90-8452f74e3d25)main.min.js:22357:13
Kernel: kernel_ready (297a8f7c-62ea-47bf-bb90-8452f74e3d25)main.min.js:22357:13
Bokeh: BokehJS not loaded, scheduling load and callback at Date 2016-10-14T11:54:05.463Zmain.min.js:61:5
Bokeh: injecting script tag for BokehJS library:  "https://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js"main.min.js:78:7
Bokeh: injecting script tag for BokehJS library:  "https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.3.min.js"main.min.js:78:7
"failed to load library https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.3.min.js"

**Comment by ewjoachim** [comment] 2016-10-14 12:05
It's actually a duplicate of #5350 .

**Closed** 2016-10-14 12:06 UTC
Labels: reso: duplicate

**Comment by ewjoachim** [comment] 2016-10-14 12:38
Just so you or someone finding this issue knows :

```python
from bokeh.resources import INLINE
import bokeh.io
bokeh.io.output_notebook(INLINE) 
```

This will not use the CDN, so in case there's a problem in the future and while it's not solved, this will work. 

![All long help threads should have a sticky globally-editable post at the top saying 'DEAR PEOPLE FROM THE FUTURE: Here's what we've figured out so far ...'](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

**Comment by bryevdv** [comment] 2016-10-14 12:42
Setting the environment variable `BOKEH_RESOURCES=inline` will also for `INLINE` resources, but without requiring any code changes.

**Comment by ewjoachim** [comment] 2016-10-14 12:52
For the scope of the notebook, it's not always handy to change the way it's launched. I imagine both solutions could be useful, depending of the users. Everyone isn't always confortable with env vars ^^

**Comment by bryevdv** [comment] 2016-10-14 14:47
The immediate SSL issue should be resolved now please confirm

**Comment by OrangeBoreal** [comment] 2016-10-17 08:51
Thank you, everything is working fine now.

**Comment by swevrywhere** [comment] 2017-01-24 23:30
I started having a similar problem today. Bokeh worked for me a couple weeks ago. How can I display the JS console to see if it's a similar problem? Thanks!

**Comment by bryevdv** [comment] 2017-01-24 23:35
> I started having a similar problem today. Bokeh worked for me a couple weeks ago. How can I display the JS console to see if it's a similar problem? Thanks! 

It's specific to every browser. You will have to GIS search for how to bring up the "JavaScript Console" for whichever browser you are using. If you find a reproducible problem, please open a ***new*** issue with code to reproduce.

**Comment by swevrywhere** [comment] 2017-02-12 00:27
I just thought I'd share the solution to my problem, in case it's helpful to others. What happened was that I was all of a sudden not able to access pydata.org from my VPN. By default, Bokeh uses a server at bokeh.pydata.org. Once IT fixed the pydata.org connection issue, it worked fine again.

**Comment by shr00mie** [comment] 2018-04-29 18:59
@ewjoachim:
dude. i spent like...3 days trying to figure out wtf is wrong and your inline code is...literally the ONLY mention i've seen on Hydrogen, jupyterlab, or bokeh githubs/forums/mailgroups let alone any of the bokeh documentation.

people need to update their shit.

p.s. love you long time. gonna go try on remote kernel and see if that works as well.
