### ISSUE TITLE
New hover features

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#5073] opened 2016-09-01 19:51 UTC
- [ ] Add ability to style hover via python
- [x] Add ability to turn off pointer/arrow
- [ ] clean-up code around "custom" tooltips as it now has no impact on styling
- [ ] Add ability to customize the hit radius

**Comment by mattpap** [comment] 2016-09-02 07:46
> Add ability to turn off pointer/arrow

This was done in #4907.

**Comment by birdsarah** [comment] 2016-09-02 07:50
> This was done in #4907.

SCORE! 🎁

**Comment by bryevdv** [comment] 2017-06-22 03:57
The hit radius task is a dupe of #2230 The other tasks I think we can just pass on

**Closed by bryevdv** 2017-06-22 03:57 UTC
Labels: tag: component: bokehjs, tag: starter, type: feature
