### ISSUE TITLE
[BUG] Bokeh Saving SVG error

### ISSUE THREAD

**Issue by goldentoby** [bokeh/bokeh#9950] opened 2020-04-21 17:53 UTC
As I am aiming to plot the data into the plot, I encounter 2 problems.

(1) For the Bokeh function, while I am plotting 4 pictures in a row and adding the save as the SVG. Then the browser is shown as figure1. Moreover, as I comment out the code below, it works definitely right as I thought(figure2). It's weird.
figure1: https://i.stack.imgur.com/MR5i3.png
figure2: https://i.stack.imgur.com/E6pOw.png

```python
p1.output_backend = "svg"
export_svgs(p1, filename="./number_like_comment/fig/{}.svg".format(action_str))
```

(2) For the second question, after I save those files, I realized that the "Label" I put in the plot also disappear. (as figure3).

figure3: https://i.stack.imgur.com/aO4II.png

Thanks so much for reading through. This question bothers me quite a long time.

**Comment by goldentoby** [comment] 2020-04-21 18:00
On the Bokeh Console, there are no errors. But on the js console, it looks like this. imgur.com/a/5qgQRcL

**Comment by goldentoby** [comment] 2020-04-21 18:04
For the function of exporting SVG I think it is quite important to me. I am aiming to export the paper's figure. I would also eager to know the alternative method in order to save the vector format of the picture. Zoom in will not be vague.

**Comment by goldentoby** [comment] 2020-04-21 18:07
As I expend the error in the JS console. https://imgur.com/a/xQDnMig

**Comment by bryevdv** [comment] 2020-04-21 18:10
HI @goldentoby please provide actual code to reproduce

**Comment by goldentoby** [comment] 2020-04-21 18:26
For this, the code is a bit lengthy. I place it on the google drive.
As you download the corresponding file. Just operate to following cli.

```
bokeh serve number_like_comment
```

Then it should work.

https://drive.google.com/drive/folders/1eWLZd95VUe-EgGuWsOhAUJNo_Wf03_2_?usp=sharing

**Comment by bryevdv** [comment] 2020-04-21 18:38
@goldentoby Respectfully, please whittle things down. We really need to have a *minimal complete reproducer*. So if the problem show up in one plot, we don't need the extra code for four. If it does not involve styling or tools or or if simple fake data will do instead of ay kind of actual unrelated computation, then all of that should be stripped out.  There are ~500 issues here on the tracker, so it is imperative that users making reports put in some effort to make the report as simple and focused as possible. Ideally an MRE is a few tens of lines.  If OSS is to be successful, it has to be a collaboration involving users.

**Comment by syntonym** [comment] 2020-04-21 21:15
The problem is with 0 values and a logarithmic axis, the canvas renderer will skip the line segments coming from/going to 0, while the svg renderer will not render the entire line. A logarithmic y axis shows the same behavior. Code to reproduce:

```
p = figure(x_axis_type="log")
p.line(x=[0, 1, 2], y=[1,1,1])
p.output_backend = "svg"
show(p)
```

**Comment by bryevdv** [comment] 2020-04-21 21:59
@goldentoby can you confirm if there are zeros in your data? 

If so, zeros on log axes are not currently supported, so I would close this. It's possible #6517 will be implemented at some point to add a "symlog" scale (though that really only seems useful in a narrow set of use cases to me).

**Comment by goldentoby** [comment] 2020-04-22 01:53
First of all, sorry for providing the lengthy code for debugging, I'll be careful next time. 

Sorry for the late reply, Just wake up. I remove the 0 value in both the x and y-axis. it works!! Huge thanks for the reach out. 

Currently, there is still a problem in showing the Label while saving SVG. I've e search through the  Issue pages, it seems to be a problem of not detecting the DOM in the HTML. I'd like to ask whether it is solved or having another way around.(The problem is noted in problem 2 above) Huge Thanks for the help.

**Comment by goldentoby** [comment] 2020-04-22 01:54
It supposes to have the text inside.

https://i.stack.imgur.com/aO4II.png

**Comment by goldentoby** [comment] 2020-04-22 16:46
@bryevdv Looking for helps.

**Comment by bryevdv** [comment] 2020-04-22 17:59
@goldentoby OSS projects are run on an all-volunteer effort. Cycle times for issues are are often measured in days, weeks, or sometimes months. This is not an on-call help desk, and there is no SLA. 

Apart from that, I don't actually know what you are seeking. The latest image, that is an incorrect image? Or the correct one? Or something else? What is missing? What is the code that generated it? Are you specifying a css render mode for labels? Are you even using actual `Label` objects or do you mean something else? (Impossible to know without code this is why minimal code is essential to provide)

**Comment by bryevdv** [comment] 2020-08-25 05:53
I'm still not sure what is actionable here, or even what the issue is. Recent 2.2 had a large overhaul of SVG export that fixed many bugs, so hopefully that include this one.

**Closed by bryevdv** 2020-08-25 05:53 UTC
Labels: NEEDS MORE INFO, type: discussion
