### ISSUE TITLE
ImportError: cannot import name XYBuilder

### ISSUE THREAD

**Issue by johanwasserman** [bokeh/bokeh#3839] opened 2016-02-06 21:38 UTC
Upgraded Bokeh this morning.

Installing collected packages: futures, bokeh

  Found existing installation: bokeh 0.10.0

    Uninstalling bokeh-0.10.0:

      Successfully uninstalled bokeh-0.10.0

Successfully installed bokeh-0.11.1 futures-3.0.4

Now I'm getting

traceback (most recent call last):

  File "[path]/Workspaces/Eclipse/random_tests/trd_calc/calculate.py", line 7, in <module>

    from bokeh.charts import Line, output_file, show

  File "[path]/anaconda2/lib/python2.7/site-packages/bokeh/charts/__init__.py", line 21, in <module>

    from .builders.line_builder import Line

  File "[path]/anaconda2/lib/python2.7/site-packages/bokeh/charts/builders/line_builder.py", line 22, in <module>

    from ..builder import XYBuilder, create_and_build
ImportError: cannot import name XYBuilder

**Comment by bryevdv** [comment] 2016-02-06 21:43
Seems like you the installation went awry somehow. The file/class are definitely still part of the package:

https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builder.py#L551

As a first recommendation I can only suggest a fresh install, after clearing out anything Bokeh-related from your `site-packages`. 

@bokeh/core any ideas? Does pip leave old `.pyc` files around on upgrade or something?

**Comment by johanwasserman** [comment] 2016-02-06 21:46
Thanks for your quick response @bryevdv, that did the trick.

**Comment by bryevdv** [comment] 2016-02-06 22:08
@johanwasserman great I am glad that worked for you, I am going to mark this as a bug in case there is anything we can do to help prevent this situation in the future.

**Comment by pzwang** [comment] 2016-03-04 02:22
OK FYI I figured out the problem.  The old `builder/` directory in `bokeh/charts/`is no longer part of Bokeh due to a refactor, but in some installations it can get left behind, and this screws up the import.  The proper fix, as @bryevdv suggested, is to remove any old `bokeh*` artifacts in your `site-packages`, and that should fix the problem.

**Comment by bryevdv** [comment] 2016-03-04 03:37
FWIW I think this seems to happen with pip

**Comment by bryevdv** [comment] 2016-04-10 01:07
I just tried to reproduce this with pip `8.1.1` and could not (see attached log), so perhaps this issue has been fixed upstream. I am closing for now. Please re-open if the issue is found to persist with recent `pip`

---

```
bryan@0199-bryanv  /tmp $ conda create -n piptest python=3.4 pip numpy 
Remote site alias https://api.anaconda.org does not exist in the config file
Fetching package metadata: ......
Solving package specifications: .........

Package plan for installation in environment /Users/bryan/anaconda/envs/piptest:

The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    numpy-1.11.0               |           py34_0         2.7 MB
    setuptools-20.6.7          |           py34_0         459 KB
    pip-8.1.1                  |           py34_1         1.6 MB
    ------------------------------------------------------------
                                           Total:         4.7 MB

The following NEW packages will be INSTALLED:

    mkl:        11.3.1-0     
    numpy:      1.11.0-py34_0
    openssl:    1.0.2g-0     
    pip:        8.1.1-py34_1 
    python:     3.4.4-0      
    readline:   6.2-2        
    setuptools: 20.6.7-py34_0
    sqlite:     3.9.2-0      
    tk:         8.5.18-0     
    wheel:      0.29.0-py34_0
    xz:         5.0.5-1      
    zlib:       1.2.8-0      

Proceed ([y]/n)? y

Fetching packages ...
numpy-1.11.0-p 100% |#########################################################################################################################################################| Time: 0:00:06 443.66 kB/s
setuptools-20. 100% |#########################################################################################################################################################| Time: 0:00:00 753.44 kB/s
pip-8.1.1-py34 100% |#########################################################################################################################################################| Time: 0:00:01   1.27 MB/s
Extracting packages ...
[      COMPLETE      ]|############################################################################################################################################################################| 100%
Linking packages ...
[      COMPLETE      ]|############################################################################################################################################################################| 100%
#
# To activate this environment, use:
# $ source activate piptest
#
# To deactivate this environment, use:
# $ source deactivate
#
bryan@0199-bryanv  /tmp $ source activate piptest
discarding /Users/bryan/anaconda/bin from PATH
prepending /Users/bryan/anaconda/envs/piptest/bin to PATH
(piptest)bryan@0199-bryanv  /tmp $ pip install bokeh==0.10.0
Collecting bokeh==0.10.0
  Using cached bokeh-0.10.0.tar.gz
Collecting six>=1.5.2 (from bokeh==0.10.0)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting requests>=1.2.3 (from bokeh==0.10.0)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting PyYAML>=3.10 (from bokeh==0.10.0)
Collecting python-dateutil>=2.1 (from bokeh==0.10.0)
  Downloading python_dateutil-2.5.2-py2.py3-none-any.whl (201kB)
    100% |████████████████████████████████| 204kB 2.3MB/s 
Collecting Jinja2>=2.7 (from bokeh==0.10.0)
  Using cached Jinja2-2.8-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh==0.10.0)
Collecting pandas>=0.11.0 (from bokeh==0.10.0)
  Downloading pandas-0.18.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (8.0MB)
    100% |████████████████████████████████| 8.0MB 105kB/s 
Collecting Flask>=0.10.1 (from bokeh==0.10.0)
Collecting pyzmq>=14.3.1 (from bokeh==0.10.0)
  Downloading pyzmq-15.2.0-cp34-cp34m-macosx_10_6_intel.whl (1.3MB)
    100% |████████████████████████████████| 1.3MB 664kB/s 
Collecting tornado>=4.0.1 (from bokeh==0.10.0)
Collecting MarkupSafe (from Jinja2>=2.7->bokeh==0.10.0)
Collecting pytz>=2011k (from pandas>=0.11.0->bokeh==0.10.0)
  Downloading pytz-2016.3-py2.py3-none-any.whl (479kB)
    100% |████████████████████████████████| 481kB 1.6MB/s 
Collecting itsdangerous>=0.21 (from Flask>=0.10.1->bokeh==0.10.0)
Collecting Werkzeug>=0.7 (from Flask>=0.10.1->bokeh==0.10.0)
  Downloading Werkzeug-0.11.5-py2.py3-none-any.whl (305kB)
    100% |████████████████████████████████| 307kB 1.5MB/s 
Collecting backports-abc>=0.4 (from tornado>=4.0.1->bokeh==0.10.0)
  Using cached backports_abc-0.4-py2.py3-none-any.whl
Building wheels for collected packages: bokeh
  Running setup.py bdist_wheel for bokeh ... done
  Stored in directory: /Users/bryan/Library/Caches/pip/wheels/fc/3d/3d/5eb09b27f109b79db642a4525515fc68a2916e5c5ae0f675b0
Successfully built bokeh
Installing collected packages: six, requests, PyYAML, python-dateutil, MarkupSafe, Jinja2, pytz, pandas, itsdangerous, Werkzeug, Flask, pyzmq, backports-abc, tornado, bokeh
Successfully installed Flask-0.10.1 Jinja2-2.8 MarkupSafe-0.23 PyYAML-3.11 Werkzeug-0.11.5 backports-abc-0.4 bokeh-0.10.0 itsdangerous-0.24 pandas-0.18.0 python-dateutil-2.5.2 pytz-2016.3 pyzmq-15.2.0 requests-2.9.1 six-1.10.0 tornado-4.3
(piptest)bryan@0199-bryanv  /tmp $ ls ~/anaconda/envs/piptest/lib/python3.4/site-packages/bokeh/charts/builder/
__init__.py  __pycache__/  bar_builder.py  boxplot_builder.py  histogram_builder.py  line_builder.py  scatter_builder.py  tests/
(piptest)bryan@0199-bryanv  /tmp $ pip install -U bokeh
Collecting bokeh
  Using cached bokeh-0.11.1.tar.gz
Requirement already up-to-date: six>=1.5.2 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: requests>=1.2.3 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: PyYAML>=3.10 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: python-dateutil>=2.1 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: Jinja2>=2.7 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: numpy>=1.7.1 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: tornado>=4.3 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: MarkupSafe in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from Jinja2>=2.7->bokeh)
Requirement already up-to-date: backports-abc>=0.4 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from tornado>=4.3->bokeh)
Building wheels for collected packages: bokeh
  Running setup.py bdist_wheel for bokeh ... done
  Stored in directory: /Users/bryan/Library/Caches/pip/wheels/7c/53/56/5ee4fa3fa18f08d4ad252f7eba13192fe06e05fc9985c1c36f
Successfully built bokeh
Installing collected packages: bokeh
  Found existing installation: bokeh 0.10.0
    Uninstalling bokeh-0.10.0:
      Successfully uninstalled bokeh-0.10.0
Successfully installed bokeh-0.11.1
(piptest)bryan@0199-bryanv  /tmp $ ls ~/anaconda/envs/piptest/lib/python3.4/site-packages/bokeh/charts/builder/
ls: cannot access /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages/bokeh/charts/builder/: No such file or directory
(piptest)bryan@0199-bryanv  /tmp $ pip install bokeh==0.10.0
Collecting bokeh==0.10.0
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.10.1 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): pandas>=0.11.0 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): six>=1.5.2 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): PyYAML>=3.10 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): python-dateutil>=2.1 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): requests>=1.2.3 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): numpy>=1.7.1 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): pyzmq>=14.3.1 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): tornado>=4.0.1 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.7 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from Flask>=0.10.1->bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from Flask>=0.10.1->bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): pytz>=2011k in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from pandas>=0.11.0->bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): backports-abc>=0.4 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from tornado>=4.0.1->bokeh==0.10.0)
Requirement already satisfied (use --upgrade to upgrade): MarkupSafe in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from Jinja2>=2.7->bokeh==0.10.0)
Installing collected packages: bokeh
  Found existing installation: bokeh 0.11.1
    Uninstalling bokeh-0.11.1:
      Successfully uninstalled bokeh-0.11.1
Successfully installed bokeh-0.10.0
(piptest)bryan@0199-bryanv  /tmp $ ls ~/anaconda/envs/piptest/lib/python3.4/site-packages/bokeh/charts/builder/
__init__.py  __pycache__/  bar_builder.py  boxplot_builder.py  histogram_builder.py  line_builder.py  scatter_builder.py  tests/
(piptest)bryan@0199-bryanv  /tmp $ touch ~/anaconda/envs/piptest/lib/python3.4/site-packages/bokeh/charts/builder/bar_builder.pyc
(piptest)bryan@0199-bryanv  /tmp $ pip install -U bokeh
Collecting bokeh
Requirement already up-to-date: requests>=1.2.3 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: PyYAML>=3.10 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: python-dateutil>=2.1 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: tornado>=4.3 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: numpy>=1.7.1 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: Jinja2>=2.7 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: six>=1.5.2 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from bokeh)
Requirement already up-to-date: backports-abc>=0.4 in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from tornado>=4.3->bokeh)
Requirement already up-to-date: MarkupSafe in /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages (from Jinja2>=2.7->bokeh)
Installing collected packages: bokeh
  Found existing installation: bokeh 0.10.0
    Uninstalling bokeh-0.10.0:
      Successfully uninstalled bokeh-0.10.0
Successfully installed bokeh-0.11.1
(piptest)bryan@0199-bryanv  /tmp $ ls ~/anaconda/envs/piptest/lib/python3.4/site-packages/bokeh/charts/builder/
ls: cannot access /Users/bryan/anaconda/envs/piptest/lib/python3.4/site-packages/bokeh/charts/builder/: No such file or directory
```

**Closed by bryevdv** 2016-04-10 01:07 UTC
Labels: tag: component: build, type: bug

**Comment by linwoodc3** [comment] 2016-04-15 03:16
I got this error today; will try to fix of "clearing all old bokeh" files when i'm back on the job.
