### ISSUE TITLE
box_select not working as active_drag for gridplot

### ISSUE THREAD

**Issue by tony-bony** [bokeh/bokeh#8766] opened 2019-03-18 21:23 UTC
**ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)**

```
Python version      :  2.7.15 (default, Oct  4 2018, 22:42:40) 
IPython version     :  5.8.0
Tornado version     :  4.5.3
Bokeh version       :  1.0.4
BokehJS static path :  /usr/local/lib/python2.7/site-packages/bokeh/server/static
node.js version     :  v10.15.1
npm version         :  6.7.0
```

```
OS: Mac OS X Yosemite 10.10.5
Browser: Google Chrome 72.0.3626.121 (Official Build) (64-bit)
```

**Description of expected behavior and the observed behavior**
The box_select should be the active drag tool in the gridplot's toolbar. Now it looks like always the first drag tool is being active (PanTool in example below)

**Complete, minimal, self-contained example code that reproduces the issue**
```
from bokeh.plotting import figure, show
from bokeh.layouts import gridplot

plots = [figure(active_drag = 'box_select', tools = 'pan,wheel_zoom,box_zoom,reset,tap,crosshair,save,box_select') for i in range(6)]
show(gridplot(children = plots, ncols = 3, merge_tools = True))
```

**Comment by evoulitas** [comment] 2021-03-12 22:28
Hello, is there some information on when this issue will be fixed please?
It seems that `gridplot` is the only way to have merged tools (vs `column` for example), but it is impossible to set the active ones (while in a `column` this is feasible).

**Comment by bryevdv** [comment] 2021-03-12 23:30
@evoulitas Bokeh is a volunteer OSS project and contributors self-direct their own work. If no-one has added it to a milestone then I would not count on it being looked at at any particular time.

**Comment by philippjfr** [comment] 2024-05-07 09:28
@mattpap This would be really nice to have. Part of the problem is that there isn't even a workaround, since merging the tools creates `ToolProxy` objects and the `active_` properties don't allow for `ToolProxy` types. Either we should allow `ToolProxy` objects on the `active_` properties or it should internally check if the `active_<gesture>` refers to one of the tools owned by the `ToolProxy`.

**Closed** 2024-05-30 14:32 UTC
Labels: type: bug, reso: completed, tag: component: bokehjs
