### ISSUE TITLE
image_rgba() does not respect dw_units or dh_units set to screen

### ISSUE THREAD

**Issue by comperem** [bokeh/bokeh#10446] opened 2020-08-30 03:44 UTC
The glyph method `image_rgba()` does not rotate predictably while using screen units. It works fine with default x and y axis units, but not screen units.

When `dw_units` and `dh_units` are set to screen, the image should rotate without translating. But it doesn't. It rotates and translates in an unexpected way, and may even be scaling as well. It's unclear exactly what's happening.

An example with `image_rgba` and rotation is [located on Discourse](https://discourse.bokeh.org/t/bokeh-image-format-standards-and-interoperability/4799/4). This example rotates just fine but does not use screen units. 

Setting `dw_units` and `dh_units` to screen does not produce expected results.

To create this issue, add `dw_units` and `dh_units` to the `image_rgba` call in the example referenced above, like this:
`p.image_rgba(image='image', x='x', y='y', dw='dw', dh='dh', dw_units='screen', dh_units='screen', source=src)`

This issue is for Bokeh 2.1. 

Help. Thanks,
Marc

**Comment by bryevdv** [comment] 2020-09-04 20:51
Hi @comperem you will need to be more specific about what exactly 
>  It rotates and translates in an unexpected way, and may even be scaling as well.

means. Screenshots are advised as well. 

Also, always advised to include a complete reproducer directly in the issue. One, because it makes life easier for maintainers, but also because external links can go stale or disappear (this has happened on numerous occasions) in which case the issue will end up being closed for lack of reproducibility.

**Comment by bryevdv** [comment] 2021-06-10 16:20
Closing for lack staleness / lack of MRE.

**Closed by bryevdv** 2021-06-10 16:20 UTC
Labels: NEEDS MORE INFO, type: discussion
