### ISSUE TITLE
Toolbar wrapper prevents pan/hover on right side of plot

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#5414] opened 2016-10-27 15:59 UTC
The issue tracker isn't the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh).

For defects or deficiencies, please provide:
- Description of expected behavior and the observed behavior
- Self-contained example code that generates the issue (if possible)
- Stack traceback and/or browser developer tools console output
- Software version information output by `bokeh info` command

For desired features, please provide:
- Description of the desired feature

**Comment by bryevdv** [comment] 2016-12-10 20:10
@brendancol this issue does not contain enough information (versions, example code, screenshots, etc.) I believe this is a dupe of #4930 ? If not, please re-open with additional information

**Closed by bryevdv** 2016-12-10 20:10 UTC
