### ISSUE TITLE
Is Ajaxdatasource losing the endpoint?

### ISSUE THREAD

**Issue by Nemecsek** [bokeh/bokeh#7518] opened 2018-02-12 13:29 UTC
I reported this issue in Stackoverflow, because there the code is easier to read: https://stackoverflow.com/questions/48747524/bokeh-0-12-14-flask-broken-library-or-new-syntax-for-ajaxdatasource

I am reading some data using AjaxDataSource.
With Bokeh 0.12.13 it works, while with Bokeh 0.12.14 it doesn't: it looks like the endpoint is lost after the first data refresh. 

The JS error is "`bokeh-0.12.14.min.js:1 undefined http://0.0.0.0:5011/undefined 404 (NOT FOUND)`". 
The endpoint (that works when called from the browser directly) should be instead `http://0.0.0.0:5011/data`.

If it is not a problem for you, I would avoid reposting the same code here.

**Comment by yschroeder** [comment] 2018-02-14 12:27
I am having exactly the same issue. The data from the `AjaxDataSource` is pulled exactly once, afterwards it just regularly tries to get data from `undefined` and the source does not get updated anymore.

**Comment by bryevdv** [comment] 2018-02-19 19:17
cc @clairetang6 this seems due to the selection refactor, running the code in the SO link reports the following in the JS console:

> Error: property AjaxDataSource.selection_policy wasn't declared

**Comment by clairetang6** [comment] 2018-02-26 07:12
@bryevdv, the error you mention above is a problem, which I think can be fixed pretty easily, though I can't reproduce it using master. (The `selection_policy` is defined on and initialized in `ColumnarDataSource` which `AjaxDataSource` should just inherit from) Which version of the code is compiled to create the 0.12.14 cdn build? The 0.12.14 tagged commit was before the selection refactor PR was merged. 

But I think the fundamental problem for this issue might be due to the Typescript conversion. The `AjaxDataSource` has a `get_data` method, which is run through `setInterval`. In the current master after TypeScript conversion, `get_data` is being called with `window` as `this` instead of the instance of the `AjaxDataSource`. I think the coffeescript version uses the => syntax to make it so that the `get_data` method is always called with the correct `this`. @mattpap, what do you think?

**Comment by mattpap** [comment] 2018-02-26 11:10
Yep, the code should be changed to:
```
this.interval = setInterval(() => this.get_data(this.mode, this.max_size, this.if_modified), this.polling_interval)
```
I'm pretty sure this was overlooked, because of using this non-sense vararg version of `setInverval()`.

**Comment by bryevdv** [comment] 2018-02-27 21:41
@clairetang6 my bad, I did not notice the test script loaded Bokeh from CDN explicitly. After updating it to load from `bokeh static` and some other py3 fixes, it works with the change above. I'll push a PR shortly

**Closed** 2018-02-28 16:26 UTC
Labels: tag: component: bokehjs, tag: regression, type: bug
