### ISSUE TITLE
[BUG] Incorrect legend color with different glyphs with same CDS and a CDSView

### ISSUE THREAD

**Issue by thoralf-gutierrez** [bokeh/bokeh#9893] opened 2020-04-07 21:42 UTC
#### Software version info

* python: 3.6.10
* bokeh: 2.0.1
* OS: macOS 10.14.6

#### Description of expected behavior and the observed behavior

I'm plotting circles and segments with different colors from the same CDS. All circles are plotted, but only some segments are plotted, using a CDSView.

I expect the legend to show the correct symbol and color, but one of the colors doesn't match the source.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.plotting import figure
from bokeh.models import CDSView, ColumnDataSource, BooleanFilter
from bokeh.io import show

p = figure()

ds = ColumnDataSource(data={
    'color': ["blue", "red"],
    'x0': [0, 0],
    'y0': [1, 0],
    'x1': [1, 1],
    'y1': [1, 0]
})

# I also tried with an IndexFilter and CustomJSFilter and got the same result
view = CDSView(source=ds, filters=[BooleanFilter([False, True])])

p.circle(
	x='x0', y='y0',
	color='color',
	legend_field='color',
	source=ds)

p.segment(
	x0='x0', y0='y0', x1='x1', y1='y1',
	color='color',
	legend_field='color',
	source=ds,
	view=view)

show(p)
```

#### Stack traceback and/or browser JavaScript console output

No logs in python or the JavaScript console output.

#### Screenshots or screencasts of the bug in action

![image](https://user-images.githubusercontent.com/5640848/78722074-9ae49a80-78dd-11ea-8791-09da0ceb4848.png)

**Comment by bryevdv** [comment] 2020-04-07 21:48
grouped legends do not currently take CDS view into account, they always display based on the full CDS. This is a dupe of #9878

**Closed by bryevdv** 2020-04-07 21:48 UTC
Labels: TRIAGE

**Comment by thoralf-gutierrez** [comment] 2020-04-07 21:54
@bryevdv I don't think this is a dupe: I am not talking about adapting the legend based on what is filtered with the view. Instead, I'm noticing that the legend now had the _wrong_ color. Note the _red_ line across the _blue_ dot in the legend. This is not correct even if the legend is based on the full CDS.

**Comment by bryevdv** [comment] 2020-04-07 23:00
@thoralf-gutierrez on closer inspection, I do still think it is the same underlying issue. The proximate problem is that the legend codepaths draw legends for indices that they should not. In the other case, by sheer coincidence, since there are more than two items, the bad indices are sill at least inside the `all_indices` that the view generates. However, your example is a specific example, with only two total entries in the CDS, is a corner case where the extra indices are out of bounds of the `all_indices` array.  

One fix is to make sure the CDS views inform all parts of the legend codepath, instead of only half of them as it does now, and that is the proposed fix in #9878

**Comment by bryevdv** [comment] 2020-04-07 23:03
I've left a note in the other issue to make sure to validate the above analysis when the other issue is addressed.

**Comment by bryevdv** [comment] 2020-04-08 02:57
And actually looking in to things a bit more closely I think we will be limited in what we can do. Basically all renderers that specify the same `legend_field` are grouped together on the Python side. We can probably make the BokehJS side respect *one* view pretty easily, and that is how I will proceed for the other issue. But it's not even clear what the correct behavior should be when different renderers in the same legend map out to different groups. That's never be defined, and I think making it do anything well-defined would be a rather heavy lift for a rather obscure use case, i.e. not justifiable in terms of time/effort, given other priorities. I think in this situation it would be better to construct a legend manually however you want it using legend items with explicit indices.
