### ISSUE TITLE
Validation goes silent in python, but results in error when rendering in javascript

### ISSUE THREAD

**Issue by monkut** [bokeh/bokeh#3960] opened 2016-02-29 02:14 UTC
I'm attempting to render multiple figures in a vplot.  However, it seems that for some of these figures the necessary data is missing and they don't render properly.  At the moment, this is only known once the plot attempts to render in the browser.

is it possible to perform the validation and raise the exception in python?  As is, it's difficult to debug, 'unsatisfiable constraints.addConstraint', since it's not clear where this is coming from in the python code.

`Uncaught Error: unsatisfiable constraints.addConstraint @ bokeh-0.11.1.min.js:226t.add_constraint @ bokeh-0.11.1.min.js:3e.update_layout @ bokeh-0.11.1.min.js:5e.render @ bokeh-0.11.1.min.js:11o @ bokeh-0.11.1.min.js:3`

This is calling the following to embed code:

`script, div = components(plots_to_render)`

ideally, it would be nice if components threw an exception identifying the issue.

**Comment by bryevdv** [comment] 2016-02-29 02:46
@monkut we use a linear constraint solver to lay out the components on canvas. Unfortunately it is 100% on the JS side, I don't believe there is anything in general we can do on the python side to validate or help. But we might be able to work around possible problem scenarios or at least warn better in the console of we can reproduce your situation. Can you provide a minimal runnable code sample that reproduces the problem?

**Comment by monkut** [comment] 2016-02-29 23:49
I see.  I'll try to dig out an example that will display the issue.

**Comment by monkut** [comment] 2016-03-03 02:10
seems to have been related to setting the figure's *height* to a value too small.

**Comment by xysmas** [comment] 2016-03-19 01:51
@monkut did your figures have

 ```responsive=True``` 
enabled?

**Comment by bryevdv** [comment] 2016-04-10 00:47
@monkut do you have any updates? FYI there is ongoing work to comprehensively improve layout capability will go into `0.12`

**Comment by bryevdv** [comment] 2018-03-16 21:11
dupe of #2676

**Closed by bryevdv** 2018-03-16 21:11 UTC
Labels: type: discussion
