### ISSUE TITLE
Dask compat issues w/ nullable

### ISSUE THREAD

**Issue by pavithraes** [bokeh/bokeh#10935] opened 2021-02-22 20:38 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

bokeh 2.3.0rc2, dask 2021.2.0

#### Stack traceback and/or browser JavaScript console output

<img width="1001" alt="Screenshot 2021-02-23 at 1 56 30 AM" src="https://user-images.githubusercontent.com/33131404/108765881-65d74a00-757a-11eb-9065-852820fba281.png">

**Comment by bryevdv** [comment] 2021-02-22 20:38
I was not able to repro this just now, not sure if there is something else I am missing installed or configured

**Comment by quasiben** [comment] 2021-02-22 20:53
Occurring the scheduler dashboard: https://github.com/dask/distributed/blob/383ea0326ae103b5d5e0b62ed9c3cb18510c5b9e/distributed/dashboard/components/scheduler.py#L867-L874

**Comment by bryevdv** [comment] 2021-02-22 21:04
Dask also sets `Select.value` to None here:

https://github.com/dask/distributed/blob/383ea0326ae103b5d5e0b62ed9c3cb18510c5b9e/distributed/dashboard/components/shared.py#L277

**Comment by mattpap** [comment] 2021-02-22 21:10
Given that this code path creates `Range1d(start=0, end=None)` which was equivalent to `Range1d(start=0, end=1)` pre 2.3, then what's the intent with this? It would make sense if `DataRange1d` was  created instead. In any case, this can be resolved in plotting API, by replacing `None` with `Undefined`.

**Comment by bryevdv** [comment] 2021-02-22 21:10
cc @mattpap we will have to loosen these up to do something reaonable, and make follow-on issues with `distributed` to tighten things up on their end for now.

**Comment by mattpap** [comment] 2021-02-22 21:17
> Dask also sets Select.value to None here:

I'm not sure how that even worked before. It looks like, it should have failed with a `TypeError` at runtime.

**Comment by bryevdv** [comment] 2021-02-22 21:20
> I'm not sure how that even worked before. It looks like, it should have failed with a TypeError at runtime.

it does seem to raise an error on the JS side only, then presumably setting it to a real value later allows it to render. We should do the same for now and make issues to tighten them up later after dask has raised their min bokeh version

@quasiben  was not able to find any other problem areas

**Comment by mattpap** [comment] 2021-02-22 21:46
I tried 2.2.0 and I'm getting:
```
Error rendering Bokeh items: TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))
```
(as expected) with standalone HTML and server. I don't understand how this worked before. Our tests wouldn't catch that anyway. I think I will add `.accepts()` clause and convert `None` to an empty string.

**Comment by bryevdv** [comment] 2021-02-22 22:13
@mattpap note that they also currently set options like
```
["All", None]
```

**Comment by mattpap** [comment] 2021-02-22 23:15
If anyone wonders why this wasn't caught earlier, despite us testing "downstream" projects in CI, then this is the culprit:
```
bokeh                conda-bld/noarch::bokeh-1334255-py_0 --> conda-forge/linux-64::bokeh-2.2.3-py36h5fab9bb_0
```
(in "Install downstream packages" step).

**Comment by bryevdv** [comment] 2021-02-22 23:21
>  this is the culprit

Yikes, that is bad. I thought we errored out on a version check but maybe that's only the unit test jobs. Good catch.

**Comment by bryevdv** [comment] 2021-02-23 02:31
@mattpap There seems to be one other issue, so I imagine we will have to delay a day. During legend rendering  of the task graph, the visual is accessing an out of bounds element (elt 0 of an empty array)

<img width="646" alt="Screen Shot 2021-02-22 at 6 28 48 PM" src="https://user-images.githubusercontent.com/1078448/108795797-ffcbd200-753b-11eb-9181-09f4bc632e27.png">

To repro I ran this:
```
from dask.distributed import Client
Client()
```
Then opened a browser to the listed localhost port and then to the "Graph" tab, e.g. http://localhost:57404/graph

Then:
```
import dask
import dask.dataframe as dd
df = dask.datasets.timeseries()
df2 = df[df.y > 0]
df3 = df2.groupby('name').x.std()
df3
computed_df = df3.compute()
```

**Comment by bryevdv** [comment] 2021-02-23 02:44
This is somewhat intermittent, but seems to happen fairly often on a first render/compute. When it does happen, this is the case:
```
column_source.patch(patches, setter_id);
```
has a patches value of `{state: []}`

So perhaps we just need guard/ignore empty patches

**Comment by bryevdv** [comment] 2021-02-23 03:20
What's weird is that an example that renders a legend for empty data by itself works:
```
from bokeh.plotting import figure, ColumnDataSource, show

source=ColumnDataSource(data=dict(x=[], y=[]))

p = figure()
p.square('x', 'y', size=20, legend="foo", source=source)

show(p)
```
so I am not sure what's different in this code path.

**Comment by bryevdv** [comment] 2021-02-23 03:57
Last few notes, I am not sure what's going on. Seems like a few reloads sometimes gets the task graph back working, but it should be noted that the errors that occur are of this bad kind where the layout goes all wrong, and won't fix w/o reload once they happen:

<img width="255" alt="Screen Shot 2021-02-22 at 7 54 10 PM" src="https://user-images.githubusercontent.com/1078448/108800421-ed579580-7547-11eb-8ba0-0106cc39d214.png">

I'm not so sure about the patch notion above. I am not sure what could result in an empty `FillVector` visual if neither of the two test cases above do.

**Comment by mattpap** [comment] 2021-02-23 12:40
I was able to reproduce this. I will investigate later today.

**Comment by bryevdv** [comment] 2021-02-23 22:20
@mattpap any updates to report? Would definitely be OK with a quick fix now and an issue to revisit

**Closed** 2021-02-24 00:07 UTC
Labels: CRITICAL, reso: completed, type: task
