### ISSUE TITLE
Add example to illustrate label placement

### ISSUE THREAD

**Issue by arossi1** [bokeh/bokeh#5824] opened 2017-01-30 20:56 UTC
This issue is a byproduct from issue #5353 
[Extensions do not render when using bokeh.embed.components / bokeh.embed.file_html APIs]

The motivation for this issue is to include plot axis labels with (rendered) LaTeX labels, derived from the following example:
http://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/latex.html

As mentioned in issue #5353, the placement of the labels is problematic, and I suspect there is a better way to place labels.  Building on the example from issue #5353:
```
p = bokeh.plotting.figure(title="LaTeX Demonstration")

p.line(x, y)

equation = "f = \sum_{n=1}^\infty\\frac{-e^{i\pi}}{2^n}!"

horizLabel = LatexLabel(text=equation,
                        x=0.5, y=0.7, 
                        x_units='data', y_units='data',
                        render_mode='css', text_font_size='6pt',
                        angle=0) 
p.add_layout(horizLabel, "below")

vertLabel = LatexLabel(text=equation,
                       x=-0.3, y=2.0, 
                       x_units='data', y_units='data',
                       render_mode='css', text_font_size='6pt',
                       angle=90, angle_units="deg")
p.add_layout(vertLabel, "left")

l = bokeh.layouts.layout([[p]], sizing_mode='stretch_both')

with open("embedLatexLabelTest-file_html.html","w") as f:
    f.write(bokeh.embed.file_html(l, bokeh.resources.CDN, "Plot with LaTeX label"))
```

The latex labels move when panning the plot - also, the vertical label is too far from the plot and the horizontal label is not displayed, but those are moot points:

![image](https://cloud.githubusercontent.com/assets/11321542/22441037/ba991d5c-e703-11e6-92b5-7a48ac885ccc.png)

So I switched to "screen" units:
```
horizLabel = LatexLabel(text=equation,
                        x=500, y=0, 
                        x_units='screen', y_units='screen',
                        render_mode='css', text_font_size='6pt',
                        angle=0) 
p.add_layout(horizLabel, "below")

vertLabel = LatexLabel(text=equation,
                       x=50, y=500, 
                       x_units='screen', y_units='screen',
                       render_mode='css', text_font_size='6pt',
                       angle=90, angle_units="deg")
p.add_layout(vertLabel, "left")
```
However, now the vertical border / padding makes the label look awkward and the horizontal label is not shown until scrolling down the page:

![image](https://cloud.githubusercontent.com/assets/11321542/22441105/025fea6c-e704-11e6-8a73-b36309bac910.png)

These are extracts from the "real" program generating the plots.  In that case, the data and labels are different, and the output is inconsistent - i.e., some labels look decent, while others are butted up against the axis, while others look like they require more padding (maybe via the `min_border_left/bottom' attribute?).  I can post examples of those if that would be helpful, but I'm hoping this provides enough information.

@bryevdv suggested I add this issue, requesting that an example be added to Bokeh so future users that encounter this type of issue have a reference.

Thanks for your help!

**Comment by StevenCHowell** [comment] 2017-01-31 03:01
@arossi1 What is required to reproduce what you have here?  I reviewed the other thread and downloaded `latexTest.py.txt`.  I put this code into a jupyter notebook and ran it but get the error
```
Javascript error adding output!
Error: Model `LatexLabel' does not exist. This could be due to a widget or a custom model not being registered before first usage.
See your browser Javascript console for more details.
```
Perhaps I am missing something?  Does the LatexLabel code need to be added to the source code before running python and importing bokeh?

Here is the code I ran (I also tried adding `show(p)` but get the same error shown in the `embedLatexLabelTest-components.html`):
```
""" The LaTex example was derived from: http://matplotlib.org/users/usetex.html
"""

import numpy as np

from bokeh.core.properties import Override
from bokeh.models import Label
from bokeh.plotting import figure, show
from bokeh.embed import components, file_html
from bokeh.resources import CDN
from bokeh.resources import INLINE

JS_CODE = """
Label = require "models/annotations/label"

class LatexLabelView extends Label.View
  render: () ->

    #--- Start of copied section from ``Label.render`` implementation

    ctx = @plot_view.canvas_view.ctx

    # Here because AngleSpec does units tranform and label doesn't support specs
    switch @model.angle_units
      when "rad" then angle = -1 * @model.angle
      when "deg" then angle = -1 * @model.angle * Math.PI/180.0

    if @model.x_units == "data"
      vx = @xmapper.map_to_target(@model.x)
    else
      vx = @model.x
    sx = @canvas.vx_to_sx(vx)

    if @model.y_units == "data"
      vy = @ymapper.map_to_target(@model.y)
    else
      vy = @model.y
    sy = @canvas.vy_to_sy(vy)

    if @model.panel?
      panel_offset = @_get_panel_offset()
      sx += panel_offset.x
      sy += panel_offset.y

    #--- End of copied section from ``Label.render`` implementation

    # ``katex`` is loaded into the global window at runtime
    # katex.renderToString returns a html ``span`` element
    latex = katex.renderToString(@model.text, {displayMode: true})

    # Must render as superpositioned div (not on canvas) so that KaTex
    # css can properly style the text
    @_css_text(ctx, latex, sx + @model.x_offset, sy - @model.y_offset, angle)

class LatexLabel extends Label.Model
  type: 'LatexLabel'
  default_view: LatexLabelView

module.exports =
  Model: LatexLabel
  View: LatexLabelView
"""

class LatexLabel(Label):
    """A subclass of the Bokeh built-in `Label` that supports rendering
    LaTex using the KaTex typesetting library.

    Only the render method of LabelView is overloaded to perform the
    text -> latex (via katex) conversion. Note: ``render_mode="canvas``
    isn't supported and certain DOM manipulation happens in the Label
    superclass implementation that requires explicitly setting
    `render_mode='css'`).
    """
    __javascript__ = ["https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"]
    __css__ = ["https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css"]
    __implementation__ = JS_CODE

x = np.arange(0.0, 1.0 + 0.01, 0.01)
y = np.cos(2*2*np.pi*x) + 2

p = figure(title="LaTex Demonstration", width=500, height=500)
p.line(x, y)

# Note: must set ``render_mode="css"``
latex = LatexLabel(text="f = \sum_{n=1}^\infty\\frac{-e^{i\pi}}{2^n}!",
                   x=35, y=445, x_units='screen', y_units='screen',
                   render_mode='css', text_font_size='16pt',
                   background_fill_color='#ffffff')

p.add_layout(latex)




# file_html API
with open("embedLatexLabelTest-file_html.html","w") as f:
    f.write(file_html(p, CDN, "Plot with LaTeX label"))


# components API
script, div = components(p)
with open("embedLatexLabelTest-components.html","w") as f:

    f.write("<!DOCTYPE html>\n")
    f.write('<html>\n') 
    f.write("<head>\n") 
    f.write("<script src='http://cdn.pydata.org/bokeh/release/bokeh-0.12.3.min.js' type='text/javascript'></script>\n")
    f.write('<script type="text/javascript" src="http://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.3.min.js"></script>\n')
    f.write('<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"></script>\n')
    f.write('<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css" type="text/css" />\n')

    for x in INLINE.js_raw:
        if ("LatexLabel" in x):
            f.write('\n<script type="text/javascript">%s</script>\n' % x)
    f.write(script)

    f.write("</head>\n")
    f.write("<body>\n")

    f.write("<h2>Plot:</h2>\n")
    f.write(div)
    f.write("\n")

    f.write("</body>\n")
    f.write("</html>\n") 
 ```

**Comment by arossi1** [comment] 2017-01-31 11:52
Thanks for trying this out, @StevenCHowell.  I've never used Bokeh within a jupyter notebook, so I don't know if there are caveats.  I suggest running directly in Python (via the native interpreter).  Also, make sure you are running the latest script that contains the `bokeh.embed.components` API fix:
https://github.com/bokeh/bokeh/files/739516/latexTest2.py.txt

Thanks again for helping out!

**Comment by arossi1** [comment] 2017-01-31 12:04
Also, for reference, here is the complete script that I referenced in my original post:
[latexLabelPlacement.py.txt](https://github.com/bokeh/bokeh/files/741888/latexLabelPlacement.py.txt)

**Comment by arossi1** [comment] 2017-02-11 15:34
@StevenCHowell, did the example work for you?  If not, I'd be happy to offer more examples to illustrate the troubles I'm having placing custom (LaTeX) labels on the axes.  It seems like it should be relatively straight-forward.  Thanks again for your help.

**Comment by StevenCHowell** [comment] 2017-02-13 20:08
@arossi1 I will be able to return to this later this week.  I will post my results.

**Comment by StevenCHowell** [comment] 2017-02-19 21:03
@arossi1 do you run this in a custom bokeh install?  I tried both my install from git and an install using conda.  

I downloaded the two files you linked, `latexLabelPlacement.py.txt` and `latexTest2.py.txt`, removed the `.txt` extension, then tried running them as scripts.  

For `latexLabelPlacement.py`, I had to add to the imports,
```
import bokeh.plotting
import bokeh.models
```
after which it would run.  Unfortunately, using both my conda install and git install of bokeh the html output looks like this:

<img width="773" alt="screen shot 2017-02-19 at 3 48 42 pm" src="https://cloud.githubusercontent.com/assets/9484229/23106391/ea7b2fbc-f6ba-11e6-9aaf-08c8e4d4429f.png">

This seems strange as `LatexLabel` is defined in the code.  That is why I wondered if I need to install this, or place this code into some other location.

Running `latexTest2.py.txt` had similar results.

**Comment by StevenCHowell** [comment] 2017-02-19 21:07
If I remove the latex labels it runs, plotting the sinusoidal curve.

```
'''
horizLabel = LatexLabel(text=equation,
                        x=500, y=0,
                        x_units='screen', y_units='screen',
                        render_mode='css', text_font_size='6pt',
                        angle=0)
p.add_layout(horizLabel, "below")

vertLabel = LatexLabel(text=equation,
                       x=50, y=500,
                       x_units='screen', y_units='screen',
                       render_mode='css', text_font_size='6pt',
                       angle=90, angle_units="deg")
p.add_layout(vertLabel, "left")
'''
```

**Comment by StevenCHowell** [comment] 2017-02-19 21:14
[This doc page](http://bokeh.pydata.org/en/latest/docs/user_guide/extensions.html) references adding a `LatexLabel` with a link to [this page](http://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/latex.html#userguide-extensions-examples-latex) which demonstrates creating a Latex Label.  I will see if I can get that code running.

**Comment by StevenCHowell** [comment] 2017-02-19 21:26
Maybe this is just something weird about my system, but I can't get the code from the [doc page](http://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/latex.html#userguide-extensions-examples-latex) to run either, though the result looks completely different from the code @arossi1 uploaded (looks like it is mostly the same code with a few lines different at the bottom).  Here is what I get.  Let me know if this is a mistake with an obvious solution.

<img width="507" alt="screen shot 2017-02-19 at 4 23 48 pm" src="https://cloud.githubusercontent.com/assets/9484229/23106753/1c7fcbe4-f6c0-11e6-8dc9-a7708ba8c85a.png">

**Comment by arossi1** [comment] 2017-02-20 18:51
Thanks for taking a look, @StevenCHowell.  I think the previous examples might have been confusing the matter.  Below is a complete example that illustrates the LaTeX label placement issue.  Please let me know if you still have trouble running it.  Thanks again for your help!

```python
# this LaTeX example was derived from: http://matplotlib.org/users/usetex.html

import numpy
import bokeh

JS_CODE = """
Label = require "models/annotations/label"

class LatexLabelView extends Label.View
  render: () ->

    #--- Start of copied section from ``Label.render`` implementation

    ctx = @plot_view.canvas_view.ctx

    # Here because AngleSpec does units tranform and label doesn't support specs
    switch @model.angle_units
      when "rad" then angle = -1 * @model.angle
      when "deg" then angle = -1 * @model.angle * Math.PI/180.0

    if @model.x_units == "data"
      vx = @xmapper.map_to_target(@model.x)
    else
      vx = @model.x
    sx = @canvas.vx_to_sx(vx)

    if @model.y_units == "data"
      vy = @ymapper.map_to_target(@model.y)
    else
      vy = @model.y
    sy = @canvas.vy_to_sy(vy)

    if @model.panel?
      panel_offset = @_get_panel_offset()
      sx += panel_offset.x
      sy += panel_offset.y

    #--- End of copied section from ``Label.render`` implementation

    # ``katex`` is loaded into the global window at runtime
    # katex.renderToString returns a html ``span`` element
    latex = katex.renderToString(@model.text, {displayMode: true})

    # Must render as superpositioned div (not on canvas) so that KaTex
    # css can properly style the text
    @_css_text(ctx, latex, sx + @model.x_offset, sy - @model.y_offset, angle)

class LatexLabel extends Label.Model
  type: 'LatexLabel'
  default_view: LatexLabelView

module.exports =
  Model: LatexLabel
  View: LatexLabelView
"""

class LatexLabel(bokeh.models.Label):
    """A subclass of the Bokeh built-in `Label` that supports rendering
    LaTex using the KaTex typesetting library.

    Only the render method of LabelView is overloaded to perform the
    text -> latex (via katex) conversion. Note: ``render_mode="canvas``
    isn't supported and certain DOM manipulation happens in the Label
    superclass implementation that requires explicitly setting
    `render_mode='css'`).
    """
    __javascript__ = ["https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"]
    __css__ = ["https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css"]
    __implementation__ = JS_CODE


# data to plot
x = numpy.arange(0.0, 1.0 + 0.01, 0.01)
y = numpy.cos(2*2*numpy.pi*x) + 2

# plot data
p = bokeh.plotting.figure(title="LaTex Demonstration")
p.line(x, y)


# test equation used in LaTeX label
equation = "f = \sum_{n=1}^\infty\\frac{-e^{i\pi}}{2^n}!"

# add horizontal LaTeX label
horizLabel = LatexLabel(text=equation,
                        x=500, y=0, 
                        x_units='screen', y_units='screen',
                        render_mode='css', text_font_size='6pt',
                        angle=0) 
p.add_layout(horizLabel, "below")


# add vertical LaTeX label
vertLabel = LatexLabel(text=equation,
                       x=50, y=500, 
                       x_units='screen', y_units='screen',
                       render_mode='css', text_font_size='6pt',
                       angle=90, angle_units="deg")
p.add_layout(vertLabel, "left")


# add plot to layout in order to fill page
l = bokeh.layouts.layout([[p]], sizing_mode='stretch_both')

# write HTML
with open("embedLatexLabelTest.html","w") as f:
    f.write(bokeh.embed.file_html(l, bokeh.resources.CDN, "Plot with LaTeX label"))
```

**Comment by StevenCHowell** [comment] 2017-02-20 20:05
@arossi1 did you read my comments?  I don't think you are because every script you upload gives the same result.

- I cannot run this code without adding the imports `import bokeh.models` and `import bokeh.plotting`
- despite the class definition of `LatexLabel` I keep getting an error that it does not exist because it was not registered.

Please answer these questions:

1. What python environment/installation are you running this from?
2. Did you modify the code, adding definitions, or registering this class definition?
3. Are you running the code from within the bokeh source library?  This would account for you being able to access `bokeh.plotting` and `bokeh.models` without importing them.  Using both the Git install, and the conda install, `import bokeh` does not give access to `bokeh.plotting` or `bokeh.models`.

Try running your code from your root directory, with a fresh conda environment, and bokeh installed via conda.  Something seems different about your system.  If you put that script into your root directory, this is how you would set this up and run it:

```
$> conda create -n py35 python=3.5 numpy bokeh
$> source activate py35
$> conda install -c bokeh nodejs
(py35)$> cd ~/
(py35)$> python test.py
```
If there are some other steps to make it work, tell me what they are because that is what is missing from your explanation.

**Comment by arossi1** [comment] 2017-02-20 20:37
Yes, I read your posts.  I forgot to update my example script to include the missing imports, my apologizes.  However, other than that, I get a working result (see screenshot below source).

To answer your questions:
- environment: anaconda 2.4.0 / Python 2.7.11 (64-bit), bokeh 0.12.3
  - note: it looks like you're using Python3
- I did not make any modifications to the code, I've included it again, below, and ran it from the command line (previously I was running it from Spyder and the imports that I was missing were included from another script)
- I am running the code / script from a working directory (i.e., not the bokeh source directory)


```python
# this LaTeX example was derived from: http://matplotlib.org/users/usetex.html

import numpy
import bokeh, bokeh.models, bokeh.plotting

JS_CODE = """
Label = require "models/annotations/label"

class LatexLabelView extends Label.View
  render: () ->

    #--- Start of copied section from ``Label.render`` implementation

    ctx = @plot_view.canvas_view.ctx

    # Here because AngleSpec does units tranform and label doesn't support specs
    switch @model.angle_units
      when "rad" then angle = -1 * @model.angle
      when "deg" then angle = -1 * @model.angle * Math.PI/180.0

    if @model.x_units == "data"
      vx = @xmapper.map_to_target(@model.x)
    else
      vx = @model.x
    sx = @canvas.vx_to_sx(vx)

    if @model.y_units == "data"
      vy = @ymapper.map_to_target(@model.y)
    else
      vy = @model.y
    sy = @canvas.vy_to_sy(vy)

    if @model.panel?
      panel_offset = @_get_panel_offset()
      sx += panel_offset.x
      sy += panel_offset.y

    #--- End of copied section from ``Label.render`` implementation

    # ``katex`` is loaded into the global window at runtime
    # katex.renderToString returns a html ``span`` element
    latex = katex.renderToString(@model.text, {displayMode: true})

    # Must render as superpositioned div (not on canvas) so that KaTex
    # css can properly style the text
    @_css_text(ctx, latex, sx + @model.x_offset, sy - @model.y_offset, angle)

class LatexLabel extends Label.Model
  type: 'LatexLabel'
  default_view: LatexLabelView

module.exports =
  Model: LatexLabel
  View: LatexLabelView
"""

class LatexLabel(bokeh.models.Label):
    """A subclass of the Bokeh built-in `Label` that supports rendering
    LaTex using the KaTex typesetting library.

    Only the render method of LabelView is overloaded to perform the
    text -> latex (via katex) conversion. Note: ``render_mode="canvas``
    isn't supported and certain DOM manipulation happens in the Label
    superclass implementation that requires explicitly setting
    `render_mode='css'`).
    """
    __javascript__ = ["https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"]
    __css__ = ["https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css"]
    __implementation__ = JS_CODE


# data to plot
x = numpy.arange(0.0, 1.0 + 0.01, 0.01)
y = numpy.cos(2*2*numpy.pi*x) + 2

# plot data
p = bokeh.plotting.figure(title="LaTex Demonstration")
p.line(x, y)


# test equation used in LaTeX label
equation = "f = \sum_{n=1}^\infty\\frac{-e^{i\pi}}{2^n}!"

# add horizontal LaTeX label
horizLabel = LatexLabel(text=equation,
                        x=500, y=0, 
                        x_units='screen', y_units='screen',
                        render_mode='css', text_font_size='6pt',
                        angle=0) 
p.add_layout(horizLabel, "below")


# add vertical LaTeX label
vertLabel = LatexLabel(text=equation,
                       x=50, y=500, 
                       x_units='screen', y_units='screen',
                       render_mode='css', text_font_size='6pt',
                       angle=90, angle_units="deg")
p.add_layout(vertLabel, "left")


# add plot to layout in order to fill page
l = bokeh.layouts.layout([[p]], sizing_mode='stretch_both')

# write HTML
with open("embedLatexLabelTest.html","w") as f:
    f.write(bokeh.embed.file_html(l, bokeh.resources.CDN, "Plot with LaTeX label"))
```

![lltest](https://cloud.githubusercontent.com/assets/11321542/23140942/4949ae7a-f782-11e6-9ff9-92591369417f.png)

**Comment by StevenCHowell** [comment] 2017-02-20 21:28
I'll test this with a python 2.7 environment with bokeh 12.3

**Comment by StevenCHowell** [comment] 2017-02-20 21:44
I created a Python 2.7 environment and it did work with bokeh 12.3, but not with bokeh 12.4 or 12.5dev13.  This was the problem, not the python version.

**Comment by bryevdv** [comment] 2017-02-20 22:13
The code looks to be using the old require and module.exports syntax? The syntax changed in 0.12.4 to accommodate a slow internal migration to typescript. This was mentioned in the migrations notes here:

	http://bokeh.pydata.org/en/latest/docs/releases/0.12.4.html#custom-extension-import-export

Thanks,

Bryan

**Comment by StevenCHowell** [comment] 2017-02-21 03:51
@arossi1 my understanding of this issue is to create an example of placing latex generated labels with the purpose that it will be integrated the included examples.  I noticed a few things in the plot script that I wanted to check if these are an important aspect of the example as they seem to be edge cases, not generally applicable label placement.  Are any of these critical?

1.   adding the layout to fill the page: `l = bokeh.layouts.layout([[p]], sizing_mode='stretch_both')`
2.  outputting an html file using `bokeh.embed.file_html()` rather than `bokeh.plotting.output_file()` or `bokeh.charts.output_file()` (is that required? my initial tests seem to indicate changing to the `output_file()` options do not work)

In my view, these are the key tasks

- [ ] update the code to the current syntax (0.12.4/5), registering the LatexLabel class definition following the [release notes](http://bokeh.pydata.org/en/latest/docs/releases/0.12.4.html#custom-extension-import-export)
- [ ] generalize the example (see above)
- [ ] demonstrate moving the labels (I think this is the original intent of the issue, it would be ideal to automate some of the placement, not sure if this is possible though)
- [ ] test the functionality works in both the notebook and script environments

Am I missing anything?

Also, I noticed that saving the example plot using the save button does not include the latex label in the saved png.  Definitely not ideal.

**Comment by StevenCHowell** [comment] 2017-02-21 03:56
I did see the placement of the labels change for different label content.

**Comment by arossi1** [comment] 2017-02-21 13:06
Thanks, @StevenCHowell.  This is pretty comical - so I updated the example to use the new import/export syntax (and upgraded to bokeh 0.12.4) and now the plot does not render. :)

```python
# this LaTeX example was derived from: http://matplotlib.org/users/usetex.html

import numpy
import bokeh, bokeh.models, bokeh.plotting

JS_CODE = """

import {Label} from "models/annotations/label"

export class LatexLabelView extends Label.View
  render: () ->

    #--- Start of copied section from ``Label.render`` implementation

    ctx = @plot_view.canvas_view.ctx

    # Here because AngleSpec does units tranform and label doesn't support specs
    switch @model.angle_units
      when "rad" then angle = -1 * @model.angle
      when "deg" then angle = -1 * @model.angle * Math.PI/180.0

    if @model.x_units == "data"
      vx = @xmapper.map_to_target(@model.x)
    else
      vx = @model.x
    sx = @canvas.vx_to_sx(vx)

    if @model.y_units == "data"
      vy = @ymapper.map_to_target(@model.y)
    else
      vy = @model.y
    sy = @canvas.vy_to_sy(vy)

    if @model.panel?
      panel_offset = @_get_panel_offset()
      sx += panel_offset.x
      sy += panel_offset.y

    #--- End of copied section from ``Label.render`` implementation

    # ``katex`` is loaded into the global window at runtime
    # katex.renderToString returns a html ``span`` element
    latex = katex.renderToString(@model.text, {displayMode: true})

    # Must render as superpositioned div (not on canvas) so that KaTex
    # css can properly style the text
    @_css_text(ctx, latex, sx + @model.x_offset, sy - @model.y_offset, angle)


export class LatexLabel extends Label.Model
  type: 'LatexLabel'
  default_view: LatexLabelView

"""

class LatexLabel(bokeh.models.Label):
    """A subclass of the Bokeh built-in `Label` that supports rendering
    LaTex using the KaTex typesetting library.

    Only the render method of LabelView is overloaded to perform the
    text -> latex (via katex) conversion. Note: ``render_mode="canvas``
    isn't supported and certain DOM manipulation happens in the Label
    superclass implementation that requires explicitly setting
    `render_mode='css'`).
    """
    __javascript__ = ["https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"]
    __css__ = ["https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css"]
    __implementation__ = JS_CODE


# data to plot
x = numpy.arange(0.0, 1.0 + 0.01, 0.01)
y = numpy.cos(2*2*numpy.pi*x) + 2

# plot data
p = bokeh.plotting.figure(title="LaTeX Demonstration")
p.line(x, y)


# test equation used in LaTeX label
equation = "f = \sum_{n=1}^\infty\\frac{-e^{i\pi}}{2^n}!"

# add horizontal LaTeX label
horizLabel = LatexLabel(text=equation,
                        x=500, y=0, 
                        x_units='screen', y_units='screen',
                        render_mode='css', text_font_size='6pt',
                        angle=0) 
p.add_layout(horizLabel, "below")


# add vertical LaTeX label
vertLabel = LatexLabel(text=equation,
                       x=50, y=500, 
                       x_units='screen', y_units='screen',
                       render_mode='css', text_font_size='6pt',
                       angle=90, angle_units="deg")
p.add_layout(vertLabel, "left")


# add plot to layout in order to fill page
l = bokeh.layouts.layout([[p]], sizing_mode='stretch_both')

# write HTML
with open("embedLatexLabelTest.html","w") as f:
    f.write(bokeh.embed.file_html(l, bokeh.resources.CDN, "Plot with LaTeX label"))

```

Now I'm getting the Bokeh error that you received previously (before I specified my environment):
![image](https://cloud.githubusercontent.com/assets/11321542/23165247/21d0d404-f809-11e6-8f29-5092e0b74e56.png)

However, the LatexLabel JS code appears to be included in the HTML.

To answer your questions:

1. Adding the layout to fill the page isn't critical, but the main point of the HTML that I'm generating is to present data plots, so I'd like to fill as much of the browser as possible.  If adding LaTeX labels means sacrificing some real estate, then that is fine.  Currently, the un-rendered raw LaTeX labels are really an eye sore. :)

2. In my "real" program, I'm outputting the plots using the `bokeh.embed.components` API.  I have a work-around that is still an issue (un)addressed in #5353, but the `bokeh.embed.file_html` seemed to work with version 0.12.3, that's why I'm using it in the example.

The main goal of this issue is to simply add LaTeX labels to plot axes.  I don't necessarily care about placement, as long as they are readable / consistent and don't cause the formatting / layout to change based on label content - btw: I'm glad to see you were able to recreate this issue.   I couldn't find a reliable method to do this leveraging the example in the Bokeh documentation / using custom extensions:
http://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/latex.html#userguide-extensions-examples-latex

...this is why @bryevdv suggested I add this issue.

My main use case is in a scripting environment, but it sounds like you work in a notebook environment, so it would be nice to get this working for both cases.

The fact that the LaTeX labels don't appear in PNG images is not a show-stopper for me - but I agree, this will likely be desired by someone at some point (maybe one of us!).

Thanks again for your help pushing this issue!

**Comment by StevenCHowell** [comment] 2017-02-21 14:07
> I updated the example to use the new import/export syntax (and upgraded to bokeh 0.12.4) and now the plot does not render. :)

Right, the [0.12.4 migration notes](http://bokeh.pydata.org/en/latest/docs/releases/0.12.4.html#custom-extension-import-export) should help us update this, or at least point out what changed.  We will need to go through that.

> Adding the layout to fill the page isn't critical, but the main point of the HTML that I'm generating is to present data plots, so I'd like to fill as much of the browser as possible.

You mentioned not wanting to scroll to see the x-label.  Making the plot smaller is one way to avoid this.  

> If adding LaTeX labels means sacrificing some real estate, then that is fine.

I think one major complication is how the plot is not aware of the label size (though it did seem the plot got more narrow for a wider y-label, I think this needs additional exploration).

> In my "real" program, I'm outputting the plots using the bokeh.embed.components API. I have a work-around that is still an issue (un)addressed in #5353, but the bokeh.embed.file_html seemed to work with version 0.12.3, that's why I'm using it in the example.

In playing with this last night I did not have success using `bokeh.plotting.output_file` syntax.  I think this may be because of the need to embed the html (I am still getting familiar with this).  I would like to see an option that functions with the more simple interface but we have to start somewhere.

> My main use case is in a scripting environment, but it sounds like you work in a notebook environment, so it would be nice to get this working for both cases.

Agreed, both are important.  I find notebooks useful for tinkering, and trying out different things, and prefer scripts once I have settled on what I want for the specific situation.  This is why I turn to notebooks for things like configuring plots, label placement, etc.

**Comment by arossi1** [comment] 2017-02-21 14:24
The migration notes indicate to change the `require` / `module.exports` syntax to the `import` / `export` syntax, which I have done and provided in the example.  This breaks the rendering.  The guide does not mention further modifications (unless I'm missing something).  IMHO: it seems like we should revert to the old syntax to work out the custom label placement.  It will likely work once issues with the new syntax are fixed.

In general, I'm searching for a method to layout a custom label with a plot.  As I mentioned in one of my previous posts, I tried adding `LatexLabel` instances to the layout, but I received an error related to the fact that `LatexLabel` is not a `LayoutDOM item`.

Do you know of a method to add the custom label such that when Bokeh performs the layout / formatting, it is aware of the custom label?  The example seems to place the labels in an absolute position, this causes misalignment and is problematic in the general case.

Thanks for your help.

**Comment by arossi1** [comment] 2017-02-21 14:41
Ok, fair enough.  Thanks again for your help.  Let me know if there is anything else I can do to assist.

**Comment by bryevdv** [comment] 2018-05-10 19:18
Wow, there is alot going on here. I am going to close this issue due to lengthy inactivity, but also because there are some other issues (e.g. #6031) that seem to overlap with  it. I know this is an important topic to a specific class of users, I do hope we can make improvements in this area in time, but resources are spread extremely thin right now.

**Closed by bryevdv** 2018-05-10 19:18 UTC
