### ISSUE TITLE
embed better image and imag_RGBA figures  [FEATURE]

### ISSUE THREAD

**Issue by YoniChechik** [bokeh/bokeh#9141] opened 2019-08-04 07:53 UTC
**Is your feature request related to a problem? Please describe.**
I'm currently working on some computer vision projects that I want to show in jupyter notebooks, and I chose bokeh since it's the most complete interactive solution I could find, but still it seems that images are not really supported fully in bokeh...
by images I mean 2D array plots (e.g.: binary mask) and RGB images.

**Describe the solution you'd like**
some crucial features are missing:
- why is the y axis direction is opposite (down is 0) to all other figure plots (e.g.: matplotlib, matlab).
- why can't I see the image with "tight axis" and equal axis, meaning- show the image in it's original aspect ratio without white borders?
- in rgb_image: why do I have to input the albedo channel- which is not frequently used? 
- in rgba_image: why can I input a 2D gray-scale image easily?
- in rgba_image: why isn't there a good default hover tool?

**Describe alternatives you've considered**
I've implemented a rgb plotting function that deals with the hover tool, flipped y axis, gray-scale input, RGB without A input.
I still cant make the equal tight axis function to work...
the function and test is given below. I hope that it will be good enough for you too help **bokeh get better grip as a default interactive image viewer!** + I hope you'll have a good solution for my axis problem...

**Additional context**

```
def bokeh_imshow(img_orig, **figure_kwargs):
    import numpy as np
    import bokeh
    import bokeh.io
    import bokeh.plotting
    import cv2

    def is_run_from_ipython():
        try:
            __IPYTHON__
            return True
        except NameError:
            return False

    if is_run_from_ipython():
        bokeh.io.output_notebook()
    else:
        bokeh.plotting.output_file("bokeh_imshow_out.html")

    img = img_orig.copy().astype(np.uint8)

    if img.ndim == 2:  # gray input
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGBA)
    elif img.ndim == 3:  # rgb input
        img = cv2.cvtColor(img, cv2.COLOR_RGB2RGBA)

    img = np.flipud(img)

    p = bokeh.plotting.figure(x_range=(0, img.shape[1]), y_range=(
        img.shape[0], 0), **figure_kwargs)
    p.add_tools(bokeh.models.HoverTool(
        tooltips=[
            ("(x, y)", "($x, $y)"),
            ("RGB", "(@R, @G, @B)")]))

    source = bokeh.plotting.ColumnDataSource(data=dict(
        img=[img], x=[0], y=[img.shape[0]],
        dw=[img.shape[1]], dh=[img.shape[0]],
        R=[img[::-1, :, 0]], G=[img[::-1, :, 1]], B=[img[::-1, :, 2]]))
    p.image_rgba(source=source, image='img', x='x', y='y', dw='dw', dh='dh')

    bokeh.plotting.show(p)  # open a browser

# %%


def get_image_from_url(url):
    import os
    import urllib.request
    import cv2

    file_name = os.path.basename(url)
    urllib.request.urlretrieve(url, file_name)
    img = cv2.imread(file_name)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img


rgb_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/AdditiveColor.svg/240px-AdditiveColor.svg.png"
img = get_image_from_url(rgb_url)

bokeh_imshow(img, title="using bokeh as imshow",
             plot_width=700, plot_height=700)

```

**Comment by bryevdv** [comment] 2019-08-04 18:24
> why is the y axis direction is opposite (down is 0) to all other figure plots 

Because the people who made it originally (me) had a more pure-mathematical perspective where the origin is in the LL, than image processing perspective. In hindsight, this was arguably a bad choice, but it's way too late now to change the default, as it would break existing code all over the place. We could consider adding a new configurable flag to change the origin setting (but leave the existing default)


> why can't I see the image with "tight axis" and equal axis, meaning- show the image in it's original aspect ratio without white borders?

You can? However, if you need help with support questions, the proper forum is the Project Discourse, not the issue tracker https://discourse.bokeh.org/

> in rgb_image: why do I have to input the albedo channel- which is not frequently used?

This is certainly dependent on your situation, for others setting the alpha channel is necessary and commonplace. Another reason is that the underlying canvas API in the browser demands and expects RGBA. So the underlying data will always have to be RGBA. Happy to entertain proposals to add convenience functions, etc. to make working with RGB simpler. 

> in rgba_image: why can I input a 2D gray-scale image easily?

Not sure what you are asking. For grayscale on a scalar array I would use `Image` with a gray colormap. 

> in rgba_image: why isn't there a good default hover tool? 

There's not any way to have more than a single default hover tool, which means it there is probably no single default that will work in all situations. We have definitely prioritized the default tool to work will with lines and scatters, etc which are by far more common.

**Comment by bryevdv** [comment] 2019-08-04 18:35
Actually I may have misunderstood the tight axis/equal axis question. But this would be very difficult, I think. A canvas size has to be chosen up front, there is no getting around that.  There are situations were the canvas can be scaled due to constraints from the *outside*, i.e. filling a responsive div or page. But scaling due to something from the *inside*, i.e an image size, is basically going to be impossible. In general, layout has been a nightmare over the years, precisely because all the work is actually done in the browser after every thing leaves python, which means that some things simply cannot be expressed or constrained from the Python side. The situation with MPL is very different, where they control every aspect of the rendering directly, from Python. 

There was recent work to allow controlling the inner frame dimensions. It is *maybe possible* that these could be made "responsive" to an image, but then you are just trading empty space inside the axes for empty space outside the axes. And there are lots of questions. It's easy to state somethign like this for a single image, but the system has to accommodate every arbitrary thing users throw at it. What should the behavior be for two images? or one image plus some other glyphs?

**Comment by YoniChechik** [comment] 2019-08-04 18:51
now it works! adding it here for future interest:
```
# %%


def bokeh_imshow(img_orig,scale=1, **figure_kwargs):
    import numpy as np
    import bokeh.models
    import bokeh.io
    import bokeh.plotting
    import cv2

    def is_run_from_ipython():
        try:
            __IPYTHON__
            return True
        except NameError:
            return False

    if is_run_from_ipython():
        bokeh.io.output_notebook()
    else:
        bokeh.plotting.output_file("bokeh_imshow_out.html")

    img = img_orig.copy().astype(np.uint8)

    if img.ndim == 2:  # gray input
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGBA)
    elif img.ndim == 3:  # rgb input
        img = cv2.cvtColor(img, cv2.COLOR_RGB2RGBA)

    img = np.flipud(img)

    p = bokeh.plotting.figure(
        x_range=(0, img.shape[1]),
        y_range=(img.shape[0], 0),
        # aspect_ratio=img.shape[1]/img.shape[0],
        # aspect_scale = img.shape[1]/img.shape[0],
        frame_width=img.shape[1]*scale,
        frame_height=img.shape[0]*scale,
        # match_aspect = True,
        # sizing_mode="scale_both",
        **figure_kwargs)
    p.add_tools(bokeh.models.HoverTool(
        tooltips=[
            ("(x, y)", "($x, $y)"),
            ("RGB", "(@R, @G, @B)")]))

    source = bokeh.plotting.ColumnDataSource(data=dict(
        img=[img], x=[0], y=[img.shape[0]],
        dw=[img.shape[1]], dh=[img.shape[0]],
        R=[img[::-1, :, 0]], G=[img[::-1, :, 1]], B=[img[::-1, :, 2]]))
    p.image_rgba(source=source, image='img', x='x', y='y', dw='dw', dh='dh')

    bokeh.plotting.show(p)  # open a browser

# %%


def get_image_from_url(url):
    import os
    import urllib.request
    import cv2

    file_name = os.path.basename(url)
    urllib.request.urlretrieve(url, file_name)
    img = cv2.imread(file_name)
    img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    return img


rgb_url = "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c2/AdditiveColor.svg/240px-AdditiveColor.svg.png"
img = get_image_from_url(rgb_url)

bokeh_imshow(img[:, 0:100],scale=3, title="using bokeh as imshow")


```

![image](https://user-images.githubusercontent.com/16686924/62427845-e23cda80-b701-11e9-9f40-6535be32e25f.png)

**Comment by bryevdv** [comment] 2019-08-04 19:05
OK... well if there isn't anything more you want to discuss, I will go ahead and close this. As I mentioned the first ask is a dupe of #1666 and you seem to have figured out supported way to accomplish the other things you want. If you have concrete proposals to add convenience functions to the core library, etc. please don't open new focused issues for them (or PRs)

**Closed by bryevdv** 2019-08-04 19:05 UTC
Labels: type: discussion
