### ISSUE TITLE
API specification `server_session` broken by #7708

### ISSUE THREAD

**Issue by complyue** [bokeh/bokeh#8454] opened 2018-11-22 05:38 UTC
https://github.com/bokeh/bokeh/pull/7708/files#r235605875

_Originally posted by @complyue in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDIzNTYwNTg3NQ==/comments/review_comment_

**Comment by bryevdv** [comment] 2018-11-26 23:47
cc @mattpap AFAICT it's true we are definitely completely discarding `modelid` at this point.

**Comment by bryevdv** [comment] 2019-03-14 23:41
This is actually a duplicate of https://github.com/bokeh/bokeh/issues/8499

**Closed by bryevdv** 2019-03-14 23:41 UTC
Labels: type: discussion
