### ISSUE TITLE
[BUG]Annular Wedge Hovertools Dead Areas

### ISSUE THREAD

**Issue by mhlearn** [bokeh/bokeh#9492] opened 2019-12-02 02:55 UTC
Encountered this several times on the previous version and current version of bokeh 1.4.0, where hovertool does not work on certain areas on annular wedge. Searched through cummunity support, only found this reported once @ https://discourse.bokeh.org/t/bokeh-bug-in-annular-wedge-wedge-hover-tooltip/2813/5 

Below code to replicate the issues

```
import pandas as pd
import numpy as np
from bokeh.plotting import figure
from bokeh.io import show
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.palettes import Category20
from bokeh.transform import cumsum


###->data
data = {"Code": [11,8,4,2,6,1,13,10,5,9],
        "Count": [820,277,272,164,94,67,62,53,17,2],
        "Rate": [0.4486,0.1515,0.1488,0.0897,0.0514,0.0367,0.0339,0.0290,0.0093,0.0011]}

hover_issue_demo_df = pd.DataFrame(data)
hover_issue_demo_df["Colour"] = Category20[len(hover_issue_demo_df["Code"])]
hover_issue_demo_df["cum_s"] = (hover_issue_demo_df["Rate"].cumsum().shift(1).fillna(0))*2*np.pi
hover_issue_demo_df["cum"] = (hover_issue_demo_df["Rate"].cumsum())*2*np.pi

###->CDS source
CDS_hover_issue_demo_df = ColumnDataSource(hover_issue_demo_df)

##->figure
p_hover_issue_demo_df = figure(plot_width=400, plot_height=400, title="Demo", x_range=(-0.5, 0.5), y_range=(-1, 1))

p_hover_issue_demo_df.annular_wedge(x=0, y=0, 
                                    inner_radius=0.2, outer_radius=0.35,
                                    source=CDS_hover_issue_demo_df,
                                    start_angle="cum_s", end_angle="cum", 
                                    color="Colour"
                                    )

###->add hovertool
hover = HoverTool(tooltips=[("Count", "@Count{0,0}"), ("Percentage", "@Rate{0.0000%}")], mode="mouse", point_policy="follow_mouse")
p_hover_issue_demo_df.add_tools(hover)

show(p_hover_issue_demo_df)

```
sample output where dead spots are. 

![bokeh_plot_hover issue](https://user-images.githubusercontent.com/31059584/69927126-fcd96180-14f1-11ea-83e9-c5c92c3e9ea9.jpg)

**Comment by bryevdv** [comment] 2019-12-02 02:58
Thanks for the report @mhlearn

**Comment by anthonydouc** [comment] 2019-12-06 12:30
As far as I can tell this is caused by the bounding box being checked at [https://github.com/bokeh/bokeh/blob/aa3c87499f2d822e4258d56d7d0e95db5e8dc6eb/bokehjs/src/lib/models/glyphs/annular_wedge.ts#L111](url). The indices of every annular wedge is

**Comment by mhlearn** [comment] 2019-12-09 03:24
re-checked. it is true when it has equal space, x-range and y-range, the problem does not occur. thanks for pointing out.

**Comment by anthonydouc** [comment] 2019-12-09 05:06
@bryevdv does that suggest there is an error in drawing annular wedge (And potentially some other glyphs?). I would of thought the radius should be determined irrespective of the plot x-range and y-range if its units are in "data-space". Happy to work on a PR to fix as well.

**Comment by bryevdv** [comment] 2019-12-09 05:19
@anthonydouc What I would say is that drawing an annular wed without `match_aspect=True` is not really a meaningful thing to do. Canvas will always draw a circular arc, full stop. So if the aspect is not 1-1 then the result is not very useful.

**Comment by anthonydouc** [comment] 2019-12-09 06:19
@bryevdv, Yes I agree the only solution is to squish the circular glyphs and that it is not worth it. 
Although a few users have obviously encountered this issue - perhaps without realising the implications of their specified x-range/y-range. I would support closing, and perhaps if more people come across this issue a warning could be included.

**Closed** 2020-01-09 03:44 UTC
Labels: tag: component: bokehjs, type: bug

**Comment by mmcguffi** [comment] 2020-02-16 05:24
I know this is closed, but I do not understand some of the technical explanation of why this does not work as mentioned by @anthonydouc and @bryevdv above. This bug essentially kills my project (interactive circular DNA visualization). Is there any possible workaround? Thank you!

**Comment by anthonydouc** [comment] 2020-02-16 12:41
> I know this is closed, but I do not understand some of the technical explanation of why this does not work as mentioned by @anthonydouc and @bryevdv above. This bug essentially kills my project (interactive circular DNA visualization). Is there any possible workaround? Thank you!

Assuming nothing has changed, when I last checked the issue encountered above only occurs when the `x_range` and `y_range` of the chart were not equal. This causes an issue in the implemented hit test algorithm, so it does not correctly identify when someone hovers over the glyph. So from what I can tell, the only two workarounds are:

- Set the x_range equal to the y_range, or

- Remove the initial part of the hit test algorithm which I believe is leading to the issue occuring (which was what I wrote in my last comment).

**Comment by mmcguffi** [comment] 2020-02-16 16:59
> * Set the x_range equal to the y_range, or

I just need a square plotting area, so that works for me. I changed `x_range=(-.5, .5)` to `x_range=(-.5, .5),y_range=(-.5, .5)` and it worked like a charm. Thank you so much!

**Comment by bryevdv** [comment] 2020-02-16 17:12
More specifically, as with *any* circle-ish glyph, you probably always want to set `match_aspect=True` when you create a `figure`.

**Comment by mmcguffi** [comment] 2020-02-16 22:31
This appeared to have worked, except now I have an area of pi/6 radians (I think) to the left of the top that are not responsive. I don't have a minimal reproducible example at the moment, but here is the area that is not responsive:
<img width="684" alt="Screen Shot 2020-02-16 at 4 26 00 PM" src="https://user-images.githubusercontent.com/17573404/74614011-848a4180-50d9-11ea-98b7-08c62b71fcee.png">
I have `x_range=(-.5, .5),y_range=(-.5, .5)` as well as `match_aspect=True` -- any insights into this (apparent) bug?

**Comment by bryevdv** [comment] 2020-02-16 23:24
@mmcguffi unfortunately not, this would definitely require a reproducer so that we can put breakpoints in the JS and do real debugging. As soon as you have one, please open a new issue.

**Comment by mmcguffi** [comment] 2020-02-17 00:49
In trying to create a minimal example I discovered the cause! A non-visible legend that was occluding the hover space.
<img width="622" alt="Screen Shot 2020-02-16 at 6 48 05 PM" src="https://user-images.githubusercontent.com/17573404/74616370-fae46f00-50ec-11ea-8488-6e2d8f0b823d.png">
Sorry to bother you with this, and thank you for making such a wonder visualization library!

**Comment by bryevdv** [comment] 2020-02-17 00:59
Thanks for the kind words, glad you got it figured out!

**Comment by mhlearn** [comment] 2020-02-17 06:38
> 
> 
> In trying to create a minimal example I discovered the cause! A non-visible legend that was occluding the hover space.
> 
> <img alt="Screen Shot 2020-02-16 at 6 54 03 PM" width="625" src="https://user-images.githubusercontent.com/17573404/74616501-bc9b7f80-50ed-11ea-9ba0-730a2e2e1e5f.png">
> 
> Sorry to bother you with this, and thank you for making such a wonder visualization library!

as mentioned in here too, https://discourse.bokeh.org/t/bokeh-bug-in-annular-wedge-wedge-hover-tooltip/2813/5 , non-visible legend can be the cause. other then set legend.visible=False, also the rest of following to avoid hovertool not display properly, 

legend.glyph_height = 0
legend.glyph_width = 0
legend.label_height = 0
