### ISSUE TITLE
Add active_drag, active_scroll and active_tap for Grid plots

### ISSUE THREAD

**Issue by schlichtanders** [bokeh/bokeh#5356] opened 2016-10-15 09:10 UTC
Just tried the GridPlot functionality with its impressive extra feature to merge Toolbars. Thanks for building this.
It seems the three active makers which are available for a `Toolbar` are not yet implemented on a `ToolbarBox` (in my case they were forgotten after merge).

I am not in depth with the code, however from at least one perspective it seems weird that there is at all a difference between `ToolbarBox` and `Toolbar`. Looking at the python code in [`bokeh.models.tools`](https://github.com/bokeh/bokeh/blob/master/bokeh/models/tools.py#L136) the only added attribute is `merge_tools`, which however seems to be a static indicator not needed in the class itself but only for construction so that indeed a `Toolbar` might be used instead of a `ToolbarBox`. Please correct me here.

In the end, it would be great to have `active_drag`, `active_scroll` and `active_tap` for ToolbarBox, too. An enhanced constructor would also be great which merges the active markers from the single Toolbars.

**Comment by birdsarah** [comment] 2016-10-17 04:31
Agreed, this would be a good feature.

**Comment by birdsarah** [comment] 2016-10-17 19:58
Sorry, I just realized @schlichtanders, isn't it possible to pass these in the toolbar_options dict that's an option to gridplot?

http://bokeh.pydata.org/en/latest/docs/reference/layouts.html#bokeh.layouts.gridplot

**Comment by schlichtanders** [comment] 2016-10-17 20:30
Tried that, doesn't work to my knowledge
But good idea

**Comment by birdsarah** [comment] 2016-10-17 21:00
OK. That should have worked, it was my intention when I made `ToolbarBox` but the active tools were added later and this use case didn't crop up. 

Here's working code to demonstrate the problem.

```python
import numpy as np

from bokeh.plotting import figure, gridplot, output_file, show

N = 50

x = np.linspace(0, 4*np.pi, N)
y = np.sin(x)

TOOLS = "pan,wheel_zoom,box_zoom,reset,save,crosshair"

l = figure(title="line", tools=TOOLS, plot_width=300, plot_height=300)
l.line(x,y, line_width=3, color="gold")

aw = figure(title="annular wedge", tools=TOOLS, plot_width=300, plot_height=300)
aw.annular_wedge(x, y, 10, 20, 0.6, 4.1, color="navy", alpha=0.5,
    inner_radius_units="screen", outer_radius_units="screen")

bez = figure(title="bezier", tools=TOOLS, plot_width=300, plot_height=300)
bez.bezier(x, y, x+0.4, y, x+0.1, y+0.2, x-0.1, y-0.2,
    line_width=2, color="olive")

q = figure(title="quad", tools=TOOLS, plot_width=300, plot_height=300)
q.quad(x, x-0.2, y, y-0.2, color="tomato", alpha=0.4)

# specify "empty" grid cells with None
p = gridplot([[l, None, aw], [bez, q, None]], toolbar_options=dict(active_drag='pan'))
import ipdb; ipdb.set_trace()

output_file("grid.html", title="grid.py example")

show(p)
```

Unfortunately it may not be an easy fix. The ToolbarBox needs to have these attributes added to it and they need to be handled correctly BokehJS side.

**Comment by birdsarah** [comment] 2016-10-17 21:04
I'm marking this as a bug @bryevdv, feel free to disagree.

**Comment by bryevdv** [comment] 2018-04-10 22:48
this seems to be a dupe of #4568

**Closed by bryevdv** 2018-04-10 22:48 UTC
Labels: type: bug
