### ISSUE TITLE
LassoTool Performance

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6050] opened 2017-03-23 15:19 UTC
1) Performance is bad on Chrome 57 and Firefox 52 (OS-X) (Performance seems fine on Safair). Lasso-ing causes heavy stuttering of the cursor

2) The lasso behavior has changed. While multiselect works, holding the SHIFT key causes a lasso to not unselect double-lassoed areas.

Here's an example of a double-lassoed area becoming unselected (see the internal unselected bands). This doesn't happen when SHIFT is held:

<img width="1440" alt="screen shot 2017-03-23 at 12 18 18 pm" src="https://cloud.githubusercontent.com/assets/2198981/24254910/d196a6f4-0fc2-11e7-8040-b0a64ff2b335.png">

**Comment by bryevdv** [comment] 2017-03-23 15:30
I could live with a shift select regression temporarily as a known issue, as I am not sure it's a common operation. Able to get any profiling info on the per regression tho?

**Comment by bryevdv** [comment] 2017-05-05 01:39
It's possible (speculation) that #4967 is related to (or would improve) performance

**Comment by bryevdv** [comment] 2017-06-04 19:59
The performance issue seems related calling `stroke` so many time:

<img width="1021" alt="screen shot 2017-06-04 at 14 22 55" src="https://cloud.githubusercontent.com/assets/1078448/26764891/e4ef6932-4935-11e7-8174-1338c8008f9c.png">

This seems to be borne out y the fact that if you set `nonselection_line_color=None` then the performance dramatically improves on chrome. (the regular circles already have no line color)

It seems others have this issue as well:

https://stackoverflow.com/questions/12254415/canvas-arc-vs-drawimage
https://stackoverflow.com/questions/13916066/speed-up-the-drawing-of-many-points-on-a-html5-canvas-element

**Comment by bryevdv** [comment] 2017-06-04 20:14
I think this issue should be split:

* the drawing performance issue (which has nothing to do with the lasso tool AFAICT)
* shift-selection behavior of lasso tool

In any case, moving to to next milestone

**Comment by bryevdv** [comment] 2019-11-10 05:44
Looking at the behaviour of the lasso tool wrt SHIFT and loops,  it does what  I expect, so not going to worry about that. Performance also seems marginally acceptable on Chrome at this point but will leave this open to see if there are any quick wins.

**Comment by bryevdv** [comment] 2020-02-05 04:55
Just noting that there is still fairly bad lag on Chrome on a 16" MBP for e.g. 

https://docs.bokeh.org/en/1.4.0/docs/gallery/color_scatter.html

**Comment by bryevdv** [comment] 2020-08-25 03:44
As of 2.2 shift now does what I'd expect, and performance is also better. I will close this now.

**Closed by bryevdv** 2020-08-25 03:44 UTC
Labels: tag: component: bokehjs, type: bug
