### ISSUE TITLE
[BUG] When I clicked the legend, the legend hid in bokeh 3.1.1 . But in bokhe 3.0.1, the code behave expectedly

### ISSUE THREAD

**Issue by yuji38kwmt** [bokeh/bokeh#13133] opened 2023-05-17 07:19 UTC
### Software versions

Python version      :  3.11.2 (main, Mar  2 2023, 15:11:26) [GCC 11.3.0]
IPython version     :  8.11.0
Tornado version     :  6.2
Bokeh version       :  3.1.1
BokehJS static path :  /home/vagrant/.pyenv/versions/3.11.2/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v16.20.0
npm version         :  9.5.1
Operating system    :  Linux-5.15.0-70-generic-x86_64-with-glibc2.35

### Browser name and version

Firefox 113.0.1 (64 ビット)

### Expected behavior

When I click "Japan" in the legend, "alice" and "bob" hide.

### Observed behavior

When I clicked "Japan" in the legend, all text hid and legend hid.

In browser console, the following error occurred.

```
Uncaught (in promise) TypeError: p is undefined
```

### Example code

```Python
from bokeh.plotting import figure, output_file, save


from bokeh.models import ColumnDataSource
import pandas

df = pandas.DataFrame(
    {
        "x": [1, 2, 2.1],
        "y": [1, 4, 5.4],
        "name": ["alice", "bob", "charlie"],
        "category": ["Japan", "Japan", "U.S."],
    }
)
fig = figure()

categories = ["Japan", "U.S."]
colors = {"Japan":"red", "U.S.":"blue"}

for category in categories:
    df_category = df[df["category"] == category]
    source = ColumnDataSource(df_category)
    fig.text(
        source=source,
        x="x",
        y="y",
        text="name",
        legend_label=category,
        color=colors[category],
        #    muted_alpha=0.2,
    )
    fig.legend.location = "top_left"
    fig.legend.click_policy = "mute"

output_file("sample.html")
save(fig)
```

### Stack traceback or browser console output

In bokeh 3.0.3, the above code behaved expectedly.

### Screenshots

[result.zip](https://github.com/bokeh/bokeh/files/11495230/result.zip)

**Comment by mattpap** [comment] 2023-05-17 10:00
@yuji38kwmt, can you try this with 3.2.0.dev2?

**Comment by yuji38kwmt** [comment] 2023-05-17 10:16
This problem also occurred in bokeh 3.2.0.dev2.

**Comment by mattpap** [comment] 2023-05-17 10:29
I wasn't able to reproduce this in 3.2.0.dev2. Let's make sure this is not a caching issue. Can you verify that if you type `Bokeh.version` in JS console, you get:
![image](https://github.com/bokeh/bokeh/assets/27475/fbf5b17d-9c7c-42d3-b0f2-c153eea80416)

Also, it's generally useful to make sure caching is disabled when devtools is open. In this case in Firefox:
![image](https://github.com/bokeh/bokeh/assets/27475/d0c4d30a-51fa-4b91-8900-9f5d1e28da5c)
(second option from the top).

**Comment by yuji38kwmt** [comment] 2023-05-17 21:55
I made sure that bokes's version is "3.2.0-dev.2" in browser console.

![image](https://github.com/bokeh/bokeh/assets/6350027/6f887ae4-127b-41f1-88d9-818404b65cb6)

I captured a video.
![bokeh-legend-clicked](https://github.com/bokeh/bokeh/assets/6350027/e363bac8-e141-4bdb-8c8a-b3966ec1d810)



[sample_bokeh3.2.0.dev.zip](https://github.com/bokeh/bokeh/files/11502754/sample_bokeh3.2.0.dev.zip)

**Comment by bryevdv** [comment] 2023-05-17 22:17
@yuji38kwmt please copy and paste the full JS console error *as text*, so that can be examined in its entirety. It is impossible to glean anything from that animated image. Additionally, setting the env var `BOKEH_MINIFIED=no` should provide better console information.

**Comment by yuji38kwmt** [comment] 2023-05-18 03:48
@bryevdv OK. I copied console error.

```
[bokeh] setting log level to: 'info' bokeh-3.2.0.dev2.js:3729:21
[bokeh] document idle at 128 ms bokeh-3.2.0.dev2.js:773:34
ソースマップエラー: Error: request failed with status 403
リソース URL: https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js
ソースマップ URL: bokeh.js.map 2
Uncaught (in promise) TypeError: swidth is undefined
    _render https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:40663
    render https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:22980
    _render https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:22575
    render https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:9947
    _paint_levels https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:44823
    _actual_paint https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:44795
    paint https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:44735
    repaint https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:44728
    throttled_paint https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:44274
    later https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:44928
    fn https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:44942
    fn https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:44920
    schedule_paint https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:44229
    request_paint https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:44215
    request_paint https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:9919
    request_render https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:9916
    render https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:22388
    new_slot https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:7734
    emit https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:2736
    emit https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:2745
    _setv https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:2506
    setv https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:2533
    set https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:2254
    fn https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:27748
    on_hit https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:27756
    __trigger https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33363
    _trigger https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33240
    _tap https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33526
    _configure_hammerjs https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33012
    emit https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:35765
    emit https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:35423
    tryEmit https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:34908
    _timer https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:35403
    boundFn https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33734
    setTimeout handler*setTimeoutContext https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33586
    process https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:35401
    recognize https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:34945
    recognize https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:35632
    inputHandler https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:34029
    PEhandler https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:34359
    domHandler https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33952
    addEventListeners https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33767
    each https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33616
    addEventListeners https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33766
    init https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33969
    Input https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:33955
    PointerEventInput https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:34326
    createInputInstance https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:34004
    Manager https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:35558
    Hammer https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:35436
    UIEventBus https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:32975
    initialize https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:32735
    _build_view https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:8850
    build_view https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:8855
    lazy_initialize https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:44291
    _build_view https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:8851
    build_view https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:8855
    render_view https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:7682
    render_model https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:7693
    add_document_standalone https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:7706
    _embed_items https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:666
    embed_items https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:651
    embed_document file:///home/vagrant/Documents/study/20230515/sample_bokeh3.2.0.dev.html:33
    fn file:///home/vagrant/Documents/study/20230515/sample_bokeh3.2.0.dev.html:36
    fn file:///home/vagrant/Documents/study/20230515/sample_bokeh3.2.0.dev.html:52
    safely https://cdn.bokeh.org/bokeh/dev/bokeh-3.2.0.dev2.js:9682
    fn file:///home/vagrant/Documents/study/20230515/sample_bokeh3.2.0.dev.html:28
    EventListener.handleEvent* file:///home/vagrant/Documents/study/20230515/sample_bokeh3.2.0.dev.html:56
    <anonymous> file:///home/vagrant/Documents/study/20230515/sample_bokeh3.2.0.dev.html:57
bokeh-3.2.0.dev2.js:40663:34
```



`bokeh-3.2.0.dev2.js:40663` 

```
        _render(ctx, indices, data) {
            const { sx, sy, x_offset, y_offset, angle, labels } = data !== null && data !== void 0 ? data : this;
            const { text, background_fill, background_hatch, border_line } = this.visuals;
            const { anchor_: anchor, border_radius, padding } = this;
            const { swidth, sheight } = this;
            for (const i of indices) {
                const sx_i = sx[i] + x_offset.get(i);
                const sy_i = sy[i] + y_offset.get(i);
                const angle_i = angle.get(i);
                const label_i = labels[i];
                if (!isFinite(sx_i + sy_i + angle_i) || label_i == null)
                    continue;
                const swidth_i = swidth[i];
```

**Comment by mattpap** [comment] 2023-05-18 08:41
Now with full context it's clear this is a duplicate of https://github.com/bokeh/bokeh/issues/13112, which was fixed recently, but after dev2. I will publish dev3 later today.

**Closed as completed by mattpap** 2023-05-18 08:41 UTC
Labels: reso: duplicate, type: discussion
