### ISSUE TITLE
When using IPython, calling multiple charts ends up generating unused widgets into the HTML file, rendering them invalid

### ISSUE THREAD

**Issue by mrslezak** [bokeh/bokeh#4260] opened 2016-05-01 23:01 UTC
The issue tracker isn't the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh).

For defects or deficiencies, please provide:
- Description of expected behavior and the observed behavior
- Self-contained example code that generates the issue (if possible)
- Stack traceback and/or browser developer tools console output
- Software version information output by `bokeh info` command

For desired features, please provide:
- Description of the desired feature

**Comment by mrslezak** [comment] 2016-05-01 23:08
https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.11.1.min.css
https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.11.1.min.js

Both should be inserted into the HTML by bokeh when widgets are selected in the graph code.

**Comment by bryevdv** [comment] 2016-05-02 00:43
Can you provide a runnable example code to reproduce the problem? I have not observed the widgets files missing when they should be present, so more information is needed.

**Comment by bryevdv** [comment] 2016-05-02 10:51
Marking as `discussion` for now, pending more information from @mrslezak

**Comment by bryevdv** [comment] 2016-05-02 10:53
As an example, just running `examples/plotting/slider.py` right now works as expected. Please let us know exactly what you were trying to do.

**Comment by mrslezak** [comment] 2016-05-02 15:00
bokeh.pydata.org/en/0.11.1/docs/gallery/candlestick.HTML produces an error:
Uncaught error: Module 'Slider' does not exists.  The problem may be two
fold.  Either a model was requested that's available in an extra bundle,
e.g. a widget, or a custom model was requested, but it wasn't registered
before first usage.
On May 2, 2016 5:53 AM, "Bryan Van de Ven" <notifications@github.com> wrote:

As an example, just running examples/plotting/slider.py right now works as
expected. Please let us know exactly what you were trying to do.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/bokeh/bokeh/issues/4260#issuecomment-216197835>

**Comment by bryevdv** [comment] 2016-05-02 15:27
@mrslezak I'm still not clear. When I navigate to that page I see the example just fine. Are you saying you are trying to copy and paste that code, and run it locally? Are yo trying to add to/modify the code as well? If so we need version information (Bokeh, OS, browser, etc.) as well as the code you are actually running to try and reproduce what you are seeing. It is impossible investigate without all the details, and code to reproduce.

**Comment by mrslezak** [comment] 2016-05-02 16:07
I am copying and pasting the example into Python 3.5 and running locally using Chrome  49.0.2623.112 m as the web browser.  I am not changing the code in any way.  I also can see the example on the bokeh webpage but not when I actually run the code - in Developer Tools in Chrome the error reported is what I posted above.

**Comment by bryevdv** [comment] 2016-05-02 16:37
OK, thanks that is much more specific. I am about to look into some other notebook related issues so I will make a point to check out this example in that (and other) versions of the notebook as well.

**Comment by mrslezak** [comment] 2016-05-02 16:40
Thanks - I compared the 2 generated HTML files and there is not anything
obvious as to why 1 works and the other does not... If there is a way to
upload here I can save you some time.

**Comment by bryevdv** [comment] 2016-05-02 16:41
maybe a gist would be easiest for you: https://gist.github.com

**Comment by mrslezak** [comment] 2016-05-02 16:54
https://gist.github.com/mrslezak/b8d27f4f3d604ac7d6630e73def0fa34

Very odd, both work in Internet Explorer.  Going to upgrade my Chrome to see if it is Chrome specific.

**Comment by mrslezak** [comment] 2016-05-02 16:57
Yes that was it, Chrome bug, closing this issue.

**Comment by mrslezak** [comment] 2016-05-02 20:11
I dug into this deeper - it seems that using IPython other bokeh parameters selected on other charts end up making their way into the current plot's HTML file.  So the above error is coming from a Slider which was used in the power example on the bokeh website.  Is there a way to ensure the bokeh parameters are reset between charts in IPython???

**Comment by bryevdv** [comment] 2016-05-03 15:24
@mrslezak OK that is also interesting, I'm having a little trouble imagining the exact sequence of steps I might take to reproduce this, so if you can spell those out that would be extremely helpful. I have travel and conferences most of the rest of this week but will try to take a closer look soon.

**Comment by bryevdv** [comment] 2016-05-03 15:25
Though, if I can guess, a call to `bokeh.io.reset_output()` might solve your immediate problem. Verifying that would also be useful.

**Comment by mrslezak** [comment] 2016-05-03 15:39
Thanks for that tip to reset output.

To reproduce just run the examples in the order I listed and see if your
HTML opens and displays anything in a webbrowser.  Could just be an IPython
shell bug.
On May 3, 2016 10:25 AM, "Bryan Van de Ven" <notifications@github.com>
wrote:

Though, if I can guess, a call to bokeh.io.reset_output() might solve your
immediate problem. Verifying that would also be useful.

—
You are receiving this because you were mentioned.
Reply to this email directly or view it on GitHub
<https://github.com/bokeh/bokeh/issues/4260#issuecomment-216563982>

**Comment by bryevdv** [comment] 2016-05-03 15:42
> Could just be an IPython shell bug.

Doubtful. I'm guessing this is because there is an implicit notion of a "current document". This sometimes makes things simpler/easier for users, but can also have the opposite effect in other cases. It's possible there is some way to improve things in this situation, though.

**Comment by bryevdv** [comment] 2017-10-10 23:33
This discussion is stale. In retrospect I think this is just one of the cases where `reset_output` is unavoidable.

**Closed by bryevdv** 2017-10-10 23:33 UTC
Labels: type: discussion
