### ISSUE TITLE
Javascript error "cannot find stylesheet" when using DataTable

### ISSUE THREAD

**Issue by dennisobrien** [bokeh/bokeh#2914] opened 2015-09-26 05:45 UTC
I have a flask app that is embedding a Bokeh visualization.  About once every five page loads I get a Javascript error:

```
Uncaught Error: Cannot find stylesheet.
```

I think this is an issue with slickgrid and how I am loading the css and javascript.

The stack trace looks like this:
- getColumnCssRules
- applyColumnWidths
- updateCanvasWidth
- autosizeColumns
- resizeCanvas
- finishInitialization
- init
- SlickGrid
- a.261.e.render
- (anonymous function)
- (anonymous function)

There is a SlickGrid issue that seems related, but it has been closed for a while.
https://github.com/mleibman/SlickGrid/issues/223

Anyone else seeing this problem?  Maybe it's the order of loading the css and javascript, and my particular mix of some from CDN, some from templates.

thanks,
Dennis

**Comment by dennisobrien** [comment] 2015-09-28 23:52
One more data point:

This project had a similar issue with SlickGrid.  The fix for this project was to move SlickGrid initialization from document.ready to window.load.
https://github.com/okfn/dataexplorer/issues/41

**Comment by dennisobrien** [comment] 2015-10-02 02:16
I've made several changes in my app in the last few days and this problem seems to have gone away.  Unfortunately I have not been very scientific about it, so I can't point to a single fix or culprit.

Some of the changes:
- Use JS and CSS built from a fork of 0.10.0.
- Moved the order of some JS and CSS loading.
- Updated Chrome.

Unless anyone else is having this same problem, this issue can be closed.  If I find this again, I'll try to make a one off app example to reproduce the problem and re-open this issue with better steps to reproduce.

thanks,
Dennis

**Comment by dennisobrien** [comment] 2015-10-02 03:48
This bug can actually be seen sometimes by loading the Bokeh documentation page!  

Load the page and go to the DataTable section and notice that the table sometimes does not render, with a error in the console "Uncaught Error: Cannot find stylesheet."

http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html#data-table

**Comment by bryevdv** [comment] 2016-04-10 01:54
@dennisobrien any comment as to whether this issue has persisted ?

**Comment by bryevdv** [comment] 2017-05-12 01:54
I just reloaded the docs page 

http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/widgets.html#data-table

about 50 times and could not reproduce any issue. I've also never seen it in the last ~18 months. Closing, please re-open if a reproducible example can be found.

**Closed by bryevdv** 2017-05-12 01:54 UTC
Labels: type: bug
