### ISSUE TITLE
Arbitraty JS at the beginning of each session

### ISSUE THREAD

**Issue by ImmanuelSamuel** [bokeh/bokeh#5195] opened 2016-09-20 01:34 UTC
I am trying to run JS code at the beginning of a bokeh serve session and return some values to the python side which I will use later to update the plot data. Currently I am not able to see any documentation to achieve this.

I tried the following to no avail. Is there a way to do this?
```
from random import random
import numpy as np

from bokeh.layouts import column, row, widgetbox, layout
from bokeh.models import Button
from bokeh.palettes import RdYlBu3
from bokeh.plotting import figure, curdoc
from bokeh.models.widgets import MultiSelect, Dropdown, Select, TextInput, PreText
from bokeh.models import ColumnDataSource, CustomJS, Slider
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn


source = ColumnDataSource(data=dict(x=[0,1,2]))
jscallback = CustomJS(args=dict(source=source), code="""

var data = source.get('data');
x = data['x']
x = x+x;
console.log(x)
source.trigger('change');

""")

slider = Slider(start=0.1, end=4, value=1, step=.1, title="power", callback=jscallback)

def printcallback():
    print(source.data['x'])

button1 = Button(label="Foo", button_type="success")
button1.on_click(printcallback)

l = row(slider, button1)
curdoc().add_root(l)
```

**Comment by bryevdv** [comment] 2016-09-20 02:59
This is a duplicate of #4272

**Closed by bryevdv** 2016-09-20 02:59 UTC

**Comment by bryevdv** [comment] 2016-09-20 03:00
This capability does not yet exist.

**Comment by ImmanuelSamuel** [comment] 2016-09-20 19:38
Ah OK. Thanks for the quick response. I see that there is no way for an on load callback but is there a way to send something from a button callback on the JS side back to the python side. All the examples in the docs are only python to webpage. I want to send something back to python side with just the JS callback from a button. (this is what I am trying to achieve in the code above)

**Comment by ImmanuelSamuel** [comment] 2016-09-20 19:41
The slider changes the source data and the button is trying to print the updated data. But when I run it after button press I am not getting the updated values but the initial values. The values are updating in the client side but not in the python side.

**Comment by bryevdv** [comment] 2016-09-20 19:56
@ImmanuelSamuel There's a couple of things going on. You aren't changing the data. You are saving part of the the data in a new variable `x` and you are changing `x` (which leaves `source.data` unchanged). Also, there are limits to what can automatically by synced. Our granularity is basically at the level of: *assignments that replace an entire property can be detected*. So consider this callback:

```
jscallback = CustomJS(args=dict(source=source), code="""
source.data = {'x': [10]}
console.log(source.data['x'])
source.trigger('change');
""")
```

Put in your code above, it prints `[10]` as expected. There's just no good way for us to detect when the "inside" of an object like a list or object is changed. That's inconvenient but there is no way around it that I know.

**Comment by ImmanuelSamuel** [comment] 2016-09-20 21:04
Ah I see yes that works however the on_change event on the source does not trigger when doing this.

In the code below moving the slider changes the source. Clicking the button shows that the source has been changed and prints out the new value. However the on change event on source is not triggered.
```
import numpy as np
from bokeh.layouts import column, row, widgetbox, layout
from bokeh.models import Button
from bokeh.plotting import figure, curdoc
from bokeh.models import ColumnDataSource, CustomJS, Slider


source = ColumnDataSource(data=dict(x=[0,1,2]))
def source_callback(attr, old, new):
    print(source.data['x'])
    print(new)
source.on_change('x', source_callback)


jscallback = CustomJS(args=dict(source=source), code="""
source.data = {'x': [10]}
console.log(source.data['x'])
source.trigger('change');
""")
slider = Slider(start=0.1, end=4, value=1, step=.1, title="power", callback=jscallback)


def printcallback():
    print(source.data['x'])
button1 = Button(label="Foo", button_type="success")
button1.on_click(printcallback)

l = row(slider, button1)
curdoc().add_root(l)
```
