### ISSUE TITLE
Cannot set vbar fill_color to ColumnDataSource column name

### ISSUE THREAD

**Issue by fischja** [bokeh/bokeh#11068] opened 2021-03-16 15:52 UTC
Since 2.3.0, Bokeh does not load when specifying "fill_color" of vbar as a ColumnDataSource column. This used to work in 2.2.3.

```
source_cols = ["q1", "q2", "q3", "iqr", "upper", "lower", "value_counts", "median_hover", "mean_hover",
                   "leistungserbringer", "zsr", "labels", "alphas", "colors"]
source_1 = ColumnDataSource(data=pd.DataFrame({k: [] for k in source_cols}))

box_1 = p.vbar("labels", 0.5, "q2", "q3", fill_color="colors", line_color="black", alpha="alphas", source=source_1)
```

This results in the app not loading in the browser, with the following browser output (however no console errors):
![image](https://user-images.githubusercontent.com/23638305/111339225-e1a74c80-8677-11eb-8c23-97959d0fc668.png)

Setting "fill_color" to a fixed value such as "black" works.

**Comment by bryevdv** [comment] 2021-03-16 16:02
@fischja There are plenty of examples of `vbar` plots with sources that do work in the docs, so whatever the issue is, it is specific to your code. This is why you need to provide us with a complete [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) and most especially the exact data in the CDS in order for us to investigate. It's possible this is a usage problem (i.e. relied on previously undefined behavior that "happened to work") or it could be a bug but we cannot determine anything without actual code to run.

**Comment by bryevdv** [comment] 2021-03-23 22:13
Absent an MRE I am closing this as `norepro` for now.

**Closed by bryevdv** 2021-03-23 22:13 UTC
Labels: NEEDS MORE INFO
