### ISSUE TITLE
Passing objects from server to session

### ISSUE THREAD

**Issue by adam-hubbell** [bokeh/bokeh#4978] opened 2016-08-17 20:33 UTC
A cool feature to see implimented would be the ability to pass objects from the server to a bokeh document as soon as the server is started.
I start the server in a way similar to [this](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/LYmjTXzX43E), but now I would like to pass an object (a pandas dataframe for my purposes) for each document to have.
I currently do something like this:

```
        for key,app_context in self.bokeh_server._tornado._applications.items():
            app_context.server_context
            setattr(app_context._server_context,'dfDict',self.df_dict[key.replace('/','')])
```

where bokeh_server is the result of instantiating bokeh.server.server.Server, and df_dict is a dict of dataframes where the key is the appropriate bokeh doc that should be receiving that dataframe. The issue with this is that I need to add this line to every bokeh directory's 'server_lifecycle.py':

```
def on_session_created(session_context):
    setattr(session_context._document,'dfDict',session_context.server_context.dfDict)
```

which I would rather avoid. 
Also, if there is a hook somewhere in the Server-BokehTornado-Application_Context-SessionContext-Document stack where I could monkey patch my fix, it would be wonderful if you could point me towards it.

**Comment by bryevdv** [comment] 2016-10-04 20:11
Hi @adam-hubbell haven't forgotten these, but my schedule is a black hole until mid October. I should have some real time to devote to some of these not-tiny issues after then.

**Comment by bryevdv** [comment] 2017-03-18 14:53
@adam-hubbell OK, I realize this has been open quite awhile now. Part of the issue is that until very recently, "starting a Server programmatically" was not a very well demonstrated or understood use case. Now that there are some proper examples around this, e.g.:

https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/flask_embed.py

I think there is alot better context to address this. My main question is: is anything actually needed? In the example above the numpy arrays are created inside the `modify_doc` function, but there is no reason at all they could not be module scope variable outside the function, or passed to `modify_doc` using `functools.partial`. I would plan to advocate `FunctionHandler` as the preferred way to use the server "programmatically" and in that case this approach seems like it would address your need in a clean way without needing new API. I think that sharing read-only data this way between session is generally fine and good. 

Do you have thoughts? (also moving to `0.12.6` since `0.12.5` is about to be released)

**Comment by bryevdv** [comment] 2017-05-03 23:51
@adam-hubbell another idea comes to mind, which would be to make it possible to control server lifecycles more easily programmatically. Right now server lifecycles are coupled closely to the existence of ` server_lifecycle.py` file. But when starting a server programmatically (either with `FunctionHandler` or not) it seems like it would be useful to have programmatic hooks for setting `on_session_created` etc. I could get behind that proposal wholeheartedly, and I think it would also satisfy your use case? Your comments would be welcome.

**Comment by bryevdv** [comment] 2017-05-04 00:02
Actually, looking deeper I don't even think anything is necessary. `Handler` is itself already the base class you can override to define `on_session_created`, and you can add new handlers to any app with `.add`. Everything needed already seems to be in place:
```
class SessionHandler(Handler):

    def on_session_created(self, session_context):
        setattr(session_context._document, 'dfDict', dfDict)

bkapp.add(SessionHandler())

server = Server({'/bkapp': bokeh_app},  io_loop=io_loop)

server.start()
```
Accordingly I am going to close this, in favor of not adding extra (duplicative) API.

**Closed by bryevdv** 2017-05-04 00:02 UTC
Labels: tag: component: server, type: feature
