### ISSUE TITLE
[BUG] figure size changes if legend is clicked

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#10901] opened 2021-02-11 20:00 UTC
#### Software info 
bokeh v 2.2.3
python v 3.6
jupyter notebook

#### Description
The figure below is changing the size when the legend is clicked. It was expected that the size of the figure does't change.

####  Minimal example 
```
import networkx as nx

from bokeh.io import output_notebook, show
from bokeh.models import CustomJSTransform, LabelSet
from bokeh.models import Legend, LegendItem
from bokeh.plotting import figure, from_networkx
output_notebook()

G=nx.nx.barbell_graph(3,2)

p = figure(x_range=(-4,4), y_range=(-4,4))
p.grid.grid_line_color = None

r = from_networkx(G, nx.spring_layout, scale=3, center=(0,0))
r.node_renderer.glyph.size = 15
r.edge_renderer.glyph.line_alpha=0.2

legend = Legend(items=[("line",  [r.edge_renderer]),
                       ("orange",[r.node_renderer])
                      ],
                click_policy='hide'        
               )

p.renderers.append(r)
p.add_layout(legend)
show(p)
```
#### Screenshots or screencasts of the bug in action
![Label_resize](https://user-images.githubusercontent.com/68053396/107691111-5539f080-6cab-11eb-8b1e-78a4139b7cf1.PNG)

**Comment by bryevdv** [comment] 2021-02-11 20:02
@mosc9575 Bokeh 2.3 is not yet released, are you saying you are actually using a `2.3dev` pre-release? If not, please confirm your actual version.

**Comment by mosc9575** [comment] 2021-02-11 20:26
I am sorry for the type. I use bokeh 2.2.3.

**Comment by bryevdv** [comment] 2021-02-17 02:40
Whatever issue this is (was), it is currently fixed on master (2.3.0dev13) so I am going to go ahead and close.

**Comment by mattpap** [comment] 2021-02-17 09:35
I couldn't reproduce this either.

**Closed by mattpap** 2021-02-17 09:35 UTC
Labels: type: discussion

**Comment by mosc9575** [comment] 2021-03-02 16:24
After an update to bokeh 2.3.0 I was not able to reproduce this bug anymore. Thank you.
