### ISSUE TITLE
selection not working on all but the last glyph added to a figure

### ISSUE THREAD

**Issue by schlichtanders** [bokeh/bokeh#5200] opened 2016-09-21 14:26 UTC
Selecting points in bokeh gives unexpected behaviour if several layers of glyphs are added to a plot figure. Concretely, only the very last glyph seems to be decisive. Here is an example of the problem adapted from [bokeh doc](http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#customjs-for-selections).
```
from random import random
import numpy as np
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, output_file, show

output_file("selection.html")

x = [random() for x in range(500)]
y = [random() for y in range(500)]
x2 = np.random.uniform(size=500)
y2 = np.random.uniform(size=500)
x2[10:] = np.NaN
y2[10:] = np.NaN

s1 = ColumnDataSource(data=dict(x=x, y=y, x2=x2, y2=y2))
p1 = figure(plot_width=400, plot_height=400, tools="lasso_select", title="Select Here")
p1.circle('x', 'y', source=s1, alpha=0.6)
p1.circle('x2', 'y2', source=s1, alpha=0.6, color="red", size=10)
show(p1)
```
As you can see, only the big red points can be selected, which then also highlights appropriately the respective small blue ones with same index.

I think it is more intuitive to check all glyphs added to a figure instead of only the last one, whether they are selected. What do you think? Is there a way to realise such a behaviour?

Python version      :  2.7.6 (default, Jun 22 2015, 17:58:13) 
IPython version     :  Not installed
Bokeh version       :  0.12.2

**Comment by bryevdv** [comment] 2016-09-21 14:52
This is a dupe of #2136 there is already a WIP PR possibly to resolve: #5158

**Closed by bryevdv** 2016-09-21 14:52 UTC

**Comment by schlichtanders** [comment] 2016-09-21 15:00
thanks @bryevdv for pointing that out. I googled it for 10 min surely, and also looked roughly about the issues of bokeh. But haven't found those two obviously

**Comment by bigreddot** [comment] 2016-09-21 15:51
No worries, it's hard to search the issues unless you already know the exact terms. Hope to have this issue improved soon (it won't be in `0.12.3` but should be the release after that)
