### ISSUE TITLE
Buttons not showing up in IPython notebooks when using bokeh-server

### ISSUE THREAD

**Issue by vitiral** [bokeh/bokeh#1826] opened 2015-02-05 23:20 UTC
I can't seem to get buttons to show up in the IPython notebook when I am using the bokeh-server

with the `bokeh-server` running I run the following code in a notebook
```
from bokeh.plotting import output_notebook, VBox, show
from bokeh.models.widgets import Button
output_notebook(url='default')  # when there is no url this shows the button!
button = Button(label='randomize')
show(VBox(button))  # this doesn't work with the server!!!
```

Is there a workaround I can use for now?

Note: I can't even show figures in a VBox: `show(VBox(f, f))` doesn't work. So it looks like it is a problem with all of the widgets (except for figures)

**Comment by cloudformdesign** [comment] 2015-02-06 15:47
I'm trying to write a tutorial on how to do interactive and streaming data. I would like it to be in IPython and I would like to integrate buttons and other widgets in the tutorial. This is pretty much putting a stop to it though!

**Comment by bryevdv** [comment] 2015-02-06 16:19
Hi @cloudformdesign I can confirm this seems to be a problem. We are just coming up to a code freeze for 0.8, so most likely you can expect a fix in a dev build sometime after the 0.8 release. Definitely look forward to your tutorial. In the mean time, you might look at using IPython interactors instead of Bokeh widgets? It should be fairly trivial to have callbacks for native IPython widgets that push out new data to the server, causing plots to update, etc. Please let us know if we can assist, or provide more information.

**Comment by cloudformdesign** [comment] 2015-02-06 16:48
Thanks, it's good to know that there are currently no workarounds. I banged my head against a wall for a good long while until I realized it worked without the server, but didn't work with it!

I think IPython widgets would be fine for now, and I was considering using them except I want to use the IPython notebook to design and build the application I am doing for work. Before I dive into them though, is their API pretty similar to the bokeh GUI tools? I don't want to design something and then have to relearn a whole new API!

**Comment by bryevdv** [comment] 2015-02-06 16:52
@cloudformdesign the API is actually even simpler, I think, to the extent that we will probably try to emulate it at some point to allow notebook code to be seamlessly transferred outside notebook contexts.  You can check out an example here:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/notebook/interact_basic.ipynb

Note tho, you **won't** be using `push_notebook` you will instead be pushing updates to the server. (There is also currently a memory leak issue with `push_notebook` we are working on)

**Comment by cloudformdesign** [comment] 2015-02-06 21:48
Sounds good, thanks for the help

I've got the first draft of the interractive notebook done, check it out here:

https://github.com/cloudformdesign/bokeh/blob/doc/interractive/examples/plotting/notebook/interractive_tutorial_1.ipynb

I encountered two BUGs and one ISSUE (which I labeled as such in the document)

Bugs:
- `f.add_tools(BoxSelectTool)` doesn't seem to work for some reason. Maybe I am just doing it wrong, but I couldn't get it to work in either the string or object form (or list of objects)
- All plots (f.circle, f.line, etc) require `plot_width=200, plot_height=200` or the plot invades the space of other IPython cells.

Issues:
- Box Select doesn't seem to be working with the histogram at the end. I was hoping to be able to select histogram data and see the asociated points selected on the scatter plot.

**Comment by cloudformdesign** [comment] 2015-02-06 21:52
Also, do you know of a good way to get VBox and HBox in IPython notebooks? [This link](http://nbviewer.ipython.org/github/adrn/ipython/blob/2.x/examples/Interactive%20Widgets/Widget%20Alignment.ipynb) seems to suggest it is some complicated method like:

```
from IPython.html import widgets # Widget definitions
from IPython.display import display # Used to display widgets in the notebook
def fill_container(container):
    components = []
    for i in range(3):
        components.append(widgets.LatexWidget(value="ABC"[i]))
        components[i].set_css(child_style)
    container.children = components
    
container = make_container('VBox')
container.add_class('vbox')
fill_container(container)
```

**Comment by bryevdv** [comment] 2015-02-07 02:08
ping @mattpap @damianavila

**Comment by tactevo** [comment] 2015-02-08 04:13
I'm having similar problems.  When calling output_notebook(url='default), I get NO figures at all when calling show.  I do see the data received by the server, but nothing appears in my iPython notebook.  I've confirmed this with several examples, including the animation.ipynb example in the repo.

My particular use case needs to update an ipython embedded bokeh plot with real-time streaming data.  I was able to get this working using push_notebook() without a server, but I quickly run into this issue:

https://github.com/bokeh/bokeh/issues/1732

I switched to bokeh-server with hopes of avoiding the issue above, but have been unable to get any figure at all to output to an ipython notebook when calling output_notebook(url='default') or output_server().   

Would you mind explaining the bug?

**Comment by cloudformdesign** [comment] 2015-02-08 05:21
@tactevo are you using python 2 or 3?  I am running python 3.4

**Comment by tactevo** [comment] 2015-02-08 05:58
Python 2.7.9
IPython 3.0.0-dev
bokeh 0.7.1-430

**Comment by damianavila** [comment] 2015-02-09 12:31
@tactevo, I ca reproduce @cloudformdesign problem, but I also can run the animation example without any problem... can you provide more info about your IPython version and bokeh version (the version you pasted here does not exist)

In the IPython console...

```
import IPython
print(IPython.sys_info())
```
and
```
import bokeh
bokeh._version.get_versions()
```

Thanks!

**Comment by tactevo** [comment] 2015-02-09 15:00
I'm using the latest master branch version of bokeh directly from the Github repo.  I only started using this version after experiencing the problem with the latest conda install of Bokeh (Which I believe is also 0.7.1).

My current installed versions of bokeh and iPython are:

{'full': '7bf913a6f371a98c63350b183d847da94451a670',
 'version': '0.7.1-430-g7bf913a'}

{'commit_hash': u'9603e51',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/root/miniconda/lib/python2.7/site-packages/IPython',
 'ipython_version': '3.0.0-dev',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-32-generic-x86_64-with-debian-jessie-sid',
 'sys_executable': '/root/miniconda/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.9 |Continuum Analytics, Inc.| (default, Dec 15 2014, 10:33:51) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}

**Comment by damianavila** [comment] 2015-02-09 15:40
OK, please try updating your IPython master... and verify the behaviour again. I said that because you IPython master is from 3 Jan, and in the last weeks there were some problems with the outputs (not showing the outputs well). I want to rule out that possibility... also, using somewhat latest master of IPython (pulled yesterday), I still can not replicate the no animation behaviour...

**Comment by tactevo** [comment] 2015-02-09 16:21
Ok, I've updated iPython.  It's now:

{'commit_hash': u'28a0fc7',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/root/miniconda/lib/python2.7/site-packages/IPython',
 'ipython_version': '3.0.0-dev',
 'os_name': 'posix',
 'platform': 'Linux-3.13.0-32-generic-x86_64-with-debian-jessie-sid',
 'sys_executable': '/root/miniconda/bin/python',
 'sys_platform': 'linux2',
 'sys_version': '2.7.9 |Continuum Analytics, Inc.| (default, Dec 15 2014, 10:33:51) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}

I tried the animated example again, but it still doesn't show a figure.

As I step through the animated.ipynb in iPython, here's what happens.

1.  after executing output_notebook(url='default'), I get

`Using saved session configuration for http://localhost:5006/
To override, pass 'load_from_config=False' to Session`

2. after executing p.angular_wedge..., I get

`<bokeh.plotting.Figure at 0x7f51eafc3a50>`

3. after executing show(p), i get nothing...

4. during the while loop, I see data received by bokeh-server.

**Comment by tactevo** [comment] 2015-02-09 16:27
also, if I change output_notebook(url='default') to just output_notebook() in the animated example, show(p) works fine.  If I add a ds.push_book() in the while loop, I can see the plot animate.  So, the display works fine as long as I'm not connecting to bokeh-server.

**Comment by ivmi** [comment] 2015-04-26 11:45
I experience the same problem (no animated plot) if I try running ipython and loading notebook on separate systems. If I supply the correct url (ip address of server) in output_notebook everything works fine.

@tactevo I've posted a workaround for the issue #1732 on the issue page.

**Comment by bryevdv** [comment] 2016-06-30 16:16
closing, as this refers to the old server which has been completely deprecated and removed. New work to integrate new bokeh server widgets and callbacks in the note book are covered by other issues (and an Epic I am about to create)

**Closed by bryevdv** 2016-06-30 16:16 UTC
Labels: type: bug
