### ISSUE TITLE
[FEATURE] Scrollable legends

### ISSUE THREAD

**Issue by torfsen** [bokeh/bokeh#10709] opened 2020-11-20 09:43 UTC
**Is your feature request related to a problem? Please describe.**

I have auto-generated plots with many lines. Users must be able to show/hide each of these via the interactive legend. However, due to the large number of lines, some legend entries are not shown.

**Describe the solution you'd like**

I would like to have an option to make my interactive legends scrollable, i.e. if the legend has too many entries it should show a scrollbar.

**Describe alternatives you've considered**

My suggestion will only work for interactive settings. See #3880 for a discussion of adding multi-row/-line support to legends (something that would work in a non-interactive setting but would not be applicable in my personal use case).

A workaround that is often suggested is to use [multiple legends for a single plot](https://stackoverflow.com/a/41575193/857390). However, that always seems to require some manual positioning, which is hard to do correctly in my use case due to the auto-generation of the plots.

**Comment by bryevdv** [comment] 2020-11-20 21:47
There's unfortunately not any way to make this happen for legends "inside" a plot, because they are drawn directly on and HTML canvas or webgl canvas, which is opaque as far as the DOM is concerned (it doesn't know anything about the contents inside the canvas or how or when to scroll. It might be possible for legends outside the plot to be DOM-based, but there is already an issue for this, so I will close this as a dupe of https://github.com/bokeh/bokeh/issues/10205

**Closed by bryevdv** 2020-11-20 21:47 UTC
Labels: type: discussion

**Comment by torfsen** [comment] 2020-11-21 13:59
Thanks for the clarification, @bryevdv!
