### ISSUE TITLE
Colons in category names

### ISSUE THREAD

**Issue by icokk** [bokeh/bokeh#1912] opened 2015-02-17 16:14 UTC
When passed from python to js, categorical data in bokeh is encoded as a list of strings of format "category:value". Because of this, category names cannot contain colons, which is very annoying when you try to use e.g. times as category labels. It would be much better to use a list of tuples ["category", value] instead of custom encoding.

**Comment by bryevdv** [comment] 2015-02-17 16:24
This is a dupe of #516 I almost got to it for 0.8 release today, expect to see a fix for this soon in an upcoming dev build.

**Closed by bryevdv** 2015-02-17 16:24 UTC
Labels: reso: duplicate, type: bug
