### ISSUE TITLE
deprecate glyph functions accepting datasource and sequence literals simultanously

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2056] opened 2015-03-10 18:00 UTC
Right now, when user passes datasource and passed in data on glyph functions [checks for a passed in source](https://github.com/bokeh/bokeh/blob/master/bokeh/_glyph_functions.py#L9) and [tries to figure out](https://github.com/bokeh/bokeh/blob/master/bokeh/_glyph_functions.py#L40) what the pile of parameters correspond to, given whatever glyph we are and then in that function it actually sets columns on the data source.

We should just disallow it. If you pass in a data source, you only get to refer to constant values, or column names and if you pass data in, then you should not specify datasource.

**Comment by fpliger** [comment] 2015-03-10 18:01
ping @pzwang and @bokeh/core for opinions..

**Comment by bryevdv** [comment] 2015-03-11 15:27
reference: #2046

**Comment by bryevdv** [comment] 2015-03-14 13:55
Offline discussion] @pzwang is +1

**Comment by davideuler** [comment] 2015-05-05 08:11
+1

**Comment by bryevdv** [comment] 2016-04-02 22:40
PR above was never merged but could be used as a starting place for implementing.

**Comment by bryevdv** [comment] 2016-09-19 18:03
Changed this issue to be for adding a deprecation, will make new issue to raise exception after deprecation period

**Closed** 2016-09-20 03:38 UTC
Labels: tag: starter, type: task

**Comment by Pierretherenard** [comment] 2016-11-04 18:58
I am using this:
`p.rect('xfoo', 'ything', w, h, source=source)` but i get 
Supplying a user-defined data source AND iterable values to glyph methods is deprecated.

See https://github.com/bokeh/bokeh/issues/2056 for more information.
`source = ColumnDataSource(data=dict(x=x, y=y, xz=xz, yz=yz, sopt=sopt, frqwrd=frqwrd))`
`plot_kmeans.circle('x','y', size=15, fill_alpha = 0.0, line_color='black', line_dash=[4,2], line_width=1, source=source)`
I guess i don't understand this then: user-defined data source AND iterable values to glyph methods, would you have another way to explain it?

**Comment by bryevdv** [comment] 2016-11-04 19:02
@Pierretherenard if you pass `source` kwarg to a glyph method, then *all* columns of data have to come from the source, i.e you can't do this:
```
p.circle(x='some_column`, y=[1,2,3], source=source` 
```
In that case, `x` gets a column from the data source, but `y` gets a literal iterable value. That is no longer supported.

**Comment by bryevdv** [comment] 2016-11-04 19:07
EDIT: if you are suggesting you are getting this message in error, that is worth investigating. In that case please open a new issue with minimal complete code to reproduce.

**Comment by Pierretherenard** [comment] 2016-11-04 19:10
ok i will create a minimal code and copy it here if i still get the issue

**Comment by bryevdv** [comment] 2016-11-04 19:12
@Pierretherenard If you are able to reproduce, please make a new issue, not comment in this one.

**Comment by jakirkham** [comment] 2016-11-09 20:42
I'm confused. I don't see anything that looks like the [problematic example]( https://github.com/bokeh/bokeh/issues/2056#issuecomment-258520315 ). However, I'm also seeing this warning. Literally everything is in a `ColumnDataSource` that is passed to `source`. Are there other cases being deprecated besides that example case?

**Comment by bryevdv** [comment] 2016-11-09 21:36
This user clarified on twitter that their actual code did in fact have a literal mixed with column names.

**Comment by kdheepak** [comment] 2017-01-02 18:21
Hi all, I'm not sure how one would implement the following use case.

Let's say I had a dataframe like so 

``` python
df = pd.DataFrame({'x': [0, 1, 2, 3], 'y1': [-10, -10, 0, 0], 'additionaly1': ['s1', 's1', 's0', 's0']})
df
```

<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>additional_y1</th>
      <th>x</th>
      <th>y1</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>s1</td>
      <td>0</td>
      <td>-10</td>
    </tr>
    <tr>
      <th>1</th>
      <td>s1</td>
      <td>1</td>
      <td>-10</td>
    </tr>
    <tr>
      <th>2</th>
      <td>s0</td>
      <td>2</td>
      <td>0</td>
    </tr>
    <tr>
      <th>3</th>
      <td>s0</td>
      <td>3</td>
      <td>0</td>
    </tr>
  </tbody>
</table>

If I wanted to use a low level function to create a bar chart and the ColumnDataSource, I would have to do something like this :

``` python

hover = HoverTool(
        tooltips=[
            ("index", "$index"),
            ("(x,y)", "($x, $y)"),
            ("desc", "@additional_y1"),
        ]
    )

p = figure(width=800, height=600, tools=[hover])
p.rect(x='index', y=[v/2.0 for v in source.data['y1']], width=0.75, height=[abs(v) for v in source.data['y1']], source=source)
show(p)
```

If this feature gets deprecated, how would one do this in the future?

**Comment by kdheepak** [comment] 2017-01-02 18:29
I guess, with the new API, the only way to do the above would be to create additional columns for any data what are required.

```
df['tmp1_y1'] = df['y1']/2
df['tmp2_y1'] = abs(df['y1'])
source = ColumnDataSource(df)
p.rect(x='index', y='tmp1_y1', width=0.75, height='tmp2_y1', source=source)
```

**Comment by bryevdv** [comment] 2017-01-02 18:34
> I guess, with the new API, the only way to do the above would be to create additional columns for any data that is required.

Yes, exactly. Ether you construct a source up front with all the columns, or you let Bokeh construct one with just the data literals that are passed to the glyph method. Allowing "mixed" usage opens up the possibility of subtle bugs and unexpected behavior including overwriting data columns when this is not intended. It really had to be changed.

**Comment by kdheepak** [comment] 2017-01-02 19:39
Thanks for the quick reply! I think that makes sense. So is converting to a `ColumnDataSource` the recommended way to do this? 

I've really been digging Bokeh btw! Great job on everything :)

**Comment by cmdelatorre** [comment] 2017-01-25 18:31
I'm getting the warning _"Supplying a user-defined data source AND iterable values to glyph methods is deprecated."_ for the following case:

`fig.circle('x', 'y', source=source, size=10, fill_color=palettes.viridis(N))` where `N == len(source.data['x'])`

Is that correct? in that case, how can I set a palette as fill_color then?

**Comment by bryevdv** [comment] 2017-01-25 18:38
@cmdelatorre add it as a column to your `source`, the same way you have with `x` and `y`, and then pass the name of the column to the glyph function for the value of the `fill_color` argument.

**Comment by NoGoldFish** [comment] 2017-08-14 17:27
How can I make the legend work in the following statement if I want to using ColumnDataSource? 
 
f.circle(x='Admin',y='Mean', size = 'N_size', fill_alpha = .2, line_dash=[5,3],  legend = 'Average Total Scale Score', source=Total_SS)

**Comment by bryevdv** [comment] 2017-08-14 19:38
@NoGoldFish The issue tracker is not the right place for general support questions, please ask your question on the public mailing list:

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by Albert-Chan** [comment] 2017-12-04 07:24
What if there are several data sources in one plot? 
In tooltip, can we specify the data source for a @columnName ?

**Comment by bryevdv** [comment] 2017-12-04 17:06
@Albert-Chan please take usage and support questions to the mailing list.
