### ISSUE TITLE
Line Series with Points Selection Handling

### ISSUE THREAD

**Issue by rothnic** [bokeh/bokeh#2247] opened 2015-05-06 17:32 UTC
I was taking a look at the widget_server example under the glyphs folder and found what I assume to be non-expected behavior. When selecting a row in the data table, this causes the plot to update based on the selection. Everything switches to a higher alpha representation, but the line no longer goes through the point selected. Here are some screenshots to demonstrate the issue.

![image](https://cloud.githubusercontent.com/assets/452052/7499149/505b25d2-f3eb-11e4-8d0c-89481763882b.png)

![image](https://cloud.githubusercontent.com/assets/452052/7499157/6020637e-f3eb-11e4-8fae-999a6ccee58f.png)

This is with the latest build in the repository and with a newly built bokehjs. During the time I had to glance through, it appears that the visual update is handled on the JS side under GlyphRendererView.

**Comment by bryevdv** [comment] 2015-05-06 17:57
Yah this is definitely an issue, and has been forever. The line renderer needs to be somewhat more sophisticated and render continuous runs of selected points as separate lines, instead of just skipping unselected points (what it does currently).

**Comment by bryevdv** [comment] 2017-05-09 21:25
dupe of #515

**Closed by bryevdv** 2017-05-09 21:25 UTC
Labels: type: bug
