### ISSUE TITLE
DatetimeTickFormatter doesn't stream after second 50

### ISSUE THREAD

**Issue by adi700** [bokeh/bokeh#5213] opened 2016-09-22 09:53 UTC
![bokeh_plot 3](https://cloud.githubusercontent.com/assets/22367577/18743732/b32ea6cc-80ba-11e6-96d4-0a48be1f1941.png)

The datetime ticks draw up to second 50 and then the streaming stops. Using Bokeh 0.12.2 on Python 3.52.

Here is the code:

```
from math import radians
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource, DatetimeTickFormatter
from bokeh.plotting import figure
from datetime import datetime
from random import randrange

f=figure()
source=ColumnDataSource(data=dict(x=[],y=[]))
f.line(x='x',y='y',source=source)
def update():
    new_data=dict(x=[datetime.now()],y=[randrange(1,10)])
    source.stream(new_data,rollover=150)
    print(source.data)
f.xaxis.formatter=DatetimeTickFormatter(formats=dict(
        microseconds=["%Y-%m-%d-%H-%M-%S"],
        seconds=["%Y-%m-%d-%H-%M-%S"],
        minutes=["%Y-%m-%d-%H-%M-%S"],
        hours=["%Y-%m-%d-%H-%M-%S"],
        ))
f.xaxis.major_label_orientation = radians(90)
curdoc().add_root(f)
curdoc().add_periodic_callback(update,1000)
```

The terminal shows the following errors after each periodic callback. The same error lines are generated when trying to pan around the graph. 

```
2016-09-22 11:55:06,833 404 POST /jsnlog.logger (::1) 0.00ms
2016-09-22 11:55:06,849 404 POST /jsnlog.logger (::1) 0.00ms
```

**Comment by bryevdv** [comment] 2016-09-22 15:27
Hi, this is really a support question, so I will close it as `referred` (to the mailing list, etc). This same question was recently answered on the gitter chat channel, for instance. 

The problem is that when supplying formats, you always have to supply ***ALL*** the time scales. You are only setting four of them. One way to solve this is to use the `DEFAULT_DATETIME_FORMATS()` function to get a dict with all the default formats, that you can then update:
```
from bokeh.models.formatters import DEFAULT_DATETIME_FORMATS
formats = DEFAULT_DATETIME_FORMATS()
formats.update(
    microseconds=["%Y-%m-%d-%H-%M-%S"],
    seconds=["%Y-%m-%d-%H-%M-%S"],
    minutes=["%Y-%m-%d-%H-%M-%S"],
    hours=["%Y-%m-%d-%H-%M-%S"],
)
```
Alternatively, you can create your own formats dict from scratch but you have to make sure to provide all needed formats. 
---

If you have to ability to contribute, the core team is very strapped at the moment. Here are some improvements you could make:

* more/better documentation of this case
* possibly including a nice example
* some validation checks that throw an error immediately if the required formats are missing.

**Closed** 2016-09-22 15:27 UTC
Labels: reso: referred

**Comment by adi700** [comment] 2016-09-23 21:53
Thanks a lot. That worked.

The only issue now is the datetime tick labels show in UTC which is -2 hours from my time zone. 
I tried to pass my timezone through pytz.timezone() (i.e. datetime.now(pytz.timezone('Europe/Rome'))) when generating the datetime values, but that still shows as UTC. 
Only if I trick Python by passing the opposite of my timezone which is UTC +2 in the datetime values then I correct labels. Is there a standard way to make the labels show in the local timezone?
