### ISSUE TITLE
Hover tool currently does not work with line glyphs

### ISSUE THREAD

**Issue by gregerhardt** [bokeh/bokeh#2031] opened 2015-03-05 09:41 UTC
As noted in the documentation: 

Point hit testing is not currently available on all glyphs. Hover tool currently does not work with line or image type glyphs.

I am creating this as an issue to show that there is interest in the user community for hover tool capabilities on line glyphs as a highly desirable feature.

**Comment by knightofni** [comment] 2015-03-05 10:07
As a workaround, you can use an invisible Quad glyph, sharing the same data source than your line plot. Works very nicely.

But having hover tools work directly with lines would be nice.

**Comment by gregerhardt** [comment] 2015-03-05 10:29
Thanks.  A quad glyph is a good idea.  I'm currently using a circle glyph at the line midpoint, but that is clunky because you have to have good aim.

**Comment by bryevdv** [comment] 2015-03-05 16:22
dupe of #1486

**Closed by bryevdv** 2015-03-05 16:22 UTC
Labels: reso: duplicate
