### ISSUE TITLE
In python3, rectangle does not appear when x axis is type datetime

### ISSUE THREAD

**Issue by aelanman** [bokeh/bokeh#10488] opened 2020-09-10 20:12 UTC
I've been having trouble plotting rectangular glyphs with bokeh in Python 3. I can't find this issue documented anywhere, or any efforts to correct it.

I'm trying to plot rectangles whose x-axis extent is given as a timedelta, and whose positions are datetimes.

This is a minimum example that produces the error. I generate a set of times via numpy's datetime64, convert them to datetime objects, and plot the set of rectangles. ~No rectangles appear in the plot if the times are close to the current UTC, but if I shift them back 50 years they appear just fine.~ This was in error -- The rectangles appear, but their sizes vary. If I make them narrower by a factor of 10, they disappear altogether.

```
#!/bin/env python
from datetime import datetime, timedelta  
import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import DatetimeTickFormatter
  
## The line below is the key -- If I subtract 50 years from the current date, the rectangles appear just fine.
## If i don't subtract them, the rectangles are not rendered.
t0 = datetime.utcnow() - timedelta(weeks=52 * 50)
 
times = t0.timestamp() * 1e3 + np.linspace(0, 5, 100, endpoint=False) * 3600 * 1e3
times = times.astype('datetime64[ms]')
  
plot = figure(
      output_backend='svg',
      plot_height=500,
      plot_width=1280,
      x_axis_label='UTC Time',
      y_axis_label="",
      y_axis_type='linear'
)
  
plot.xaxis.formatter = DatetimeTickFormatter(
      hours=['%H:%M'],
      minutes=['%H:%M'],
      seconds=['%H:%M']
)
  
dm = np.linspace(0, 100, 20)
width = (np.diff(times)[0] * 0.8).astype(timedelta)
times, dm = np.meshgrid(times, dm)
plot.rect(
      x=times.astype(datetime).flatten(),
      y=dm.flatten(), width=width,
      height=100 / 20, name='rect'
)
  
show(plot)
```

Note the indicated line right after the import statements -- it seems that bokeh is having trouble with recent dates in Python3, probably because their unix times in milliseconds are very large. If I shift back to 1970, as shown here, the error goes away.

I suspect that [this function](https://github.com/bokeh/bokeh/blob/b56543346bad8cdabe99960e63133619feaafbb7/bokeh/util/serialization.py#L162) may be part of the problem. The internal serialization in bokeh converts all datetimes to milliseconds since the unix epoch, which might be overflowing something.

**Comment by bryevdv** [comment] 2020-09-10 20:40
@aelanman we will need more detailed information from you. I get visible output on Python 3.7 with both Bokeh 2.1.1 and Bokeh 2.2.1

That said @mattpap there are definitely *some* issues, since I don't get the *same* output:

## 2.1.1

<img width="600" alt="Screen Shot 2020-09-10 at 1 19 57 PM" src="https://user-images.githubusercontent.com/1078448/92799289-8616a200-f368-11ea-849f-796b7779d53c.png">

## 2.2.1

<img width="600" alt="Screen Shot 2020-09-10 at 1 20 18 PM" src="https://user-images.githubusercontent.com/1078448/92799325-8f077380-f368-11ea-97af-2523d1230b83.png">

This difference persists whether I comment out the SVG backend so it's probably not related to that. I guess this could be related to https://github.com/bokeh/bokeh/issues/10379 / https://github.com/bokeh/bokeh/issues/10329 but what is weird is the second image with uneven rects happens even if I force the type to "unit64" on the python side and verify the JS received plain number lists and not typed arrays (which should be fine) And in fact verify that the values in the JS list are evenly spaced numbers. Here are the first few elements in both versions:

* 211: `1599795298908,1599795478908,1599795658908,1599795838908`
* 221: `1599795455663,1599795635663,1599795815663,1599795995663`

You can see there are both of the correct magnitude. It seems like there might be an actual *drawing* problem?

**Comment by aelanman** [comment] 2020-09-10 20:44
I'm using Python 3.7.6 and bokeh version 2.2.0 (installed via anaconda).

I was seeing similar output to the your 2.2.1 plot (uneven column widths) when I made the widths larger by a factor of 10.

**Comment by bryevdv** [comment] 2020-09-10 20:53
> I was seeing similar output to the your 2.2.1 plot (uneven column widths) when I made the widths larger by a factor of 10.

I don't want to seem too critical @aelanman but I don't really understand why this was not mentioned in the OP? Also now I don't understand if we are seeing the same things now or not. If I divide the widths in the exact code above by 10, then I do see a blank plot as described. Are you saying you see a blank plot with *exactly the code above* and *not* dividing by 10?

**Comment by bryevdv** [comment] 2020-09-10 21:04
@mattpap my current best guess is that despite being sent as correct numbers in plain JSON lists, there is now a loss of precision occurring during the screen space mapping step. Will require some more investigation but I think we will have to figure out #10379 sooner rather than later (or else revert `NumberArray` type to be Float64, but then that would break webgl AFAIK)

**Comment by aelanman** [comment] 2020-09-10 21:07
I should have mentioned that... sorry. Having rerun it, I realized I had this example confused with a different one. In that code, the rectangles disappeared unless I increased the width. I'll update the original post in a second.

With the code as written above, I get the following:
![bokeh_plot (1)](https://user-images.githubusercontent.com/12849618/92806331-e537df00-f387-11ea-84ef-6aaf90e6e0b5.png)


Commenting out the time shift, I get:
![bokeh_plot](https://user-images.githubusercontent.com/12849618/92806224-cafe0100-f387-11ea-87b9-c6391b08c365.png)

**Comment by marecabo** [comment] 2020-09-17 11:54
I also have this issue (missing rectangles) and had to downgrade bokeh to 1.4.0 to get the correct behavior.

**Comment by bryevdv** [comment] 2020-09-17 17:01
@marecabo 2.1.x should be fine

**Comment by aelanman** [comment] 2020-09-21 19:11
It looks like switching to an earlier version of bokeh fixes this for me, so I will do that for now. Thanks for your help!

**Comment by bryevdv** [comment] 2020-09-21 23:40
Digging a bit more, I think the x coords are actually getting sent fine even in 2.2.x (you can plot circles instead of rects to see things evenly spaced correctly, and comparing computed pixel coords only differs by ~10^-7) I think actually there is a bad type interaction involving the *width*, and rect specifically.

**Comment by bryevdv** [comment] 2020-09-21 23:57
And `Glyph.sdist` as well. Here is a diff that fixes 
```
~/work/bokeh branch-2.3* 19s
(dev) ❯ git diff
diff --git a/bokehjs/src/lib/models/glyphs/glyph.ts b/bokehjs/src/lib/models/glyphs/glyph.ts
index 5261aa559..5453869a1 100644
--- a/bokehjs/src/lib/models/glyphs/glyph.ts
+++ b/bokehjs/src/lib/models/glyphs/glyph.ts
@@ -142,17 +142,17 @@ export abstract class GlyphView extends View {
     const n = pts.length
     if (pts_location == 'center') {
       const halfspan = map(spans, (d) => d/2)
-      pt0 = new NumberArray(n)
+      pt0 = new Array(n)
       for (let i = 0; i < n; i++) {
         pt0[i] = pts[i] - halfspan[i]
       }
-      pt1 = new NumberArray(n)
+      pt1 = new Array(n)
       for (let i = 0; i < n; i++) {
         pt1[i] = pts[i] + halfspan[i]
       }
     } else {
       pt0 = pts
-      pt1 = new NumberArray(n)
+      pt1 = new Array(n)
       for (let i = 0; i < n; i++) {
         pt1[i] = pt0[i] + spans[i]
       }
diff --git a/bokehjs/src/lib/models/glyphs/rect.ts b/bokehjs/src/lib/models/glyphs/rect.ts
index ecc472de0..9da8831ea 100644
--- a/bokehjs/src/lib/models/glyphs/rect.ts
+++ b/bokehjs/src/lib/models/glyphs/rect.ts
@@ -175,8 +175,8 @@ export class RectView extends CenterRotatableView {
                                                   scale: Scale): [NumberArray, NumberArray] {
     const n = coord.length

-    const pt0 = new NumberArray(n)
-    const pt1 = new NumberArray(n)
+    const pt0 = new Array(n)
+    const pt1 = new Array(n)

     for (let i = 0; i < n; i++) {
       pt0[i] = coord[i] - side_length[i]/2
```
cc @mattpap for any thoughts. I'll have to think on this a little as well, if we take this route for now then there may be other spots to change as well.

**Comment by bryevdv** [comment] 2020-09-21 23:58
Also marking as 2.3 for now but if we cut a 2.2.2 this fix should definitely go in

**Closed** 2020-09-23 18:16 UTC
Labels: tag: component: bokehjs, type: bug

**Comment by bryevdv** [comment] 2020-10-14 19:59
This should have gone in to 2.2.2 but unfortunately was neglected. We will need to see how far out 2.3 is or if we need to cut a 2.2.3 since this a a fairly annoying bug for anyone using rects with datetimes

**Comment by ItamarShDev** [comment] 2020-10-16 11:50
@bryevdv thank you.

This bug have almost created false positives in my company's data science team.

**Comment by mattpap** [comment] 2020-10-16 19:16
> This bug have almost created false positives in my company's data science team.

If your company depends on bokeh that much, you may want to consider donating towards development of this project, so that we could hire developers to help with expanding our test suite and reduce the number of, especially such severe, regressions in future.

**Comment by mattpap** [comment] 2020-10-16 19:19
> This should have gone in to 2.2.2 but unfortunately was neglected. We will need to see how far out 2.3 is or if we need to cut a 2.2.3 since this a a fairly annoying bug for anyone using rects with datetimes

Yeah, it should have. The overcrowded milestone helped with getting this slip through. I would consider pushing 2.2.3, as 2.3 is weeks away even if code freeze was scheduled soon, unless 2.3-dev is good enough.

**Comment by bryevdv** [comment] 2020-10-16 19:42
OK, I will work on 2.2.3 this weekend (and try to move the dial on more release automation, I have just been personally stuck on getting started on that...)
