### ISSUE TITLE
[BUG] HoverTool works improperly when x axis is manually scaled with smaller range than y axis

### ISSUE THREAD

**Issue by Fabmat1** [bokeh/bokeh#13030] opened 2023-03-25 14:46 UTC
### Software versions

Python version      :  3.11.1 (tags/v3.11.1:a7a450f, Dec  6 2022, 19:58:39) [MSC v.1934 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.1.0
BokehJS static path :  C:\Users\[user]\PycharmProjects\[project]\venv\Lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.22621-SP0

### Expected behavior

The HoverTool collision circle should show the tooltip for the whole marker of a particular datapoint, no matter how the axes are scaled.

### Observed behavior

When the x axis is scaled to be smaller than the y axis using fig.x_range and fig.y_range, the vertical collision area for the HoverTool shrinks proportionally to the relative scaling of the axes. The horizontal collision area stays the same, resulting in an ellipsoidal collision area smaller than the rendered marker that makes the Hovertool not useable for very differently scaled axes. This only occurs when the x-axis covers a smaller range than the y axis. (See attached screencast for an example)

### Example code

```Python
import numpy as np
from bokeh import models as mpl
from bokeh import plotting as bpl
from bokeh.models import Range1d

def example_code():    
    # Grid of values that is more spaced out in the y than in the x direction
    x = []
    y = 10 * [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

    for i in range(10):
        step = 10 * [i * 0.1]
        x += step

    x = np.array(x)
    y = np.array(y)

    exp_src = {"x": x, "y": y}
    example_source = bpl.ColumnDataSource(data=exp_src)

    fig = bpl.figure(width=700, height=400)

    main_plot = fig.scatter(source=example_source,
                            name="main",
                            x="x",
                            y="y",
                            marker="circle",
                            radius=.025,
                            alpha=.7)

    hover = mpl.HoverTool(tooltips=[("x", "@x"),
                                    ("y", "@y")],
                          renderers=[main_plot])
    fig.add_tools(hover)

    fig.x_range = Range1d(np.amin(x) - np.ptp(x) * 0.05, np.amax(x) + np.ptp(x) * 0.05)
    fig.y_range = Range1d(np.amax(y) + np.ptp(y) * 0.05, np.amin(y) - np.ptp(y) * 0.05)

    return fig
```

### Screenshots

Ignore the mouse glitch from my capture software, thats unrelated.

https://user-images.githubusercontent.com/88104880/227724253-c73c3233-bc22-4621-b895-a64da409f9a8.mp4

**Comment by bryevdv** [comment] 2023-03-25 15:41
This is ultimately a duplicate of #517 (and #6396 and #7965 and  #8266 and #10494 and others) 

Please see those issues for detailed discussion. There are two options and which you choose depends on your needs

* Force the data aspect ratio to match pixel-circles -> use `aspect_match` and auto-ranging (no manual range setting)
* Force the circles to "squish" to match you non-square range aspect -> use ellipses instead of circles

**Closed as completed by bryevdv** 2023-03-25 15:41 UTC
Labels: reso: duplicate
