### ISSUE TITLE
Changing the min_date of a DatePicker in a js callback

### ISSUE THREAD

**Issue by sjohnson5** [bokeh/bokeh#8441] opened 2018-11-16 00:00 UTC
I'm trying to control the min_date of a DatePicker with another DatePicker and a js callback. The idea being that I can allow a user to select a date range but not be able to select a start after the end or an end before the start.

Here's my code:
```
from datetime import datetime

import bokeh
from bokeh.io import output_file, show, reset_output
from bokeh.models import CustomJS
from bokeh.models.widgets import DatePicker
from bokeh.layouts import row

print('Bokeh version:', bokeh.__version__)
reset_output()
output_file("test.html")

start_picker = DatePicker(title="Start",
                    min_date=datetime(2018, 1, 10),
                    max_date=datetime(2018, 1, 31),
                    value=datetime(2018, 1, 1))

end_picker = DatePicker(title="End",
                    min_date=datetime(2018, 1, 10),
                    max_date=datetime(2018, 1, 31),
                    value=datetime(2018, 1, 15))


start_picker_callback = CustomJS(args=dict(end_picker=end_picker), code=f"""
    var min_date = Date.parse(Date(cb_obj.value));
    console.log('Selected start:', min_date)
    console.log('Old end_picker.min_date =', end_picker.min_date)
    
    end_picker.min_date = min_date;
    console.log('New end_picker.min_date =', end_picker.min_date)
    
    end_picker.change.emit();
""")
start_picker.js_on_change('value', start_picker_callback)

layout = row(start_picker, end_picker)
show(layout)
```

From the console.log(...) calls the callback appears to be changing the value of end_picker's min_date. However when you try to select an end date (after changing the start date), there has been no change. 

However, if I follow the same logic with Sliders it works:
```
from datetime import datetime

import bokeh
from bokeh.io import output_file, show, reset_output
from bokeh.models import CustomJS
from bokeh.models.widgets import Slider
from bokeh.layouts import row

print('Bokeh version:', bokeh.__version__)
reset_output()
output_file("test.html")

slider1 = Slider(title="Slider 1",
                 start=1,
                 end=5,
                 value=3,
                 step=1)

slider2 = Slider(title="Slider 2",
                 start=1,
                 end=10,
                 value=6,
                 step=1)


slider_callback = CustomJS(args=dict(slider2=slider2), code="""
    var min_num = cb_obj.value;
    console.log('Selected number:', min_num)
    console.log('Old slider2.start =', slider2.start)
    
    slider2.start = min_num;
    console.log('New slider2.start =', slider2.start)
    
    slider2.change.emit();
""")
slider1.js_on_change('value', slider_callback)

layout = row(slider1, slider2)
show(layout)
```
Is this a bug or is there something I am doing wrong or some way to get around it?

Also a DatePicker for ranges would be cool!
Something like this:
![image](https://user-images.githubusercontent.com/36089304/48589109-dba9d100-e8ee-11e8-9675-244874fcb5fc.png)

#### Software versions:
-bokeh 1.0.1
-python 3.7.0
-Ubuntu 18.04.1
-Firefox Quantum 63.0

**Comment by mattpap** [comment] 2018-11-16 16:58
Currently changing min/max dates or really any other properties on date picker widget isn't supported (well, you can change the values, but nothing will happen as a result). This is currently a common pattern in bokehjs, that changes to quite a few properties result in no action to be taken. There are numerous similar issues open at this point.

**Comment by bryevdv** [comment] 2019-07-13 04:12
This is a dupe of #8934 which I have a PR inflight for.

**Closed by bryevdv** 2019-07-13 04:12 UTC
Labels: tag: component: bokehjs, tag: widgets, type: bug

**Comment by bryevdv** [comment] 2020-01-17 03:49
NOTE: #9509 re-fixes this and many other datepicker issues (as well as adds selenium tests) but note that the implementatoon was switched to Flatpickr, and also now date values can *only* be expressed as ISO date strings, or `datetime.date` and nothing else (in particular no more datetime values which caused endless trouble with time zones)
