### ISSUE TITLE
Hit detection conflict with multiple HoverTools and single ColumnDataSource

### ISSUE THREAD

**Issue by schoolie** [bokeh/bokeh#8357] opened 2018-10-24 03:26 UTC
#### Description of expected behavior and the observed behavior
I expect to be able to add multiple HoverTools to a plot, and use the `renderers` kwarg to specify which glyph the HoverTool references. In fact, this works great when the glyphs are created by passing data in directly from a DataFrame, i.e. `plot.line(df['x'], df['y1'])`

However, when I use a ColumnDataSource, the HoverTools seem to "overlap." Only the last HoverTool defined detects the mouse cursor hover event, but when it detects a hover, _both_ lines switch to their hover glyphs.

#### Complete, minimal, self-contained example code that reproduces the issue
```
from bokeh.plotting import figure, output_notebook, show
from bokeh.models import HoverTool, SaveTool, ColumnDataSource
import pandas as pd
import numpy as np

output_notebook()

x = np.arange(0,10)
y1 = x**2
y2 = 81-x**2


## Figure 1 - Directly accessing pd.DataFrame  --  hover glyph behaves as expected
df = pd.DataFrame(dict(x=x, y1=y1, y2=y2))

# Basic plot setup
plot = figure(plot_width=600, plot_height=300, x_axis_type="datetime", tools="", title='Fig 1 - Direct access from DataFrame - Behaves as expected')


line1 = plot.line(df['x'], df['y1'], line_width=1, color='red', hover_color='red')
line1.hover_glyph.line_width = 4

line2 = plot.line(df['x'], df['y2'], line_width=1, color='blue', hover_color='blue')
line2.hover_glyph.line_width = 4


plot.add_tools(HoverTool(tooltips=[('y1 value', '@y')], renderers=[line1]))
plot.add_tools(HoverTool(tooltips=[('y2 value', '@y')], renderers=[line2]))

show(plot)


## Figure 2 - Using CDS  --  hovertool highlights both curves, but only when hovering over blue line
source = ColumnDataSource(dict(x=x, y1=y1, y2=y2))

plot = figure(plot_width=600, plot_height=300, x_axis_type="datetime", tools="", title='Fig 2 - CDS, Blue Line HoverTool added last')

line1 = plot.line('x', 'y1', source=source, line_width=1, color='red', hover_color='red')
line1.hover_glyph.line_width = 4

line2 = plot.line('x', 'y2', source=source, line_width=1, color='blue', hover_color='blue')
line2.hover_glyph.line_width = 4

plot.add_tools(HoverTool(tooltips=[('y1 value', '@y1')], renderers=[line1]))
plot.add_tools(HoverTool(tooltips=[('y2 value', '@y2')], renderers=[line2]))

show(plot)


## Figure 3 - Using CDS, swapped HoverTool definitions  --  hovertool highlights both curves, but only when hovering over red line
source = ColumnDataSource(dict(x=x, y1=y1, y2=y2))

plot = figure(plot_width=600, plot_height=300, x_axis_type="datetime", tools="", title='Fig 3 - CDS, Red Line HoverTool added last')

line1 = plot.line('x', 'y1', source=source, line_width=1, color='red', hover_color='red')
line1.hover_glyph.line_width = 4

line2 = plot.line('x', 'y2', source=source, line_width=1, color='blue', hover_color='blue')
line2.hover_glyph.line_width = 4

plot.add_tools(HoverTool(tooltips=[('y2 value', '@y2')], renderers=[line2]))
plot.add_tools(HoverTool(tooltips=[('y1 value', '@y1')], renderers=[line1]))

show(plot)
```

#### Screenshots or screencasts of the bug in action
![bokeh-issue](https://user-images.githubusercontent.com/3915737/47404149-d30c1380-d711-11e8-9a37-a84e6486ed90.gif)

#### Version Info:
bokeh 0.13.0
python 3.6.4
ubuntu 16.04
chrome 63.0.3239.108

**Comment by bryevdv** [comment] 2018-10-24 03:32
Thanks for the detailed report @schoolie As an FYI I believe this may be a duplicate of https://github.com/bokeh/bokeh/issues/7397 in which case we will close this issue with the link back. Will be sometime after the release before I can look more deeply, though.

**Comment by bryevdv** [comment] 2019-02-19 03:58
I do believe this is a duplicate of #7397 There is some broad cleanup/fixup needed in this area still

**Closed** 2019-02-19 03:58 UTC
Labels: reso: duplicate, type: discussion
