### ISSUE TITLE
[BUG] Google Chrome 130 fails to draw figure, throws `TypeError: Failed to execute 'fill' on 'CanvasRenderingContext2D'`

### ISSUE THREAD

**Issue by erenatas** [bokeh/bokeh#14090] opened 2024-10-03 16:05 UTC
### Software versions

Python version        :  3.12.0 (main, Oct 26 2023, 16:32:05) [Clang 15.0.0 (clang-1500.0.40.1)]
IPython version       :  8.28.0
Tornado version       :  6.4
NumPy version         :  1.26.4
Bokeh version         :  3.6.0
BokehJS static path   :  /Users/eatas/git_repo/repo_a/venv/lib/python3.12/site-packages/bokeh/server/static
node.js version       :  v18.20.2
npm version           :  10.5.0
jupyter_bokeh version :  (not installed)
Operating system      :  macOS-14.6.1-arm64-arm-64bit

### Browser name and version

Google Chrome 130+ (Reproduced in Version 130.0.6723.19 (Official Build) beta (arm64))

### Expected behavior

Expected to show figure on Chrome

### Observed behavior

Bokeh does not work, showing only sidebar and throwing errors on console

Starting from Google 130, we started to observe these javascript errors even on a basic figure example taken from Bokeh docs. Reproduced in multiple laptops.

### Example code

```Python
from bokeh.plotting import figure, show

plot = figure(width=300, height=300)
plot.annulus(x=[1, 2, 3], y=[1, 2, 3], color="#7FC97F",
             inner_radius=0.2, outer_radius=0.5)

show(plot)
```

### Stack traceback or browser console output

```
bokeh-3.6.0.min.js:185 [bokeh 3.6.0] setting log level to: 'info'
bokeh-3.6.0.min.js:256 Uncaught (in promise) TypeError: Failed to execute 'fill' on 'CanvasRenderingContext2D': The provided value 'undefined' is not a valid enum value of type CanvasFillRule.
    at c.apply (bokeh-3.6.0.min.js:256:264)
    at o._paint_empty (bokeh-3.6.0.min.js:623:18180)
    at o._actual_paint (bokeh-3.6.0.min.js:623:16812)
    at o.paint (bokeh-3.6.0.min.js:623:15775)
    at o._after_layout (bokeh-3.6.0.min.js:623:15470)
    at o.after_layout (bokeh-3.6.0.min.js:588:6020)
    at o.compute_layout (bokeh-3.6.0.min.js:588:5400)
    at o.invalidate_layout (bokeh-3.6.0.min.js:588:6198)
    at o._after_render (bokeh-3.6.0.min.js:588:6074)
    at o.after_render (bokeh-3.6.0.min.js:277:2318)
3bokeh-3.6.0.min.js:256 Uncaught (in promise) TypeError: Failed to execute 'fill' on 'CanvasRenderingContext2D': The provided value 'undefined' is not a valid enum value of type CanvasFillRule.
    at c.apply (bokeh-3.6.0.min.js:256:264)
    at o._paint_empty (bokeh-3.6.0.min.js:623:18180)
    at o._actual_paint (bokeh-3.6.0.min.js:623:16812)
    at o.paint (bokeh-3.6.0.min.js:623:15775)
    at o.repaint (bokeh-3.6.0.min.js:623:15643)
    at bokeh-3.6.0.min.js:623:3700
    at a (bokeh-3.6.0.min.js:627:187)
apply @ bokeh-3.6.0.min.js:256
_paint_empty @ bokeh-3.6.0.min.js:623
_actual_paint @ bokeh-3.6.0.min.js:623
paint @ bokeh-3.6.0.min.js:623
repaint @ bokeh-3.6.0.min.js:623
(anonymous) @ bokeh-3.6.0.min.js:623
a @ bokeh-3.6.0.min.js:627
requestAnimationFrame
(anonymous) @ bokeh-3.6.0.min.js:627
setTimeout
(anonymous) @ bokeh-3.6.0.min.js:627
r @ bokeh-3.6.0.min.js:627
schedule_paint @ bokeh-3.6.0.min.js:623
request_paint @ bokeh-3.6.0.min.js:623
request_repaint @ bokeh-3.6.0.min.js:623
unpause @ bokeh-3.6.0.min.js:623
update_range @ bokeh-3.6.0.min.js:623
_update @ bokeh-3.6.0.min.js:684
_pan @ bokeh-3.6.0.min.js:684
i @ bokeh-3.6.0.min.js:500
trigger @ bokeh-3.6.0.min.js:500
__trigger @ bokeh-3.6.0.min.js:500
_trigger @ bokeh-3.6.0.min.js:500
on_pan @ bokeh-3.6.0.min.js:500
on_pan @ bokeh-3.6.0.min.js:470
_pointer_move @ bokeh-3.6.0.min.js:470
bokeh-3.6.0.min.js:256 Uncaught (in promise) TypeError: Failed to execute 'fill' on 'CanvasRenderingContext2D': The provided value 'undefined' is not a valid enum value of type CanvasFillRule.
    at c.apply (bokeh-3.6.0.min.js:256:264)
    at o._paint_empty (bokeh-3.6.0.min.js:623:18180)
    at o._actual_paint (bokeh-3.6.0.min.js:623:16812)
    at o.paint (bokeh-3.6.0.min.js:623:15775)
    at o.repaint (bokeh-3.6.0.min.js:623:15643)
    at bokeh-3.6.0.min.js:623:3700
    at a (bokeh-3.6.0.min.js:627:187)
apply @ bokeh-3.6.0.min.js:256
_paint_empty @ bokeh-3.6.0.min.js:623
_actual_paint @ bokeh-3.6.0.min.js:623
paint @ bokeh-3.6.0.min.js:623
repaint @ bokeh-3.6.0.min.js:623
(anonymous) @ bokeh-3.6.0.min.js:623
a @ bokeh-3.6.0.min.js:627
requestAnimationFrame
(anonymous) @ bokeh-3.6.0.min.js:627
r @ bokeh-3.6.0.min.js:627
schedule_paint @ bokeh-3.6.0.min.js:623
request_paint @ bokeh-3.6.0.min.js:623
request_repaint @ bokeh-3.6.0.min.js:623
unpause @ bokeh-3.6.0.min.js:623
update_range @ bokeh-3.6.0.min.js:623
_update @ bokeh-3.6.0.min.js:684
_pan @ bokeh-3.6.0.min.js:684
i @ bokeh-3.6.0.min.js:500
trigger @ bokeh-3.6.0.min.js:500
__trigger @ bokeh-3.6.0.min.js:500
_trigger @ bokeh-3.6.0.min.js:500
on_pan @ bokeh-3.6.0.min.js:500
on_pan @ bokeh-3.6.0.min.js:470
_pointer_move @ bokeh-3.6.0.min.js:470
```

### Screenshots

<img width="1512" alt="image" src="https://github.com/user-attachments/assets/12738f94-d605-4b4b-9b49-b8e4d6d6e55b">

**Comment by bryevdv** [comment] 2024-10-03 16:18
@erenatas Can you please re-run with the environment variable `BOKEH_MINIFIED=no` set, and attach the more detailed stack trace here?

**Comment by bryevdv** [comment] 2024-10-03 16:20
Well, I guess this is where it is complaining about:

https://github.com/bokeh/bokeh/blob/9750886691199029bc407e776d1665b8b9f01bc9/bokehjs/src/lib/core/visuals/fill.ts#L18-L25

Evidently [`"nonzero"` is the default](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fill#specifying_a_path_and_a_fillrule) can we also just make that an explicit default on our end, so that we can pass an actual value in all cases? Otherwise I suppose we will need to condition explicitly for the case when a rule is not passed in. 

This is a pretty annoying change on Chrome's part.  I'd be curious to know if it was intentional or just some unintended consequence of other work. Either way, we might want to backport this a few releases, maybe even all the way to 3.4...

Edit: I didn't find anything relevant on the Chromium tracker, but I also didn't look too hard

**Comment by erenatas** [comment] 2024-10-03 16:26
> @erenatas Can you please re-run with the environment variable `BOKEH_MINIFIED=no` set, and attach the more detailed stack trace here?

ran it such as:
```bash
$ BOKEH_MINIFIED=no python test.py

$ cat test.py
from bokeh.plotting import figure, show

plot = figure(width=300, height=300)
plot.annulus(x=[1, 2, 3], y=[1, 2, 3], color="#7FC97F",
             inner_radius=0.2, outer_radius=0.5)

show(plot)
```

```
Uncaught (in promise) TypeError: Failed to execute 'fill' on 'CanvasRenderingContext2D': The provided value 'undefined' is not a valid enum value of type CanvasFillRule.
    at Fill.apply (bokeh-3.6.0.js:13270:21)
    at FigureView._paint_empty (bokeh-3.6.0.js:51366:42)
    at FigureView._actual_paint (bokeh-3.6.0.js:51296:22)
    at FigureView.paint (bokeh-3.6.0.js:51228:22)
    at FigureView._after_layout (bokeh-3.6.0.js:51208:22)
    at FigureView.after_layout (bokeh-3.6.0.js:48120:18)
    at FigureView.compute_layout (bokeh-3.6.0.js:48076:22)
    at FigureView.invalidate_layout (bokeh-3.6.0.js:48136:22)
    at FigureView._after_render (bokeh-3.6.0.js:48125:22)
    at FigureView.after_render (bokeh-3.6.0.js:15701:18)
```

Hope it helps!

**Comment by mattpap** [comment] 2024-10-10 10:02
Inexcusable regression and I'm not sure what's worse, if it was done by accident or intentionally. This breaks bokeh releases since 2.4. I submitted PR #14093 resolving this.

**Comment by bryevdv** [comment] 2024-10-10 13:32
@mattpap can you file an upstream issue? Not super hopeful but maybe someone who agrees it is a regression will notice it.

**Closed as completed** 2024-10-11 06:13 UTC
Labels: type: bug, reso: completed, plat: chrome, tag: component: bokehjs

**Comment by mattpap** [comment] 2024-10-11 06:14
> can you file an upstream issue? Not super hopeful but maybe someone who agrees it is a regression will notice it.

I will be investigating this further, so I may submit a bug report at some point.

**Comment by erenatas** [comment] 2024-10-11 11:45
Thank you very for reacting very quickly on this? Will you backport this? Chrome already released version 130 AFAIK

**Comment by bryevdv** [comment] 2024-10-11 15:46
Yes, but it will take time, and we will have to see how far back is feasible to build and release. There's pretty much no chance of getting the 2.x build machinery up and running again at this point, for example.

**Comment by bryevdv** [comment] 2024-10-11 16:30
@bokeh/dev I've opened backport PRs back to 3.3.x How far do we want to try to go? Branches older than `branch-3.2` have already been archived, so we'd have to reconstitute them on GH to try and go further than that. I am not sure if it's worth it, though. The real issue is that anything previously "deployed" will break with this new chrome without user intervention, regardless of how far we go.

**Comment by bryevdv** [comment] 2024-10-11 16:51
@mattpap I think getting something on the Chromium tracker is a priority. If you don't expect to submit something today, that's fine but please let me know and I will file a bug report there this afternoon.

**Comment by mattpap** [comment] 2024-10-11 20:14
@bryevdv, if you have time, please do so. I'm sick currently (probably courtesy of fellow travelers on Wednesday), so I'm not in a position to do anything right now.

**Comment by bryevdv** [comment] 2024-10-11 20:28
Feel better @mattpap I have submitted https://issues.chromium.org/u/1/issues/372907704

**Comment by bryevdv** [comment] 2024-10-14 14:02
The bugzilla issue has been updated to P0/Release Blocking so maybe there is hope that this is resolved upstream. 

Edit: evidently this change has been identified and will be reverted. It still might be a good exercise to try and identify places where this particular usage occurs in Bokeh more generally, and remove it for good measure. I have no idea whether it's actually covered by a standard somewhere, or if we've just gotten "lucky" with a common result for undefined behavior all these years.

**Comment by bryevdv** [comment] 2024-10-14 16:29
It looks like the change to revert has been pushed upstream. @erenatas can you try things out with the next beta release of chrome? (And thank you *very* much for bringing this to our attention early)

**Comment by mattpap** [comment] 2024-10-15 10:27
That's a very good outcome. I'm glad you acted quickly.

For me the takeaway is that we urgently need to set up some form of testing, even rudimentary unit testing (ideally) with code coverage, of Chromium's release candidates. As a secondary goal, we need to apply such base tests to other browsers and hopefully their RCs. Our current strategy is to have very finely detailed tests focusing on one platform, and one browser and version, primarily due to technical reasons (baseline testing) and performance, but it's high time to have an orthogonal approach for multiple versions, platforms and vendors.

Another takeaway is that we should change the default bokehjs' CDN URL versioning strategy from specific versions to specific branches, while preserving version specific approach as an option for e.g. highly security minded folks. What I mean is that instead of this in generated HTML output:
```html
<script src="https://cdn.bokeh.org/bokeh/dev/bokeh-3.7.0.min.js"></script>
```
we should have this:
```html
<script src="https://cdn.bokeh.org/bokeh/dev/bokeh-3.7.min.js"></script>
```
which would resolve to the most recent patch version of 3.7. If we used that approach already and assuming that Chromium kept the offending change, then we would be able to publish new patch releases for all affected versions and no user intervention would be needed to take advantage of these releases.

Well, or something equivalent, e.g. learning from existing CDNs, like jsdelivr, which support npm's versioning strategies, like `~3.7` meaning the latest patch version in 3.7. In any case, to allow this, we will have to be stringent to have very focused and non-breaking patch releases, which in fact we managed to have for a while now.

**Comment by erenatas** [comment] 2024-10-15 10:36
> It looks like the change to revert has been pushed upstream. @erenatas can you try things out with the next beta release of chrome? (And thank you _very_ much for bringing this to our attention early)

My pleasure, I will make sure to test on next beta release. I tried with chromium dev build now `Version 132.0.6779.0 (Developer Build) (x86_64 translated)`, and I can report that its working on our side. I will keep you updated if I can also verify it on chrome-beta side.

**Comment by mattpap** [comment] 2024-10-15 18:30
> (...) I have no idea whether it's actually covered by a standard somewhere, or if we've just gotten "lucky" with a common result for undefined behavior all these years.

I originally thought this was some form of UB, but upon reading [Web IDL](https://webidl.spec.whatwg.org/) standard specification, which is used to define concrete Web APIs like HTML Canvas API, I think that the original and restored behavior is the correct and well defined one.

Here's the excerpt of relevant definitions from [HTML Canvas](https://html.spec.whatwg.org/#2dcontext) specification:

```ts
interface mixin CanvasDrawPath {
  undefined fill(optional CanvasFillRule fillRule = "nonzero");
  undefined fill(Path2D path, optional CanvasFillRule fillRule = "nonzero");
}
```

Let's focus on the first one, but the reasoning is equivalent in both cases.

First of all, in section [2.5.8.1 Overloading vs. union types](https://webidl.spec.whatwg.org/#idl-overloading-vs-union):

> Specification authors are encouraged to treat missing argument and `undefined` argument the same way in the JavaScript language binding.

and:

> (...) specification authors are encouraged to use an `optional` argument, which would categorize both `foo()` and `foo(undefined)` as "arg is missing".

Then in section [3.6 Overload resolution algorithm](https://webidl.spec.whatwg.org/#js-overloads), step 11.4.1 we get:

> If optionality is “optional” and V is undefined, then:
>   If the argument at index i is declared with a default value, then append to values that default value.

and a note regarding the algorithm:

> When converting an optional argument’s JavaScript value to its equivalent IDL value, `undefined` will be converted into the optional argument’s default value, if it has one, or a special value “missing” otherwise.

Altogether we get that `ctx.fill()` and `ctx.fill(undefined)` are equivalent, and imply `ctx.fill("nonzero")`.
