### ISSUE TITLE
Use of HTMLTemplateFormatter causes DataTable to not render in 0.12.5

### ISSUE THREAD

**Issue by caseyzak24** [bokeh/bokeh#6465] opened 2017-06-13 19:01 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Software version info: Python 3.6.0 (Anaconda) on Windows 7 Professional on a Lenovo Thinkpad Ultrabook. Launching via a bokeh server.

#### Description of expected behavior and the observed behavior

In 0.12.4, setting the formatter of a TableColumn (for use in a DataTable) to HTMLTemplateFormatter behaves as expected. In 0.12.5, the same code causes only the DataTable column headings to render, but none of the column content.

#### Complete, minimal, self-contained example code that reproduces the issue

#The following code executes a expected in 0.12.4 but not in 0.12.5 (executed as file 'example.py')
import pandas as pd
import numpy as np
from fuzzywuzzy import process
from bokeh.io import curdoc
from bokeh.layouts import row, column, widgetbox, Spacer
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import HTMLTemplateFormatter
from bokeh.models.widgets import DataTable, TableColumn

template = """
<div style="color:red"><%= value %></div>
"""
source1 = ColumnDataSource(data=dict())
columns = [TableColumn(field="Col1", title="Col1"),TableColumn(field="Col2", title="Col2", formatter=HTMLTemplateFormatter(template=template))]
data_table1 = DataTable(source=source1, columns=columns, row_headers=False)

def update(selected=None):
	tbl1 = pd.DataFrame(columns=['Col1','Col2'])
	tbl1 = tbl1.assign(Col1=['thing1'],Col2=['thing2'])
	source1.data = {
        'Col1'                  : tbl1.Col1,
        'Col2'                  : tbl1.Col2,
        }

layout = data_table1

update()

curdoc().add_root(layout)
curdoc().title = "Example"

import os
os.system(r"start cmd /c bokeh serve --show C:\XXX\XXX\XXX\example.py")

#### Screenshots or screencasts of the bug in action
This is what it looks like with 0.12.5
![image](https://user-images.githubusercontent.com/29411281/27099250-319753f8-502f-11e7-9e74-bdaca4eca66e.png)

This is what it looks like with 0.12.4
![image](https://user-images.githubusercontent.com/29411281/27099484-f465fcb8-502f-11e7-9bdd-e3f55fbdf265.png)

**Comment by bryevdv** [comment] 2017-06-13 19:04
This is almost certainly a dupe of https://github.com/bokeh/bokeh/issues/6207 

Please try with `0.12.6` (released this morning) and re-open if a problem is still reproducible.

**Closed by bryevdv** 2017-06-13 19:04 UTC
