### ISSUE TITLE
webgl incorrect clipping, 0.12.11 onwards

### ISSUE THREAD

**Issue by doiko** [bokeh/bokeh#7211] opened 2017-11-14 13:41 UTC
When webgl is enabled and firefox is used after zooming or panning glyphs can go outside the axes.
Moving them back can also leave some "garbages" outside axes.

Can be reproduced in: 
https://bokeh.pydata.org/en/latest/docs/user_guide/webgl.html
![untitled](https://user-images.githubusercontent.com/33360731/32782681-7a183db6-c949-11e7-8a75-a04c59c94fc2.png)

This issue do not appear at chrome, or edge

**Comment by mattpap** [comment] 2017-11-14 14:20
Which version of Firefox and what platform?

**Comment by doiko** [comment] 2017-11-14 15:59
Problem appears in Firefox 56.0 (64-bit), both standard and developer edition under Ubuntu 17.04 and 16.04.

**Comment by mattpap** [comment] 2017-11-14 16:18
Are there any error in JS console? E.g.:
```
Error: WebGL warning: Failed to create WebGL context: WebGL creation failed: 
* Refused to create native OpenGL context because of blacklist entry: 
* Exhausted GL driver options.
```
I have exactly the same setup in my dev VM and on my host system, and in VM it works and fails on host. Anyway, what you observe here is that webgl wasn't allowed to be initialized (I suspect it's a configuration issue), so bokeh fell back to software rendering, but didn't properly set up clipping region (as this is done by webgl renderer if requested).

**Comment by mattpap** [comment] 2017-11-14 16:26
https://wiki.mozilla.org/Blocklisting/Blocked_Graphics_Drivers may help enabling webgl.

**Comment by doiko** [comment] 2017-11-14 17:47
Hi,
I am opening https://bokeh.pydata.org/en/latest/docs/user_guide/webgl.html
and the error I see is
```
Source map error: request failed with status 404
Resource URL: https://cdn.pydata.org/bokeh/release/bokeh-0.12.10.min.js
Source Map URL: bokeh.min.js.map
```
Working in a VM.

**Comment by AzraelDD** [comment] 2017-12-14 15:17
On my Windows laptop, I have the same problem. The rectangle where glyphs are displayed does not match with the figure axis.
In my case the problem appears in all browsers (Firefox, Chrome, Egde). At the same time, all of them show huge performance improvements with enabled webgl. So I assume that webgl is sort of working (i.e. not blocklisted), just not properly. I already tried a second Windows laptop which shows the same behaviour.
Is there anything I can do to help identify the cause of the issue?

**Comment by alexomics** [comment] 2018-01-17 01:54
Similar issues on MacOS. In Firefox, with webgl enabled, I only see overflow on the top or bottom axes on some plots (see below) Though it seems like the 'view' is just shifted in one direction.
![bokeh_plot 1](https://user-images.githubusercontent.com/30386655/35021122-6295b280-fb27-11e7-8a2b-8702378ca8ae.png)
![bokeh_plot 3](https://user-images.githubusercontent.com/30386655/35021213-d3a4c27c-fb27-11e7-9eb1-fbd7829a2bc9.png)

Both from [https://bokeh.pydata.org/en/latest/docs/user_guide/webgl.html](https://bokeh.pydata.org/en/latest/docs/user_guide/webgl.html)

In Chrome, with webgl disabled, I see overflow on all sides.

Firefox console warning: `bokeh-gl-0.12.13.min.js:1:12536`
```
Error: WebGL warning: Drawing without vertex attrib 0 array enabled forces the browser to do expensive emulation work when running on desktop OpenGL platforms, for example on Mac. It is preferable to always draw with vertex attrib 0 array enabled, by using bindAttribLocation to bind some always-used attribute to location 0.
```

Chrome console warning: `bokeh-0.12.13.min.js:sourcemap:1 `
```
bokeh-0.12.13.min.js:sourcemap:1 [bokeh] WebGL is not supported, falling back to 2D canvas.
e.init_webgl @ bokeh-0.12.13.min.js:sourcemap:1
```

Mac OS X 10.13.1
Chrome/63.0.3239.132
Firefox 57.0.4

**Comment by birdsarah** [comment] 2018-03-17 21:09
I've updated the title, and marked as bug.

Go to User Guide -> Speeding up with WebGL 

For 0.12.10 and then 0.12.11 onwards and I see this bug on Chrome and Firefox.

Am marking this one as other reportees are being directed here.

**Comment by birdsarah** [comment] 2018-03-17 21:12
Screenshot of Firefox on Linux 0.12.11

![screenshot from 2018-03-17 16-10-40](https://user-images.githubusercontent.com/1796208/37559989-05fb3dbe-29fe-11e8-99a5-3de2a26482ed.png)

**Comment by birdsarah** [comment] 2018-03-17 21:14
Screenshot of Chrome on OSX for 0.12.15dev3

<img width="1129" alt="screen shot 2018-03-17 at 4 12 14 pm" src="https://user-images.githubusercontent.com/1796208/37560007-31f1a7aa-29fe-11e8-97d9-e0c441ae4653.png">

**Comment by birdsarah** [comment] 2018-03-17 21:14
Figured it wasn't worth screenshotting all the possible combinations in between.

**Comment by bryevdv** [comment] 2018-03-17 21:34
WebGL is currently a mess. Not surprising since it is not really under automated test at the moment, and there is no one spending time maintaining it. It might be possible to get SauceLabs test running again to help with WebGL. They broke when we refactored the build to switch to TravisCI stages. I was not able to get them working again, despite trying. More preferable to me personally tho, would be getting locally runnable image diff tests based off Chrome Headless working, since CH supports webgl. 

Longer term I'd like to consider not supporting two backends, maybe basing BokehJS on ReGL for non-text rendering, but that's currently pie in the sky planning

**Closed** 2018-03-22 14:54 UTC
Labels: tag: webgl, type: bug

**Comment by AzraelDD** [comment] 2018-03-23 16:07
I was quite excited for this fix, so I have cloned and built Bokeh 0.12.15dev6+1.ga2949b2.
While my personal main project now becomes usable with webgl (thank you so much!!!), it is still not perfect, I'm afraid.
To me it seems like single figures work fine, as well as the first figure in a grid or a row. However, drawing outside of the plot area still happens with the other figures. Please consider the following example:

``` python
import numpy as np
import bokeh
from bokeh.plotting import figure
from bokeh.io import curdoc
from bokeh.layouts import row

#backend = 'canvas'
backend = 'webgl'

N = 10000
np.random.seed(0)  # Fix random

x = np.random.normal(0, np.pi, N)
y = np.sin(x) + np.random.normal(0, 0.2, N)

p1 = figure(title='Works fine', output_backend=backend)
p1.circle(x, y, fill_alpha=0.1)

p2 = figure(title='Compare for blurriness', output_backend=backend)
p2.circle(x, y, fill_alpha=0.1)

x = np.linspace(0, 10*np.pi, N)
y = np.cos(x) + np.sin(2*x+1.25) + np.random.normal(0, 0.001, (N, ))

p3 = figure(title='Drawing outside plot area happens', output_backend=backend)
p3.line(x, y, color="#22aa22", line_width=3)

curdoc().add_root(row(p1, p2, p3))
curdoc().title = backend+' '+bokeh.__version__
```
... But maybe there is more to this and it deserves a new issue:
- I also noticed that with webgl, all but the first figure in a grid or row have LOD-decimation activated (they turn grey while panning). So maybe this is somehow related?
- Moreover, there is the topic of blurriness: In 0.12.13 all webgl plots are a little bit blurred. (Its very subtle though, on my 1080p Monitor.) However, in 0.12.15dev only the first figure is blurred.
- My conclusion would be that only the first figure has webgl activated properly, because the other figures use a lod_factor and are not blurred.
- This is hard to measure, but I also feel like 0.12.15dev webgl is not as responsive as 0.12.13

I hope those explanations make somewhat sense!

**Comment by mattpap** [comment] 2018-03-23 16:24
> I also noticed that with webgl, all but the first figure in a grid or row have LOD-decimation activated 

webgl disables LOD, so if you see LOD-like behavior, webgl is off. This may be a recent regression in webgl initialization code.

**Comment by bryevdv** [comment] 2018-03-23 16:28
In any case that's a separate problem, so please file a new GH issue with this information

**Comment by mattpap** [comment] 2018-03-23 16:33
It's completely broken (#7681).
