### ISSUE TITLE
curdoc().add_root() seems only to work at the end of a callback

### ISSUE THREAD

**Issue by noppelmax** [bokeh/bokeh#8783] opened 2019-03-24 20:37 UTC
```
(ncview2) max@sam:~/git/praktClimaAnalyse$ python --version
Python 3.6.8 :: Anaconda, Inc.
(ncview2) max@sam:~/git/praktClimaAnalyse$ firefox --version
Mozilla Firefox 66.0
(ncview2) max@sam:~/git/praktClimaAnalyse$ bokeh --version
1.1.0dev11
(ncview2) max@sam:~/git/praktClimaAnalyse$ 
```

I wrote a minimal example for that.

```
import bokeh as bokeh

from bokeh.layouts import layout, widgetbox
from bokeh.models import Div
from bokeh.io import curdoc

def preDialog():
    global slVar
    divLoading = Div(text="Loading metadata...")
    curdoc().clear()
    l = layout([
    [widgetbox(divLoading)]
    ])
    curdoc().add_root(l)

    # Do something for a while
    for i in range(0,1000000):
        sum = i
        print(sum)

    slVar = bokeh.models.Select(title="Variable", options=["TR_stn","none"], value="TR_stn")
    btShow = bokeh.models.Button(label="show")
    btShow.on_click(mainDialog)

    curdoc().clear()
    l = layout([
    [widgetbox(slVar)],
    [widgetbox(btShow)]
    ])
    curdoc().add_root(l)

def mainDialog():
    # Showing a Loading Infotext
    divLoading = Div(text="Done...")
    curdoc().clear()
    l = layout([
        [widgetbox(divLoading)]
    ])
    curdoc().add_root(l)

def entry():
    btStart = bokeh.models.Button(label="start")
    btStart.on_click(preDialog)
    l = layout([
        [widgetbox(btStart)]
    ])
    curdoc().add_root(l)

entry()
```

The div containing "Loading metadata..." is not shown in the browser. When the call has finished the new layout is shown, but not inbetween.

Kind regards,
Max

**Comment by bryevdv** [comment] 2019-03-24 20:41
@noppelmax can you link the video, and platform browser in details o as well? I know from outside chat it is failing on 1.1.0dev11 but we need as much info as possible to reproduce. 

For reference, this code works for me 1.1.dev on OSX/Safari

**Comment by xavArtley** [comment] 2019-03-24 20:42
works for me v1.1.0dev10 on windows/chrome

**Comment by philippjfr** [comment] 2019-03-24 20:43
>For reference, this code works for me 1.1.0dev11 on OSX/Safari

+1

**Comment by noppelmax** [comment] 2019-03-24 20:44
[ https://cloud.vspace.one/s/3pcsFdpCo4x7BJ2]( https://cloud.vspace.one/s/3pcsFdpCo4x7BJ2)

I'm on Linux. Maybe that is the point?

**Comment by bryevdv** [comment] 2019-03-24 20:44
Also works for me on OSX/FF 66 as well. There is an error message emitted:

> 2019-03-24 13:43:57,129 error handling message Message 'EVENT' (revision 1) content: '{"event_name":"button_click","event_values":{"model_id":"1010"}}': RuntimeError('Set changed size during iteration')

But things still function as expected

**Comment by noppelmax** [comment] 2019-03-24 20:44
I get this error too

**Comment by bryevdv** [comment] 2019-03-24 20:45
> I'm on Linux. Maybe that is the point?

Possibly, I will have to get a Linux VM up an running at this point to look further (my old ones are gone in laptop wipe), so that will not be until later this week/next at least

**Comment by noppelmax** [comment] 2019-03-24 20:51
I'll also do some investigations the next days.

**Comment by bryevdv** [comment] 2019-04-13 17:45
@noppelmax can you try on linux with 1.1?

**Comment by bryevdv** [comment] 2019-04-13 18:33
Note that #8835 fixes the Runtime error message

**Comment by bryevdv** [comment] 2019-04-13 20:13
OK I have been procrastinating getting a Linux VM set up so I finally did this morning. I cannot reproduce any issue on Ubuntu 18.10 Chrome or FF, or on OSX, with 1.1. As mentioned the error message was fixed up elsewhere. So I will close this now. Please feel free to re-open with more information and specifics to reproduce if there is still a repeatable problem

**Closed by bryevdv** 2019-04-13 20:13 UTC
Labels: type: discussion
