### ISSUE TITLE
Using "reset" tool in Notebook unexpectedly resets the plot layout to defaults

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#5328] opened 2016-10-07 17:56 UTC
- Description of expected behavior and the observed behavior

If I create a figure in a notebook that is, say, 800x400, then I wouldn't expect the "reset" button to change that figure layout.  I expect the "reset" button to take me back to the original image that was first displayed on the screen.

Right now the reset button also resets the plot width and height.  At least when using the `bokeh.charts` API, as you can see in this short screencast (same effect in Chrome and Firefox):

http://screencast.com/t/ssde3cHFiY
- Self-contained example code that generates the issue (if possible)

The Notebook that demonstrates this can be found here: 

https://anaconda.org/safari-intro-ods/1-introduction-to-open-data-science/notebook
- Stack traceback and/or browser developer tools console output
- Software version information output by `bokeh info` command

0.12.2 on Mac

**Comment by ijstokes** [comment] 2016-10-07 18:05
Possible that this is related to one of #5294 #4865 #4857 #5185

**Comment by bryevdv** [comment] 2016-10-07 19:10
@ijstokes the tool originally did not reset width and height. It was changed to do that after many users repeatedly asked for that to be the behavior.

**Comment by bryevdv** [comment] 2016-10-07 19:12
@ijstokes that screencast requires flash, so I can't view it.

**Comment by ijstokes** [comment] 2016-10-19 13:40
@bryevdv I'd like to suggest that "reset" takes the image layout back to how it was originally plotted at page load, not back to plot layout defaults.  IOW, if as the Bokeh plot author I define a layout of 200x800 then the "reset" tool should "return" the image to 200x800.  If I add in a "resize" tool and the end user viewing it, in their web client, decides to use the corner image handle to drag the plot into a layout of 300x500, then when they click "reset" I believe it should go back to 200x800, not back to the global defaults of 400x400 (or whatever they are).

PS - if you can recommend a Mac based screencast recording tool I'll use that.

**Comment by bryevdv** [comment] 2016-10-19 14:03
This is a failure to communicate. As I said I can't view the videos you made (no flash player). When you said "Right now the reset button also resets the plot width and height" I think "of course, back to the original (user-supplied) width and height, that's what it does." If that's not what it is doing (i.e. it's resetting width and height to something other than the user-supplied width and height), that is a bug. The reset tool is only supposed to undo any canvas size changes made by the resize tool, and then only back to the original dimensions (not some defaults).

**Comment by bryevdv** [comment] 2016-12-10 20:35
@ijstokes can you confirm whether this only happens in the notebook?

**Comment by bryevdv** [comment] 2016-12-10 20:48
Also yes this is a dupe of #5185

**Closed by bryevdv** 2016-12-10 20:48 UTC
Labels: tag: component: bokehjs, type: bug
