### ISSUE TITLE
Plot renders glyphs outside axis area when webgl is used

### ISSUE THREAD

**Issue by renzop** [bokeh/bokeh#7572] opened 2018-02-26 10:37 UTC
When creating a line plot, the line are getting rendered outside the axis area. (See the screenshots)
It can be reproduced with the code from the examples library. Ithe issue only appears when output_backend == "webgl"
Ive tested line plots and scatter plot. same behaviour

It is less visible when the figure has a tiltle... see : [Examples](https://bokeh.pydata.org/en/latest/docs/user_guide/webgl.html) 

###Environment:
Macos Sierra
python 2.7.10
bokeh 0.12.14
chrome 64.0.3282.167 

```
from bokeh.plotting import figure, output_file, show

output_file("line.html")

p = figure(plot_width=400, plot_height=400)
p.output_backend = 'webgl'

# add a line renderer
p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=2)

show(p)

```

Theere is no output on the console. 

#### Screenshots or screencasts of the bug in action
With webgl:
<img width="446" alt="screen shot 2018-02-26 at 11 34 34" src="https://user-images.githubusercontent.com/8982565/36665950-491da6a0-1ae9-11e8-89d5-b1dd11a55be3.png">

wihtout wbgl
<img width="553" alt="screen shot 2018-02-26 at 11 34 57" src="https://user-images.githubusercontent.com/8982565/36665953-50def8d0-1ae9-11e8-83b0-6adcdfc34f20.png">

**Comment by mattpap** [comment] 2018-02-26 11:16
This seems to be a duplicate of issues #6867 and #7211 (which are basically the same issue). If you have anything to add, like relevant JS console output, please continue discussion there (#7211 has fair amount of feedback).

**Closed by mattpap** 2018-02-26 11:16 UTC
