### ISSUE TITLE
[BUG] HoverTool stops working in the area of a BoxAnnotation

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#14195] opened 2024-12-16 13:07 UTC
### Expected behavior

I expect, that a HoverTool is able to work with a BoxAnnotations in the background.

### Observed behavior

When hovering over the line in the area of the BoxAnnotation, the cursor changes from cross ("precision select") to an arrow with four arrows ("move") and at the edges to a two-sided arrow ("resize"). The HoverTool does not work in this area.

### Example code

```Python
from bokeh.layouts import grid
from bokeh.models import BoxAnnotation, HoverTool
from bokeh.plotting import figure, output_notebook, show
output_notebook()

def draw_figure(x, y, draw_box_annotation:bool = True):
    p = figure(height=300, width=300)
    lr = p.line(x, y)
    if draw_box_annotation:
        p.renderers.extend(
             [BoxAnnotation(fill_color='gray', fill_alpha=0.5, left=2, right=4)]
        )
    p.add_tools(HoverTool(tooltips=[("value", "$y")], renderers=[lr], mode='vline'))
    return p

x = [1,2,3,4,5]
y = [1,2,3,4,5]

show(grid([[draw_figure(x, y), draw_figure(x, y, draw_box_annotation=False)]]))
```

### Screenshots

![Image](https://github.com/user-attachments/assets/a7c36df4-9f0e-425c-bf2e-3bcc71581876)

<details><summary>technical details</summary>
### Software versions

Python version        :  3.12.4 (tags/v3.12.4:8e8a4ba, Jun  6 2024, 19:30:16) [MSC v.1940 64 bit (AMD64)]
IPython version       :  8.25.0
Tornado version       :  6.4.1
NumPy version         :  1.26.4
Bokeh version         :  3.6.2
BokehJS static path   :  [~\Envs\fbpinn\Lib\site-packages\bokeh\server\static](~/Envs/fbpinn/Lib/site-packages/bokeh/server/static)
node.js version       :  v20.17.0
npm version           :  10.8.2
jupyter_bokeh version :  4.0.5
Operating system      :  Windows-10-10.0.19045-SP0

### Browser name and version

Firefox 133.0.3

### Jupyter notebook / Jupyter Lab version

Jupyter Lab 4.2.3
</details>

**Comment by mattpap** [comment] 2024-12-16 13:54
This is a duplicate of #13980.

**Closed as duplicate by mattpap** 2024-12-16 13:54 UTC
Labels: reso: duplicate
