### ISSUE TITLE
Toolbar is not working in chrome v50

### ISSUE THREAD

**Issue by dcrystalj** [bokeh/bokeh#4351] opened 2016-05-22 10:04 UTC
No buttons are working for me in tool bar in all examples version `0.11.1` (latest). 
In version `0.10` wheel zoom scroll is working for sure.

I have ubuntu `16.04`, chrome `50`.  
In firefox it's working

**Comment by beojan** [comment] 2016-05-22 18:11
Same here, with Chromium 50

**Comment by birdsarah** [comment] 2016-05-22 21:44
Thank you both for the report.

We'll check it out ASAP.

On 5/22/16 11:12 AM, Beojan Stanislaus wrote:
>
> Same here, with Chromium 50
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/bokeh/bokeh/issues/4351#issuecomment-220847084>
>

-- 

*Sarah Bird*
*/Developer, Bokeh/*

Continuum Analytics <http://continuum.io>

**Comment by birdsarah** [comment] 2016-05-22 21:46
@beojan - are you also on Ubuntu? On OSX with Chrome 50, I'm not having the same issue.

Also, can you both point to an example online with this issue. For example, do these work: http://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html

**Comment by beojan** [comment] 2016-05-22 21:47
Archlinux actually.

None of those work. Neither do the examples linked from http://bokeh.pydata.org/en/latest/.

**Comment by birdsarah** [comment] 2016-05-22 21:48
Perfect - thanks!

**Comment by dcrystalj** [comment] 2016-05-22 22:04
if you want to see the problem here:
![anim](https://cloud.githubusercontent.com/assets/1460727/15456730/d071e7b8-2079-11e6-9f82-0170640649b0.gif)

**Comment by birdsarah** [comment] 2016-05-22 22:13
Oh! Thanks so much for posting the gif. 

I believe this is a known issue. 

Can you try the workaround here: http://bokehplots.com/pages/faqs.html - see Troubleshooting at the bottom.

**Comment by dcrystalj** [comment] 2016-05-22 22:19
if I set chrome://flags/#touch-events to disabled it is working magically. But
i wonder why it is working on version 0.10.  
Shouldnt this be solved the other way around?  
  

On May 23 2016, at 12:13 am, Sarah Bird &lt;notifications@github.com&gt;
wrote:  

> Oh! Thanks so much for posting the gif.

>

> I believe this is a known issue.

>

> Can you try the workaround here: <http://bokehplots.com/pages/faqs.html> \-
see Troubleshooting at the bottom.

>

> —  
You are receiving this because you authored the thread.  
Reply to this email directly or [view it on GitHub](https://github.com/bokeh/b
okeh/issues/4351#issuecomment-220859787)![](https://github.com/notifications/b
eacon/ABZJ9xxmN5LZpPjmTqIK0QriVDVBpIu8ks5qENUNgaJpZM4Ij9NK.gif)

**Comment by birdsarah** [comment] 2016-05-22 22:22
> Shouldnt this be solved the other way around?

I'm not sure what that means, but yes, this is a known bug, that we really want to solve, but is in a long line. We'd love your help if that's something you can do.

**Comment by birdsarah** [comment] 2016-05-22 22:23
Duplicate of #1848.

**Closed by birdsarah** 2016-05-22 22:23 UTC
Labels: reso: duplicate

**Comment by birdsarah** [comment] 2016-05-22 22:28
Hah! This was wonderfully serendipitous timing. I've been working on a completely separate issue, but I had noticed something off, and I think I just realized that it's the cause of this!!! I'll keep you updated.

**Comment by damianavila** [comment] 2016-05-25 23:06
> I think I just realized that it's the cause of this!!! I'll keep you updated.

I would love to hear about that...

**Comment by birdsarah** [comment] 2016-05-27 07:36
@damianavila - fix merged: https://github.com/bokeh/bokeh/pull/4353
