### ISSUE TITLE
Bokeh not embedding plot in Django app sea_surface example [BUG]

### ISSUE THREAD

**Issue by msouff** [bokeh/bokeh#10434] opened 2020-08-26 21:20 UTC
OS Ubuntu 2018
Bokeh server version 2.1.0 and up (running with Django channels)
Django 2.2.8
Django channels 2.4.0
Python version 3.7.8
Browser: Tested on Chrome and Firefox

When using versions 2.1.0 and up, the django server_embed sea_surface example (127.0.0.1/sea_surface) fails to embed the graph:

The example using panel (127.0.0.1/shape_viewer) works fine. The sea_surface_with_template example (127.0.0.1/sea_surface_with_template) also works.

I'd attach code but these are the basic examples found on examples/howto/server_embed/django_embed and they can be reproduced from there.

![image](https://user-images.githubusercontent.com/17328135/91351822-259f3680-e7a6-11ea-81d4-a847e5616078.png)

I have a few apps that use the way shown in the sea_surface example and so they are not working on 2.1.0 or up.

Thanks in advance for your help.

**Comment by bryevdv** [comment] 2020-08-26 21:46
@msouff  please provide all the information asked for, OS, browser, etc. E.g his may be a duplicate of #10431 but you have not given enough context to determine that.

**Comment by msouff** [comment] 2020-08-26 22:09
@bryevdv I just added more info. Thanks.

**Comment by mattpap** [comment] 2020-08-26 22:17
ref https://github.com/holoviz/panel/issues/1552 (variation on issue #10412).

**Comment by msouff** [comment] 2020-08-26 22:38
Yup, I can confirm that I saw the same behavior @philippjfr reported in that issue with the _embed_items function and the docs_json appearing to be null.

**Closed** 2020-08-31 16:49 UTC
Labels: reso: completed, tag: django, type: bug
