### ISSUE TITLE
Problem when categorical item is duplicated

### ISSUE THREAD

**Issue by luk-f-a** [bokeh/bokeh#8026] opened 2018-06-25 20:53 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh: 0.13
Python: Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
IPython 6.4.0 
The version of the notebook server is: 5.4.0
OS: Linux Mint 18
Browser: Chromium Version 62.0.3202.94

#### Description of expected behavior and the observed behavior
When a categorical item is duplicated the plot will silently fail. Only error message shown us in javascript console and here there are thousands of error, an ever increasing amount of them that consumes 100% of CPU resources.

Expected behaviour:
If a duplicated categorical item is such a big problem at JS level, there should be a validation performed at Python level. JS level problems would ideally not enter an endless loop that consumes all CPU resources.

#### Complete, minimal, self-contained example code that reproduces the issue
Example based on https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html
with a minimal modification to create a duplicated category.

```
from bokeh.io import show, output_file, output_notebook
from bokeh.plotting import figure

#output_file("bars.html")
output_notebook()
fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Apples','Strawberries']

p = figure(x_range=fruits, plot_height=250, title="Fruit Counts",
           toolbar_location=None, tools="")

p.vbar(x=fruits, top=[5, 3, 4, 2, 4, 11, 6], width=0.9)

p.xgrid.grid_line_color = None
p.y_range.start = 0

show(p)

```
Observed behaviour:
There's no stack traceback.  JavaScript console output shows thousands (ever increasing) amount of errors saying

bokeh-0.13.0.min.js:sourcemap:31 Uncaught Error: duplicate factor or subfactor: Draw
    at m (bokeh-0.13.0.min.js:31)
    at t._init (bokeh-0.13.0.min.js:31)
    at t.initialize (bokeh-0.13.0.min.js:31)
    at t.u.finalize (bokeh-0.13.0.min.js:31)
    at bokeh-0.13.0.min.js:31
    at _ (bokeh-0.13.0.min.js:31)
    at _ (bokeh-0.13.0.min.js:31)
    at _ (bokeh-0.13.0.min.js:31)
    at _ (bokeh-0.13.0.min.js:31)
    at Function.P._initialize_references_json (bokeh-0.13.0.min.js:31)

The error count keeps increasing and consumes 100% CPU.

Expected behaviour:
There should an error shown at python level. And definitely should not enter into an error loop that consumes 100% CPU.

**Comment by bryevdv** [comment] 2018-06-25 21:00
This is dupe of #3322 which was closed in https://github.com/bokeh/bokeh/pull/8022

**Closed by bryevdv** 2018-06-25 21:00 UTC
