### ISSUE TITLE
Get a png or jpeg image instead of html file

### ISSUE THREAD

**Issue by sagarrakshe** [bokeh/bokeh#3381] opened 2015-12-21 13:14 UTC
I am trying to create images from data, but I don't need interactive images, just `png` images from the data.
I didn't get any way to do this using `bokeh`.

**Comment by bryevdv** [comment] 2015-12-27 04:38
dupe of #538

**Comment by bryevdv** [comment] 2015-12-27 04:39
@sagarrakshe this is still an open feature request, we are evaluating different technical options. There is the "preview save tool" that can generate PNG, but it requires active user interaction (to click a button, right click->save as, etc)

**Closed** 2015-12-27 04:40 UTC
Labels: reso: duplicate, type: discussion
