### ISSUE TITLE
[BUG] Wedge plot can't be updated.

### ISSUE THREAD

**Issue by marcschulze** [bokeh/bokeh#12489] opened 2022-10-14 23:15 UTC
### Software versions

Python version      :  3.10.4 (tags/v3.10.4:9d38120, Mar 23 2022, 23:13:41) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.2.0
Tornado version     :  6.1
Bokeh version       :  2.4.3
BokehJS static path :  C:\Users\Marc\AppData\Local\Programs\Python\Python310\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19043-SP0

### Browser name and version

Firefox 105.0.3

### Jupyter notebook / Jupyter Lab version

notebook         : 6.4.10

### Expected behavior

Update the wedge plot when source data are changed.

### Observed behavior

Wedge plot is only updated when hover data of hover tool was displayed. If hover tool is disabled, there are no updates of the plot. 

### Example code

```Python
import pandas as pd
from bokeh.plotting import show, figure, output_notebook
from bokeh.models import CustomJS, Slider, Column
from bokeh.palettes import Plasma
from bokeh.transform import cumsum
from math import pi

vals = [20, 100, 50]
names = ["Agnostic", "Competetive", "Loyalist"]

def data_generator(names, vals, f):
    data = pd.DataFrame([[name, val * f] for name, val in zip(names, vals)], columns=['name', 'value'])
    return data

f_start = 30
data = data_generator(names, vals, f_start)

data['angle'] = data['value']/data['value'].sum() * 2*pi 
data['color'] = Plasma[len(data)]

p = figure(plot_height=350, title="Loyalty Breakout", toolbar_location=None,
            tools="hover", tooltips="@segment: @value",
            x_range=(-0.5, 1.0))

wedge = p.wedge(x=0, y=1, radius=0.4,
        start_angle=cumsum('angle', include_zero=True), end_angle=cumsum('angle'),
        line_color="white", fill_color='color', legend_field='name', source=data)

update = CustomJS(args=dict(wedge=wedge, vals=vals, xr=p.x_range), code="""
    var f = cb_obj.value;
    var scaled = Array.from(vals, (x, i) => i==0?x*f/10:x)
    var sum = scaled.reduce((a, b) => a + b, 0)
    var angles =  Array.from(scaled, (x) => x/sum * 2 * Math.PI)

    wedge.data_source.data['angle'] = angles
    wedge.data_source.data['value'] = scaled
    wedge.data_source.change.emit()
""")

lookback_slider = Slider(start=0, end=180, value=f_start, step=1, title="Lookback (days)")
lookback_slider.js_on_change('value',update)

p.axis.axis_label=None
p.axis.visible=False
p.grid.grid_line_color = None

show(Column(lookback_slider, p))
```

**Comment by bryevdv** [comment] 2022-10-15 01:48
@marcschulze using `emit` is not the best way to trigger data updates, and at this point I would even say it is discouraged. There is already an open issue to remove demonstration of this method from the docs entirely: https://github.com/bokeh/bokeh/issues/12180

The best practice is always to set the entire property value, not to update things "in place". Here is a working version. I will close this as a dupe of #12180   

```
update = CustomJS(args=dict(source=wedge.data_source, vals=vals, xr=p.x_range), code="""
    const f = cb_obj.value;
    const scaled = Array.from(vals, (x, i) => i==0 ? x*f/10 : x)
    const sum = scaled.reduce((a, b) => a + b, 0)
    const angles =  Array.from(scaled, (x) => x/sum * 2 * Math.PI)
    const data = {
        color: source.data.color,
        angle: angles,
        value: scaled,
    }
    source.data = data
""")
```

**Closed by bryevdv** 2022-10-15 01:48 UTC
Labels: TRIAGE

**Comment by marcschulze** [comment] 2022-10-15 19:12
Thank you @bryevdv for this useful hint and yes this bug report is obsolete.
