### ISSUE TITLE
Geo: setting axis ranges yield unexpected results

### ISSUE THREAD

**Issue by mjmare** [bokeh/bokeh#6098] opened 2017-04-05 10:38 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant pacakges)
python 3.6.1, OSX, bokeh 0.12.4

#### Description of expected behavior and the observed behavior
I first interactively determined the axis ranges I'd like to have. However when using these values does not show the selected rectangle on the map. I'd expect slight discrepancies but not this large. 
See screenshots: intended.jpg shows the desired map area (note axes). When setting these ranges in code I get actual.jpg, which is obviously incorrect. 

#### Complete, minimal, self-contained example code that reproduces the issue
```
import pandas as pd
import numpy as np

from bokeh.io import output_file, show
from bokeh.plotting import figure
from bokeh.tile_providers import WMTSTileSource

from geopy.geocoders import Nominatim


output_file('geo.html')
x_range = (4.8e+05, 5.8e+05)
y_range = (6.860e+06, 6.980e+06)

fig = figure(tools='pan, wheel_zoom', x_range=x_range, y_range=y_range)
fig.axis.visible = True

url = 'http://a.basemaps.cartocdn.com/dark_all/{Z}/{X}/{Y}.png'
# attribution = "Map tiles by Carto, under CC BY 3.0. Data by OpenStreetMap, under ODbL"
attribution = None

fig.add_tile(WMTSTileSource(url=url, attribution=attribution), alpha=0.8)

show(fig)
```
#### Screenshots or screencasts of the bug in action
![intended](https://cloud.githubusercontent.com/assets/1711378/24701889/8c93f2de-19fc-11e7-9476-59cffb04575c.jpg)
![actual](https://cloud.githubusercontent.com/assets/1711378/24701890/8cb28910-19fc-11e7-8e48-4c4c5c2284fd.jpg)

**Comment by bryevdv** [comment] 2017-10-14 00:22
dupe of #6655 (keeping the other issue)

**Closed by bryevdv** 2017-10-14 00:22 UTC
