### ISSUE TITLE
line_color=None doesn't work in scatter()

### ISSUE THREAD

**Issue by kkdd** [bokeh/bokeh#8243] opened 2018-09-13 12:54 UTC
Hello,
I noticed that ```line_color=None``` doesn't work in ```scatter()```.  I observes that the workaround about this issue seems as follows:

```python
def plotData(xdat, ydat, colors):
    output_file("loci.html", title="loci plot")
    p = figure(output_backend="webgl")
    p.scatter(xdat, ydat, fill_color=colors, line_color=colors)
    save(p)
```

# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

**Comment by bryevdv** [comment] 2018-09-13 15:11
Cannot reproduce any problem. Example output below, both with `line_color="red"` and `line_color=None`, passed to `scatter`, behaving exactly as intended:

<img width="616" alt="screen shot 2018-09-13 at 08 09 38" src="https://user-images.githubusercontent.com/1078448/45497393-87d30e00-b72c-11e8-8723-58ce50a3b09a.png">
<img width="618" alt="screen shot 2018-09-13 at 08 09 49" src="https://user-images.githubusercontent.com/1078448/45497394-87d30e00-b72c-11e8-9b34-b967981ae50e.png">

Since the issue did not contain any of the requested information or code to reproduce, closing as `norepro`

**Closed by bryevdv** 2018-09-13 15:11 UTC
