### ISSUE TITLE
[BUG] Wedge/arc radius does not match y-axis

### ISSUE THREAD

**Issue by Aaron-560** [bokeh/bokeh#10494] opened 2020-09-14 14:55 UTC
#### Versions
Bokeh 2.2.1
Python 3.8.0
Ubuntu 18.04.5 LTS
Firefox 80.0.1 (64-bit) / Chromium 85.0.4183.83

#### Expected and observed behavior
Expected: When plotting a wedge (or annular_wedge, or arc) the radius should be constant and match the radius (or outer_radius) argument, and this should be consistent with the axis markings.
Observed: The radius of the wedge in the y-dimension is about 10% smaller than expected according to the axis markings. (It appears to my eye that the wedge is correctly sized (i.e. it is constant radius) and the y-axis is incorrect.)

#### Screenshot
![bokeh_wedge_radius_axis_bug](https://user-images.githubusercontent.com/58945774/93096925-df4e4080-f69c-11ea-943b-6f4dac5da6d4.png)
This is firefox, looks identical in chromium to me. Same effect when plotting annular_wedge and arc. (ellipse and vbar seem fine)

#### Example code
```
from bokeh.plotting import figure, show

p = figure()

pi = 3.142

p.wedge(
    x=0, y=0,
    radius=1,
    start_angle=2*pi,
    end_angle=0,
    direction='clock',
)

# p.annular_wedge(
#     x=0, y=0,
#     inner_radius=0.5,
#     outer_radius=1,
#     start_angle=2*pi,
#     end_angle=0,
#     direction='clock',
# )

# p.arc(
#     x=0, y=0,
#     radius=1,
#     start_angle=2*pi,
#     end_angle=0,
# )

show(p)
```

#### Browser JavaScript console output
```
[bokeh] setting log level to: 'info' bokeh-2.2.1.min.js:188:1389
[bokeh] document idle at 83 ms bokeh-2.2.1.min.js:166:1258
```

Thanks, and please let me know if there is anything else I should supply.

**Comment by bryevdv** [comment] 2020-09-14 15:30
dupe of #517

**Closed by bryevdv** 2020-09-14 15:30 UTC
Labels: TRIAGE

**Comment by bryevdv** [comment] 2020-09-14 15:32
@Aaron-560 pass `match_aspect=True` to `figure` if you need to draw "large" circles, with radii specified in data-space units.

**Comment by Aaron-560** [comment] 2020-09-14 15:45
@bryevdv Thank you

**Comment by Aaron-560** [comment] 2020-09-30 11:41
Bit late here but want to note that passing `match_aspect=True` to `figure` did not fix this problem. I've moved on without a solution for now.

**Comment by bryevdv** [comment] 2020-09-30 20:22
@Aaron-560 You will have to elaborate, with `match_aspect` set all the examples above render as expected exactly touching the borders of a (1,-1) square with Bokeh 2.2.1

<img width="594" alt="Screen Shot 2020-09-30 at 1 20 35 PM" src="https://user-images.githubusercontent.com/1078448/94735699-01dc8c80-0320-11eb-8da1-f97404e08f82.png">
<img width="438" alt="Screen Shot 2020-09-30 at 1 20 56 PM" src="https://user-images.githubusercontent.com/1078448/94735701-030db980-0320-11eb-98f7-495168e9a1b3.png">
<img width="461" alt="Screen Shot 2020-09-30 at 1 21 18 PM" src="https://user-images.githubusercontent.com/1078448/94735706-043ee680-0320-11eb-824f-b513e345f7bd.png">

**Comment by bryevdv** [comment] 2020-09-30 20:24
Note: I had to manually zoom out to see the above images, because these glyphs are not yet fully auto-ranging, but that is a separate issue.
