### ISSUE TITLE
DeserializationError when editing Data Table

### ISSUE THREAD

**Issue by pmicheletty** [bokeh/bokeh#7417] opened 2018-01-16 15:37 UTC
Current environment:
- Bokeh 0.12.14dev3 (although I think the same error occurs in 0.12.13)
- Python 3.6
- Windows 10
- Google Chrome

When editing or clicking on cells in a data table bokeh will display a `DeserializationError`:
![image](https://user-images.githubusercontent.com/9287000/34996773-dda6100e-fa97-11e7-8ef2-e8f959bb618c.png)

This can be tested with the [data_table.py](https://github.com/bokeh/bokeh/blob/53cd93bea4168f87d296ad8a0b9bcd7d18e886ae/examples/models/server/data_tables.py) example on the bokeh github. Open that server up and then click on a cell and the error should appear. Not sure where this is coming from, but I do believe it happened somewhere after 0.12.10 (which doesn't produce the error).

**Comment by mattpap** [comment] 2018-01-16 16:02
Looks like a typed array.

**Comment by bryevdv** [comment] 2018-01-30 22:57
Binary array transport landed in `0.12.9` so it's not directly that.

**Comment by bryevdv** [comment] 2018-01-30 23:03
Also, that example is gone (all the bad examples of `bokeh.client` "app outside the server" were removed) but here is an updated `export_csv` that shows the issue:
```
import pandas as pd

from bokeh.layouts import row, widgetbox
from bokeh.models.widgets import Select, MultiSelect
from bokeh.plotting import curdoc, figure
from bokeh.models import ColumnDataSource, LabelSet
from bokeh.models.ranges import FactorRange
from bokeh.io import show

df = pd.DataFrame(data={
        'category': ['e', 'e', 'f', 'f'],
        'subcategory': ['a', 'b', 'c', 'd'],
        'number': [1, 2, 3, 4],
        'number2': [5, 6, 7, 8]
        })

df['cat_sub'] = list(zip(df.category, df.subcategory))

source = ColumnDataSource(df)

p = figure(plot_width=800,
           y_range=FactorRange(factors=list(df.cat_sub)),
           title='sweet', plot_height=500)

h1 = p.hbar(right="number", y="cat_sub", color='darkgrey',
            height=0.8, source=source)

labels = LabelSet(
        text='number', text_font_size='9pt', level='glyph',
        x='number', y='cat_sub', x_offset=3, y_offset=-6.5,
source=source)

p.add_layout(labels)


def update_source():
    df2 = df.copy()
    df3 = df2[
            df2.category.isin(cats.value)
            & df2.subcategory.isin(subcats.value)]
    print(df3)
    df4 = df3.reindex(columns=['category', 'subcategory', nums.value])
    print(df4)
    df4['cat_sub'] = list(zip(df4.category, df4.subcategory))
    source.data = source.from_df(df4)
    print(source.data)


def update_glyph():
    h1.glyph.right = nums.value
    labels.text = nums.value
    labels.x = nums.value


def update(attr, old, new):
    update_source()
    update_glyph()
    r.children[1] = update_glyph()


catlist_u = df['category'].unique().tolist()
subcatlist_u = df['subcategory'].unique().tolist()

cats = MultiSelect(title='Category', value=['f'], options=catlist_u)

subcats = MultiSelect(title='Subcategory', value=['a'],
                      options=subcatlist_u)

nums = Select(title='Value', value='number2', options=['number', 'number2'])

cats.on_change('value', update)
subcats.on_change('value', update)
nums.on_change('value', update)

w = widgetbox([cats, subcats, nums])

r = row([w, p], sizing_mode="scale_width")

curdoc().add_root(r)
curdoc().title = "test"
```

**Comment by mattpap** [comment] 2018-01-30 23:06
I was able to reproduce this with some app examples.

**Comment by bryevdv** [comment] 2018-01-30 23:22
FYI a potential workaround is to use python lists for a datatable source:
```
def update():
    current = df[(df['salary'] >= slider.value[0]) & (df['salary'] <= slider.value[1])].dropna()
    source.data = {
        'name'             : list(current.name),
        'salary'           : list(current.salary),
        'years_experience' : list(current.years_experience),
    }
```

**Comment by smilerz** [comment] 2018-03-07 19:54
Note to anyone that uses the workaround @bryevdv suggested: 
You have to either drop or fill or otherwise change any NaN or NaT values in your DataFrame before assigning them to the list. 

Otherwise the workaround seemed to correct the issue I was having.

**Comment by Karel-van-de-Plassche** [comment] 2018-06-17 20:19
Just to let you know this is still there in `0.13.0dev11'. A minimal(er) example:

``` python
import numpy as np

from bokeh.models import ColumnDataSource
from bokeh.io import curdoc, output_notebook, push_notebook, show
from bokeh.models.widgets import DataTable, TableColumn, StringFormatter

data = dict(
X = np.linspace(0, 10), # Wrap with list() to remove the unhandled error
Y = np.linspace(10, 20) # Wrap with list() to remove the unhandled error
)
source = ColumnDataSource(data)

columns = [ 
TableColumn(field="X", title="X",formatter=StringFormatter(font_style="bold",text_color="midnightblue")),TableColumn(field="Y", title="Y",formatter=StringFormatter(font_style="bold",text_color="midnightblue")),
]

data_table = DataTable(source=source,
                       columns=columns,
                       fit_columns=True,
                       width=850, height=280,       
                       editable=True)

curdoc().add_root(data_table)
```

**Closed** 2018-10-11 17:21 UTC
Labels: tag: component: bokehjs, tag: regression, type: bug
