### ISSUE TITLE
[BUG] Box Annotation example not working

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#13529] opened 2023-11-15 04:46 UTC
### Software versions

Current documentation, https://docs.bokeh.org/en/latest/docs/examples/basic/annotations/box_annotation.html https://docs.bokeh.org/en/latest/docs/user_guide/basic/annotations.html#box-annotations

### Expected behavior

The examples for box annotation should display a box annotation. 

### Observed behavior

The examples don't show the box annotation.

### Example code

```Python
Go to https://docs.bokeh.org/en/latest/docs/examples/basic/annotations/box_annotation.html or https://docs.bokeh.org/en/latest/docs/user_guide/basic/annotations.html#box-annotations to see the example where the box annotation is missing
```

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/39711796/72373d2e-ed09-48a5-869e-d2cfc459cb1d)

**Comment by mosc9575** [comment] 2023-11-15 08:15
I think this is a duplicate of #13432.

**Closed as completed by mosc9575** 2023-11-15 08:15 UTC
Labels: reso: duplicate
