### ISSUE TITLE
When plotting a line using a CDSView and non-consecutive indexes on IndexFilter, some segments are plotted instead of a line

### ISSUE THREAD

**Issue by chesucr** [bokeh/bokeh#7594] opened 2018-03-04 12:42 UTC
Is this the expected behaviour? Or is it going to be fixed in the future?
```
from bokeh.models import ColumnDataSource, CDSView, IndexFilter
from bokeh.layouts import column
from bokeh.plotting import curdoc, figure
import numpy as np

plot_1 = figure(
    width=400,
    height=400,
)

x = list(range(0,10))
y = np.random.random_integers(200, size=(10))

source = ColumnDataSource(data=dict(x=x, y=y))

selection = list(np.random.random_integers(100, size=(20)))
view = CDSView(
    source=source,
    filters=[IndexFilter([0, 1, 5, 6])]
)

lr = plot_1.line(
    x='x',
    y='y',
    line_color='red',
    line_width=3,
    line_alpha=1.0,
    source=source,
    view=view,
)
lr.nonselection_glyph = None

curdoc().add_root(column([plot_1]))
```
![segments](https://s10.postimg.org/ebnvnc3fd/line_cdsview.png)

Bryan answered me this on Gitter:

> lines have some sub optimal behaviour with selections, which is somewhat similar so I would not be surprised of issues with views too. The underlying issue is that the low level line renderer needs to be smarter about how to handle such things but it will add a lot of complexity so it has not been done yet

**Comment by clairetang6** [comment] 2018-03-09 05:26
Hi @chesucr, this is a duplicate of [this issue](https://github.com/bokeh/bokeh/issues/7070). See [this comment](https://github.com/bokeh/bokeh/issues/7070#issuecomment-338092176) for an explanation of why this occurs. I'm going to close this issue, but feel free to add more comments to the other issue!

**Closed by clairetang6** 2018-03-09 05:26 UTC
