### ISSUE TITLE
Investigate disabling user-select

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#4295] opened 2016-05-07 17:58 UTC
Recently, sometimes Bokeh plots get annoyingly "selected" i.e. are blued out like selected text. I believe this is because user-select needs to be disabled, something like:

```
this.$el.css({
  "user-select": "none",
  "ms-user-select": "none",
  "moz-user-select": "none",
  "khtml-user-select": "none",
  "webkit-user-select": "none"});
```

**Comment by bryevdv** [comment] 2016-05-09 23:24
Specifially trying to prevent this occurrence: 

<img width="553" alt="screen shot 2016-05-09 at 1 18 05 pm" src="https://cloud.githubusercontent.com/assets/1078448/15131161/97845dd4-1645-11e6-8b0a-29ba62c8d769.png">

Which seems pretty easy to do by dragging across the non-canvas parts of the plot in some situations. 

@birdsarah any input?

**Comment by birdsarah** [comment] 2016-05-10 02:25
Definitely agree and have seen the problem myself.

My first thought was that your solution might have unintended consequences, which I would need to test / think through more.

**Comment by birdsarah** [comment] 2016-05-10 02:25
not sure you need all those vendor-prefixes for modern browsers.

**Comment by almarklein** [comment] 2016-05-13 21:36
Strangely, I cannot reproduce the blue selection on Windows (on any browser).

**Comment by almarklein** [comment] 2016-05-14 11:29
Did some more testing:
* Windows + Firefox: no problems
* Windows + Chrome: only some blue borders around canvas
* Windows + Edge: no problems
* Ubuntu Linux + Firefox: blue overlay
* Ubuntu Linux + Chrome: blue overlay
* OSX + Firefox: no problem
* OSX + Safari: blue overlay
* OSX + Chrome: blue overlay

**Comment by almarklein** [comment] 2016-06-02 13:52
I just did some testing with current master. It works on more systems, because `-webkit-user-select: none` is set on the `bk-canvas-wrapper` (happened during layout work?). If we also add `-webkit-user-select:none` to `bk-toolbar-wrapper` it should everywhere (where it can work). This should be easy to do, except that I seem unable to find where the `-webkit-user-select` is currently set ??

Also, slider widgets are currently selectable. Is that something we want to disable too? Seems to be possible by applying the same CSS to `bk-widget`, though that might have other implications (maybe some widgets should stay selectable). Otherwise `bk-slider-parent` also seems to work.

**Comment by bryevdv** [comment] 2016-07-02 16:56
I added `webkit-user-select: none` by hand to the toolbar wrapper and it worked. Suggest adding a CSS class
```
.bk-unselectable {
  -moz-user-select: none;
  -webkit-user-select: none;
  -ms-user-select: none;
}
```
to help with this. I know there is a "bootstrap" one but ditching bootstrap is a long term dream

**Comment by almarklein** [comment] 2016-07-08 14:38
@bryevdv can you still reproduce this? I just tried, but I cannot seem to select the toolbar anymore. Would be great if it was now fixed, except that I don't understand how it's done :)

**Comment by bryevdv** [comment] 2016-07-08 15:19
I believe so. Easiest way: activate lasso too and drag anywhere outside central plot area

**Comment by bryevdv** [comment] 2017-02-01 16:30
NoUISlider might fix this, worth checking that

**Comment by StevenCHowell** [comment] 2017-02-05 04:07
> I believe so. Easiest way: activate lasso too and drag anywhere outside central plot area

I just tried this using `chromium-browser` on Ubuntu 14.04.  I did not see the blue highlight.  I did have an issue in a jupyter notebook where I activated the lasso tool, drug it out of the plot above into some code (or earlier cell's output, just so something was highlighted) then released; after doing this, when I tried to click in the plot again, it was as if I was trying to drag and drop the highlighted region.  I could recover so I could interact with the plot by selecting another tool, e.g., select the pan tool, then re-select the lasso_select tool.

Not sure if this is exactly what you are concerned about but it seems similar.

**Comment by canavandl** [comment] 2017-03-23 16:03
Using Safari 10.10.3 on OSX (Bokeh 0.12.5rc1), it's possible to highlight the toolbar icons. So any solution should also include the toolbar elements as well

**Comment by bryevdv** [comment] 2017-04-27 23:26
I can't seem to select the plot area anymore but I can select the toolbar. Slightly annoying but can wait a bit longer.

**Comment by bryevdv** [comment] 2017-07-03 20:10
important polish detail, but can be deferred again

**Closed** 2017-07-16 17:25 UTC
Labels: tag: component: bokehjs, type: bug
