### ISSUE TITLE
Embedded bokeh app in Jupyter Notebook from remote location

### ISSUE THREAD

**Issue by msalvaris** [bokeh/bokeh#6678] opened 2017-07-26 20:41 UTC
I have been looking at the example of running a bokeh app embedded in Jupyter Notebook. I am able to run it locally but when I try to run the same example with the server being in a remote location it doesn't work. I have tried various permutation of the URL. I have even tried creating a tunnel but still no luck. It seems to me that looking at the error it is expecting things to be running on localhost (127.0.0.1:42372/autoload.js)? Any help would be greately appreciated.

OS:Ubuntu 16.04
Browser: Chrome, Edge, Firefox
Python: 2.7.13
Bokeh Version: 0.12.5

Logs from Chrome:

127.0.0.1:42372/autoload.js?bokeh-autoload-element=e887e209-f173-4d18-a249-…bokeh-app-path=/&bokeh-absolute-url=http://127.0.0.1:42372&_=1501083730439 Failed to load resource: net::ERR_CONNECTION_REFUSED
main.min.js:12406 Loading extension: jupyter-js-widgets/extension
:9999/nbextensions/jupyter-js-widgets/extension.js?v=20170726151321:148 loaded widgets
:9999/nbextensions/jupyter-js-widgets/extension.js?v=20170726151321:14530 Widget backend and frontend versions are compatible
main.min.js:23577 Kernel: kernel_restarting (f2f54002-72b3-4134-b35d-0c2cefbc9b62)
main.min.js:23577 Kernel: kernel_created (f2f54002-72b3-4134-b35d-0c2cefbc9b62)
main.min.js:23933 Starting WebSockets: ws://ms4deep.southcentralus.cloudapp.azure.com:9999/api/kernels/f2f54002-72b3-4134-b35d-0c2cefbc9b62
main.min.js:23577 Kernel: kernel_connected (f2f54002-72b3-4134-b35d-0c2cefbc9b62)
main.min.js:23577 Kernel: kernel_ready (f2f54002-72b3-4134-b35d-0c2cefbc9b62)
:9999/nbextensions/jupyter-js-widgets/extension.js?v=20170726151321:14530 Widget backend and frontend versions are compatible
autoload.js Failed to load resource: net::ERR_CONNECTION_REFUSED

**Comment by bryevdv** [comment] 2017-07-26 20:44
This is a dupe of #6598 resolved in https://github.com/bokeh/bokeh/pull/6609

**Closed by bryevdv** 2017-07-26 20:44 UTC
