### ISSUE TITLE
Unexpected typed array Float64Array

### ISSUE THREAD

**Issue by raqsilva** [bokeh/bokeh#9257] opened 2019-10-02 09:26 UTC
Hi,

I have a couple of plots working perfectly in Chrome Version 74 but not appearing in IE 11 due to an error: **SCRIPT5022: Unexpected typed array class: function Float64Array() { [native code] } . bokeh-1.3.4.min.js (41,15939)**

These plots are created with Python 3.6, bokeh==1.3.4.

I have added the following as scripts tags:
http://cdn.pydata.org/bokeh/release/bokeh-1.3.4.min.js
http://cdn.pydata.org/bokeh/release/bokeh-widgets-1.3.4.min.js
http://cdn.pydata.org/bokeh/release/bokeh-tables-1.3.4.min.js
http://cdn.pydata.org/bokeh/release/bokeh-api-1.3.4.min.js
plus a bokeh css.

Figures are created and then dumped on the python side (`json.dumps(json_item(plot))`) to be picked up by JS with: 
```
let item = JSON.parse(data.image_b64);
let embed_item = Bokeh.embed.embed_item(item, "bokeh_plot");
return(<React.Fragment><div id="bokeh_plot" class='bk bk-root'></div>{embed_item}</React.Fragment>)
```

Hope you can help,
Thanks in advance,
Raquel

**Comment by bryevdv** [comment] 2019-10-02 14:32
@raqsilva We will need more information, including a reproducing example and more detailed platform information. IE has supported typed arrays since IE *10*

https://caniuse.com/#feat=mdn-javascript_builtins_float64array

So offhand I don't have any idea why you might be seeing such a message.

**Comment by bryevdv** [comment] 2019-10-02 14:34
Also, please repeat this with the unminified versions of the URLs so that the reported line numbers are more meaningful

**Comment by mattpap** [comment] 2019-10-02 14:40
This errors originates from flatbush: 

https://github.com/mourner/flatbush/blob/e75b1e932ae295fe90d4fe3546d76535acab1dea/index.js#L54-L56

**Comment by raqsilva** [comment] 2019-10-02 15:28
Not sure what platform info you need but it is windows 10 enterprise N with IE 11.765.17134.0.

Error located at line 24828 in the unminified version:
` this.ArrayType = r || Float64Array, this.IndexArrayType = a < 16384 ? Uint16Array : Uint32Array;
var l = e.indexOf(this.ArrayType),
c = 4 * a * this.ArrayType.BYTES_PER_ELEMENT;
if (l < 0) throw new Error("Unexpected typed array class: " + r + ".");`


**Minimal example:**
Python side:
`p = figure(plot_height=350, plot_width=800)
p.circle(x=1, y=4)
json.dumps(json_item(p))
`
Then in the JS side:
`submit(data) {
    let stringified_model = JSON.stringify(data);
    fetch(this.state.data_target, {
      method: 'post',
      body: stringified_model,
      headers: {'X-CSRFToken': this.props.csrf_token, 'Content-Type': 'application/json', 'Accept': 'application/json'}
    }).then(response => {return(response.json());}).then(data => {this.setState({image_b64: data['plot']})});
  };`

render:
`let item = JSON.parse(data.image_b64);
let embed_item = Bokeh.embed.embed_item(item, "bokeh_plot");
return(<React.Fragment><div id="bokeh_plot" class='bk bk-root'></div>{embed_item}</React.Fragment>)`

**Comment by mattpap** [comment] 2019-10-02 15:50
I can't reproduce this on IE 11, albeit a different sub-version. @raqsilva, can you run this code:
```
[Float32Array, Float64Array].indexOf(Float64Array)
```
in your IE's developer console (press `F12` or look for "Developer Tools" in one of menus)? Click on "console" tab and there should be an input prompt at the bottom of the screen. The result should be `1`. Otherwise it's likely to be a bug in that specific version of IE.

**Comment by raqsilva** [comment] 2019-10-02 15:52
It did return 1

**Comment by mattpap** [comment] 2019-10-02 16:13
In this case it still may be a bug in IE, but there may also be something more at play, e.g. a broken polyfill or interaction of bokehjs with other involved libraries (which likely may be polyfill related as well). Given that I can't reproduce this, for now I can only recommend to debug this on your own (by setting a breakpoint at the exception line or enabling automatic breaking on error/exception) and poke around. Also you could test bokehjs plotting without additional libraries (like react) and see if this is the error persists. This way we could eliminate IE as the source of the bug.

**Comment by bryevdv** [comment] 2019-10-02 17:11
@raqsilva additionally testing on other Windows systems or with other patch versions of IE 11. None of the active Bokeh core devs are windows users or have ready access to windows systems to test with, so the reality is that some legwork on your part will be required here.

**Comment by raqsilva** [comment] 2019-11-13 09:34
[Update]
I had some spare time to have a look at this...
Internet explorer v11 apparently does not like to do indexOf in arrays with functions so I had to change everything with .toString() and it worked.

**Comment by bryevdv** [comment] 2019-11-13 15:36
I'll leave this open, perhaps we can add a polypill in the tentatively planned compat bundle for IE11

**Comment by bryevdv** [comment] 2020-08-25 04:59
Absent an MRE, and in light of MS's recent announcement, will close this after all. Note that IE support will be dropped entirely sometime in the next year.

**Closed by bryevdv** 2020-08-25 04:59 UTC
Labels: plat: ie, type: discussion
