### ISSUE TITLE
Multiple Action Tools in GridPlot

### ISSUE THREAD

**Issue by racheladdison** [bokeh/bokeh#4832] opened 2016-07-18 16:11 UTC
I am trying to include both the save and reset tools in a gridplot layout, but only the last of those tools in the list passed in shows up.

I am using version 0.12.0, and using example code from the Linked Brushing example on the website to be sure I wasn't making the mistake:
`from bokeh.io import output_file, show
from bokeh.layouts import gridplot
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

output_file("brushing.html")

x = list(range(-20, 21))
y0 = [abs(xx) for xx in x]
y1 = [xx**2 for xx in x]

source = ColumnDataSource(data=dict(x=x, y0=y0, y1=y1))

TOOLS = "box_select,lasso_select,reset,save,help"

left = figure(tools=TOOLS, width=300, height=300, title=None)
left.circle('x', 'y0', source=source)

right = figure(tools=TOOLS, width=300, height=300, title=None)
right.circle('x', 'y1', source=source)

p = gridplot([[left, right]])

show(p)`

TOOLS = "box_select,lasso_select,reset,save,help"
![screen shot 2016-07-18 at 10 00 30 am](https://cloud.githubusercontent.com/assets/11946711/16921411/b0ca87c2-4cce-11e6-94ce-63f63c694caf.png)
TOOLS = "box_select,lasso_select,save,reset,help"
![screen shot 2016-07-18 at 10 01 10 am](https://cloud.githubusercontent.com/assets/11946711/16921425/bab2b278-4cce-11e6-9d4c-a03d0c3245a0.png)

**Comment by bryevdv** [comment] 2016-07-18 18:34
Duplicate of #4759 fixed in #4763

**Comment by bryevdv** [comment] 2016-07-18 18:35
Please try the current latest dev build, or else `0.12.1` when it is released.

**Closed by bryevdv** 2016-07-18 18:34 UTC
