### ISSUE TITLE
cannot specify list of legend labels to Patches()

### ISSUE THREAD

**Issue by bje-** [bokeh/bokeh#6376] opened 2017-06-03 12:22 UTC
It is not possible to specify a list of labels for the legend when using Patches().  It is not satisfactory to use Patch() (which does) as there is a performance penalty for having too many glyphs.

**Comment by bryevdv** [comment] 2017-06-04 16:29
The "same-glyph" legend created by grouping a column, described in the end of this section does work for patches:

http://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html#legends

This code

```
from bokeh.io import show
from bokeh.models import ColumnDataSource
from bokeh.palettes import RdBu3
from bokeh.plotting import figure

c1 = RdBu3[2] # red
c2 = RdBu3[0] # blue
source = ColumnDataSource(dict(
    xs=[[1,2,2], [1,2,2], [3,4,4], [3,4,4]],
    ys=[[3,3,4], [1,1,2], [3,3,4], [1,1,2]],
    color=[c1, c2, c1, c2],
    label=['hi', 'lo', 'hi', 'lo']
))

p = figure(x_range=(0, 7), y_range=(0, 5), plot_height=300)

# Note legend field matches the column in `source`
p.patches( xs='xs', ys='ys', color='color', legend='label', source=source)
show(p)
```

Produces this output:

<img width="649" alt="screen shot 2017-06-04 at 11 26 28" src="https://cloud.githubusercontent.com/assets/1078448/26763453/aaeb3c6a-4918-11e7-9ed2-6e38d7b356da.png">


So, I am going to close this. However, I would say there is a decent chance this feature and the "interactive legend" features (muting and hiding) may not play well together. So if you encounter a specific problem, please open a new issue with example code to reproduce the problem. Alternatively if this approach is not what you are looking for, please feel free to open a feature request. But what would most help in that case is a concrete proposal for the syntax you'd like to use, and the outcome you'd like to see with that syntax.

**Closed by bryevdv** 2017-06-04 16:29 UTC

**Comment by gramster** [comment] 2017-10-09 21:26
This doesn't work for me. I have a chart with 6 distinct colors, set this way:

    , ...fill_color={'field': 'days', 'transform': LinearColorMapper(palette=palette, low=0, high=5, low_color='black')

and in my case the items list has only a single element.

**Comment by aqpoona** [comment] 2017-11-29 04:28
@bryevdv The code that you have given above produces the output: 
![bokeh_plot](https://user-images.githubusercontent.com/11692489/33357925-87aef8e4-d519-11e7-81ba-276dafcc122f.png)

 Has there been a code update which is leads to displaying the string 'label' rather than retrieving the label value from the source (ColumnDataSource)?

**Comment by bryevdv** [comment] 2017-11-29 05:33
@aqpoona I think it must be the contrary, and you are using a very old version. What you are seeing is teh way things used to behave, quite some time ago. With 0.12.11 (released today) the above code yields the expected result:

<img width="551" alt="screen shot 2017-11-28 at 23 32 08" src="https://user-images.githubusercontent.com/1078448/33359462-7dea9848-d494-11e7-9d3c-b16859bcb98a.png">

**Comment by aqpoona** [comment] 2017-11-29 06:15
@bryevdv Thanks for the fast reply! You are right, turns out that I was using an old version of bokeh ( although I only installed it last month!). After updating bokeh, this works. Thanks again!
