### ISSUE TITLE
[FEATURE] Allow custom date formats in DatePicker (flatpickr)

### ISSUE THREAD

**Issue by rstrutt** [bokeh/bokeh#10619] opened 2020-10-29 19:26 UTC
As-per the Discourse discussion here: https://discourse.bokeh.org/t/flatpickr-date-display-format/6630

Currently,  we are constrained to the ISO yyyy-mm-dd format for the flatpickr implementation of DatePicker (post-2.0);

![image](https://user-images.githubusercontent.com/7271339/97622498-c0acca80-19fa-11eb-97a3-20911adc49ae.png)

It would be great to expose the existing flatpickr dateFormat options to the user, retaining the standard ISO display as a default.

Looks like flatpickr supports everything from the JS side already via their config.dateFormat options;

https://flatpickr.js.org/formatting/

**Comment by wenjaylfw** [comment] 2020-11-10 06:20
Hello, is this issue available to work on? I'd like to give an implementation a shot.

**Comment by wenjaylfw** [comment] 2020-12-10 06:09
Hello I haven't been able to work on this issue since I last commented but I am working on it now! Just a quick question, if I make an edit in BokehJS do I not need to comment the code? I didn't see any comments in the typescript files.

**Comment by bryevdv** [comment] 2020-12-10 23:19
@wenjaylfw There is no hard and fast rule. If you think the code is tricky or confusing or has some special considerations that should always be recalled, then it is good to leave a comment explaining why that is. (In general, comments for "why" somethings the way it is, are much more useful than "what" comments that just restate what the code does in plain language)

**Comment by wenjaylfw** [comment] 2020-12-11 05:17
Thanks for the reply! I have another question though, I added date format as a prop of the Date Picker class and option to the DatePickerView and a class variable of the python class but when I try and pass in a value to that variable I get an error saying TypeError: Cannot read property 'set_value' of undefined. Is there some intermediate step that I need to modify between the python class definition and the date_picker.ts?

**Comment by bryevdv** [comment] 2020-12-11 07:09
@wenjaylfw I can't actually tell exactly what you have done from that description. The best way to avoid ambiguity and guessing is for you to submit a WIP PR so that we can discuss actual code (and discuss it on the PR, not this issue)

**Comment by wenjaylfw** [comment] 2020-12-11 19:45
Ok, will do

**Comment by wenjaylfw** [comment] 2020-12-12 18:48
Hello I submitted a WIP PR but am still unable to figure out what is causing the error. Between the python class and typescript class is there another definition that I need to alter?

**Comment by wenjaylfw** [comment] 2020-12-12 19:31
On further testing, it seems like changes made to the ts files aren't being used in my test. Is there something other than running setup.py and building fresh BokehJS to apply the changes?

**Comment by bryevdv** [comment] 2020-12-14 02:56
If it is not a Bokeh server app, then typically you would need to specify "inline" resources in order to use the locally built version:

https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#next-steps

**Comment by wenjaylfw** [comment] 2020-12-15 03:33
Hello, sorry if this is unneeded but just to bring this to your attention, I've submitted a final pull request that reflects the changes suggested in your last review

**Comment by mattpap** [comment] 2023-02-08 14:46
Closing as a duplicate of issue #8926.

**Closed by mattpap** 2023-02-08 14:46 UTC
Labels: reso: duplicate, type: feature, tag: component: bokehjs, tag: widgets
