### ISSUE TITLE
[BUG] Broken LOD downsampling

### ISSUE THREAD

**Issue by oleksulkowski** [bokeh/bokeh#13201] opened 2023-06-12 20:07 UTC
### Software versions

Python version      :  3.11.3 (main, May 15 2023, 15:45:52) [GCC 11.2.0]
IPython version     :  8.12.0
Tornado version     :  6.2
Bokeh version       :  3.1.1
BokehJS static path :  /home/olek/miniconda3/envs/testing/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  v18.16.0
npm version         :  9.5.1
Operating system    :  Linux-5.10.102.1-microsoft-standard-WSL2-x86_64-with-glibc2.31

### Expected behavior

I'm working on a genetic sequence viewer, where I add Text glyphs onto the plot where each glyph contains a single character.
The default LOD threshold is 2000. I expect downsampling to activate and improve interactions when sequences become longer than 2000 characters.

### Observed behavior

In this example, I created a 6-character-long sequence and set the lod_threshold at 10 to prevent downsampling in the top plot, and set it at 5 to activate downsampling in the bottom plot.

Level of detail downsampling worked normally in Bokeh 3.0.3 when panning a figure:
![3 0 3](https://github.com/bokeh/bokeh/assets/63408297/f9220e48-3c56-4127-8331-0ad5fe12b6ea)

Top: Downsampling OFF. Bottom: Downsampling ON.

In Bokeh 3.1.1, when downsampling is activated, the plot breaks:
![3 1 1](https://github.com/bokeh/bokeh/assets/63408297/1e363ea5-19c4-4d9f-aec6-a1ff60cdfff7)

### Example code

```Python
from bokeh.plotting import figure
from bokeh.io import output_notebook, show

output_notebook()

def create_figure(lod_threshold):
    text = ['A', 'T', 'G', 'A', 'T', 'G']
    x = [1, 2, 3, 4, 5, 6]
    y = [0, 0, 0, 0, 0, 0]

    # Create the bokeh figure
    plot = figure(title=None, width=400, height=200, lod_threshold=lod_threshold, tools="xpan")
    plot.text(x=x, y=y, text=text)

    return plot

show(create_figure(10))
show(create_figure(5))
```

### Stack traceback or browser console output

When using Panel 1.1.0 to interact with the figure, the following console error appears:

```
Uncaught (in promise) TypeError: p is undefined
    _render http://localhost:5006/static/js/bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:534
    render http://localhost:5006/static/js/bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:376
    _render http://localhost:5006/static/js/bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:372
    render http://localhost:5006/static/js/bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:239
    _paint_levels http://localhost:5006/static/js/bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:582
    _actual_paint http://localhost:5006/static/js/bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:582
    paint http://localhost:5006/static/js/bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:582
    repaint http://localhost:5006/static/js/bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:582
    throttled_paint http://localhost:5006/static/js/bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:582
    a http://localhost:5006/static/js/bokeh.min.js?v=c8d721b75531cff043feef626ae0d6e29a26031fae26bba93c1baa962ecfb1b43f211027df3a0cf7772f30afed8c38198d70677b8967e581ca7e605358c68465:583
```

**Comment by mattpap** [comment] 2023-06-12 20:34
This works in bokeh 3.2.0-dev4. Looks like a duplicate of issue https://github.com/bokeh/bokeh/issues/13112.

**Closed as completed by mattpap** 2023-06-12 20:34 UTC
Labels: reso: duplicate
