### ISSUE TITLE
DateRangeSlider issues on Bokeh server (Tornado) not on script

### ISSUE THREAD

**Issue by MikeWoodward** [bokeh/bokeh#8042] opened 2018-07-02 01:26 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 13.0
Python 3.6.5
Browser: Chrome
OS: OSX

#### Description of expected behavior and the observed behavior

DateRangeSlider behaves differently when run via Bokeh server (Tornado) than from within a script (not using the server). The Bokeh server (Torndao) behavior is incorrect.

In the example below. the daterange slider is give a start date, and end date, and values. When the example is run using this code:
```
    reset_output()
    output_file('test.html')
    show(layout)
```
everything is correct. However, if the code is run using this code (Bokeh Tornado):
```
    reset_output()
    document = Document()
    document.title = "Slider"
    document.add_root(layout)
    session = push_session(document)
    session.show()

    session.loop_until_closed()
```
The start date is incorrect and the lower value is incorrect. The code also gives an error message in the browser.

This bug may be related to #8009 and #8015. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
import datetime
from bokeh.layouts import column
from bokeh.client import push_session
from bokeh.document import Document
from bokeh.models.widgets import DateRangeSlider
from bokeh.plotting import output_file, reset_output, show

sliders = []

dates = [datetime.date(1969, 12, 31),
         datetime.date(1970, 12, 31),
         datetime.date(1971, 12, 31),
         datetime.date(1972, 12, 31),
         datetime.date(1973, 12, 31)]

today = datetime.date.today()

for date in dates:

    offset = date + datetime.timedelta(days=1000)

    sliders.append(
            DateRangeSlider(title="Date Range: ",
                            start=date,
                            end=today,
                            value=(offset, today),
                            step=1,
                            width=800)

    )

layout = column(sliders)

# To see error. change True to False
if True:
    reset_output()
    output_file('test.html')
    show(layout)
else:
    reset_output()
    document = Document()
    document.title = "Slider"
    document.add_root(layout)
    session = push_session(document)
    session.show()

    session.loop_until_closed()

```

**Comment by bryevdv** [comment] 2018-07-02 15:40
This is probably a duplicate of one of the linked issues, so I am going to close for now since they are linked. In particular `bokeh.client` is probably just exposing the inconsistent data formats that can apparently happen that you've noted.

In the interest of getting good information to as many possible, I do feel compelled to note that this kind of usage of `bokeh.client` with `session.loop_until_closed()` is *officially* discouraged. From the users guide:

> Warning
>
> It is possible to use bokeh.client to build up apps “from scratch”, outside a Bokeh server, including running and servicing callbacks by making a blocking call to session.loop_until_closed in the external Python process using bokeh.client. This usage has a number of inherent technical disadvantages, and should be considered unsupported.

Bokeh apps should always be run directly in a bokeh server. This can be a separate `bokeh serve` process, or a server embedded in a jupyter notebook, or a server is embedded as a library in another app. The only appropriate and supported uses of `bokeh.client` is:

* session customization (for apps running directly in a bokeh server)
* various kinds of testing purposes

It was probably a mistake to ever add `session.loop_until_closed()` and there will probably be a discussion about deprecating and removed it for 2.x

**Closed by bryevdv** 2018-07-02 15:40 UTC
