### ISSUE TITLE
Updates for Selection Model

### ISSUE THREAD

**Issue by bryevdv** [bokeh/bokeh#7611] opened 2018-03-08 22:45 UTC
After #7261 there is still some follow on work to do:

* update all examples to use new `Selection` model
* expand docs around the `Selection` model
* Add a migration section to release notes (programmatically updated selections will break)

**Comment by clairetang6** [comment] 2018-03-09 06:02
Duplicate of [issue 7516](https://github.com/bokeh/bokeh/issues/7516). I'll add that issue to the milestone and add checkboxes for the tasks.

**Closed by clairetang6** 2018-03-09 06:02 UTC
Labels: tag: component: docs, tag: component: examples, type: task

**Comment by bryevdv** [comment] 2018-03-09 08:28
Ah I missed that issue, thanks for the catch!
