### ISSUE TITLE
Layout partly removes axis ticks (example: sliders.py)

### ISSUE THREAD

**Issue by MaxMMadsen** [bokeh/bokeh#7244] opened 2017-11-22 14:52 UTC
#### I expect to see the full axis ticks (and axis label if any) but they seem to partly be covered by widgets.
Additonally i have experienced that the axis ticks are missing entirely if there is no axis label, as if the plot is scaled which makes the axis ticks visible but not the axis label.

#### Even the Slider.py example generates this problem:
![image](https://user-images.githubusercontent.com/33839162/33133264-85d01792-cf9c-11e7-9187-fe7042277612.png)

With axis label:
![image](https://user-images.githubusercontent.com/33839162/33133368-cb76f7fc-cf9c-11e7-805f-60817e0e275c.png)
But the more i zoom in and axis ticks gets longer:
![image](https://user-images.githubusercontent.com/33839162/33133391-e7caaade-cf9c-11e7-85eb-27546b2396cd.png)

**Comment by bryevdv** [comment] 2017-11-25 19:17
This is a dupe of https://github.com/bokeh/bokeh/issues/6676 which was fixed in #7197 and will be in the next release. 

<img width="641" alt="screen shot 2017-11-25 at 13 16 58" src="https://user-images.githubusercontent.com/1078448/33233883-f68137f8-d1e2-11e7-8b8c-5ab964db8593.png">

<img width="673" alt="screen shot 2017-11-25 at 13 17 05" src="https://user-images.githubusercontent.com/1078448/33233884-f9621faa-d1e2-11e7-9d58-aab1d1c302c8.png">

**Closed by bryevdv** 2017-11-25 19:17 UTC
