### ISSUE TITLE
Allow click on graph to follow link

### ISSUE THREAD

**Issue by yerfdogyrag** [bokeh/bokeh#653] opened 2014-05-24 14:54 UTC
I'd like to have a way of making it so that clicking on a graph will allow going to a new url, opening a new window, or copying a value to the clipboard.  Essentially, this would be similar to the HoverTool, but for clicks.

**Comment by damianavila** [comment] 2015-02-10 14:51
This is somewhat addressed by #1854, at least the open url thing...

**Comment by bryevdv** [comment] 2015-02-10 14:52
Yes I think this can be closed as a dupe.

**Closed by bryevdv** 2015-02-10 14:52 UTC
Labels: type: feature

**Comment by mattpap** [comment] 2015-02-10 15:09
Technically #1795 is a duplicate of this one, but it doesn't really matter.

**Comment by bryevdv** [comment] 2015-02-10 15:12
Yes, I am not rigid about choosing issues to label as dupes. We don't always catch them soon enough, so my policy is to keep whichever one has gotten the real discussion.
