### ISSUE TITLE
Bokeh legends move behind data points when webgl=True is used

### ISSUE THREAD

**Issue by pythonUzer** [bokeh/bokeh#4901] opened 2016-07-29 02:55 UTC
* Description of expected behavior and the observed behavior:
Bokeh legends move behind data points when webgl=True is used

* Self-contained example code that generates the issue (from bokeh legend sample in User Guide:
`import numpy as np
from bokeh.plotting import figure, show, output_file

x = np.linspace(0, 4*np.pi, 100)
y = np.sin(x)

output_file("legend_labels.html")

p = figure(webgl=True)

p.circle(x, y, legend="sin(x)")
p.line(x, y, legend="sin(x)")

p.line(x, 2*y, legend="2*sin(x)",
       line_dash=[4, 4], line_color="orange", line_width=2)

p.square(x, 3*y, legend="3*sin(x)", fill_color=None, line_color="green")
p.line(x, 3*y, legend="3*sin(x)", line_color="green")

p.legend.location = "bottom_left"

show(p)`
* Stack traceback and/or browser developer tools console output:
N/A
* Software version information output by `bokeh info` command:
Python version      :  3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06) 
IPython version     :  4.2.0
Bokeh version       :  0.12.0

For desired features, please provide:
* Description of the desired feature

**Comment by bryevdv** [comment] 2016-07-29 02:58
This is a duplicate of #4679 fixed in #4686 and available in the latest `0.12.1` release.

**Closed by bryevdv** 2016-07-29 02:58 UTC

**Comment by bryevdv** [comment] 2016-07-29 13:40
Here is a screenshot of your code above with 0.12.1 on OS X/Safari:

<img width="309" alt="screen shot 2016-07-29 at 8 34 56 am" src="https://cloud.githubusercontent.com/assets/1078448/17249833/59e59e6e-5567-11e6-957e-c3b0b8436c06.png">

If you are still seeing an issue can you first verify your installation/versions? In particular the JS console should have a log message to list both the python and JS version that are actually drawing.

**Comment by pythonUzer** [comment] 2016-07-29 16:21
I have since been able to verify it is working properly with 0.12.1. I had some environment problems on my end. Great work

**Comment by bryevdv** [comment] 2016-07-29 16:24
Great! Glad to hear it is working, thanks
