### ISSUE TITLE
High level charts - Histogram does not behave as expected

### ISSUE THREAD

**Issue by gwvr** [bokeh/bokeh#4467] opened 2016-06-09 14:26 UTC
* Description of expected behavior and the observed behavior:
In my example, given a simple list of ints, Histogram does not produce a histogram. The expected behaviour is to produce a histogram. Given the same data, both pandas and seaborn render a histogram as I would expect. Have I missed something in the documentation?

* [Self-contained example code](https://gist.github.com/gwvr/cbe5df5652d6542c054922d0837197d4) that generates the issue:

```python
numbers = [1, 4, 11, 15, 29, 32, 33, 55, 55, 56, 65, 90, 118, 124, 288, 385, 538, 617, 1260, 1717, 1830, 2268, 3553, 15964, 34577, 36315]

from bokeh.charts import Histogram, output_notebook, show
output_notebook()

p = Histogram(numbers)
show(p)
```

`bokeh info`
Python version      :  3.5.1 |Continuum Analytics, Inc.| (default, Dec  7 2015, 11:16:01) 
IPython version     :  4.2.0
Bokeh version       :  0.11.1

**Comment by bryevdv** [comment] 2016-06-09 14:40
This is duplicate of #3875, addressed by PR #3988, fixed in the latest dev build (verified):

<img width="829" alt="screen shot 2016-06-09 at 9 39 45 am" src="https://cloud.githubusercontent.com/assets/1078448/15933644/20ecc97e-2e26-11e6-99e6-f6a976962ec1.png">

**Closed by bryevdv** 2016-06-09 14:40 UTC

**Comment by gwvr** [comment] 2016-06-09 14:43
Thanks and apologies - I'd missed the five closed bugs.

**Comment by bryevdv** [comment] 2016-06-09 14:50
No worries, and please do check out the dev build if you can (`conda install -c bokeh bokeh` to get it), we recently merged a very large PR centered around layout but we could use help with testing and feedback.
