### ISSUE TITLE
[BUG] png export via save tool shows only part of figure

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#10280] opened 2020-07-10 09:14 UTC
#### Software version info (bokeh, python)
Python: 3.6.10
Bokeh: 2.1.1

#### Description of expected behavior and the observed behavior
The exported picture using the save tool (save icon) has a very strange focus. It only displays the top left corner (missing about 1/3 of information on x- and y-axis). The export_png() function works fine and the comparison of this two ways to generate a figure makes the unexpacted behaviour if the hover tool very clear.

#### Minimal Example

```
import numpy as np
import bokeh.plotting as bk_plt
import bokeh.io as bk_io

bk_plt.output_notebook()

N = 500
x = np.linspace(0, 10, N)
y = np.linspace(0, 10, N)
xx, yy = np.meshgrid(x, y)
d = np.sin(xx)*np.cos(yy)

p2 = bk_plt.figure(x_range=(0, 10), y_range=(0, 10))
p2.image(image=[d], x=0, y=0, dw=10, dh=10, palette="Spectral11", alpha = 0.5)
bk_io.export_png(p2, filename = 'asdf.png')
bk_plt.show(p2)
```

#### Screenshots or screencasts of the bug in action
This is how the figure is shown in a jupyter notebook.
![code_png_export](https://user-images.githubusercontent.com/68053396/87137841-d48ebe00-c29d-11ea-8336-92debbcbc4fd.PNG)
This is the exported figure using the save tool.
![export_png_hover_tool](https://user-images.githubusercontent.com/68053396/87137864-d9ec0880-c29d-11ea-9883-c26de4e0d0b8.png)
This is the export generated in the line before the last line in the code block.
![asdf](https://user-images.githubusercontent.com/68053396/87137871-deb0bc80-c29d-11ea-84b4-74306cf8b790.png)

**Comment by mattpap** [comment] 2020-07-10 09:17
This is a duplicate of issue #10249.

**Closed by mattpap** 2020-07-10 09:17 UTC
Labels: TRIAGE
