### ISSUE TITLE
BoxPlot does not draw when data label contains colon

### ISSUE THREAD

**Issue by mjmare** [bokeh/bokeh#2570] opened 2015-07-16 14:56 UTC
data = {'days:': [6., -70., 2., 4., 5.,-6., 7., 2., 4., 5.,6., 7., 2., 4., 150.,]}
plot = BoxPlot(data, title="BoxPlot", width=400, height=400)

Will not draw the box plot if the label contains a colon. So label 'days' is OK, but 'days:' is not. No errors are issued.

**Comment by bryevdv** [comment] 2015-07-16 15:08
dupe of #516 hope to be fixed soon(ish).

**Closed by bryevdv** 2015-07-16 15:08 UTC
Labels: reso: duplicate
