### ISSUE TITLE
[BUG] docs_json strings have improperly escaped quote characters

### ISSUE THREAD

**Issue by RyanChapman2x** [bokeh/bokeh#10399] opened 2020-08-14 19:40 UTC
bokeh: 2.1.1
python: 3.8.3
OS: windows

Code to reproduce (minimally edited code from https://docs.bokeh.org/en/latest/docs/user_guide/quickstart.html#userguide-quickstart)
```
from bokeh.plotting import figure, output_file, show
from bokeh.embed import components

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# output to static HTML file
output_file("lines.html")

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend_label="Temp.", line_width=2)

# show the results
show(p)

# json-ify the results
script, div = components(p)
```

The resulting json data string from `show(p)` (the expected output):
```
{"f09d7e95-e4be-4b19-89b5-324c0b4aa714":{"roots":{"references":[{"attributes":{},"id":"1004","type":"DataRange1d"} ...
```

The resulting json data string from `components(p)` (improperly quoted):
```
'{&quot;fb5578dd-c925-421f-a8bd-689a237db4d5&quot;:{&quot;roots&quot;:{&quot;references&quot;:[{&quot;attributes&quot;:{&quot;axis&quot;:{&quot;id&quot;:&quot;1016&quot;}
```

I don't know if this was done intentionally since one value is embedded between <script> tags and the other is rendered directly as a string, but the `elements.script_for_render_items()` comments make it pretty explicit that `&quot;` strings are to be avoided because of the impact they make on the size of generated files (which is how I detected this problem in the first place):
```
        # XXX: encodes &, <, > and ', but not ". This is because " is used a lot in JSON,
        # and encoding it would significantly increase size of generated files. Doing so
        # is safe, because " in strings was already encoded by JSON, and the semi-encoded
        # JSON string is included in JavaScript in single quotes.
```

**Comment by bryevdv** [comment] 2020-08-14 20:44
This is a duplicate of https://github.com/bokeh/bokeh/pull/10271 (fixed in https://github.com/bokeh/bokeh/pull/10271)

**Closed** 2020-08-14 20:44 UTC
Labels: TRIAGE
