### ISSUE TITLE
cannot import name 'future_set_result_unless_cancelled'

### ISSUE THREAD

**Issue by tcrensink** [bokeh/bokeh#8241] opened 2018-09-12 20:42 UTC
I cloned the bokeh repo. On trying one of the examples:

`bokeh serve --show taylor.py`

I get the error:
`ERROR:cannot import name 'future_set_result_unless_cancelled'`

after `conda update bokeh` I get more errors.  Any suggestions?

System/dependencies:
- Ubuntu 14.04
- chrome 64.0.3282.186
- fresh install of anaconda: `conda create -n py3 anaconda: (3.6.5)
(bokeh 0.12.16)
(tornado 5.0.2)

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/26497809/45452277-67ef0c00-b692-11e8-9b63-3baf32dcfd60.png)

**Comment by bryevdv** [comment] 2018-09-12 21:18
This name `future_set_result_unless_cancelled` does not appear anywhere inside the Bokeh codebase:

https://github.com/bokeh/bokeh/search?q=future_set_result_unless_cancelled&unscoped_q=future_set_result_unless_cancelled

However it is apparently a part of Tornado 5.x:

http://www.tornadoweb.org/en/stable/concurrent.html#tornado.concurrent.future_set_result_unless_cancelled

I am unable to reproduce any issue with the combination of Bokeh 0.12.16 an Tornado 5.0.2 and Python 3.6 on OSX. So I conclude this must either be:

* a corrupted installation issue of some kind on your system
* an upstream issue with Tornado itself on linux 

I don't foresee any action on our part in either case, so I am closing this issue. Am happy to continue trying to help with this as a support question on the mailng list.

**Closed by bryevdv** 2018-09-12 21:18 UTC
Labels: reso: referred, type: discussion
