### ISSUE TITLE
Animation in bokeh-server not running through a router/firewall

### ISSUE THREAD

**Issue by dvls** [bokeh/bokeh#1266] opened 2014-09-29 17:59 UTC
Hi,

I have recently started testing bokeh for inclusion in one of my projects.
I setup a separate python 3.4 environment using pyenv, and installed bokeh-0.6.1

When running bokeh-server at the default ip (127.0.0.1) animated plots run ok.

If the ip address is changed to the configured network ip (private 192.168.xx.xx style) and bokeh-server is accessed through the ip address, animated plots also work.

But, when accessing bokeh-server through a router with "port forwarding" (I am forwarding ports 5006 and 5007) the plots are shown but static. Refreshing the page using the browsers buttons updates once.

What other configurations are necessary to allow connections through router using port forwarding?

Any help is appreciated. Thanks

**Comment by rjhbrunt** [comment] 2015-01-12 17:18
I am having this same issue. I try to run the animated example, but when I go to the server page it is a static plot. When I refresh the page the plot updates (but still static). I am using bokeh 0.7 on Ubuntu 12.04. When I start the server I get the following exception:

![image](https://cloud.githubusercontent.com/assets/1848544/5707183/4b73d54e-9a4c-11e4-82d7-0c51b6f0eb40.png)

I am not sure if that is related to the problem, but it is the only error being thrown.

**Comment by bryevdv** [comment] 2015-01-12 17:58
OK. I have added this to the 0.8 milestone, we will begin a proper investigation to get this working. @hhuuggoo do you think using the server will entail firewall mods?

**Comment by alishir** [comment] 2015-01-28 10:43
Hi all,
I think I have the same problem when running bokeh-server on openshift PaaS.
I run the bokeh-server on openshift by following command and it starts successfully.
`bokeh-server --port $OPENSHIFT_PYTHON_PORT --ip $OPENSHIFT_PYTHON_IP --backend memory`

But when I run simple code to draw simple static plot, the only result on the server is a link with **link to this** text, and there is no plot. I start debugging by chrome and there is an error about **wsurl** in the console. The error is `GET http://bokeh/wsurl/ net::ERR_NAME_NOT_RESOLVED`.

Also I set `--ws-conn-string` when running server but it didn't resolve the error.

**Comment by alishir** [comment] 2015-01-28 11:13
After setting `Config.prefix` in `bokeh.js` manually I got the static plot, but for dynamic plots I should refresh browser to see the changes.

**Comment by damianavila** [comment] 2015-01-28 17:03
probably dupe of #1775?

**Comment by alishir** [comment] 2015-01-28 17:22
@damianavila for the static plots yes, but for the dynamic plots no. Even by resolving #1755 there is problem in dynamic plots, and there is no animation in plots.

**Comment by hhuuggoo** [comment] 2015-01-28 17:36
@alishir what I mean is setting Config.prefix properly should fix all these issues

**Comment by hhuuggoo** [comment] 2015-01-28 17:36
In fact, in your case, you could hardcode Config.prefix = "/" and see if that resolves

**Comment by alishir** [comment] 2015-01-28 17:37
@hhuuggoo Thanks for your comment. I will test it as soon as possible.

**Comment by alishir** [comment] 2015-01-28 18:15
@hhuuggoo I hard code Config.prefix = "/" but there is no animation yet.

**Comment by hhuuggoo** [comment] 2015-01-28 18:24
Is bokeh listening on port 5006, but you're using something like nginx to map to port 80?

**Comment by alishir** [comment] 2015-01-28 19:35
Yes, openshift pass have some port mapping, it maps port 80 to some random
port.

**Comment by alishir** [comment] 2015-04-26 17:25
Hi,

I&#39;d like to include you in my network to share updates and stay in touch.

- Ali

Confirm that you know Ali: https://www.linkedin.com/e/v2?e=ksjoks-i8yq8l0o-n&amp;a=preRegInvite&amp;tracking=eml-guest-invite-cta&amp;ek=invite_guest&amp;sharedKey=RPEzr8Sz&amp;invitationID=5998144666061545472


You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=ksjoks-i8yq8l0o-n&amp;t=lun&amp;midToken=AQFmrFVhGEd36Q&amp;ek=invite_guest&amp;loid=AQFxfECO0z0xFwAAAUz2w14B17CRC1C6eUOjUY05wlH173Z4CgFysHf3A-Rus5SsCai40ugoINs8DnuOjbS4soYNdEpkG2fp1XGtldWmD3FSQ6m9bjHdFyN5lP32m8iwyxK6_HwOVMhy4eWwVKb2ddBkZRicfC9M8v6bj9JUByehyZCg92e7ypIKPmya2F6tpLcM&amp;eid=ksjoks-i8yq8l0o-n Learn why we included this at the following link: https://www.linkedin.com/e/v2?e=ksjoks-i8yq8l0o-n&a=customerServiceUrl&ek=invite_guest&articleId=4788
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by damianavila** [comment] 2015-04-28 00:16
@alishir, I think you were spammed and now this last message is being pasted in multiple issues.

**Comment by alishir** [comment] 2015-04-30 12:00
Ali Shirvani would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=czsQdjgRcjoMdzoSd3gNe3AVdjR4imVLqnhxt6BSrCACuBcUsDF5k58Zumlbp6lOomxP9DhUpnhvt71BoSdxfndQ9CZOpmwZrioPfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9ClQqnpKimtBkClOs3Rx9zoSbjlKtDFOcPBFbndHrSFPqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683719553024_500&markAsRead=

View Ali Shirvani&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=0Td3gOdPsQcj4Zh4BOpm9JpmQCt7xBt5ZBr6BCrT9MfndQ9CZOpmwZrioQfmBI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9DpMrzRQ9zoSbjlKtDFOcPBFbndHrSFPqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683719553024_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=rmZzhj8BoDlEt6BDhj8BumNMpn8Md2kSej0Sd64Oc6lzejoNoj8Vp3pypj1Bc34Nc30Mc30Mc6pzczAMcPsOpm9yd3xAp6kQdmcUe3kToS8Soz9xoPsTdP5Be6hxpmoQdPsTczxApmkMc312cylVr71BszRIqm5JpioMdz0MczRAqioOdPgRd3kNdz0SdzoQd34UejARfmhFpOoNc5ZOpmhKqmRBsBZQsSlRpRZQsT9FpzRHpipQu6lQnS9RsSVRbjkJoDlPrDkJcj1vsClArCBJpn9vt7dBtmtvt7dOqmoJr6RBfmtKqmJzon9Q9CZLpPRQ9zoSbjlKtDFOcPBFbndHrSFPqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683719553024_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=3oSbjlKtDFOcPBFbndHrSFPqPRAqmkCq3hat3l2tAV9mm5yqDpcmAxkkDcRuCx6u6ZihQpmcDxne45CknB3cQRLdChSjjpLk4Zpk5hxkmFyd5t5c7cVkRB4lTxntSZEtyRUgD5NkDkOc5x2dSpUt3hCe4tiqBwPskded30Si5wVrmITqTdRm6IJcS4Um5dOdQxchCtklQJpiT5qtlFvk4cTqktxrlFUrARGqTtatQ9fin5KhChPqCJqsDtScSZDlTB4jkF2c4Rbc5l1gk51uCJpcztGt71bdkphgjRAqmZI9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9zoSbjlKtDFOcPBFbndHrSFPqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5998144683719553024_500&amp;markAsRead=This email was intended for bokeh/bokeh. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=3wUdPgZp4BBr6dFt79x9z4MnT9Bp6VFrmlOnThPpnlDnThPsCBCfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9zoSbjlKtDFOcPBFbndHrSFPqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683719553024_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by bryevdv** [comment] 2015-04-30 14:12
I have deleted the spam.

**Comment by alishir** [comment] 2015-05-07 07:28
Ali Shirvani would like to connect on LinkedIn. How would you like to respond?

Accept: https://www.linkedin.com/blink?simpleRedirect=0OdPgRd3kNdz0SdzoQd34UejARfkh9rCZFt65QqnpKqipWkPxOuAlgkzRVpkJApn9xq7cCt7xBt5ZQs6lzoS4ZsTgCrT9Bq3RJ9zcZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9ClQqnpKimtBkClOs3Rx9zARbmlHs75Rp3BFbndHrSFPqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683719553024_500&markAsRead=

View Ali Shirvani&#39;s profile: https://www.linkedin.com/blink?simpleRedirect=3sQd38TdPgNcjR4in9BoCRBripQu6lQnSlIqmpLsD0ZsTgCrT9Bq3RJ9zgZqmMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DpMrzRQ9zARbmlHs75Rp3BFbndHrSFPqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683719553024_500&markAsRead=

You are receiving Reminder emails for pending invitations. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=6RLoQkO9m9Rq7hFpQkO9nBIs6lOc3gBdzAMdzhxcz1BoPAScm4OemgSoCkMpj0Ncj0Mc30Mc31CoP8Vc3cTcClyozgUp6hBd3lze3wRdSdydC8OomcTdPsNpjxAomlCd3sTdP8Up6lBc30Mgz8BumNMpn8Zr6BxrmkCc3oMc38Zp6ACczsQdjgRcjoMdzoSd3gNe3AVdjRAqmsCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9DhUpnhvoDlPrDkJdyRytndKtiQNc5ZOpmhKqmRBsBZQsSlRpRZArCZzpncJr6RBfmtKqmJzon9Q9CZLpPRQ9zARbmlHs75Rp3BFbndHrSFPqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683719553024_500&markAsRead=

You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/blink?simpleRedirect=ejkJpmJMsnlAemAJsSJLqDdHfmhFpipWhzBMpzlAmANahB4Ool5fd6gOqORLq6RPc3dpozlhjT9UjCZWlmBSmAZPcDdfl38JtzBNpRlGmAtmt75UjRlpiTd3cSZodSRmslhOu3xRiQsQk3poikdBd5Fxj45hqPp1sjhQk49crA9Dc6h1lDlIlT18tkRkbkRvmAZoijl2k6JookRjhSh6qzhikjx9imZxsBh3c4FGhntKiAR6dAdbrD9KemVvrAlNk4p1emhLkDgMlk51gntApBAObkkShThmhR51fmhFrSMCcj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9B4ScSh5hSxmhD9JhB51fmVBqSZkp6BJ9CVRr3RQ9zARbmlHs75Rp3BFbndHrSFPqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&amp;msgID=I5998144683719553024_500&amp;markAsRead=This email was intended for bokeh/bokeh. Learn why we included this at the following link: https://www.linkedin.com/blink?simpleRedirect=e3wTd3RAimlIoSBQsC4Ccj1vsClArCBJpn9vt7dBtmtvp6VLoSlPfmJB9CNOlmlzqnpOpldOpmRLt7dRoPRx9zARbmlHs75Rp3BFbndHrSFPqPRBfP9SbSkLrmZzbCVFp6lHrCBIbDtTtOYLeDdMt7hE&msgID=I5998144683719553024_500&markAsRead=
&copy; 2015, LinkedIn Corporation. 2029 Stierlin Ct. Mountain View, CA 94043, USA

**Comment by bryevdv** [comment] 2016-04-10 02:58
This issue refers to the old `bokeh-server` which has been completely removed, so I am closing it now. The new server has much more extensive deployment documentation (including scenarios similar to this one) in the user's guide: http://bokeh.pydata.org/en/latest/docs/user_guide/server.html

**Closed by bryevdv** 2016-04-10 02:58 UTC
Labels: type: bug
