### ISSUE TITLE
[FEATURE]  NumeralTickFormatter language pack

### ISSUE THREAD

**Issue by DappenIT** [bokeh/bokeh#12359] opened 2022-09-08 06:33 UTC
### Problem description

I am trying to use the NumeralTickFormatter to format the y values / axis in my plot. I am developing an application in the german area, so I would like to change the value formatting to a german language-specific format. For example in german we write the number 10,000.00 like that: 10.000,00. So the comma and the dots are switched. The NumeralTickFormatter does not provide a way to do that. 

### Feature description

The current NumeralTickFormatter has an attribute "language" but it has no function yet. This attribute could be used for regional formatings, so that the ticks are displayed in the format that is defined trought the language attribute.
Code example for that:
```
plot = figure(name='kwhPlot', x_axis_type='datetime', plot_width=1500, plot_height=500, title='kWh Plot', x_axis_label='Zeitpunkt', y_axis_label='[kWh]')
plot.xaxis.formatter = DatetimeTickFormatter(
            days=["%d.%m.%y %H:%M"],
            months=["%d.%m.%y %H:%M"],
            hours=["%d.%m.%y %H:%M"],
            minutes=["%d.%m.%y %H:%M"]
        )
plot.yaxis.formatter = NumeralTickFormatter(language='de')
```

### Potential alternatives

The current alternative is to use the CustomJSTickFormatter and format it manually.

**Comment by mattpap** [comment] 2022-09-08 11:57
Duplicate of issue #7477.

**Closed by mattpap** 2022-09-08 11:57 UTC
Labels: reso: duplicate
