### ISSUE TITLE
Memory problem with bokeh server

### ISSUE THREAD

**Issue by waqarmalik** [bokeh/bokeh#4007] opened 2016-03-09 00:14 UTC
Initially posted @ https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/Uq3YB3u7Gfs

I've modified a line_animate example to plots more data points. This was done in an attempt to find a memory problem when running the program in a bokeh server.

The program is run using the following:
bokeh serve &
python  line_animate.py

The server process stays stable in its memory use, but the python process running the line_animate.py keeps accumulating memory. You can see observe it increasing a few MB per minute.

bokeh: 0.11.1
python 3.5
Mac OSX 10.9.5

Here's the modified line_animate.py code

```
# You must first run "bokeh serve" to view this example
import pandas as pd
import numpy as np
from numpy import pi
from bokeh.client import push_session
from bokeh.driving import cosine
from bokeh.plotting import figure, curdoc, ColumnDataSource

data = pd.DataFrame(columns=['x', 'y1', 'y2'])
data.x = np.linspace(0, 4*pi, 600)
data.y1 = np.sin(data.x)
data.y2 = np.cos(data.x)

df = data 
p = figure(plot_width=600, plot_height=600,)
r1 = p.circle(source=ColumnDataSource(df), x = 'x', y='y1', size=3, color="navy", alpha=0.4)
r2 = p.circle(source=ColumnDataSource(df), x = 'x', y='y2', size=3, color="firebrick", alpha=0.4)

# open a session to keep our local document in sync with server
session = push_session(curdoc())

ind = np.arange(len(data))
def update():
    global ind
    ind = np.roll(ind,1)
    df['x'] = data.ix[ind, 'x'].values
    r1.data_source.data = ColumnDataSource(df).data
    r2.data_source.data = ColumnDataSource(df).data

curdoc().add_periodic_callback(update, 50)

session.show() # open the document in a browser

session.loop_until_closed() # run forever
```

**Comment by bryevdv** [comment] 2016-03-09 00:56
@waqarmalik I believe this might only be an issue when using the Bokeh server with `bokeh.client` and not when running Bokeh server apps directly in the server. Can you confirm?

**Comment by waqarmalik** [comment] 2016-03-09 07:23
Running as server app has similar effect. Started at around 58MB and in around 5 minute was over 90MB, though this increase was not linear/uniform as it was with `bokeh.client`. This was without webgl. With webgl the memory increased at a much slower rate.

Is it possible to pass command line arguments to the program with running apps directly in the server?

**Comment by bryevdv** [comment] 2016-03-09 19:53
> Is it possible to pass command line arguments to the program with running apps directly in the server?

There is a new PR #4010 if you have an opportunity to test it out it would be helpful

**Comment by bryevdv** [comment] 2016-03-09 20:19
> This was without webgl. With webgl the memory increased at a much slower rate.

Wait, can you confirm what process is growing? webgl can only affect the browser, there is nothing anywhere on the python/server side that does anything with webgl (or even could, in principle -- it's purely a javascript thing)

**Comment by waqarmalik** [comment] 2016-03-11 04:02
When running as a server app, it is the memory python process corresponding to the server that grows. When run as `bokeh.client` it is the python process corresponding to the program that grows. Leaving the program running overnight causes a majority of memory of my machine to be used up.

**Comment by bryevdv** [comment] 2016-03-11 04:27
Something about these two lines:
```
    r1.data_source.data = ColumnDataSource(df).data
    r2.data_source.data = ColumnDataSource(df).data
``` 
arouses my suspicions. Can you try running with these two variations:
* with them commented out completely
* updating data, without creating new CDF objects in the call

**Comment by bryevdv** [comment] 2016-03-11 04:31
I should also add, although it does not address the problem directly, if your use case is "streaming" data (i.e., adding new values to the end of existing series) you should look at the streaming API demonstrated here:

https://github.com/bokeh/bokeh/blob/master/examples/app/ohlc/main.py#L60-L95

**Comment by bryevdv** [comment] 2016-04-10 00:45
@waqarmalik do you have any updates to this?

**Comment by waqarmalik** [comment] 2016-04-11 18:58
I was on vacation and got back to it today. If I comment out the two lines, the data_source does not get updated and no animation is seen. I'll try updating without creating a new ColumnDataSource and report back sometime today.

**Comment by waqarmalik** [comment] 2016-04-12 17:38
@bryevdv 
I ran the program with two variants:

- 

  Ran with the update function as follows:
  ```
  def update():
      global ind
      ind = np.roll(ind,1)
      df['x'] = data.ix[ind, 'x'].values
  ``` 
  There is no memory increase, but the plots are also not updated as the data_sources are not updated.

- _updating data, without creating new CDF objects in the callback_: 
  ```
  def update():
      global ind
      ind = np.roll(ind,1)
      r1.data_source.data['x'] = data.ix[ind, 'x'].values
      r2.data_source.data['x'] = data.ix[ind, 'x'].values
  ```
  The problem persists and the memory keeps increasing

**Comment by bryevdv** [comment] 2016-04-13 05:52
Thanks for the info @waqarmalik this is on my short list

**Comment by bryevdv** [comment] 2016-06-15 20:32
just an update, sorry I got swamped with some other work. On current master with a "server app" version of this I still see growth but much lest dratic that you report earlier. After 5 minutes I saw ~0.5 MB growth, from 53.9 MB to 54.4 MB. This is still unacceptable, of course, but is still an improvement. After the upcoming `0.12` release we intend to make some comprehensive reviews of performance and stability. `0.12` is the last release series before planned `1.0` so improving those aspects will really be the primary focus.

**Comment by bryevdv** [comment] 2016-06-15 20:32
For reference, here is the script I ran `bokeh serve` on:
```
import pandas as pd
import numpy as np
from numpy import pi
from bokeh.driving import cosine
from bokeh.plotting import figure, curdoc, ColumnDataSource

data = pd.DataFrame(columns=['x', 'y1', 'y2'])
data.x = np.linspace(0, 4*pi, 600)
data.y1 = np.sin(data.x)
data.y2 = np.cos(data.x)

df = data
p = figure(plot_width=600, plot_height=600,)
r1 = p.circle(source=ColumnDataSource(df), x = 'x', y='y1', size=3, color="navy", alpha=0.4)
r2 = p.circle(source=ColumnDataSource(df), x = 'x', y='y2', size=3, color="firebrick", alpha=0.4)

ind = np.arange(len(data))
def update():
    global ind
    ind = np.roll(ind,1)
    #df['x'] = data.ix[ind, 'x'].values
    r1.data_source.data['x'] = data.ix[ind, 'x'].values
    r2.data_source.data['x'] = data.ix[ind, 'x'].values

curdoc().add_periodic_callback(update, 50)
curdoc().add_root(p)
```

**Comment by bryevdv** [comment] 2018-03-13 23:23
I'm marking this a dupe of #7468

**Closed by bryevdv** 2018-03-13 23:23 UTC
Labels: type: bug
