### ISSUE TITLE
Bokeh Resources path does not load correctly when put bokeh server behind  a proxy. 

### ISSUE THREAD

**Issue by jevy-wangfei** [bokeh/bokeh#11168] opened 2021-04-15 06:02 UTC
https://github.com/bokeh/bokeh/blob/ed54705d627ae500509e57fe071fc7a60fc8a951/bokeh/server/django/consumers.py#L91

when put bokeh server behind a proxy or sub-route, such as `user/dan/dash-servebokehasdoc-with-tool', the reqeust such as 
```
http://localhost:8899/user/dan/dash-servebokehasdoc-with-tool/autoload.js?bokeh-autoload-element=1054&bokeh-app-path=/user/dan/dash-servebokehasdoc-with-tool&bokeh-absolute-url=http://localhost:8899/user/dan/dash-servebokehasdoc-with-tool
```

will return js_urls as: 

```
var js_urls = ["https://unpkg.com/tabulator-tables@4.9.3/dist/js/tabulator.js", "https://unpkg.com/moment@2.27.0/moment.js", "http://localhost:8899/static/js/bokeh.min.js?v=ada5d64938a63c435e537bbd83d34dfd3b1da9bfb3ca9c7b8e947f29983f2bd491f6a157b4613e727b5739396d69da58a21a56167d248c5ff99c5f3062545d11", "http://localhost:8899/static/js/bokeh-widgets.min.js?v=7c5d69c297ce643ea7819a254cab8350b24d29abd64ec600eef3c7aa177c23dfd2fac0b0e6ee981e019825ae02826f6590e98a2136bd173763d46d16bae43712", "http://localhost:8899/static/js/bokeh-tables.min.js?v=66c51fb45504582a2107573d44652e3c6fea046a294cbac15e4d7f9b8aa7e7953270a3f98107eeb94aa5f0eae031cb909f23c1113ab734a69fc77e0379ae6e8a", "http://localhost:8899/static/extensions/panel/panel.js"];
  
```

**Comment by bryevdv** [comment] 2021-04-15 06:12
@jevy-wangfei We will need much more information. A complete script to run, as well as full instructions or configurations of other tools to reproduce and investigate.

**Comment by philippjfr** [comment] 2021-04-15 10:08
@jevy-wangfei It looks like you are using Panel and I have in fact recently released Panel 0.11.3 which explicitly supports placing the server behind a proxy. I have to think about how to upstream some of that into bokeh itself but for now upgrading should solve your issues and if it doesn't please file an issue on the Panel issue tracker first.

**Comment by bryevdv** [comment] 2021-04-15 17:29
I am going to go ahead and close this issue then, and @philippjfr can make targeted issues for anything that can up upstreamed here

**Closed by bryevdv** 2021-04-15 17:29 UTC
Labels: NEEDS MORE INFO

**Comment by philippjfr** [comment] 2021-04-15 17:31
Oh @jevy-wangfei I missed that you were using the Django integration here. That's something I haven't yet look at so could you file an issue about that with Panel?

**Comment by jevy-wangfei** [comment] 2021-04-15 23:40
Thanks for your help. I'll create a issue with Panel.
