### ISSUE TITLE
`ValueError: Out of range float values are not JSON compliant` when the 1st column of the df is all nans

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#5584] opened 2016-12-19 16:06 UTC
`bokeh` 0.12.3

Repro:
```python
import numpy as np
import pandas as pd
p = TimeSeries(pd.DataFrame(dict(a=[np.nan, np.nan], b=[2, 3])))
show(p)
```

Swapping the columns round results in the expected plot. Likewise, adding a non-`nan` number also works.

**Comment by bryevdv** [comment] 2016-12-19 16:12
Dupe of #5581 among others. Root problem is JSON does not support `nan` values. Please look forward to PR https://github.com/bokeh/bokeh/pull/5544

**Closed by bryevdv** 2016-12-19 16:12 UTC
