### ISSUE TITLE
[BUG] Cannot access `ColumnarDataSource`

### ISSUE THREAD

**Issue by stefanv** [bokeh/bokeh#11616] opened 2021-09-14 23:02 UTC
This issue is potentially related to https://github.com/bokeh/bokeh/pull/11140

With Bokeh 2.3.1, 2.3.2, and 2.3.3 I see the following import error:

```
Uncaught ReferenceError: Cannot access 'ColumnarDataSource' before initialization
    at Module.eval [as ColumnarDataSource] (columnar_data_source.js?ffa7:1)
    at eval (cds_view.js?5c9c:13)
    at Function.define (has_props.js?e67c:88)
    at Function.init_CDSView (cds_view.js?5c9c:11)
    at eval (cds_view.js?5c9c:84)
    at Module../node_modules/@bokeh/bokehjs/build/js/lib/models/sources/cds_view.js (vendors~Bokeh.a20869519350f5a60a33.bundle.js:3287)
    at __webpack_require__ (main.bundle.js?388a4291dd5c1d7f7cfefa171acb6de1:64)
    at eval (glyph_renderer.js?42bb:1)
    at Module../node_modules/@bokeh/bokehjs/build/js/lib/models/renderers/glyph_renderer.js (vendors~Bokeh.a20869519350f5a60a33.bundle.js:3095)
    at __webpack_require__ (main.bundle.js?388a4291dd5c1d7f7cfefa171acb6de1:64)
```

I did not see this error with 2.2.3.

This is my Webpack configuration:

```
      {
        test: /\.js?$/,
        include: /node_modules\/@bokeh/,
        use: [
          {
            loader: "babel-loader",
            options: {
              plugins: [
              "@babel/plugin-proposal-export-namespace-from",
              "@babel/plugin-proposal-optional-chaining",
              "@babel/plugin-proposal-nullish-coalescing-operator"
              ],
            },
          },
        ],
      },
```

Versions:

```
bokeh/bokehjs: 2.3.2
Python: 3.9.6
OS: Linux
Browser: Chromium
```

**Comment by bryevdv** [comment] 2021-09-14 23:19
@stefanv please try with `2.4.0rc2` available via `pip install --pre` or `conda install -c bokeh//c/dev`

**Comment by stefanv** [comment] 2021-09-14 23:22
@bryevdv Is there a matching JS version? Upgrading the Python library does not fix it by itself.

**Comment by mattpap** [comment] 2021-09-14 23:23
Yes, e.g. https://www.npmjs.com/package/@bokeh/bokehjs/v/2.4.0-rc.2.

**Comment by bryevdv** [comment] 2021-09-14 23:24
@stefanv Yes, BokehJS 2.4.0rc2 is on NPM as well as scripts uploaded to CDN. 

Also note: if you are not able to test with 2.4.0rc2, or if you do verify the problem persists, then we absolutely must have a complete  [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) in order to actually investigate.

**Comment by mattpap** [comment] 2021-09-14 23:26
I tried reproducing this (give or take) on 2.4 and it seems to work (at least it loads without exceptions). If it doesn't work for you, I will need to know full webpack config and how this is being tested.

**Comment by mattpap** [comment] 2021-09-14 23:27
Also, if webpack has any tooling for cycle detection it would be good to enable it and see if it complains. We run our own cycle detection of every build.

**Comment by stefanv** [comment] 2021-09-14 23:38
I'm trying to think how I can contribute an MVP for the test suite.  Cycle detection was introduced a while ago already, but seems to have missed this one.  So I can do a minimal webpack build, but then it would need to be exercised to highlight this kind of failure.

**Comment by stefanv** [comment] 2021-09-14 23:47
Here is what the webpack circular dependency plugin shows for 2.3.2:

```
ERROR in Circular dependency detected:
node_modules/@bokeh/bokehjs/build/js/lib/core/selection_manager.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/renderers/glyph_renderer.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/sources/columnar_data_source.js -> node_modules/@bokeh/bokehjs/build/js/lib/core/selection_manager.js

ERROR in Circular dependency detected:
node_modules/@bokeh/bokehjs/build/js/lib/core/util/ndarray.js -> node_modules/@bokeh/bokehjs/build/js/lib/core/util/serialization.js -> node_modules/@bokeh/bokehjs/build/js/lib/core/util/ndarray.js

ERROR in Circular dependency detected:
node_modules/@bokeh/bokehjs/build/js/lib/core/util/serialization.js -> node_modules/@bokeh/bokehjs/build/js/lib/core/util/ndarray.js -> node_modules/@bokeh/bokehjs/build/js/lib/core/util/serialization.js

ERROR in Circular dependency detected:
node_modules/@bokeh/bokehjs/build/js/lib/models/glyphs/circle.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/glyphs/webgl/markers.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/glyphs/circle.js

ERROR in Circular dependency detected:
node_modules/@bokeh/bokehjs/build/js/lib/models/glyphs/webgl/markers.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/glyphs/circle.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/glyphs/webgl/markers.js

ERROR in Circular dependency detected:
node_modules/@bokeh/bokehjs/build/js/lib/models/renderers/glyph_renderer.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/sources/columnar_data_source.js -> node_modules/@bokeh/bokehjs/build/js/lib/core/selection_manager.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/renderers/glyph_renderer.js

ERROR in Circular dependency detected:
node_modules/@bokeh/bokehjs/build/js/lib/models/renderers/graph_renderer.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/renderers/glyph_renderer.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/sources/columnar_data_source.js -> node_modules/@bokeh/bokehjs/build/js/lib/core/selection_manager.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/renderers/graph_renderer.js

ERROR in Circular dependency detected:
node_modules/@bokeh/bokehjs/build/js/lib/models/sources/cds_view.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/sources/columnar_data_source.js -> node_modules/@bokeh/bokehjs/build/js/lib/core/selection_manager.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/renderers/glyph_renderer.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/sources/cds_view.js

ERROR in Circular dependency detected:
node_modules/@bokeh/bokehjs/build/js/lib/models/sources/columnar_data_source.js -> node_modules/@bokeh/bokehjs/build/js/lib/core/selection_manager.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/renderers/glyph_renderer.js -> node_modules/@bokeh/bokehjs/build/js/lib/models/sources/columnar_data_source.js
```

**Comment by stefanv** [comment] 2021-09-14 23:49
That report is clean for 2.4.0-rc2!

**Comment by mattpap** [comment] 2021-09-15 00:02
Which seems expected because the aforementioned PR (removing cycles) was merged for 2.4.0dev1.

**Comment by mattpap** [comment] 2021-09-15 00:03
Also webgl had some cyclic dependencies but that was also redesigned in 2.4.

**Closed** 2021-09-15 00:03 UTC
Labels: type: discussion, reso: noaction

**Comment by stefanv** [comment] 2021-09-15 00:10
OK, here's an MVP of a cycle detector:

https://github.com/stefanv/bokehjs-cycle-detection

Also, it may be helpful to have an example to show how to expose BokehJS through webpack?

**Comment by mattpap** [comment] 2021-09-15 00:17
> Also, this may be a helpful example of how to expose BokehJS through webpack?

We need to update our webpack example https://github.com/bokeh/bokehjs-examples/tree/main/webpack-example (at least with the cycle detection configuration you've provided) and bring it under downstream tests.

**Comment by stefanv** [comment] 2021-09-15 00:29
Shall we also modify that example to install from npm?  I feel like most people won't compile a tar-ball in practice, and the path towards modifying it to work as in the cycle-detection example above is not obvious.

**Comment by mattpap** [comment] 2021-09-15 00:33
Sure, if we have a tagged release (only those are published). The npm pack approach is good all-round. So, from examples' perspective the former is better and from testing the later.

**Comment by stefanv** [comment] 2021-09-15 04:52
I filed a PR for further discussion at https://github.com/bokeh/bokehjs-examples/pull/12
