### ISSUE TITLE
[FEATURE] Allow DataTable sorting of NaN values below numeric values

### ISSUE THREAD

**Issue by EfremBraun** [bokeh/bokeh#11740] opened 2021-10-14 20:44 UTC
**Is your feature request related to a problem? Please describe.**
When NaN or None values appear in a DataTable, they get sorted as if the values are greater than the numeric values. For example:
```
from datetime import date
from random import randint

from bokeh.io import show
from bokeh.models import ColumnDataSource, DataTable, DateFormatter, TableColumn

data = dict(
        dates=[date(2014, 3, i+1) for i in range(11)],
        downloads=[randint(0, 100) for i in range(10)]+[None],
    )
source = ColumnDataSource(data)

columns = [
        TableColumn(field="dates", title="Date", formatter=DateFormatter()),
        TableColumn(field="downloads", title="Downloads")
    ]
data_table = DataTable(source=source, columns=columns, width=400, height=280)

show(data_table)
```
When you sort the Data Table by the Downloads column, the None values gets sorted as if it's greater than the other items.

**Describe the solution you'd like**
I think that usually a None value should be sorted below the numeric values, as it's more commonly something like 0. Alternatively, it can be a user's choice.

**Additional context**
This is really more something that SlickGrid needs to implement before an interface can be built into Bokeh for it. In https://github.com/bokeh/SlickGrid/blob/bokeh%402.4.41/slick.dataview.js, the `comparer` (currently in line 47) is what would need to be changed.

**Comment by bryevdv** [comment] 2024-07-09 18:26
dupe of #11104

**Closed by bryevdv** 2024-07-09 18:26 UTC
Labels: type: discussion, tag: component: bokehjs
