### ISSUE TITLE
Issue with simple app and Google Chrome on Ubuntu 16.04

### ISSUE THREAD

**Issue by caiostringari** [bokeh/bokeh#4804] opened 2016-07-14 00:28 UTC
Was trying to build a simple app based on the "weather" app and run under a unsuspected behaviour on Ubuntu 16.04 and Google Chrome 51.0.2704.106.

Noticed that the when calling `bokeh serve --show weather/` if the default browser is set to Chrome, it will only open a new blank page. Both my app and the "weather" example had the same behaviour under Chrome.

The same example works fine on Windows and if the default browser is set to Firefox on Ubuntu it also works fine.

**Comment by bryevdv** [comment] 2016-07-14 01:04
Can you open the browser JS console and report if there is any output?

**Comment by caiostringari** [comment] 2016-07-14 01:10
There is no output. It only starts the browser in the home page and does nothing more.

**Comment by bryevdv** [comment] 2016-07-14 01:17
Just to be clear, you are looking at the developer tools JavaScript console? `ctrl`-`shift`-`J` opens the Chrome console IIRC. I ask to clarify, because there should almost certainly be *some* output in the JavaScript console.

**Comment by caiostringari** [comment] 2016-07-14 01:29
This is what is shown by Chrome after executing `bokeh serve --show weather/` and pressing ctrl-shift-J

![bokeh_issue_0](https://cloud.githubusercontent.com/assets/8363752/16825165/a5eb3b2e-49b5-11e6-8e11-07845bd7be42.png)

Some more detail:

![bokeh_issue](https://cloud.githubusercontent.com/assets/8363752/16825168/b43330e2-49b5-11e6-9cc9-c7e1a2ea04b4.png)

sorry, I am no expert on Bokeh or JavaScript...

**Comment by canavandl** [comment] 2016-07-14 01:35
You'll have to reload the page with the console open to capture the output.

**Comment by bryevdv** [comment] 2016-07-14 01:35
Can you click on the menu item labeled `Console` at the top, in between `Elements` and `Sources`

**Comment by caiostringari** [comment] 2016-07-14 01:44
something else showed up this time.

![bokeh_3](https://cloud.githubusercontent.com/assets/8363752/16825457/4da6f9a0-49b8-11e6-9785-3c6bcc7ea030.png)

**Comment by bryevdv** [comment] 2016-07-15 16:07
None of those messages coms from or have anything to do with Bokeh. Is there any chance you could test with chrome on a different machine, or a different version of chrome? Do you have any chrome extensions or plugins installed?

**Comment by bryevdv** [comment] 2016-12-20 23:48
closing for lack up update, please re-open if there is additional information to help reproduce

**Closed by bryevdv** 2016-12-20 23:48 UTC
Labels: type: discussion
