### ISSUE TITLE
[FEATURE] provide an example about moving the legend outside of the main figure

### ISSUE THREAD

**Issue by nicchan** [bokeh/bokeh#10092] opened 2020-05-29 17:53 UTC
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh Project Discourse](https://discourse.bokeh.org).

**Is your feature request related to a problem? Please describe.**

I am trying to configure legend of figure from vbar_stack(). I want to move the legend out of the stacked vbar figure so that the legend won't block any content in the main figure area.
The current stacked vbar example "https://docs.bokeh.org/en/latest/docs/gallery/bar_stacked.html" is using keyword "legend" which is deprecated in bokeh 2.0.2.

**Describe the solution you'd like**

I would like a legend manipulation example to be included in the stacked vbar example "https://docs.bokeh.org/en/latest/docs/gallery/bar_stacked.html".
The example should not use deprecated objects.

**Describe alternatives you've considered**

Deprecated "legend" keyword still works for now.
"add_layout" method was utilized as a work-around to move the legend outside of the main figure.

**Additional context**

**Comment by bryevdv** [comment] 2020-05-30 21:29
@nicchan I am confused by this:

> The current stacked vbar example "https://docs.bokeh.org/en/latest/docs/gallery/bar_stacked.html" is using keyword "legend" which is deprecated in bokeh 2.0.2.

The example at that link is clearly *not* using `legend`, it is using the current `legend_label`

**Comment by nicchan** [comment] 2020-05-30 22:18
@bryevdv Thank you for looking into this. I checked my script again and I did make an error when I tried to copy the current example over. Apologies for the confusion on the legend vs legend_label keywords.

I think the only request for now is to provide an example that demo how the legend can/should be moved so that the figure content won't be blocked. 

Thank you for your time!

**Comment by bryevdv** [comment] 2020-05-31 22:21
I'll close this as a duplicate of #10098 (which has some additional context)

**Closed by bryevdv** 2020-05-31 22:21 UTC
Labels: TRIAGE
