### ISSUE TITLE
Bokeh 0.12.4 to 0.12.6 - UTF-8 charset support

### ISSUE THREAD

**Issue by MacZel** [bokeh/bokeh#6633] opened 2017-07-17 01:35 UTC
Lately I've upgraded to Bokeh ver 0.12.6 from 0.12.4. I have previously used some UTF-8 codes in labels like ©, ®, .etc, and as far as I can see it's no longer supported. Is there a fix or am I doing something wrong?

example:
```
citation = Label(x=90, y=70, x_units='screen', y_units='screen',
    text='&copy;2017 xyz.com', text_font_style="bold")
```
in ver 12.4 produces:
`©2017 xyz.com`
and in ver: 12.6:
`&copy;2017 xyz.com`

test case script:
```
from bokeh.plotting import figure, output_file, show
from bokeh.models import Label

output_file("toolbar.html")

# create a new plot with the toolbar below
p = figure(plot_width=400, plot_height=400,
           title=None, toolbar_location="right",
           toolbar_sticky=False)

p.circle([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=10)

citation = Label(x=90, y=70, x_units='screen', y_units='screen',
                 text='&copy;2017 xyz.com', render_mode='css', text_font_style="bold")
p.add_layout(citation)

show(p)
```

**Comment by mattpap** [comment] 2017-07-17 07:36
What you are referring to is a HTML entity that can replace a Unicode character. This was previously accidentally allowed, because the implementation was sloppy, allowing for arbitrary HTML. What should work is using a unicode escape sequence `'\u00a9 2017 xyz.com'`, but doesn't for whatever reason (a bug).

**Comment by MacZel** [comment] 2017-07-17 08:17
Thanks a lot, it does work for me

**Comment by mattpap** [comment] 2017-07-17 14:08
> Thanks a lot, it does work for me.

@MacZel, that's interesting, because this doesn't work for me. Though I'm working on 0.12.7-dev, so maybe there's a regression since 0.12.6.

**Comment by bryevdv** [comment] 2017-07-17 16:40
If it's not working on master, we should look into it.

**Comment by bryevdv** [comment] 2017-10-11 00:12
works for me with `0.12.10dev2` so closing

<img width="379" alt="screen shot 2017-10-10 at 19 11 59" src="https://user-images.githubusercontent.com/1078448/31416453-e874cdcc-adee-11e7-830f-a431441333f4.png">

**Closed by bryevdv** 2017-10-11 00:12 UTC
Labels: type: discussion
