### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by nathan-vignal** [bokeh/bokeh#8927] opened 2019-05-23 12:23 UTC
I don't get the same result when pushing a previously displayed bokeh plot with push_notebook() and when I am using show()

I tried to check if I was still using the same handler and plot -> I am.
```
def update(self):
    if self.__handler == None:
        self.__handler = show(self.__plot, notebook_handle=True)
    else:
        show(self.__plot)
        push_notebook(handle=self.__handler)
```
before calling the upper function I change self.__plot and hide some of it's glyph.
```
    if self.__plot is not None:  # if the plot has already been displayed
        toDelete = self.__plot.select({'name': 'toDelete'})
        for glyph in toDelete:
            if glyph.visible == True:
                glyph.visible = False
```
In the first function (update):

The result of show(self.__plot) is not displaying the hidden glyphs.So it's doing what I want.

The result of push_notebook(handle=self.__handler) is displaying everything, and unfortunatly the things that are supposed to be hidden.
Running this on anaconda environment, bokeh 1.1.0, notebook 5.7.8, chrome, python 3.7

The first call of update is fine:
![initial graph](https://user-images.githubusercontent.com/37573225/58252166-bb5b4300-7d65-11e9-899a-c2db96503fe4.png)
Ather calling update a second time : 
You can see in the second one that the plot displayed by show and push_notebook are not the same.
![first interaction](https://user-images.githubusercontent.com/37573225/58252170-c0b88d80-7d65-11e9-9e7d-94b5727157a5.png)
After calling it a third time : 
everything merge together but the show() function is diplaying exactly what I want.
![second interaction](https://user-images.githubusercontent.com/37573225/58252393-50f6d280-7d66-11e9-9fa2-ba73571e2e2b.png)

**Comment by bryevdv** [comment] 2019-05-23 17:32
@nathan-vignal to have any hope of investigating we will need a complete notebook that reproduces the issue, as requested in the issue template.

**Comment by nathan-vignal** [comment] 2019-05-24 07:36
I'm really sorry, here's everything you need:
[debug.zip](https://github.com/bokeh/bokeh/files/3215635/debug.zip)

**Comment by bryevdv** [comment] 2019-05-27 00:32
@nathan-vignal glancing at your code, there are definitely some usage issues off the bat:

* The expected usage of `push_notebook` is this: `show` is called ***once***, in one cell. Then, later, in other cells, `push_notebook` can be used to update the previously shown output.

You are calling `show` every time in `update`, which right off the bat is not intended (that said, it is doing what you ask -- it is in fact showing all the things by appending them to the output cell, that is what `show` does)

Given these usage issues, I am going to close this issue for now. I happy to help you work through things, but the proper place for support questions is the new Discourse site:

https://discourse.bokeh.org/

So I will ask you to re-post will all this information in a topic there and we can discuss it further.  It might turn out we find there is a bug, or perhaps there is some documentation that can be expanded or improved. We can make relevant new issues at that time.

**Closed by bryevdv** 2019-05-27 00:32 UTC
Labels: TRIAGE
