### ISSUE TITLE
[BUG] Embedded plot not sized correctly if not visible from the start

### ISSUE THREAD

**Issue by mcrot** [bokeh/bokeh#12640] opened 2022-11-22 10:44 UTC
### Software versions

Python version      :  3.8.5 (default, Sep  4 2020, 07:30:14) 
IPython version     :  8.6.0
Tornado version     :  6.2
Bokeh version       :  3.0.2
BokehJS static path :  /home/michael/work/imtek/issues/bokeh_3.0.1_problem/venv/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.4.0-132-generic-x86_64-with-glibc2.10

### Browser name and version

Firefox 107.0

### Expected behavior

In my web app, I want to show two bokeh plots, each in a separate bootstrap tab. The are embedded
using [*components*](https://docs.bokeh.org/en/latest/docs/user_guide/output/embed.html#components).

When changing the tab, the corresponding plot in the tab should always be rendered and visible with correct size,
no matter whether it was visible from the start or not.

This worked fine with bokeh version 2.4.3, but not anymore with bokeh 3.0.x.

### Observed behavior

The plot on the second tab (which was not active when loading the page) shows a degenerated plot only.
The plot on the first tab looks good.
See series of screenshots below.

### Example code

```Python
############################################################
## Preparation
############################################################
pip install bokeh==3.0.2
pip install flask

############################################################
## File "app.py"
############################################################

from flask import Flask, render_template
from bokeh.embed import components
from bokeh.plotting import figure
from bokeh.resources import INLINE

app = Flask(__name__)

@app.route('/')
def index():

    fig1 = figure(width=300, height=300)
    fig1.line(
        x=[1, 2, 3, 4],
        y=[4, 3, 5, 1],
    )

    fig2 = figure(width=300, height=300)
    fig2.line(
        x=[1, 2, 3, 4],
        y=[1, -3, 5, -1],
    )

    
    # grab the static resources
    js_resources = INLINE.render_js()
    css_resources = INLINE.render_css()

    # render template
    script1, div1 = components(fig1)
    script2, div2 = components(fig2)
    html = render_template(
        'index.html',
        plot_script1=script1,
        plot_div1=div1,
        plot_script2=script2,
        plot_div2=div2,
        js_resources=js_resources,
        css_resources=css_resources,
    )
    return html
    

if __name__ == '__main__':
    app.run(port=5001, debug=True)

############################################################
## File "templates/index.html" (uses bootstrap via CDN)
############################################################
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="content-type" content="text/html; charset=utf-8">
    <title>Bokeh Tab Issue</title>

    <!-- Bokeh resources from flask -->
    {{ js_resources|indent(4)|safe }}
    {{ css_resources|indent(4)|safe }}
    {{ plot_script1|indent(4)|safe }}
    {{ plot_script2|indent(4)|safe }}

    <!-- Bootstrap 4 for tab navigation -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" crossorigin="anonymous"></script>
  </head>
  <body>

    <nav class="nav nav-tabs">
      <a class="nav-item nav-link active" data-toggle="tab" href="#first">First</a>
      <a class="nav-item nav-link" data-toggle="tab" href="#second">Second</a>
    </nav>

    <div class="tab-content">
      <div class="tab-pane fade show active" id="first" role="tabpanel">
	<h2>On first tab</h2>
	{{ plot_div1|indent(4)|safe }}
      </div>
      <div class="tab-pane fade" id="second" role="tabpanel">
	<h2>On second tab</h2>
	{{ plot_div2|indent(4)|safe }}
      </div>
    </div>
       
  </body>
</html>
```

### Stack traceback or browser console output

No error message in Python or in JS console (except the favicon is missing).

## This is how the first tab looks like, which is fine:
![grafik](https://user-images.githubusercontent.com/9113541/203292775-f3aab830-ffc8-45d4-a036-404cd1987282.png)

## Using _bokeh 3.0.2_, the plot on the second tab is broken:
![grafik](https://user-images.githubusercontent.com/9113541/203292925-917877d2-e823-4f83-9fee-5d81c83c2a7e.png)

## Using _bokeh 2.4.3_ with exactly the same code, the second plot is also okay:
![grafik](https://user-images.githubusercontent.com/9113541/203293219-3866b592-c933-44c9-8894-b8692655399a.png)

Note that the second plot has different data than the first in order to be sure it's the other figure.

**Comment by mcrot** [comment] 2022-11-22 10:51
Another note which might help: In bokeh version 3.0.0dev4, it was still working, so this problem does not happen with
```
pip install bokeh==3.0.0dev4
```
So this is probably related to the changes between 3.0.0dev4 and 3.0.0 (final).

**Comment by bryevdv** [comment] 2022-11-22 17:02
possible dupe of #12614 

This seems like the exact same issue Dask is having with their tabs/panels.

**Comment by mattpap** [comment] 2022-11-22 17:40
I didn't yet verify, but this is different, because this doesn't use any of flexible sizing modes. Most likely computed layout is not applied when CSS visibility changes (outside the scope of bokehjs' managed visibility).

**Comment by mattpap** [comment] 2022-11-22 17:44
> So this is probably related to the changes between 3.0.0dev4 and 3.0.0 (final).

There were 10 or so dev releases and a few hundred of PRs between those two. However, given how it fails, we know precisely the PR at fault (#11915).

**Comment by mcrot** [comment] 2022-11-23 10:54
Thanks for taking this into account! 
Since I need a short-term solution for a release of a web app, do you know any workaround on BokehJS level, 
some "refresh" function which I can call in Javascript and which would resize the plot correctly? 
Probably I could bind that to a tab change.

**Comment by kernc** [comment] 2022-11-25 04:28
> Since I need a short-term solution for a release of a web app, do you know any workaround

@mcrot If you really can't wait a few more days, you can pin your web app release on working bokeh==2.4.3. Besides fixing the issue at its core, this is your best workaround, provided the issue can be expected to be fixed.

**Closed as completed** 2022-11-29 20:04 UTC
Labels: type: bug, reso: completed, tag: component: bokehjs
