### ISSUE TITLE
Text annotation does not stay in the right spot after zoom

### ISSUE THREAD

**Issue by jsignell** [bokeh/bokeh#6057] opened 2017-03-23 19:08 UTC
Bokeh 0.12.5rc1
Chrome, Firefox, Safari

If you use the box zoom to zoom into a corner of the plotting/file/burtin.py and then zoom back out the text doesn't stick to the right spots. Might be related to #1883.

<img width="673" alt="screen shot 2017-03-23 at 3 00 42 pm" src="https://cloud.githubusercontent.com/assets/4806877/24265444/f93ff7e8-0fd9-11e7-9d3c-22ad8434f9d5.png">
<img width="698" alt="screen shot 2017-03-23 at 3 01 20 pm" src="https://cloud.githubusercontent.com/assets/4806877/24265447/fd277d68-0fd9-11e7-9162-f06023f088d4.png">
<img width="706" alt="screen shot 2017-03-23 at 3 01 50 pm" src="https://cloud.githubusercontent.com/assets/4806877/24265452/00630d6c-0fda-11e7-8f4b-3b3e2cea9e05.png">

**Comment by mattpap** [comment] 2017-03-23 19:10
@jsignell, can you confirm that this isn't a regression since 0.12.4?

**Comment by bryevdv** [comment] 2017-03-23 19:12
I believe this is definitely a dupe of #1883

**Comment by jsignell** [comment] 2017-03-23 19:13
> @jsignell, can you confirm that this isn't a regression since 0.12.4?

Same behavior is in 0.12.4  - not a regression

**Closed** 2017-03-23 19:25 UTC
Labels: reso: duplicate
