### ISSUE TITLE
[BUG]  - selection_glyph & nonselection_glyph do not modify size or marker type

### ISSUE THREAD

**Issue by LorenzoPeve** [bokeh/bokeh#12564] opened 2022-11-04 19:00 UTC
### Software versions

Python version      :  3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.6.0
Tornado version     :  6.2
Bokeh version       :  2.4.3
BokehJS static path :  C:\Users\lpeve\Documents\LP_Repo\InSIGHT\venv\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19042-SP0

### Expected behavior

I was expecting the selected points to change the marker type and size as indicated. 

### Observed behavior

 However, it seems that only the color attributes change.

### Example code

```Python
from bokeh.io import output_file, show
from bokeh.models import Circle, Scatter
from bokeh.plotting import figure

plot = figure(width=400, height=400, tools="tap", title="Select a circle")
renderer = plot.scatter([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=50, marker= 'circle')

selected_circle = Scatter(marker = 'triangle', fill_color="black")
nonselected_circle = Scatter(marker = 'circle', fill_color="blue", size = 2)

renderer.selection_glyph = selected_circle
renderer.nonselection_glyph = nonselected_circle

show(plot)
```

**Comment by bryevdv** [comment] 2022-11-04 19:02
dupe of https://github.com/bokeh/bokeh/issues/2367 this is still a feature to be implented.

**Closed by bryevdv** 2022-11-04 19:02 UTC
Labels: TRIAGE
