### ISSUE TITLE
Excess text when multi_line hover hits two or more lines

### ISSUE THREAD

**Issue by BenZickel** [bokeh/bokeh#7416] opened 2018-01-15 21:48 UTC
I'm using the code found at [https://stackoverflow.com/questions/38304753/multi-line-hover-in-bokeh](https://stackoverflow.com/questions/38304753/multi-line-hover-in-bokeh) in order to produce multiple lines with hover text.

The problem is that when the cursor hits two or more lines excessive text is generated by hover (for N hits at the current cursor position the entire hover text is replicated N times).

This can be seen when running the example from the above link and putting the cursor at a point which hits two lines (see below image).

![image](https://user-images.githubusercontent.com/35469979/34962835-1dc80c86-fa4e-11e7-8a18-6416a87fe4d3.png)

Instead of having just two text boxes, one for each line, there are four text boxes, two identical for each line.

This happens in Python 2.7 with bokeh version 0.12.7.

**Comment by bryevdv** [comment] 2018-01-15 21:55
We are extremely resource limited, and only have the capacity to investigate and work on issues from the latest release. Please confirm whether this persists with the latest release (0.12.13) and report back.

**Comment by BenZickel** [comment] 2018-01-15 22:25
I checked and the problem occurs exactly in the same way in bokeh version 0.12.13.

**Comment by p-himik** [comment] 2018-01-23 13:58
Probable cause: #7448

**Comment by clairetang6** [comment] 2018-01-23 19:14
I ran into this issue at some point, and it's caused by a bug in the hovertool [here](https://github.com/bokeh/bokeh/blob/7e2c4d396eb2b11a6476073b6b1421e497c8c10f/bokehjs/src/coffee/models/tools/inspectors/hover_tool.ts#L270), where the inner loop should be over `indices['2d'].indices[i]` and not `indices['2d'].indices`. The selection refactor in [this PR](https://github.com/bokeh/bokeh/pull/7261) changes `indices['2d']` to be called `multiline_indices` and also fixes this issue.

**Comment by bryevdv** [comment] 2018-02-02 15:26
pushing this off since #7261 is being deferred to the next cycle

**Comment by bryevdv** [comment] 2018-02-09 17:46
confirmed fixed by #7261

**Closed** 2018-02-09 17:46 UTC
Labels: reso: completed, tag: component: bokehjs, type: bug
