### ISSUE TITLE
autoload.js not working for IE11 in Bokeh versions > 0.12.4

### ISSUE THREAD

**Issue by esti** [bokeh/bokeh#7003] opened 2017-10-03 10:03 UTC
Hi all,

When I try to embed a plot using autoloading, I get an "Bokeh error: Invalid calling object" javascript error on IE11. Everything works fine in Chrome and Firefox.

I believe the problem is in autoload.js because the traceback in the javascript console points there and because when I replace the script tag generated by "autoload_server" by the components returned by the "components" function, everything is fine.

To make sure the problem is not in my python code, I have reproduced the problem using the very simple "Scatter markers" example provided here: https://bokeh.pydata.org/en/latest/docs/user_guide/plotting.html#userguide-plotting
Once again, when embeded this plot using the script and div components returned by the "components" python function, the plot shows up in IE11, but when using the self contained script tag returned by "autoload_server", the mention error appears.

Any hint? Thanks in advance!

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Python version: 3.5.3
Bokeh versions with the problem: 0.12.7, 0.12.6, 0.12.5. I haven't tried with 0.12.9 because it is not yet installable via anaconda. There is no error when using 0.12.4.
Browser: IE 11 (11.0.9600.18349) 

#### Description of expected behavior and the observed behavior
I expected the plot to show but the javascript error shown in the screenshot below is shown below

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.embed import components
from bokeh.plotting import figure, curdoc
p = figure(plot_width=400, plot_height=400)
# add a circle renderer with a size, color, and alpha
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)
layout = layout([
    [p],
])
curdoc().add_root(layout)

# script, div = components(p) # including in my html these components works fine
# script = autoload_server(url="url_to_my_bokeh_server_application") # including this script tag returns error
```

#### Stack traceback and/or browser JavaScript console output
See screenshots bellow

#### Screenshots or screencasts of the bug in action
Shown javascript error

<img width="168" alt="bokeh-error" src="https://user-images.githubusercontent.com/11853/31119837-9e13b4a8-a832-11e7-8594-bb24fddb8905.png">

Traceback

<img width="678" alt="bokeh-error2" src="https://user-images.githubusercontent.com/11853/31119838-9e15a5ec-a832-11e7-8ea1-51ea498b6ffa.png">

**Comment by bryevdv** [comment] 2017-10-03 19:55
@esti Bokeh `0.12.9` should now be available on conda:
```
❯ conda install bokeh
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /Users/bryan/anaconda:

The following packages will be UPDATED:

    bokeh: 0.12.5-py36_1 --> 0.12.9-py36h7e0c046_0

Proceed ([y]/n)?
```
There were a number of changes in that release that were tangentially or directly related to "autoload" style embedding. Before proceeding any further, can you verify whether or not there is an issue with `0.12.9` ?

Also as an FYI, `autoload_server` was too complicated. It has been deprecated and split into two simpler functions, `server_document` and `server_session` (you probably want the first)

**Comment by esti** [comment] 2017-10-04 05:15
@bryevdv I can't seem to find the 0.12.9 version (?)

`$ conda install bokeh
Fetching package metadata .........
Solving package specifications: .

All requested packages already installed. 
packages in environment at /home/hcoop/anaconda3/envs/hcoop:

bokeh                     0.12.7                   py35_0

$ conda search bokeh
Fetching package metadata .........
bokeh                        0.1.1                np17py27_0  defaults        
                             0.2                  np17py27_0  defaults        
...
                             0.12.4                   py27_0  defaults        
                             0.12.4                   py34_0  defaults        
                             0.12.4                   py35_0  defaults        
                             0.12.4                   py36_0  defaults        
                             0.12.5                   py27_0  defaults        
                             0.12.5                   py35_0  defaults        
                             0.12.5                   py36_0  defaults        
                             0.12.5                   py27_1  defaults        
                             0.12.5                   py35_1  defaults        
                             0.12.5                   py36_1  defaults        
                             0.12.6                   py27_0  defaults        
                             0.12.6                   py35_0  defaults        
                             0.12.6                   py36_0  defaults        
                             0.12.7                   py27_0  defaults        
                          *  0.12.7                   py35_0  defaults        
                             0.12.7                   py36_0  defaults        
r-rbokeh                     0.2.1                  r3.2.0_0  defaults        
                             0.2.1                  r3.2.1_0  defaults        
                             0.2.1                 r3.2.0_0a  defaults        
...`

**Comment by ivan-usov** [comment] 2017-10-04 06:32
@esti You could try to install from the bokeh channel
`$ conda install -c bokeh bokeh`

**Comment by esti** [comment] 2017-10-04 08:00
@ivan-usov Thanks, that worked!
@bryevdv I get the same error when using Bokeh 0.12.9. BTW, the script tag returned server_document is basically the same as the one retuned by autoload_server or am I doing something wrong?

Thanks!

**Comment by mattpap** [comment] 2017-10-04 10:29
It looks like this is a duplicate of issue #6982. To verify, someone has to test this with bokeh 0.12.10dev2.

**Comment by esti** [comment] 2017-10-04 12:03
@mattpap Eureka! It does work properly with bokeh 0.12.10dev2.
Is it save to use this version in production? If not, do you have an estimation of when 0.12.10 will be released?

Thanks for the help!

**Comment by bryevdv** [comment] 2017-10-04 13:00
Only safe with inline resources. The CDN filed for dev builds are periodically cleaned. I hope to release 0.12.10 in a week or ten days.

**Closed** 2017-10-04 13:19 UTC
Labels: reso: duplicate, type: discussion
