### ISSUE TITLE
Tornado Next Tick Callback Issue

### ISSUE THREAD

**Issue by kylesav** [bokeh/bokeh#7219] opened 2017-11-15 15:02 UTC
Posted this to the Google Group a couple weeks ago but didn't seem to get any activity there but wanted to bring this to attention:

Build is on bokeh 0.12.9, tornado version 4.5.2. Chrome browser. 

I've been building an application to consume a UDP stream and add the data as it comes in to a bokeh plot. I can consume the UDP stream fine and most of the time the bokeh callbacks work to add the data but sometimes I get a long error message as follows:

2017-10-25 14:35:52,825 Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x000000ADC0CA3048>)
Traceback (most recent call last):
  File "d:\afcbm\continuum\lib\site-packages\tornado\ioloop.py", line 605, in _run_callback
    ret = callback()
  File "d:\afcbm\continuum\lib\site-packages\tornado\stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "d:\afcbm\continuum\lib\site-packages\bokeh\util\tornado.py", line 133, in wrapper
    self.remove_next_tick_callback(callback)
  File "d:\afcbm\continuum\lib\site-packages\bokeh\util\tornado.py", line 160, in remove_next_tick_callback
    self._remove(callback, self._next_tick_callbacks)
  File "d:\afcbm\continuum\lib\site-packages\bokeh\util\tornado.py", line 155, in _remove
    self._error_on_double_remove(callback, callbacks)
  File "d:\afcbm\continuum\lib\site-packages\bokeh\util\tornado.py", line 116, in _error_on_double_remove
    raise ValueError("Removing a callback twice (or after it's already been run)")
ValueError: Removing a callback twice (or after it's already been run)

Minimal Code example below:

```
import socket
import struct
import time
from bokeh.plotting import figure
from bokeh.layouts import column
from bokeh.models import ColumnDataSource
from bokeh.io import curdoc
from threading import Thread
from functools import partial
from tornado import gen

plot_column = column()

UDP_IP = "127.0.0.1" # 172.17.1.32
UDP_PORT = 29505

sock = socket.socket(socket.AF_INET, # Internet
                     socket.SOCK_DGRAM) # UDP

sock.bind((UDP_IP, UDP_PORT))

doc = curdoc()

f = figure(plot_width=700, plot_height=200)
source = ColumnDataSource(data=dict(x=[], y=[]))
l = f.circle(x='x', y='y', source=source)
plot_column.children.insert(0, f)

@gen.coroutine
def update(x, val):
    source.stream(dict(x=[x], y=[val]))


def receive_loop():
    while True:
        data, addr = sock.recvfrom(1024) # buffer size
        val = struct.unpack('!i', data)[0]
        doc.add_next_tick_callback(partial(update, x=time.time(), val=val))


doc.add_root(plot_column)
thread = Thread(target=receive_loop)
thread.start()


Minimal code example for the client:

import socket
from random import random
import time
import struct

UDP_IP = "127.0.0.1" # 172.17.1.32
UDP_PORT = 29505

sock = socket.socket(socket.AF_INET,
                     socket.SOCK_DGRAM)
x = 0
while True:
    time.sleep(0.2)
    x += 1

    sock.sendto(struct.pack('!i', x), (UDP_IP, UDP_PORT))

```

Interestingly, I've been able to create a temporary workaround on my system by modifying the tornado.py file within bokeh by adding a time.sleep(.001) call at line 154 within the _remove method. With any amount of sleep in the process of removing the next tick callback the ValueError shown above doesn't trigger. The error seems to show randomly on the system, with no real consistency of when it shows up within the stream of data.

**Comment by bryevdv** [comment] 2017-11-15 15:40
I can't reproduce any problem with `0.12.10` or `master` on OSX Safari or Chrome with Tornado 4.5.2  @kylesav please confirm whether there is a problem with current releases, and if so, please provide more detailed system information.

**Comment by kylesav** [comment] 2017-11-15 16:01
![image](https://user-images.githubusercontent.com/25437924/32845968-1cba20fc-c9f4-11e7-9b51-fd4af5cc0a6d.png)

Still having the bug on my system with bokeh 0.12.10, see image for system details. Windows 10 OS.

**Comment by bryevdv** [comment] 2017-11-15 16:12
Right, knowing that it is windows is an important detail. It's possible this is some upstream Tornado issue on Windows we will have to try and work around. None of the core devs are regular windows users, and thus far no one from the community has stepped up to volunteer to be the windows maintainer, so given that it will take some extra time and effort to look into this.

**Comment by kylesav** [comment] 2017-11-15 16:32
No problem, the workaround I found works for now (adding a small sleep before removing callbacks in the bokeh tornado.py file).

**Comment by yurijvolkov** [comment] 2017-11-18 15:44
Hi. Found same problem on Ubuntu 16.04.3 LTS. With tornado 4.5.2 and bokeh 0.12.10. Workaround suggested by @kylesav works.

**Comment by p-himik** [comment] 2017-11-24 15:41
I've been having this problem for quite a while in the exact same environment - Ubuntu and Bokeh 0.12.{7..10}.
I have no idea what's going on, but take a look at this:
![image](https://user-images.githubusercontent.com/4410314/33216895-5c6fc1cc-d168-11e7-8d9a-ea34532abe86.png)
So, the breakpoint has been hit because of the callback not being present in the dict callbacks. But the evaluation window clearly shows that it's there.

**Comment by p-himik** [comment] 2017-11-24 15:43
Oh, wow, it's actually pretty clear now.
`self._loop.add_callback(wrapper)` is run before `self._next_tick_callbacks[callback] = remover`. It has to be the other way around because `add_next_tick_callback` can be called from a thread different from the one where `IOLoop` is running.
@bryevdv Is my assumption correct?

**Comment by p-himik** [comment] 2017-11-24 15:52
Also, even if the issue is fixed by the swapping of the lines in `add_next_tick_callback`, I think that it would make sense to make it less simple for the users to make a mistake by executing `remove_next_tick_callback` manually in another thread. Probably `remove_next_tick_callback` should be made private. Or at least some documentation about `remove_next_tick_callback` not being thread-safe should be added.

**Comment by p-himik** [comment] 2017-11-24 16:02
Heh, and `add_next_tick_callback` is not completely thread-safe either.
First, the code checks for the passed callback being in `self._next_tick_callbacks`, and then, without any locking, it adds the callback there. Because of this, the situation that should result in `ValueError("Next-tick callback added twice")` could result in `ValueError("Removing a callback twice (or after it's already been run)")`.
Is there any reason for not allowing adding the same callback twice?

**Comment by bryevdv** [comment] 2017-11-25 19:23
@p-himik Thanks for digging further into this. I don't know offhand why adding the same callback twice is disallowed. Most of the server code was originally written by @havocp who is working on other things these days. It seems like adding locking code would definitely be a reasonable fix, however I'd be open to considering relaxing the duplicate callback prohibition too, if you want to submit a PR to use as a basis for evaluation.

**Comment by havocp** [comment] 2017-11-25 21:59
I think it was just to avoid the book-keeping work. If you allow double add you have to be sure the remove method only removes one of them (and which one should it remove? does it matter?).

The simplest way around this is to make removal use an id returned by add, but I think we had a remove method using function identity instead, which makes us care about dups.

If the remove method removes all dups, then app code can get confused because add/remove usually come in pairs and code units don’t expect the remove from a different pair to step on their add. Having remove affect only one instance makes app code work more as expected.

Anyway my guess is this was mostly to avoid some implementation effort to allow dups properly.

**Comment by p-himik** [comment] 2017-11-26 15:46
Right now, all callbacks added via a document are wrapped with some `SessionCallback` that automatically generates an ID - it can be used to solve the problem with double additions.
If my understanding is correct, the only other place where callbacks can be added is lifecycle hooks. `ServerContext` used there doesn't use `SessionCallback`, but we can use the same mechanism to generate unique IDs.
I'd like to go with the approach where `add_*_callback` methods return an ID and `remove_*_callback` methods accept that ID. But it's a breaking change, albeit arguably a small one since I don't think that `remove_*_callback` are often used methods.

If there are no objections to this breaking change, I'll create a PR.

**Comment by bryevdv** [comment] 2017-12-13 19:01
@p-himik I would support such a PR, however I would also support a PR that allows dups, and simply removes the last *one* when `remove_*_callback` is called, citing this as precedent for that approach
```
In [2]: lst.remove(2)

In [3]: lst
Out[3]: [1, 3, 4, 2]
```

**Comment by p-himik** [comment] 2017-12-14 08:09
@bryevdv Ok, I'll try to come up with something.

**Comment by yschroeder** [comment] 2018-02-09 07:11
I am seeing the same issue in 0.12.14 on Arch Linux:
```
2018-02-09 08:01:17,800 Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f746ec09048>)
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/usr/lib/python3.6/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/bokeh/util/tornado.py", line 135, in wrapper
    self.remove_next_tick_callback(callback)
  File "/usr/lib/python3.6/site-packages/bokeh/util/tornado.py", line 161, in remove_next_tick_callback
    self._remove(callback, self._next_tick_callbacks)
  File "/usr/lib/python3.6/site-packages/bokeh/util/tornado.py", line 156, in _remove
    self._error_on_double_remove(callback, callbacks)
  File "/usr/lib/python3.6/site-packages/bokeh/util/tornado.py", line 118, in _error_on_double_remove
    raise ValueError("Removing a callback twice (or after it's already been run)")
ValueError: Removing a callback twice (or after it's already been run)
```

**Comment by bryevdv** [comment] 2018-02-09 13:20
@yschroeder you will need to provide code to reproduce. We have no ability to investigate a problem that we can't reproduce.

**Comment by bryevdv** [comment] 2018-02-09 18:00
@yschroeder please disregard, I saw this in an email and thought you had made a new issue.

**Comment by yschroeder** [comment] 2018-02-10 15:41
I could provide example code nonetheless, but it is almost the same as the original report. I have a blocking thread that does ``doc.add_next_tick_callback(...)``. It is implemented as described for blocking threads in the Bokeh Server documentation:

**Comment by aayla-secura** [comment] 2018-03-01 10:16
I am seeing the same issue on Linux (Debian), bokeh v 0.12.14, tornado 4.5.3, python 3.6 (tested chrome and firefox). Weird thing is that I only call `add_next_tick_callback` (not remove) and I only call it from the main `IOLoop` thread (though I have another thread running). The structure of my application is:

```
app
 |
 +---main.py
 +---server_lifecycle.py
 +---common.py
```

The logic is such that `server_lifecycle.py` defines `on_server_load` starting a thread which generates some data and saves it in a `ColumnDataSource` defined in `common.py` and imported by `main.py` as well. `main.py` defines an `on_change` callback for the data of the source, so it knows when new data arrives and calls `curdoc().add_next_tick_callback` to process the data and update its document. Here's a minimal PoC:

```
# main.py

import common
from bokeh.plotting import curdoc, figure
from bokeh.models import ColumnDataSource

doc = curdoc()

# a new source, for this session
source = ColumnDataSource(data=dict(bins=[], counts=[]))

# Call this via add_next_tick_callback
def update_doc():
    source.data = common.hist.data
    pass

# Schedules an update when the receiver thread updates common.hist.data
def update_source(attrname, old, new):
    doc.add_next_tick_callback(update_doc)

common.hist.on_change('data', update_source)

########## Session document
plot = figure(output_backend='webgl')
# same with canvas
# plot = figure(output_backend='canvas')

bars = plot.vbar(x='bins', top='counts', width=1, source=source)
doc.add_root(plot)
```

```
# common.py
from bokeh.models import ColumnDataSource

# sessions should wait for a change of data and only read it
hist = ColumnDataSource(data=dict(bins=[], counts=[]))
```

```
# server_lifecycle.py

from threading import Thread
from numpy.random import rand
from time import sleep
import common

def on_server_loaded(server_context):
    
    def updater():
		    dsize=100
        while True:
            data = dict(bins=rand(dsize), counts=rand(dsize))
            common.hist.data = data
            sleep(0.1)
    
    
    thread = Thread(target=updater)
    thread.daemon = True
    thread.start()
```

Results in:

```
2018-03-01 20:07:23,410 Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fa38b079730>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 605, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.6/dist-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/util/tornado.py", line 135, in wrapper
    self.remove_next_tick_callback(callback)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/util/tornado.py", line 161, in remove_next_tick_callback
    self._remove(callback, self._next_tick_callbacks)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/util/tornado.py", line 156, in _remove
    self._error_on_double_remove(callback, callbacks)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/util/tornado.py", line 118, in _error_on_double_remove
    raise ValueError("Removing a callback twice (or after it's already been run)")
ValueError: Removing a callback twice (or after it's already been run)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/path/to/poc/server_lifecycle.py", line 12, in updater
    common.hist.data = data
  File "/usr/local/lib/python3.6/dist-packages/bokeh/core/has_props.py", line 263, in __setattr__
    super(HasProps, self).__setattr__(name, value)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/core/property/descriptors.py", line 931, in __set__
    self._internal_set(obj, value, hint=hint, setter=setter)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/core/property/descriptors.py", line 727, in _internal_set
    self._real_set(obj, old, value, hint=hint, setter=setter)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/core/property/descriptors.py", line 796, in _real_set
    self._trigger(obj, old, value, hint=hint, setter=setter)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/core/property/descriptors.py", line 873, in _trigger
    obj.trigger(self.name, old, value, hint, setter)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/model.py", line 543, in trigger
    super(Model, self).trigger(attr, old, new, hint=hint, setter=setter)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/util/callback_manager.py", line 120, in trigger
    invoke()
  File "/usr/local/lib/python3.6/dist-packages/bokeh/util/callback_manager.py", line 116, in invoke
    callback(attr, old, new)
  File "/path/to/poc/main.py", line 17, in update_source
    doc.add_next_tick_callback(update_doc)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/document/document.py", line 183, in add_next_tick_callback
    return self._add_session_callback(cb, callback, one_shot=True)
  File "/usr/local/lib/python3.6/dist-packages/bokeh/document/document.py", line 812, in _add_session_callback
    raise ValueError("callback has already been added")
ValueError: callback has already been added
```

It happens only with a small enough sleep interval, and large enough data (or even with an array of length 1, if I start dragging on the plot).

**Comment by bryevdv** [comment] 2018-03-01 18:10
@aayla-secura i am glad you found a workaround, though just FYI I feel compelled to state that I would not consider any shared use of a Bokeh model between sessions as you are doing with the CDS in `common.py` to be a supported practice. Bokeh models should be created and exclusively confined to sessions.

**Comment by aayla-secura** [comment] 2018-03-03 22:25
@bryevdv , the data I am reading in to common.hist comes from the network and should be the same for all sessions. It is not modified in any session, rather each session sets up a callback, waiting for common.hist to change and then makes a local copy of it. How else can more than one session read the same data from a TCP socket (well they can if using ZMQ PUB-SUB, but it would still require spawning a new thread every session, doesn't scale well). I thought I can get away with spawning a thread by using unlocked callbacks and futures, but couldn't get it to work (the server was still getting locked up). Anyway, this is not related to this issue, so I don't want to span the thread, but I'm open to suggestions on a better way to implement live-plotting of streaming data from the network.

**Closed** 2018-03-27 17:55 UTC
Labels: tag: component: server, type: bug
