### ISSUE TITLE
CheckboxButtonGroup bug

### ISSUE THREAD

**Issue by dwhcho** [bokeh/bokeh#7626] opened 2018-03-13 17:25 UTC
There seems to be a bug for the CheckboxButtonGroup. This can be seen in the demo on the bokeh widgets page https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/widgets.html. For example, click off Option 1 and clicking back on will also deactivate Option 2.

**Comment by bryevdv** [comment] 2018-03-13 18:04
I believe this is a dupe of #7562

**Closed by bryevdv** 2018-03-13 18:04 UTC
