### ISSUE TITLE
0.12.6 HoverTool not in gridplot with merged tools

### ISSUE THREAD

**Issue by rocheseb** [bokeh/bokeh#6723] opened 2017-08-04 12:24 UTC
The HoverTool does not appear in the toolbar of gridplot layouts since 0.12.6 when merged tools is True.

**Comment by julioasotodv** [comment] 2017-08-04 16:55
Indeed, it does not appear even if all models inside the gridplot include it.

**Comment by bryevdv** [comment] 2017-08-05 16:01
This is a duplicate of https://github.com/bokeh/bokeh/issues/5497

**Comment by julioasotodv** [comment] 2017-08-05 16:08
Indeed.Perhaps rocheseb agrees and closes it.

**Comment by bryevdv** [comment] 2017-08-05 16:09
Thanks, I meant to close it a minute ago but got distracted.

**Closed** 2017-08-05 16:09 UTC
Labels: reso: duplicate, type: discussion
