### ISSUE TITLE
[FEATURE] Add a way to disable hovering for `Image` and `ImageRGBA`

### ISSUE THREAD

**Issue by hoxbro** [bokeh/bokeh#14141] opened 2024-11-05 17:26 UTC
### Problem description

Currently (and to my knowledge), when you add a HoverTool to an `Image` or `ImageRGBA`, it will show a HoverTool for the data, even if there is no data. 

A simple example is the bottom left corner in this example will show `NaN` if you hover over it.  

``` python
import numpy as np
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure, show

N = 100
x = np.linspace(0, 10, N)
y = np.linspace(0, 10, N)
xx, yy = np.meshgrid(x, y)
image = np.sin(xx) * np.cos(yy)
image[: N // 2, : N // 2] = np.nan  # For these points no hover should be shown

source = ColumnDataSource(
    data={"image": [image], "x": [0], "y": [0], "dw": [10], "dh": [10]}
)
p = figure(x_range=(0, 10), y_range=(0, 10))
p.image(image="image", x="x", y="y", dw="dw", dh="dh", source=source)

hover = HoverTool(tooltips=[("Pixel Value", "@image")])
p.add_tools(hover)

show(p)
```

![image](https://github.com/user-attachments/assets/99bd357a-0537-4b88-b892-dd815f17972f)

### Feature description

Add a way to disable hover for specific ranges or a value for `Image` and `ImageRGBA`. 

### Potential alternatives

None, but I'm open to suggestions!

**Comment by bryevdv** [comment] 2024-11-06 00:06
`nan` is still data, the question is whether to show it. I actually think this is a duplicate of 

* https://github.com/bokeh/bokeh/issues/9087

which is an issue to provide a generic CustomJS hook for a hover filter policy, e.g. if you want to inspect the hit-indices and remove all the ones that correspond to `nan` in some CDS column, you could do that. (FYI the original motivation a `hit_filter` was to be able to reduce the number of tooltips when there are multiple hits). 

I did make a stab at this issue at one point quite awhile back, thinking it would be fairly trivial, but ran into some unexpected difficulties. But maybe I can take a look again soon (or if anyone else wants to, I am happy to advise or review or help)

**Closed as completed by bryevdv** 2024-11-06 00:06 UTC
Labels: reso: duplicate
