### ISSUE TITLE
Legend should automatically adjust to plot's size

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4213] opened 2016-04-21 22:18 UTC
If plot's size is too small, legend can take up significant part of canvas, obscuring the plot. There should be some policy for making legend less obstructive in such situation. The simplest approach is to hide the legend entirely if takes, lets say, `>= 25%` of canvas area. It could also change orientation automatically (it would be useful if only one of plot's dimensions was really small. Long term solution would be to make legend act like a tooltip. It would collapse to a small button that would show the legend on hover.

**Comment by almarklein** [comment] 2016-04-22 08:26
>  The simplest approach is to hide the legend entirely if takes, lets say, >= 25% of canvas area.

I'd be -1 on hiding it completely, unless you mean "It would collapse to a small button that would show the legend on hover."

Small note: `legend.position = xxx` currently does not update directly, but needs a resize to take effect.

**Comment by almarklein** [comment] 2016-04-22 08:42
Another thing. If the legend is added to the plot when there is no data yet, it is positioned. relatively far to the left, because there are no ticks on the left. Then when the datasource gets populated, ticks appear, but the legend does not get repositioned (until a resize), which makes the legend disappear partly under the left tick-area.

**Comment by mattpap** [comment] 2016-04-22 10:06
> Not sure if there is a sensible way to fix this though..

It's fixed in PR #4212.

**Comment by bryevdv** [comment] 2016-04-22 16:39
> I'd be -1 on hiding it completely, unless you mean "It would collapse to a small button that would show the legend on hover."

I the example I was shown with small plots, a legend would take up >90%, rendering the plot entirely useless. I agree that a longer term solution is to provide alternative interactions to present the legend. But in the short term, something that moves the needle from "useless" to "not quite as useful as it could be" is still an improvement. 

So, maybe we can add the "hiding" option in a way that leaves the door open?
```
oversize_policy = None     # what there is now
oversize_policy = "hide"   # what is added short term
oversize_policy = "popup"  # for the future
```
something along those lines?

**Comment by almarklein** [comment] 2016-04-22 20:23
Yes that makes sense. I wrongly assumed that the plan was to make it the default behavior to hide the legend, which I imagine would lead to a confusion. When a prop has to be set to enable the hiding, the user should be aware of it.

**Comment by bryevdv** [comment] 2016-06-12 02:59
@bokeh/dev Now that legends can appear outside of plots I propose to simply close this with `wontfix`.  Opinions?

**Comment by almarklein** [comment] 2016-06-12 20:00
Does the fact that legends can appear outside of a plot really solve the original problem? If there is simply very little space, then putting the legend outside will make the plot even smaller ...

**Comment by birdsarah** [comment] 2016-06-15 14:19
"Long term solution would be to make legend act like a tooltip. It would collapse to a small button that would show the legend on hover."

I am +1 on this as a feature.

**Comment by omearac** [comment] 2016-07-20 15:09
Hi everyone, any progress on this feature??

**Comment by almarklein** [comment] 2016-07-21 09:10
@omearac at this point work on this has not started yet as there are other issues that have a higher priority.

**Comment by nhoening** [comment] 2018-10-08 10:42
Rare that this is not getting more attention - I'd think being able to look at plots in responsive fashion and on smaller screens  should be rather important. Legends overlaying data are a nuisance.

I cannot easily tell how responsiveness is adressed in the upcoming 1.0 release. #7708 might be relevant, but what that really means is going over my head :)

**Comment by bryevdv** [comment] 2018-10-08 16:36
> I cannot easily tell how responsiveness is adressed in the upcoming 1.0 release. 

The layout work has been pushed to 1.1 since it is a large effort and we cannot get it done as quickly as we had wanted. The 1.0 release is about API stability and now that we have a stable API we are ready to defend going forward, it is important for a variety of reasons to get that out the door. 

But in any case that work does not really affects legend. To be perfectly frank the Bokeh team is under-resourced and lacks depth in the area of mobile web design. It's a specific area that will probably not see much movement until some new contributors decide to get involved. 

>  #7708 might be relevant, but what that really means is going over my head :)

Not really. Currently legends are drawn on an HTML canvas. If you really want something responsive, then some sort of new DOM-based legend will probably be necessary. but then the drawing of the actually representative glyphs might mean having to manage several small sub canvases. Not impossible by any stretch, but also definitely not trivial. As I mentioned the fasted way for this to move forward is for a new contributor to decide to champion it.

**Comment by bryevdv** [comment] 2020-06-20 03:58
I don't think we will ever do anything with the current on-canvas legend. There is simply way too much wheel re-inventing that would need to happen just to reproduce what the browser itself is already good at. I have opened a new issue #10205 to discuss requirements for a new DOM-based legend option.

**Closed by bryevdv** 2020-06-20 03:58 UTC
Labels: type: discussion
