### ISSUE TITLE
Graph node selection cannot change size 

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#6979] opened 2017-09-28 19:52 UTC
When using the new graph functionality, if I set the selection_glyph size to a different size from the initial size setting for the marker.

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh version: 0.12.9

#### Description of expected behavior and the observed behavior
Expect the market to change to the new size

#### Complete, minimal, self-contained example code that reproduces the issue
Take the examples/models/file/graphs.py example and in the `create_graph()` function change 

`graph_renderer.node_renderer.selection_glyph = Circle(size=15, fill_color=Spectral4[2])` 
to
`graph_renderer.node_renderer.selection_glyph = Circle(size=45, fill_color=Spectral4[2])`

**Comment by hsparra** [comment] 2017-09-28 19:58
Note: changing the `line_size` of an edge works as expected.

**Comment by bryevdv** [comment] 2018-03-17 04:11
Possibly related related to #3405 and #2367

**Comment by mattpap** [comment] 2023-10-29 22:36
Duplicate of issue #2367.

**Closed by mattpap** 2023-10-29 22:36 UTC
Labels: reso: duplicate
