### ISSUE TITLE
Use different image in place of logo?

### ISSUE THREAD

**Issue by bs1234** [bokeh/bokeh#3081] opened 2015-11-06 20:28 UTC
Great package, thank you all for your considerable efforts. 

Question on the logo: Is it possible to replace the bokeh logo with a different (user specified) image?
I see it can be set to any of 'normal', 'grey' or removed completely with:

p = figure(...)
p.logo = None

But I was hoping to add a different image in it place, perhaps via:

p.logo = path_to_image.png

Is there a simple way to currently do this?

**Comment by bryevdv** [comment] 2015-11-06 20:43
There's not currently any way to specify that that I am aware of but we could consider a PR that added that functionality.

**Comment by bs1234** [comment] 2015-11-06 20:51
Hmmm,ok,  I guess I shouldn't have asked if I wasn't willing to do it myself...

As i'm new to all this: is the protocol to open a PR and its ok to sit open for a lengthy period of time? or should i only open it when I plan to actually work on it?

thanks and sorry for the basic question

**Comment by bryevdv** [comment] 2015-11-06 20:55
No, it's always OK to ask, but I can also state that this feature is not going to be near the top of our current priorities. Our PR lifecycle and management are laid out in BEP-1:

https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management

A PR will be set inactive after a long period of time but they can also always be re-opened so I'd say its up to you.

**Comment by bryevdv** [comment] 2016-04-10 01:48
This is a dupe of #3820 That one is newer but it's a planned issue, so closing this one in favor of it.

**Closed by bryevdv** 2016-04-10 01:48 UTC
Labels: type: feature
