### ISSUE TITLE
Weird plot behavior 

### ISSUE THREAD

**Issue by crashMOGWAI** [bokeh/bokeh#5598] opened 2016-12-21 16:15 UTC
After running this code, clicking on the cells of the table should cause the line to redraw. This behavior isn't necessarily tied to the table because I've noticed it before when picking from line plots. Haven't run across this in the issues, is it known?

```
from bokeh.client import push_session
from bokeh.io import curdoc
from bokeh.plotting import figure, ColumnDataSource
from bokeh.models import HoverTool
from bokeh.models.widgets import TableColumn, DataTable
from bokeh.layouts import layout
import pandas as pd
import os

os.system('bokeh serve')

def make_data():
    global rawdata
    rawdata = pd.DataFrame({
        'A':[2,3,4,5,6,7,8,9,10,11,12],
        'B':[884,1100,794,1200,1100,590,864,668,373,887,1006],
        'C':[5083,5163,4981,4927,5000,5110,5212,5333,5440,5541,5668]})`        
    return rawdata

global source
source = ColumnDataSource(make_data())

def make_plot():
    """build up data plot
    """
    plot1 = figure(
        plot_width=400, plot_height=400,
        toolbar_location='right',
        tools='pan,reset,save,wheel_zoom,hover')
    plot1.title.text = "Plot Title"
    plot1.xaxis.axis_label='THIS'
    plot1.yaxis.axis_label='THAT'
    
    tooltips="@A"
    plot1.select_one(HoverTool).tooltips= tooltips

    plot1.line(x='A', y='B',
        source = source, 
        line_width=5, line_color="blue", alpha=1)
    plot1.circle(x='A', y='B',
        source = source,
        size=5, fill_color="purple", alpha=1)
    return plot1   

def make_layout():
    """main worksheet layout
    """
    plot1 = make_plot()
        
    #define table 
    columns = [
        TableColumn(field="A", title="THIS"),
        TableColumn(field="B", title="THAT")]
    data_table = DataTable(
        source=source, columns=columns, width=400, height=400, editable=True)
    #set overall layout
    worksheet = layout([plot1],[data_table])
        
    return worksheet

#setup server and push worksheet
curdoc().add_root(make_layout())
curdoc().title='Whatever Stuff'
session = push_session(curdoc())
session.show()

if __name__ == "__main__":
    session.loop_until_closed()
```

**Comment by bryevdv** [comment] 2016-12-21 17:16
Hi,

I don't seen any callbacks (either the CustomJS or python .on_change kind) so I am not quite sure what is expected. Can you elaborate on what you are expecting to see, vs what you are actually seeing?

Thanks,

Bryan

**Comment by crashMOGWAI** [comment] 2016-12-21 18:05
I didn't expect the line to redraw on every pick. It seems the line glyph throws out the picked point and redraws itself, is that an expected behavior? 

![error](https://cloud.githubusercontent.com/assets/17650526/21400362/5180c57a-c775-11e6-9ea3-4ba512c8caab.PNG)

**Comment by bryevdv** [comment] 2016-12-21 18:15
Hi,

Oh I see now. That is this old issue:

	https://github.com/bokeh/bokeh/issues/515

Regrettably, lines don't currently handle rendering selections well, and also selections propagate automatically on shared data sources. I am afraid my only current suggestion to work around is to make a new, separate copy of the data source so that the data table and the line do not share a data source. Or alternatively, to plot using scatter markers like circle, instead of a line. 

BTW would you add this code (or a link to this ML thread) to that issue? Having a test case handy will help whenever that issue can be investigated. Having actually implemented a similar system in a different context many years ago, I can say it will be a little involved to fix, unfortunately. 

Thanks,

Bryan

**Comment by bryevdv** [comment] 2016-12-21 18:16
dupe of #515

**Closed by bryevdv** 2016-12-21 18:16 UTC
