### ISSUE TITLE
Disabled Buttons still call callbacks when clicked

### ISSUE THREAD

**Issue by tobyhodges** [bokeh/bokeh#4940] opened 2016-08-10 15:53 UTC
Button widgets, when disabled, still invoke their callback function when clicked. Using the example code below, the message 'Start button was clicked' can be seen in the browser console when the (disabled) button is clicked.

``` Python3
from bokeh.models import Button, CustomJS
from bokeh.plotting import show

callback = CustomJS(code="""
    console.log('Start Button was pressed.')
""")

button_one = Button(label="Start", disabled=True, callback=callback)
show(button_one)
```

**Comment by birdsarah** [comment] 2016-08-10 17:54
I remember having a conversation about this exact thing while I was working on the layout work, but I can't find it quickly. Maybe it was on the mailing list.

I have some vague notion that it came up that the event was desirable. But I remember thinking exactly the same thing - if the button's disabled it shouldn't fire events.

@bryevdv does any of this ring a bell, am I going mad?

**Comment by tobyhodges** [comment] 2016-08-11 07:36
From my perspective, while I concede that there might be cases where firing the callback would still be desirable, I expected the default behaviour to be that disabling the button disables the callback. Perhaps if there was an attribute for the widget, called e.g. `callback_when_disabled`?

**Comment by bryevdv** [comment] 2016-08-11 16:37
IMO disabled widgets should be greyed, non-interactable, and (as a consequence) never fire callbacks. I'm not sure what "disabled" would mean otherwise.

**Comment by JasonSickler** [comment] 2016-10-04 14:23
I experienced that disabled isn't respected (Toggle() in particular), which tripped me up given the documentation of the disabled parameter:  "If True, the widget will be greyed-out, and not respond to UI events."  I think nearly everyone would expect, particularly by comparison to other languages, that this should completely deactivate the widget, and it's callbacks.

I realize you guys only have so much time and a priority list.  I want to get a rough idea of when it might be addressed, for my own planning (using Bokeh on a project that is subject to deadlines).  Thanks guys!

**Comment by bryevdv** [comment] 2016-12-21 02:30
This is actually a dupe of #1376

**Closed by bryevdv** 2016-12-21 02:30 UTC
Labels: tag: starter, tag: widgets, type: bug
