### ISSUE TITLE
Add ability to embed plots using `components` when they have User Defined Models

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3665] opened 2016-01-15 19:38 UTC
See #3632 for the problems that happened when trying.

The solution was to use the resources called EMPTY. When you render them, they spit out the CustomJS.

It would probably be more intuitive if this was included in the JS output from components.

The only slight gotcha is explaining the need to include the Bokeh compiler.

**Comment by mattpap** [comment] 2016-01-18 16:47
> It would probably be more intuitive if this was included in the JS output from components.

That's a at least a temporary solution.

> The only slight gotcha is explaining the need to include the Bokeh compiler.

And here we get to less temporary solution: resource bundles. Currently we have wrong view on resources in bokeh, which makes features like optional dependencies cumbersome to implement.

**Comment by birdsarah** [comment] 2016-02-24 19:48
Did this get fixed @mattpap @brendancol, I have this feeling that it did.

**Comment by mattpap** [comment] 2016-02-24 20:37
A workaround was suggested, but `components()` is still cumbersome to use in the given context, so still needs work, which I will hopefully do for 0.12.

**Comment by bryevdv** [comment] 2016-06-12 01:48
@mistakevin recently ran into this, I'd forgotten the (current) solution was in the tracker here. Nothing #4127 seems related.

**Comment by bryevdv** [comment] 2017-05-12 02:37
is this not a dupe of #3632 ?  @birdsarah @mattpap

**Comment by bryevdv** [comment] 2017-06-22 04:09
I tested the latex custom extension, which relies on external resources, by rendering an HTML file with it using `components`. It worked fine, so closing this now.

**Closed by bryevdv** 2017-06-22 04:09 UTC
Labels: type: feature
