### ISSUE TITLE
Weird left toolbar in gridplots in dev build and master

### ISSUE THREAD

**Issue by mdagost** [bokeh/bokeh#4246] opened 2016-04-28 19:37 UTC
I'm seeing weird behavior with the toolbar both on the 0.12.0dev8 conda build and when building from source off of the current master.  Anytime I make a gridplot, the toolbar ends up like this:  

![screen shot 2016-04-28 at 2 33 08 pm](https://cloud.githubusercontent.com/assets/1334817/14898768/2e8507ca-0d4e-11e6-861e-b939374a7663.png)

The toolbar elements are still functional; there's just something wrong with the icons.

Some simplified code:

```
col_a = np.array([0])
col_b = np.array([0])
col_c = np.array([0])

data = ColumnDataSource(data=dict(col_a=col_a, col_b=col_b,col_c=col_c))

left_hover = HoverTool(
        tooltips=[
            ("x", "@col_a"),
            ("y1", "@col_b")
        ])

left = figure(title="y1 vs. x", x_axis_label="x", y_axis_label="y",
                  x_range=[0, 1], y_range=[0, 1], plot_width=600)
left.add_tools(left_hover)
left.circle("col_a", "col_b", source=data)
left.add_tools(BoxSelectTool())

right_hover = HoverTool(
        tooltips=[
            ("x", "@col_a"),
            ("y2", "@col_c")
        ])

right = figure(title="y2 vs. x", x_axis_label="x", y_axis_label="y", plot_width=600,
              x_range=left.x_range, y_range=[0, 1])
right.add_tools(right_hover)
right.add_tools(BoxSelectTool())
right.circle("col_a", "col_c", source=data, color="red")

show(gridplot([[left, right]]))
```

**Comment by birdsarah** [comment] 2016-04-28 20:08
I have seen this. @mattpap is currently working on toolbar stuff and I'm currently working on layout. Hopefully between the two this will get fixed for 0.12. There may be another issue

**Comment by mattpap** [comment] 2016-05-02 11:54
It's broken since one of `ts_apiN` PRs. That will be taken care of before 0.12.

**Comment by koganm** [comment] 2016-05-09 00:10
hi all,

great new features in 0.12.0dev8, playing around with gridplot example now and am seeing the missing icons as well. however this version does look to have the fix from 0.11 where using vform would cause duplicate empty axes above the legit charts. any estimate on when the version with the icon fix will be released?

thx

**Comment by koganm** [comment] 2016-05-10 15:35
btw, i found a temporary workaround to this left toolbar issue:
i'm running bokeh serve in one virtual env with bokeh version 0.11.0 set up, and connecting to the server via the bokeh.client library using bokeh version 0.12.0.dev8. this way i don't get any duplicate empty axes and all the app icons show up correctly when i use vform.

thx

**Comment by bryevdv** [comment] 2016-06-09 00:42
AFAIK this is fixed in master and the latest dev build. Please re-open if the issue is found to persist.

**Closed by bryevdv** 2016-06-09 00:42 UTC
Labels: type: bug
