### ISSUE TITLE
Remove locks from Bokeh server

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#4068] opened 2016-03-25 14:57 UTC
I would like to include tornado coroutines within my bokeh server application.  Some of these coroutines wait on external events.

```python
@gen.coroutine
def f():
    result = yield tornado_future
    source.update(...)
```

Or are long running

```python
@gen.coroutine
def f():
    while True:
        result = yield tornado future
        source.update(...)
```

If I submit these to the bokeh document like so:

    curdoc().add_next_tick_callback(f)

Then they'll run, but they'll also block all other Bokeh callbacks from running until they finish, despite the fact that they politely yield control.  This is because the Bokeh server employs locks to protect state and communication channels.  As a result, no updates happen while these coroutines continue to wait on external events.

The current solution to this is to poll:

```python
@gen.coroutine
def f():
    if tornado_future.done():
        source.update(...)

curdoc().add_periodic_callback(f, some_short_interval)
```

But this is suboptimal.  For intuitive and fully reactive server applications it would be nice if the Bokeh server did not significantly protect the Tornado IOLoop.  Other applications (like the Jupyter notebook server) do this and it greatly improves the extent to which they interoperate with other systems in reactive ways.

To this end it would be nice to remove locks so that Bokeh could trust other coroutines on the main Tornado event loop to not come in an inopportune times.  

After a conversation with @havocp I believe that there are two reasons why locks are in use today:

1.  Bokeh yields at times when it is in an illegal state
2.  Several places may write to the same IOStream, causing garbled messages

I suspect that both of these issues are resolvable:

1.  Ensure that all state changes happen atomically between yield points
2.  Linearize all communications on each IOStream through a queue

However, my experience with Bokeh is weak and there are probably situations with which I am unfamiliar.  It would be good to get an exhaustive list of where the locks are necessary so that solutions could be found.

**Comment by havocp** [comment] 2016-03-25 15:08
For me I'd have to really spend some time to see when the document lock is currently important.

Another option is to have ways to add callbacks that don't add the auto-lock-document wrapper, and then inside those unlocked callbacks you'd have to either avoid the document or lock it yourself. Eliminating the document lock is probably more elegant though if we could prove it safe.

**Comment by bryevdv** [comment] 2016-04-07 22:18
dupe of #3702

**Closed by bryevdv** 2016-04-07 22:18 UTC
Labels: type: discussion

**Comment by pitrou** [comment] 2016-12-08 17:06
Where is this "document lock" defined? I can find no mention of it in the few places I've looked in.

Regardless, there's a decorator called `without_document_lock` in `bokeh/document.py` that may do the trick... though, being a decorator, it's unsure it would work appropriately on a coroutine.

**Comment by pitrou** [comment] 2016-12-08 17:16
Ok, I've found the lock in ServerSession (`bokeh/server/session.py`) :-) I guess I'm a bit surprised: I would have expected the document lock to be stored on the document object. Does a Bokeh application have access to the server session object?

**Comment by bryevdv** [comment] 2016-12-08 17:22
I am fairly certain the session for a document can be gotten to with enough effort in the app code, but I'd have to go digging to verify how.

**Comment by bryevdv** [comment] 2016-12-08 17:23
@havocp do you have any quick context on why the lock is where it is?

**Comment by havocp** [comment] 2016-12-08 17:35
A session is the only context in which a lock makes sense (because concurrent access is possible). The document is just a "dumb document" (tree of models, the "data" being served), while the session is all the logic around hosting that document in a dynamic web server. Documents can be used without sessions (for example, to generate static html), and in that case there's no point in locking (or coroutines, or anything of that nature). We don't want server stuff leaking out of the server/ subdirectory, basically.

IIRC the locking is meant to ensure that multiple http requests (or websocket message handlers or callbacks) don't modify the document at the same time and step on each other, but as noted earlier on this issue, even when it was fresher in my mind I didn't remember some of the exact scenarios the lock was trying to protect against. The issue is that every "yield" lets other callbacks or handlers run, so the document could be in an arbitrary state after each yield, without the lock. The first thing I'd probably do if tackling this issue is try to catalog all the "yield" while the lock is held, and consider what happens if (for example) half the document is deleted during that yield. Then the question is whether that's ok, or how to handle it besides with locking.
