### ISSUE TITLE
Datatables do not update properly for on_change events 0.12.7

### ISSUE THREAD

**Issue by lazmol** [bokeh/bokeh#6863] opened 2017-09-01 20:47 UTC
Hi,

thanks for all the development on Bokeh.
I noticed with the latest Bokeh version 0.12.7 the DataTable does not update properly for on_change events. See for instance the [car data table example](https://github.com/bokeh/bokeh/raw/master/examples/models/server/data_tables.py).
To reproduce:
-run the example preceded by "bokeh serve"
-select some filters from the drop down menus
-observe strange behaviours like at first filter showing unidentifed in the table, or when changing back to All (i.e. no filtering on the dataframe) the table still shows some filtered data.
I am not sure this is because the example has to be updated to 0.12.7 or some coding is wrong with 0.12.7.

Thanks and best regards,
Laszlo

**Comment by bryevdv** [comment] 2017-09-05 03:47
This is a bug, and it will be fixed at some point, however:

This usage of `bokeh.client` (with `loop_until_closed` to run an app "outside" the server) was a mistake to ever demonstrate. It is not suitable for any real use case. I have tried to publicly discourage using Bokeh in this way as loudly and as often as I can, but the message does not seem to be taking.  Please see https://github.com/bokeh/bokeh/issues/6887 for a discussion regarding removing all examples or mention of this usage.

**Comment by bryevdv** [comment] 2017-09-05 03:48
similar to #6092

**Comment by ashern** [comment] 2017-09-06 15:14
I have a similar issue with the Datatable not updating properly. I am trying to dynamically update the table contents from a dataframe by calling on the table's ColumnDataSource:

`source.data = source.from_df(df)`

The table contents update - but not correctly. Sometimes rows will be missing. Sometimes many rows will appear displaying 'undefined' in every cell.

Is there something I need to do beyond the single line above to get the contents to properly refresh?

My problem seems related to this issue, but if not I'm happy to open under separate cover.

Thank you very much - great library.

**Comment by DuCorey** [comment] 2017-09-12 17:32
Hi. 
I don't believe this is an issue with the ```loop_unitl_closed```. I've had this issue on the application I'm building as well since 0.12.7. I found a hack that could be added to the python script that fixes the issue.

```
data_table_force_change = CustomJS(args=dict(source=source), code="""
    source.change.emit()
""")
source.js_on_change('data', data_table_force_change)
```
With ```source``` being the ```ColumnDataSource``` attached to the Table.

I haven't had the time to debug the issue further, but I'm hoping this fix can help someone else until the issue is fixed.

**Comment by lazmol** [comment] 2017-09-14 13:27
Hello,

ok so loop_until_closed is not recommended. But then, could you tell me what is the recommended way to make interactive plot with widgets?
There should just be a curdoc().add_root(widgets) in the main and then run it with bokeh serve --show plot.py?
Can you point to an up-to-date example which shows the correct way (ideally with datatable and a plot)?

Thanks!

**Comment by bryevdv** [comment] 2017-10-11 15:46
@lazmol This example has a datatable and a widget:

https://github.com/bokeh/bokeh/tree/master/examples/app/export_csv

Adding a plot would be simple addition (as shown in the other other examples)

**Comment by bryevdv** [comment] 2017-10-11 15:46
This was fixed with https://github.com/bokeh/bokeh/pull/7036

**Closed by bryevdv** 2017-10-11 15:46 UTC
Labels: tag: component: server, type: bug
