### ISSUE TITLE
"Unrecognized side" error in SizePanel due to null default

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5221] opened 2016-09-23 16:06 UTC
This appears in tests. Either a proper default value should be set for `side` or the code should guard against `null`. Also, please don't overuse logging when `throw new Error('bla')` (a hard error) is more appropriate.

**Comment by birdsarah** [comment] 2016-09-24 05:08
dupe of #4539?

**Comment by birdsarah** [comment] 2016-09-24 05:10
dupe of #5063?

**Closed** 2016-12-09 16:29 UTC
Labels: reso: duplicate, tag: component: bokehjs, type: bug
