### ISSUE TITLE
Refactor deploy.sh

### ISSUE THREAD

**Issue by brittainhard** [bokeh/bokeh#4904] opened 2016-07-29 15:27 UTC
There is a lot of cruft in `deploy.sh`. This can be refactored.

- [ ] Separate common build actions into functions.
- [ ] Add a list of files needed for pushing a release, i.e. `version.coffee`, `package.json`, sphinx `conf.py`

**Comment by bryevdv** [comment] 2016-10-27 02:49
dupe of #5325

**Closed by bryevdv** 2016-10-27 02:49 UTC
Labels: tag: component: build, type: task
