### ISSUE TITLE
Notebook with linked legend causes plot to render multiple times

### ISSUE THREAD

**Issue by djbarker** [bokeh/bokeh#8158] opened 2018-08-10 15:38 UTC
Versions:
* nbconvert: 5.3.1
* python: 3.6.4
* bokeh: 0.12.13

Example:
```python
from bokeh.io import output_notebook, show
from bokeh.models import Legend
from bokeh.plotting import figure
from bokeh.layouts import gridplot
import numpy as np

output_notebook()

plot1 = figure(width=200, height=200)
plotl = figure(width=200, height=200)

x = np.linspace(0, 10, 50)
y = np.sin(x)
z = np.cos(x)

l1 = plot1.line(x, y)

plotl.add_layout(Legend(items=[('foobar', [l1])])) 
plotl.legend.click_policy = "hide"

show(plotl)
# show(gridplot([[plot1, plot2]]))  # this also fails
```

Running the preceding code in a notebook is okay and it renders what one would expect. If the notebook is then converted to an HTML file using `nbconvert` _or_ the notebook is reloaded from Jupyter Notebook / Lab the plot just continually renders an increasing number of copies of itself eventually rendering the browser unresponsive.

**Comment by bryevdv** [comment] 2018-08-10 15:41
Can you reproduce this with the latest version? If not, this can be closed. We have no resources to develop on or patch old releases.

**Comment by djbarker** [comment] 2018-08-10 15:46
It's still an issue with bokeh 0.13.0

**Comment by bryevdv** [comment] 2018-08-10 15:53
Can you possibly attach a gif screen capture of this in the process of happening?

cc @canavandl

**Comment by djbarker** [comment] 2018-08-10 15:58
Unfortunately not right now, I can have a look when I get more of a chance. I suppose it's also useful, this was in Chrome 64.0.3282.167 (Official Build) (64-bit).

**Comment by bryevdv** [comment] 2018-08-10 15:59
Well, the issue is that I am unable to reproduce any problem with notebook reloads on either safari or chrome on osx. What versions of juptyter tools?

**Comment by djbarker** [comment] 2018-08-10 16:04
Ah, yes also probably useful:
```
$ jupyter --version
4.4.0
```
This is on linux, too.

**Comment by bryevdv** [comment] 2018-08-10 16:06
I seem to have the same:
```
❯ conda list jupyter
# packages in environment at /Users/bryanv/anaconda/envs/013:
#
# Name                    Version                   Build  Channel
jupyter_client            5.2.3                    py36_0
jupyter_core              4.4.0            py36h79cf704_0`
```

**Comment by bryevdv** [comment] 2018-08-10 16:07
I also can't reproduce any problem with `nbconvert` Output HTML renders and loads fine

**Comment by bryevdv** [comment] 2018-08-10 21:40
@djbarker Sorry, your `l` and `1` names were nearly indistinguishable, and I was not testing the correct thing. I can indeed reproduce the behavior with exactly your code. However, sharing and renderers between plots as you have done is definitely not currently supported. There is already another issue to investigate the possibility (https://github.com/bokeh/bokeh/issues/7607) so I am closing this one.

**Closed by bryevdv** 2018-08-10 21:40 UTC

**Comment by bryevdv** [comment] 2018-08-10 23:43
It definitely seems reasonable and useful (which is why the other issue is still open!) but I can't speculate offhand when we might be able to get to it. We could probably add a document validation check for this situation, but I don't think a lot of people are trying this so it's a coin flip for me as to whether the effort is justified.
