### ISSUE TITLE
`contour` doesn't render all lines completely in the docs example

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#13052] opened 2023-04-04 08:33 UTC
In the example [contour_polar](https://docs.bokeh.org/en/latest/docs/examples/topics/contour/contour_polar.html) for the usage of polar coordinates the black line is not closed. There is a gap and it looks like the black line is not completely rendered.

In the shlightly modified version of the example from the docs, where the black line has a line witdh of 4

```
import numpy as np

from bokeh.palettes import Cividis
from bokeh.plotting import figure, show, output_notebook
output_notebook()

# Data to contour is a 2D sin wave on a polar grid.
radius, angle = np.meshgrid(np.linspace(0, 1, 20), np.linspace(0, 2*np.pi, 120))
x = radius*np.cos(angle)
y = radius*np.sin(angle)
z = 1 + np.sin(3*angle)*np.sin(np.pi*radius)

p = figure(width=550, height=400)

levels = np.linspace(0, 2, 11)
contour_renderer = p.contour(
    x=x, y=y, z=z, levels=levels,
    fill_color=Cividis,
    hatch_pattern=["x"]*5 + [""]*5,
    hatch_color="white",
    hatch_alpha=0.5,
    line_color=["blue"]*5 + ["black"] + ["red"]*5,
    line_dash=["solid"]*6 + ["dashed"]*5,
    line_width=[1]*5 + [4] + [2]*5,
)

colorbar = contour_renderer.construct_color_bar(title="Colorbar title")
p.add_layout(colorbar, "right")

show(p)
```

it is easy to see.

![contour](https://user-images.githubusercontent.com/68053396/229733726-840c39b6-8fb8-42c2-bc24-a3c0cdd8ae3f.png)

The data of the black line is not the problem. In the example below all lines are closed, if 12 levels are used.

```
# Data to contour is a 2D sin wave on a polar grid.
radius, angle = np.meshgrid(np.linspace(0, 1, 20), np.linspace(0, 2*np.pi, 120))
x = radius*np.cos(angle)
y = radius*np.sin(angle)
z = 1 + np.sin(3*angle)*np.sin(np.pi*radius)

p = figure(width=550, height=400)

#  use 12 levels instead of 11
levels = np.linspace(0, 2, 12)
contour_renderer = p.contour(
    x=x, y=y, z=z, levels=levels,
    fill_color=Cividis,
    hatch_pattern=["x"]*5 + [""]*6,
    hatch_color="white",
    hatch_alpha=0.5,
    line_color=["blue"]*6 + ["black"] + ["red"]*5,
    line_dash=["solid"]*7 + ["dashed"]*5,
    line_width=[1]*6 + [4] + [2]*5,
)

colorbar = contour_renderer.construct_color_bar(title="Colorbar title")
p.add_layout(colorbar, "right")

show(p)
```

![contour_with_12_levels](https://user-images.githubusercontent.com/68053396/229734944-163c39c1-a3a1-4a53-a899-6e64685177e5.png)

<details>
### Software versions

Python version      :  3.9.10 | packaged by conda-forge | (main, Feb  1 2022, 21:24:11) 
IPython version     :  8.1.1
Tornado version     :  6.1
Bokeh version       :  3.1.0
BokehJS static path :  /opt/conda/envs/bk3/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  v17.4.0
npm version         :  8.3.1
Operating system    :  Linux-4.19.0-21-amd64-x86_64-with-glibc2.31

### Browser name and version

Chrome 111.0.5563.147 (Offizieller Build) (64-Bit)
</details>

**Comment by ianthomas23** [comment] 2023-04-04 08:51
Both the calculation and the rendering are correct. The `z` data values around the outside vary between just below and just above `1.0`, by about `1e-16`, so contour lines calculated at `z=1` are not continuous.

**Comment by mosc9575** [comment] 2023-04-04 08:56
@ianthomas23 Thanks for the explanation.

**Comment by ianthomas23** [comment] 2023-04-04 12:52
I am closing this as it is working as intended.

**Closed as completed by ianthomas23** 2023-04-04 12:52 UTC
Labels: reso: working as intended, type: discussion, tag: contour
