### ISSUE TITLE
Rotated rects are incorrectly positioned/sized

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#5808] opened 2017-01-27 16:33 UTC
Bokeh version: 0.12.4

```python
import bokeh.plotting as bp
from math import sqrt, pi

i = 1 / sqrt(2)
f = bp.figure(width=500, height=500)
f.rect([-i, 0, 0, i], [0, -i, i, 0], angle=pi / 4,
       width=1, height=1, color=['red', 'green', 'blue', 'yellow'])
```

![bokeh_plot](https://cloud.githubusercontent.com/assets/4410314/22378593/bb3136fe-e4e8-11e6-9172-519898895020.png)

There should be no gaps/overlaps between the rects.

**Comment by bryevdv** [comment] 2017-01-27 16:53
This is a dupe of the underlying situation described by #5170 

The cause of this is that the aspect ratio between the x- any y- axes is not strictly 1-1 . That is to say. 10 pixels in the x direction does not correspond to the same "data space" distance that 10 pixels in the y direction does. 

The only way to adjust for this is to make sure the that aspect ratio of the central area is 1-1. There is an open issue to make that easily specifiable. Until then you will have to use settings like `min_border` and perhaps rotating axes labels to prevent them from growing too long in the direction perpendicular to the axis, to make sure the central plot are has the the right aspect ratio.

**Closed by bryevdv** 2017-01-27 16:53 UTC

**Comment by p-himik** [comment] 2017-01-27 16:59
I believe you meant #517

**Comment by bryevdv** [comment] 2017-01-27 17:01
I did, 5170 was a "helpful" tab-completion from GH
