### ISSUE TITLE
segment plots with too-long category labels cause 'unsatisfiable constraint' errors

### ISSUE THREAD

**Issue by ahmadia** [bokeh/bokeh#2930] opened 2015-10-01 02:36 UTC
Seems to happen around 70-90 characters.

**Comment by birdsarah** [comment] 2015-10-01 02:41
My guess is this is because the solver can't lay it out. 

I had the following issue:

Using `Bokeh.Collections("Plot").at(3).set("plot_width", 106)`

The issue as I'm currently seeing it. On FF and Chrome. You can resize the image down to:
![wont go smaller](https://cloud.githubusercontent.com/assets/1796208/6184819/7290203c-b31b-11e4-9bc0-c0b9045aabcc.png)

But an attempt to go one point smaller in either width or height will give `Uncaught Error: unsatisfiable constraint`. And, perhaps more annoyingly, will render that plot non responsive to further commands.

The same error occurs with:
* negative number
* decimal number

Perhaps obviously, they do leave the object with the value set so `Bokeh.Collections("Plot").at(3).get("plot_width")` will return 100.22 if you just tried to do that.

**Comment by ahmadia** [comment] 2015-10-01 02:43
Right, setting width/height allows for longer text labels.

**Comment by birdsarah** [comment] 2015-10-01 02:44
I think the outcome we want is for the solver to fail more gracefully and to just find its own minimum and report that if it can't solve for what we want. This might mean some modifications to kiwi as I believe kiwi doesn't give us back an error gracefully.

**Comment by mattpap** [comment] 2015-10-01 18:11
I presume this is a duplicate of https://github.com/bokeh/bokeh/issues/1965.

**Comment by bryevdv** [comment] 2017-05-12 01:56
Yes i think it is a dupe

**Closed by bryevdv** 2017-05-12 01:56 UTC
Labels: tag: component: bokehjs, type: bug
