### ISSUE TITLE
DataTable: selected row no longer highlights associated glyph in plot by default.

### ISSUE THREAD

**Issue by esvhd** [bokeh/bokeh#7966] opened 2018-06-06 11:15 UTC
I noticed that in 0.12.16 (and at least 1 version ago as well), selected rows (i.e. associated glyph) in DataTable are no longer highlighted in figure. 

Has the default behaviour changed and if so is there a way to turn it back on?

Running the same code as previous versions in notebook, code example below:

```
from datetime import date
from random import randint

# from bokeh.layouts import widgetbox
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn

import bokeh.models as bkm
import bokeh

data = dict(
        dates=[i for i in range(10)],
        downloads=[randint(0, 100) for i in range(10)],
    )
source = ColumnDataSource(data)

p = bkp.figure(plot_width=300, plot_height=200)
downs = bkm.Cross(x='dates', y='downloads', size=12, line_color='blue')
g = p.add_glyph(source_or_glyph=source, glyph=downs)

columns = [
        TableColumn(field="dates", title="Date", formatter=DateFormatter()),
        TableColumn(field="downloads", title="Downloads"),
    ]
data_table = DataTable(source=source, columns=columns, width=400, height=280)

layout = bkm.layouts.Column(p, bokeh.layouts.WidgetBox(data_table))

bkp.show(layout)
```

**Comment by mattpap** [comment] 2018-06-06 12:10
I will safely assume that this is a duplicate of #7924. If fixing that issue won't help here, we will repoen.

**Closed by mattpap** 2018-06-06 12:10 UTC
