### ISSUE TITLE
ValueError in L221 of serialization.py repo

### ISSUE THREAD

**Issue by vicade-mp** [bokeh/bokeh#12050] opened 2022-03-17 23:58 UTC
### Software versions

N/A

### Expected behavior

N/A

### Observed behavior

N/A

### Example code

```Python
N/A
```

### Screenshots

<img width="1440" alt="VE 2" src="https://user-images.githubusercontent.com/67339350/158912531-3d73a757-37e8-45a6-9614-7ee0d908ccb4.png">
<img width="1440" alt="VE 3" src="https://user-images.githubusercontent.com/67339350/158912537-713c2d69-ad35-415e-ba34-000e794db898.png">

**Comment by bryevdv** [comment] 2022-03-18 00:09
Hi @vicade-mp it’s not clear what issue you are reporting. Please add a text description of the problem as well as any code (as copyable text) that will reproduce the problem, etc.

**Comment by bryevdv** [comment] 2022-03-18 00:10
Dupe of #12049

**Closed by bryevdv** 2022-03-18 00:10 UTC
Labels: TRIAGE, NEEDS MORE INFO
