### ISSUE TITLE
Group Filter accept only strings as values

### ISSUE THREAD

**Issue by doiko** [bokeh/bokeh#8108] opened 2018-07-25 06:05 UTC
Currently Group Filter accept only string as the group attribute.
There should be several cases that a non string column is considered for filtering the source.
Can this be considered in a release to follow?

**Comment by bryevdv** [comment] 2018-07-25 06:10
This is a dupe of https://github.com/bokeh/bokeh/issues/7524

**Closed by bryevdv** 2018-07-25 06:10 UTC
