### ISSUE TITLE
[BUG] SaveTool generates smaller image than plot

### ISSUE THREAD

**Issue by VictorBrugnago** [bokeh/bokeh#10249] opened 2020-07-01 00:40 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
```
Python version      :  3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.0.3
Bokeh version       :  2.1.1
BokehJS static path :  c:\users\msmegaron\anaconda3\envs\pythonmongodb\lib\site-packages\bokeh\server\static
node.js version     :  v12.13.1
npm version         :  6.12.1

OS: Windows 10 Pro 64-Bits
Browser: Opera 69.0.3686.36; Firefox 77.0.1 (64 Bits); Microsoft Edge Version 83.0.478.58 (Official build) (64-bit)
Django Version: 2.2
```

#### Description of expected behavior and the observed behavior

When I use SaveTool to save the image, the generated file is not from the full plot but only from a small area of it. Even if I change the size of the plot_width and plot_height, I can't download the full image.

#### Complete, minimal, self-contained example code that reproduces the issue

Plot file:
```
from bokeh.layouts import row
from bokeh.palettes import Set1_6
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Panel
from bokeh.models.widgets import Tabs
from bokeh.plotting import figure
from bokeh.transform import factor_cmap

import pandas as pd


def researches():
    
    data = {
        'x_axis': ['SEMINARIO', 'CONFERENCIA', 'CONGRESSO', 'OUTRA', 'COMUNICACAO', 'SIMPOSIO'],
        'values': ['7', '19', '11', '24', '32', '5']
    }

    df_plot = pd.DataFrame(data)

    # Getting Courses and Degrees
    types = list(df_plot['x_axis'])
    amount = df_plot.columns.tolist()
    amount = amount[1:]

    # Getting data source
    source = ColumnDataSource(data=df_plot)

    plot = figure(x_range=types, plot_height=400, plot_width=600, title='Curso de curta duração',
                  toolbar_location='right',
                  tools='pan, zoom_in, zoom_out, save, undo, reset')

    plot.vbar(x='x_axis', top=amount[0], source=source, width=.2, legend_field='x_axis',
              line_color='white', fill_color=factor_cmap('x_axis', palette=Set1_6, factors=types))

    layout_graph = row(plot)

    # Creating Tabs
    bar_panel = Panel(child=layout_graph, title='Pesquisadores')

    tabs = Tabs(tabs=[bar_panel])

    return tabs

```

In the view.py
```
from django.shortcuts import render

from bokeh.embed import components
from bokeh.layouts import row

from .graphs.technical_productions import short_courses

def dashboard(request, category, name):

    technical_productions_plot = row(short_courses.researches())

    tecnico_script, tecnico_div = components(technical_productions_plot)
    return render(request, 'dashboard.html',
                  {'tecnico_script': tecnico_script, 'tecnico_div': tecnico_div})
```

#### Screenshots or screencasts of the bug in action

That's what I get when I click SaveTool

![bokeh_plot (15)](https://user-images.githubusercontent.com/18515464/86190144-a2e55c80-bb11-11ea-8642-2de8015f01fc.png)

**Comment by bryevdv** [comment] 2020-07-01 01:27
@mattpap seems like the device pixel ratio stopped getting set correctly on canvas export?

**Comment by philippjfr** [comment] 2020-07-01 02:36
Can also reproduce this on my machine.

**Comment by bryevdv** [comment] 2020-07-01 02:50
I guess I assumed this was a DPR issue, but if that were the case I would expect the output to be exactly one-quarter full output. But looking at the screen shot and the code, it looks like the output is larger than that. 

However, on my machine I do get output that looks like exactly one-quarter of the canvas:

![bokeh_plot](https://user-images.githubusercontent.com/1078448/86197740-e2f51100-bb0a-11ea-9a88-cdd3664fcf6d.png)

**Comment by bryevdv** [comment] 2020-07-01 15:37
Thanks for the report @VictorBrugnago  This is fixed in the repo and will be part of the next minor release towards the end of this month.

**Closed** 2020-07-01 15:36 UTC
Labels: tag: component: bokehjs, tag: regression, type: bug
