### ISSUE TITLE
Bokeh HoverTool performance on many points selected by mouse

### ISSUE THREAD

**Issue by David-Herman** [bokeh/bokeh#6948] opened 2017-09-18 21:03 UTC
Hello,

I noticed a performance issue when dealing with many points being selected, intentionally or accidentally, by hovertool mouse. In my original use case I had a categorical x-axis with a jitter. Some categories had more or less scatter then others and at the default view those closely clustered points tended to show a noticeable performance degradation compared to other areas of my plot with only a few overlapping points.

The code example below replicates the performance issues when hovering over the cluster of points in chrome using Bokeh 0.12.9

```
output_file("Bokeh_hover_issue.html")
_tools_to_show = 'box_zoom,pan,save,hover,resize,reset,tap,wheel_zoom' 

n=1000
source = ColumnDataSource({'x':[1]+[2 for i in range(n)],
                           'y':[1]+[2 for i in range(n)],
                           'c':['string' for _ in range(n+1)] })
p = figure(plot_width=300, plot_height=300, tools=_tools_to_show,
       title="Hover tool tip slow down on multiple points")
p.circle(x=jitter('x', width=0.05),
         y=jitter('y', width=0.05),
         source=source, alpha=0.3,size=12)

hover = p.select(dict(type=HoverTool))
hover.tooltips=[('c',"@c")]

save(p)

```

![image](https://user-images.githubusercontent.com/22305345/30564275-813d36e8-9c92-11e7-8fc8-280b084b3a3d.png)

**Comment by bryevdv** [comment] 2017-09-18 21:09
There are open issues to offer better alternatives in the case of hover hittest collisions, but if you have 1000 overlapping points a hover tooltip is probably never going to be a great option. Can you characterize if this number is comparable to your actual use case?

**Comment by David-Herman** [comment] 2017-09-18 21:17
My use case is a visualization of a DB dump where the hover tool has about 10 fields with longer strings. The actual count is far less, ~100-200. The slowdown "feels" longer then the present example. The main issue is that the average y-axis range varies among the x-axis categories to produce an initial overlap in the data. This is why I chose the particular example.

**Comment by bryevdv** [comment] 2017-09-18 21:24
Well I guess one question that might inform the other issue is: what would you like to happen when a mouse hovers over 200 overlapping points? There's several possibilities (and more I have not thought of I'm sure) so it would be good to hear from someone that actually has this use-case

**Comment by David-Herman** [comment] 2017-09-19 02:36
Good question. In my visualization, I manually solved the problem by refreshing the page, turning off the hover, zooming, and then hovering on the specific categorical set where my hover tool was useful to inspect individual data point outliers that may correspond to values of interest that I can cross reference giving the information provided in the hover. This is obviously not an ideal state.

It appears that the hover tool is causing the page's length to dynamically expand which is not helpful at all since you cannot scroll down with un-hovering the data points originally selected. I am not sure what if any benefit this behavior creates.

My initial idea would be to show the "top" N points of information with a last row stating the total number not shown. N would be the number of samples where the tool tips would fit evenly within the initial plot dimensions or current browser page.

**Comment by rocheseb** [comment] 2017-09-19 20:12
You can use custom css to only allow the first tooltip to be displayed when you hover over clumped data.
```
var css = document.createElement("style");
css.type = "text/css";
css.innerHTML = ".bk-tooltip>div:not(:first-child) { display: none }";
document.body.appendChild(css);
```
This helps a bit with the hover lag over a lot of data. But it is just a visual workaround, if you use the hover_color argument you will still have clumps of selected data under the mouse.

**Comment by David-Herman** [comment] 2017-09-20 01:27
Interesting. Is there any way to access the css for the hover tool tip from the python side of Bokeh?

**Comment by rocheseb** [comment] 2017-09-20 13:32
It was probably not intended that way but you can add arbitrary html elements to the webpage via a dummy custom class for a model. Similarly you can add script divs with "global" javascript.

```
import bokeh
from bokeh.io import show
from bokeh.models import TextInput
from bokeh.plotting import figure

from random import random

dumclass_code = """
document.addEventListener 'DOMContentLoaded', (->
	setTimeout (->
		console.log document # in addition to the timeout this seems to help ensuring that all the bokeh objects have finished rendering before starting the following code

		custom_css = document.createElement('style')
		custom_css.id = 'mystyle'
		custom_css.type = 'text/css'
		custom_css.innerHTML = '.bk-tooltip>div:not(:first-child) { display: none }'
		document.body.appendChild custom_css

		return
	), 2000
	return
), false
"""

class DumClass(TextInput):
	__implementation__ = dumclass_code

fig = figure(tools='hover,wheel_zoom,pan')

x = range(10**5)
y = [random() for i in x]

fig.scatter(x,y)

show(fig)
```

**Comment by David-Herman** [comment] 2017-09-20 15:24
Interesting trick. I need to install nodejs to try it out but thanks for sharing.

```
python-2.7.10.amd64\lib\site-packages\bokeh\util\compiler.pyc in _detect_nodejs()
    140     version = ".".join(map(str, nodejs_min_version))
    141     raise RuntimeError('node.js v%s or higher is needed to allow compilation of custom models ' % version +
--> 142                        '("conda install -c bokeh nodejs" or follow https://nodejs.org/en/download/)')
    143 
    144 _nodejs = None

RuntimeError: node.js v6.10.0 or higher is needed to allow compilation of custom models ("conda install -c bokeh nodejs" or follow https://nodejs.org/en/download/)
```

**Comment by rocheseb** [comment] 2017-09-27 16:44
If you use the bokeh server you can do that with a custom template.

myapp/main.py
```
import bokeh
from bokeh.io import curdoc
from bokeh.plotting import figure

from random import random

fig = figure(tools='hover,wheel_zoom,pan')

x = range(10**5)
y = [random() for i in x]

fig.scatter(x,y)

curdoc().add_root(fig)
```

myapp/templates/index.html
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>hover</title>
    {{ bokeh_css }}
    {{ bokeh_js }}
  </head>
  <body>
    <style type="text/css">
      {% include 'styles.css' %}
    </style>
    {{ plot_div|indent(8) }}
    {{ plot_script|indent(8) }}
  </body>
</html>
```

myapp/templates/styles.css
```
.bk-tooltip>div:not(:first-child) {
	display:none;
}
```
If you save a static html file you can just add the style tag to the file yourself.

**Comment by bryevdv** [comment] 2020-02-07 05:46
#9087 is a dupe of this / how this will be handled, but more current, so closing this.

**Closed by bryevdv** 2020-02-07 05:46 UTC
Labels: type: discussion
