### ISSUE TITLE
DatePicker widget produces error

### ISSUE THREAD

**Issue by shaginhekvs** [bokeh/bokeh#6618] opened 2017-07-15 08:39 UTC
I have written the following script:

from bokeh.plotting import curdoc

from bokeh.layouts import widgetbox
from bokeh.layouts import column as bokehCol
from bokeh.models.layouts import Column
from bokeh.models.widgets import DatePicker
from datetime import date
from datetime import timedelta as td
from datetime import datetime as dt

crnt_date=dt.now()

dt_pckr_strt=DatePicker(title='Select start of sync date',min_date=date(2017,1,1),max_date=date.today())

     def callback(attr,old,new):
     
          print(type(old))
     
          print('old was {} and new is {}'.format(old,new))
     
dt_pckr_strt.on_change('value',callback)
curdoc().add_root(bokehCol(dt_pckr_strt))

I am using bokeh 0.12.6 and on running bokeh server, the following error is shown in server log when value of DatePicker is changed by clicking : 

error handling message Message 'PATCH-DOC' (revision 1): ValueError('Unknown string format',)

am I doing anything wrong ? 

also the view of the widget is primitive as shown below:

![bokeh_datepicker](https://user-images.githubusercontent.com/26320110/28237936-fa076a52-697b-11e7-920b-94af9caa7613.png)

**Comment by mattpap** [comment] 2017-07-15 08:44
This is a duplicate of #4503. This was fixed in 0.12.7-dev.

**Closed by mattpap** 2017-07-15 08:44 UTC
Labels: reso: duplicate

**Comment by shaginhekvs** [comment] 2017-07-15 13:43
Hi Mattpap I downloaded 0.12.7-dev and although the css shows up better but the value error was still there. To get the fix I followed the hack mentioned in #4965 by rheineke at bottom : go to  bokeh/core/properties.py and change line 1052 to value = dateutil.parser.parse(value.split(' (')[0]).date()  to make it work in Windows( Chrome and Explorer )

**Comment by shaginhekvs** [comment] 2017-07-15 13:49
Rather, more elegant is the following : 
           try:
                value = dateutil.parser.parse(value).date()
            except ValueError:
                value = dateutil.parser.parse(value.split(' (')[0]).date()

**Comment by mattpap** [comment] 2017-07-16 21:06
I didn't notice that there are multiple errors listed. Maybe you could submit a PR with this fix?

**Comment by mattpap** [comment] 2017-07-16 21:07
Just for reference, this is a duplicate of #4965.
