### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by alkanDol** [bokeh/bokeh#13829] opened 2024-04-16 15:12 UTC
### Problem description

There is no way to have a dynamic progress bar when a button is clicked. I wanted it to be able to follow the background process of some function when they are running after a button is clicked. 

### Feature description

Progress bar 

### Potential alternatives

Display_event with custom js without the need of an object to trigger.

**Comment by bryevdv** [comment] 2024-04-16 15:35
Dupe of https://github.com/bokeh/bokeh/issues/6556

**Closed as completed** 2024-04-16 15:35 UTC
Labels: reso: duplicate
