### ISSUE TITLE
[BUG] color definitions don't work on some glyphs

### ISSUE THREAD

**Issue by tcmetzger** [bokeh/bokeh#11667] opened 2021-09-22 18:35 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.4 (pypi)
Ubuntu, win10

#### Description of expected behavior and the observed behavior
Defining colors should work consistently for different elements of a plot. For example, this should work (but doesn't):

````
from bokeh.plotting import figure, show

p = figure()
color = "rgb(128 0 0)"
p.circle(x=[1,2,3], y=[3,4,5], size=60, color=color)
p.line(x=[1,2,3], y=[3,4,5], color=color)
p.xaxis.axis_label = "foo"
p.xaxis.axis_label_text_color = color

show(p)
````

#### Complete, minimal, self-contained example code that reproduces the issue
This works:
```
from bokeh.plotting import figure, show

p = figure()
color = "rgb(128 0 0)"
p.circle(x=[1,2,3], y=[3,4,5], size=60, color=color)

show(p)
```

This should work, but leads to a ValueError: `expected either None or a value of type Color, got 'rgb(128 0 0)'`:
````
from bokeh.plotting import figure, show

p = figure()
color = "rgb(128 0 0)"
p.line(x=[1,2,3], y=[3,4,5], color=color)

show(p)
````

This also leads to the same ValueError:
````
from bokeh.plotting import figure, show

p = figure()
color = "rgb(128 0 0)"
p.circle(x=[1,2,3], y=[3,4,5], size=60, color=color)
p.xaxis.axis_label = "foo"
p.xaxis.axis_label_text_color = color

show(p)
````

**Comment by tcmetzger** [comment] 2021-09-22 18:51
I see that I am using a color definition that is not supported (any more), it should be `"rgb(r, g, b"`, wich commas. However, I find it curious that `"rgb(128 0 0)"` works with `circle()` but not the other glyphs.

**Comment by mattpap** [comment] 2021-09-22 18:52
> `rgb(128 0 0)`

This is CSS4 syntax, supported in bokehjs, but apparently bokeh wasn't update (though the docstrings say otherwise).

**Comment by tcmetzger** [comment] 2021-09-22 18:54
That might explain why `circle()` behaves differently, given that it was updated only recently!

**Comment by mattpap** [comment] 2021-09-22 21:36
This seems to be to be a duplicate or almost duplicate of issue #10902. In general, color validation on bokeh's side needs a proper refinement. I will close this in favor of the older issue.

**Closed by mattpap** 2021-09-22 21:36 UTC
Labels: type: bug
