### ISSUE TITLE
hover only shows in the first rect

### ISSUE THREAD

**Issue by Punchwes** [bokeh/bokeh#4444] opened 2016-06-05 08:16 UTC
I am using rect to create bar.
this is my update code:

```
def update(attrname,old,new):
    plot.xaxis.axis_label=x_axis.value
    plot.yaxis.axis_label='numbers'
    source.data=dict(
        x=axis_map[x_axis.value],
        y=height_map[x_axis.value],
        height=height_map[x_axis.value]*2.0
        )
    plot.x_range.factors=axis_map[x_axis.value]
    plot.rect(x=axis_map[x_axis.value],y=height_map[x_axis.value],height=height_map[x_axis.value]*2.0)
```

(i am sorry this line is too long that it has incorrect indention.)

after updating only the first bar shows its hover while the other bars don't

**Comment by birdsarah** [comment] 2016-06-14 07:32
Can you please update this issue. I can't tell if all the code you've posted is inside the update function.

Here's a guide to using github markdown: https://guides.github.com/features/mastering-markdown/

Also:

* this seems like the kind of question that would be better addressed to the mailing list
* it's very hard to support people without a complete code example - I can't run the code you've supplied in order to try and see the problem you're seeing.

**Comment by bryevdv** [comment] 2016-06-26 00:53
I've add the code quotation. But @birdsarah is right, can you provide a complete, minimal, runnable code sample that reproduces the issue?

**Comment by bryevdv** [comment] 2017-07-13 19:08
Closing due to lack of update

**Closed by bryevdv** 2017-07-13 19:08 UTC
Labels: type: discussion
