### ISSUE TITLE
IE11 erroring with 0.12.5

### ISSUE THREAD

**Issue by TidyData** [bokeh/bokeh#6255] opened 2017-05-08 20:01 UTC
For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : 2.1.5
         python version : 3.6.0.final.0
       requests version : 2.13.0

Windows 7 (Windows/6.1.7601)
IE11 Version 11.0.9600.18638 [Update versions: 11.0.41 (KB4014661)]
django==1.10.5

#### Description of expected behavior and the observed behavior
relates to embedding bokeh
0.12.4 (works)
0.12.5 (broken)

#### Complete, minimal, self-contained example code that reproduces the issue
see the attached minimal django project

1. unzip django project: [bokehbug0125.zip](https://github.com/bokeh/bokeh/files/984680/bokehbug0125.zip)
2. install requirements (django & bokeh)
3. within the directory where manage.py exists run python manage.py runserver
4. navigate to ip:port with IE11
5. switch between bokeh 0.12.4 and 0.12.5 versions and will get the error with 0.12.5

**note: this does not produce the error in firefox**

#### Screenshots or screencasts of the bug in action
![bokeh_example_bug_documentation](https://cloud.githubusercontent.com/assets/22264476/25822596/e7834eb4-33ed-11e7-9fdb-f369e3cfc4b0.jpg)

**Comment by mattpap** [comment] 2017-05-08 20:26
This is a duplicate of #6127.

**Closed by mattpap** 2017-05-08 20:26 UTC
