### ISSUE TITLE
Improve Selection Manager

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2328] opened 2015-05-21 09:26 UTC
The intent here is open a discussion regarding the current selection management (SM) implementation to better understand: 
- what would be the desired functionality
- what SM currently provides and what not
- understand what changes are necessary to add what's missing

There are quite a few open issues regarding selectors and inspectors that are related to that. The introduction of the JSActions add an extra area where a different (better?) SM would come handy. To provide an example, let's say there are overlapping glyphs (circle, i.e.) and an user uses the tap tool + OpenURL action to open a link. There is now way to add any minimal logic to prevent opening N new tabs. The same "overlapping" situation is an issue for HoverTool as well.

**Comment by bryevdv** [comment] 2016-04-07 18:43
reference: https://github.com/bokeh/bokeh/wiki/Selection-and-Hit-test-Managements 

Changing this to a feature issue, since there is work started that could reference this issue in a future PR (ping @mattpap)

**Comment by bryevdv** [comment] 2016-04-07 19:03
related to #1512

**Comment by bryevdv** [comment] 2016-10-02 00:51
ping @canavandl this issue and a recent ML post reminds me of the possible need for the selection manager. WE very much need to be able to implement polices like:

* only return the closest
* only return the closest that is also "on top"
* return everything
* return N closest

A selection manager seems like a central place to specify and implement these policies. Thoughts?

**Comment by asanakoy** [comment] 2017-12-20 18:50
When showing tooltips on the overlapping points it would be nice to be able to have options:
- Stack all tooltips vertically (as it is working right now)
- Display all tooltips in a grid.  
Use-case for this is when you visualize a lot of points (for example TSNE plot), each of them corresponding to an image. Each tooltip shows an image. If there are too many overlapping points tooltips do not fit in the screen. Grid could be a much better option here.

**Comment by chesucr** [comment] 2018-03-14 10:59
When you select points with some selection tools and you change the tool you are working with, I think the selection should be kept. The current behaviour is to reset and lose the previous selected points

**Comment by bryevdv** [comment] 2018-09-13 04:02
this is a dupe of #1512

**Closed by bryevdv** 2018-09-13 04:02 UTC
Labels: tag: component: bokehjs, type: feature
