### ISSUE TITLE
hplot spacing too large

### ISSUE THREAD

**Issue by guillochon** [bokeh/bokeh#3658] opened 2016-01-14 23:36 UTC
I have two plots which I want to place side by side, however when I use `hplot` a very large whitespace is inserted between them:

![image](https://cloud.githubusercontent.com/assets/4998058/12341142/7161ecf6-baed-11e5-8c10-95065e12368a.png)

It appears the `bk-hbox-spacer` style has the attribute `margin-right: auto`, and removing this attribute gets rid of the space. Is it intentional to have the plots spaced so widely when using `hplot`?

**Comment by birdsarah** [comment] 2016-01-15 00:45
Hi @guillochon, thanks for this bug report.

I am also seeing the same thing, and although there is an open issue for this problem https://github.com/bokeh/bokeh/issues/3609 I believe you have described it more clearly and so I will close the other issue and track it here.

In the mean-time there is a work-around - you can wrap your `hplot` in a `vplot` e.g.

    show(vplot(hplot(plot1, plot2)))

**Comment by birdsarah** [comment] 2016-01-15 00:48
For others, an easy way to reproduce this is to go to: `examples/charts/file` and use any of the `_multi.py` examples and then just use `show(hplot(plot1, plot2))` at the end of any example.

**Comment by fpliger** [comment] 2016-01-15 02:55
@guillochon spacing on `hplot` (and `VBox`) is intentional since before every child was just squeezed right next to the other.. It was a last minute change so there wasn't much time dedicated to it and we are already aware that we need to improve this asap.

That said the spacing solution got merged since you can have *some* control over it by explicitly specifying the `vplot` `width` argument. This is definitely not an optimal solution but is something that can be used at the moment without having to tweak css properties..

**Comment by bryevdv** [comment] 2016-01-15 14:59
>  Is it intentional to have the plots spaced so widely when using hplot?

Not exactly. It's the best we could get done with limited resources in the time we had. Better and automatic is our next big priority.

**Comment by birdsarah** [comment] 2016-02-03 18:37
@fpliger - am I right in thinking you were working on a fix for this?

**Comment by fpliger** [comment] 2016-02-03 18:44
Merged #3802 yesterday with a fix that set the spacer to a fixed width [of 40px]..

@birdsarah thanks for the ping

**Closed by fpliger** 2016-02-03 18:44 UTC
Labels: type: bug
