### ISSUE TITLE
Step chart should have 'index

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2992] opened 2015-10-14 19:46 UTC
Based on feedback from @jcrist, the new high-level Step chart should have an 'x' argument so the x-axis will be more than an index (such as a datetime axis). He also suggested an 'aggregation' or 'stacked' attribute so that plotting multiple 'step' lines could be summed.

He's cache profiling some dask computation and would like to visualize the size of multiple caches using a step chart, and also the cache sizes stacked like an area chart to see the total cache size.

cc: @fpliger

**Comment by jcrist** [comment] 2015-10-14 20:06
To clarify, what I want is an area chart with the ability to step instead of ramp between points (something like [this](http://bokeh.pydata.org/en/latest/docs/gallery/area_chart.html) but "stepped"). The old `Area` chart also didn't provide the ability to provide an x-axis, as noted above. Not sure how the api should spell this, but having both of these built-in to the new charts would prevent me from having to write my own :).

**Comment by canavandl** [comment] 2015-10-14 20:08
Thanks for the clarification @jcrist

**Comment by rothnic** [comment] 2015-12-10 18:53
@jcrist: could you provide some sample data? We have updated step, but not sure if it would provide what you were looking for.

**Comment by jcrist** [comment] 2015-12-10 19:48
Sure. Given this:
```
x = [0, 1, 2, 5, 10, 12]
y = [1, 3, 0, 4, 6, 2]
```
Step should provide a way to give the same plot as:
```
p.line(x=[0, 1, 1, 2, 2, 5, 5, 10, 10, 12, 12],
       y=[1, 1, 3, 3, 0, 0, 4, 4, 6, 6, 2])
```

**Comment by rothnic** [comment] 2015-12-10 20:08
@jcrist Thanks!

In the updated charts to be included in 0.11, here is that example:

```
from bokeh.charts import Step, show, output_file

# build a dataset where multiple columns measure the same thing
data = dict(x=[0, 1, 2, 5, 10, 12],
            y=[1, 3, 0, 4, 6, 2])

# create a line chart where each column of measures receives a unique color and dash style
step = Step(data, x='x', y='y')

output_file("steps.html")
show(step)
```

Which produces:

![image](https://cloud.githubusercontent.com/assets/452052/11727094/777384ae-9f47-11e5-9098-c802cde19dbc.png)

Does that meet your intent?

**Comment by fpliger** [comment] 2015-12-10 20:14
@rothnic I'm not sure if it's the case @jcrist have in mind.. but what I think we should have is that:

```
x = [0, 1, 2, 5, 10, 12]
y = [1, 3, 0, 4, 6, 2]

data = pd.DataFrame({'y': y}, index=x)
step = Step(data, y='y')
```

produces the same results you've posted. It's not the case ATM. Opinions?

**Comment by jcrist** [comment] 2015-12-10 20:16
@rothnic, looks good to me! Only issue I have with what @fpliger suggests is that I may have multiple pairs of (`x`, `y`). All I really want are line plots, but with zero-order-hold for interpolation. Perhaps both could work?

**Comment by rothnic** [comment] 2015-12-10 20:24
As for @fpliger 's example, this produces the same result as my previous example:

```
from bokeh.charts import Step, show, output_file
import pandas as pd

df = pd.DataFrame(dict(y=[1, 3, 0, 4, 6, 2]), index=[0, 1, 2, 5, 10, 12])
step = Step(df)

output_file("steps.html")
show(step)
```

If you have multiple pairs of x, y, I think we'd like to support that, but looks like it would need some work. If the data is being placed against the same axis then it should be fairly consistent, so you could likely build something that would work, but it would be manual for now.

**Comment by fpliger** [comment] 2015-12-10 20:30
> As for @fpliger 's example, this produces the same result as my previous example:

does it? It's not for me on master.. (honestly I'd expect it to...

**Comment by rothnic** [comment] 2015-12-10 20:34
@fpliger I'm on the charts/add_data_labels branch, so maybe I fixed something in there, but it should work.

To handle the different pairs, internally we'd have to align the "index" or the x's. I believe the pandas alignment methods could be useful:

http://pandas.pydata.org/pandas-docs/version/0.17.1/basics.html?highlight=align#combining-overlapping-data-sets

Then we'd need to make sure to both handle the multiple x columns, then do the alignment, making sure to handle the nans.

So, doing these alignment operations manually could be a temporary workaround.

**Comment by fpliger** [comment] 2015-12-10 20:54
@rothnic that's fine. The current master have many regressions so it's definitely fine to have it fixed when we merge that. Thanks!

**Comment by fpliger** [comment] 2016-05-05 19:24
this is fixed on current master...

**Closed by fpliger** 2016-05-05 19:24 UTC
Labels: tag: API: charts, type: feature
