### ISSUE TITLE
Error in embed/slideshow/app_reveal.py

### ISSUE THREAD

**Issue by mistakevin** [bokeh/bokeh#2501] opened 2015-07-03 15:12 UTC
Error in flask server `requests.exceptions.ConnectionError`

**Comment by birdsarah** [comment] 2015-07-03 15:43
i only get that error if bokeh-server isn't running.

run `bokeh-server` from one terminal and then `python app_reveal.py` in the other.

**Comment by damianavila** [comment] 2015-07-03 15:46
I can run the example but I have a cross origin problem... anyone else is seeing this behavior?

**Comment by birdsarah** [comment] 2015-07-03 15:50
ok......this is weird...digging in more. i was happily playing with it in chrome. then i saw your message about cors. opened it up in ff and refreshed in chrome and then chrome got the cors......digging.

**Comment by mistakevin** [comment] 2015-07-03 15:54
Working for me now.

**Comment by damianavila** [comment] 2015-07-03 15:56
Yes, I had the server in multiuser mode... closing here...

**Closed by damianavila** 2015-07-03 15:56 UTC
Labels: type: discussion

**Comment by birdsarah** [comment] 2015-07-03 15:57
totally can't reproduce what i saw.
