### ISSUE TITLE
[BUG] Broken hyperlinks on the documentation ("First steps")

### ISSUE THREAD

**Issue by BSchilperoort** [bokeh/bokeh#12422] opened 2022-09-26 08:45 UTC
### Software versions

Latest docs (2.4.3) on docs.bokeh.org.

### Expected behavior

The hyperlinks on the following page to work:
http://docs.bokeh.org/en/latest/docs/first_steps.html#first-steps-guides

E.g. all the "Go to section *" hyperlinks, under the figures.

### Observed behavior

All the hyperlinks return an error 404.

The hyperlinks are in the following format:
http://docs.bokeh.org/en/latest/docs/first_steps/first_steps_1

While the correct hyperlinks should be:
http://docs.bokeh.org/en/latest/docs/first_steps/first_steps_1.html

### Example code

```Python
Navigate to: http://docs.bokeh.org/en/latest/docs/first_steps.html#first-steps-guides
Click on "Go to section 1"
```

**Comment by bryevdv** [comment] 2022-09-26 15:57
Thanks for the report @BSchilperoort however this is a dupe of https://github.com/bokeh/bokeh/issues/12378 which was addressed in https://github.com/bokeh/bokeh/pull/12397 (changes will not show up until the next version is released)

**Closed by bryevdv** 2022-09-26 15:57 UTC
Labels: TRIAGE
