### ISSUE TITLE
The radius of the circle is not accurate

### ISSUE THREAD

**Issue by tristaneljed** [bokeh/bokeh#7965] opened 2018-06-06 08:41 UTC
I've set a radius of my geofence to 2500 meters. I have a point that its distance to the center of this geofence is 2332.84 meters. So it should be inside the geofence.
Here it is in Bokeh:
<img width="471" alt="screen shot 2018-06-06 at 4 39 16 pm" src="https://user-images.githubusercontent.com/10809104/41026867-33754cd2-69a8-11e8-8aa5-36df557777c9.png">
You can clearly see the point is outside the geofence, however when I verify the distance with Google Maps you can see it's the same as the one I've calculated:
<img width="905" alt="screen shot 2018-06-06 at 4 40 27 pm" src="https://user-images.githubusercontent.com/10809104/41026921-598dd966-69a8-11e8-8a13-53615cd3871b.png">

This is the line of the code:

`circle = Circle(x="longitude_deg", y="latitude_deg", radius=2500, fill_color="#ffbdaf", fill_alpha=0.4, line_color="#2471A3")`

**Comment by mattpap** [comment] 2018-06-07 21:09
Most likely this is a duplicate of #517 (though #6603 visualizes this better). I say most likely, because there is a very remote chance that this may be related to google maps integration. It would be good to see an entire plot, with axes, toolbars, etc., or maybe a complete code snippet, to give you a conclusive answer.

**Comment by bryevdv** [comment] 2018-06-07 21:16
@tristaneljed yes, please supply a complete MRE as requested, so that we can investigate.

**Comment by tristaneljed** [comment] 2018-06-08 04:07
<img width="619" alt="screen shot 2018-06-08 at 11 54 59 am" src="https://user-images.githubusercontent.com/10809104/41138323-21c75482-6b13-11e8-9a8a-913add05999b.png">

* I am auto-centering and setting the Zoom Level in another file SpatialTools

```{python}
output_notebook()
# Key Plotting Frame Parameters
frame_width=500 #pixels
frame_height=600 #pixels

# CREATE THE MAP: AUTO-CENTER & ZOOMLEVEL FROM SPATIALTOOLS
map_options = GMapOptions(lat = pltools.CenterMap(df['lat'],df['lon'])['lat'],
                          lng = pltools.CenterMap(df['lat'],df['lon'])['lon'],
                          map_type="roadmap",
                          zoom = pltools.ZoomLevel(frame_width,frame_height,df['lat'],df['lon']))
# BASICS
plot = GMapPlot(x_range=Range1d(), y_range=Range1d(), map_options=map_options)
plot.api_key ="----------------------------------"

######## PLOT USER LOCATION
source = ColumnDataSource(df)
circle = Circle(x="lon", y="lat", size=15, fill_color="#2471A3", fill_alpha=0.6, line_color="#2471A3")
plot.add_glyph(source, circle)
########

######## PLOT GEOFENCE
source = ColumnDataSource(df_syd)
circle = Circle(x="longitude_deg", y="latitude_deg", radius=2500, fill_color="#ffbdaf", fill_alpha=0.4, line_color="#2471A3")
plot.add_glyph(source, circle)
########

######## PLOT CENTER OF GEOFENCE
source = ColumnDataSource(df_syd)
circle = Circle(x="longitude_deg", y="latitude_deg", size=15, fill_color="#2471A3", fill_alpha=0.4, line_color="#2471A3")
plot.add_glyph(source, circle)
########


## SHOW
plot.add_tools(PanTool(), WheelZoomTool(), BoxSelectTool(),HoverTool(tooltips=[
    ("latitude", "@lat"),
    ("longitude","@lon"),
    ("country","@iso_country"),
    ("region","@iso_region"),
    ("code","@iata_code"),
    ("type","@type")]))

show(plot)
```


* SpatialTools

```
def CenterMap(self,df_lat,df_lon):
        # create df_dat
        df_dat=pd.DataFrame(df_lat,columns=['lat'])
        df_dat['lon']=df_lon

        # calculate center
        spread_max=df_dat[['lat','lon']].max()
        spread_min=df_dat[['lat','lon']].min()
        center=spread_min+0.5*(spread_max-spread_min)

        return center
    
    # ZoomLevel - Calculate the zoomlevel for google maps to show all data
    # Input: df_lat -> a pandas column with latitudes of the points
    #        df_lon -> pandas column with longitudes of the points
    #        frame_width and frame_height in pixels (as used by map as well)
    # Output: zoomlevel for Google Maps. If there is only 1 point, zoomlevel is set to 15
    def ZoomLevel(self,frame_width,frame_height,df_lat,df_lon):
        # create df_dat
        df_dat=pd.DataFrame(df_lat,columns=['lat'])
        df_dat['lon']=df_lon

        if len(df_dat)>1:
            # Frame Scaling Factor (1.1 for margin)
            lon_scale=1.1*256/frame_width
            lat_scale=1.1*256/frame_height

            # Finding extreme plotting values - move to radians
            spread_max=df_dat[['lat','lon']].max()*(math.pi/180)
            spread_min=df_dat[['lat','lon']].min()*(math.pi/180)
            # Max Variation
            scaled_lat=abs(math.log(abs(1/math.cos(spread_max['lat'])+math.tan(spread_max['lat'])))-math.log(abs(1/math.cos(spread_min['lat'])+math.tan(spread_min['lat']))))
            scaled_lon=(spread_max['lon']-spread_min['lon'])

            # Calculate Zoomlevels
            lat_zoom=math.floor(math.log(360/(scaled_lat*lat_scale*(180/math.pi)),2))
            lon_zoom=math.floor(math.log(360/(scaled_lon*lon_scale*(180/math.pi)),2))
            zoom_level=min(lat_zoom,lon_zoom)
            return int(zoom_level)
        else: 
            return 15    
```

**Comment by birdsarah** [comment] 2018-11-19 02:37
I bumped into what I think is the same thing but with more trivial example. This was a problem using circle or arc. If I remove the toolbar to make the plot "square" then things line up, but this is not a correct representation. If I've asked for radius 10, it should touch my gridlines.

```
p = figure(x_range=(-21, 21), y_range=(-21, 21), toolbar_location='right',)
p.arc(x=0, y=0, radius=10, start_angle=0, end_angle=2*np.pi, line_color='black')
show(p)
```
![screenshot from 2018-11-18 20-34-32](https://user-images.githubusercontent.com/1796208/48683163-626de080-eb71-11e8-9517-aa4640d216ab.png)

```
p = figure(x_range=(-21, 21), y_range=(-21, 21), toolbar_location=None,)
p.arc(x=0, y=0, radius=10, start_angle=0, end_angle=2*np.pi, line_color='black')
show(p)
```

![screenshot from 2018-11-18 20-35-05](https://user-images.githubusercontent.com/1796208/48683183-77e30a80-eb71-11e8-8e5f-5be03bee1bb6.png)

```
p = figure(x_range=(-21, 21), y_range=(-21, 21), toolbar_location='right',)
p.circle(x=0, y=0, radius=10, line_color='black', fill_color=None)
show(p)
```

![screenshot from 2018-11-18 20-36-06](https://user-images.githubusercontent.com/1796208/48683206-a2cd5e80-eb71-11e8-8d23-960010da655e.png)

**Comment by bryevdv** [comment] 2019-02-19 03:49
@birdsarah in your case you should be setting `match_aspect=True` to for the screen aspect and data aspect ratios to match. That is the only way to ensure circles are circles. 

I am still unfortunately not sure what is the issue in the gmap case, or what to do about it.

**Comment by arashgmn** [comment] 2020-01-31 16:18
This issue exists even if the x and y ranges are equal. For instance, consider the following simple code that monotonously increases the (x,y) of the center of a circle and also draws the circle itself.
I expect to always see the circle touching the location (0,0). Yet, it detaches from this point. 

More interestingly, after the while loop ends, if you zoom in close to the center, you'll see that the circle border jumps. I'm using python 3 and bokeh '1.4.0'.

```python
import numpy as np
from bokeh.io import output_notebook, push_notebook
from bokeh.models import ColumnDataSource
from bokeh.models.markers import Cross
from bokeh.plotting import figure, show
import time

output_notebook()

t = 0
r = 1
x = 0
y = 0

src = ColumnDataSource(data={'x': [x], 'y': [y], 'xx': [x+r], 'yy': [y+r], 'radius':[np.abs(r)]})

# setting up the figure
plot = figure(x_range=(-10,10), y_range=(-10,10))
point = plot.circle('x','y',  source=src, size=4)
circle = plot.circle('xx','yy', radius = 'radius',  source=src, fill_color='green', fill_alpha=0.3 , color ='green')
glyph = Cross(x="xx", y="yy", line_color="red", fill_color=None, line_width=2, size=5)
plot.add_glyph(src, glyph)


handle=show(plot, notebook_handle=True);
new_r = r
dr=0.1
# starting of the animation
while new_r<63:
    new_r += dr
    new_xx = x + new_r
    new_yy = y + new_r

    circle.data_source.data['xx'] = [new_xx]
    circle.data_source.data['yy'] = [new_yy]
    circle.data_source.data['radius'] = [np.linalg.norm(np.array([new_xx-x, new_yy-y]))]
    push_notebook(handle=handle)
    time.sleep(0.1)
```

**Comment by bryevdv** [comment] 2020-01-31 17:06
@arashgmn you have not set `match_aspect=True`. The data range start/end being the same is irrelevant if the pill extents of those ranges differ. Setting `match_aspect=True` forces the data/screen *aspect ratios* to be identical, which is what actually matters. 

Separately, this issues is about an evident discrepancy in how gmaps and bokeh are measure, but that is unrelated to your code.

**Comment by arashgmn** [comment] 2020-01-31 20:34
@bryevdv `match_aspect`, if set true, changes the range and of course by setting both ranges, a fixed frame is what one needs. The problem with the `Circle` however`, as indicated in [#517](https://github.com/bokeh/bokeh/issues/517), and its solution, `match_aspect`, should be of concern whenever the range/scale of the axes are different scales/ranges, unlike my example.

That said, I don't see why the radius of the `Circle` is not accurate in this fixed-isometric frame such as in my example. I still believe this example shows a shortcoming, in line with the title of this discussion, albeit not related to gmap.

**Comment by bryevdv** [comment] 2020-01-31 20:48
@arashgmn Because the amount of space taken up by the bottom axis is not the same as the amount of space taken up by the left axis. Therefore the central area in the plot frame is *not* square, even though the HTML canvas is. Therefore: the pixel aspect ration and the data aspect ratio *do not match*. 

Setting a large `min_border`:
```
plot = figure(x_range=(-10,10), y_range=(-10,10), min_border=100)
```
will for the interior plot frame to be square, and you will see your observed effect go away.

**Comment by p-himik** [comment] 2020-05-18 21:15
Similar thing happens with ellipses when specifying `angle`:
```python
import math

from bokeh.io import show
from bokeh.plotting import figure

p = figure()

p.circle([-1, 1], [-1, 1], radius=0.03)
p.ellipse(x=0, y=0, width=4, height=0.1, angle=math.pi / 4, fill_color=None)
show(p)
```

**Comment by bryevdv** [comment] 2020-08-25 04:02
@p-himik that's entirely expected. Nothing that is supposed to be "rotatable" will behave in a "mathematical" way, ***unless `match_aspect` is set*** to True.


However, none of this has anything to do with the OP, which is narrowly related to gmap plotting. Due to the potential for confusion, I am going to lock this issue for further comment.

**Comment by bryevdv** [comment] 2020-08-25 04:06
And actually looking back, there is no complete minimal reproducer, so I'm not going to be able to investigate. @tristaneljed if you can still repro this in current version (2.2+) then please open a new issue.

**Closed by bryevdv** 2020-08-25 04:06 UTC
Labels: reso: norepro, type: discussion
