### ISSUE TITLE
[BUG] Lazy initialization of DataTable causes incomplete table rendering (only the first row is displayed)

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#11966] opened 2022-01-20 21:31 UTC
### Software versions

Python version      :  3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  2.4.2

### Expected behavior

Regular behaviour if the ColumnDataSource is lazy assigned to a DataTable

### Observed behavior

Table will only render the first row once the data is assigned. Direct assignment of the source does not show this kind of problem.

(Note: using a CDSView does fix the problem however)

### Example code

```Python
from bokeh.layouts import row
from bokeh.models import Button, ColumnDataSource, CDSView, DataTable, IndexFilter, TableColumn
from bokeh.plotting import curdoc, figure


col_names = ["col1","col2","col3","col4"]

source = ColumnDataSource()
ui_columns = [TableColumn(field=col, title=col) for col in col_names]

# lazy source init
table = DataTable(width=300, max_width=300, columns=ui_columns)
table.source = source

#direct init
table2 = DataTable(width=500, max_width=500, source=source, columns=ui_columns)

def add_data_to_table():
    table.source.data = {"col1":[0,4],"col2":[1,5],"col3":[2,5],"col4":[3,6]}


button = Button(label="test")
button.on_click(add_data_to_table)


curdoc().add_root(row(table, button, table2))
```

### Screenshots

![bokeh_table_render_bug](https://user-images.githubusercontent.com/71090451/150425057-32cd6d69-028a-455c-badb-a6bd79b15d11.PNG)

**Comment by bryevdv** [comment] 2022-01-20 21:38
> Table will only render the first row once the data is assigned. 

Table columns refer to columns that are *presumed exist in the data source*. So at the very least, regardless, you really need to define your CDS with empty lists/arrays for the column names that the table expects.

That said, the separate issue here is that the formatting step is very unhappy when there is no data (with or without empty columns). Confirmed present also in `branch-3.0`

**Comment by muendlein** [comment] 2022-01-20 21:53
@bryevdv I have also noticed that in previous versions (in particular 2.1.1) this kind of incomplete rendering does not occur.

**Comment by bryevdv** [comment] 2022-01-20 22:02
I am going to mark this as a dupe of #11965 for now, I don't know that two separate issues is helpful here.

**Closed by bryevdv** 2022-01-20 22:02 UTC
Labels: TRIAGE
