### ISSUE TITLE
examples/glyphs/data_tables.ipynb error

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#2095] opened 2015-03-23 16:48 UTC
In the last cell of the notebook, when this command is run:

```python
VBox(children=[plot, data_table]).html
```
This error is returned

```
Javascript error adding output!
ReferenceError: Bokeh is not defined
See your browser Javascript console for more details.
```

**Comment by damianavila** [comment] 2015-03-25 20:42
FIx by #2101

**Comment by fpliger** [comment] 2015-05-06 15:11
Confirmed it looks good but notebook has a new error because of recent interface changes (this new bug is being fixed by #2246). So I'm closing this issue as fixed as @damianavila mentioned.

**Closed by fpliger** 2015-05-06 15:11 UTC
Labels: type: bug
