### ISSUE TITLE
Image from ColumnDataSource only works with variable name 'image'

### ISSUE THREAD

**Issue by marcuskd** [bokeh/bokeh#5738] opened 2017-01-15 17:48 UTC
In v0.12.4, plotting an image using a ColumnDataSource doesn't work unless the image variable name is 'image' - see the example code below. Commenting out the two lines which use 'z' and uncommenting those which use 'image' makes the code work.

-----------------

import numpy

from bokeh.charts import output_file
from bokeh.plotting import Figure, show
from bokeh.models import ColumnDataSource

z = numpy.random.randn(10,10)
zsrc = ColumnDataSource(data={'z':[z]}) # Doesn't work
#zsrc = ColumnDataSource(data={'image':[z]}) # OK

p = Figure(x_range=(-5,5),y_range=(-5,5))

i = p.image('z',source=zsrc,x=-5,y=-5,dw=10,dh=10,palette="Spectral11") # Doesn't work
#i = p.image('image',source=zsrc,x=-5,y=-5,dw=10,dh=10,palette="Spectral11") # OK

output_file('CDSTest.html')
show(p)

**Comment by mattpap** [comment] 2017-01-15 18:40
This is a duplicate of issue #5706.

**Closed by mattpap** 2017-01-15 18:40 UTC
Labels: reso: duplicate

**Comment by marcuskd** [comment] 2017-01-15 19:40
Thanks. It was me who raised this in the forum and Bryan asked me to raise
a GH issue but someone else raised one first.

**Comment by bryevdv** [comment] 2017-01-15 21:53
Thanks @marcuskd :) Hoping this is something simple, in which case it will be fixed in a dev build soon
