### ISSUE TITLE
[BUG] plot.x_range have start > end when zooming quickly in and out

### ISSUE THREAD

**Issue by Hongyuy** [bokeh/bokeh#14092] opened 2024-10-04 02:26 UTC
### Software versions

I was just fiddling with the example in the official documentation and noticed this bug.

### Browser name and version

Chrome Version 122.0.6261.69 (Official Build) (64-bit)

### Expected behavior

when wheel zoom quickly in and out. plot.x_range should always have start < end

### Observed behavior

![image](https://github.com/user-attachments/assets/8c30e961-1204-4494-aeb2-f879fc5dc331)
I was fiddling with the official example and noticed that, when wheel zoom quickly in and out, RangeUpdate event can have x0 > x1. and when it occurs, it will stay that x0 > x1 and for the plot, x_range has start > end. I noticed it applies to many official examples when zooming quickly in and out.

### Example code

```Python
https://docs.bokeh.org/en/3.0.0/docs/user_guide/interaction/js_callbacks.html#js-on-event-callback-triggers
```

**Comment by bryevdv** [comment] 2024-10-04 04:14
Seems to be a duplicate of https://github.com/bokeh/bokeh/issues/13504

**Closed as completed by bryevdv** 2024-10-04 04:14 UTC
Labels: reso: duplicate
