### ISSUE TITLE
Multiline hover_glyph "half" failing [BUG] 

### ISSUE THREAD

**Issue by gmerritt123** [bokeh/bokeh#11853] opened 2021-12-02 15:09 UTC
### Software versions

Python version      :  3.7.10 | packaged by conda-forge | (default, Sep 13 2021, 19:12:52) [MSC v.1916 64 bit (AMD64)]
IPython version     :  7.29.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  C:\ProgramData\Anaconda3\envs\geo_env37v2\lib\site-packages\bokeh\server\static
node.js version     :  v16.12.0

### Browser name and version

Chrome: Version 96.0.4664.45 (Official Build) (64-bit

### Expected behavior

- Two multiline glyph-renderers being driven by the same source but plotted on separate axes. 
- Creation of a purple line hover_glyph for both. 
- Creation of a hovertool that points to both these renderers, with $y as the only tooltip. 

Expected behavior:

1. Hovering over any line should trigger the hover glyph (i.e. line should turn purple), and the corresponding line plotted on the other axis (as per them being from the same data source) should also turn purple.
2. The $y should display the value of the corresponding line value.

### Observed behavior

1. Only half works. Depending on the order of the renderers list passed to the HoverTool, the hover glyph only triggers for the SECOND renderer. See comment in the code.
2. Works great for both renderers... BUT, the real tough question/issue is how to get the $y of the "other" line to display on the hovertool as well. I can't use '@ys' and '@zs' as that displays the whole array. This is probably a separate issue/feature request but it came up in this example so thought I'd mention it here.

### Example code

```Python
from bokeh.models import DataRange1d, Range1d, MultiLine,LinearAxis
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure, save, show

src = ColumnDataSource(data={'xs':[[1,2,3,4,5,6],[1,2,3,4,5,6]]
                             ,'ys':[[1,2,5,6,7,8],[2,6,8,9,9.1,10,11]]
                             ,'zs':[[1,10,100,1000,10000,100000],[1,20,80,800,9000,110000]]})

f = figure()

f.extra_y_ranges={'z':DataRange1d()}

#try to add a log secondary y axis
f.add_layout(LinearAxis(y_range_name='z'),'right')

g1 = MultiLine(xs='xs',ys='ys',line_color='blue',line_width=3)
g1h = MultiLine(xs='xs',ys='ys',line_color='purple',line_width=3)
r1 = f.add_glyph(src,g1,hover_glyph=g1h)
f.y_range.renderers=[r1]

g2 = MultiLine(xs='xs',ys='zs',line_color='red',line_width=3)
g2h = MultiLine(xs='xs',ys='zs',line_color='purple',line_width=3)
r2 = f.add_glyph(src,g2,y_range_name='z',hover_glyph=g2h)
f.extra_y_ranges['z'].renderers=[r2]

#try rearranging r2 and r1 here!
# whichever is first, its hover_glyph doesn't activate.
#the tooltip works magnificently though
hvr = HoverTool(renderers=[r1,r2]
                ,tooltips=[('','$y')]
                )
hvr.line_policy = 'interp'
f.add_tools(hvr)

show(f)
```

**Comment by bryevdv** [comment] 2021-12-02 18:07
I am pretty sure this is a duplicate of a fairly old bug about selections/inspections but I will have to go do some digging to find it later when I have time. 

I am afraid I don't understand the comment about `$y`. That special formatter always (and only) displays the y-coordinate directly under the cursor (using the configured range for the inspected glyph), and seems to be behaving as intended and expected with the code above. If you need something different I think you would have to use a `CustomJSHover`

https://docs.bokeh.org/en/latest/docs/reference/models/tools.html#bokeh.models.CustomJSHover

**Comment by bryevdv** [comment] 2021-12-02 18:17
Here are the old refs, I expect this issues is a duplicate of one or both of these:

* https://github.com/bokeh/bokeh/issues/7397
* https://github.com/bokeh/bokeh/issues/10441

Unfortunately I think this will not be simple to fix and will require a substantive re-design of how selections are handled in general, that will almost certainly involve breaking changes as well.

**Comment by gmerritt123** [comment] 2021-12-02 18:36
Thanks for looking into it. Honestly, it is mind boggling how awesome the multiline hover works in conjunction with other linked datasources on other plots (the power it gives me to tie transient and spatial data is just absurd)... but hey gotta always ask for more eh :-D

You probably already surmise this but this is directly relevant to my cross section tool/transient data showcase thing. Everything in the modelling world is "how does the simulated compare with observed?" And for those transient hydrographs, I want a solid line showing observed and a dotted one showing model simulated... so were this bug "fixed", it'd mean the user could hover over a simulated water level line and see it's corresponding observed water level line (and vice versa) by virtue of the hover glyph getting triggered on both.... in addition to the well on the cross section and in plan view highlighting too (and that works amazing currently).

Sorry I wasn't clear re the tooltip thing. Let me elaborate with another basic example, but with none of the two axis funny business, and instead of two multiline glyphs, i'll use two single line glyphs:

```
from bokeh.models import Line
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure, save, show

src = ColumnDataSource(data={'x':[1,2,3,4,5,6]
                             ,'y1':[1,2,5,6,7,8]
                             ,'y2':[2,6,8,9,9,10]})

f = figure()

g1 = Line(x='x',y='y1',line_color='blue',line_width=3)
g1h = Line(x='x',y='y1',line_color='purple',line_width=3)
r1 = f.add_glyph(src,g1,hover_glyph=g1h)

g2 = Line(x='x',y='y2',line_color='red',line_width=3)
g2h = Line(x='x',y='y2',line_color='purple',line_width=3)
r2 = f.add_glyph(src,g2,hover_glyph=g2h)


hvr = HoverTool(renderers=[r1,r2]
                ,tooltips=[('blue y','@y1')
                           ,('red y','@y2')]
                )
hvr.line_policy = 'interp'
f.add_tools(hvr)

show(f)
```
![image](https://user-images.githubusercontent.com/58000181/144480422-846db658-8688-432a-9866-ba3e35c71a51.png)

This example suffers from the same hover_glyph bug as above (but that's not what I'm getting at here, just an aside), but what I'm showing here is that (obviously) I can retrieve any data field from the CDS and display it using the '@' notation... so in this case I'm displaying the y1 and y2 values for both lines on one hover because they're from the same data source. I CAN'T do this with two multiline glyphs sharing the same datasource as far as I know, because the added layer of complication is that it's an array of arrays (i.e. @ ys).  So to tie back to my use case, user hovers over a simulated water level line at a particular well for a particular time, and it'd be nice for them to be able to see the corresponding observed water level at that exact same time for that particular well.

I'll should explore CustomJSHover a bit more because I might find reasonable workarounds though, thanks for the suggestion.

**Comment by bryevdv** [comment] 2021-12-02 18:41
(in a bit of a rush just now but I meant to add, and want to agreed, current options all probably go through `CustomJSHover` since you can run actual JS code to do whatever you need at inspection time)

**Comment by gmerritt123** [comment] 2021-12-02 18:54
Yup, the solution always ends up being "get better at JS"... that'll always be a work in progress...

**Comment by bryevdv** [comment] 2022-03-03 20:50
As mentioned I do think this is covered by one or both of the issues linked above, so I will close this now.

**Closed by bryevdv** 2022-03-03 20:50 UTC
Labels: reso: duplicate, type: discussion
