### ISSUE TITLE
The perimeter circles sit on wrong positions

### ISSUE THREAD

**Issue by js418** [bokeh/bokeh#6500] opened 2017-06-19 20:06 UTC
I try to draw RadViz chart, however, I found some problems for rendering the circles sitting on the perimeter. Here is a  simple test `code:
`import numpy as np
from bokeh.plotting import figure, output_file, show
from bokeh.plotting import figure

r =300

t= [ 0.,2.48412237,3.3859823,3.96624619,3.82495986,3.65339717,2.04537165,2.54204158,2.53869576,2.83884976,2.63021265,2.54389624,6.06368477,6.09002423,3.58175554,5.56765706,5.83838094,3.82340399]
x = r*np.cos(t) + r
y = r*np.sin(t) + r

#t2 = np.random.random(10) * 2 * np.pi
#x2 = r*np.cos(t2) + r
#y2 = r*np.sin(t2) + r

f = figure(plot_width=500, plot_height=500,title="test", x_axis_type= None, y_axis_type = None)
f. circle(r,r,radius= r, line_color="black", fill_color= None)
f.circle(x,y,size = 10,fill_color = "blue")
#f.circle(x2,y2,size = 10,fill_color = "red")

output_file("test.html")
show(f)`

![image](https://user-images.githubusercontent.com/23486997/27303296-5cadc0ee-5508-11e7-8146-88458806152c.png)

you can see the circles are not sitting on the perimeter.However, if you uncomment the lines (add some randoms circles on the perimeter), the rendering seems fine~

![image](https://user-images.githubusercontent.com/23486997/27303574-4261b758-5509-11e7-9e23-e47e1407c3a4.png)

I use Bokeh 12.6 and Python 3.6

**Comment by bryevdv** [comment] 2017-06-19 20:29
This is a dupe of #474 / #517 

The cause is the underlying aspect ratio of the central plot area is not 1-1. Until there is an option or Bokeh to enforce a 1-1 aspect ratio (hopefully next release) users must work to ensure the aspect ration manually (e.g by tweaking border min widths and axis label orientations, etc.)

**Closed by bryevdv** 2017-06-19 20:29 UTC

**Comment by bryevdv** [comment] 2017-06-19 20:34
BTW I think the change between the commented / uncommented is a coincidence -- I think with the random circles added the auto ranging bounds are different in a way that makes it look better, essentially by accident (the auto-range bounds with random circles are closer to 1-1)

**Comment by js418** [comment] 2017-06-19 20:39
OK, thanks a lot for the quick respond!
