### ISSUE TITLE
Issue updating DataRange start/end explicitly

### ISSUE THREAD

**Issue by jdupl123** [bokeh/bokeh#4014] opened 2016-03-10 05:51 UTC
@jbednar FYI

When using datashader an image is produced and pass along to the dynamicImageRender

see [https://github.com/bokeh/datashader/blob/master/examples/dashboard/dashboard.py](url)

I would like to change the axis dynamically in my plot using Select drop down box.

I have modified the dashboard above to make this work. However unfortunately when I set a new axis there appears to be no way for the dynamicImageRender to update the range of the axis. With normal renderers this work because the data is available to the renderer. I propose a interface be added to the dynamicImageRender so that it can be passed the desired axis range.

Cheers,
Jaco.

**Comment by birdsarah** [comment] 2016-03-10 20:54
@jdupl123 - this seems like it belongs as an issue in the datashader repo. Closing for now. 

If I'm mistaken can you re-open and be more specific about the bokeh feature you'd like?

**Comment by jdupl123** [comment] 2016-03-11 01:02
@birdsarah how do i repopen the issue? This issue is with bokeh and not the datashader part. when you create a figure in bokeh you can specify in initial xrange and y range. when you are doing a scatter plot you can use a datasource when you change which column of the datasource is being used for xdata the xrange is dynamicaly updated. this can be seen in the stocks app under bokeh examples. hower when using a dynamicImageRenderer there is no datasource and therefore unfortunately the axis is not dynamicaly updated. The functionality i desire is a way to manualy update the xrange and yrange when using a dynamicImageRenderer.

**Comment by philippjfr** [comment] 2016-03-11 02:01
It's not quite clear to me what you want to achieve. The point of ``DynamicImage`` is to easily use the bokeh interactive zooming tools to update a datashader plot based on the selected ranges. It sounds like you want to change the ``x_range`` and ``y_range`` dynamically with a drop down box. Do you want to mix interactive zooming with your dropdown selection? If so, mixing other widgets with DynamicImage is currently not supported because the image plot hooks into the bokeh display machinery at a very low level to make it more responsive. In future IPython kernel callbacks may be supported directly in bokeh, but I think it's out of the scope of datashader to implement this functionality on ``DynamicImage`` in its current form.

**Comment by jdupl123** [comment] 2016-03-11 03:00
I think what you are saying is what I want to achieve. 

The bokeh stock app at 

[https://github.com/bokeh/bokeh/tree/master/examples/app/stocks](url) does what I am trying to do with a smaller dataset.

 I have data with many differents columns and lots of datapoints. I would like to plots the different columsn againts each other without having to create a new plot every time. it already work the only issue is that i have to zoom alot to fit the data in the figure properly once i change column. this is because some columns such as motor torque range from 0 to 1000 while other columns such as total elapsed time may go up to 1000000 seconds or more. I had a look at the js code and it seems there are variables keeping track of what the current x and y ranges are so i figured it would not be too hard to add a function that says the new initial x and y ranges are ... and then reset the figure.

**Comment by philippjfr** [comment] 2016-03-11 12:11
I'm sure you could adapt the ``DynamicImage`` implementation to make it do what you're asking for but until the bokeh team have decided on a way to handle bidirectional Jupyter Comms in general, it's not within the scope of datashader to support this directly.

**Comment by jdupl123** [comment] 2016-03-12 07:26
Hi @philippjfr Thanks for your response. Although i do not see how the Jupyter coms is relavant. I am using the dashboard example as the basis for my code. This code is pure python, no notebook involved. datashader talks with the tornado server using the tornado request handler.

[https://github.com/bokeh/datashader/blob/master/examples/dashboard/dashboard.py](url)

**Comment by philippjfr** [comment] 2016-03-12 10:45
I see now and my apologies. We were talking about two different things. DynamicImage is a datashader level concept, while DynamicImageRenderer appears to be a bokeh level concept. So I think you're right that this is a bokeh issue and should be reopened here.

**Comment by bryevdv** [comment] 2016-03-12 15:09
Ping @brendancol

**Comment by brendancol** [comment] 2016-03-18 15:10
@jdupl123 Can you point me to a code sample of the issue.  My hunch is that the `TileRenderer` could be resetting the extent of the map in attempt to preserve aspect-ratio.  Have you tried removing the `add_tile` line?

More generally, the `DynamicImageRenderer` will only read the plot frame axes, not update them.

**Comment by jdupl123** [comment] 2016-03-20 22:37
@brendancol I am working on the data shader example which can be found here [https://github.com/bokeh/datashader/blob/master/examples/dashboard/dashboard.py](url).

I have added an axes selector
```python
xaxes_select = Select.create(name='X-Axes',
                                    options=self.model.axes, value=self.xaxis[0])
xaxes_select.on_change('value', self.on_xaxes_change)
```
```python
def on_xaxes_change(self, attr, old, new):
        self.xaxis = self.model.axes[new]
        self.model.active_axes = ((self.xaxis[0] + " vs " + self.yaxis[0]),(self.xaxis[1]),(self.yaxis[1]))
        self.x_range = Range1d(start=self.model.df[self.xaxis[1]].min(),
                               end=self.model.df[self.xaxis[1]].max(), bounds=None)
        self.fig.x_range=self.x_range
        self.fig.xaxis.axis_label = self.xaxis[0]
        self.axesChanged = True
        self.update_image()
```
update image then busts the cache resulting get method of the GetDataset class being called.
a new image is rendered and sent off to be displayed by the dynamic image renderer.

this all works fine except setting `self.fig.x_range=self.x_range` does not update the range of the plot when the new image is rendered. 

as for the DynamicImageRenderer will only read the plot frame axes, not update them. 

that is the whole point of this issue. I need it to update them.

**Comment by bryevdv** [comment] 2016-03-21 04:38
As a workaround can you try setting start/end properties on the existing range, instead of creating a new range? Perhaps there is a bug preventing the update with a wholesale model replacement.

**Comment by jdupl123** [comment] 2016-03-21 06:40
@bryevdv thanks for the suggestion. Setting x_range.start and x_range.end rather than providing a new range1d solves the problem I was having. although may still cause confusion for others in the future. 

Regards,
Jaco.

**Comment by jbrambleDC** [comment] 2016-04-11 21:58
I am doing the following in my update method for a bokeh server application:
```python
  ### Update titles
    p.title = 'Daily {} Usage @ {}'.format(inventory.value, store_name.value)
    p1.title = 'Usage Vs. Netsales for {} @ {}'.format(inventory.value, store_name.value)
    p2.title = 'Monthly {} Usage at {}'.format(inventory.value, store_name.value)
    #p3.title = 'Usage by day of week for {}'.format(inventory.value)

    ### Update axis sizes
    p.y_range.end = np.max(data['y_avg']) + 100
    p2.y_range.end = data['usage_by_month']['daily_usage'].max() + 50
```
and even updating the ranges does not solve the issue.

**Comment by bryevdv** [comment] 2016-04-11 22:15
@jbrambleDC It's difficult to say anything definitive with just an isolated snippet in isolation. Can you provide a complete, minimal, runnable example that reproduces your problem, that can be used for investigation or comment?

**Comment by marco-c** [comment] 2016-04-27 17:44
The same problem applies to `FactorRange`s.

I'm also seeing something similar with a `ColumnDataSource` object, I need to update the `x` and `y` parameters instead of replacing `source.data`.

**Comment by savadhani** [comment] 2016-05-22 20:19
@bryevdv sir, i m new to building bokeh applications that run using the bokeh server. I so far haven't found the solution to the problem of changing x_range or y_range in the update(attr,old,new) by python lists, especially when the contents of the list are python strings. Is there a workaround to  this problem at all? such as changing the type of x / y axis ( if at all it exists) ?

**Comment by savadhani** [comment] 2016-05-22 20:20
@bryevdv sir, i m new to building bokeh applications that run using the bokeh server. I so far haven't found the solution to the problem of changing x_range or y_range in the update(attr,old,new) by python lists, especially when the contents of the list are python strings. Is there a workaround to  this problem at all? such as changing the type of x / y axis ( if at all it exists) ?

**Comment by marco-c** [comment] 2016-05-22 22:04
I'm doing something like this (the first for string, the second for numeric):
```
    fig.x_range.factors = ['Factor1', 'Factor2', ...]
    fig.y_range.end = 42
```

**Comment by bryevdv** [comment] 2016-05-23 13:14
The first step is for someone to provide a complete, minimal, runnable script that reproduces the problem. It is a huge burden for us to try and "guess" and "fill in the gaps" because there is every reason to think we won't guess right, and might spend lots of time looking at the wrong thing or a different issue entirely.

**Comment by marco-c** [comment] 2016-05-23 13:21
My code snippet wasn't meant to show the problem, but to provide a possible workaround for @savadhani.

This is a (non minimal) example: https://github.com/marco-c/releaseVSbeta/blob/master/main.py#L360

It works if I manually modify the properties of `fig.x_range` and `fig.y_range` (e.g. `x_range.factors = ...`), it doesn't work if I replace `x_range` with a new `FactorRange` object).

**Comment by savadhani** [comment] 2016-05-24 05:46
[bokeh_hm.txt](https://github.com/bokeh/bokeh/files/278839/bokeh_hm.txt)

that's how my code looks like. 
i get the following error : 
ValueError: expected an instance of type Range, got ['Mon', 'Tue', 'Wed', 'Thru'
, 'Fri', 'Sat', 'Sun'] of type list

**Comment by savadhani** [comment] 2016-05-24 06:04
[bokeh_hm_FactoRange.txt](https://github.com/bokeh/bokeh/files/278863/bokeh_hm_FactoRange.txt)

when i set x_range to be a FactorRange obj. i generate these warning messages and the plot doesn't update. am I missing something? 

"WARNING:bokeh.core.properties:JSON had attr u'_bounds_as_factors' on obj <bokeh.models.ranges.FactorRange object at 0x0000000008B89898>, which is a client-only or invalid attribute that shouldn't have been sent"

I am basically typing to generate a heat map using basic rect glyphs  and i want the plot to update upon changing the selection (although i know there is HeatMap charts , problem is i donot know how to change the column datasource for highlevel charts (i'd be exreamtly thankful if i could get any leads on this aspect too))

**Comment by marco-c** [comment] 2016-05-24 11:36
@savadhani have you read my comment? `p.x_range.factors=days` not `p.range=days`.

**Comment by savadhani** [comment] 2016-05-24 11:45
yes yes I did ! 
I'm sorry that i had forgotten to post about it ! my bad ! 
Thanks for the help.

**Comment by Punchwes** [comment] 2016-06-04 16:28
can I change figure's para in update? I created interactive bar by rect, due to my different x_axis, I wish to change my figure's x_range, so to change the bar's x_axis name.
`xis_map = {
    "Current Location":location,
    #'Current Company':'company',
    "Current Industry":industry,
    "Current Company":company
}

y_map ={
    "Current Location":local_counts1,
    "Current Industry":industry_counts1
}
height_map={
    "Current Location":y_local_height,
    "Current Industry":y_indus_height,
    "Current Company":y_company_height
}

cities=TextInput(title='location name')
x_axis=Select(title='X axis',options=sorted(axis_map.keys()),value='Current Industry')

source = ColumnDataSource(data=dict(x=[],y=[],height=[],x_range_name=[]))


plot = figure(plot_height=600, plot_width=800, title="", toolbar_location=None, tools=[hover],x_range=axis_map[x_axis.value],y_range=[0,2000])
plot.rect(x='x',y='y',width=.8,height='height',source=source)



def update():

    plot.xaxis.axis_label=x_axis.value
    plot.yaxis.axis_label='numbers'

    source.data=dict(
        x=axis_map[x_axis.value],
        y=height_map[x_axis.value],
        height=height_map[x_axis.value]*2.0,
        x_range_name=axis_map[x_axis.value]

        )
    #bokeh.plotting.curplot().x_range=axis_map[x_axis.value]
  
def input_change(attrname,old,new):
    update()





controls=[cities,x_axis]
for control in controls:
	control.on_change('value',input_change)

inputs=HBox(VBoxForm(*controls))
input_change(None,None,None)
curdoc().add_root(HBox(inputs,plot))`


in the line plot=figure,the value of x_range will be the value of my x_axis, I want to change it every time I update my data.
is there any solution?

**Comment by Punchwes** [comment] 2016-06-05 03:58
here my plot code:

source = ColumnDataSource(data=dict(x=[],y=[],height=[]))
plot = figure(plot_height=600, plot_width=800, title="", toolbar_location=None, tools=[hover],x_range=industry,y_range=[0,2000])
p=plot.rect(x='x',y='y',width=.8,height='height',source=source)

I have three different x_range which should be changed when I select different x_axis:

x_axis=Select(title='X axis',options=sorted(axis_map.keys()),value='Current Industry')

here is my update function:

def update(attrname,old,new):
    plot.xaxis.axis_label=x_axis.value
    plot.yaxis.axis_label='numbers'
    source.data=dict(
        x=axis_map[x_axis.value],
        y=height_map[x_axis.value],
        height=height_map[x_axis.value]*2.0
        )

question:
I wish to change my rect's x value and figure's x_range value at the same time in every update. But I can't find a way to it.

**Comment by petobens** [comment] 2017-01-25 22:14
Hi @bryevdv . Consider the following `~/foo/main.py` file:
```python
import numpy as np

from bokeh.io import curdoc
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Slider
from bokeh.layouts import layout, Row
from bokeh.plotting import figure

max_value = Slider(title="Max value", value=10, start=10, end=1000, step=10)

# Plot
source_plot = ColumnDataSource(data=dict(left=[], right=[], hist=[]))
plot = figure(plot_height=500, plot_width=1000, toolbar_location=None)
plot.quad(
    bottom=0,
    left='left',
    right='right',
    top='hist',
    source=source_plot,
    alpha=0.6)
plot.y_range.start = 0


def update_plot():
    max_val = max_value.value
    hist_values = np.random.randint(1, high=max_val, size=1000)
    hist, edges = np.histogram(hist_values)
    # plot.x_range.end = max(hist_values)
    plot.title.text = "X_range end is: {}".format(str(max(hist_values)))
    source_plot.data = dict(left=edges[:-1], right=edges[1:], hist=hist)


# Update plot when selector updates
max_value.on_change('value', lambda attr, old, new: update_plot())

# Initial plot
update_plot()

l = layout([[Row(max_value), Row(plot)], ], sizing_mode='fixed')
curdoc().add_root(l)
curdoc().title = "TEST"
```
When I run the previous code with `bokeh serve --show foo` and move the slider widget then the x-axis correctly updates its value:
<img width="1071" alt="screen shot 2017-01-25 at 7 09 52 pm" src="https://cloud.githubusercontent.com/assets/2583971/22311377/fe976fde-e331-11e6-9f57-41e552f46796.png">

On the other hand, if I uncomment the line `plot.x_range.end = max(hist_values)`,  the x-axis values are not updated:
<img width="1083" alt="screen shot 2017-01-25 at 7 10 24 pm" src="https://cloud.githubusercontent.com/assets/2583971/22311402/1aab808e-e332-11e6-82ea-7ac6443ac15b.png">

Please let me know if you can reproduce this. Thanks!!

**Comment by bryevdv** [comment] 2017-01-25 22:38
> On the other hand, if I uncomment the line plot.x_range.end = max(hist_values), the x-axis values are not updated:

@petobens That is 100% expected behaviors. If you set the value of `.end` that is *explicity* telling Bokeh, *"don't auto-range, use the value I provided"* 

I'm still not sure what (if anything) the issue is here

**Comment by bryevdv** [comment] 2017-01-25 22:40
Yes, I can reproduce a problem with the code above

**Comment by petobens** [comment] 2017-01-26 03:37
@bryevdv thanks for looking into this.

**Comment by TiemenSch** [comment] 2017-02-01 19:21
I can confirm that I can't update my axis to a new FactorRange dynamically
```python
def update(setting=5.0):
    # Calculate new heatmap ColumnDataSource, with labels reordered. 
    cds, row_labels, col_labels = hm_calculate(dataframe, setting)
    p.x_range = FactorRange(factors=col_labels)
    p.y_range = FactorRange(factors=row_labels[::-1])
    push_notebook()
```
Although I think that the problem of assigning new axes straight to the plot/Figure was already clear. 
The reordering is essential to have some clusters showing up. Calling another ``show(p)`` works however. 

Workaround for categorical/factor axis:
```python
p.x_range.factors = col_labels
p.y_range.factors = row_labels[::-1]
```

**Comment by bryevdv** [comment] 2017-09-18 01:46
If I switch to not using a data range e.g 
```
plot = figure(plot_height=500, plot_width=1000, toolbar_location=None,x_range=(0,10))
``` 
then the code above works fine with the uncommented line. So I'm guessing it has to with DataRange. OTOH if you just let data range do its thing (Leave the range.end update out) then the ranged update on their own automatically correctly. So there is maybe some issue, but there are two workable workarounds depending on your need

@TiemenSch please make a separate issue with a complete code sample for that.

**Comment by bryevdv** [comment] 2018-03-16 21:09
This issue has been all over the place, but `DynamicImageRenderer` is gone from HV AFAIK, so I am renaming to reflect the last MRE, which does actually seem to show a discrete problem.

**Comment by bryevdv** [comment] 2018-06-27 18:08
Thinking about this further, I don't there is any action to take. If you want to control the start/end of a range, you should be using `Range1d` and not using `DataRange1d` whose purpose is explicitly to automatically set start/end without intervention. 

In retrospect, the right API would have been a user-settable `initial_start` and `initial_end` (or `override_start` or something like that) for fixing these on data ranges, and start/end on DataRange1d ought to have been `readonly` just reporting the computed values back. But the readonly concept did not exist way back at the time data ranges were first created, so that's not what happened. I think it's not a breaking change I would want to make now, and additionally my subjective experience from the lack of question on the mailing list, SO, etc is that this has not generally been a stumbling block.

**Closed by bryevdv** 2018-06-27 18:08 UTC
Labels: type: bug
