### ISSUE TITLE
[BUG] "line_color" not applied from YAML theme file

### ISSUE THREAD

**Issue by tony-bony** [bokeh/bokeh#9173] opened 2019-08-19 10:55 UTC
**ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)**
```
Python version      :  3.7.2 (default, Mar 15 2019, 01:06:31) 
IPython version     :  (not installed)
Tornado version     :  6.0.3
Bokeh version       :  1.3.0
BokehJS static path :  /usr/local/lib/python3.7/site-packages/bokeh/server/static
node.js version     :  v10.15.1
npm version         :  6.10.0
```
OS: Mac OS X Mojave 10.14.6
Browser: Google Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Description of expected behavior and the observed behavior**
Expected behavior: theme should be applied so `line_color` should be set to red
Observed behavior: `line_color` is not applied (remains default)

**Complete, minimal, self-contained example code that reproduces the issue**

main.py
```py
from bokeh.plotting import curdoc, figure

plot = figure()
plot.line(x = [1, 2], y = [1, 2])

curdoc().add_root(plot) 
```
theme.yaml
```yaml
attrs: 
    Line:
        line_width: 10
        line_color: "#FF0000"  
```

**Additional info**

Both files are in `test_yaml` directory. The app is run as follows:
`bokeh serve --show yaml_test`

No JS console warnings or error are given.

The plot looks like:
![Screenshot 2019-08-19 at 12 50 16](https://user-images.githubusercontent.com/10279903/63260205-98ff9580-c280-11e9-8933-3c7d869c6bb6.png)

**Comment by bryevdv** [comment] 2019-08-31 16:43
Thanks for the report @tony-bony

**Comment by osule** [comment] 2019-10-07 22:43
@bryevdv 

I started to look into this and  discovered that `line_color` is set in the `_property_values` of `Line` instance to default blue color.

https://github.com/osule/bokeh/blob/57068d6c50f318cf6e0b6f5eb57ab489c07b8e9d/bokeh/core/property/descriptors.py#L645
```
        if self.name not in obj._property_values:
            return self._get_default(obj)
        else:
            return obj._property_values[self.name]
```
Currently, invoking `apply_theme` on the `Model` is setting its `__theme_values__` property
What do you think of update `_property_values`  dict with property values also?
https://github.com/osule/bokeh/blob/57068d6c50f318cf6e0b6f5eb57ab489c07b8e9d/bokeh/core/has_props.py#L623

**Comment by bryevdv** [comment] 2019-10-07 23:16
@osule I'd definitely welcome some more investigation around this. There are definitely some bugs to sort out, they may be somewhat tricky to trace but I am happy to try to provide any guidance I can. Offhand some comments:

* `obj._property_values` is only ever supposed to contain keys for property values that users have explicitly set via assignments they have themselves made. I.e. it's supposed to keep track of all the things users have manually asked to be overridden. That's obviously not the case here, and is the proximate cause of the issue: `line_color` for the `Line` object, should ***not*** be in `obj._property_values`

   Good places to trace/debug are `_real_set` and `_get_default`

* I would pare the example down as much as possible. I.e. use `Plot` with not axes, no tools, etc. this will make this simpler since many of those things also have `line_color` properties. 

* Two `Line` objects are being created (!) I am not sure if this is something reasonable I have forgotten about, out a very weird (bad?) bug.

**Comment by bryevdv** [comment] 2019-10-07 23:20
Uh, OK, interesting devlopemnt. Paring the example down to the minimal:
```
from bokeh.plotting import curdoc, figure
from bokeh.models import Plot, Range1d, ColumnDataSource, Line

plot = Plot()
plot.x_range = Range1d(0, 3)
plot.y_range = Range1d(0, 3)
source = ColumnDataSource(data=dict(x=[1,2], y=[1,2]))
plot.add_glyph(source, Line(x='x', y='y'))

curdoc().add_root(plot)
```
***WORKS***

**Comment by bryevdv** [comment] 2019-10-07 23:38
@osule this is absolutely an artifact of the higher level plotting api. See this line:

https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/helpers.py#L918

When run with the examples, the args passed to it are:

> <class 'bokeh.models.glyphs.Line'> {'x': 'x', 'y': 'y'} {'line_color': '#1f77b4', 'line_alpha': 1.0}

That precisely counts as *setting* those values, which means to override the theme. The problem is that `_pop_colors_and_alpha` function returns values for color and alpha even when they are not set by the user. It should not do that, at least not for the "normal" glyph.

**Comment by bryevdv** [comment] 2019-10-07 23:40
@solstag can you comment on this in relation to your PR https://github.com/bokeh/bokeh/pull/9153 does your PR keep this behaviour?

**Comment by osule** [comment] 2019-10-08 12:30
Thanks for pointing in the relevant code hotspot  and behavior I may have overlooked @bryevdv.
This will be helpful for me when giving a fresh look at this bug tonight.

**Comment by solstag** [comment] 2019-10-08 12:38
@bryevdv In `_pop_visuals`, I kept this behaviour where some properties, plus all properties with some trait, get forced values. I did so as in `_pop_colors_alpha` it seemed intentional, [there being a (now gone) comment saying so](https://github.com/bokeh/bokeh/blob/master/bokeh/plotting/helpers.py#L295-L298). The properties affected are "text_color", "alpha" and any property whose trait is "color", such as the present case's "line_color".

Eliminating this behaviour would simply be a matter of removing the `setdefault` lines here:

https://github.com/solstag/bokeh/blob/style_visuals/bokeh/plotting/helpers.py#L328-L332

Let me know if this is the way to go and I'll fix it.

**Comment by solstag** [comment] 2019-10-08 12:55
Also, no idea if this even makes sense, but I would add that `_pop_visuals` can be passed a `defaults` dict. So if we can get the values from the theme at that point, we could pass them as the normal glyph's `defaults`, in addition to the explicit values. And that would cascade to the other glyphs, as the normal glyph's values are used as their `defaults`.

**Comment by bryevdv** [comment] 2019-10-08 15:55
@solstag I think we should just make sure `_pop_visuals` does not return values when they would be the same as the base defaults. The reason for this is that theme values are applicable to any Bokeh model, and are handled in one place in the `HasProps` machinery. If we look up theme values and pass them to `pop_visuals` we are spreading the responsibility for handling theme values across multiple places (and only in some cases, not others) I would prefer to the maintain the invariant:

> property values are not "set" if their values are the same as the bas property defaults

Then the existing theme machinery (which applies to all Bokeh models) will work for he special case of colors/alphas no differently from any other case

@osule If you want to work on this and submit a PR that fixes `_pop_colors_alpha` I definitely won't discourage you, but please be aware that there is already an open PR waiting until 2.0 to be merged that completely removes/refactors `_pop_colors_alpha`. I'm OK with just waiting to have this fixed in 2.0 but I am sure Python 2 users would appreciate a fix in 1.4. FYI for a fix to go in 1.4 it would need to be submitted berore the end of next week or so.

**Comment by solstag** [comment] 2019-10-09 23:05
> I think we should just make sure _pop_visuals does not return values when they would be the same as the base defaults.

Ni! @bryevdv I need some precision on what you mean by that.

If it means removing all hardcoded defaults, I'm quite happy with that and it does suffice to remove those lines I mentioned.

If it means returning nothing in case an explicitly passed value happens to be equal to the so called "base default", then I find it weird, and I would need to know where to get these "base defaults" from in order to make these comparisons.

**Comment by bryevdv** [comment] 2019-10-10 01:47
I actually spoke too hastily. I thought the `_pop_colors_and_alpha` function was written to coincidentally return the same color as the `Line.line_color` property. But that's not the case. It just returns the value of `get_default_color` which is whatever it is, and unrelated to the property default, More importantly means that the plotting API setting its own defaults requires actually *setting* property values, and that means that any theme values for those properties are overrides.

Thinking about more things, I am not sure there is a reasonable alternative here:

* If if we wanted to special-case a comparison directly with the theme, *there is nothing requiring a theme to be set yet.* Someone could wait until the very end to supply at theme, at which point it is too late to make a comparison. 

* setting a theme for line color actually seems odd. Themes were imagined for: make the background color on all these 5 plots the same, or set the same font on every axis. But lines? Most plots that have lines have more than one, in which case a theme makes no sense, because multiple lines in a plot are almost always different colors. And if you do just have one line on the plot, well, it's actually less work to just set it in code. 

I'm leaning towards closing this with `noaction` or possibly just a not stating that line color and alpha are not theme-able in conjunction with the `bokeh.plotting` API

**Comment by osule** [comment] 2019-10-10 18:27
I agree with your thoughts @bryevdv 

It isn't so straight-forward to remove entries from the result dictionary returned in `_pop_colors_alpha` without setting the theme earlier unless one tracks these properties are forwarded defaults, and when getting the properties, prefer the theme one over them.

I'll stop here and find another issue to contribute in.

**Comment by solstag** [comment] 2019-10-14 17:13
One could also ask why is the plotting API setting its own defaults when the properties already have defaults of their own... @bryevdv

**Comment by bryevdv** [comment] 2019-10-14 17:25
@solstag Although never fully realized, the idea behind `get_default_color` was to be an abstraction that could e.g. auto-cycle colors when multiple glyphs are added in succession. That's something that could still be pursued and seems useful, except if we hard code things to only ever use the single line color a given glyph type can have. Beyond that, there's just no a-priori reason to suppose that higher level API defaults need to match low level type defaults for any particular reason.

**Comment by bryevdv** [comment] 2019-10-14 17:51
And actually, even that above would not be sufficient, if we did want to support e.g. auto-cycling. Because them values apply to *types* so there is no way to specify multiple values for different glyphs without *setting* the properties on different instances.

**Comment by solstag** [comment] 2019-10-14 18:33
@bryevdv I get it now. Thanks for the explanation!

Although your schema for what we have now seems to be missing one link:

`[*] := if using plotting API`

`set explicitly > [API defaults >] theme > type defaults`

And in the case of my patch for 2.0:

`explicitly set > [set for non-prefixed glyph >] [API defaults >] theme > type defaults`

In any case, the doc for the themes should say something like:

_The `plotting API`'s defaults override some theme properties. Namely: `fill_alpha`, `fill_color`, `line_alpha`, `line_color`, `text_alpha` and `text_color`. Those properties should therefore be set explicitly when using the plotting API._

**Comment by bryevdv** [comment] 2019-10-15 00:35
@solstag that's perfect text, I will add that to the docs in a PR soon (unless you or someone else gets to it sooner!)

**Closed** 2019-10-15 18:31 UTC
Labels: reso: completed, tag: component: docs, type: task
