### ISSUE TITLE
[BUG] gridplot toolbar_options behavior broke in 3.2.2

### ISSUE THREAD

**Issue by andyschuster** [bokeh/bokeh#13397] opened 2023-09-28 16:56 UTC
### Software versions

Python version      :  3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)]
IPython version     :  8.15.0
Tornado version     :  6.3.2
Bokeh version       :  3.2.2
BokehJS static path :  \.venv\Lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.22621-SP0

### Expected behavior

Prior to 3.2.2 it was possible to disable the toolbar logo by passing `toolbar_options={'logo': None}` to `gridplot`. This now throws an exception.

I suspect this might be a broader issue with toolbar_options after the following change in 3.2.2: 

> Allow to merge Toolbar.active_* and other properties ([pull request 13318](https://github.com/bokeh/bokeh/pull/13318))

I verified the bug does not exist in 3.2.1.

### Observed behavior

Passing `toolbar_options={'logo': None}` to `gridplot` throws exception: 

> TypeError: bokeh.models.tools.Toolbar() got multiple values for keyword argument 'logo'

### Example code

```Python
from bokeh import plotting, layouts, io

fig = plotting.figure(title='Test')
fig.circle(0, 0)

plotting.show(layouts.gridplot(
    [[fig]],
    toolbar_options={'logo': None},  # THIS line causes issue
))
```

**Comment by bryevdv** [comment] 2023-09-28 17:00
dupe of https://github.com/bokeh/bokeh/issues/13369

**Closed as completed by bryevdv** 2023-09-28 17:00 UTC
Labels: reso: duplicate
