### ISSUE TITLE
Streaming greater number of Pandas Data types[BUG]

### ISSUE THREAD

**Issue by Tmorrison2017fit** [bokeh/bokeh#11172] opened 2021-04-16 19:09 UTC
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

**Comment by Tmorrison2017fit** [comment] 2021-04-16 19:11
`

import logging # isort:skip
log = logging.getLogger(__name__)
#import the python tester
import pytest

#bokeh
from bokeh.util.dependencies import import_optional

#all pandas data types
__all__ = (
    'pd',
)

#including test pandas
@pytest.fixture
def pd():
    ''' A PyTest fixture that will automatically skip a test if Pandas is
    not installed.

    '''

    #import pandass
    pandas = import_optional('pandas')
    if pandas is None:
        pytest.skip('pandas is not installed')
    return pandas`

**Comment by bryevdv** [comment] 2021-04-16 19:11
dupe of https://github.com/bokeh/bokeh/issues/10904

**Closed** 2021-04-16 19:11 UTC
Labels: TRIAGE
