### ISSUE TITLE
[FEATURE] Sliders to take a list of allowed values

### ISSUE THREAD

**Issue by andrzejnovak** [bokeh/bokeh#10325] opened 2020-07-21 00:24 UTC
**Is your feature request related to a problem? Please describe.**
I would like to use RangeSlider (but really could apply to any slider) to select histogram bin range. This range is not necessarily uniform, so specification with `start:stop:step` is insufficient

**Describe the solution you'd like**
`"start"`, `"stop"` and `"step"` kwargs could be optionally replaced by sth like `"values"` which would take a list or array of allowed slider values.

**Describe alternatives you've considered**
I don't seem to be able to find any good alternatives. Customs widgets don't seem to play nice with layouts.

**Comment by bryevdv** [comment] 2020-07-21 00:29
This is a dupe of #9843

**Closed by bryevdv** 2020-07-21 00:29 UTC
Labels: TRIAGE
