### ISSUE TITLE
Data dropped on field name collision in `ColumnDataSource`

### ISSUE THREAD

**Issue by jcrist** [bokeh/bokeh#4030] opened 2016-03-15 03:38 UTC
If I create a `ColumnDataSource` with a field (`"y"` in the example below), then use that source to create some glyphs, but pass in extra data to other parameters that have a name collision with a field in the source (`y` in the example below), the extra data is dropped.

```python
In [1]: import bokeh.plotting as bp

In [2]: bp.output_file('foo.html')

In [3]: f = bp.figure()

In [4]: data = {'y': [1, 2, 3, 4, 5]}

In [5]: source = bp.ColumnDataSource(data)

In [6]: y = [5, 4, 3, 2, 1]

In [7]: f.circle(x='y', y=y, radius=0.2, source=source)

In [8]: bp.show(f)

In [9]: import bokeh

In [10]: bokeh.__version__
Out[10]: '0.11.1'
```

<img width="651" alt="screen shot 2016-03-14 at 10 31 23 pm" src="https://cloud.githubusercontent.com/assets/2783717/13767010/c12e35e8-ea34-11e5-83be-6db5911d13b3.png">

Perhaps some name mangling scheme should be adapted for automatically added fields to `ColumnDataSource`s (at least on a collision with an existing field).

**Comment by bryevdv** [comment] 2016-03-19 19:36
Hrm I thought we had actually just disallowed mixing things like this completely, but maybe that PR was not accepted for some reason. I think just disallowing supplying both literal values and an explicit source, would be be safest policy?

**Comment by jcrist** [comment] 2016-03-21 18:20
That's probably a good idea (assuming that only forbids array/list input, and not scalars like `radius=0.5`). I only ran into this issue because I was curious how bokeh handled it, not because it's a real workflow I want to use.

**Comment by bryevdv** [comment] 2016-03-21 19:29
Yes, scalar are handled differently, they are "values" not "fields" so it would only affect sequence literals.

**Comment by bryevdv** [comment] 2016-04-08 19:16
Also, this is a dupe of #2056

**Closed by bryevdv** 2016-04-08 19:16 UTC
Labels: type: discussion
