### ISSUE TITLE
BoxAnnotation does not appear to handle formal NumberSpec

### ISSUE THREAD

**Issue by hafen** [bokeh/bokeh#6669] opened 2017-07-24 20:36 UTC
It appears that BoxAnnotation properties like `top`, `bottom`, etc. only support a simple specification like `"top": 80"` instead of `"top": { "value": 80 }`. For example, the output of this example: http://bokeh.pydata.org/en/latest/docs/user_guide/annotations.html#box-annotations is available in these gists: https://gist.github.com/hafen/288265f12ec58ae5d5f82768756e57ad, the first using `"top": 80"` and the second using `"top": { "value": 80 }` (this is the only difference between the two). The modified box annotation in the second gist doesn't work.

This could very well extend to other annotations but I have only checked BoxAnnotation.

**Comment by mattpap** [comment] 2017-07-24 21:17
This is a duplicate of issue #6163.

**Comment by bryevdv** [comment] 2017-07-24 23:02
@mattpap I disagree that this is a duplicate. In this case `top = Either(Auto, NumberSpec())` so `"top": { "value": 80 }` not working is a bug. 

#6163 is about whether all annotations should be vectorizable or not (e.g. should `Label` and `LabelSet` be distinct or not?)

**Closed** 2022-08-06 17:31 UTC
Labels: type: bug, tag: component: bokehjs
