### ISSUE TITLE
Option to *not* share selections and inspections

### ISSUE THREAD

**Issue by Squirrel8475** [bokeh/bokeh#10441] opened 2020-08-28 11:42 UTC
### Description:
A first scatterline is defined combining:
-  an instance of the Line glyph (_blue_)
-  an instance of the Circle glyph (_blue_)
-  and another instance of the Circle glyph aimed at defining the hover style (circle color changed as _orange_)

A second scatterline is built repeating the process but using _red_ instead of _blue_. A single hover tool is added to the plot combining the renderers. A single datasource is used for all the renderers.
 
### Expected behavior: 
A _blue_ circle should change to _orange_ when hovered.
A _red_ circle should change to _orange_ when hovered.
![20200828_expected_behavior](https://user-images.githubusercontent.com/52817858/91556864-bb1c0100-e933-11ea-8f2e-5d769f59264d.jpg)

### Observed behavior
Two circles, one _blue_ and one _red_, change to _orange_ when the _red_ is hovered.
When a _blue_ circle is hovered, it does not change color.
![20200828_actual_behavior](https://user-images.githubusercontent.com/52817858/91556865-bbb49780-e933-11ea-91b8-15505be30897.jpg)

### Tested so far
-   Defining multiple hover tools did not help.
-   **Expected behavior can be obtained by creating two different instances of ColumnDataSource containing exactly the same data. This solution is not very convenient as the data source must be duplicated every time a new scatterline is added. The underlying question would be is there a way of achieving the expecting behavior without cloning the data source?** 

### Version
Bokeh version 2.1.1
Python version 3.8.3 
Browser: Google Chrome Version 84.0.4147.135 64bits under Windows 

### Minimal example
Set _clone_cds_ to _False_ to reproduce the unexpected behavior. 
Setting _clone_cds_ to _True_ to get the expected behavior at the price of cloning the datasource for every scatterline.

```
from bokeh import models as bkmdl
from bokeh import plotting as bkplt

# Data
data0 = {
        'x0':[0.5,5,  12, 16, 20], 
        'y0':[2, 144, 169,196,220],
        'z0':[5, 80,  65, 52, 50],
        'a0':[3, 4,   5,  6,  7] ,       
        'b0':[5, 120, 200,165,125]
        }
cds0 = bkmdl.ColumnDataSource(data0)

clone_cds=False
if(clone_cds):
    cds1 = bkmdl.ColumnDataSource(data0)

# Figure 
plot=bkmdl.Plot()
plot.x_range=bkmdl.DataRange1d()
plot.x_scale=bkmdl.LinearScale()
x_axis=bkmdl.LinearAxis()   
y_axis=bkmdl.LinearAxis()   
plot.add_layout(obj=x_axis,place='below')
plot.add_layout(obj=y_axis,place='left')

# First scatterline
xy0={'x':'x0','y':'y0'}                             
g0=bkmdl.Line(line_width=6, line_color="navy",**xy0) # Line as glyph...
g0s=bkmdl.Circle(size=24, fill_color="navy",**xy0)   #... with circle markers as scatter glyph
g0h=bkmdl.Circle(size=24, fill_color="orange",**xy0) #... and hover version of it
r0=plot.add_glyph(source_or_glyph=cds0,glyph=g0)     # Add line to plot
r0h=plot.add_glyph(source_or_glyph=cds0,glyph=g0s)   # Add markers to plot
r0h.update(hover_glyph=g0h)                          # Add hover glyph

# Repeat with a second scatterline
xy1={'x':'x0','y':'b0'} 
if(not clone_cds):
    source1=cds0
else:
    source1=cds1    
g1=bkmdl.Line(line_width=6, line_color="firebrick",**xy1) 
g1s=bkmdl.Circle(size=24, fill_color="firebrick",**xy1)  
g1h=bkmdl.Circle(size=24, fill_color="orange",**xy1)
r1=plot.add_glyph(source_or_glyph=source1,glyph=g1)
r1h=plot.add_glyph(source_or_glyph=source1,glyph=g1s)
r1h.update(hover_glyph=g1h)

# Hover 
hover_tool=bkmdl.HoverTool()
hover_tool.tooltips=hover_tool.tooltips[0:2]
hover_tool.mode="mouse"
hover_tool.line_policy="nearest"
hover_tool.update(renderers=[r0,r0h,r1,r1h]) 
plot.add_tools(hover_tool)       

bkplt.output_file('test.html')
bkplt.show(plot)
```

**Comment by bryevdv** [comment] 2020-08-28 16:33
Hi @Squirrel8475 thank you for your very detailed report. However, your intuition about expected behaviors is not quite correct. Specifically, Bokeh selections and inspections are properties of data sources, and in Bokeh ***sharing a data source is the explicit mechanism to share selections and inspections.***. This is explained in this section of the users guide 

https://docs.bokeh.org/en/latest/docs/user_guide/interaction/linking.html#linked-brushing

(The page there somewhat minimally only mentions selections I notice, but everything there applies to inspections, i.e. hover, as well)

So the expected behavior, when a data source is shared, is that all corresponding points in glyphs that share the source "light up". The bug is in fact, only the last observation:

>  When a blue circle is hovered, it does not change color.

I believe however that this is duplicate of https://github.com/bokeh/bokeh/issues/7397

Regarding "creating two different instances of ColumnDataSource containing exactly the same data." It's not clear to me that this is true  in general. You would need to data sources, but they would each only need to contain whatever minimum amount of data is required for the glyph, and any hovers or other transforms. In some cases that might mean a complete duplication, but certainly not in general. In the code above, e.g only one CDS would need to have `y0` and only one CDS would need to have `b0`

Rather than close this immediately with `repo:dupe` I'll leave it open for now in case any @bokeh/dev want to chime in with any ideas about new feature development related to this.

**Comment by philippjfr** [comment] 2020-08-28 16:37
The only way to decouple the linking on a single data source would be if we created separate selection indices for each renderer. Hard to see how to do that in a backward compatible way but I can see it being useful.

**Comment by bryevdv** [comment] 2020-08-28 16:43
Well, one idea might be: we could report the glyph the "originates" an inspection along with the inspection, and then e.g. have flag to tell glyphs to only render hover mode if they they are the originator. But I think there are alot of fine details that glosses over that might make that impossible/impractical. (Specifically what happens when a hover inspection hits multiple glyphs)

**Comment by bryevdv** [comment] 2020-08-28 16:48
And then another completely different avenue would be to find a way to have CDSes be able "share" columns, i.e so two glyphs could have two different CDSes (so no linked behaviors) without duplicating any data. I had had some ideas about this a *long* time ago, e.g some central "data store" that actually had all the data and then CDS just had references in to it. But this was never pursued and there's certainly any number of pitfalls possible there too (and also maintaining compatibility would be a very hard problem)

**Comment by Squirrel8475** [comment] 2020-09-01 17:42
Thank you very much for your detailed answers!

**Comment by bryevdv** [comment] 2022-03-06 18:55
Besides #7397 this also seems a dupe of #7644 which is explicitly about adding options to suppress selection sharing.

**Closed by bryevdv** 2022-03-06 18:55 UTC
Labels: type: discussion
