### ISSUE TITLE
[BUG] Div size not inherited starting with v2.3.0

### ISSUE THREAD

**Issue by Suicoleiro** [bokeh/bokeh#11261] opened 2021-05-12 12:22 UTC
When updating to Bokeh v2.3.x the Div widget <b> width </b>and <b>height</b> are not embedded in the html file.

<b>Minimal Example:</b>
```
from bokeh.io import show
from bokeh.models import Div

myDiv = Div(text='my test div', width=600, height=200, background='lightgrey')

show(myDiv)
```
Expected outcome: a Div of the size 600 x 200 px

Observed outcome:

<b>v2.2.3</b>
Div of the size 600 x 200 px
![image](https://user-images.githubusercontent.com/56967998/117973648-ee20ec00-b32c-11eb-8e01-0ef69ca26282.png)

<b>v2.3.x (x=0,1,2)</b>
Div of the size 63x18px just fitting the text "my test div"
![image](https://user-images.githubusercontent.com/56967998/117973372-9bdfcb00-b32c-11eb-9fde-5b9d60fb565c.png)

sizing_mode, width_policy, height_policy properties do not resolve the issue.

Thanks for the support!

**Comment by mattpap** [comment] 2021-05-12 12:46
This is a duplicate of issue #11161.

**Closed by mattpap** 2021-05-12 12:46 UTC
Labels: TRIAGE
