### ISSUE TITLE
SelectEditor raises TypeError

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#7341] opened 2017-12-21 14:26 UTC
`bokeh==0.12.7`

1. Run [examples/models/file/data_tables.py](https://github.com/bokeh/bokeh/blob/53cd93bea4168f87d296ad8a0b9bcd7d18e886ae/examples/models/file/data_tables.py) from the command line. You get a `UnicodeEncodeError` on saving html (not really concerned).
2. Copy the code into a notebook and run. Try modifying a cell in e.g. *Manufacturer* column. No values get displayed, and you get `Uncaught TypeError: Cannot read property 'length' of undefined` in the console.

**Comment by bryevdv** [comment] 2017-12-21 14:49
@rs2 can you verify whether there is an issue with the current release? Once old releases are released, they are done. We do not have the capability or resources to make patch releases to old branches.

**Comment by rs2** [comment] 2017-12-21 16:40
@bryevdv Further regression in `0.12.13`. Unable to edit cells using any `CellEditor `. And another side-effect is that long tables scroll to the end, i.e. display `.tail()`, not '.head()'.

```
Uncaught TypeError: Cannot read property 'container' of undefined
    at t.render (cdn.pydata.org/bokeh/release/bokeh-tables-0.12.13.min.js:1)
...
    at HTMLDivElement.handleDblClick (cdn.pydata.org/bokeh/release/bokeh-tables-0.12.13.min.js:34)
```

**Comment by bryevdv** [comment] 2017-12-21 16:42
@rs2 Yes the editing is noted and scheduled to be fixed fo rate next release https://github.com/bokeh/bokeh/issues/7304 

cc @mattpap

**Comment by bryevdv** [comment] 2017-12-26 22:38
@rs2  I should have a dev build out by tomorrow with the fix for editing

**Comment by bryevdv** [comment] 2017-12-27 16:59
The other PR is merged, I will start a dev build presently.

**Comment by bryevdv** [comment] 2018-01-02 01:08
@rs2 I can't reproduce the original issue with `master` and it is editable as well (see first row mpg changed to 48 with plot updated):

<img width="1042" alt="screen shot 2018-01-01 at 19 07 08" src="https://user-images.githubusercontent.com/1078448/34472399-0cc79a14-ef27-11e7-913d-c5d5064dd8cd.png">

Additionally the scroll issue is already reported in #7139 so I am going to close this issue.

**Closed by bryevdv** 2018-01-02 01:08 UTC
