### ISSUE TITLE
[BUG] RangeSlider not displaying vertically

### ISSUE THREAD

**Issue by a-lensh** [bokeh/bokeh#11094] opened 2021-03-22 16:02 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

python 3.7, bokeh 2.3.0, Pycharm Community 2020.3.3, Windows 10, Chrome 88.0.4324.190

#### Description of expected behavior and the observed behavior

When creating a vertical RangeSlider in my report it seems to be compressed and is not displaying properly. 
It appears to be missing the range portion and only has the sliders themselves with no range to move over.
When attempting to change values they change to NaN as seen in the log message.

#### Complete, minimal, self-contained example code that reproduces the issue

```

from bokeh.plotting import show, output_file
from bokeh.models import RangeSlider, NumeralTickFormatter, CustomJS


sld=RangeSlider(title=None, start=0, show_value=False,
                          end=1000, value=(0, 1000), direction='rtl', height=500, width=100,
                       step=10, orientation='vertical', format=NumeralTickFormatter(format="0%"))

sld.js_on_change('value', CustomJS(code="""
console.log(this.value)
"""))

output_file('tst.html', mode='inline')

show(sld)

```

#### Stack traceback and/or browser JavaScript console output

No Errors in python console.
Slider value printed to log after trying to change slider values:
Array(2)
0: NaN
1: NaN
length: 2

#### Screenshots or screencasts of the bug in action

The compressed slider can be seen in the top left corner.

![bokeh_slider_issue](https://user-images.githubusercontent.com/36133250/112019958-005a8700-8b41-11eb-84d3-bbf28c8cc5ea.jpg)

**Comment by bryevdv** [comment] 2021-03-22 16:09
@mattpap should range slider have an `orientation` property? AFAIK the sliders have not supported vertical orientations.

**Comment by mattpap** [comment] 2021-03-22 16:35
It does have, but it's defined in `Widget` (for some reason I don't remember right now).

**Comment by mattpap** [comment] 2021-03-22 16:35
This is a duplicate of issue #10444.

**Closed by mattpap** 2021-03-22 16:35 UTC
Labels: type: discussion
