### ISSUE TITLE
Bokeh 0.12.14 doesn't highlight initially selected options in MultiSelect widget

### ISSUE THREAD

**Issue by resenganalytics** [bokeh/bokeh#7515] opened 2018-02-09 12:43 UTC
Tested on Chrome and Firefox clients
Server  is Python 3.6 on Ubuntu 16.04
A code snippet to reproduce the issue on bokeh server:

```
from bokeh.models.widgets import MultiSelect, Paragraph
from bokeh.layouts import column
from bokeh.io import curdoc

multi_select = MultiSelect(title="Option:", value=["foo", "quux"],
                           options=[("foo", "Foo"), ("bar", "BAR"), ("baz", "bAz"), ("quux", "quux")])

p = Paragraph(text='Selected options: ' + ' '.join(multi_select.value), width=200, height=100)
layout = column(multi_select, p)
curdoc().add_root(layout)

```

The Stack traceback   and browser JavaScript console output look normal.

**Comment by bryevdv** [comment] 2018-02-09 17:56
OK this confused me at first, since things seemed to be behaving as normal. It's probably worth stating explicitly that this has to do specifically with *initial* selected options. I've updated the title.

**Comment by kagacins** [comment] 2018-02-14 01:03
Hello.  I'm seeing a similar but different issue after moving from 0.12.13 last night to 0.12.14 today with Bokeh server.  I have a series of MultiSelect widgets.  Selecting items triggers a callback where I filter some data and create a statistical forecast on the filtered data.  However, after the callback, the MultiSelects lose both their highlighting and the actual selection value.  Additionally, it seems the loss of selection(s) seems almost dependent on the length of time the callback is running (on a smaller filtered data set the values and highlighting are retained, on a larger filtered data set they tend to always disappear).  I am also unable to re-select/highlight the desired items by storing their initial status.  Please let me know if you need any additional information from me.

**Comment by bryevdv** [comment] 2018-03-20 20:20
@kagacins I can't reproduce anything like that, please open a separate issue with an MRE

**Comment by bryevdv** [comment] 2018-03-20 20:21
@mattpap This is fixed by simply adding a call to `render_selection` to the end of `render` I will make a PR and try to add some tests.

**Closed** 2018-03-20 22:12 UTC
Labels: tag: component: bokehjs, type: bug
