### ISSUE TITLE
[BUG] Error: Cannot find module '677'

### ISSUE THREAD

**Issue by EduardoLZevallos** [bokeh/bokeh#13550] opened 2023-11-25 17:44 UTC
### Software versions

Python version        :  3.11.6 (main, Oct 23 2023, 22:47:21) [GCC 9.4.0]
IPython version       :  8.17.2
Tornado version       :  6.3.3
Bokeh version         :  3.3.1
BokehJS static path   :  /home/madmax/projects/calculator_tutorial/lib/python3.11/site-packages/bokeh/server/static
node.js version       :  (not installed)
npm version           :  (not installed)
jupyter_bokeh version :  (not installed)
Operating system      :  Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31

### Browser name and version

fire fox

### Jupyter notebook / Jupyter Lab version

jupyter-lab 4.0.9

### Expected behavior

I refreshed by browser and I expected to use my notebook without issue

### Observed behavior

When I refreshed the browser, in the console I am getting an error "cannot find module 677".  I found this error when trying to trouble shoot why I don't have any panel button reactivity.

### Example code

```Python
I am getting this error just from refreshing the browser of my notebook
```

### Screenshots

![image](https://github.com/bokeh/bokeh/assets/72849155/90eb3579-93a6-4519-965a-82bdaec8dfdb)

**Comment by mattpap** [comment] 2023-11-25 17:54
In bokeh 3.3.1, module 677 refers to the entry point of `bokeh-mathjax` bundle, which should be included unconditionally (I presume). Did you see any "JavaScript error: ..."? If so then this may be a duplicate of issue #13499.

**Comment by bryevdv** [comment] 2023-12-07 19:04
Closing for lack of response.

**Closed as completed by bryevdv** 2023-12-07 19:04 UTC
Labels: type: discussion

**Comment by nashikhmin** [comment] 2024-01-17 18:59
Hello I have the same issue.
```
[0117/225119.000:INFO:CONSOLE(2727)] "Start app component", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.012:INFO:CONSOLE(2727)] "Angular is running in development mode. Call enableProdMode() to enable production mode.", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.029:INFO:CONSOLE(2727)] "Script manager: Is online status: true", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.179:INFO:CONSOLE(2727)] "Bokeh: BokehJS not loaded, scheduling load and callback at", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.180:INFO:CONSOLE(2727)] "Wed Jan 17 2024 22:51:19 GMT+0400 (Armenia Standard Time)", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.182:INFO:CONSOLE(2727)] "Bokeh: injecting script tag for BokehJS library: ", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.183:INFO:CONSOLE(2727)] "https://cdn.bokeh.org/bokeh/release/bokeh-3.3.3.min.js", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.185:INFO:CONSOLE(2727)] "Bokeh: injecting script tag for BokehJS library: ", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.189:INFO:CONSOLE(2727)] "https://cdn.bokeh.org/bokeh/release/bokeh-gl-3.3.3.min.js", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.190:INFO:CONSOLE(2727)] "Bokeh: injecting script tag for BokehJS library: ", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.191:INFO:CONSOLE(2727)] "https://cdn.bokeh.org/bokeh/release/bokeh-widgets-3.3.3.min.js", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.192:INFO:CONSOLE(2727)] "Bokeh: injecting script tag for BokehJS library: ", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.193:INFO:CONSOLE(2727)] "https://cdn.bokeh.org/bokeh/release/bokeh-tables-3.3.3.min.js", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.194:INFO:CONSOLE(2727)] "Bokeh: injecting script tag for BokehJS library: ", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.194:INFO:CONSOLE(2727)] "https://cdn.holoviz.org/panel/1.3.4/dist/panel.min.js", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.258:INFO:CONSOLE(16)] "Uncaught ReferenceError: jsPanel is not defined", source: https://cdn.jsdelivr.net/npm/jspanel4@4.12.0/dist/extensions/modal/jspanel.modal.js (16)
[0117/225119.420:INFO:CONSOLE(2727)] "Bokeh: all BokehJS libraries/stylesheets loaded", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.421:INFO:CONSOLE(2727)] "Bokeh: BokehJS plotting callback run at", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.423:INFO:CONSOLE(2727)] "Wed Jan 17 2024 22:51:19 GMT+0400 (Armenia Standard Time)", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.424:INFO:CONSOLE(2727)] "[bokeh] setting log level to: 'info'", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.426:INFO:CONSOLE(2727)] "Bokeh: all callbacks have finished", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.562:INFO:CONSOLE(2727)] "Unhandled Promise rejection:", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.563:INFO:CONSOLE(2727)] "Cannot find module '677'", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.564:INFO:CONSOLE(2727)] "; Zone:", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.565:INFO:CONSOLE(2727)] "<root>", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.566:INFO:CONSOLE(2727)] "; Task:", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.567:INFO:CONSOLE(2727)] "Promise.then", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.568:INFO:CONSOLE(2727)] "; Value:", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.569:INFO:CONSOLE(2727)] "Error: Cannot find module '677'", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
[0117/225119.570:INFO:CONSOLE(2727)] "Error: Cannot find module '677'
    at require (https://cdn.bokeh.org/bokeh/release/bokeh-3.3.3.min.js:89:23)
    at https://cdn.bokeh.org/bokeh/release/bokeh-3.3.3.min.js:321:1488
    at push.31952._ZoneDelegate.invoke (http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:490:30)
    at push.31952.Zone.run (http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:250:47)
    at http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:1407:38
    at push.31952._ZoneDelegate.invokeTask (http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:524:35)
    at push.31952.Zone.runTask (http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:295:51)
    at drainMicroTaskQueue (http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:713:39)", source: http://127.0.0.1:63343/jupyter/main.dadf39cb339a9254.js (2727)
2024-01-17 22:51:19,907 [  10964]   WARN - #java.lang.Class - Unhandled Promise rejection:
2024-01-17 22:51:19,955 [  11012]   WARN - #java.lang.Class - Cannot find module '677'
2024-01-17 22:51:19,956 [  11013]   WARN - #java.lang.Class - ; Zone:
2024-01-17 22:51:19,957 [  11014]   WARN - #java.lang.Class - <root>
2024-01-17 22:51:19,958 [  11015]   WARN - #java.lang.Class - ; Task:
2024-01-17 22:51:19,959 [  11016]   WARN - #java.lang.Class - Promise.then
2024-01-17 22:51:19,959 [  11016]   WARN - #java.lang.Class - ; Value:
2024-01-17 22:51:19,960 [  11017]   WARN - #java.lang.Class - Error: Cannot find module '677'
2024-01-17 22:51:20,066 [  11123]   WARN - #java.lang.Class - Error: Cannot find module '677'
    at require (https://cdn.bokeh.org/bokeh/release/bokeh-3.3.3.min.js:89:23)
    at https://cdn.bokeh.org/bokeh/release/bokeh-3.3.3.min.js:321:1488
    at push.31952._ZoneDelegate.invoke (http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:490:30)
    at push.31952.Zone.run (http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:250:47)
    at http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:1407:38
    at push.31952._ZoneDelegate.invokeTask (http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:524:35)
    at push.31952.Zone.runTask (http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:295:51)
    at drainMicroTaskQueue (http://127.0.0.1:63343/jupyter/polyfills.129d435780066154.js:713:39)
```
there is a log. Do you know what to do?

**Comment by nashikhmin** [comment] 2024-01-18 13:43
I found the reason of this error t is connected with Holoviz panel. It initialize bokeh however forget to include bokeh-mathjax It is not important error for holoviz  and everything work without it
