### ISSUE TITLE
Bokeh show() produces empty blue screen on Cloud9 Linux server

### ISSUE THREAD

**Issue by mgmoulton** [bokeh/bokeh#7242] opened 2017-11-22 01:14 UTC
Hi,
Here is the code. 
#########################################################
#test.py
from bokeh.plotting import figure, output_file, show

# create a Figure object
p = figure(plot_width=300, plot_height=300, tools="pan,reset,save")
# add a Circle renderer to this figure
p.circle([1, 2.5, 3, 2], [2, 3, 1, 1.5], radius=0.3, alpha=0.5)

# specify how to output the plot(s)
#output_file("test.html")

# display the figure
show(p)

**Comment by bryevdv** [comment] 2017-11-25 19:13
dupe of #7246

**Closed by bryevdv** 2017-11-25 19:13 UTC
