### ISSUE TITLE
[BUG] Units in blackbody example should be upright

### ISSUE THREAD

**Issue by zmoon** [bokeh/bokeh#12533] opened 2022-10-31 19:11 UTC
### Software versions

.

### Expected behavior

.

### Observed behavior

.

### Example code

```Python
.
```

**Comment by bryevdv** [comment] 2022-10-31 19:12
dupe of #12531

**Comment by zmoon** [comment] 2022-10-31 19:13
It's not a dupe. Different issue, that I am opening a PR for.

**Closed by bryevdv** 2022-10-31 19:12 UTC
Labels: TRIAGE
