### ISSUE TITLE
TimeSeries not correclty represent x-axis when applied to DataFrame with datetime index

### ISSUE THREAD

**Issue by akasolace** [bokeh/bokeh#4344] opened 2016-05-20 06:39 UTC
Bokeh version: 0.11.1

I'm trying to use TimeSeries to plot a Pandas dataframe with a DateTime index but it is not working :  I get time in milliseconds in the x-axis (as well as in the hover tool).
A partial fix is to create a Date column from the index and to specify explicitly x to use that column: it fixes the x display but the hover tool is still not working.

.

**Comment by sanga** [comment] 2016-05-20 08:55
+1 I struck this too. Given that Pandas is the default data analysis tool in Python it would seem natural that a TimeSeries plot in Bokeh would understand Pandas datetime format

**Comment by birdsarah** [comment] 2016-05-21 04:52
> it would seem natural that a TimeSeries plot in Bokeh would understand Pandas datetime format

I believe the problem is that its an index, not the format.

Agreed that this would be a good addition. If either of you are familiar with pandas this should just be a matter of tweaking our data pre-processing for TimeSeries if you'd like to take a stab.

**Comment by sanga** [comment] 2016-05-21 11:29
You're right. Sorry I jumped to conclusions (and actually if I'd have read the original report more carefully I'd have realised that too). It's got nothing to do with date formats. 

So I had a quick crack at using the dataframe index for the x axis if no x is defined. However, didn't manage to find the correct place in the bokeh machinery to make that happen.

**Comment by birdsarah** [comment] 2016-05-21 17:10
I'm not sure, as I've never worked on the charts api. But it looks to me like the TimeSeries builder points directly to LineBuilder (https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builders/line_builder.py).

There's some lines in the parent XYBuilder about handling dtypes of different pandas columns: https://github.com/bokeh/bokeh/blob/master/bokeh/charts/builder.py#L695 

 Ping @fpliger.

**Comment by akasolace** [comment] 2016-05-22 20:21
Could this be link to bug #4183

**Comment by damianavila** [comment] 2016-05-25 23:25
This was closed by @akasolace, but still I think it deserve some more discussion? ping @birdsarah and @fpliger

**Comment by akasolace** [comment] 2016-05-28 17:57
I actually closed it by mistake.
I just wanted to delete a comment that I made but apparently I closed the bug .... sorry for that !

**Comment by canavandl** [comment] 2016-06-06 19:42
From @ChristianTremblay on Gitter:

Bokeh doesn't properly encode pd.DatetimeIndex instances, so making a TimeSeries plot using a df with a datetime index will result in an incorrect x-axis. Looking at the generated document JSON it appears that the index is encoded simply as the element indices (i.e. [0,1,2,3...])

code to reproduce:
```python
import pandas as pd
import numpy as np
from bokeh.charts import TimeSeries
from bokeh.io import output_file, show
output_file('ts.html')

dates = pd.date_range('1950-01', '2013-03', freq='M')
df = pd.DataFrame(data={'data':np.random.randn(758)}, index=dates)

ts = TimeSeries(df, x='index', y='data')
show(ts)
```

output:
<img width="675" alt="screen shot 2016-06-06 at 2 31 21 pm" src="https://cloud.githubusercontent.com/assets/2198981/15834943/72c48ae6-2bf3-11e6-802b-1a65f88ecee9.png">

However - converting the DatetimeIndex to a dtype=datetime column and and plotting using the new 'dates' column, the x_range will be properly set.
```python
df['dates'] = df.index.to_datetime()

ts = TimeSeries(df, x='dates', y='data')
show(ts)
```

Solution would involve adding conditional to https://github.com/bokeh/bokeh/blob/master/bokeh/core/json_encoder.py
to check for pd.DatetimeIndex and properly encoding there.

**Closed** 2016-06-12 02:11 UTC
Labels: tag: API: charts, type: feature
