### ISSUE TITLE
Desired feature for textInput widget: is it possible to mask the entered text, e.g. password input?

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#4112] opened 2016-04-05 16:03 UTC
Desired feature for textInput: is it possible to mask the entered text, e.g. password input?

I am using Bokeh to provide user a place to enter username and password so that data can be downloaded and analyzed. I need the password text input field be masked.

**Comment by bryevdv** [comment] 2016-04-05 16:07
This seems like a nice feature, but it does not currently exist. I have tagged this issue as a feature request. In the mean time, it is now possible to wrap other JS libraries for use with Bokeh, you can see an example here: https://github.com/bokeh/bokeh/blob/master/examples/models/custom.py We are still working on documenting the JS api

**Comment by birdsarah** [comment] 2016-04-28 20:32
For a basic solution, you just need type='password' but there might be some browsers that need more support. Can we expose "type"? (I know there might be some typescript api conflict)

**Comment by charleywan2004** [comment] 2016-04-30 15:34
![image](https://cloud.githubusercontent.com/assets/15861395/14936958/5e2105e0-0ec7-11e6-944b-99ee12bce59c.png)

Currently "type" is not exposed.

**Comment by bryevdv** [comment] 2019-03-08 05:50
https://github.com/bokeh/bokeh/issues/6492 was a dupe of this but it was not noticed. In any case password hiding was implemented a long ago, so I will mark this issue as the dupe.

**Closed by bryevdv** 2019-03-08 05:50 UTC
Labels: type: feature
