### ISSUE TITLE
Expose initial_start and initial_end in Range1d

### ISSUE THREAD

**Issue by bgyarfas** [bokeh/bokeh#6320] opened 2017-05-23 12:46 UTC
In some cases you might not know the range of data when a bokeh application initially loads. In this case the `Range1d` is set to a default of `[0,1]` for the figure you intend to plot in. After plotting the data you can of course change `figure.x_range.start` and `figure.x_range.end` to have the graph contain your newly plotted data. But, if you have the `ResetTool` available and use it, the range will reset to `[0,1]`. If the properties `_initial_start` and `_initial_end` are exposed you can change the 'default' range so reset works properly.

**Comment by bryevdv** [comment] 2017-05-26 15:11
@mattpap do you have any thoughts on this? I had originally thought the tool itself might be the best place for this configuration. Then I thought perhaps not, because there can be multiple axes/ranges. It seems like a nice feature to support specifying the "reset state" explicitly but it runs into a lot of rough corners suprisingly quickly.

**Comment by mattpap** [comment] 2017-05-26 17:05
@bryevdv, I don't have any immediate advice.

**Comment by p-himik** [comment] 2017-08-12 09:40
I just encountered the need for such feature as well.

What about some signal to recompute `initial_start` and `initial_end`? The user won't be able to change them directly, so no inconsistencies should be possible.

**Comment by bryevdv** [comment] 2018-02-21 17:36
I think this might be a dupe of https://github.com/bokeh/bokeh/issues/5443 ?

**Comment by philippjfr** [comment] 2018-06-02 11:35
Does exposing ``initial_start`` and ``initial_end`` on Range1d still seem like the best approach here? If so I'll go ahead an implement that since I need some way of setting these properties from outside the Range1d model to fix https://github.com/bokeh/bokeh/issues/7936.

**Closed** 2018-06-04 20:07 UTC
Labels: tag: component: bokehjs, type: feature
