### ISSUE TITLE
[FEATURE] Rescaling of Text 

### ISSUE THREAD

**Issue by HuangYanqiColumbia** [bokeh/bokeh#10864] opened 2021-01-22 21:26 UTC
I added text to a `bokeh Figure` as follows, 
```
import bokeh.plotting as bop
from bokeh.models import Text
from bokeh.models import ColumnDataSource

fig = bop.Figure()
source = ColumnDataSource(dict(x=xs, y=ys, text=texts))
text = Text(x="x", y="y", text="text", text_color="black")
fig.add_glyph(source, text)
bop.output_notebook()
bop.show(fig)
```
However, when I zoom in, the text 'a', 'b' or 'c' don't re-scale. 
I wish the feature of re-scalable text could be added the next few versions. 
Thanks!!!

**Comment by bryevdv** [comment] 2021-01-22 21:33
duplicate of #9407

**Closed by bryevdv** 2021-01-22 21:33 UTC
