### ISSUE TITLE
[BUG] Browser error while bind the GlyphRenderer as the CustomJS argument of js_on_change('data', custom_js)

### ISSUE THREAD

**Issue by maeglin89273** [bokeh/bokeh#9899] opened 2020-04-09 07:16 UTC
Bokeh version: 2.0.0

For some reasons, I want do the manipulation on the glyph renderer at JS side, and the manipulation is triggered from the js_on_change('data', js_callback) event of the CDS that binds to this renderer.

Sample code:

```
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource, CustomJS
from bokeh.plotting import figure

cds = ColumnDataSource(dict(x=[1, 2, 3], y=[1, 2, 3]))

fig = figure(sizing_mode='scale_width',
            tools='pan,xwheel_zoom',
           active_scroll='xwheel_zoom')


renderer = fig.line(x='x', y='y', source=cds)
custom_js = CustomJS(args=dict(renderer=renderer),
                     code='''
                    console.log('I can do operation on the renderer')
                    ''')

cds.js_on_change('data', custom_js)
curdoc().add_root(fig)
```
Another example is that there are some indirect dependencies:
```
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource, CustomJS
from bokeh.plotting import figure

cds = ColumnDataSource(dict(x=[1, 2, 3], y=[1, 2, 3]))
another_cds = ColumnDataSource(dict(x=[1, 2, 3], y=[5, 6, 7]))

fig = figure(sizing_mode='scale_width',
            tools='pan,xwheel_zoom',
           active_scroll='xwheel_zoom')


renderer = fig.line(x='x', y='y', source=cds)
fig.line(x='x', y='y', source=another_cds)


cds.js_on_change('data', CustomJS(args=dict(another_cds=another_cds), code=''))

custom_js = CustomJS(args=dict(renderer=renderer),
                     code='''
                    console.log('I can do operation on the renderer')
                    ''')
another_cds.selected.js_on_change('indices', custom_js)
curdoc().add_root(fig)
```
In both cases, the browser throws the following error:
![console](https://user-images.githubusercontent.com/5237288/78866694-7968e780-7a72-11ea-871d-1a45456a13e0.png)

**Comment by bryevdv** [comment] 2020-04-10 01:35
@maeglin89273 Thank you for the detailed issue. This is almost certainly a duplicate of https://github.com/bokeh/bokeh/issues/9218 so I am closing this issue in favor of that one which already has some discussion.

**Closed by bryevdv** 2020-04-10 01:35 UTC
