### ISSUE TITLE
Adding Figure to document using add_root causes BokehJS error

### ISSUE THREAD

**Issue by plubans580** [bokeh/bokeh#3679] opened 2016-01-19 16:37 UTC
To reproduce, launch the server:

`bokeh serve --host localhost:5006`

On the same machine, run the following python script:

    import numpy    
    import bokeh.client
    import bokeh.plotting
    import bokeh.models.widgets
    
    doc = bokeh.plotting.curdoc()
    session = bokeh.client.push_session(doc)
    
    checkboxes = bokeh.models.widgets.CheckboxButtonGroup(labels = ["one"])
    
    layout = bokeh.models.widgets.VBoxForm(children = [checkboxes])
    doc.add_root(layout)
    
    class Updater(object):
        
        def __init__(self):
            self.__plot = None
            
        def __call__(self, *args, **kwargs):
            if self.__plot is not None:
                doc.remove_root(self.__plot)
            self.__plot = bokeh.plotting.Figure()
            self.__plot.line(x = range(4), y = numpy.random.randn(4))
            doc.add_root(self.__plot)
    
    update = Updater()
    checkboxes.on_click(update)
    
    session.loop_until_closed()

Once both are running, open a web browser on the same machine and go to http://localhost:5006/?bokeh-session-id=<session-id>, where <session-id> is the UID printed in the bokeh server log.  The browser will display a single button, and when you click on it, you'll get the following message in the browser console, where <ref-id> is the hex UID for the model:

    "Got an event for unknown model " Object { subtype: "Figure", type: "Plot", id: "<ref-id>" }

You also get the error "Bokeh: Error handling message" with a stack trace (this is from firefox):

    "Bokeh: Error handling message " bokeh.min.js:63:12556
    Bokeh</<.jsnlog</</k</n.prototype.cerror() bokeh.min.js:63
    Bokeh</<.jsnlog</</k</n.prototype.sendLogItemsConsole() bokeh.min.js:63
    Bokeh</<.jsnlog</</w</i.prototype.sendBatch() bokeh.min.js:63
    Bokeh</<.jsnlog</</w</i.prototype.log() bokeh.min.js:63
    Bokeh</<.jsnlog</</j</t.prototype.log() bokeh.min.js:63
    Bokeh</<.jsnlog</</j</t.prototype.error() bokeh.min.js:63
    Bokeh</<["common/client"]</r</t.prototype._on_message() bokeh.min.js:2
    Bokeh</<["common/client"]</r</t.prototype.connect/</</t.socket.onmessage() bokeh.min.js:1  

If you then reload the page, you will see the plot displayed correctly under the button.  If you click the button again, the same thing happens: the plot doesn't update, you get a similar log-message/stack-trace in the browser console, and once you reload a second time, you see the new plot.

This is on Bokeh 0.11.0.

Thanks,

Peter

**Comment by birdsarah** [comment] 2016-01-21 23:16
Thanks for the report.

What happens if you don't wrap the checkboxes in a VBoxForm?

ping @havocp @bryevdv - any thoughts?

**Comment by birdsarah** [comment] 2016-01-21 23:17
fwiw @plubans580 you may get more help by starting out posting this question to the mailing list and seeing if someone has any ideas there. The mailing list reaches a much wider audience: https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Comment by plubans580** [comment] 2016-01-21 23:55
I get the same error (and no plot) if I do doc.add_root(checkboxes) instead. 

And thanks for the tip.

**Comment by havocp** [comment] 2016-01-22 00:39
I think this is probably a bug in bokeh, fwiw. Needs investigation.

**Comment by bryevdv** [comment] 2016-06-21 04:43
The above code, lightly updated, works in master:
```
import numpy
import bokeh.client
import bokeh.plotting
import bokeh.models.widgets

doc = bokeh.plotting.curdoc()
session = bokeh.client.push_session(doc)

checkboxes = bokeh.models.widgets.CheckboxButtonGroup(labels = ["one"])

layout = bokeh.models.layouts.VBoxForm(children = [checkboxes])
doc.add_root(layout)

class Updater(object):

    def __init__(self):
        self.__plot = None

    def __call__(self, *args, **kwargs):
        if self.__plot is not None:
            doc.remove_root(self.__plot)
        self.__plot = bokeh.plotting.Figure()
        self.__plot.line(x = range(4), y = numpy.random.randn(4))
        doc.add_root(self.__plot)

update = Updater()
checkboxes.on_click(update)
session.show()
session.loop_until_closed()
```

**Comment by bryevdv** [comment] 2016-06-21 04:44
Also I think this was a dupe of #3546

**Closed by bryevdv** 2016-06-21 04:43 UTC
Labels: type: discussion
