### ISSUE TITLE
[BUG] y_range updates inconsistently when data is also updated

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#11980] opened 2022-01-26 17:56 UTC
### Software versions

Python version      :  3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  2.4.2

### Expected behavior

Updating y_range.start should render a plot as one would expect.

### Observed behavior

In my example code I have a bar plot that is updated with new data while the y_range start is also adjusted. However the y_range resets with every second update.
1. Button click: data updates, y_range updates
2. Button click: data updates, y_range resets to default
3. Button click: data updates, y_range updates
4. Button click: data updates, y_range resets to default
5. ...

### Example code

```Python
import numpy as np

from bokeh.layouts import row, column
from bokeh.models import Button, ColumnDataSource, CDSView, DataTable, IndexFilter, TableColumn
from bokeh.plotting import curdoc, figure

fruits = ['Apples', 'Pears', 'Nectarines', 'Plums', 'Grapes', 'Strawberries']
years = ["2015", "2016", "2017"]
colors = ["#c9d9d3", "#718dbf", "#e84d60"]

data = {'fruits' : fruits,
        '2015'   : [2, 1, 4, 3, 2, 4],
        '2016'   : [5, 3, 4, 2, 4, 6],
        '2017'   : [3, 2, 4, 4, 5, 3]}

data2= {'fruits' : fruits,
        '2015'   : np.random.rand(6),
        '2016'   : np.random.rand(6),
        '2017'   : np.random.rand(6),
        }

cds = ColumnDataSource(data)

p = figure(x_range=fruits, height=250, title="Fruit counts by year", toolbar_location=None, tools="")

p.vbar_stack(years, x='fruits', width=0.9, color=colors, source=cds,
             legend_label=years)

p.y_range.start = 0
p.x_range.range_padding = 0.1
p.xgrid.grid_line_color = None
p.axis.minor_tick_line_color = None
p.outline_line_color = None
p.legend.location = "top_left"
p.legend.orientation = "horizontal"


def update_range_and_data():
    #update data + y_range
    cds.data = data2
    p.y_range.start = 1

button = Button(label="update_data")
button.on_click(update_range_and_data)

curdoc().add_root(row(p, button))
```

**Comment by bryevdv** [comment] 2022-01-26 19:45
This is a dupe of https://github.com/bokeh/bokeh/issues/7281

**Closed by bryevdv** 2022-01-26 19:45 UTC
Labels: TRIAGE
