### ISSUE TITLE
Feature request: Embedding plot by sending json instead of preformed javascript

### ISSUE THREAD

**Issue by hatsy** [bokeh/bokeh#6165] opened 2017-04-19 20:03 UTC
The current way of generating an embedded plot is to generate javascript code on the backend (for example using `embed.components`) and send that code to the frontend where it gets evaluated. We would rather send json objects (eg `docs_json` and `render_items`) and generate the js on the frontend. 
This would require changing the backend to expose the necessary json formatted data and changing bokehjs to handle plotting given json data. 

Here's an example of a current workaround: https://github.com/cesium-ml/cesium_web/pull/185/files#diff-599367a9c9f8640f2003c4e8adf1d15bR45

**Comment by hatsy** [comment] 2017-04-19 20:04
@bryevdv I was thinking to add a keyword argument to embed.components to return the raw docs_json and render_items and add a function in bokehjs with a signature similar to function bokeh_render_plot(node, docs_json, render_items) which is equivalent of the static javascript code currently generated by embed.components.

**Comment by bryevdv** [comment] 2017-05-01 17:23
@hatsy I am pretty slammed with travel and other obligations the next few weeks but if you wanted to submit a PR I'd be happy to help you iterate on it / answer questions. My only comment is that if we are going to make essentially the same function in BokehJS, then it would be best to just *move* the function there and have python Bokeh generate JS code that use it (rather than maintain similar functions in two places)

**Comment by cLupus** [comment] 2018-07-20 16:18
Is this still relevant?
I've come in a similar situation, where the plot is made in Python, and should be passed along to a client, as JSON, and then show the plot by using BokehJS.

Thus far, that was been *much* easier said than done.

**Comment by bryevdv** [comment] 2018-07-20 16:49
This has only been requested by a handful of people over the years, so it has not become a priority, given how many other important tasks are outstanding. As I said I'm happy help anyone work up a PR. If you just want the `docs_json` you can get that from `standalone_docs_json_and_render_items`. You'd need to re-recreate all the JS code to load that `docs_json` and render it into a div, but I guess that's actually what you are asking for.

**Comment by bryevdv** [comment] 2018-09-21 04:50
This is a dupe of https://github.com/bokeh/bokeh/issues/5231 which I am working on presently.

**Closed by bryevdv** 2018-09-21 04:50 UTC
Labels: tag: component: bokehjs, type: feature
