### ISSUE TITLE
interactive legend & stacked barplot

### ISSUE THREAD

**Issue by Dr-Nuke** [bokeh/bokeh#9853] opened 2020-03-29 20:44 UTC
When using interactive legend together with stacked barplots, make the bars bottom-adjusted, i.e. fill gaps if some bars get hidden.
The Image shows the counter-example: bars keep levitating, and the sum of the bars is a misleading value.
![image](https://user-images.githubusercontent.com/56429408/77860315-d7920100-720e-11ea-8091-33dfc90f5d09.png)

**Comment by bryevdv** [comment] 2020-03-29 20:47
This is a dupe of https://github.com/bokeh/bokeh/issues/9774

**Closed by bryevdv** 2020-03-29 20:47 UTC
Labels: TRIAGE

**Comment by bryevdv** [comment] 2020-03-29 20:50
@Dr-Nuke If you'd like to add the image and a minimal complete test script to the other linked issue it would certainly be helpful
