### ISSUE TITLE
Allow the configuration of language used by the tooltip number formatter

### ISSUE THREAD

**Issue by andresmrm** [bokeh/bokeh#7903] opened 2018-05-14 18:30 UTC
I couldn't find a way to configure the language use by the tooltip (HoverTool) number formatter.
Found nothing about it at the docs:
https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#formatting-tooltip-fields
And asked this question on the list, which is still unanswered:
https://groups.google.com/a/continuum.io/forum/#!searchin/bokeh/language$20tooltip$20format/bokeh/BlCQEjbJPIo/NgU4N9rcBgAJ
So it seems this isn't possible for now, right?

But Numbro do support languages:
http://numbrojs.com/languages.html

I need this feature to use different thousands and decimal separators. For now the only work around I can find is doing the formatting myself in the data, using Python.

Is this right? Am I missing something?

Thanks in advance.

**Comment by bryevdv** [comment] 2018-05-14 18:47
This is a dupe of https://github.com/bokeh/bokeh/issues/7477

Just bundling all the languages all the time is not an option, it will bloat `bokeh.js` hugely. A solution to just include what is needed, when it is needed, would be appropriate, but we are very under-resourced. If you have the ability to help your contribution would be appreciated.

**Closed by bryevdv** 2018-05-14 18:47 UTC

**Comment by bryevdv** [comment] 2018-05-14 22:01
For me it would be ok to manually add the link to the Numbro language file

@andresmrm in that case I would suggest looking at the `CustomJSHover` that was just added in `0.12.16` that should allow you to have complete control over how fields are formatted
