### ISSUE TITLE
CSS/HTML issues with grid plots

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#1964] opened 2015-02-23 18:06 UTC
**Note**: I encountered this behavior most recently in *plotting/notebook/linked_brushing.ipynb* running Python 3, with Chrome as the browser.  I have seen this behavior in other grid plots .py files, as well.  **I have not yet found a way to consistently reproduce this; reloading the notebook or .py file often solves the problem.**

When clicking the preview widget in many grid plots, the previews appear as two stacked frames, rather than popup window (see below).

![screen shot 2015-02-23 at 11 58 02 am](https://cloud.githubusercontent.com/assets/1417520/6333611/191b26e6-bb54-11e4-81f2-8ce0f813c94c.png)

When clicking **close** or the **x**, rather than going away, a small, empty frame remains at the bottom of the screen.

![screen shot 2015-02-23 at 11 48 47 am](https://cloud.githubusercontent.com/assets/1417520/6333617/305d4a00-bb54-11e4-9fbc-4e2d93a1d3ac.png)

Additionally, the widget buttons display much larger than normal, as well (see above).

**Comment by damianavila** [comment] 2015-02-23 18:33
I think I can have an idea about this... I think the problem comes from loading bokehjs multiple times... I did not see it for a while, but I will investigate...

**Comment by bryevdv** [comment] 2015-03-07 02:59
Now believe this is a dupe of #2024

**Closed by bryevdv** 2015-03-07 02:59 UTC
Labels: type: bug
