### ISSUE TITLE
Misaligned columns when displaying a single DataTable in ipython notebook

### ISSUE THREAD

**Issue by troianow** [bokeh/bokeh#2717] opened 2015-08-13 20:06 UTC
When running the first half of the bokeh/examples/glyphs/data_tables.py example, i.e.up to 
`data_table = DataTable(source=source, columns=columns, editable=True)`
and plot with:
`plotting.show(data_table)`
the result has misligned column headers:
![image](https://cloud.githubusercontent.com/assets/1373343/9260220/70f80454-41d4-11e5-84ea-cfac980fc5bb.png)

If, on the other hand, I use:
`plotting.show(vplot(data_table))`
It displays the table correctly: 
![image](https://cloud.githubusercontent.com/assets/1373343/9260261/b007f8de-41d4-11e5-8db6-bc67b51fc972.png)

It behaves that way on firefox 40 and chrome 44 on Windows 7.

Is that the intended behavior?

Thanks

**Comment by birdsarah** [comment] 2016-09-08 20:41
duplicate of #4680

very succinct description though - so copying @troianow's description into the original issue

**Closed** 2016-09-08 20:41 UTC
Labels: reso: duplicate, type: discussion

**Comment by birdsarah** [comment] 2016-09-08 20:43
I realize that this issue is older - which is interesting because it makes me realize that this has been a problem for a while - but the other issue got more traction.
