### ISSUE TITLE
Bokeh Graph not showing in Jupyter Notebooks

### ISSUE THREAD

**Issue by woodrujm** [bokeh/bokeh#7700] opened 2018-03-26 21:25 UTC
I have the following code: 

```
import matplotlib as mpl

import bokeh.plotting as bpl
import bokeh.models as bmo

from bokeh.models import CategoricalColorMapper, ContinuousColorMapper





TOOLS="hover,crosshair,pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,"
    
def graph_bokeh(algorithm,coordinate_df,metric):

    
    source = bpl.ColumnDataSource(coordinate_df)

    if metric != 'LengthOfStayDaysNBR':
        color_mapper = CategoricalColorMapper(palette=['red','grey'])#,factors = metric)
    else:
        color_mapper = ContinuousColorMapper(palette='Magma256', low=min(coordinate_df[metric]), high=max(coordinate_df[metric]))

    
    bokeh_graph = figure(width=250, height = 250, title = '{}'.format(str(algorithm)[:3]),tools=TOOLS)
    
    bokeh_graph.scatter('x-{}'.format(str(algorithm)[:3]),'y-{}'.format(str(algorithm)[:3])\
                        ,color={'field': metric,'transform': color_mapper}\
                        , legend = metric, source = source)
    

    s2 = ColumnDataSource(data=dict(x=[], y=[]))

    source.callback = CustomJS(args=dict(s2=s2), code="""
            var inds = cb_obj.get('selected')['1d'].indices;
            var d1 = cb_obj.get('data');
            console.log(d1)
            var kernel = IPython.notebook.kernel;
            IPython.notebook.kernel.execute("inds = " + inds);
            """
    )
    
    return bokeh_graph,source

bokeh_graph,source = graph_bokeh(LocallyLinearEmbedding(), df_algs,'LengthOfStayDaysNBR')

show(bokeh_graph)
```

note:     output_notebook(resources = bokeh.resources.INLINE) doesnt seem to fix it

**Comment by bryevdv** [comment] 2018-03-26 21:28
@woodrujm you need to provide more information, as requested in the issue template: all relevant system and software versions (bokeh, browser, notebook, python, OS...) as well as check for any browser console error messages.

**Comment by bryevdv** [comment] 2018-03-26 21:29
You also need to provide a *complete* minimal example that reproduces the issue,  so that we can run it for investigation. If we cannot reproduce an issue, it will have to be closed as `norepro` with no further action.

**Comment by woodrujm** [comment] 2018-03-26 21:57
active environment : None
       user config file : U:\.condarc
 populated config files :
          conda version : 4.5.0
    conda-build version : 3.0.27
         python version : 3.6.3.final.0
       base environment : C:\ProgramData\Anaconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/win-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/pro/win-64
                          https://repo.anaconda.com/pkgs/pro/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\jamesw\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\jamesw\AppData\Local\conda\conda\envs
                          C:\ProgramData\Anaconda3\envs
                          U:\.conda\envs
               platform : win-64
             user-agent : conda/4.5.0 requests/2.18.4 CPython/3.6.3 Windows/10 Windows/10.0.14393
          administrator : False
             netrc file : None
           offline mode : False


 packages in environment at C:\ProgramData\Anaconda3:
#
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he6757f0_0
absl-py                   0.1.11                    <pip>
alabaster                 0.7.10           py36hcd07829_0
anaconda                  custom           py36h363777c_0
anaconda-client           1.6.5            py36hd36550c_0
anaconda-navigator        1.6.9            py36hc720852_0
anaconda-project          0.8.0            py36h8b3bf89_0
AnyQt                     0.0.8                     <pip>
asn1crypto                0.22.0           py36h8e79faa_1
astor                     0.6.2                     <pip>
astroid                   1.5.3            py36h9d85297_0
astropy                   2.0.2            py36h06391c4_4
atom                      0.4.0                     <pip>
babel                     2.5.0            py36h35444c1_0
backports                 1.0              py36h81696a8_1
backports.shutil_get_terminal_size 1.0.0            py36h79ab834_2
beautifulsoup4            4.6.0            py36hd4cc5e8_1
bitarray                  0.8.1            py36h6af124b_0
bkcharts                  0.2              py36h7e685f7_0
blaze                     0.11.3           py36h8a29ca5_0
bleach                    2.0.0            py36h0a7e3d6_0
bleach                    1.5.0                     <pip>
bokeh                     0.12.14                  py36_0
boto                      2.48.0           py36h1a776d2_1
bottleneck                1.2.1            py36hd119dfa_0
brewer2mpl                1.4.1                     <pip>
bzip2                     1.0.6            vc14hdec8e7a_1  [vc14]
ca-certificates           2017.08.26           h94faf87_0
cachecontrol              0.12.3           py36hfe50d7b_0
certifi                   2018.1.18                py36_0
cffi                      1.10.0           py36hae3d1b5_1
chardet                   3.0.4            py36h420ce6e_1
click                     6.7              py36hec8c647_0
cloudpickle               0.4.0            py36h639d8dc_0
clyent                    1.2.2            py36hb10d595_1
colorama                  0.3.9            py36h029ae33_0
CommonMark                0.7.5                     <pip>
comtypes                  1.1.2            py36heb9b3d1_0
conda                     4.5.0                    py36_0
conda-build               3.0.27           py36h309a530_0
conda-env                 2.6.0                h36134e3_1
conda-verify              2.0.0            py36h065de53_0
console_shortcut          0.1.1                h6bb2dd7_3
contextlib2               0.5.5            py36he5d52c0_0
cryptography              2.0.3            py36h123decb_1
curl                      7.55.1           vc14hdaba4a4_3  [vc14]
cycler                    0.10.0           py36h009560c_0
cython                    0.26.1           py36h18049ac_0
cytoolz                   0.8.2            py36h547e66e_0
dask                      0.15.3           py36h396fcb9_0
dask-core                 0.15.3           py36hd651449_0
datashape                 0.5.4            py36h5770b85_0
deap                      1.2.2                     <pip>
decorator                 4.1.2            py36he63a57b_0
distlib                   0.2.5            py36h51371be_0
distributed               1.19.1           py36h8504682_0
docutils                  0.14             py36h6012d8f_0
entrypoints               0.2.3            py36hfd66bb0_2
et_xmlfile                1.0.1            py36h3d2d736_0
fastcache                 1.0.2            py36hffdae1b_0
filelock                  2.0.12           py36hd7ddd41_0
flask                     0.12.2           py36h98b5e8f_0
flask-cors                3.0.3            py36h8a3855d_0
freetype                  2.8              vc14h17c9bdf_0  [vc14]
future                    0.16.0                    <pip>
gast                      0.2.0                     <pip>
get_terminal_size         1.0.0                h38e98db_0
gevent                    1.2.2            py36h342a76c_0
ggplot                    0.11.5                    <pip>
glob2                     0.5              py36h11cc1bd_1
greenlet                  0.4.12           py36ha00ad21_0
grpcio                    1.10.0                    <pip>
h5py                      2.7.0            py36hfbe0a52_1
hdf5                      1.10.1           vc14hb361328_0  [vc14]
healthcareai              1.0                       <pip>
heapdict                  1.0.0            py36h21fa5f4_0
html5lib                  0.999999999      py36ha09b1f3_0
html5lib                  0.9999999                 <pip>
icc_rt                    2017.0.4             h97af966_0
icu                       58.2             vc14hc45fdbb_0  [vc14]
idna                      2.6              py36h148d497_1
imageio                   2.2.0            py36had6c2d2_0
imagesize                 0.7.1            py36he29f638_0
imbalanced-learn          0.3.2                     <pip>
intel-openmp              2018.0.0             hcd89f80_7
ipykernel                 4.6.1            py36hbb77b34_0
ipython                   6.1.0            py36h236ecc8_1
ipython_genutils          0.2.0            py36h3c5d0ee_0
ipywidgets                7.0.0            py36h2e74ada_0
isort                     4.2.15           py36h6198cc5_0
itsdangerous              0.24             py36hb6c5a24_1
jdcal                     1.3              py36h64a5255_0
jedi                      0.10.2           py36hed927a0_0
jinja2                    2.9.6            py36h10aa3a0_1
joblib                    0.11                      <pip>
jpeg                      9b               vc14h4d7706e_1  [vc14]
jsonschema                2.6.0            py36h7636477_0
jupyter                   1.0.0            py36h422fd7e_2
jupyter-core              4.4.0                     <pip>
jupyter_client            5.1.0            py36h9902a9a_0
jupyter_console           5.2.0            py36h6d89b47_1
jupyter_core              4.3.0            py36h511e818_0
jupyterlab                0.27.0           py36h34cc53b_2
jupyterlab_launcher       0.4.0            py36h22c3ccf_0
Keras                     2.1.5                     <pip>
keyring                   12.0.0                    <pip>
keyrings.alt              3.0                       <pip>
lazy-object-proxy         1.3.1            py36hd1c21d2_0
libiconv                  1.15             vc14h29686d3_5  [vc14]
libpng                    1.6.32           vc14h5163883_3  [vc14]
libssh2                   1.8.0            vc14hcf584a9_2  [vc14]
libtiff                   4.0.8           vc14h04e2a1e_10  [vc14]
libxgboost                0.60                 h1133f5d_0
libxml2                   2.9.4            vc14h8fd0f11_5  [vc14]
libxslt                   1.1.29           vc14hf85b8d4_5  [vc14]
llvmlite                  0.20.0                   py36_0
locket                    0.2.0            py36hfed976d_1
lockfile                  0.12.2           py36h0468280_0
lxml                      4.1.0            py36h0dcd83c_0
lzo                       2.10             vc14h0a64fa6_1  [vc14]
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
Markdown                  2.6.11                    <pip>
markupsafe                1.0              py36h0e26971_1
matplotlib                2.1.0            py36h11b4b9c_0
mccabe                    0.6.1            py36hb41005a_1
menuinst                  1.4.10           py36h42196fb_0
mistune                   0.7.4            py36h4874169_0
mkl                       2018.0.0             h36b65af_4
mkl-service               1.1.2            py36h57e144c_4
mpld3                     0.3                       <pip>
mpmath                    0.19             py36he326802_2
msgpack-python            0.4.8            py36h58b1e9d_0
msys2-conda-epoch         20160418                      1
multipledispatch          0.4.9            py36he44c36e_0
navigator-updater         0.1.0            py36h8a7b86b_0
nbconvert                 5.3.1            py36h8dc0fde_0
nbformat                  4.4.0            py36h3a5bc1b_0
networkx                  2.0              py36hff991e3_0
nltk                      3.2.4            py36hd0e0a39_0
nose                      1.3.7            py36h1c3779e_2
notebook                  5.0.0            py36hd9fbf6f_2
numba                     0.35.0              np112py36_0
numexpr                   2.6.2            py36h7ca04dc_1
numpy                     1.14.1                    <pip>
numpy                     1.12.1           py36hf30b8aa_1
numpydoc                  0.7.0            py36ha25429e_0
odo                       0.5.1            py36h7560279_0
olefile                   0.44             py36h0a7bdd2_0
openpyxl                  2.4.8            py36hf3b77f6_1
openssl                   1.0.2n               h74b6da3_0
Orange3                   3.11.0                    <pip>
packaging                 16.8             py36ha0986f6_1
pandas                    0.20.3           py36hce827b7_2
pandas-profiling          1.4.0                     <pip>
pandoc                    1.19.2.1             hb2460c7_1
pandocfilters             1.4.2            py36h3ef6317_1
partd                     0.3.8            py36hc8e763b_0
path.py                   10.3.1           py36h3dd8b46_0
pathlib2                  2.3.0            py36h7bfb78b_0
patsy                     0.4.1            py36h42cefec_0
pep8                      1.7.0            py36h0f3d67a_0
pickleshare               0.7.4            py36h9de030f_0
pillow                    4.2.1            py36hdb25ab2_0
pip                       9.0.1                    py36_5
pkginfo                   1.4.1            py36hb0f9cfa_1
plotly                    2.5.0                     <pip>
ply                       3.10             py36h1211beb_0
progress                  1.3              py36hbeca8d3_0
prompt_toolkit            1.0.15           py36h60b8f86_0
protobuf                  3.5.2                     <pip>
psutil                    5.4.0            py36h4e662fb_0
py                        1.4.34           py36ha4aca3a_1
py-xgboost                0.60            py36np112h982e225_0    anaconda
pycodestyle               2.3.1            py36h7cc55cd_0
pycosat                   0.6.3            py36h413d8a4_0
pycparser                 2.18             py36hd053e01_1
pycrypto                  2.6.1            py36he68e6e2_1
pycurl                    7.43.0           py36h086bf4c_3
pyflakes                  1.6.0            py36h0b975d6_0
pygal                     2.4.0                     <pip>
pygments                  2.2.0            py36hb010967_0
pylint                    1.7.4            py36ha4e6ded_0
pyodbc                    4.0.17           py36h0006bc2_0
pyopenssl                 17.2.0           py36h15ca2fc_0
pyparsing                 2.2.0            py36h785a196_1
pyqt                      5.6.0            py36hb5ed885_5
pyqtgraph                 0.10.0                    <pip>
pysocks                   1.6.7            py36h698d350_1
pytables                  3.4.2            py36h71138e3_2
pytest                    3.2.1            py36h753b05e_1
python                    3.6.3                h9e2ca53_1
python-dateutil           2.6.1            py36h509ddcb_1
pytz                      2017.2           py36h05d413f_1
pywavelets                0.5.2            py36hc649158_0
pywin32                   221              py36h9c10281_0
pywin32-ctypes            0.1.2                     <pip>
pywinpty                  0.5.1                     <pip>
pyyaml                    3.12             py36h1d1928f_1
pyzmq                     16.0.2           py36h38c27d9_2
qt                        5.6.2           vc14h6f8c307_12  [vc14]
qtawesome                 0.4.4            py36h5aa48f6_0
qtconsole                 4.3.1            py36h99a29a9_0
qtpy                      1.3.1            py36hb8717c5_0
requests                  2.18.4           py36h4371aae_1
rope                      0.10.5           py36hcaf5641_0
ruamel_yaml               0.11.14          py36h9b16331_2
scikit-image              0.13.0           py36h6dffa3f_1
scikit-learn              0.19.1           py36h53aea1b_0
scipy                     0.19.1           py36h7565378_3
seaborn                   0.8.0            py36h62cb67c_0
Send2Trash                1.4.2                     <pip>
serverfiles               0.2.1                     <pip>
setuptools                36.5.0           py36h65f9e6e_0
setuptools                38.5.2                    <pip>
simplegeneric             0.8.1            py36heab741f_0
singledispatch            3.4.0.3          py36h17d0c80_0
sip                       4.18.1           py36h9c25514_2
six                       1.11.0           py36h4db2310_1
sklearn                   0.0                       <pip>
snowballstemmer           1.2.1            py36h763602f_0
sortedcollections         0.5.3            py36hbefa0ab_0
sortedcontainers          1.5.7            py36ha90ac20_0
sphinx                    1.6.3            py36h9bb690b_0
sphinxcontrib             1.0              py36hbbac3d2_1
sphinxcontrib-websupport  1.0.1            py36hb5e5916_1
spyder                    3.2.4            py36h8845eaa_0
sqlalchemy                1.1.13           py36h5948d12_0
sqlite                    3.20.1           vc14h7ce8c62_1  [vc14]
statsmodels               0.8.0            py36h6189b4c_0
stopit                    1.1.2                     <pip>
sympy                     1.1.1            py36h96708e0_0
tblib                     1.3.2            py36h30f5020_0
tensorboard               1.6.0                     <pip>
tensorflow                1.6.0                     <pip>
termcolor                 1.1.0                     <pip>
terminado                 0.8.1                     <pip>
testpath                  0.3.1            py36h2698cfe_0
tk                        8.6.7            vc14hb68737d_1  [vc14]
toolz                     0.8.2            py36he152a52_0
tornado                   4.5.2            py36h57f6048_0
TPOT                      0.9.2                     <pip>
tqdm                      4.19.6                    <pip>
traitlets                 4.3.2            py36h096827d_0
typing                    3.6.2            py36hb035bda_0
unicodecsv                0.14.1           py36h6450c06_0
update-checker            0.16                      <pip>
urllib3                   1.22             py36h276f60a_0
vc                        14                   h2379b0c_2
vs2015_runtime            14.0.25123           hd4c4e62_2
wcwidth                   0.1.7            py36h3d5aa90_0
webencodings              0.5.1            py36h67c50ae_1
werkzeug                  0.12.2           py36h866a736_0
Werkzeug                  0.14.1                    <pip>
wheel                     0.30.0                    <pip>
wheel                     0.29.0           py36h6ce6cde_1
widgetsnbextension        3.0.2            py36h364476f_1
win_inet_pton             1.0.1            py36he67d7fd_1
win_unicode_console       0.5              py36hcdbd4b5_0
wincertstore              0.2              py36h7fe50ca_0
wrapt                     1.10.11          py36he5f5981_0
xlrd                      1.1.0            py36h1cb58dc_1
xlsxwriter                1.0.2            py36hf723b7d_0
xlwings                   0.11.4           py36hd3cf94d_0
xlwt                      1.3.0            py36h1a4751e_0
yaml                      0.1.7            vc14hb31d195_1  [vc14]
zict                      0.1.3            py36h2d8e73e_0
zlib                      1.2.11           vc14h1cdd9ab_1  [vc14]


            import matplotlib as mpl

            import bokeh.plotting as bpl
            import bokeh.models as bmo


            from bokeh.models import CategoricalColorMapper, ContinuousColorMapper





            
  
  
  
  
  
  TOOLS="hover,crosshair,pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,"
    
            def graph_bokeh(algorithm,coordinate_df,metric):

    
                source = bpl.ColumnDataSource(coordinate_df)

                if metric != 'LengthOfStayDaysNBR':
                    color_mapper = CategoricalColorMapper(palette=['red','grey'])#,factors = metric)
                else:
                    color_mapper = ContinuousColorMapper(palette='Magma256', low=min(coordinate_df[metric]), high=max(coordinate_df[metric]))

    



                bokeh_graph = figure(width=250, height = 250, title = '{}'.format(str(algorithm)[:3]),tools=TOOLS)
    
                bokeh_graph.scatter('x-{}'.format(str(algorithm)[:3]),'y-{}'.format(str(algorithm)[:3])\
                                    ,color={'field': metric,'transform': color_mapper}\
                                    , legend = metric, source = source)
    

                s2 = ColumnDataSource(data=dict(x=[], y=[]))

                source.callback = CustomJS(args=dict(s2=s2), code="""
                        var inds = cb_obj.get('selected')['1d'].indices;
                        var d1 = cb_obj.get('data');
                        console.log(d1)
                        var kernel = IPython.notebook.kernel;
                        IPython.notebook.kernel.execute("inds = " + inds);
                        """
                )
    
                return bokeh_graph,source



            bokeh_graph,source = graph_bokeh(LocallyLinearEmbedding(), df_algs,metric)
            show(bokeh_graph)

metric = 'test'
algorithm = LocallyLinearEmbedding()
test_df = pd.DataFrame({'x-{}'.format(str(algorithm)[:3]):np.random.rand(318),'y-{}'.format(str(algorithm)[:3]):np.random.rand(318),metric:np.random.rand(318)})
bokeh_graph,source = graph_bokeh(algorithm, test_df,metric)
show(bokeh_graph)



I think that should be enough to reproduce. let me know if missing anything

**Comment by bryevdv** [comment] 2018-03-26 22:02
What is `LocallyLinearEmbedding`?

**Comment by woodrujm** [comment] 2018-03-26 22:04
ah sorry - algorithm = 'Loc' should be good

**Comment by bryevdv** [comment] 2018-03-26 22:09
After trying to fix the indenting, then changing to `loc` I get `NameError: name 'df_algs' is not defined` Could you put an actual notebook up on GH or a gist, etc?

**Comment by woodrujm** [comment] 2018-03-26 22:16
# Clustering/dimensionalirty reduction libraries
            from sklearn.manifold import *
            from sklearn.cluster import *
            from sklearn.decomposition import *

            # Graphing libraries
            from ggplot import *
            import matplotlib.pyplot as plt
            import plotly.plotly as py
            from mpl_toolkits.mplot3d import Axes3D
            import pygal
            import seaborn as sns
            import bokeh
            from bokeh.plotting import figure
            from bokeh.layouts import gridplot
            from bokeh.io import output_file, show
            from bokeh.models import HoverTool
            from bokeh.layouts import row
            from bokeh.models import CustomJS, ColumnDataSource
            from bokeh.plotting import figure, output_file, show

            from bokeh.io import output_notebook
            import matplotlib as mpl

            import bokeh.plotting as bpl
            import bokeh.models as bmo

            from bokeh.models import CategoricalColorMapper, ContinuousColorMapper

            # other
            from time import time
            import random
            import numpy as np
            import pandas as pd
            from sklearn.preprocessing import StandardScaler
            import itertools

            output_notebook(resources = bokeh.resources.INLINE)





            TOOLS="hover,crosshair,pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,"
                
            def graph_bokeh(algorithm,coordinate_df,metric):

                
                source = bpl.ColumnDataSource(coordinate_df)

                if metric != 'LengthOfStayDaysNBR':
                    color_mapper = CategoricalColorMapper(palette=['red','grey'])#,factors = metric)
                else:
                    color_mapper = ContinuousColorMapper(palette='Magma256', low=min(coordinate_df[metric]), high=max(coordinate_df[metric]))

                



                bokeh_graph = figure(width=250, height = 250, title = '{}'.format(str(algorithm)[:3]),tools=TOOLS)
                
                bokeh_graph.scatter('x-{}'.format(str(algorithm)[:3]),'y-{}'.format(str(algorithm)[:3])\
                                    ,color={'field': metric,'transform': color_mapper}\
                                    , legend = metric, source = source)
                

                s2 = ColumnDataSource(data=dict(x=[], y=[]))

                source.callback = CustomJS(args=dict(s2=s2), code="""
                        var inds = cb_obj.get('selected')['1d'].indices;
                        var d1 = cb_obj.get('data');
                        console.log(d1)
                        var kernel = IPython.notebook.kernel;
                        IPython.notebook.kernel.execute("inds = " + inds);
                        """
                )
                
                return bokeh_graph,source

            metric = 'test'
            algorithm = 'Loc'
            test_df = pd.DataFrame({'x-{}'.format(str(algorithm)[:3]):np.random.rand(318),'y-{}'.format(str(algorithm)[:3]):np.random.rand(318),metric:np.random.rand(318)})
            bokeh_graph,source = graph_bokeh(algorithm, test_df,metric)
            show(bokeh_graph)

**Comment by woodrujm** [comment] 2018-03-26 22:18
Thanks in advance for the help. The above code reproduces the error on my end

**Comment by woodrujm** [comment] 2018-03-26 22:26
![image](https://user-images.githubusercontent.com/25488611/37936348-6f2d06d0-3112-11e8-896d-3abf49666a44.png)

I'm seeing this error in the chrome developer console

**Comment by mattpap** [comment] 2018-03-26 22:45
This needs to be tested with 0.12.15-dev7. This was likely fixed by one of recent TS PRs.

**Comment by woodrujm** [comment] 2018-03-26 22:51
I have tested a few different options. Things seem to render without the color parameter. I have a feeling the issue comes up here. Do we know of a way to 1) color categorical data and 2) color continuous data that works in jupyter notebook?

**Comment by woodrujm** [comment] 2018-03-26 22:53
i.e. 

                # Clustering/dimensionalirty reduction libraries
                from sklearn.manifold import *
                from sklearn.cluster import *
                from sklearn.decomposition import *

                # Graphing libraries
                from ggplot import *
                import matplotlib.pyplot as plt
                import plotly.plotly as py
                from mpl_toolkits.mplot3d import Axes3D
                import pygal
                import seaborn as sns
                import bokeh
                from bokeh.plotting import figure
                from bokeh.layouts import gridplot
                from bokeh.io import output_file, show
                from bokeh.models import HoverTool
                from bokeh.layouts import row
                from bokeh.models import CustomJS, ColumnDataSource
                from bokeh.plotting import figure, output_file, show

                from bokeh.io import output_notebook
                import matplotlib as mpl

                import bokeh.plotting as bpl
                import bokeh.models as bmo

                from bokeh.models import CategoricalColorMapper, ContinuousColorMapper

                # other
                from time import time
                import random
                import numpy as np
                import pandas as pd
                from sklearn.preprocessing import StandardScaler
                import itertools

                output_notebook(resources = bokeh.resources.INLINE)





                TOOLS="hover,crosshair,pan,wheel_zoom,zoom_in,zoom_out,box_zoom,undo,redo,reset,tap,save,box_select,poly_select,lasso_select,"
                    
                def graph_bokeh(algorithm,coordinate_df,metric):

                    
                    source = bpl.ColumnDataSource(coordinate_df)

        #             if metric != 'LengthOfStayDaysNBR':
        #                 color_mapper = CategoricalColorMapper(palette=['red','grey'])#,factors = metric)
        #             else:
        #                 color_mapper = ContinuousColorMapper(palette='Magma256', low=min(coordinate_df[metric]), high=max(coordinate_df[metric]))

                    



                    bokeh_graph = figure(width=600, height = 600, title = '{}'.format(str(algorithm)[:3]),tools=TOOLS)
                    
                    bokeh_graph.scatter('x-{}'.format(str(algorithm)[:3]),'y-{}'.format(str(algorithm)[:3])\
                                      # ,color={'field': metric,'transform': color_mapper}\
                                        , source = source)
                    

                    s2 = ColumnDataSource(data=dict(x=[], y=[]))

                    source.callback = CustomJS(args=dict(s2=s2), code="""
                            var inds = cb_obj.get('selected')['1d'].indices;
                            var d1 = cb_obj.get('data');
                            console.log(d1)
                            var kernel = IPython.notebook.kernel;
                            IPython.notebook.kernel.execute("inds = " + inds);
                            """
                    )
                    
                    return bokeh_graph,source

                metric = 'test'
                algorithm = 'Loc'
                test_df = pd.DataFrame({'x-{}'.format(str(algorithm)[:3]):np.random.rand(318),'y-{}'.format(str(algorithm)[:3]):np.random.rand(318),metric:np.random.rand(318)})
                bokeh_graph,source = graph_bokeh(algorithm, test_df,metric)
                show(bokeh_graph)


Seems to work

**Comment by bryevdv** [comment] 2018-03-26 23:00
My apologies, but we  need to take this to the mailing list or SO. When I saw "graph" I thought you meant network/node/edge graph, which is fairly new and I could have imagined had a bug. But this is a usage questions, so not appropriate or GH. 

You can see examples of using `factor_cmap` and `linear_cmap` (newer and simpler ways to colormap than creating colormap models by hand) in the live tutorial: 

https://mybinder.org/v2/gh/bokeh/bokeh-notebooks/master?filepath=tutorial%2F00%20-%20Introduction%20and%20Setup.ipynb

**Closed by bryevdv** 2018-03-26 23:01 UTC

**Comment by bryevdv** [comment] 2018-03-26 23:03
@mattpap as best I can tell the issue is that @woodrujm is configuring a categorical color mapper on continuous data (see the `if` on metric name)

**Comment by woodrujm** [comment] 2018-03-26 23:05
there are three metrics used - two binary categorical (not length of stay) and length of stay (continuous)

**Comment by bryevdv** [comment] 2018-03-26 23:17
@woodrujm categorical data in Bokeh is always represented by string names, perhaps that's an issue. Again we should take this to the ML for now, and if an actual issue is determined we can put that here.

**Comment by bryevdv** [comment] 2018-03-26 23:22
regarding a working example, e.g.:

<img width="618" alt="screen shot 2018-03-26 at 16 21 41" src="https://user-images.githubusercontent.com/1078448/37938181-cec3b7f2-3111-11e8-9984-b16b1e5b9f82.png">

**Comment by woodrujm** [comment] 2018-03-27 01:41
Thanks! I appreciate the effort. I got the colors working using linear_cmap and factor_cmap. Unfortunately the whole purpose was to create a interactive graph that returns the x/y coordinates of the selected data (using lasso), which doesnt seem to be working. If you could help that would be amazing (FYI I had it working before, but it seems to not return anything now.) :


        import pandas as pd
        import numpy as np
        import matplotlib as mpl
        from bokeh.transform import factor_cmap, linear_cmap
        from bokeh.palettes import Spectral6
        from bokeh.plotting import figure, output_file, show
        from bokeh.models import CustomJS, ColumnDataSource
        from bokeh.io import output_notebook

        import bokeh.plotting as bpl
        import bokeh.models as bmo
        from bokeh.models.tools import *

        output_notebook()

        algorithm = 'Loc'
        metric = 'LengthOfStayDaysNBR'
        coordinate_df = pd.DataFrame({'x-{}'.format(str(algorithm)[:3]):np.random.rand(500)\
                                      ,'y-{}'.format(str(algorithm)[:3]):np.random.rand(500)\
                                     ,metric:np.random.rand(500)})


        TOOLS="pan,wheel_zoom,reset,hover,poly_select,lasso_select"


        p = figure(title = '{}'.format(str(algorithm)[:3]),tools=TOOLS)


        source = bpl.ColumnDataSource(coordinate_df)

        if metric == 'LengthOfStayDaysNBR':
            color_mapper = linear_cmap(metric,palette=Spectral6,low=coordinate_df[metric].min(),high=coordinate_df[metric].max())
        else:
            color_mapper = factor_cmap(metric,palette=Spectral6,factors=coordinate_df[metric].unique())



        p1 = figure(width=250, height = 250, title = '{}'.format(str(algorithm)[:3]),tools=TOOLS)

        p1.scatter('x-{}'.format(str(algorithm)[:3]),'y-{}'.format(str(algorithm)[:3]),fill_color= color_mapper, source = source)


        source.callback = CustomJS(args=dict(p1=p1), code="""
                var inds = cb_obj.get('selected')['1d'].indices;
                var d1 = cb_obj.get('data');
                console.log(d1)
                var kernel = IPython.notebook.kernel;
                IPython.notebook.kernel.execute("inds = " + inds);
                """
        )

        show(p1)


        # Run this after selecting
        for x,y in  zip([source.data['x-{}'.format(str(algorithm)[:3])][i] for i in inds],
            [source.data['y-{}'.format(str(algorithm)[:3])][i] for i in inds]):
            print(x,y)

**Comment by woodrujm** [comment] 2018-03-27 01:43
p.s. it is also posted here: https://stackoverflow.com/questions/49502860/return-x-y-coordinates-from-bokeh-graph

**Comment by bryevdv** [comment] 2018-03-27 04:06
I have posted an answer there.
