### ISSUE TITLE
Tooltips in gridplots appear below neighbouring plots (bad z-index)

### ISSUE THREAD

**Issue by cstjean** [bokeh/bokeh#2083] opened 2015-03-18 16:21 UTC
When using a gridplot with tooltips on the individual plots, the tooltips appear below the other plots that are to the right or down from the current plot.
```python
import bokeh.plotting as bop
from bokeh.models import HoverTool
def foo():
    fig = bop.figure(tools='hover')
    fig.select(dict(type=HoverTool)).tooltips = "The quick brown fox jumped over the lazy dog"*25
    fig.scatter([1,2,3],[2,3,2])
    fig.plot_width = 150
    fig.plot_height = 150
    return fig
bop.show(bop.gridplot([[foo() for i in range(2)] for j in range(3)]))
```
eg. the bottom right plot is over the tooltip:
![screen shot 2015-03-18 at 12 17 34](https://cloud.githubusercontent.com/assets/8622776/6713454/cafe03f8-cd68-11e4-9cc8-a831705f5705.png)

This is especially problematic when we have images in the tooltips (which are awesome - thank you for Bokeh!)

I assume that this could be fixed by specifying the z-index. We could do that ourselves if [this commit](https://github.com/johngergely/bokeh/commit/7f522e5375984b50b6d3b83394bc994f212853e4) was merged in.

**Comment by bryevdv** [comment] 2015-03-21 21:52
Marking this as a dupe of https://github.com/bokeh/bokeh/issues/1744

@cstjean there is some additional info in the linked issue. It unfortunately seems to be a little more complicated than just the `z-index` but if you have any suggestions they would be welcomed.

**Closed by bryevdv** 2015-03-21 21:52 UTC
Labels: type: discussion
