### ISSUE TITLE
No math symbols?

### ISSUE THREAD

**Issue by scweiser** [bokeh/bokeh#3649] opened 2016-01-13 19:42 UTC
Hi all,  I'm trying to add a \Delta symbol to my axis, and Matplotlib TeX-based expressions does not seem to work.  Also I didn't find any example figures in the bokeh gallery that included math symbols...  are math symbols not supported, or am I using incorrect text formatting?

**Comment by gregnordin** [comment] 2016-01-13 19:56
Are you using Python 2 or 3? If Python 3, you can use the unicode symbol for \Delta, so your string would be:

"\u0394 and whatever other stuff you want"

If Python 2 it would be:

u"\u0394 and whatever other stuff you want"

I'm using Python 3 and came across this yesterday and found that unicode symbols work fine for the greek letters I needed.

**Comment by bryevdv** [comment] 2016-01-13 20:06
dupe of #647 

As @gregnordin notes, it is possible to use unicode to an extent. There is not currently support for LaTeX. That is a long standing feature request, unfortunately it is decidedly not trivial, and the any implementation strategy would also have unavoidable wider implications on other things as well. You can see the referenced issue above for more information.

**Closed by bryevdv** 2016-01-13 20:06 UTC

**Comment by scweiser** [comment] 2016-01-13 20:37
Ok--thanks for the info!
