### ISSUE TITLE
bokeh.charts.Histogram has some bar layout issues

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#5192] opened 2016-09-19 21:01 UTC
Using latest Chrome on latest OS X with Bokeh 0.12.3dev I observe bar layout issues for the `bokeh.charts.Histogram` object, as observed below.  In some places there is bar overlap, and in other places there are gaps between bars.  Inside of Jupyter.

<img width="1010" alt="screen shot 2016-09-19 at 4 58 48 pm" src="https://cloud.githubusercontent.com/assets/293525/18648865/80950062-7e8a-11e6-99ba-ccde3da446a4.png">

**Comment by bryevdv** [comment] 2016-09-19 21:03
Dupe of #3315

**Closed by bryevdv** 2016-09-19 21:03 UTC
