### ISSUE TITLE
Better documentation is needed for text displayed by the hovertool

### ISSUE THREAD

**Issue by dbk123** [bokeh/bokeh#3518] opened 2016-01-04 13:49 UTC
Formatting of the pop-up tooltips provided by the hovertool needs better documentation.  For example, I found that (@y){int} causes the output to be displayed as an integer, but this is not addressed in the official documentation.  

It would also be nice to provide an complete listing of the known fields that can be called using '$' operator.

Thanks!

**Comment by bryevdv** [comment] 2016-01-27 04:17
ping @mattpap can you point to full information about what formats work? I'd like to write them up.

**Comment by gwenzek** [comment] 2016-03-31 14:50
duplicate of #2595

**Closed** 2017-04-13 22:49 UTC
Labels: reso: duplicate, tag: component: docs, type: task
