### ISSUE TITLE
embed/publishing example not showing the plot after auth, no py neither js error

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2290] opened 2015-05-14 16:21 UTC
When opening publishing.html it works fine but if I try to log to bokeh-server I can see the plot listed in the user objects but cannot open it.

Should be due to 

```
.collapse {
  /* display: none; */
}
```

applied here: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/server/usercontext/wrappertemplate.eco#L9

**Comment by damianavila** [comment] 2015-05-14 19:44
In fact this is the way to see that the plot is already there but collapsed... in previous versions, when you hit the link, the div takes a "auto" height parameter in the style and you see the plot... and that property disappear when you collapse the div... I think the problem is the the collapse itself... 

I found this comment in the source code that could be related:
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/server/usercontext/usercontext.coffee#L40-L51

But that was also commented out in previous versions too, and it works in the latest release.

Searching in the web, I found that sometimes the collapse do not work in jquery is not loaded before... but when I saw this file `usercontext.coffee` I see jquery loaded at the top...

pinging @tswicegood @hhuuggoo, maybe they can give us a hint...

**Comment by tswicegood** [comment] 2015-05-14 21:22
My name being on it is a red herring -- it's there because of the Great Browserification of 2015. :-)

https://github.com/bokeh/bokeh/blame/4e9b9061fe47f57556c4ad98f469d1da7bccc42a/bokehjs/src/coffee/server/usercontext/usercontext.coffee#L45-L56

It looks like @mattpap is responsible for most of that code so maybe he can shed some light.

**Comment by damianavila** [comment] 2015-09-03 21:18
This was also solved by #2792, closing.

**Closed by damianavila** 2015-09-03 21:18 UTC
Labels: type: bug
