### ISSUE TITLE
[FEATURE] Better Handling of Missing or Irrelevant Data Ranges

### ISSUE THREAD

**Issue by sirinath** [bokeh/bokeh#11885] opened 2021-12-11 15:38 UTC
### Problem description

When certain data ranges does have data the charts appear broken. This in some cases might be desirable so that linearity or scaling of the axis are maintained but not in some. So it is possible to add support to these cases.

### Feature description

Want to have the ability to:
- large ranges of missing data (time periods data was not collected)
- systematic missing data (E.g. weekends)
- non systematic missing data (e.g. holidays)

The applied adjustments can be:
- specified by the user of the API
- detected by the library

Possible way to handle:
- Break axis if there more missing data above a threshold by detecting such gaps or specified by the user
- Remove systematic missing data ranges respace distance between data points by specifying such rages
- Remove data range for non systematic short periods of missing data and respace distance between data points detecting such gaps
- Other strategies to handle missing data, respace distance between data points and readjust axis by specifying or detecting

### Potential alternatives

Can use custom axis labels but is more a hack than a solution when dealing with numerical and data based axises as you loose the numerical or date based properties and formatting. Getting the spacing, major, minor ticks, etc. is a challenge as the labels are text.

### Additional information

The solution should be made as simple and straightforward to be used as missing data is something everyone needs to deal with.

**Comment by bryevdv** [comment] 2021-12-12 02:33
This is duplicate of https://github.com/bokeh/bokeh/issues/11593 

I will (re-)state that I think the "day-index" based solution described in #11593 is the only possible avenue for Bokeh, since Bokeh is extremely general-purpose, supports interactive range updates via user interactions, and can have dynamic and streaming data updates. Making broken axes possible with arbitrary continuous scale such that it works correctly with all glyphs, annotations, tools, and data is just not going to be feasible. 

But that's OK, since as far as as I know, no one has actually ever asked for that. This request has *always and only* come in in the context of finance plots. I think a day-index solution can be sufficient for that use case, with some improvements for usability or convenience, e.g. more flexible or automatic formatting. I'd encourage you to share any thoughts you have about specific improvements in [#11953](https://github.com/bokeh/bokeh/issues/11593).

Otherwise, it might be better to look at other tools that specialize in finance plots.

**Closed by bryevdv** 2021-12-12 02:33 UTC
Labels: TRIAGE
