### ISSUE TITLE
BUG: All patches vanish on selection

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#2514] opened 2015-07-06 04:56 UTC
When selecting patches from a plot all the other patches vanish as opposed to dimming as occurred before.

This bug was introduced in a recent change. However, I am not sure exactly where it entered. I know that this commit ( 595bc636daffb4b88a261892a2ed8185079bf57c ) did not have the error, but it does appear in the [0.9.1]( https://github.com/bokeh/bokeh/tree/0.9.1 ) release.

Example of the problem ( http://nbviewer.ipython.org/github/jakirkham/bokeh_examples/blob/master/Bokeh_Example_16.ipynb ).

**Comment by bryevdv** [comment] 2015-07-06 05:52
@birdsarah I think the problem is here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/renderer/glyph/patches.coffee#L76

The args passed should be `sxs` and not `@sxs` I think.

**Comment by jakirkham** [comment] 2015-07-06 12:36
I should add that this is causing the title, axis titles, and tick marks to vanish, as well. Also, clicking on patches (even if you can't see them) still seems to yield a correct result (minus that you can't see the patches, etc.). Clicking off of a patch returns everything to normal.

**Comment by bryevdv** [comment] 2015-07-06 13:22
@damianavila this is a quick fix, what do you think about a dev build Friday or so?

**Comment by damianavila** [comment] 2015-07-06 14:53
>@damianavila this is a quick fix, what do you think about a dev build Friday or so?

Yes, for sure... let's collect all the tiny fixes during the week and I will make a devel build on Friday.

**Comment by bryevdv** [comment] 2015-07-06 16:44
@birdsarah forgot about you schedule, reassigned to @Maggie-M she can make the change today.

**Comment by birdsarah** [comment] 2015-07-06 19:26
@bryevdv @damianavila - I have this test file https://github.com/birdsarah/bokeh-miscellany/blob/master/tests/2376_hover_on_discontinuous_patches.py that I used during development.

(Unfortunately I didn't test after a final "little" code refactor!)

Should we put this, or some version of this, in examples so that it can be manually tested?

**Closed** 2015-07-06 20:40 UTC
Labels: type: bug

**Comment by jakirkham** [comment] 2015-07-06 20:57
Thanks for this fix everyone. Works great.
