### ISSUE TITLE
image update sets data on a client twice

### ISSUE THREAD

**Issue by ivan-usov** [bokeh/bokeh#7079] opened 2017-10-20 08:21 UTC
In the image_blur example (https://github.com/bokeh/bokeh/blob/master/examples/app/image_blur.py) for every image update with a slider the _get_values function of LinearColorMapper is called twice. In fact, the whole stack of GlyphRendererView.set_data is executed twice (see attached image). Clearly, it also affects any other bokeh app with an image being updated through ColumnDataSource, similar to image_blur. Probably, several listeners with overlapping functionality are registered for the image update event. Fixing it could significantly improve an image update performance, unless there is a reason behind this over-execution.

![selection_101](https://user-images.githubusercontent.com/13196195/31811212-05e07630-b57f-11e7-87a6-c0430c8832b2.png)

Observed with:
bokeh/0.12.10
python/3.6.2

Ubuntu 16.04
Firefox 56.0 (64-bit) and Chrome 61.0.3163.100 (Official Build) (64-bit)

**Comment by ivan-usov** [comment] 2017-10-20 09:26
I guess, the oversubscription happens here,
https://github.com/bokeh/bokeh/blob/a60d2eb0776128d0abb82e37cb84339b2f69fa44/bokehjs/src/coffee/models/renderers/glyph_renderer.coffee#L74-L87

 I wonder if an additional 'if-statement' would resolve the issue? Probably, it won't be that easy.

**Comment by bryevdv** [comment] 2017-10-22 18:58
@ivan-usov thanks for the detailed information. I am going to close this as a duplicate of https://github.com/bokeh/bokeh/issues/4967 because it's almost certainly the same root cause. I' not sure the problem is oversubscription -- all of those different situations legitimately imply that a redraw, recompute, etc. need to happen. I think rather it's over eventing, in the sense that if a "more specific" event happens, then the "more general" event should be suppressed. Alternatively, the another idea might be to apply more throttling, which is a bit of a cop-out but also probably simple to do.

**Closed by bryevdv** 2017-10-22 18:58 UTC

**Comment by ivan-usov** [comment] 2017-10-24 09:06
Indeed, suppressing more general events would make more sense than "breaking" established bindings. Nevertheless, I'm already happy if this puts a tiny bit more weight for fixing #4967 in the future.
