### ISSUE TITLE
Add option to disable single axis zoom on WheelZoomTool 

### ISSUE THREAD

**Issue by kcpevey** [bokeh/bokeh#7815] opened 2018-04-19 18:56 UTC
Zooming on a single axis is not appropriate for map-based plots or projected data. Having the ability to disable the single axis zoom, therefore only making the scaled zoom available, would be really great to have.

**Comment by bryevdv** [comment] 2018-04-19 19:12
This is a dupe of https://github.com/bokeh/bokeh/issues/2427 which was completed in #7743

**Closed by bryevdv** 2018-04-19 19:12 UTC

**Comment by kcpevey** [comment] 2018-04-19 19:19
My apologies!
