### ISSUE TITLE
0.12.9 misplaced figure title

### ISSUE THREAD

**Issue by rocheseb** [bokeh/bokeh#6932] opened 2017-09-13 21:57 UTC
You changed ResetToolView.prototype.doit with that line :
`return this.plot_model.plot.trigger_event(new bokeh_events_1.Reset());`
I am not sure if that is the reason but the reset tool no longer fixes the position of updated titles in plots.
See this example:

```
from bokeh.io import show, output_file
from bokeh.plotting import figure
from bokeh.models import CustomJS, Button
from bokeh.layouts import gridplot

output_file("test.html")
fig = figure()
fig.line(x=[1,2,3], y=[1,2,3])

button = Button(label="add title",callback=CustomJS(args={'title':fig.title},code="title.text='new title'"))

show(gridplot([[fig,button]]))
```
After pushing the button the title will be inside the plot instead of above it, this used to be fixed when pushing the reset button.
This gets fixed when you drag the webpage tab and then let it go, or when you open the console (checked in firefox and chrome).

If an original title is given like 
`fig = figure(title='original title')`
then the title will be correctly placed above the plot, and the updated title too

**Comment by bryevdv** [comment] 2017-09-14 05:48
@rocheseb I'm not clear, when you say:

 > After pushing the button the title will be inside the plot instead of above it, this used to be fixed when pushing the reset button.

Do you mean it has *always* been the case that changing the title has misplaced the title, and that hitting reset was your workaround to fix it? If so, that was purely an accident. I don't think the change has anything to do with this, there was other layout work that might have had an impact. Regardless, if the title is being misplaced, we should concentrate on fixing that core issue, not on an accidental and unintentional  bandaid workaround.

**Comment by rocheseb** [comment] 2017-09-14 12:38
@bryevdv yes agreed the misplaced title is the issue and it has always happened when a title was not originally given.

**Comment by mattpap** [comment] 2017-09-27 12:57
This is "by design" and limited by the fact that updating certain parts of layout isn't possible. I will be working on this broad subject in my next round of layout improvements.

**Comment by mattpap** [comment] 2017-09-27 13:00
@rocheseb, for now you can use ugly hack from https://github.com/bokeh/bokeh/issues/6748#issuecomment-321014827 to force re-layout in your custom js.

**Comment by bryevdv** [comment] 2017-10-26 00:11
@mattpap after the recent changes, this code produces the toolbar above the button, what's going on?
<img width="798" alt="screen shot 2017-10-25 at 19 10 40" src="https://user-images.githubusercontent.com/1078448/32029155-45931e76-b9b8-11e7-8bc7-01d5b68c9a5c.png">

**Comment by bryevdv** [comment] 2017-10-26 00:14
OK well now the code does not seem to add a title at all, except that it does, it is just covered up. If you add e.g. `min_border=60` the  you can see the title update properly. I think this is a dupe of the other issues about axis labels not triggering re-layouts?

**Comment by mattpap** [comment] 2017-10-26 07:40
> after the recent changes, this code produces the toolbar above the button, what's going on?

It's correct now. Detached toolbar is added to this layout as a row spanning all columns.

**Comment by mattpap** [comment] 2017-10-26 07:43
> I think this is a dupe of the other issues about axis labels not triggering re-layouts?

Most of issues of this kind boil down to the same lack of ability to update layout. If we are going to close a subset of those issues as duplicates, just make sure to reference duplicates in the main issue, so that I can test each provided code, in case there's something unique about them.

**Comment by rocheseb** [comment] 2017-10-26 13:22
For now a simple workaround is to declare the figure with a whitespace title every time.
`fig=figure(title=" ")`

**Comment by bryevdv** [comment] 2017-12-19 17:05
This appears to be fixed in master, before/after button press using original issue code:

<img width="812" alt="screen shot 2017-12-19 at 11 04 44" src="https://user-images.githubusercontent.com/1078448/34169287-85787828-e4ac-11e7-88bc-a57e9c677fa6.png">

<img width="786" alt="screen shot 2017-12-19 at 11 04 50" src="https://user-images.githubusercontent.com/1078448/34169295-893dfbfe-e4ac-11e7-8779-161cc7ee01e1.png">

**Closed by bryevdv** 2017-12-19 17:05 UTC
Labels: tag: layout, type: bug
