### ISSUE TITLE
One pixel overlap of toolbar on top of plot's outline (bokehjs, burtin)

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4610] opened 2016-06-21 11:14 UTC
Pretty much outline is hidden along toolbar.

**Comment by birdsarah** [comment] 2016-06-22 00:05
dupe of #4574?

**Comment by canavandl** [comment] 2016-06-22 00:10
Is this related to: #4376 ?

i.e. Adding a border_line to a css box model causes the box to increase in size by the line width (i.e. the box increases by the width of the border_line)

**Comment by birdsarah** [comment] 2016-06-22 00:13
I don't think so because it's canvas, but I don't know how we apply the border to canvas.

**Comment by birdsarah** [comment] 2016-06-22 00:13
What I'm trying to say is I believe that the border is drawn on the canvas and not a css border.

**Comment by canavandl** [comment] 2016-06-22 00:26
You're right that the border is drawn onto the canvas: https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/plots/plot_canvas.coffee#L615

**Comment by mattpap** [comment] 2016-06-22 10:49
@birdsarah, duplicate, just different examples are in consideration, but the problem the same.

**Comment by birdsarah** [comment] 2016-06-22 21:27
I've noted that it also affects the burtin js example on #4574. Closing this so there's just one place to solve it. Feel free to add any extra details.

**Closed by birdsarah** 2016-06-22 21:27 UTC
Labels: reso: duplicate, tag: regression, type: bug
