### ISSUE TITLE
Touch scroll the page when no tools are active

### ISSUE THREAD

**Issue by samaust** [bokeh/bokeh#5918] opened 2017-02-24 03:56 UTC
# Version :

Tested on Bokeh 0.12.3.

# Expected behavior :
When no tools are active in the toolbar and you slide your finger up and down starting on a plot on an Android Tablet, the web page should scroll up and down.

# Observed behavior :
The page does not scroll.

# My solution :

1. Change the default Hammer option touchAction from TOUCH_ACTION_COMPUTE to TOUCH_ACTION_PAN_Y.
2. if a 'pan' event_type is received, call preventDefault on the event (code in bold below).

<pre>
UIEvents.prototype._trigger_event = function(event_type, active_tool, e) {
    if (active_tool.active === true) {
      if (event_type === 'scroll') {
        e.preventDefault();
        e.stopPropagation();
      }<b>
      if (event_type === 'pan') {
        e.preventDefault();
      }</b>
      return this.trigger(event_type + ":" + active_tool.id, e);
    }
  };
</pre>

# References :
https://github.com/hammerjs/hammer.js/issues/241
https://github.com/hammerjs/hammer.js/wiki/How-to-fix-Chrome-35--and-IE10--scrolling-(touch-action)

# Discussion

When using Bokeh on a tablet, I disable all the tools by default and I want the page to scroll using touch when no tools are selected. I use long webpages with a Bokeh plot at the top that takes almost all width and can take more than the screen height. I plot large Gantt charts using quad glyphs.

I leave the proper implementation to the more experienced Bokeh developpers. I don't have a deep enough understanding of Bokeh to be sure that the above fix does not break something else.

**Comment by bryevdv** [comment] 2017-02-24 15:09
@samaust Thanks for the detailed write up. Despite your modesty, I think it would be helpful if you have the ability to make a small PR to do so. It will lift a burden on over-committed devs and make it things simpler to test and evaluate (and if there are more changes to make, maintainers can continue working on the branch, but having a fist cut helps immensely)

**Comment by patrickjwright** [comment] 2017-11-20 22:47
I am having the exact same expected behavior and observed behavior. My issue is described in a [SO post](https://stackoverflow.com/questions/47162223/enable-touch-scrolling-for-mobile-view-bokeh-app). After extensive experimentation with various potential css solutions (such as disabling/enabling the `-webkit-overflow-scrolling: touch;` property), I have come to the conclusion that the Bokeh plots themselves are preventing touch scrolling on a mobile display. Areas outside the plot window are touch-sensitive, but if you have one (or several) large plots with no white space on the edges, scrolling is not functional within the plot area. The link for my mobile app is here: https://btac-web-plots.herokuapp.com/avyview?style=snowpacktracker-mobile. There are no tools enabled, and touch scrolling does not work.

Rather than editing .js files within Bokeh, only to lose my edits with future Bokeh updates, it would be great if a solution similar to the above could be implemented in an upcoming Bokeh release! This would make Bokeh Apps much more user friendly on mobile platforms.

**Comment by Bobstin** [comment] 2018-02-12 16:40
Hi! First time at this, and I am not that familiar with JS, so apologies in advance.

I ran into this problem, and created a quick workaround that works for my situation, but probably is overbroad. I disabled the three hammer events that seem to stop scrolling (pan, pinch, and rotate) if the toolbar is off, by making the change to bokeh.js below (first line is the only material change):

```
if (this.toolbar.toolbar_location != null) {
            this.hammer.get('pan').set({ direction: Hammer.DIRECTION_ALL });
            this.hammer.on('panstart', function (_this) {
                return function (e) {
                    return _this._pan_start(e);
                };
            }(this));
            this.hammer.on('pan', function (_this) {
                return function (e) {
                    return _this._pan(e);
                };
            }(this));
            this.hammer.on('panend', function (_this) {
                return function (e) {
                    return _this._pan_end(e);
                };
            }(this));
            this.hammer.get('pinch').set({ enable: true });
            this.hammer.on('pinchstart', function (_this) {
                return function (e) {
                    return _this._pinch_start(e);
                };
            }(this));
            this.hammer.on('pinch', function (_this) {
                return function (e) {
                    return _this._pinch(e);
                };
            }(this));
            this.hammer.on('pinchend', function (_this) {
                return function (e) {
                    return _this._pinch_end(e);
                };
            }(this));
            this.hammer.get('rotate').set({ enable: true });
            this.hammer.on('rotatestart', function (_this) {
                return function (e) {
                    return _this._rotate_start(e);
                };
            }(this));
            this.hammer.on('rotate', function (_this) {
                return function (e) {
                    return _this._rotate(e);
                };
            }(this));
            this.hammer.on('rotateend', function (_this) {
                return function (e) {
                    return _this._rotate_end(e);
                };
            }(this));
        }
```

Hoping to make a small PR, but my questions are:
1) I think it is too broad to assume someone wants to scroll when touched just because the toolbar is off. Is there a better rule that I should use? (that there are no tools enabled?) Should it be added as an option "scroll_when_touched" to the figure?
2) In github, the relevant code seems to be in ui_events.ts, but I'm not sure how to compile everything into a bokeh.js that I can use for testing. Are there some resources you could point me to?

Thanks!

**Comment by invokermain** [comment] 2018-10-16 17:42
Not sure if this is GitHub etiquette, but also would love to see this issue solved as it impacts mobile users viewing embedded bokeh plots on a website dramatically.

**Comment by bryevdv** [comment] 2018-10-16 17:48
> Not sure if this is GitHub etiquette, but also would love to see this issue solved as it impacts mobile users viewing embedded bokeh plots on a website dramatically.

Solving issues like this one is going to require someone with the necessary mobile dev experience to step up an become a new contributor.

**Comment by hrobinsona** [comment] 2019-03-24 15:58
Is there any resolution to this?

**Comment by bryevdv** [comment] 2019-03-24 17:17
@hrobinsona if there were any updates, they would be here. As I said above, this is any area where the project needs help. We are happy to collaborate with any experience mobile dev.

**Closed** 2019-04-13 02:08 UTC
Labels: tag: component: bokehjs, type: task
