### ISSUE TITLE
Hover text issues in examples/glyphs/calendars.py

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#2094] opened 2015-03-23 16:45 UTC
The first issue is that in place of apostrophes in hover text, we instead get a jumble of characters.

![screen shot 2015-03-23 at 11 36 47 am](https://cloud.githubusercontent.com/assets/1417520/6785119/ca84df54-d151-11e4-80a3-84f442fae185.png)

Second is the way the hover direction is determined.  It appears that any holiday that falls at the end of the week will display hovering to the left of the date on the calendar.

This is fine unless the given calendar is the furthest left on its row, in which case, the text can be cut off by the end of the page.

![calendar](https://cloud.githubusercontent.com/assets/1417520/6785171/143fe36e-d152-11e4-9e5b-23393e96f32d.png)

**Comment by jcrist** [comment] 2015-06-25 04:38
I just ran into the first part (html escape characters being inserted). Simple reproducible example:

```python
from collections import OrderedDict
from bokeh.plotting import output_file, show, figure, ColumnDataSource
from bokeh.models import HoverTool

output_file('test.html')
p = figure(tools='hover')

data = {'x': [0, 1, 2, 3],
        'y': [0, 1, 2, 3],
        'width': [1, 1, 1, 1],
        'height': [1, 1, 1, 1],
        'hover': ["Hover", "doesn't", 'handle', '"quotes"']}

source = ColumnDataSource(data=data)
p.rect(source=source, x='x', y='y', width='width', height='height')

p.select(type=HoverTool).tooltips = OrderedDict([('tip', '@hover')])

show(p)
```

**Comment by colinfang** [comment] 2015-07-09 23:10
Can we add an option to mark certain `replace_placeholders` safe so that the HTML escape doesn't apply?

Code here: https://github.com/bokeh/bokeh/blob/0c78cf646ec95d3c003c714c35a388db4b4ad834/bokehjs/src/coffee/util/util.coffee#L38

Besides I think `OpenURL` might have a problem of escaping if it contains query parameters, i.e. ?a=1&b=2, which are incorrectly escaped as well.

**Comment by birdsarah** [comment] 2015-07-16 21:06
I know this isn't perfect, but if you use the custom form of tooltips then the escaping won't be an issue.

Try:

```python
p.select(type=HoverTool).tooltips = '@hover'
```

You could add more custom styling inline to give a better look and feel if you want.  You may also be able to work around the left cut off as a result.

See sprints https://github.com/bokeh/bokeh/blob/master/examples/glyphs/sprint.py#L90 for an elaborate example.

Personally, I like to really customize my bokeh tooltips, but that involves rolling your own css which you may not want to do. I can point you to some examples if you're interested.

**Comment by birdsarah** [comment] 2016-03-10 20:24
(didn't mean to close - sorry)

**Comment by birdsarah** [comment] 2016-08-05 22:07
Closing as duplicate of #4930 which very nicely lays out the hover cutoff problem.

**Closed by birdsarah** 2016-08-05 22:07 UTC
Labels: type: bug
