### ISSUE TITLE
[BUG] DataModel warns about being registered multiple times

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#11029] opened 2021-03-09 18:57 UTC
Every time I display anything all the `DataModels` I have defined complain that they were already registered. Either they are sent and serialized each time or something is causing them to be re-registered each time. In any case I see tons of these warnings:

<img width="297" alt="Screen Shot 2021-03-09 at 7 51 32 PM" src="https://user-images.githubusercontent.com/1550771/110522791-976f1a00-8111-11eb-99c0-6b35d0181e1d.png">

**Comment by bryevdv** [comment] 2021-03-09 18:58
is this a dupe of #11026?

**Comment by mattpap** [comment] 2021-03-09 18:59
No, this is duplication in the other direction.

**Closed** 2021-04-06 01:34 UTC
Labels: reso: completed, tag: component: bokehjs, type: bug
