### ISSUE TITLE
fill_color and line_color do not respect `None` in data

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#3421] opened 2015-12-28 14:33 UTC
Given the following code:
````
from bokeh.plotting import figure
from bokeh.io import output_file, show

output_file('circle.html')

p = figure(tools='')
p.circle(
    x=[1, 2, 3, 4],
    y=[1, 2, 3, 4],
    fill_color=['red', None, 'black', 'gray'],
    line_color=[None, 'blue', None, 'red'],
    line_width=5,
    radius=0.5
)
show(p)
````
I see: 
<img width="598" alt="screen shot 2015-12-28 at 9 30 56 am" src="https://cloud.githubusercontent.com/assets/1796208/12020054/b92fd580-ad45-11e5-8f26-83793c1eed65.png">

I had expected:
1) The second circle (at 2,2) to have no fill
2) The first and third circles to have no outlines.

**Comment by canavandl** [comment] 2016-02-21 03:06
This issue is a duplicate of #2622 and has a related doc warning PR in #3904 . The problem isn't the None argument exactly - there'd be the same behavior with 

```python
...
fill_color=['red', (0,0,0,0), 'black', 'gray'],
...
``` 

but rather an issue with having non-CSS compliant color props in data sources. See discussion in #2622 for more.

 I'm going to make as duplicate and close, unless you disagree.

**Closed by canavandl** 2016-02-21 03:06 UTC
Labels: type: discussion
