### ISSUE TITLE
Wheel zooming makes glyph render over toolbar area

### ISSUE THREAD

**Issue by camelia-c** [bokeh/bokeh#7403] opened 2018-01-11 17:06 UTC
Hello,

Using Bokeh 0.12.13, I get this behaviour when zooming

![image](https://user-images.githubusercontent.com/5008864/34836854-c4435188-f701-11e7-8bb5-d088c359ee15.png)

As you can see, the glyphs in blue color are plotted over the toolbar zone (be it on the left/right/below/above) as well as over the title zone. The figure's other two edges (that don't have title nor toolbar) are displayed ok.

Thank you in advance,
Camelia

**Comment by mattpap** [comment] 2018-01-11 17:37
Do you have webgl enabled?

**Comment by camelia-c** [comment] 2018-01-11 18:31
Thank you for answering so fast!

Indeed, the behaviour only happens with the  output_backend="webgl"

I do have WebGL enabled - I've checked as suggested in https://superuser.com/questions/836832/how-can-i-enable-webgl-in-my-browser

and here is one screenshot for Chrome (latest version):

![image](https://user-images.githubusercontent.com/5008864/34840074-8c4da61a-f70c-11e7-84ad-13a3b37f58b5.png)

Thank you!

**Comment by mattpap** [comment] 2018-01-12 13:57
It's likely this is a duplicate of #7211, #6867 and possibly other issues. webgl is supported by your browser, but fails somewhere else (e.g. graphic driver). The fallback to software renderer is broken on bokeh's side and results in the visible artifacts. Are there any errors or other unusual information in JS console?

**Comment by mattpap** [comment] 2018-03-26 15:17
Closing as a duplicate of #6867.

**Closed by mattpap** 2018-03-26 15:17 UTC
