### ISSUE TITLE
hover hover

### ISSUE THREAD

**Issue by Pierretherenard** [bokeh/bokeh#5922] opened 2017-02-26 17:40 UTC
This is what i use: (insert code never work for me sorry)

hover = p5.select(dict(type=HoverTool))
            hover.tooltips = [("New words", " @ttnwwrd"), ('Date', ' @date'), ('Nb Source', ' @hwmnsrc')]

            p5.add_tools(HoverTool(renderers=[redot], tooltips=[("Date", " @nowd"), ]))

            p5.add_tools(HoverTool(renderers=[circleabv], tooltips=[("Total", " @ttabv100"),]))
I tried this one as well, which mean just having add_tools:
hover = p5.select(dict(type=HoverTool))
            #hover.tooltips = [("New words", " @ttnwwrd"), ('Date', ' @date'), ('Nb Source', ' @hwmnsrc')]
            p5.add_tools(HoverTool(renderers=[hovbar],tooltips=[("New words", " @ttnwwrd"), ('Date', ' @date'), ('Nb Source', ' @hwmnsrc'),]))
            p5.add_tools(HoverTool(renderers=[redot], tooltips=[("Date", " @nowd"), ]))

            p5.add_tools(HoverTool(renderers=[circleabv], tooltips=[("Total", " @ttabv100"),]))
This is what i get with the last code when i hover on the red circle:
![screen shot 2017-02-26 at 9 37 08 am](https://cloud.githubusercontent.com/assets/23002446/23342019/3b012580-fc07-11e6-8749-1222a23f7f25.png)

the previous code as well display overlap of Hover

**Comment by bryevdv** [comment] 2017-03-01 22:48
This is a duplicate of https://github.com/bokeh/bokeh/issues/1512

**Closed by bryevdv** 2017-03-01 22:48 UTC
