### ISSUE TITLE
Feature request: vertical-horizontal line points connection

### ISSUE THREAD

**Issue by cloud-rocket** [bokeh/bokeh#6692] opened 2017-07-28 19:31 UTC
Per [this](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/jmWFAtr20I0) discussion, it will be great to have a built in option for line glyph (or it's own glyph) for creating a chart with vertical-horizontal lines connecting data points (instead of direct line).

Currently extra points need to be added to achieve this functionality.

Use-cases requiring this functionality:
* Displaying "square" signals
* Tracking value changes

Etc.

Thanks,
Meir Tseitlin

**Comment by bryevdv** [comment] 2017-07-28 19:42
This is a dupe of https://github.com/bokeh/bokeh/issues/3644

**Closed by bryevdv** 2017-07-28 19:42 UTC
