### ISSUE TITLE
Hover Tooltips for image_rgba

### ISSUE THREAD

**Issue by rokalito** [bokeh/bokeh#8706] opened 2019-03-04 10:18 UTC
Hi,

I'm quite new to Bokeh, but it seems that the basic image.py provided as an example which shows x,y and the value when hovering over an image, does not work when using "image_rgba".  Does anyone know why? 

If it's not implemented, as suggested in [https://stackoverflow.com/questions/54753032/hover-image-rgba-bokeh](url), is there any other way of achieving a similar result? 

In any case, it doesn't look like it would be very hard to implement this feature, and it would be very much appreciated.

Best regards,

**Comment by bryevdv** [comment] 2019-03-04 16:59
@rokalito  It simply has not been implemented due to time/resource contstraints. Would you be interested in working on this with some guidance?

**Comment by bryevdv** [comment] 2019-03-12 05:04
This is a duplicate of #8668

**Closed by bryevdv** 2019-03-12 05:04 UTC
