### ISSUE TITLE
Axis zoom range selector

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [bokeh/bokeh#3441] opened 2015-12-29 18:39 UTC
Are you planning to add zoom range selector like many other plot libraries?https://developers.google.com/chart/interactive/docs/gallery/annotationchart, http://www.highcharts.com/docs/chart-concepts/range-selector or https://rstudio.github.io/dygraphs/gallery-range-selector.html

It is very popular for time-series axis, but can be used for any type of long axis that requires a smart and fast scrolling.

It is very popular UX expectations for modern and interactive plots.

**Comment by bryevdv** [comment] 2015-12-29 21:31
Adding a specialized interface for almost certainly might make sense, but just FYI in case it is useful, this can mostly be accomplished currently with a `BoxSelectTool` and a few lines of code in a `CustomJS` callback. 
```
x = np.linspace(0, 10, 500)
y = np.sin(x) + np.random.normal(size=500)

p1 = figure(plot_width=800, plot_height=250, min_border=0)
p1.line(x, y)

p2 = figure(plot_width=800, plot_height=250, min_border=0)
p2.line(x, y)

callback = CustomJS(args=dict(p1=p1), lang="coffeescript", code="""
    g = cb_data.geometry
    p1.get('frame').get('x_ranges').default.set({start: g.x0, end: g.x1})
""")

p2.add_tools(BoxSelectTool(callback=callback, dimensions=['width']))

show(vplot(p1, p2))
```
What is lacking: ability to leave the overlay present (is a new existing feature issue), and it's not possible to specify "no renderers" for hit testing it seems.

**Comment by VelizarVESSELINOV** [comment] 2015-12-29 23:16
I agree you have 1st step of zoom range selector, what I like it is that is generic and the developer can use it horizontally, vertically for any kid of axis, but please find the few items that I was not able to do:
 1. First UX the tooltip is going outside the visual boundaries
 2. I was not able to hide the toolbar with one possible action should be able to remove it
 3. No visual indication of which part of the upper part I'm looking in the bottom part plot
 4. There is easy way to move left, right or adjust the left or right zoom range without do all the selection from the beginning.
 5. If I'm moving the upper part I would like to see the visual update of the bottom part
 6. Possibility to create global buttons like 1h, 1d for automatic zoom on all the connected plots

![rangeselector](https://cloud.githubusercontent.com/assets/8209940/12043843/f10af1c6-ae3d-11e5-8599-e1f5a895213a.png)

```
"""Bokeh range select test."""
import numpy as np

from bokeh.models import BoxSelectTool
from bokeh.models.callbacks import CustomJS
from bokeh.plotting import figure, show, vplot

x = np.linspace(0, 10, 500)
y = np.sin(x) + np.random.normal(size=500)

p1 = figure(plot_width=800, plot_height=250, min_border=0)
p1.line(x, y)

p2 = figure(plot_width=800, plot_height=50, min_border=0, tools='', logo=None)
p2.line(x, y)

callback = CustomJS(args=dict(p1=p1), code="""
    g = cb_data.geometry
    p1.get('frame').get('x_ranges').default.set({start: g.x0, end: g.x1})""")

p2.add_tools(BoxSelectTool(callback=callback, dimensions=['width']))

show(vplot(p1, p2))
```

**Comment by VelizarVESSELINOV** [comment] 2016-06-03 03:17
The code above is not working anymore with the latest version of Bokeh, it is challenging to debug Bokeh JS code.

For step 3 is needed to display rectangle object Rect, it is unclear how to access the properties in JS language ```rect.get('frame').get('x_ranges').default.set({start: g.x0, end: g.x1})""")```

**Comment by bryevdv** [comment] 2016-06-03 03:28
The JS callback was still correct, the problem was something different. There was a bug in `min_border` combined with a minimum canvas size. Setting the top and bottom explicitly works for me:
```
"""Bokeh range select test."""
import numpy as np

from bokeh.models import BoxSelectTool
from bokeh.models.callbacks import CustomJS
from bokeh.plotting import figure, show, vplot, output_file

x = np.linspace(0, 10, 500)
y = np.sin(x) + np.random.normal(size=500)

p1 = figure(plot_width=800, plot_height=250, min_border_top=0, min_border_bottom=0)
p1.line(x, y)

p2 = figure(plot_width=800, plot_height=80, min_border_top=0, min_border_bottom=0, toolbar_location=None, tools='', logo=None)
p2.line(x, y)

callback = CustomJS(args=dict(p1=p1), code="""
    g = cb_data.geometry
    p1.get('frame').get('x_ranges').default.set({start: g.x0, end: g.x1})""")

p2.add_tools(BoxSelectTool(callback=callback, dimensions=['width']))

output_file("bar.html")

show(vplot(p1, p2))
```

**Comment by VelizarVESSELINOV** [comment] 2016-06-03 04:07
@bryevdv Thanks for the bug workaround

Please find improved version of the overview plot, but as you can see there is two rectangles, one when you move on the top plot and another when you select the zoom area on the bottom, and I'm unable to sync them together.
```python
"""Bokeh range select test."""
import numpy as np

from bokeh.models import BoxSelectTool, Rect, ColumnDataSource
from bokeh.models.callbacks import CustomJS
from bokeh.plotting import figure, show, vplot, output_file
from bokeh.io import output_notebook

output_notebook()

source = ColumnDataSource({'x': [], 'width': []})

jscode="""
    var data = source.get('data');
    var start = cb_obj.get('start');
    var end = cb_obj.get('end');
    data['%s'] = [start + (end - start) / 2];
    data['%s'] = [end - start];
    source.trigger('change');
"""
x = np.linspace(0, 10, 500)
y = np.sin(x) + np.random.normal(size=500) / 10

p1 = figure(plot_width=800, plot_height=250, min_border_top=0, min_border_bottom=0)
p1.line(x, y)
p1.x_range.callback = CustomJS(args=dict(source=source), code=jscode % ('x', 'width'))

p2 = figure(plot_width=800, plot_height=80, min_border_top=0, min_border_bottom=0, toolbar_location=None, tools='',
            logo=None)

p2.line(x, y)
            
rect = Rect(x='x', y=0, width='width', height=5, fill_alpha=0.1,
            line_color='black', fill_color='black')
p2.add_glyph(source, rect)

callback = CustomJS(args=dict(p1=p1, rect=rect, source=source), code="""
    g = cb_data.geometry
    p1.get('frame').get('x_ranges').default.set({start: g.x0, end: g.x1})
    rect.set({x: g.x0, width: g.x1 - g.x0});""" + jscode)

p2.add_tools(BoxSelectTool(callback=callback, dimensions=['width']))

show(vplot(p1, p2))
```

**Comment by VelizarVESSELINOV** [comment] 2016-06-28 13:00
**0.12.0 regression**

There are two interactions in the script:

1. Move upper position x range it is shown in the bottom plot
2. Select x range in the bottom overview plot should be propagated to the upper plot (with 0.12.0 stopped to work, with 0.11.1 version is working)

Updated version of code to manage vplot to column change.
```python
"""Bokeh range select test."""
import numpy as np

from bokeh.models import BoxSelectTool, Rect, ColumnDataSource
from bokeh.models.callbacks import CustomJS
from bokeh.plotting import figure, show, output_file
from bokeh.layouts import column
from bokeh.io import output_notebook

output_notebook()

source = ColumnDataSource({'x': [], 'width': []})

jscode="""
    var data = source.get('data');
    var start = cb_obj.get('start');
    var end = cb_obj.get('end');
    data['%s'] = [start + (end - start) / 2];
    data['%s'] = [end - start];
    source.trigger('change');
"""
x = np.linspace(0, 10, 500)
y = np.sin(x) + np.random.normal(size=500) / 10

p1 = figure(plot_width=800, plot_height=250, min_border_top=0, min_border_bottom=0)
p1.line(x, y)
p1.x_range.callback = CustomJS(args=dict(source=source), code=jscode % ('x', 'width'))

p2 = figure(plot_width=800, plot_height=80, min_border_top=0, min_border_bottom=0, toolbar_location=None, tools='',
            logo=None)

p2.line(x, y)

rect = Rect(x='x', y=0, width='width', height=5, fill_alpha=0.1,
            line_color='black', fill_color='black')
p2.add_glyph(source, rect)

callback = CustomJS(args=dict(p1=p1, rect=rect, source=source), code="""
    g = cb_data.geometry
    p1.get('frame').get('x_ranges').default.set({start: g.x0, end: g.x1})
    rect.set({x: g.x0, width: g.x1 - g.x0});""" + jscode)

p2.add_tools(BoxSelectTool(callback=callback, dimensions=['width']))

show(column(p1, p2))
```

**Comment by bryevdv** [comment] 2016-06-28 13:33
Hi, previously the JS API was largely considered an internal implementation detail. We are working to make it more stable and documented going forward, to help support the use of both JS callbacks and custom extensions, but the recent layout work necessitated some fairly extensive changes on the BokehJS side that were unavoidable. This updated callback works for me:
```
callback = CustomJS(args=dict(p1=p1, rect=rect, source=source), code="""
    g = cb_data.geometry
    p1.plot_canvas.frame.get('x_ranges').default.set({start: g.x0, end: g.x1})
    rect.set({x: g.x0, width: g.x1 - g.x0});""" + jscode)
```

**Comment by VelizarVESSELINOV** [comment] 2016-10-10 18:36
@bryevdv the previous script it is not working with Bokeh 0.12.3, what are the recent changes that can make the callback work again?

**Comment by bryevdv** [comment] 2016-10-10 18:52
ping @mattpap

**Comment by VelizarVESSELINOV** [comment] 2016-10-11 01:15
After some troubles, please find few edits to make it work with 0.12.3:

```python
"""Bokeh range select test."""
import numpy as np

from bokeh.models import BoxSelectTool, Rect, ColumnDataSource
from bokeh.models.callbacks import CustomJS
from bokeh.plotting import figure, show, output_file
from bokeh.layouts import column
from bokeh.io import output_notebook

output_notebook()

source = ColumnDataSource({'x': [], 'y': [], 'width': [], 'height': []})

jscode="""
    var data = source.data;
    var start = cb_obj.start;
    var end = cb_obj.end;
    var width = end - start;
    data['%s'] = [start + width / 2];
    data['%s'] = [width];
    source.trigger('change');
"""

x = np.linspace(0, 10, 500)
y = np.sin(x) + np.random.normal(size=500) / 10

p1 = figure(plot_width=800, plot_height=250, min_border_top=0, min_border_bottom=0)
p1.line(x, y)
p1.x_range.callback = CustomJS(args=dict(source=source), code=jscode % ('x', 'width'))
p1.y_range.callback = CustomJS(args=dict(source=source), code=jscode % ('y', 'height'))
plot_width=800

p2 = figure(plot_width=plot_width, plot_height=80, min_border_top=0, min_border_bottom=0, toolbar_location=None, tools='',
            logo=None)

p2.line(x, y)

rect = Rect(x='x', y='y', width='width', height='height', fill_alpha=0.1,
            line_color='black', fill_color='black')
p2.add_glyph(source, rect)

callback = CustomJS(args=dict(p1=p1, rect=rect, source=source), code="""
    var g = cb_data['geometry'];
    var x = g['x0'];
    var width = g['x1'] - g['x0'];
    // console.log('x', x, 'width', width);
    p1.plot_canvas.frame.x_range.start = g['x0'];
    p1.plot_canvas.frame.x_range.end = g['x1'];
    var data = source.data;
    data.x = [x + width / 2];
    data.width = [width];
    source.trigger('change');
    """)

p2.add_tools(BoxSelectTool(callback=callback, dimensions='width'))

show(column(p1, p2))
```

**Comment by bryevdv** [comment] 2016-10-11 13:43
@VelizarVESSELINOV would you be interested in working up a PR to add a tool for this? As you state, I think many people would find this useful and be appreciative. I think it would essentially be identical to the current box zoom tool, except that it could be configured with a second plot, and it would update the ranges of that second plot instead of the one the tool is on. In fact , maybe this second plot to modify could just be added as an option property on the existing box zoom tool.

**Comment by VelizarVESSELINOV** [comment] 2016-10-11 13:58
@bryevdv please let me know what it is needed for PR.
In general our needs are very close to what Plotly it is proposing: https://plot.ly/python/range-slider/
The two missing parts are:

1. Possibility to adjust the box in the overview track (move all the rectangle or move one of the sides of the rectangle).
2. Quick access to predefined ranges (1d, 1h, etc.)

Of course will be nice to improve the UX, in my example the current view is grey in Plotly the hidden part is grey, etc.

**Comment by bryevdv** [comment] 2016-10-11 14:09
OK thinking about it a bit more, a new tool probably makes sense. The main differences between the current box zoom tool are:

* ability to shade both the selected and unselected areas in a customizable way
* have the shading remain persistent (current box zoom does not do this) 

A "nice to have" (but could be added later in a follow-on) would be a UI handle of some sort at the edge of the selected area.

For your question about what is required, are you asking about what is needed in terms of process and procedure? Or are you asking for technical guidance? I'm happy to supply either or both, I just can't tell which you are looking for.

**Comment by VelizarVESSELINOV** [comment] 2016-10-11 23:19
I think this example should be listed as the other on CustomJS page: http://bokeh.pydata.org/en/latest/docs/user_guide/interaction/callbacks.html#userguide-interaction-callbacks

**Comment by linar-jether** [comment] 2018-03-27 08:30
@VelizarVESSELINOV Your example is no longer working with newer bokeh versions... any chance you already have a fix?

**Comment by bryevdv** [comment] 2018-04-16 23:00
#7795 is a dupe of this. This issue is older, but I happened to sketch out a somewhat detailed plan for how to add this kind of tool there, so I will close this issue and defer to the other.  (I think all the pieces are now in place to make it straightforward now)

**Closed by bryevdv** 2018-04-16 23:00 UTC
Labels: type: feature
