### ISSUE TITLE
Patch (not patches): tools and events not working

### ISSUE THREAD

**Issue by chmielcode** [bokeh/bokeh#9154] opened 2019-08-10 14:49 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 1.3.4
python 3.7.3
firefox 68.0.1
ubuntu 18.04

#### Description of expected behavior and the observed behavior
Registered js_on_event callbacks do not trigger and tools (hover, tap) do not work with a simple "patch". "Patches", on the other hand, work perfectly fine. 
The result of running example code below is that tooltips show up for the "patches"-added glyph and not for the "patch" one.

#### Complete, minimal, self-contained example code that reproduces the issue
```
fig = bokeh.plotting.figure(tools=["hover"], tooltips=[("x", "$x")])
fig.patch(x=[1, 2, 3], y=[1, 2, 6])
fig.patches(xs=[[6, 7, 8]], ys=[[6, 7, 11]])
bokeh.plotting.show(fig)
```

**Comment by bryevdv** [comment] 2019-08-10 14:55
Marking as `feature` since it's not something that exists that is broken, it is something that has  never been implemented for `Patch`

**Comment by bryevdv** [comment] 2020-02-07 05:21
#9182 is a dupe of this but more general, so closing this

**Closed by bryevdv** 2020-02-07 05:21 UTC
Labels: tag: component: bokehjs, type: feature
