### ISSUE TITLE
Plot becomes unresponsive when button widget is appended to layout

### ISSUE THREAD

**Issue by SimonFransen** [bokeh/bokeh#5856] opened 2017-02-07 06:21 UTC
Hi,

I have a problem when appending Button widgets to a VBox in a nested layout.

Python: 2.7.12 64-bit
Bokeh Version: 0.12.4
Browser: Chrome & Edge
OS: Windows 10

The below code reproduces the problem. When the add button is pressed the new Button widget is displayed, however the plot figure stops updating or responding. A small graphics glitch also occurs on the title of the plot. No console or browser errors are reported.

```
import numpy as np

from bokeh.io import curdoc
from bokeh.layouts import row
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

# Set up data
x = np.linspace(0, 4*np.pi, 200)
y = np.sin(x)
source = ColumnDataSource(data=dict(x=x, y=y))

# Set up plot
plot = figure()

plot.line('x', 'y', source=source)

# Problem Code:
from bokeh.models.widgets import Button
from bokeh.models.layouts import VBox

button = Button(label="Add")
vbox = VBox(children=[button])

def create_button():
    button = Button(label=str(len(vbox.children)))
    vbox.children.append(button)

button.on_click(create_button)

curdoc().add_root(row(vbox, plot))
curdoc().title = "Sliders"

```

Thanks in advance for any help on this.

Regards,
Simon

**Comment by cutright** [comment] 2017-04-28 16:10
Very quickly, I just want to mention how appreciative I am of Bokeh.  I'm using it to build a front-end for a large DB in an academic cancer center.  I'm very excited to see how it will improve patient care and research.

In response to Simon:

I have a very similar problem.  I got around this by keeping a very simple layout.  If I use tabs, panels, or complicated combinations of row/column, I lose plot functionality after editing the layout... and it appears as if order matters, but I can't quickly demonstrate that right now.  One work around was to create a new figure and replace the corrupted figure in the layout, but obviously this is clunky and slow compared to simply editing the ColumnSourceData.

Below are two examples of dynamically adding a widget.  One works, the other fails simply by using Tabs.

Bad:
```
from bokeh.layouts import layout, row
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Select, Button, Tabs, Panel

from bokeh.plotting import figure
from bokeh.io import curdoc

source = ColumnDataSource(data={'x': [0, 1, 2, 3, 4],
                                'y': [0, 1, 4, 9, 16]})


def update():
    pass


def button_add_selector_row():
    layout_query.children.append(AddSelectorRow().row)


class AddSelectorRow:
    def __init__(self):
        self.select_category = Select(value="option1", options=["option1", "option2"])
        self.row = row([self.select_category])



# set up layout
plot = figure(plot_width=1000, plot_height=400)
plot.line('x', 'y', source=source)
layout_data = layout([[plot]])


# Set up initial buttons
main_add_selector_button = Button(label="Add Selector", button_type="default", width=400)
main_add_selector_button.on_click(button_add_selector_row)
layout_query = layout([[main_add_selector_button]])


# Generate tabs
tab_query = Panel(child=layout_query, title="Query")
tab_data = Panel(child=layout_data, title="Data")
tabs = Tabs(tabs=[tab_query, tab_data])

curdoc().add_root(tabs)

update()
```

Good:
```
from bokeh.layouts import layout, row
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import Select, Button, Tabs, Panel

from bokeh.plotting import figure
from bokeh.io import curdoc

source = ColumnDataSource(data={'x': [0, 1, 2, 3, 4],
                                'y': [0, 1, 4, 9, 16]})


def update():
    pass


def button_add_selector_row():
    layout_query.children.append(AddSelectorRow().row)


class AddSelectorRow:
    def __init__(self):
        self.select_category = Select(value="option1", options=["option1", "option2"])
        self.row = row([self.select_category])



# set up layout
plot = figure(plot_width=1000, plot_height=400)
plot.line('x', 'y', source=source)

# Set up initial buttons
main_add_selector_button = Button(label="Add Selector", button_type="default", width=400)
main_add_selector_button.on_click(button_add_selector_row)
layout_query = layout([[main_add_selector_button], [plot]])

curdoc().add_root(layout_query)

update()
```

In my final app I have no issues using the following to add a class of widgets from the list query_rows on a button click:
`layout.children.insert(1 + len(query_rows), query_rows[-1].row)`

My initial layout is now defined as a column containing figure, row, DataTable, and PreText objects:

```
layout = column(dvh_plots,
                row(main_add_selector_button,
                    main_add_range_button,
                    main_add_endpoint_button,
                    update_button,
                    download_button),
                data_table_title,
                data_table,
                rxs_table_title,
                data_table_rxs,
                beam_table_title,
                data_table_beams,
                plans_table_title,
                data_table_plans)
```
Bokeh 0.12.5
Python 2.7.10 and 2.7.12
Mac OS X 10.12.4 and Ubuntu 16.04 LTS
Safari 10.1 (Mac), Chrome 58.0 (on Mac), and Firefox 53.0 (on Ubuntu)

**Comment by bryevdv** [comment] 2017-04-28 16:14
I"m not entirely sure these two are related. I also can't reproduce any problems with the original code, on current master. Buttons are added, the plot still pans, etc (though the code doesn't add a title or update anything so I am not quite sure what those statements refer to)

**Comment by cutright** [comment] 2017-04-28 16:16
"original code" meaning Simon's or mine?

**Comment by bryevdv** [comment] 2017-04-28 16:18
Simon's code. It generally works with current master (the new button widths are not great). But it also doesn't do much so I'm not sure if it fully captured the problem or not. (i.e. there is mention of a title and updates but the code does not have either of those) @SimonFransen can you comment?

**Comment by cutright** [comment] 2017-04-28 16:25
I suspect he is seeing the issue near the top of the y-axis here?  It behaves differently if titles are set on the plot.

<img width="1039" alt="text issue" src="https://cloud.githubusercontent.com/assets/4778878/25537690/22dcebc8-2c05-11e7-8652-9cd9dc2fc136.png">

**Comment by mattpap** [comment] 2017-04-28 16:28
Looks like side panels still do collapse.

**Comment by bryevdv** [comment] 2017-04-28 16:39
Adding to `0.12.6` ass part of overall layout effort

**Comment by SimonFransen** [comment] 2017-05-01 04:21
The above code reproduces the bug as is. By title, I just meant the graphics glitch occurs where a title on a graph would usually be. By updates, I just meant through panning and zooming; I haven't tried updating the source data.

I added a title to the figure and received the below graphics glitch once the Add button was pressed. I think it is the same glitch that occurs in @cutright's image although it's a bit hard to tell. The main problem is the graph becoming unresponsive, just thought the graphics glitch might point towards the cause.

plot = figure(title="Title")
![image](https://cloud.githubusercontent.com/assets/17974278/25571385/883e0e74-2e72-11e7-8af4-0993c71635e1.png)

I made the following observations, hope they help:
- The tool selection still functions fine.
- The graph stops panning or zooming.
- Dragging the zoom box tool creates a dotted box, however it's size and shape is not proportional to the mouse movements. The box either has a set height and grows in width faster than the mouse drag distance or has a set width and grows in height faster than the mouse drag distance.
- Clicking the reset tool makes the entire plot area disappear, only the toolbox remains.
- Replacing VBox with column produces the same problem.
- Updated to 0.12.5-py27_0 and the problem was the same.

I tried to make the code do as little as possible except reproduce the bug. My fix so far was to create a custom Bokeh widget that is a list of buttons (or some other widget) that is managed on the JS side. This works well, but might not be ideal for everyone.

Please let me know if you have any questions and thanks for producing this great framework. I think manipulating data in Python (using Pandas) and quickly presenting it interactively in the browser is brilliant.

**Comment by bryevdv** [comment] 2017-05-01 15:36
@SimonFransen Thanks for the clarifications. Here is the result with current `master`:

<img width="930" alt="screen shot 2017-05-01 at 10 34 40" src="https://cloud.githubusercontent.com/assets/1078448/25584002/ddbd5698-2e59-11e7-9f51-13d126bb4c6f.png">

The title is no longer messed up and panning/zooming, etc now function fine. I think this is a substantial improvement tho there are still issues (e.g. the new button width)

**Comment by bryevdv** [comment] 2017-05-01 15:37
For clarity, I'm actually inclined to make two new issues  (for the button width issue, and for @cutright issue) and close this one, any objections?

**Comment by cutright** [comment] 2017-05-01 15:54
OK with me.  Thanks!

**Comment by SimonFransen** [comment] 2017-05-02 01:33
Great, thanks.

**Comment by bryevdv** [comment] 2017-05-08 22:42
@SimonFransen your new issue for the button size: #6259

**Comment by bryevdv** [comment] 2017-05-08 22:52
@cutright and here is yours: #6262 unfortunately I have some good/bad news: both of your code versions above are now failing (bad news) but they are both failing with the same error now, which is also hopefully a simple one to fix (good news)

**Comment by bryevdv** [comment] 2017-05-08 22:53
Closing, since the "unresponsinve" part has been fixed in recent work.

**Closed by bryevdv** 2017-05-08 22:52 UTC
Labels: tag: component: bokehjs, tag: layout, type: bug
