### ISSUE TITLE
Smooth change of RGB-values does not lead to a smooth color change

### ISSUE THREAD

**Issue by mdk73** [bokeh/bokeh#4197] opened 2016-04-20 19:58 UTC
When I keep the values for e.g. green and blue constant at zero, and change the values for red from  zero to 255, I would expect a smooth color transition from black to red.

My test code for RGB-values:
```python
from pandas import DataFrame
from bokeh.io import show, output_file, output_server
from bokeh.charts import Line, color
import subprocess
import time

if __name__ == '__main__':   
    output_file('rgb-palette.html')
    
    maxvalue = 255

    #empty dictionary for a DataFrame
    dic = {}
    
    # DataFrame
    # creating as many rows as maxvalue
    # two columns to create a straight line per row
    yvalue = 0
    for item in list(range(maxvalue)):
        dic[str(item)] = [yvalue, yvalue]
        yvalue = yvalue + 1
    df = DataFrame(dic)
    
    # set color palette rgb
    palette_r = list(range(maxvalue)) 
    palette_g = maxvalue * [0]    # keeping values for 'green' constant. 
    palette_b = maxvalue * [0]    # keeping values for 'blue' constant. 
    palette = list(zip(palette_r, palette_g, palette_b))
    
    # define the plot
    p = Line(df, title="palette rgb", plot_width = 300, plot_height = 200,
            color=palette)

    show(p)
```

Result:
![image](https://cloud.githubusercontent.com/assets/2737768/14688255/00717858-0742-11e6-8c03-20c5860820a3.png)

The color transition is not smooth from black to red, but seems to start several times from black to red.
For Hex-values I get the same result.

**Comment by bryevdv** [comment] 2016-04-20 20:23
I think this is a problem with your data not being what you think it is. You are making the keys of the dict be strings:
```
'253': [253, 253],
 '254': [254, 254],
 '26': [26, 26],
 '27': [27, 27],
 '28': [28, 28],
 '29': [29, 29],
 '3': [3, 3],
 '30': [30, 30],
 '31': [31, 31],
 '32': [32, 32],
 '33': [33, 33],
 '34': [34, 34],
 '35': [35, 35],
 '36': [36, 36],
```
I'm not sure what pandas is doing with that, but it is probably not what you think:
```
In [40]: df
Out[40]: 
   0  1  10  100  101  102  103  104  105  106 ...  90  91  92  93  94  95  \
0  0  1  10  100  101  102  103  104  105  106 ...  90  91  92  93  94  95   
1  0  1  10  100  101  102  103  104  105  106 ...  90  91  92  93  94  95   

   96  97  98  99  
0  96  97  98  99  
1  96  97  98  99  

[2 rows x 255 columns]

```
At the moment, I believe this is a support question, and not a bug, so I am closing and referring you to the mailing list:

https://groups.google.com/a/continuum.io/forum/?pli=1#!forum/bokeh

If it is established that this is a bug then we can certainly re-open.

**Closed by bryevdv** 2016-04-20 20:23 UTC

**Comment by bryevdv** [comment] 2016-04-20 20:31
Looking more, I think the issue is that the columns in the data frame are sorted alphabetically by column name, and the palette is cycled through in order.

**Comment by bryevdv** [comment] 2016-04-20 20:31
Yup, pad with zeros:
```
for item in list(range(maxvalue)):
    dic['%03d' % item] = [yvalue, yvalue]
    yvalue = yvalue + 1
```
to get:
```
In [64]: df
Out[64]: 
   000  001  002  003  004  005  006  007  008  009 ...   245  246  247  248  \
0    0    1    2    3    4    5    6    7    8    9 ...   245  246  247  248   
1    0    1    2    3    4    5    6    7    8    9 ...   245  246  247  248   

   249  250  251  252  253  254  
0  249  250  251  252  253  254  
1  249  250  251  252  253  254  

[2 rows x 255 columns]
```
yields this plot:
<img width="301" alt="screen shot 2016-04-20 at 3 31 39 pm" src="https://cloud.githubusercontent.com/assets/1078448/14689469/03db476a-070d-11e6-81ac-d767710ff1d4.png">

**Comment by mdk73** [comment] 2016-04-21 04:26
Many thanks for pointing out and correcting the mistake in the column design!
