### ISSUE TITLE
Feature request: click-drag Tool 

### ISSUE THREAD

**Issue by shaunswanson** [bokeh/bokeh#6503] opened 2017-06-19 22:25 UTC
Hi everyone. I'm trying to build a Bokeh-based graph editor which would require the type of click-drag interaction described in this Google Group thread (https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/45RfxZWUBOg). Specifically, I'd like to use a click-drag interaction to move individual Circle glyphs and to create new Segment glyphs between two Circle nodes.

Is there any timeline for when such functionality might be included as a new Tool perhaps?

Should I focus on developing something using custom javascript callbacks to make the above features possible today?

Thanks!
Shaun

**Comment by jlstevens** [comment] 2017-06-19 23:06
> Is there any timeline for when such functionality might be included as a new Tool perhaps?

Yes! 

This work is currently in development as part of a set of general edit tools that I am working on together with @philippjfr. What you are suggesting sounds like it will be covered by that work which we have been discussing in #6370.

I'll close this issue as a duplicate of #6370 so please do give us feedback/suggestions on that issue!

**Closed by jlstevens** 2017-06-19 23:06 UTC

**Comment by shaunswanson** [comment] 2017-06-20 07:59
Sweet, thanks :)

**Comment by shaunswanson** [comment] 2017-06-20 08:12
@jlstevens the issue you linked to (#6370) would probably work for my problem of edge drawing in this graph editor (click-and-drag to generate Segment glyph), but it doesn't appear to allow me to click-and-drag single Circle glyphs to different positions?

**Comment by jlstevens** [comment] 2017-06-20 11:09
I would expect glyph drag tools would be included (even if we didn't mention that explicitly) but I'll ping @philippjfr just to check...

**Comment by shaunswanson** [comment] 2017-06-28 08:47
@jlstevens @philippjfr 

How can I subscribe to an email notification when one or both of these features (click-drag for segment glyph generation, click-drag to reposition circle glyph) are completed and released? 

What related files in the repo are you two editing (as I wouldn't mind tinkering myself on the subject). Do your code edits involve custom BokehJS callbacks as per [this thread's suggestion](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/45RfxZWUBOg)? :)
