### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by cep87** [bokeh/bokeh#13484] opened 2023-10-25 08:19 UTC
### Software versions

Python version      :  3.11.3 | packaged by Anaconda, Inc. | (main, Apr 19 2023, 23:46:34) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.1.1
BokehJS static path :  C:\Users\cp1\AppData\Local\anaconda3\envs\elac-excon-console\Lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19045-SP0

### Browser name and version

Chrome Version 118.0.5993.89 (Official Build) (64-bit)

### Jupyter notebook / Jupyter Lab version

n/a

### Expected behavior

Expected the table displayed in the browser to update when the contents of the ColumnDataSource that is used as the source of the DataTable was updated. The update should be triggered using the trigger method from a periodic_update_callback.

### Observed behavior

The table only responds to the first update when the option autosize_mode="fit_columns" is included in the DataTable. All subsequent updates are ignored. The issue goes away when this option is removed.

### Example code

```Python
# Bokeh modules
from bokeh.models.layouts import Column
from bokeh.models.widgets import DataTable, TableColumn
from bokeh.models.layouts import Column
from bokeh.models import ColumnDataSource
from bokeh.application.handlers import FunctionHandler
from bokeh.application import Application
from bokeh.server.server import Server
from tornado.ioloop import IOLoop

class App():
    def __init__(self):
        # Test parameters
        self._ID = 0
        # Add data source
        self._source = ColumnDataSource(data={"Name": [],
                                              "ID": []})
        self._columns = [
            TableColumn(field="Name", title="Name"),
            TableColumn(field="ID", title="ID")
        ]
        # This definition of _logTable doesn't work
        self._logTable = DataTable(source=self._source, columns=self._columns,
                                   width=600, height=600, index_position=None, 
                                   autosize_mode="fit_columns")
        # This definition of _logTable works
        # self._logTable = DataTable(source=self._source, columns=self._columns,
        #                            width=600, height=600, index_position=None)
        # Build layout
        self.UI = Column(self._logTable)
        
    def UpdateApp(self):
        # Update entity tab
        cdata = self._source.data
        cdata["Name"].append("NewName{}".format(self._ID))
        cdata["ID"].append(self._ID)
        self._source.trigger('data', cdata, cdata)
        self._ID +=1
        
def get_doc(doc):
    app = App()
    doc.add_root(app.UI)
    doc.add_periodic_callback(app.UpdateApp, 2000)
    doc.title = 'Demo'

if __name__ == '__main__':
    io_loop = IOLoop.current()
    app = Application(FunctionHandler(get_doc))
    server = Server({'/Demo': app}, io_loop=io_loop)
    server.start()
    io_loop.add_callback(server.show, '/Demo')
    io_loop.start()
```

**Comment by bryevdv** [comment] 2023-10-31 23:41
@mattpap I think this is a duplicate?

**Comment by mattpap** [comment] 2023-11-17 16:52
This is a duplicate of issue #11557.

**Closed as completed by mattpap** 2023-11-17 16:52 UTC
Labels: reso: duplicate
