### ISSUE TITLE
Feature request: Title for DataTable

### ISSUE THREAD

**Issue by tony-bony** [bokeh/bokeh#8763] opened 2019-03-18 13:07 UTC
**Feature description:**

A `DataTable` is not always associated with plot data and can be used as stand-alone (no plots involved). In this case it would be useful if it had a `title` attribute like the `Plot` so it is clear which data is being presented. This would exclude the need for using Div or Paragraph for describing table contents

**Expected result:**

![Screen Shot 2019-03-18 at 14 08 46](https://user-images.githubusercontent.com/10279903/54532160-670f9d80-4987-11e9-90f9-45369e934bad.png)

**Comment by mattpap** [comment] 2019-03-18 13:57
This is a duplicate of issue #8047.

**Closed by mattpap** 2019-03-18 13:57 UTC
Labels: reso: duplicate, type: discussion
