### ISSUE TITLE
New added tool complains plot is already set when it isn't

### ISSUE THREAD

**Issue by copperwire** [bokeh/bokeh#3878] opened 2016-02-15 16:25 UTC
Hi! 

Might it be beneficial that the construction of Figure objects set that figure object that sets the tools plot attribute as that Figure? Such that the following code-snippet functions: 

    Tools = [TapTool(), BoxZoomTool(), BoxSelectTool(), PreviewSaveTool(), ResetTool()]
    figure(tools = Tools)

Without having to go by `.add_tools` or iterating over each tool and set `tool.plot = figure`

**Comment by birdsarah** [comment] 2016-02-17 18:13
@copperwire, this is how Bokeh currently works. Please see documentation here: http://bokeh.pydata.org/en/0.11.1/docs/user_guide/tools.html

If you are stuck trying to use this feature, please post to the public mailing list:
https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

I will close this issue for now, if you believe you have found a bug while using this feature, please do feel welcome to report it with:
a) a complete working example
b) description of what happened when running
c) description of what you expected to happen

Sincerely,

**Comment by copperwire** [comment] 2016-02-18 12:28
I posted a [question on the open group](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/IGYBeZIjrE0) where @bryevdv encouraged me to make this issue.

**Comment by bryevdv** [comment] 2016-02-18 14:16
@copperwire thanks for the issue, I think a subsequent post of yours actually uncovered a bug, and that was what i was referring to. I'll have to go back through my emails to get the specifics though.

**Comment by bryevdv** [comment] 2016-02-18 14:20
Here's the text from the messages;
```
I have an issue when specifying tools on a plot with a list  in the following way: 

    from bokeh.models import HoverTool, TapTool, BoxZoomTool, BoxSelectTool, PreviewSaveTool, ResetTool

     hover = HoverTool(
      tooltips=[
	     ("(x,y)", "($x, $y)"),
     ])

     Tools = [hover, TapTool(), BoxZoomTool(), BoxSelectTool(), PreviewSaveTool(), ResetTool()]


     figure_obj = figure(plot_width = 1000, plot_height = 800, title = "these are waves", tools = Tools)	

Which throws the following error

     ValueError: tool HoverTool, ViewModel:HoverTool, ref _id: 4c7b8138-3e8d-4e0d-8c91-062e91ddfe81 to be added already has 'plot' attribute set
```
That should work, since `HoverTool` does not already have the plot attribute set.

**Comment by copperwire** [comment] 2016-02-18 14:26
I figure I should mention that the problem persists its just a list of un-edited tools i.e

    Tools = [TapTool(), BoxZoomTool(), BoxSelectTool(), PreviewSaveTool(), ResetTool()]
    figure_obj = figure(tools = Tools)

In which case the error is more or less the same:
    `ValueError: tool TapTool, ViewModel:TapTool, ref _id: 36c0d4c0-79af-477b-abd0-2645854c3d08 to        be added already has 'plot' attribute set`


Sorry for not being clear in the original post!

**Comment by jeremybickerstaffe** [comment] 2016-06-28 16:57
I'm also having trouble with this in 0.11.1. This snippet of code reproduces the error.
```
from bokeh.plotting import figure, output_notebook, show
from bokeh.models import HoverTool, BoxSelectTool
output_notebook()

TOOLS = [BoxSelectTool(), HoverTool()]

p1 = figure(plot_width=400, plot_height=400, title=None, tools=TOOLS)
p2 = figure(plot_width=400, plot_height=400, title=None, tools=TOOLS)

p1.circle([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], radius=0.1, alpha=0.5)
p2.circle([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], radius=0.1, alpha=0.5)

show(p)
```

**Comment by birdsarah** [comment] 2016-07-11 12:22
@jeremybickerstaffe, that's not the same issue. Feel free to open a separate issue if you need to.

Regarding the original issue:

```python
I have an issue when specifying tools on a plot with a list  in the following way: 

    from bokeh.models import HoverTool, TapTool, BoxZoomTool, BoxSelectTool, PreviewSaveTool, ResetTool

     hover = HoverTool(
      tooltips=[
         ("(x,y)", "($x, $y)"),
     ])

     Tools = [hover, TapTool(), BoxZoomTool(), BoxSelectTool(), PreviewSaveTool(), ResetTool()]


     figure_obj = figure(plot_width = 1000, plot_height = 800, title = "these are waves", tools = Tools)    

Which throws the following error

     ValueError: tool HoverTool, ViewModel:HoverTool, ref _id: 4c7b8138-3e8d-4e0d-8c91-062e91ddfe81 to be added already has 'plot' attribute set
```

I cannot reproduce this, so closing. Apologies if I'm mistaken and there's another issue here - which at this point it may be clearer to start a new thread.

**Closed by birdsarah** 2016-07-11 12:22 UTC
Labels: type: bug

**Comment by jeremybickerstaffe** [comment] 2016-07-11 13:15
Apologies Sarah, I don't follow what you're saying. When I run my code above, what it's doing is adding some tools, first to plot p1, and then to plot p2. The error that arises (I'm now running 0.12) is:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-8c807a229ae2> in <module>()
      6 
      7 p1 = figure(plot_width=400, plot_height=400, title=None, tools=TOOLS)
----> 8 p2 = figure(plot_width=400, plot_height=400, title=None, tools=TOOLS)
      9 
     10 p1.circle([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], radius=0.1, alpha=0.5)

C:\Anaconda3\lib\site-packages\bokeh\plotting\figure.py in figure(**kwargs)
    556         del kwargs['responsive']
    557 
--> 558     fig = Figure(**kwargs)
    559     return fig
    560 

C:\Anaconda3\lib\site-packages\bokeh\plotting\figure.py in __init__(self, *arg, **kw)
     57 
     58         tool_objs, tool_map = _process_tools_arg(self, tools)
---> 59         self.add_tools(*tool_objs)
     60         _process_active_tools(self.toolbar, tool_map, active_drag, active_scroll, active_tap)
     61 

C:\Anaconda3\lib\site-packages\bokeh\models\plots.py in add_tools(self, *tools)
    262         for tool in tools:
    263             if tool.plot is not None:
--> 264                 raise ValueError("tool %s to be added already has 'plot' attribute set" % tool)
    265             tool.plot = self
    266             if hasattr(tool, 'overlay'):

ValueError: tool BoxSelectTool, ViewModel:BoxSelectTool, ref _id: 94344ade-fa8f-4649-bb55-c3695ad2b911 to be added already has 'plot' attribute set.

```

The title of this bug is: "New added tool complains plot is already set when it isn't"
And my error message is: "tool BoxSelectTool ... to be added already has 'plot' attribute set"

What's the difference?

**Comment by bryevdv** [comment] 2016-07-11 13:28
@jeremybickerstaffe this is no longer the behavior in `0.12`:
```
In [5]: from bokeh.plotting import figure

In [6]: from bokeh.models import HoverTool

In [7]: figure(tools=[HoverTool()])
Out[7]: <bokeh.plotting.figure.Figure at 0x1142b7198>

```

**Comment by jeremybickerstaffe** [comment] 2016-07-11 13:50
Yup, definitely 0.12
```
import bokeh
bokeh.__version__
'0.12.0'
```
A complete runnable test case is already above, see my earlier comment above with the text "This snippet of code reproduces the error."

**Comment by bryevdv** [comment] 2016-07-11 14:45
@jeremybickerstaffe Sorry this is a confusing issues. Your problem is indeed not the same as the original issue. The original issue referred to completely newly created tools mistakenly complaining with an error. 

Your case is different. You are trying to re-use *the same tool object* across two plots. This is simply not going to work. Instantiated tool objects have a reference back to the plot they are configured on. They can only be associated with at most one plot. This is why tools can be configured using strings as a convenience, e.g.:
```
figure(tools="pan,save,reset")
```
In this case Bokeh creates new tools for each figure on your behalf behind the scenes.

**Comment by bryevdv** [comment] 2016-07-11 14:47
For reference, I tend to use the strings for most everything, and if there are any specific tools that need special configuration, then do something like:
```
p.circle(x, y, size=20, tools="pan,reset,save")

p.add_tools(HoverTool(tooltips=None, renderers=[cr], mode='hline'))
```

**Comment by jeremybickerstaffe** [comment] 2016-07-11 14:55
Thanks, makes more sense now.
