### ISSUE TITLE
[BUG] add_periodic_callback doesn't seem to work properly for callback chaining

### ISSUE THREAD

**Issue by hrbigelow** [bokeh/bokeh#13068] opened 2023-04-06 08:16 UTC
### Software versions

Python version      :  3.9.4 | packaged by conda-forge | (default, May 10 2021, 22:13:33) 
IPython version     :  7.23.1
Tornado version     :  6.1
Bokeh version       :  3.1.0
BokehJS static path :  /home/henry/miniconda3/envs/pytorch181/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  v16.19.1
npm version         :  8.19.3
Operating system    :  Linux-5.4.0-146-generic-x86_64-with-glibc2.31

### Expected behavior

I see no reason why the `driver` function shown in the code example below can't be attached via `add_periodic_callback`, but it does work when attached with `add_next_tick_callback`.

However, I am fairly novice with async programming.  Any ideas would be appreciated.

### Observed behavior

The figure appears as expected only when I attach `driver` using `add_next_tick_callback`.  When I attach it with `add_periodic_callback` or `add_timeout_callback`, I don't see the figure appear in the webpage, despite that the `init_page` message appears in stdout.

### Example code

```Python
# bokeh serve test-server.py
# test-server.py
from bokeh.io import curdoc
from bokeh.plotting import figure
from functools import partial

def init_page(doc):
    print('in init_page')
    fig = figure(width=1500, height=600, title='bla')
    doc.add_root(fig)

def driver(doc):
    doc.add_next_tick_callback(partial(init_page, doc))

doc = curdoc()

# works - I see the figure rendered in the webpage
doc.add_next_tick_callback(partial(driver, doc))

# fails - I can see the 'in init_page' messages printed to stdout,
# but the webpage is blank indefinitely
# doc.add_periodic_callback(partial(driver, doc), 3000)
# doc.add_timeout_callback(partial(driver, doc), 3000)
```

**Comment by bryevdv** [comment] 2023-04-06 18:06
I think this is actually a dupe of https://github.com/bokeh/bokeh/issues/12628 and the problem is that the real issue is that `add_root` is currently  broken for "dynamic" (post-init) usage. 

Edit: almost certainly, since the callbacks can be seen to be getting invoked

**Closed as completed** 2023-04-06 20:28 UTC
Labels: reso: duplicate
