### ISSUE TITLE
Updating data source in a periodic_callback will make the toolbar unresponsible [BUG]

### ISSUE THREAD

**Issue by ruoyu0088** [bokeh/bokeh#9323] opened 2019-10-24 05:11 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Windows 10, Chrome 77, Python 3.7, Bokeh 1.3.4

#### Description of expected behavior and the observed behavior

Updating data source in a periodic_callback will make the toolbar unresponsible. Maybe the same problem as #8833.

#### Complete, minimal, self-contained example code that reproduces the issue

Here is an example, I can solve the problem by using a gridplot to wrap the figure.

```python
import numpy as np
from bokeh.io import show, curdoc
from bokeh.models import ColumnDataSource, Button
from bokeh.layouts import column
from bokeh.plotting import figure
from bokeh.layouts import gridplot

def app(doc):
    p = 0
    x = np.linspace(0, 4*np.pi, 300)
    y = np.sin(x + p)
    source = ColumnDataSource(dict(x=x, y=y))
    fig = figure(height=200, width=400)
    line = fig.line("x", "y", source=source)
    
    def update():
        nonlocal p
        p += 0.05
        y = np.sin(x + p)
        source.data = dict(x=x, y=y)
    
    doc.add_periodic_callback(update, 0.1)
    button = Button(label="hello")
    button.on_click(update)
    #doc.add_root(column(button, gridplot([[fig]]))) # comment out this line to solve the problem.
    doc.add_root(column(button, fig))
    
app(curdoc())
```

#### Stack traceback and/or browser JavaScript console output

I found that the `PlotView.paint()` method calls `ToolbarPanelView.render()`, and `ToolbarPanelView.render()` calls `empty(this.el)` to clear the toolbar and then append all the tool buttons again.

If I wrap the figure with gridplot, `ToolbarPanelView.render()` is not called.

Maybe Chrome on Windows can't process mouse click correctly on elements that remove & append periodically.

Can use only clear `this.el` only there are some changes on the toolbar model?

**Comment by bryevdv** [comment] 2019-10-24 15:12
@ruoyu0088 AFAICT this is definite a duplicate of #8833

**Closed by bryevdv** 2019-10-24 15:12 UTC
Labels: TRIAGE
