### ISSUE TITLE
HBox not working properly with plots

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#2284] opened 2015-05-13 15:29 UTC
Here is an example ( http://nbviewer.ipython.org/urls/gist.githubusercontent.com/jakirkham/f354d21bf36725bde9bc/raw/mandelbrot_image_notebook.ipynb ). This also happens with the static HTML version ( http://nbviewer.ipython.org/urls/gist.githubusercontent.com/jakirkham/f354d21bf36725bde9bc/raw/mandelbrot_image.ipynb ). See the static HTML rendered here ( http://htmlpreview.github.io/?https://gist.githubusercontent.com/jakirkham/f354d21bf36725bde9bc/raw/bc7c0ffcdb9890f0fe05af9f5796f45cb2418419/image.html )

**Comment by bryevdv** [comment] 2015-05-13 16:27
Should be fixed https://github.com/bokeh/bokeh/pull/2276

**Comment by jakirkham** [comment] 2015-05-13 16:29
Oh, wow! Ok, let me take a look

**Comment by jakirkham** [comment] 2015-05-13 16:37
First off, this seems to work. Thanks.

Second, how do you normally go about installing a development version with bokeh? Normally, I have been doing the standard `python setup.py develop`. However, this doesn't seem to work great with the building of BokehJS. So, do you just build a new conda package for each version or something else?

**Comment by bryevdv** [comment] 2015-05-13 16:40
Dev build installs described here:

http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

Building for source is more involved, it is described here :+1: 

http://bokeh.pydata.org/en/latest/docs/dev_guide/building.html#devguide-building

**Comment by jakirkham** [comment] 2015-05-13 17:32
It was just surprising that `python setup.py develop --uninstall` triggers a build of BokehJS. Maybe this could be checked for to avoid this unnecessary building.

**Comment by bryevdv** [comment] 2015-05-13 17:51
Sure, that sounds like a reasonable thing. The `setup.py` is pretty complicated unfortunately, and it's entirely possible no-one has ever actually tried `--uninstall`

**Comment by jakirkham** [comment] 2015-05-13 17:55
Cool, glad to hear you are onboard. Unfortunately, that seems to be the nature of all `setup.py`s. I can try to work on some changes to address this and maybe you could give me some feedback.

**Comment by bryevdv** [comment] 2015-05-13 17:55
That would be great!

**Comment by birdsarah** [comment] 2015-05-14 06:57
Hi,

The first thing to note is that, I believe, HBox and VBox have been
deprecated in favor of hplot and vplot.

However, I have seen this behavior for both HBox and hplot.

This will work:

show(HBox(VBox(p1), VBox(p2)))

(You can also see how i've done the same pattern here:
http://nbviewer.ipython.org/github/birdsarah/pycon_2015_bokeh_talk/blob/master/notebooks/Building%20the%20static%20visualization.ipynb
- see In: [30])

I will investigate and file a bug, if one hasn't been filed.

Hope this helps,

Sarah Bird

**Comment by birdsarah** [comment] 2015-05-14 07:30
Sorry, I'm reading my emails in the wrong order and while sick! As you've seen this is already fixed.

Sorry for the noise.

**Comment by jakirkham** [comment] 2015-05-20 20:11
Yeah, so, the original HBox problem seems to have resurfaced. I am on the breaking edge namely ( bokeh/bokeh@480614f09c6bb7c5c0970beb3dfbe3aaffc34e1e )

**Comment by bryevdv** [comment] 2015-05-20 20:18
`hplot` is just a wrapper around `HBox`. Can you provide a minimal example code? The latest changes were to get `HBox` working for all the examples and docs we have. FWIW I am not sure our current simplistic layout system can be made to work in all cases. We are looking at integrating something like PhosphorJS for much more robust layout facilities but that is a more medium term prospect.

**Comment by jakirkham** [comment] 2015-05-20 20:36
Ah ok, well, I just figured I should check if the point were raised. Yes, no problem ( http://nbviewer.ipython.org/github/jakirkham/bokeh_examples/blob/master/Bokeh_Example_9.ipynb ). This is based off an existing example ( http://bokeh.pydata.org/en/latest/docs/user_guide/interaction.html ) just in the iPython notebook.

**Comment by bryevdv** [comment] 2015-05-20 20:38
side note: @damianavila what's up with that `__version__`?

**Comment by jakirkham** [comment] 2015-05-20 20:39
Oh, I was going to mention something about the version. Are you guys using versioneer or do you have another way of keeping track of it? I know that old iterations of versioneer were not PEP440 compliant. However, that has changed in version 0.14.

**Comment by bryevdv** [comment] 2015-05-20 20:43
@fpliger I can reproduce this in the notebook, probably some interaction with the notebook JS/CSS I am not sure we can fix it in one place and not have it break in another.

@jakirkham We do use versioneer bu not *just* versioneer. We layer on some additional cases to name and support our dev builds. Worth looking at 0.14 though for sure.

**Comment by jakirkham** [comment] 2015-05-20 20:45
Ah ok, yeah, I remember seeing the `versioneer` file, but it looked like something else was happening, as well.

**Comment by bryevdv** [comment] 2015-05-20 21:05
@jakirkham I can't reproduce that weird version on either a conda or pip installed bokeh on OS X. How did you install?

**Comment by jakirkham** [comment] 2015-05-20 21:08
Ah yes, installed in develop mode `python setup.py develop`.

**Comment by bryevdv** [comment] 2015-05-20 21:39
hmm weird not seeing that on a `setup.py develop` either!

**Comment by jakirkham** [comment] 2015-05-20 22:42
Interesting, are you using the same commit I am or is it different?

**Comment by fpliger** [comment] 2015-05-21 08:59
@jakirkham  @bryevdv IIRC all static examples were working correctly with hplot/HBox but there was a notebook where hplot was not (and was not a quick fix). Sorry, it seems that I missed to create an issue for that.

@jakirkham as a temp workaround you you can still use gridplot instead. It should work correctly.

**Comment by damianavila** [comment] 2015-05-21 14:33
> side note: @damianavila what's up with that __version__?

not sure...someone could reproduce it??

**Comment by jakirkham** [comment] 2015-05-21 15:03
@damianavila, I see this when installing via `python setup.py develop` with this commit ( bokeh/bokeh@480614f09c6bb7c5c0970beb3dfbe3aaffc34e1e ) if that helps.

**Comment by guillochon** [comment] 2015-12-14 03:07
I can't see the examples in the OP, but for me the issue is that an hplot call within file_html does not result in the plots being placed in the same row, they instead appear in the same column. The workaround of wrapping a vplot around the hplot seems to fix the issue. Is this the same issue as OP?

**Comment by bryevdv** [comment] 2015-12-14 03:59
@guillochon I'm not sure but it's probably worth mentioning that the existing layouts are somewhat simplistic and fragile, in the near future we will be re-implementing our layout (and adding new options) using the excellent PhosphorJS library.

**Comment by birdsarah** [comment] 2016-05-28 16:31
Confirm as part of #4392

**Comment by birdsarah** [comment] 2016-06-15 12:04
hplot is now gone. HBox has been replaced with Row (although will likely be restored as a synonym: https://github.com/bokeh/bokeh/issues/4496).

Confirmed that Row correctly displays in notebook and in file.

Fixed in #4343.

**Closed by birdsarah** 2016-06-15 12:04 UTC
Labels: type: bug

**Comment by birdsarah** [comment] 2016-06-15 12:10
@jakirkham, thanks for your persistence, and for the cool code, I made a code-post out of your example while testing this was fixed: http://bokeh-cookbook.github.io/blog/2016/06/15/image_n_image_rgba_plot/ (the post was a notebook before it became a post, you can check out the notebook here: http://nbviewer.jupyter.org/github/bokeh-cookbook/bokeh-cookbook/blob/master/content/articles/2016/06/image%20%26%20image_rgba%20plot.ipynb)
