### ISSUE TITLE
[BUG] Unexpected behavior while svg export using level 'overlay'

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#10381] opened 2020-08-06 13:20 UTC
#### Software version info (bokeh, python)

Python: 3.6.10
Bokeh: 2.1.1

#### Description of expected behavior and the observed behavior
If a svg file is generated using bokeh there will be two files created. There was an issue for this alrady (talking about bokeh 2.1.1) : [#10273](https://github.com/bokeh/bokeh/issues/10273)
This problem is connected to the one mentioned before, because if a figure has different layers, not all the data is stored in the same file. The example below uses two different `LabelSet`s, one with the `level='underlay'` and one with `level='overlay'`. After the export to svg the data of the second `LabelSet` is stored separately in a file with the same name as the first one with a suffix "_1" right before the file extension.
It was expected that both layers appear in the same svg export.

#### Minimal Example
This example generates two files named 'Labels.svg' and  'Labels_1.svg'. The second file contains the data of the variable 'labels_2'.
```
from bokeh.io import show, export_svgs
from bokeh.models import ColumnDataSource, LabelSet
from bokeh.plotting import figure, output_notebook

output_notebook()

# the figure
p = figure(x_range=(0, 4), y_range=(0,3), plot_height=300, tools='' )

# some data
source = ColumnDataSource(dict(x=range(1,4), y_1=[1]*3, y_2=[2]*3, names=['a', 'b', 'c'], color_1=['green']*3, color_2=['red']*3))
# plot data as circle
p.circle(x='x', y='y_1', color='color_1', radius=0.3, alpha=0.3, source=source)
p.circle(x='x', y='y_2', color='color_2', radius=0.3, alpha=0.3, source=source)

# add arrow
labels_1 = LabelSet(x='x', y='y_1', text='names', level='underlay', text_align='center',
                  x_offset=0, y_offset=-8, source=source, render_mode='canvas')
labels_2 = LabelSet(x='x', y='y_2', text='names', level='overlay', text_align='center',
                  x_offset=0, y_offset=-8, source=source, render_mode='canvas')
p.add_layout(labels_1)
p.add_layout(labels_2)
show(p)

p.output_backend = "svg"
export_svgs(p, filename ='Labels.svg')
```

#### Screenshots
This is the html output in a jupyter notebook:
![grafik](https://user-images.githubusercontent.com/68053396/89534218-e3ad5100-d7f4-11ea-9393-39c68f76616f.png)

This is a screenshot of 'Labels.svg':
![Labels](https://user-images.githubusercontent.com/68053396/89536253-ea899300-d7f7-11ea-80da-5adf5521032a.png)
And this is a screenshot of 'Labels_1.svg':
![Labels_1](https://user-images.githubusercontent.com/68053396/89536267-ed848380-d7f7-11ea-935a-4c2f210f7dbf.PNG)

**Comment by mattpap** [comment] 2020-08-06 13:29
Duplicate of issue #10273.

**Closed by mattpap** 2020-08-06 13:29 UTC
Labels: TRIAGE
