### ISSUE TITLE
Add generic/simpler way for CustomJS to trig Python-side events

### ISSUE THREAD

**Issue by JEGBergqvist** [bokeh/bokeh#8728] opened 2019-03-07 19:06 UTC
Add generic/simpler way for CustomJS to trig Python-side events and vice versa

Using Bokeh v.1.0.4.

For functionality not covered by the Bokeh framework, I find it from time to time crucial to put additional HTML/CSS into a Bokeh Div-object. This works well and have saved me several times. However, I have not found a good way to have e.g. JS code trigger a Python-side event in the corresponding Python Model object. 

My current workaround is to have an invisible Div (0x0 pixels) at the end of the layout, and insert some dummy string into its text attribute, which is catchable Py-side using js_on_change to set up a callback at the layout creation phase. However, this is cumbersome and breaks the encapsulation of the actual GUI-element, usable as a last resort to be sure, but easily gets error-prone in terms of fragile code.

**Suggestion:**
- Simple syntax for events between JS and Py, e.g.:
    - ToMyModel("This is an event JS->Py to my corresponding Model");
    - self.ToMyImpl("This is an event Py->JS to my HTML DOM implementation")
- Simplify extensions:
    - my_div_path=self.GetMyImplDiv(); print("My Div's place in your browser DOM: "+my_div_path)

Of course, any custom extension of Bokeh leads to non-standard solutions in some respect, and should be avoided if there is explicit support for whatever feature is needed. But it seems to me at least a few special cases tend to pop up in most projects, which tends to be unnecessarily hard to implement manually using CSS/JS/HTML5. A few simple helper functions would go a long way, I think.

**Comment by bryevdv** [comment] 2019-03-07 19:12
> Add generic/simpler way for CustomJS to trig Python-side events and vice versa

@JEGBergqvist Unless I am mistaken about what you a, this is a duplicate of https://github.com/bokeh/bokeh/issues/5983

**Closed by bryevdv** 2019-03-07 19:12 UTC

**Comment by JEGBergqvist** [comment] 2019-03-07 19:13
Wow, that was fast! I was not even done writing the issue! :-)

**Comment by bryevdv** [comment] 2019-03-07 19:15
For my own sanity, I try to clear things that can be cleared very quickly, very quickly :) 

FWIW I think #5983 would be extremely valuable but I'm not sure when we will have resources to implement it, offhand. It might make a nice GSOC project but it's too late for this year I think (and we have no mentor capacity at the moment)

**Comment by JEGBergqvist** [comment] 2019-03-07 19:18
Yes, #5983 is very much related.

**Comment by JEGBergqvist** [comment] 2019-03-07 19:41
@bryevdv 
I understand the resource situation. Regarding #5983 I am a little worried as it sounds like the approach is quite profound. Although targeting the same kind of problem, my suggestion would be to keep it simple. If the client-side DOM path is known to the Py-Model, and something along the lines of: 

- JS->Py: Button's on_click could be moved to the DOMLayout or Model level (like on_change) it would cover most cases where Custom JS->Py is needed.
- Py->JS: Add a very simple and generic function to fire away some arbitrary JS code to be executed immediately (i.e. next tick) client-side. As long as each Model have a string identifying its (usually Div) HTML path, it would be simple to adapt the custom JS accordingly.
- Alternatively, the HTML "top" element for each corresponding Model could get a uniq identifier during the creation phase, to be easily accessible in the "immediate JS code" using a GetElementByName-like function.

Introducing a major new communication framework inspired by Cobra would be very interesting, but I would happily settle for something simpler. Use case: "As a Model, I want to be able to execute JS right now targeted at "my place in the browser". :-)

**Comment by bryevdv** [comment] 2019-03-07 20:01
> If the client-side DOM path is known to the Py-Model,  

It's definitely not known, and making it known would be a huge undertaking To be honest, I don't understand how this relates to things at all. 

> JS->Py: Button's on_click could be moved to the DOMLayout or Model level

The muddies the semantics of `on_click` I would be -1 on making `on_click` cover non-clicks

> Add a very simple and generic function to fire away some arbitrary JS code

> Use case: "As a Model, I want to be able to execute JS right now targeted at "my place in the browser", just tell me where and I'll go to the right place and do my stuff". :-)

This is exactly #5983 (as is the opposite direction) which is intended to be as simple as possible (CORBA is only mentioned as a reference point for framing the discussion)

**Comment by JEGBergqvist** [comment] 2019-03-07 21:14
> > If the client-side DOM path is known to the Py-Model,
> It's definitely not known, and making it known would be a huge undertaking To be honest, I don't understand how this relates to things at all.
===> Explanation: If it the DOM tree _would have been known_, JS from a Model at runtime could have found its corresponding element client-side, i.e. _not_ being routed by the framework to the right element = no Bokeh changes in that respect. Not elegant, but very quick, IF the dom would have been known. Since it is not, scratch that suggestion, obviously not feasible.

JS->Py: Button's on_click could be moved to the DOMLayout or Model level
The muddies the semantics of on_click I would be -1 on making on_click cover non-clicks
===> Clarification: Absolutely, on_click should _definitely not_ mean anything other than a user click event. Very much agreed indeed, and not intended at all. I'll try to be more precise: What I have found by using Bokeh extensively for some time now is that when I find myself lacking simple communication JS->Py is almost always some component _other than buttons_ that would need a on_click (like some custom Div taking up some screen area). As for the text, that was just a nice-to-have, like a hint, but that's not important if it does not sit well with the framework. 

This is exactly #5983 (as is the opposite direction) which is intended to be as simple as possible (CORBA is only mentioned as a reference point for framing the discussion)
===> I see. Thanks for the explanation. 


Since the DOM is not for Python-side Bokeh to know, could the "tags" attribute, if specified, be included at the browser side elements? It could serve as a (very-) last-resort to let any JS find whatever element. It's not intended (not usable, not advisable) for most of the GUI layout. It is only intended as a slightly-less-dirty helper in situations where tweaking is really required, typically domain-specific special cases not covered by Bokeh.
