### ISSUE TITLE
Ordering of grouped bars in bokeh.charts Bar

### ISSUE THREAD

**Issue by tobyhodges** [bokeh/bokeh#2935] opened 2015-10-01 13:26 UTC
I've been updating my scripts to take advantage of the improved charts interface in 0.10 and can't figure out how to control the order of grouped bars. I've checked the documentation/tutorials but couldn't find any information on this, sorry if I've missed it. Can someone point me in the right direction please?

Here is an example of the kind of data that I'm working with, where I'm plotting numbers for consecutive years. As you can see from the plot, I can't get the grouped bars to be arranged in the same order as the years are listed in the legend. 

```
from bokeh.charts import Bar, output_file, show
import pandas as pd

data = pd.DataFrame({'Group' :['A','A','A','A','B','B','B','B','C','C','C','C','D','D','D','D'],
                     'Year'  :['2009','2010','2011','2012','2009','2010','2011','2012','2009','2010','2011','2012','2009','2010','2011','2012'],
                     'Height':[1,2,3,4,2,2,2,2,3,0,3,0,4,3,2,1]})
fig = Bar(data, label='Group', values='Height', group='Year', legend='top_right')
output_file('chartsBarTest.html')
show(fig)
```

![chartstest](https://cloud.githubusercontent.com/assets/9694524/10221647/ef9bcd58-684f-11e5-9712-6316a93831d0.png)

**Comment by damianavila** [comment] 2015-10-02 14:22
Duplicate of #2924, let's continue the discussion there...

**Comment by fpliger** [comment] 2015-12-23 19:11
This is actually a different issue then #2924 .. the order of the category axis labels is already supported but honestly the order of the grouping is not... even explicitly specifying `group=CatAttr(columns=['Year'], sort=True)` and `color=ColorAttr(columns=['Year'], sort=False)` 

ping @rothnic in case I'm missing any internals..

**Comment by fpliger** [comment] 2015-12-23 19:17
pinging @ahothan here since you've mentioned you are having the same issue. Please feel free to provide any example to demonstrate your use case. This would probably be very helpful..

**Comment by ahothan** [comment] 2015-12-23 21:59
@fpliger here is a small example that shows the problem.

from bokeh.charts import Bar
from bokeh.charts import show
from bokeh.charts import output_notebook
from pandas import DataFrame
dc = {
    'count': {0: 772, 1: 2243, 2: 101, 3: 1833, 4: 2058, 5: 100, 6: 2236, 7: 1836, 8: 100, 9: 4387, 10: 93}, 
    'group': {0: '18x24', 1: '18x24', 2: '18x24', 3: '06x110', 4: '06x110', 5: '06x110', 6: '05x113', 7: '05x113', 8: '05x113', 9: '02x215', 10: '02x215'}, 
    'task_name': {0: 'ASA.01.vcpu0', 1: 'CSR.01.vcpu0', 2: 'WSA.01.vcpu0', 3: 'ASA.01.vcpu0', 4: 'CSR.01.vcpu0', 5: 'WSA.01.vcpu0', 6: 'ASA.01.vcpu0', 7: 'CSR.01.vcpu0', 8: 'WSA.01.vcpu0', 9: 'ASA.01.vcpu0', 10: 'WSA.01.vcpu0'}
}

df = DataFrame(dc)
print df

p = Bar(df, label='task_name', values='count', group='group',
        legend='top_right',
        tools="resize,hover,save")
output_notebook()
show(p)

And the output looks like:
<img width="563" alt="screen shot 2015-12-23 at 1 56 20 pm" src="https://cloud.githubusercontent.com/assets/4954645/11985769/08f20ea2-a97d-11e5-9624-80d255d9323a.png">

So the legend order is alphabetical (02, 05, 06, 18) and the order in each group has it at 02, 05, 18, 06
I think it would be much better to have the order in each group to be same as the legend (by default).
In my case I need to show the progression of count values based on a certain order, so having a different order is actually pretty bad for me.

**Comment by ahothan** [comment] 2015-12-23 22:01
Any workaround (with 0,10) to fix this order would be great...

**Comment by rothnic** [comment] 2015-12-25 18:27
Just wanted to mention that I enumerated each method of sorting a chart attribute in the [attributes deep dive](https://notebooks.anaconda.org/nroth/deep-dive-attributes) in pr #3417.

I'm definitely interested in hearing how the behavior should be by default. This won't work in 0.10 or master as I had to make some small modifications to make sure things worked as intended.

@fpliger, I'll have to take a look at your manual use, because the sort=False should turn the sorting off. It may be the global sorting of the dimensions that need to be disabled. The thing that makes this one a little strange is that a stacked bar chart really utilizes nested dimensions, and there isn't explicit support for that.

I think the stacked bar example of the Olympic medals uses a lot of the manual sorting control, so might be worth checking that.

**Comment by Kurt-von-Laven** [comment] 2016-07-29 00:19
I believe I am hitting this issue in bokeh 0.12.0 as well. Has anyone come across a workaround by chance since the earlier discussion?

**Comment by Kurt-von-Laven** [comment] 2016-07-29 00:48
I finally realized I could use http://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.sort_values.html (e.g., `data.sort(group, inplace=True)`) to control the order in which the groups are presented in the chart. I can't promise this works in all cases, but it seemed to solve my problem.

**Comment by Maggie-M** [comment] 2017-04-27 17:49
moved to [bkcharts repo](https://github.com/bokeh/bkcharts/issues/41)

**Closed by Maggie-M** 2017-04-27 17:49 UTC
Labels: type: discussion
