### ISSUE TITLE
Setting language on NumeralTickFormatter produces errors

### ISSUE THREAD

**Issue by danaki** [bokeh/bokeh#3673] opened 2016-01-17 20:03 UTC
```
    p = figure(plot_width=800, plot_height=600, title="Year vs Price", webgl=True)
    p.yaxis[0].formatter = NumeralTickFormatter(format="0,0 $", language="ru")
    p.scatter(x, y, alpha=0.5)
```

produces "Uncaught TypeError: Cannot read property 'delimiters' of undefined"

and this chunk:

```
    p = figure(plot_width=800, plot_height=600, title="Year vs Price", webgl=True)
    p.yaxis[0].formatter = NumeralTickFormatter(format="0 $", language="fr")
    p.scatter(x, y, alpha=0.5)
```

produces "Uncaught TypeError: Cannot read property 'currency' of undefined"

also tried for "fr-ch", "es" etc

```
$> conda list bokeh
# packages in environment at /Users/yuri/anaconda2/envs/bb:
#
Could not find an activated virtualenv (required).
# Warning: subprocess call to pip failed
bokeh                     0.11.0                   py27_1    defaults
```

**Comment by birdsarah** [comment] 2016-01-21 23:10
@danaki, I'm not sure it's the language that's the problem.

Can you try just `format="$0"` and then if that works `format="$0", language="fr"` and report back.

**Comment by danaki** [comment] 2016-01-22 16:38
Just `format="$0"` produces no error and "$100000-like" marks, but `format="$0", language="fr"` gives "Uncaught TypeError: Cannot read property 'currency' of undefined"

Actually what I want to achieve is to have Euro-signs instead of $ (like in "fr") locale keeping everything else in English + "," inside big numbers. I've checked out Numeral.JS sources and it seems impossible to achieve (or by introducing own hybrid locale which is stupid).

**Comment by birdsarah** [comment] 2016-01-23 01:45
This is a bug, sorry @danaki.

The error I get in the console is `TypeError: language is undefined` with the error coming from inside the numeraljs code: 

          if (d.split('.')[1].length) {
                d = language.delimiters.decimal + d.split('.')[1];
            } else {
                d = '';
            }

maybe we're not passing language correctly to numeraljs. We've had other problems with numeral js and I believe we were planning on replacing it, but that may have stalled for some reason.

The work around is a little cumbersome but should work - it's to use a Custom Model - see an example here: https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/custom_datetime_axis.py

**Comment by garth-wells** [comment] 2016-10-26 14:35
Is this bug being worked on? From my tests, I do not get an error but cannot get a currency symbol other than '$'.

**Comment by bryevdv** [comment] 2017-07-13 18:05
Can someone provide a *complete*, minimal test case? That would go a long way towards getting this looked at in detail.

**Comment by leokury** [comment] 2018-01-31 19:29
Here is a minimal example.  Any value we put in language argument always get same currency symbol result and no error is displayed.

```
df = pd.DataFrame(MSFT)[:51]
inc = df.close > df.open
dec = df.open > df.close

p = figure(plot_width=1000, title="MSFT Candlestick with Custom X-Axis")


p.yaxis[0].formatter = NumeralTickFormatter(format="$0.00a", language='pt-br')
p.xaxis.bounds = (0, df.index[-1])
p.x_range.range_padding = 0.05

p.segment(df.index, df.high, df.index, df.low, color="black")
p.vbar(df.index[inc], 0.5, df.open[inc], df.close[inc], fill_color="#D5E1DD", line_color="black")
p.vbar(df.index[dec], 0.5, df.open[dec], df.close[dec], fill_color="#F2583E", line_color="black")

show(p)
```

**Comment by bryevdv** [comment] 2018-01-31 19:38
I believe this is a dupe of https://github.com/bokeh/bokeh/issues/7477

Basically, we do not ship Numbro's languages files by default as that would add over half a megabyte to the size of the library. If you need this you will have to include those files from CDN manually. I am closing this issue in favor of this other one, which is clearly about better documenting how that might be done.

**Closed by bryevdv** 2018-01-31 19:38 UTC
Labels: type: bug
