### ISSUE TITLE
[BUG] hover disappears

### ISSUE THREAD

**Issue by kanglcn** [bokeh/bokeh#13511] opened 2023-11-04 19:54 UTC
### Software versions

Python version      :  3.10.13 | packaged by conda-forge | (main, Oct 26 2023, 18:07:37) [GCC 12.3.0]
IPython version     :  8.17.2
Tornado version     :  6.3.3
Bokeh version       :  3.3.0
BokehJS static path :  /users/kangl/miniforge3/envs/work/lib/python3.10/site-packages/bokeh/server/static
node.js version     :  v20.2.0
npm version         :  9.6.6
Operating system    :  Linux-5.15.0-47-generic-x86_64-with-glibc2.35

### Jupyter notebook / Jupyter Lab version

jupyterlab                4.0.8              pyhd8ed1ab_0    conda-forge

### Expected behavior

Hover should exist and show the detailed data of the point in jupyterlab.

### Observed behavior

But it doesn't appear. However, if save the plot to html, it does exist.

### Example code

```Python
# this code is from bokeh doc
from bokeh.plotting import ColumnDataSource, figure, output_file, show
from bokeh.io import output_notebook
output_notebook()
# output_file("toolbar.html")

source = ColumnDataSource(data=dict(
    x=[1, 2, 3, 4, 5],
    y=[2, 5, 8, 2, 7],
    desc=['A', 'b', 'C', 'd', 'E'],
))

TOOLTIPS = [
    ("index", "$index"),
    ("(x,y)", "($x, $y)"),
    ("desc", "@desc"),
]

p = figure(width=400, height=400, tooltips=TOOLTIPS,
           title="Mouse over the dots")

p.circle('x', 'y', size=20, source=source)

show(p)
```

### Screenshots

In saved html: 
![image](https://github.com/bokeh/bokeh/assets/62387227/d12158cd-3615-443e-a904-760df13ef7c8)

In jupyterlab:
![image](https://github.com/bokeh/bokeh/assets/62387227/f9f980dd-82ff-4b0d-bd35-ecb7c1a1dfa5)

**Comment by bryevdv** [comment] 2023-11-04 21:44
Might be dupe of / related to https://github.com/bokeh/bokeh/issues/13428

@kanglcn please try again with 3.3.1 when it is released in the next few days.

**Comment by kanglcn** [comment] 2023-11-04 21:56
@bryevdv OK. Thanks for your quick reply.

**Comment by bryevdv** [comment] 2023-11-04 23:11
Let's keep it open until it's verified to be fixed in the new release or not

**Comment by bryevdv** [comment] 2023-11-09 21:57
@kanglcn 3.3.1 is now released, can you test things out and report back?

**Comment by kanglcn** [comment] 2023-11-12 03:53
Hi @bryevdv , sorry for this late reply.
After updating to 3.3.1, the hover is showed now but at wrong place. See the attached screenshort:
![image](https://github.com/bokeh/bokeh/assets/62387227/4d997e0e-3d66-4168-b1a5-4364827112c8)

**Comment by bryevdv** [comment] 2023-11-16 17:15
@kanglcn does this problem only occur in notebooks? If so, is there any difference across different jupyter versions?

**Comment by mattpap** [comment] 2023-11-16 17:48
The version in the notebook is still 3.3.0.

**Comment by bryevdv** [comment] 2023-12-07 19:08
@kanglcn As noted, in your last screenshot, the version is still 3.3.0:

<img width="392" alt="Screenshot 2023-12-07 at 11 05 47" src="https://github.com/bokeh/bokeh/assets/1078448/b5104bd0-32a1-4604-8f90-1a60d86b2c30">

Can you re-try with 3.3.2 and confirm the version? If not we will have to close this as `norepro` For reference, it's working as expected for me on the 3.4 "dev" branch:

<img width="450" alt="Screenshot 2023-12-07 at 11 07 41" src="https://github.com/bokeh/bokeh/assets/1078448/a8b07c06-f418-43d9-9260-c91ddb787c4b">

**Comment by kanglcn** [comment] 2023-12-07 23:08
I am so sorry that I forget to answer you. With bokehJS 3.3.1, everything works perfect.

I don't know why my above post still use bokehJS 3.3.0.
When I plot that figure, I launch jupyter-lab in my base conda environment which has bokeh 3.3.0 installed.
But the notebook runs in a conda environment with bokeh 3.3.1 installed with the help of a package called [nb_conda_kernels](https://github.com/Anaconda-Platform/nb_conda_kernels).
Did I plot with bokeh 3.3.0 in the base environment in such case? If so, is there any workaround about it?

**Comment by bryevdv** [comment] 2023-12-11 21:15
In general, a notebook will use whatever version was loaded when the notebook was saved. If necessary, you can restart the kernel and "clear all output cells" if to "unload" BokehJS.

**Closed as completed by bryevdv** 2023-12-11 21:15 UTC
Labels: type: discussion
