### ISSUE TITLE
[BUG] Boxannotation not working in 3.3

### ISSUE THREAD

**Issue by matteoquirino** [bokeh/bokeh#13517] opened 2023-11-08 08:55 UTC
### Software versions

Python version      :  3.9.18 (main, Sep 11 2023, 13:41:44) 
IPython version     :  (not installed)
Tornado version     :  6.3.3
Bokeh version       :  3.3.0
BokehJS static path :  /home/utente/miniconda3/envs/hermes-tvac-plot/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.15.0-88-generic-x86_64-with-glibc2.31

### Expected behavior

Boxannotation layout to insert boxes

### Observed behavior

Boxannotation is not working, the box is not rendered, also in the userguide page is not rendered.

### Example code

```Python
import numpy as np
from bokeh.plotting import figure, show
from bokeh.models import ColumnDataSource, BoxAnnotation

# Time vector
dt_nonop = 7
dt_plateau = 3
dt_op = 6
dt_rise = 2
n_cylces = 3

# Non op
t = [0,
	 dt_nonop,
	 dt_nonop + dt_plateau,
	 dt_nonop + dt_plateau + dt_nonop,
	 dt_nonop + dt_plateau + dt_nonop + dt_plateau,
	 dt_nonop + dt_plateau + dt_nonop + dt_plateau + dt_op]

# Op
for i in range(n_cylces):
	t.append(t[-1] + dt_plateau)
	t.append(t[-1] + dt_rise)
	t.append(t[-1] + dt_plateau)
	t.append(t[-1] + dt_op)
	t.append(t[-1] + dt_plateau)
	t.append(t[-1] + dt_rise)
	t.append(t[-1] + dt_plateau)
	t.append(t[-1] + dt_op)

# Tbal
t[-1] = t[-1] - 3
t.append(t[-1] + 6)
t.append(t[-1] + dt_rise)
t.append(t[-1] + 6)
t.append(t[-1] + 3)
t.append(t[-1] + dt_rise)
t.append(t[-1] + 6)
t.append(t[-1] + 3)

print(t)
print(len(t))

# Temperatures
T_max_nonop = 60
T_max_op = 55
T_min_nonop = -15
T_min_op = -10
T_on = 30
T_bal_low = 0
T_bal_high = 35
dT_rise = 20

# Nonop
T = [20,
	 T_max_nonop,
	 T_max_nonop,
	 T_min_nonop,
	 T_min_nonop,
	 T_on]

# Op
for i in range(n_cylces):
	T.append(T_on)
	T.append(T_max_op)
	T.append(T_max_op)
	T.append(T_min_op)
	T.append(T_min_op)
	T.append(T_min_op + dT_rise)
	T.append(T_min_op + dT_rise)
	T.append(T_on)

# Tbal
T[-1] = T_bal_low
T.append(T_bal_low)
T.append(T_bal_low + dT_rise)
T.append(T_bal_low + dT_rise)
T.append(T_bal_high)
T.append(T_bal_high + dT_rise)
T.append(T_bal_high + dT_rise)
T.append(20)

print(T)
print(len(T))

# Create dictionaries

data_source = {'t': t,
			   'T': T,
			   'index': list(range(len(T)))}

source = ColumnDataSource(data=data_source)

print(data_source)
########################################################################################################################
# PLOT
########################################################################################################################

# Figure set up
p = figure(width=1200, height=400)

# add a line renderer
p.line(t, T, line_width=2)

# Non operative range
dT_tol = 5
box_nonop_high = BoxAnnotation(top=T_max_nonop + 5,
							   bottom=T_max_nonop,
							   fill_alpha=1,
							   fill_color='red')

p.add_layout(box_nonop_high)

show(p)
```

**Comment by mattpap** [comment] 2023-11-08 08:59
This is a duplicate of issue #13432.

**Closed as completed by mattpap** 2023-11-08 08:59 UTC
Labels: reso: duplicate
