### ISSUE TITLE
Selections only work on the last of two series in one plot

### ISSUE THREAD

**Issue by bald** [bokeh/bokeh#2136] opened 2015-04-01 15:34 UTC
If a plot contains multiple series of data, only selections (`box_select` or `tap`) on the second have an effect on the plot, selection data points of the first series does nothing. Both series share the same data source.
### Selection on the second series (green)

![screenshot](https://cloud.githubusercontent.com/assets/574252/6944163/b48fcff4-d892-11e4-9b1f-630c5ec8a5b3.png)
### Selection on the first series (blue)

![screenshot](https://cloud.githubusercontent.com/assets/574252/6944176/c7ca2aa6-d892-11e4-88e5-f3d1abe1cb54.png)
### Code

Here is the example code:

```
import bokeh.plotting as bk
bk.output_file("example.html",)
chartData = {"name": [1, 2, 3],
                     "number": [0.5, 1, 1.5],
                     "number2": [1.5, 2, 2.5]}
df = bk.ColumnDataSource(data = chartData)
p = bk.figure(title = "selection", tools = "tap,box_select")
p.circle(x = "name", y = "number", source = df)
p.circle(x = "name", y = "number2", color = "green", source = df)
bk.show(p)
```

Bokeh 0.8.2
Python 3.4.3

**Comment by bald** [comment] 2015-04-07 09:04
Same problem with Bokeh 0.9 dev

**Comment by bald** [comment] 2015-05-21 11:49
Same problem with Bokeh 0.9.0rc.62565432

**Comment by seanlaw** [comment] 2016-07-27 15:23
Has this issue been resolved yet?

**Comment by bryevdv** [comment] 2016-07-27 15:51
Yes it is fixed in master and the latest release candidate.

**Comment by damianavila** [comment] 2016-07-28 17:00
@bryevdv do you know which PR  or commit solved this one?

**Comment by bryevdv** [comment] 2016-07-28 17:06
#4856

**Comment by bryevdv** [comment] 2016-07-28 17:07
Oh, wait, I may have issues mixed up, I thought this was the "selections don't work on last point" issue...

**Comment by bryevdv** [comment] 2016-07-28 17:09
My apologies, this still seems to be open. Very similar wording to another issue.

**Comment by mattpap** [comment] 2016-08-26 15:11
This is a fundamental design issue around selections (and inspections) when glyphs share a data source. In this case, `for` loop in `TapToolView._tap()` overrides selection which each next glyph, so as indicated in the issue, only last added glyph works under selection. The problem is that a data source can hold only indices and not glyph to indices mapping. Currently I'm not sure how such change would effect the rest of bokehjs. Note that we can't simply take union of all selections, because this would select erroneous indices for earlier glyphs.

**Comment by bryevdv** [comment] 2016-08-26 15:17
Actually I don't think it would be erroneous. The precise, exact point of sharing a data source is to share selections: if an an earlier glyph has item 10 selected that means all glyphs that share the date source should have item 10 selected. It should not be erased because the next glyph in the loop happens to select item 15 as well.

**Comment by bryevdv** [comment] 2016-08-26 15:18
I do think the selections dict needs to be overhauled, and become a real model, with some minimal (perhaps read-only) deprecated view that reproduces the current section object. But to fix this immediately, I think coalescing all the selections from all the renderers, across the loop, is the quickest and also the correct thing to do.

**Comment by bryevdv** [comment] 2017-03-24 17:34
I was thinking some more on this. I think there are actually a couple of considerations:

* when selections *are* shared, the behavior needs to be better and better defined

* sometimes users want to share sources, but not share selections

I think we can fix this by leaving the current selection manager intact. It does a nice job a decoupling responsibilities by coordinating tools, sources, and selectors. For the first bullet, we just need to implement better merging and maintain it under test. 

For the second, I think an approach might be this: selection managers create a default `Selector` that it used as it currently is for linked selections. But glyphs can be (optionallY) configured to have their own selector, in which case they do not share selections, even if they share a source with other glyphs.

**Comment by clairetang6** [comment] 2017-04-26 00:32
I've encountered this issue working on the CDS subsets and have an idea of one way to fix it (at least the first bullet point). I agree with @bryevdv that the default behavior should be that there is one selection for each data source which is shared across all glyph renderers that use that data source. 
The problem with the implementation in the selection manager right now is that `.select` is called for each renderer and during that call, each renderer's selector is used to set the selection on the data source, overwriting a selection that may have occurred during the same "selection event" (e.g. a box select event on a plot with multiple renderers). 

One solution would be to have the `.select` method on the selection manager be called with all of the renderers associated with the data source that it is associated with. Then, you could union the indices within the one call to select and set the data source's selected property with that. 

The second bullet point also can be split into two cases:

1. users only want some renderers to be part of the selection event. In this case, setting the renderers for a tool to use should work as there would still just be one selection for the data source. 

2. users want multiple selections per data source. This could be done, but maybe they should just use separate data sources then. The semantics of having one selection per data source seems to me to be a pretty good one.

**Comment by clairetang6** [comment] 2017-04-26 15:32
Related issue [5044](https://github.com/bokeh/bokeh/issues/5044): Shift selection currently doesn't work across plots because the union happens for each renderer individually. Having the union happen for the group of renderers with the same CDS would fix both issues.

**Closed** 2017-05-16 14:20 UTC
Labels: type: bug
