### ISSUE TITLE
Any Chinese charactor in script will cause bokeh serve error.

### ISSUE THREAD

**Issue by gafeng** [bokeh/bokeh#7613] opened 2018-03-09 03:13 UTC
# READ AND FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and
technical assistance, come ask the [Bokeh mailing list](https://groups.google.com/a/continuum.io/forum/#!forum/bokeh) or join the chat on [Gitter](https://gitter.im/bokeh/bokeh). For feature requests, please provide a detailed description or proposal of the new capability or behavior.

For defects or deficiencies, please provide ALL OF THE FOLLOWING:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

>\>bokeh -v
0.12.13

>\>python -V
Python 3.6.4

>OS: Windows 10

#### Description of expected behavior and the observed behavior

Any Chinese charactor in script will cause bokeh serve error.

>\>bokeh serve --show mainGUI_bokeh.py
ERROR:'gbk' codec can't decode byte 0xaa in position 1387: illegal multibyte sequence

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks
tab_set = Panel(child=widgetbox(p), title="设置")
```

#### Stack traceback and/or browser JavaScript console output

I have inspected the code and found following change will fix this issue:
```
# bokeh\application\handlers\script.py:87
# origin: with open(filename, 'r') as f:
with open(filename, 'r', encoding="utf-8") as f:
```

**Comment by bryevdv** [comment] 2018-03-09 20:31
@gafeng can you submit a small PR with that change so that we can try to evaluate it more thoroghly?

**Comment by iAmGhost** [comment] 2018-03-21 08:30
Someone tried same fix but rejected since it causes an error on Python 2.7(see pull request #7305).

My workaround is wrapping code like below, it works on 0.12.14 without touching anything:

### main.py
```python
import main_script

main_script.main()
```

### main_script.py
```python
# -*- coding: utf-8 -*-
from random import random

from bokeh.layouts import column
from bokeh.models import Button
from bokeh.palettes import RdYlBu3
from bokeh.plotting import figure, curdoc


def main():
    # create a plot and style its properties
    p = figure(x_range=(0, 100), y_range=(0, 100), toolbar_location=None)
    # ...
    button = Button(label="한글 버튼")
    curdoc().add_root(column(button, p))
```

**Comment by gafeng** [comment] 2018-05-03 07:43
@bryevdv following the correct solution from #7272 , I tried the statement:
`with io.open(filename, 'r', encoding='utf8') as f:`
For python 3.6.4, it works.
For python 2.7.14, the script.py works fine, but 

> Invalid syntax in "mainGUI_bokeh.py" on line 0:
None
Traceback (most recent call last):
  File "D:\ProgramData\Anaconda3\envs\py27\lib\site-packages\bokeh\application\handlers\code_runner.py", line 76, in __init__
    nodes = ast.parse(source, path)
  File "D:\ProgramData\Anaconda3\envs\py27\lib\ast.py", line 37, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "C:\Users\gfeng\CAST\mainGUI_bokeh.py", line 0
SyntaxError: encoding declaration in Unicode string

Seems python ast doesn't support unicode.

**Comment by bryevdv** [comment] 2018-05-11 02:08
I believe this is actually a dupe of #7272 so I will close this one. I will say I am simply not sure there is a solution to support Python 2 here, and we may simply have to advise anyone needing this to work that only Python 3 is supported.

**Closed by bryevdv** 2018-05-11 02:08 UTC
