### ISSUE TITLE
[BUG] output_notebook() fails to render in Jupyter Lab

### ISSUE THREAD

**Issue by ned2** [bokeh/bokeh#10039] opened 2020-05-19 09:44 UTC
Bokeh version: 2.0.2
Jupyter Lab version: 2.1.2
OS: Ubuntu 19.10
Browser: Chrome
I have installed both Jupyer labextensions as described [here](https://docs.bokeh.org/en/latest/docs/user_guide/jupyter.html#jupyterlab).

When I run one of the bokeh gallery visualisations in a notebook in Jupyer Lab (modified to use `open_notebook()` ) Bokeh fails to render, displaying the following message: 

    Javascript Error: Cannot read property 'kernels' of undefined

The developer tools console shows me the following two errors which I've also attached the logs of.

![Screenshot from 2020-05-19 19-40-35](https://user-images.githubusercontent.com/2831640/82311239-c85a5300-9a08-11ea-81d4-c26d1ddbc72a.png)

Here's the example that's I'm running:

```python
import numpy as np

from bokeh.io import output_notebook, show
from bokeh.models import HoverTool
from bokeh.plotting import figure

n = 500
x = 2 + 2*np.random.standard_normal(n)
y = 2 + 2*np.random.standard_normal(n)

p = figure(title="Hexbin for 500 points", match_aspect=True,
           tools="wheel_zoom,reset", background_fill_color='#440154')
p.grid.visible = False

r, bins = p.hexbin(x, y, size=0.5, hover_color="pink", hover_alpha=0.8)

p.circle(x, y, color="white", size=1)

p.add_tools(HoverTool(
    tooltips=[("count", "@c"), ("(q,r)", "(@q, @r)")],
    mode="mouse", point_policy="follow_mouse", renderers=[r]
))

output_notebook()

show(p)
```

[localhost-1589881097035.log](https://github.com/bokeh/bokeh/files/4649532/localhost-1589881097035.log)
[localhost-1589881088103.log](https://github.com/bokeh/bokeh/files/4649533/localhost-1589881088103.log)

**Comment by ned2** [comment] 2020-05-19 10:45
Update, after installing the labexstension described in the [Holoviews setup page](https://holoviews.org/user_guide/Installing_and_Configuring.html), it's now rendering:

    jupyter labextension install @pyviz/jupyterlab_pyviz

**Comment by philippjfr** [comment] 2020-05-19 15:46
That's very odd, the PyViz extension should not interact with the Bokeh extension in any way.

**Comment by bryevdv** [comment] 2020-05-20 04:42
With just those two lab extensions installed on the same version of jlab:
```
(202) ❯ jupyter labextension list
JupyterLab v2.1.2
Known labextensions:
   app dir: /Users/bryan/anaconda/envs/202/share/jupyter/lab
        @bokeh/jupyter_bokeh v2.0.1  enabled  OK
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
```
I am unable to repro any issue on OSX on either Chrome or Safari wth Bokeh 2.0.2:

<img width="1281" alt="Screen Shot 2020-05-19 at 9 39 39 PM" src="https://user-images.githubusercontent.com/1078448/82405696-7a9a1680-9a19-11ea-88c9-d175416501e5.png">

**Comment by bryevdv** [comment] 2020-05-20 04:54
For good measure I fired up a Ubuntu VM and tried there as well:

<img width="1192" alt="Screen Shot 2020-05-19 at 9 51 19 PM" src="https://user-images.githubusercontent.com/1078448/82406237-f2b50c00-9a1a-11ea-9c18-2909629cec01.png">

@ned2 my guess is that this was some transient labextension issue and that the extensions were not actually built/activated. The messages above are consistent with the extensions not being used at all because they are not present. I am going to go ahead and close this as `norepro` since you also have things working now. if you can find any way to reliably reproduce this we can certainly re-open but also please check the labextension list to make sure the extensions are reported as active.

**Closed by bryevdv** 2020-05-20 04:54 UTC
Labels: TRIAGE
