### ISSUE TITLE
[BUG] Databable cannot be put in Dialog

### ISSUE THREAD

**Issue by Latill** [bokeh/bokeh#13915] opened 2024-05-27 13:06 UTC
### Software versions

Python version : 3.9.2 (default, Feb 28 2021, 17:03:44)
IPython version : 7.20.0
Tornado version : 6.3.3
Bokeh version : 3.4.1

### Browser name and version

Chrome or Edge

### Expected behavior

** This is not a Duplicate from #13912 **

You cannot put a Datatable within a Dialog.

### Observed behavior

you get a js error 

bokeh-tables.min.js?…081989ac1c17dd81:93 
 Uncaught (in promise) Error: SlickGrid Cannot find stylesheet.
    at getColumnCssRules (bokeh-tables.min.js?…ac1c17dd81:93:41250)
    at applyColumnWidths (bokeh-tables.min.js?…ac1c17dd81:93:52454)
    at updateCanvasWidth (bokeh-tables.min.js?…ac1c17dd81:93:20576)
    at reRenderColumns (bokeh-tables.min.js?…ac1c17dd81:93:51180)
    at legacyAutosizeColumns (bokeh-tables.min.js?…ac1c17dd81:93:51076)
    at autosizeColumns (bokeh-tables.min.js?…ac1c17dd81:93:46127)
    at resizeCanvas (bokeh-tables.min.js?…ac1c17dd81:93:67947)
    at finishInitialization (bokeh-tables.min.js?…ac1c17dd81:93:13246)
    at init (bokeh-tables.min.js?…ac1c17dd81:93:12751)
    at new SlickGrid (bokeh-tables.min.js?…c1c17dd81:93:103242)

### Example code

```Python
from datetime import date
from random import randint
import numpy as np

from bokeh.layouts import column
from bokeh.models import Button, Dialog, OpenDialog
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource, InlineStyleSheet
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn, Div


show_Dialog = Button(label="Show Dialog")



data = dict(
        dates=[date(2014, 3, i+1) for i in range(10)],
        downloads=[randint(0, 100) for i in range(10)],
    )
source = ColumnDataSource(data)
columns = [
        TableColumn(field="dates", title="Date", formatter=DateFormatter()),
        TableColumn(field="downloads", title="Downloads"),
    ]
data_table = DataTable(source=source, columns=columns, width=400, height=280)



dialog = Dialog(
    title="test",
    content=column(data_table)
)
show_Dialog.js_on_click(OpenDialog(dialog=dialog))


layout = column([
    show_Dialog,
    Div(text="test"),
])



curdoc().add_root(layout)
```

### Stack traceback or browser console output

bokeh-tables.min.js?…081989ac1c17dd81:93 
 Uncaught (in promise) Error: SlickGrid Cannot find stylesheet.
    at getColumnCssRules (bokeh-tables.min.js?…ac1c17dd81:93:41250)
    at applyColumnWidths (bokeh-tables.min.js?…ac1c17dd81:93:52454)
    at updateCanvasWidth (bokeh-tables.min.js?…ac1c17dd81:93:20576)
    at reRenderColumns (bokeh-tables.min.js?…ac1c17dd81:93:51180)
    at legacyAutosizeColumns (bokeh-tables.min.js?…ac1c17dd81:93:51076)
    at autosizeColumns (bokeh-tables.min.js?…ac1c17dd81:93:46127)
    at resizeCanvas (bokeh-tables.min.js?…ac1c17dd81:93:67947)
    at finishInitialization (bokeh-tables.min.js?…ac1c17dd81:93:13246)
    at init (bokeh-tables.min.js?…ac1c17dd81:93:12751)
    at new SlickGrid (bokeh-tables.min.js?…c1c17dd81:93:103242)

**Comment by mattpap** [comment] 2024-05-27 15:12
This is a duplicate of issue https://github.com/bokeh/bokeh/issues/13787.

**Closed as completed by mattpap** 2024-05-27 15:12 UTC
Labels: reso: duplicate

**Comment by Latill** [comment] 2024-05-27 16:05
Ah yes indeed, sorry for the duplicate.
