### ISSUE TITLE
pandas-compat.ipynb example doesn't render dates properly

### ISSUE THREAD

**Issue by jreback** [bokeh/bokeh#3045] opened 2015-10-31 17:22 UTC
Straight from the [docs](https://github.com/bokeh/bokeh/blob/master/examples/compat/pandas/pandas.ipynb)

under ``bokeh 0.10.0``

http://nbviewer.ipython.org/gist/jreback/33c51dae1e0e599708fa

date rendering seems broken

**Comment by bryevdv** [comment] 2015-10-31 22:57
dupe of https://github.com/bokeh/bokeh/issues/2973  (PR in flight)

**Closed by bryevdv** 2015-10-31 22:57 UTC
Labels: reso: duplicate
