### ISSUE TITLE
Changing tile provider does not remove attribution

### ISSUE THREAD

**Issue by sida-wang** [bokeh/bokeh#11413] opened 2021-07-08 04:40 UTC
In reference to a [previous topic](https://discourse.bokeh.org/t/how-to-update-the-tile-provider-in-bokeh-server-plot-without-overlapping-the-plot/4640) on changing tile providers from the community support discourse, I noticed that the attribution in the bottom right hand corner is not removed when changing the TileRender which leads to the attributions stacking on top of each other.

Screenshot of the issue
![image](https://user-images.githubusercontent.com/42928828/124863222-1316a000-dffa-11eb-8279-7a5fe0afa0a6.png)

MWE below
```
from bokeh.plotting import figure
from bokeh.layouts import column
from bokeh.tile_providers import get_provider
from bokeh.models.renderers import TileRenderer
from bokeh.io import curdoc
from bokeh.models import RadioButtonGroup

#dictionary of TileRenders
tiles = {'Cartodb': TileRenderer(tile_source=get_provider('CARTODBPOSITRON')),
         'Esri': TileRenderer(tile_source=get_provider('ESRI_IMAGERY')),
         }

tile_labels = list(tiles.keys())

#callback
def tile_select_cb(new):
    p.renderers[0] = tiles[tile_labels[new]]

#widget for changing tiles
tile_selector = RadioButtonGroup(labels=tile_labels, active=0)
tile_selector.on_click(tile_select_cb)


p = figure(x_range=(-2000000, 6000000), y_range=(-1000000, 7000000),
           x_axis_type="mercator", y_axis_type="mercator")
p.renderers.append(tiles['Cartodb'])

layout = column(tile_selector, p, name='layout')
curdoc().add_root(layout)
```

This was run on a bokeh server using the following (assuming above is in mwe.py)
```
bokeh serve --show mwe.py --allow-websocket-origin='*'
```
I’m allowing the websocket origins due to running this on an Amazon EC2 Linux instance.

Bryan's response from the [community support post](https://discourse.bokeh.org/t/changing-tile-provider-does-not-remove-attribution/8102/2):
>Looking at `tile_renderer.ts` it seem like perhaps old attributions are not cleaned up or removed. So this seems like a bug. Please file a GitHub Issue with these details.

**Comment by tcmetzger** [comment] 2021-07-13 20:24
Thanks for opening this issue, @sida-wang! 
@IuryPiva and I have been able to reproduce the behavior (win10, Bokeh branch-2.4). This looks like something that would need to be fixed in `tile_renderer.ts`, as @bryevdv already pointed out.

**Comment by IuryPiva** [comment] 2021-07-13 20:29
<img width="469" alt="image" src="https://user-images.githubusercontent.com/26139868/125520240-53fd07e6-5539-4147-a11d-2406b03b8476.png">
I think we just need to add some logic to not repaint if the attribution is gone, we would add this logic to the `tile_renderer.ts` just after the code above

**Comment by brendancol** [comment] 2021-07-17 19:20
@IuryPiva seems like maybe the attribution element needs to be removed in a cleanup method

**Closed** 2021-08-17 11:16 UTC
Labels: type: bug, reso: completed, tag: component: bokehjs, tag: geo
