### ISSUE TITLE
DatePicker rendering is working but needs improvement

### ISSUE THREAD

**Issue by jbrambleDC** [bokeh/bokeh#4977] opened 2016-08-17 19:54 UTC
Attached is an example screenshot. I would be glad to help, but I suspect this is a CSS issue which is not my strong suit. 

<img width="306" alt="screen shot 2016-08-17 at 3 53 45 pm" src="https://cloud.githubusercontent.com/assets/6984748/17750935/ddcf4ccc-6492-11e6-84a6-377974b0c197.png">

**Comment by birdsarah** [comment] 2016-08-18 00:29
duplicate of #4503

**Closed** 2016-08-18 00:29 UTC
Labels: reso: duplicate
