### ISSUE TITLE
Cannot select tools in certain examples

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#7484] opened 2018-02-01 16:42 UTC
In current bokeh master selecting tools does not work in certain examples, specifically the problem can be seen in ``./examples/apps/selection_histogram.py`` when trying to select a tool other than the default pan tool.

I've tried bisecting the history to figure out what was causing it and the bisect points to this commit: https://github.com/bokeh/bokeh/commit/2b7ec420b091987840d8bfbde38af7e13cac1661 I currently have no idea how that commit could possibly be responsible for this issue but  so I double checked that the commit before it indeed works fine.

**Comment by jlstevens** [comment] 2018-02-01 17:19
Damn. As a regression, I think this is a priority to fix before the next release - if it can be fixed without waiting too long for a suitable bokeh release (if there is no other workaround).

**Comment by bryevdv** [comment] 2018-02-01 17:23
No ifs, this must be fixed for the next release.

**Comment by bryevdv** [comment] 2018-02-01 18:01
The problem is these lines from that PR:
```
     for (const name in x_ranges) {
       const rng = x_ranges[name];
       this.connect(rng.change, () => this.set_data())
     }

     for (const name in y_ranges) {
       const rng = y_ranges[name];
       this.connect(rng.change, () => this.set_data())
     }
```
which are also breaking #7475

**Closed** 2018-02-01 19:47 UTC
Labels: tag: regression, type: bug
