### ISSUE TITLE
Ability to edit rects by moving their vertices

### ISSUE THREAD

**Issue by meassinal** [bokeh/bokeh#11245] opened 2021-05-07 04:07 UTC
Currently `BoxEditTool` cannot allow to edit the size of the rects. What I can do with this tool is that I only draw, drag, or delete.  

It will be more useful and good user experience if the tool allows the edit by moving their vertices and the resized shape should be by width and height respectively.

**Comment by philippjfr** [comment] 2021-05-07 05:50
Thanks for your suggestion.This looks to be a duplicate of https://github.com/bokeh/bokeh/issues/8521 though so I'm going to close.

**Closed by philippjfr** 2021-05-07 05:50 UTC
Labels: TRIAGE
