### ISSUE TITLE
Plots break when replacing widgets using bokeh server

### ISSUE THREAD

**Issue by dantamont** [bokeh/bokeh#7303] opened 2017-12-08 18:42 UTC
Hello all, I am running bokeh version 12.11 from Spyder (Python 2.7), and am experiencing a strange error.  I have a GUI layout where I am replacing some spacers with widget boxes, and it ends up breaking the plots that I have in the layout.  I've attached some pictures that show the weirdness.  Sorry about the black boxes, can't reveal my secrets~

To replace widgets in the layout, I am using the following line:

```
layout.children[widget_row].children[widget_column] = widget
```

, since the layout children object is a list of rows, each of which has the children contained in the row.  As a side note, I am not making any changes to the plots at all.   Just updating some of the row entries that show up in the middle column of the GUI.

Update:  I added some more spacers to the GUI, and now only the bottom-right plot is experiencing weirdness, but it is absolutely unclear as to what is making the plots look strange or how to go about fixing them.

Second Update:  I have tried both the latest version of bokeh as well as the latest developer build, and both have this issue.  Interestingly, when I run the bokeh server, it says "Starting Bokeh server version 0.12.5", which I assume is an outdated version?  Not sure why it doesn't match my version of bokeh.

Before changing layout:
![bugs2](https://user-images.githubusercontent.com/27838575/33780129-7f404888-dc04-11e7-8fad-a2cadf15c07c.png)
After:
![bugs1](https://user-images.githubusercontent.com/27838575/33780126-7c402b1c-dc04-11e7-9d16-f6a6f04d3102.png)

**Comment by bryevdv** [comment] 2017-12-13 15:45
>  it says "Starting Bokeh server version 0.12.5", which I assume is an outdated version? Not sure why it doesn't match my version of bokeh.

 If it is printing `0.12.5` at startup, that's definitely the version that is running. Do you have multiple virtualenvs or conda envs? If so you are probably running bokeh from a different environment than you are intending (one with the older version installed). There are still plenty of issues, but there has been *alot* of layout work done since 0.12.5. So the first thing is that you would need you to figure out your local system path issues and confirm that your code has the problem with current Bokeh (`0.12.13 at this time).  Then, if it is still a problem with recent versions, we absolutely must have a *complete minimal example* to reproduce the problem. 

I am going to close this for now, if you determine that the problem does exist in recent versions and an provide an MRE we can certainly re-open.

**Closed by bryevdv** 2017-12-13 15:45 UTC
