### ISSUE TITLE
How to deploy 3rd party components to Bokeh

### ISSUE THREAD

**Issue by volkerjaenisch** [bokeh/bokeh#7094] opened 2017-10-24 00:20 UTC
We wrote some 3rd party components for Bokeh. A leaflet map component for instance. We would like to give these components back to the community.

But how?

I suppose we agree that it is no good idea to put 3rd party code in the Bokeh.core code. 
We have build Bokeh widgets/extensions but we have no clue how to deploy them independently.

We would like to get some pointers on how to deploy our Bokeh widget python/coffee code to fit into a python package to be deployed via pypi or anaconda.

**Comment by bryevdv** [comment] 2017-10-24 15:27
This is a dupe of https://github.com/bokeh/bokeh/issues/5108 One of the two issues should be closed. That discussion petered out, so I'm not sure if it would be better to try to start fresh. Let me know which one to close and I will do that. 

FWIW my opinion has changed somewhat. I had somewhat grand ideas about something similar to the browser or atom/sublimetext plugin managers. But it would take a team of people and resources to implement them, and that I don't have. So absent a group of folks stepping up and volunteering to take this on, I am happy to consider any reasonable, much simpler proposals (that will still require collaboration and help, and realistically, someone else in the driver's seat). 

My only basic thought is this: I don't think we should collect actual code in a single repo or anything like that. At most there could be a "contrib" repo that collects links and meta data about plugins. I also have no more opinions about whether or what package manager to rely on.

**Comment by volkerjaenisch** [comment] 2017-10-24 21:41
Sorry for producing a dupe. Did not found it.
I can truly understand your bad feelings toward plugins. I am involved in the Zope/Plone community where there are standards and a defined infrastructure for plugins also supported by buildout as a deloyment tool. Plugins in Zope/Plone also profit from zope.interfaces which makes it possible to define clean interfaces for e.g. plugins to dock. There are paster like tools to bootstrap a complete Plone plugin https://docs.plone.org/develop/addons/bobtemplates.plone/README.html .
Without such well defined measures for a plugin infrastructure one will end where django currently struggles with lots of incompatible plugins. Also an active community contributing lots of plugins is nice, but without organisational force there will be rank growth. The Zope/Plone community has different repositories for different strength of code as well as a maintained set of know good tools called the Zope-Toolkit. One repository at Zope corporation containg the "industrial strength" core components. Then there is the "collective" repository which contains packages and plugins contributed from the community and maintained by a group of volunteers. And then there are lots of homebrewn packages/plugins living simply at PyPI or github without an organized maintenance.
I will not state that this solution is perfect nor that Bokeh/Plugins may be organized in the same fashion. But if one decides to build something new it is good to learn from others who have faced the problems, already.
On the other hand one can start discussing this topic over and over to find the perfect solution but in the end did not get any things done. 
If I get you right there was never the intention to build a plugin system around Bokeh, at all. Bokeh should be the "one layer to rule them all" and on this layer all Bokeh programs should be build. So if we like to have a plugin system some parts (of which I have no clue) at the core infrastructure of Bokeh will have to change to enable something like plugins at all, firsthand. I do not think that I am capable to do this. But I volunteer to write the first plugin that uses a prototypish plugin interface (builded by someone else) and do the testing. We can probably use our leaflet map Bokeh component for this.
After we got the first rudimentary plugin interface up and running we will have learned a lot and then can design the final plugin interface based on this knowledge.

**Comment by bryevdv** [comment] 2017-10-24 22:13
> If I get you right there was never the intention to build a plugin system around Bokeh, at a

This isn't quite right I don't think. I definitely have thought for a long time that having Bokeh be extensible is critically important as a "relief mechanism" for users that need things beyond the core library. And I have also thought that a clear way to define, share, search, and install these extensions would magnify their value. I'd call those "plugins" I suppose. My previous thoughts were that simply it would be far simpler to mandate that plugins not depend on *other plugins*. Given that, there is no "dependency problem", at least not *between plugins*, because plugins can only depend on Bokeh (or other third party python libs maybe). In the simples case, "installing" plugins could just mean copying code to the `.bokeh/extensions` dir or something. To me that seemed to strike a good balance between capability and complexity. But others disagree, and thing that allowing plugins to depend on one another is important. And if that's the case, OK, but then there would need to be a decision about an official package manager, because then there would absolutely be a "dependency problem" to solve.

**Comment by volkerjaenisch** [comment] 2017-10-25 08:07
Sorry for having you misunderstood. I am new to this discussions and may have not got all the relevant discussions.
Your proposed method "copying code to the .bokeh/extensions dir" for plugins is IMHO hindering true modularity. 
Would it be possible to define a plugin as a python package containing python code (myplugin.py) as well as JS code (myplugin.js/myplugin.css) and utilizing some sort of "binding" Bokeh code to build and register itself to Bokeh. The plugin binding itself then can be realized by simply putting a symlink to the package root into .bokeh/extensions.
The user then is responsible to deliver the JS part (nginx, etc.). While the binding code assures that e.g. the autoload.js generated code includes script/CSS links to the myplugin.js/myplugin.css.

**Closed** 2018-03-16 21:58 UTC
Labels: reso: duplicate, type: discussion
