### ISSUE TITLE
Hard dependency on numpy

### ISSUE THREAD

**Issue by elyase** [bokeh/bokeh#1280] opened 2014-10-06 23:26 UTC
According to the documentation Bokeh shouldn't have a hard dependency on numpy and should work only with python lists. I installed bokeh in a virtualenv with the `--no-deps` option, no numpy is installed inside the environment. When I try to import something from bokeh I get:

```python
>>> from bokeh.plotting import *
Traceback (most recent call last):
  File "testbokeh.py", line 7, in <module>
    from bokeh.plotting import *
  File "/Users/yaser/.virtualenvs/testenv/lib/python2.7/site-packages/bokeh/plotting.py", line 13, in <module>
    from . import _glyph_functions as gf
  File "/Users/yaser/.virtualenvs/testenv/lib/python2.7/site-packages/bokeh/_glyph_functions.py", line 2, in <module>
    from . import glyphs
  File "/Users/yaser/.virtualenvs/testenv/lib/python2.7/site-packages/bokeh/glyphs.py", line 1, in <module>
    from .properties import Align, Bool, DataSpec, Enum, HasProps, Size, Any, Color
  File "/Users/yaser/.virtualenvs/testenv/lib/python2.7/site-packages/bokeh/properties.py", line 16, in <module>
    import numpy as np
ImportError: No module named numpy
```
Steps to reproduce:
```
$ mkvirtualenv testenv
(testenv)$ pip install bokeh --no-deps
(testenv)$ pip install six python-dateutil
(testenv)$ python
>>> from bokeh.plotting import scatter

**Comment by scottlawton** [comment] 2015-04-18 16:40
This item is still flagged as Open, so perhaps a comment from an outsider is ok.

While Numpy is awesome for many things, it's overkill for many other tasks -- and does impose installation challenges. So, partial functionality would be great, and 'naive pure-python reimplementation' even better. e.g. I've used this statlib for many years: https://code.google.com/p/python-statlib/

**Comment by bryevdv** [comment] 2015-04-18 19:30
@scottlawton absolutely, there is no lack of desire for this from anyone afaik, only lack of time/resources to get it done at the moment. To be clear, we have decided to make Pandas a dependency of `bokeh.charts` because many charts involve groupy/split-apply-combine and statistical and time-series transformations, and reproducing that machinery is far too much wheel reinvention. But `bokeh.plotting` and `bokeh.models` should not require NumPy, and actually should be pretty close to NumPy-free even now:
```
bryan@laptop (git:feature/2174_callback) ~/work/bokeh/bokeh $ grep numpy *.py |grep import
mpl.py:import numpy as np
mpl_helpers.py:import numpy as np
plotting_helpers.py:import numpy as np
properties.py:import numpy as np
properties.py:        import numpy as np
protocol.py:import numpy as np
```

**Comment by damianavila** [comment] 2015-04-20 12:00
>There's also a question of how to handle optional dependencies. Installing NumPy, Pandas, etc. is trivial with conda, so maybe we have full dependencies for conda packages and a more limited set of dependencies for sdists.

I don't like the asymmetries, but it is true that the triviality introduced by conda is difficult to reproduce with sdists, so I guess the proposal is reasonable at the end.

**Comment by matthiasha** [comment] 2015-11-11 05:26
There are some strange version dependencies from the pandas windows wheel. It requires a specific version of numpy (1.8.1 currently). The scipy wheel requires a different version of the numpy wheel. I currently made a bokeh-0.10.0 wheel where I removed the pandas dependency line. It seems to work very well for my use cases. Would be happy to see it removed in future versions.

**Comment by bryevdv** [comment] 2015-11-11 12:12
Pandas is definitely an optional dependency (really only required for `bokeh.charts`) and should be removed from the default list of dependencies. What needs to replace it tho is very specific messages to install it in cases where it is needed. 

Regarding NumPy I am not so sure anymore. Although users themselves may or may not use NumPy I am not sure it can be easily extricated from internal Bokeh usage.

**Comment by bryevdv** [comment] 2015-11-11 12:16
FYI:
```
$ grip "import numpy"
./_json_encoder.py:
   10 : import numpy as np
./charts/builders/line_builder.py:
   71 :         import numpy as np
./charts/chart.py:
   25 : import numpy as np
./charts/conftest.py:
    3 : import numpy as np
./charts/data_source.py:
   16 : import numpy as np
./charts/glyphs.py:
    5 : import numpy as np
./charts/properties.py:
   11 : import numpy as np
./charts/stats.py:
   17 : import numpy as np
./charts/tests/test_chart.py:
   22 : import numpy as np
./compat/bokeh_renderer.py:
   20 : import numpy as np
./compat/mpl_helpers.py:
   16 : import numpy as np
./compat/mplexporter/renderers/base.py:
    5 : import numpy as np
./compat/mplexporter/utils.py:
    9 : import numpy as np
./crossfilter/models.py:
    7 : import numpy as np
./crossfilter/plotting.py:
    3 : import numpy as np
./crossfilter/plugins.py:
    3 : import numpy as np
./plotting_helpers.py:
    8 : import numpy as np
./properties.py:
  110 :     import numpy as np
  735 :         import numpy as np
  739 :         import numpy as np
 1142 :             import numpy as np
./tests/test_document.py:
  333 :         import numpy as np
./tests/test_json_encoder.py:
    6 : import numpy as np
./tests/test_properties.py:
    3 : import numpy as np
  406 :             import numpy as np
  455 :             import numpy as np
  504 :             import numpy as np
  553 :             import numpy as np
./transforms/ar_downsample.py:
   10 : import numpy as np
./transforms/image_downsample.py:
    3 : import numpy as np
./transforms/line_downsample.py:
    5 : import numpy as np
./util/serialization.py:
   12 :     import numpy as np
```

**Comment by bryevdv** [comment] 2015-11-11 13:06
I would also take some doing to figure out how to maintain this under test. Many tests do and always will need numpy, and that is fine, but there would need to be some explicit set of tests and way to run them that ensured things works without NumPy.

**Comment by birdsarah** [comment] 2015-11-12 00:52
that's no where near as bad as I thought it would be. to my mind: `compat`, `crossfilter`, `transforms` are not core bokeh, that leaves

```sh
./_json_encoder.py
./plotting_helpers.py
./properties.py
./util/serialization.py
```
which don't look that bad - they're mostly about handling np types if they've been used.

> I would also take some doing to figure out how to maintain this under test. Many tests do and always will need numpy, and that is fine, but there would need to be some explicit set of tests and way to run them that ensured things works without NumPy. 

Some thoughts:

1) the way I would do this in a less complicated testing setup would be with tox. In our case we'd probably stick with existing machinery but need multiple builds. It may not be too bad we could pick one environment, say py34 (or whatever latest python is) and test with no pandas, no numpy etc.

2) Alternatively.....we could monkey patch numpy, pandas, and anything else to be None in a set of tests. This is prone to maintenance issues.

3) I also don't see why it wouldn't be possible in `.travis.yml`, to manually uninstall `numpy` and `pandas` before running a set of tests e.g. on https://github.com/bokeh/bokeh/blob/master/.travis.yml#L64
```yaml
 - if [[ -z "$TRAVIS_TAG" && "$GROUP" == no_deps ]]; then ( conda remove pandas numpy; py.test -m 'nodeps' ) ; fi 
```
---
From @pzwang:
> I would really like to keep it possible to use Bokeh with Python web projects that don't have the scientific/pydata stack installed. 
+1 on this. I'm from django world. We have a set of deploy scripts that work well and use pip (but not wheels). If you go to add a library and all of a sudden your deploy time goes from 30s to 5+ minutes because it compiles numpy every time then it's a turn off.

**Comment by bryevdv** [comment] 2015-11-12 12:35
@birdsarah sure it's not that many places, I'd just like to do it right. There are other dependencies we could soften. E.g. if we make a `bokeh-server` metapackage, that could depend on Tornado and core bokeh could not depend on it. But the client *does* need it, so we need a regular way to inform users when they are missing optional dependencies. I guess I'd suggest something like:
```
from bokeh.utils.modules import require, try

# pandas is required, warn and fail if missing
pd = require('pandas', 'bokeh.charts')

# optional, return None silently if missing
np = try('numpy')
```

**Comment by damianavila** [comment] 2015-11-12 13:33
> 3) I also don't see why it wouldn't be possible in .travis.yml, to manually uninstall numpy and pandas before running a set of tests e.g. on https://github.com/bokeh/bokeh/blob/master/.travis.yml#L64

That's an interesting way to achieve the goal...

**Comment by bryevdv** [comment] 2015-12-17 03:37
Checking up, our (soon to be) current dependencies are:
```
    - python
    - six
    - requests
    - pyyaml
    - python-dateutil
    - jinja2
    - numpy
    - tornado >=4.0.1
    - futures        [py27]
```
`pandas` is optional (for `bokeh.charts`) and I think we could potentially get rid of `six` as well since we only use two or three functions from it. 

I think this is OK? Between conda and wheels I think *just numpy* is not a big burden these days. Thoughts @bokeh/dev ?

**Comment by mattpap** [comment] 2015-12-17 10:05
> I think we could potentially get rid of six as well

Please don't. If we depend on numpy then we can definitively depend on six and not maintain yet another set of functions.

**Comment by fpliger** [comment] 2015-12-17 18:04
>> I think we could potentially get rid of six as well

>Please don't. If we depend on numpy then we can definitively depend on six and not maintain yet another set of functions.

+1

**Comment by bryevdv** [comment] 2016-04-02 22:11
> Please don't. If we depend on numpy then we can definitively depend on six and not maintain yet another set of functions.

I guess it's a preference of maintaining (but not really, just vendoring and forgetting) two functions vs maintaining another dependency (which is also not cost-free). But I'll demur since others feel strongly. 

Anyway, updated "numpy" dependence (excluding `charts` and any `tests` dirs):
```
./core/compat/bokeh_renderer.py:
   20 : import numpy as np
./core/compat/mpl_helpers.py:
   16 : import numpy as np
./core/compat/mplexporter/renderers/base.py:
    5 : import numpy as np
./core/compat/mplexporter/utils.py:
    9 : import numpy as np
./core/json_encoder.py:
   14 : import numpy as np
./core/properties.py:
  123 :     import numpy as np
 1089 :         import numpy as np
 1093 :         import numpy as np
 1544 :             import numpy as np
./core/property_containers.py:
  167 :         import numpy as np
./models/sources.py:
  226 :         import numpy as np
./plotting/helpers.py:
    9 : import numpy as np
./util/serialization.py:
   14 :     import numpy as np
```
We can't get rid of the dependence in `mplexporter` that's just vendored in code. We are going to eventually move to a binary array protocol option for the server, so that would add some more. For referfence the current dependency list is now just:
```
    - python
    - six
    - requests
    - pyyaml
    - python-dateutil
    - jinja2
    - numpy
    - tornado >=4.3
    - futures-compat
```
So "removing" numpy would really mean making it an optional dependency, which is needed for the server or for MPL support. That seems potentially very confusing and a source of many questions/issues. Given the existence of both conda packages and now pip wheels, I think I am -1 on pursuing this.

**Comment by bryevdv** [comment] 2016-08-22 19:43
I'd really like to close this. It's risky, long and tedious to implement, will require a raft of testing, all for an extremely nominal gain (personal opinion) in the era of conda and wheels.

**Comment by damianavila** [comment] 2016-08-23 13:10
>I'd really like to close this. It's risky, long and tedious to implement, will require a raft of testing, all for an extremely nominal gain (personal opinion) in the era of conda and wheels.

I second your opinion here...

**Closed** 2016-09-06 23:33 UTC
Labels: type: discussion
