### ISSUE TITLE
Line plotting goes awry at a specific plot size

### ISSUE THREAD

**Issue by birdsarah** [bokeh/bokeh#7465] opened 2018-01-27 18:16 UTC
Code to reproduce

```python
import numpy as np
from scipy.stats import norm

from bokeh.io import output_notebook, show
from bokeh.plotting import figure

output_notebook()

SAMPLE_SIZE = 2000
normal_model = norm()
x_model = np.linspace(normal_model.ppf(0.1), normal_model.ppf(0.9), SAMPLE_SIZE)
y_model = np.linspace(normal_model.ppf(0.1), normal_model.ppf(0.9), SAMPLE_SIZE)

def make_plot(height):
    p = figure(plot_height=height, plot_width=600)
    p.line(y=y_model, x=x_model)
    # Need axis labels to reproduce
    p.yaxis.axis_label = 'Y'
    p.xaxis.axis_label = 'X'
    return p

crazy_plot = make_plot(500)
normal_plot = make_plot(400)

show(crazy_plot)
show(normal_plot)
```
Saved from crazy_plot
![bokeh_plot_crazt](https://user-images.githubusercontent.com/1796208/35474934-22726720-035b-11e8-9d61-9dd9077d9abf.png)

From normal_plot
![bokeh_plot](https://user-images.githubusercontent.com/1796208/35474935-2283eafe-035b-11e8-920a-762908c141d4.png)

Adding a title, removing an axis stop this from happening. I can also only make it happen at certain sample sizes e.g. 2000, 2700, 3000 - but not values around them e.g. 2001, 2100.

I figured it's worth reporting, but this trivial to work around and is not affecting me.

- Bokeh version: 0.12.13
- Browser: Firefox
- In jupyter notebook

**Comment by bryevdv** [comment] 2018-01-29 15:58
Honestly this seems like a bizarre bug in FF

**Comment by bryevdv** [comment] 2018-01-29 16:02
The problem goes away with webgl (there are other webgl issues) as well as with SVG, so I am definitely leaning more towards FF canvas bug

**Comment by bryevdv** [comment] 2018-01-29 16:12
I'd love to try and make a pure JS reproducer to submit to FF tracker but I don't know when I would have time to do that. I am going to close this as `upstream` however, since as best I can tell that is the case

**Closed by bryevdv** 2018-01-29 16:12 UTC

**Comment by bryevdv** [comment] 2018-01-29 16:14
Additionally: changing one point even a little causes the problem to go away. It seems limited to arrays of N exactly co-linear points, for certain specific values of N.
