### ISSUE TITLE
[FEATURE] MultiChoice: allow flag for the options menu to be closed after an item is selected or not

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#12157] opened 2022-06-02 23:01 UTC
### Problem description

Status quo: Every selection will close the options menu which is annoying if multiple options need to be selected:

open menu -> select item -> open menu -> select item -> open menu -> select item

### Feature description

Keep options menu open after selection:

open menu -> select item -> select item -> select item -> select item -> close menu by clicking somewhere else

Behaviour demonstrated in choices.js https://choices-js.github.io/Choices/ under _Multiple select input_ -> _With remove button_

Benefit: reduce number of clicks to get desired result

Fun fact: Seems to be the preferred behaviour of choices.js (at least all their examples have it).

### Potential alternatives

-

**Comment by bryevdv** [comment] 2022-06-02 23:06
These are the only defaults Bokeh overrides:
```typescript
    const options = {
      choices,
      duplicateItemsAllowed: false,
      shouldSort: false,
      removeItemButton: this.model.delete_button,
      classNames: {item, button} as any, // XXX: missing typings
      placeholderValue: this.model.placeholder ?? undefined,
      maxItemCount: this.model.max_items ?? undefined,
      renderChoiceLimit: this.model.option_limit ?? undefined,
      searchResultLimit: this.model.search_option_limit ?? undefined,
    }
```
It would be good to compare to the demo examples. @muendlein perhaps you can try to track down the source for one of the examples?

**Comment by muendlein** [comment] 2022-06-03 15:08
@bryevdv Here is a minimal working example (html), it seems like all default settings are used.

`<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width,initial-scale=1,user-scalable=no"
    />

	
	<link
	  rel="stylesheet"
	  href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/base.min.css"
	/>

	
	<link
	  rel="stylesheet"
	  href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css"
	/>

	
	<script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>
  </head>

  <body>
    <div class="container">
      <div class="section">

        <label for="choices-multiple-remove-button">With remove button</label>
        <select
          class="form-control"
          name="choices-multiple-remove-button"
          id="choices-multiple-remove-button"
          placeholder="This is a placeholder"
          multiple
        >
          <option value="Choice 1" selected>Choice 1</option>
          <option value="Choice 2">Choice 2</option>
          <option value="Choice 3">Choice 3</option>
          <option value="Choice 4">Choice 4</option>
        </select>
      </div>
    </div>
    <script>
      document.addEventListener('DOMContentLoaded', function() {

        var multipleCancelButton = new Choices(
          '#choices-multiple-remove-button',
          {
            allowHTML: true,
            removeItemButton: true,
          }
        );
      });
    </script>
  </body>
</html>`

**Comment by bryevdv** [comment] 2022-06-03 16:06
For easy reference here:
```
        var multipleCancelButton = new Choices(
          '#choices-multiple-remove-button',
          {
            allowHTML: true,
            removeItemButton: true,
          }
        );
```
Well, seems a bit weird offhand. We default `removeItemButton` to True so that's the same. `allowHTML` defaults to `true` to begin with so setting it there seems redundant. I guess it is also possible that this is a recent feature addition to `choices.js` and just need to upgrade the version we include. Some investigation will be required, for sure.

**Comment by bryevdv** [comment] 2022-06-03 16:18
@mattpap actually, `MultiChoice` on `branch-3.0` just seems to be broken:

https://docs.bokeh.org/en/dev-3.0/docs/user_guide/interaction/widgets.html#multichoice

Clicking on the input the selection pops up and disappears immediately before anything can be selected.

**Comment by mattpap** [comment] 2022-06-03 16:33
Yeah, I've noticed when working on widget tooltips.

**Comment by gmerritt123** [comment] 2023-01-23 23:32
Bumping this/tagging on because I've noticed the shouldSort/shouldSortItems options aren't exposed bokeh-side (or it's simply not working/behaving as intended). 

Say I choose "foo", then "baz", then "bar". I want the value array to stick to the user-selected order... but the multichoice currently re-sorts itself to sitck to it's original input order (so the value array becomes ["foo", "bar", "baz"])

I think that's shouldSort=false override not working? There's a shouldSortItems option as well, kinda confused about the difference between the two....

Anyway, if (while you fix this) an option could also be added to handle either case (i.e. "sort according to original input list" vs "sort according to user input" that'd be pretty swell :-D

**Comment by mzy2240** [comment] 2023-02-21 02:03
I am using Panel 0.14.3 which leveraging 3.1.0.dev2, and I can confirm that the dropdown menu items are always auto-sorted, regardless of what order is given.

**Comment by mattpap** [comment] 2023-02-21 10:49
> I am using Panel 0.14.3 which leveraging 3.1.0.dev2, and I can confirm that the dropdown menu items are always auto-sorted, regardless of what order is given.

Panel 0.14 doesn't work with bokeh 3.x. Sorting of items in the menu was fixed in bokeh 3.0. You will have to wait for panel 1.0 to take advantage of this fix. Sorting of items in the input widgets still occurs and it looks like a bug in the underlying library, which currently isn't actively maintained.

**Comment by mattpap** [comment] 2023-02-21 11:13
Not closing the menu after a click is the default behavior of choices.js. However, in bokeh we do this:
```js
this.on_change([
  value, max_items, option_limit, search_option_limit,
  delete_button, placeholder, options, name, title,
], () => this.render())
```
which effectively closes the menu by destroying the component whenever value changes.

**Comment by mattpap** [comment] 2023-02-21 11:18
Not destroying the component every time, also fixes the item sorting issue.

**Closed** 2023-02-24 07:08 UTC
Labels: type: feature, tag: component: bokehjs, tag: widgets
