### ISSUE TITLE
for v0.12, tabs and panels only work if one of the tabs is figure

### ISSUE THREAD

**Issue by charleywan2004** [bokeh/bokeh#5762] opened 2017-01-19 13:04 UTC
The following code works

#####################################
from bokeh.plotting import Figure
from bokeh.models import Range1d, ColumnDataSource,HoverTool,BoxZoomTool,ResetTool,ResizeTool
from bokeh.layouts import column, row, widgetbox
from bokeh.models.widgets import Slider, TextInput, Toggle, CheckboxGroup, DataTable, TableColumn, Select, Panel, Tabs
from bokeh.io import curdoc
from bokeh.io import output_file, show
from bokeh.layouts import widgetbox
from bokeh.models.widgets import Button, RadioButtonGroup, Select, Slider

output_file("layout_widgets.html")

p1 = figure(plot_width=300, plot_height=300)
p1.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)
tab0 = Panel(child=p1, title="circle")

slider = Slider(start=0, end=10, value=1, step=.1, title="Slider")
button_group = RadioButtonGroup(labels=["Option 1", "Option 2", "Option 3"], active=0)
select = Select(title="Option:", value="foo", options=["foo", "bar", "baz", "quux"])
button_1 = Button(label="Button 1")
button_2 = Button(label="Button 2")

tab1 = Panel(child=row(button_1, slider), title="plot") 
tab2 = Panel(child=row(button_group, select, button_2), title="datatable") 
tabs = Tabs(tabs=[tab0,  tab1, tab2 ]) 

show(tabs)
################################

Yet, if I remove tab0, tabs and panels are not working
###########################
from bokeh.plotting import Figure
from bokeh.models import Range1d, ColumnDataSource,HoverTool,BoxZoomTool,ResetTool,ResizeTool
from bokeh.layouts import column, row, widgetbox
from bokeh.models.widgets import Slider, TextInput, Toggle, CheckboxGroup, DataTable, TableColumn, Select, Panel, Tabs
from bokeh.io import curdoc
from bokeh.io import output_file, show
from bokeh.layouts import widgetbox
from bokeh.models.widgets import Button, RadioButtonGroup, Select, Slider

output_file("layout_widgets.html")

slider = Slider(start=0, end=10, value=1, step=.1, title="Slider")
button_group = RadioButtonGroup(labels=["Option 1", "Option 2", "Option 3"], active=0)
select = Select(title="Option:", value="foo", options=["foo", "bar", "baz", "quux"])
button_1 = Button(label="Button 1")
button_2 = Button(label="Button 2")

tab1 = Panel(child=row(button_1, slider), title="plot") 
tab2 = Panel(child=row(button_group, select, button_2), title="datatable") 
tabs = Tabs(tabs=[tab1, tab2 ]) 

show(tabs)
#############################################

**Comment by mattpap** [comment] 2017-01-19 15:20
This is a duplicate of issue #5143.

**Closed by mattpap** 2017-01-19 15:20 UTC
Labels: reso: duplicate
