### ISSUE TITLE
bokeh-server content length too long

### ISSUE THREAD

**Issue by azjps** [bokeh/bokeh#2334] opened 2015-05-26 00:10 UTC
python gives an unfriendly error when bokeh-server is sent too much data. Is there some documentation somewhere regarding how much data bokeh-server can process? I realize there certainly has to be a limit to the amount of data processed due to networking constraints etc, but wasn't able to find any discussion of scalability. I think matplotlib can handle a dataset of a size like the one below (albeit slowly):

```python
import numpy as np
import bokeh.plotting as blt

def plot_random(fig, n):
    fig.line(np.arange(n), np.random.rand(n))

bplt.output_server('test')
fig = bplt.figure()
plot_random(fig, 4000000)
bplt.show(fig)
```

This yields the incorrect error message:
```python
    317         except requests.exceptions.ConnectionError as e:
    318             warnings.warn("You need to start the bokeh-server to see this example.")
--> 319             raise e
    320         if resp.status_code == 409:
    321             raise DataIntegrityException

ConnectionError: ('Connection aborted.', error(104, 'Connection reset by peer'))
```

`bokeh-server` shows the more useful error message:

```bash
$ 2015-05-25 19:55:50,652:INFO:tornado.general:Malformed HTTP message from 127.0.0.1: Content-Length too long
```

**Comment by bryevdv** [comment] 2015-05-26 13:39
Hi @azjps It's true that we need to characterize and advertise the limits of the Bokeh server better. 

However, I can say right off the bat that one of the express purposes of the Bokeh server is to be a facility that eliminates the need to ever try to send four million points into the browser. There are number of reasons that you would not want to do this.

First, a 1000x1000 pixel plot only has one million pixels. Sending four million points, even with naive alpha-compositing, is almost certainly not going to be productive in terms of generating a useful visualization. 

The reason second is that no browser is going to be able to accommodate that many points before it issues a stack size overflow error. This is not a limitation that is under our control. Instead, the bokeh server is intended to be a place where large data sets can be intelligently downsampled, or even have their visual representation re-molded, so that you are not sending more data than you have pixels. Some of our work around "abstract rendering" is an attempt to automate this process, but that is still very early stage. At the moment you would have to write your own Bokeh app to do this kind of downsampling or transformation. 

It's possible in this last scenario that you would want to send all the data to the server at once, in which case we would evidently need to look at some kind of message chunking. Preferable would be to generate the data inside the server in the app, or use a remote data source or blaze data source to read from an external data store.

**Comment by azjps** [comment] 2015-05-26 20:16
Thanks for the detailed reply, that was helpful (as you can probably tell I'm new to this module). I'll poke around the docs more, the options you mentioned in the last sentence are definitely what I'm looking to be able to do.

**Comment by bryevdv** [comment] 2015-11-19 00:07
I can confirm that this is still an issue with the new tornado and websocket-based server:
```
Traceback (most recent call last):
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/tornado/iostream.py", line 644, in _handle_read
    pos = self._read_to_buffer_loop()
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/tornado/iostream.py", line 614, in _read_to_buffer_loop
    if self._read_to_buffer() == 0:
  File "/Users/bryan/anaconda/lib/python3.4/site-packages/tornado/iostream.py", line 744, in _read_to_buffer
    raise StreamBufferFullError("Reached maximum read buffer size")
tornado.iostream.StreamBufferFullError: Reached maximum read buffer size
```
It does work with 400k points and webgl (albeit opening somewhat slowly). This I think is realistically past the upper end of where you'd want to start looking at more sophisticated downsampling or pre-rasterization schemes. 

I'm going to close this for now please feel free to re-open if there is more to discuss

**Closed by bryevdv** 2015-11-19 00:07 UTC
Labels: type: discussion
