### ISSUE TITLE
Color Issue w/ IE11 and WebGL

### ISSUE THREAD

**Issue by crashMOGWAI** [bokeh/bokeh#4240] opened 2016-04-27 19:38 UTC
First off, props to everyone on this library! 

The below snippet works on IE10 & QtWeb as expected. However, once I updated to IE11 the RGB coloring on selection of the plot is messed up. The expected behavior returns when simplifying the plotting, so it seems to be pointing to `ColumnDataSource` but everything traces through fine..so I'm scratching my head. Anyone else see this issue? Any guess as to why this is happening? 

Excuse the hacked code, but its as simple as I could manage while replicating the issue:

```
from bokeh.plotting import ColumnDataSource,figure, show, output_file
import pandas as pd

#init data
FILE = (['foo','foo','foo','bar','bar','bar','baz','baz'])
A = ([5,5,6,6,8,8,5,5])
B = ([1,1,2,2,3,3,1,1])
c1 = (100, 50, 10)
c2 = (200, 100, 0)
c3 = (120, 95, 50)
#build and name index using data
index = pd.MultiIndex.from_arrays([FILE,A,B], names=['iFILE','iA','iB'])

init = pd.DataFrame({'X': [ 0, 1, 2, 3, 4, 5, 6, 7],
                   'Y': [ 1, 2, 3, 4, 5, 6, 7, 8],
                   'HUE': [c1,c1,c2,c2,c3,c3,c1,c1],
                   'dFILE':FILE,
                   'dA': A,
                   'dB': B}, index=index)
                   
#group data                   
df = {} 
group = init.groupby(level=('iA','iB'))
for name, group in group:
    uniA = name[0]
    uniB = name[1]
    k = int(uniA), int(uniB)  
    df.update({k:group})                   
                   
#configure plot
TOOLS='resize,crosshair,pan,wheel_zoom,tap,hover'
p = figure(tools=TOOLS, 
           webgl=True)
for perPt in df:
    dataSource = ColumnDataSource(df[perPt])
    color1 = df[perPt]['HUE'].head(1)[0]
    color2 = df[perPt]['HUE'].head(1)[0]
    p.circle(x='X', y='Y', source=dataSource,
             size=10, line_width=4,
             fill_color=None, line_color='lightgrey',        
             # set visual properties for selected glyphs
             selection_alpha=1,
             selection_fill_color= color1,
             selection_line_color= 'yellow',                      
             # set visual properties for non-selected glyphs
             nonselection_alpha=1,
             nonselection_fill_color=color1,
             nonselection_line_color=color2)
             
output_file("lastsession.html")
show(p)
```

**Comment by bryevdv** [comment] 2016-04-27 20:59
Tentatively marking as `windows`, @crashMOGWAI can you see if the problem goes away if you use hex color strings? (e.g., `"#ff22a4"`) There have historically been some hiccups with color tuples and there may still be some kinks to work out.

**Comment by crashMOGWAI** [comment] 2016-04-27 21:31
Doesn't work with named strings
```
c1 = 'black'
c2 = 'red'
c3 = 'orange'
```
or hex
```
c1 = '#ff22a4'
c2 = '#00ffff'
c3 = '#ff8C00'
```
I don't see the color issues on any of the lower level plotting, just when I start pushing everything through from a source.

**Comment by bryevdv** [comment] 2016-04-27 21:42
Well, it seems to be working as expected on master on OS X, so it will  reproducing your environment more carefully, which will unfortunately take some time before I can get to. I think another issue on master may have been uncovered, however, I had to disable webgl to get any output

@almarklein @mattpap I believe the recent work on JS properties left some of the webgl code not functioning correctly.

**Comment by bryevdv** [comment] 2016-04-27 21:44
@crashMOGWAI also curious, to be clear, the problem happens with the exact code above? Because although there is a column of colors, you aren't actually referring to or using that column anywhere as an actual data column, I so I am a bit doubtful that is is the problem.

**Comment by crashMOGWAI** [comment] 2016-04-27 21:51
Code is a mess, sorry will edit. Confirm webgl=True is the underlying issue. After disabling it worked as expected..but you know, slower :)

**Comment by bryevdv** [comment] 2016-04-27 21:56
@crashMOGWAI we will make sure to look into this, glad we could narrow it down. Can you let us know what version of Bokeh you are using?

@almarklein please take a quick look when you get back

**Comment by crashMOGWAI** [comment] 2016-04-27 22:09
> >>> bokeh.__base_version__
> '0.11.1'

**Comment by almarklein** [comment] 2016-05-02 21:11
@bryevdv  I can confirm that current master shows nothing with WebGL. This is another issue, for which I just made #4265.

**Comment by almarklein** [comment] 2016-05-03 13:41
I can reproduce this bug on Edge, and also know why it happens, unfortunately, we cannot do anything about it.

The problem is due to a known issue on IE, that we also mention in the docs (but which I also forgot about): "Making a selection of markers on Internet Explorer will reduce the size of the markers to 1 pixel (looks like a bug in IE)."

In #4269 I added some code to produce a warning when using selections with webgl on IE. Other than that, the only advice I can give is to use Firefox or Chrome.

**Closed by almarklein** 2016-05-03 13:41 UTC
Labels: tag: webgl, type: bug

**Comment by mortonjt** [comment] 2017-02-25 17:27
I'm experiencing the same problems on chrome on `bokeh=0.12.4`.  Running

```
import bokeh.plotting as plt
p = plt.figure(plot_width=500, plot_height=500, webgl=True)
p.circle([487.5, 12.5, 324.897, 338.261, 193.169],
         [347.769, 483.28, 16.7199, 271.728, 365.925], size=20, color='#0000FF')
show(p)
```
Gives me
<img width="517" alt="screen shot 2017-02-25 at 9 25 37 am" src="https://cloud.githubusercontent.com/assets/4184797/23333209/7f4a094e-fb3c-11e6-9163-5c08fd351426.png">
