### ISSUE TITLE
Embed bokeh plot with BlazeDataSource - CORS

### ISSUE THREAD

**Issue by omearac** [bokeh/bokeh#2418] opened 2015-06-19 13:22 UTC
Hi everyone,

I've been working on figuring this out, and it might be relevant to [this Blaze issue](https://github.com/ContinuumIO/blaze/issues/1131) that was closed 2 days ago and related to a similar problem/question [here](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/K95W5eiz5u8).

I'm new to Bokeh, so please dont mind if there are some misunderstandings..

This situation is this:

I want to embed the data plot from the abstract render example (at first without doing any downsampling) into an html file. My real data is too large to directly create the html page with the plot+data in it already, but this simple test case does the job. Note that the abstract render example uses Blaze as the data source.

```
from bokeh.plotting import cursession, figure, output_server, show, push, Session
import bokeh.embed as embed
from blaze.server.client import Client
from blaze import Data
from bokeh.models import BlazeDataSource

output_server("blazeembed")
c = Client('http://localhost:5006')
d = Data(c)
source = BlazeDataSource()
source.from_blaze(d.gauss)

plot = figure(tools="pan,wheel_zoom,box_zoom,reset,previewsave", plot_width=600, plot_height=600)
plot.circle('oneA', 'oneB',color='#A6CEE3',source=source)
show(plot)

tag = embed.autoload_server(plot, cursession(), public=True)
html = """
<html>
  <head></head>
  <body>
    %s
  </body>
</html>
"""
html = html % (tag)
with open("blaze_embed.html", "w+") as f:
    f.write(html)
print("""
To view this example, run
    python -m SimpleHTTPServer (or http.server on python 3)
in this directory, then navigate to
    http://localhost:8000/blaze_embed.html
""")
```

The output from the ```show(plot)``` shows that the connection to the Blaze data works fine.
However, when I run a SimpleHTTPServer, the consoles in firefox and chrome tell me

```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:5006/compute.json. This can be fixed by moving the resource to the same domain or enabling CORS.
```

It seems there is an OPTIONS compute.json method call to the bokeh server, and there is no ```Access-Control-Allow-Origin``` response header to that. 

Any help would be appreciated! Its great software and my workplace might be using it for a really neat project I can discuss with Continuum if some demos work.

Notes: 
1) Bryan pointed me here to create an issue from our chat on the [google group](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/TmYo-mHhsG8)

2) My Bokeh Server Configuration and versions
```
    Bokeh Server Configuration
    ==========================
    python version : 2.7.8
    bokeh version  : b56402b7b89cdf0e7395e94b668477d91a31d3e7
    listening      : 127.0.0.1:5006
    backend        : memory
    python options : debug:OFF, verbose:OFF, filter-logs:OFF, multi-user:OFF
    js options     : splitjs:OFF, debugjs:OFF

```

**Comment by omearac** [comment] 2015-06-22 08:58
@damianavila I'm not entirely sure this is a discussion as opposed to a bug. The test case example works when I'm just doing a ''normal'' plot and not using BlazeDataSource.

**Comment by bryevdv** [comment] 2015-06-22 11:43
Are you trying with a build of the Blaze server that was made since the issue you linked was closed?

**Comment by damianavila** [comment] 2015-06-22 11:58
> @damianavila I'm not entirely sure this is a discussion as opposed to a bug. The test case example works when I'm just doing a ''normal'' plot and not using BlazeDataSource.

It is a "sort" of default label... we need to test by ourselves the problem to actually label it as a bug. We look for replication to filter noise in the issue tracker. I am not saying that your report is not a problem, or a actual bug, just been conservative in the labeling until someone can replicate the issue. Hope it makes sense to you :wink:

**Comment by omearac** [comment] 2015-06-22 14:32
@bryevdv yep I pulled it after the issue was closed. But the example that I posted above doesn't explicitly use the Blaze server..from what I can see anyway. When I try to run the bokeh-server with the correct origin header setting from crossdomain.py it doesn't seem to stick when I use the BlazeDataSource. 

Seems many [people](https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/eciRFKSOj3M) have seem similar issues. I actually very surprised for such a core feature! 

I'll keep investigating but some of these deeper Flask details are very new to me.

and @damianavila, no worries I understand hehe. Thanks for the help/input!

**Comment by bryevdv** [comment] 2015-06-22 14:56
ping @mcdonc

**Comment by hhuuggoo** [comment] 2015-06-22 15:20
https://github.com/ContinuumIO/multiuserblazeserver/blob/master/mbs/views.py

most likely need to add crossdomain decorator there 

and here

https://github.com/bokeh/bokeh/blob/master/bokeh/server/blaze/views.py

**Comment by bryevdv** [comment] 2016-04-07 18:56
This discussion refers to the old `bokeh-server` which has been completely removed. Additionally, it refers to the `BlazeDataSource` which has been moved to maintenance by the Blaze team. For these reasons I am closing. If there is a reproducible issue with the new server, please open a new bug report with code to reproduce.

**Closed by bryevdv** 2016-04-07 18:56 UTC
Labels: type: discussion
