### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Saifeddinebr** [bokeh/bokeh#12879] opened 2023-03-02 17:33 UTC
### Software versions

Python version      :  3.8.8 (default, Apr 13 2021, 19:58:26) 
IPython version     :  7.26.0
Tornado version     :  6.2
Bokeh version       :  2.4.3
BokehJS static path :  /home/saifeddine/.local/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.15.0-60-generic-x86_64-with-glibc2.10

### Expected behavior

I'm using bokeh CDSView to filter my dataset but in some cases the filter does not behave correctly. I prepared a minimal code provided with data to demonstrate this behaviour.  The idea of the code is when you select a multiline, the filtered vertices by index given in a list should appear in black. These vertices are filtered using bokeh CDSView by IndexFilter.

### Observed behavior

When the index list is [0, 10, 12] for example (line 27) the code behaves correctly. However when you change the index list to [43, 45, 46] (uncomment line 28 + comment line 27 and re-execute the code) nothing appears on the screen. I think that something weird is going on and i can't find out what it is. I'm using bokeh 2.4.3.

### Example code

```Python
import numpy as np
from bokeh.plotting import figure, curdoc, show
from bokeh.models import ColumnDataSource, MultiLine, CDSView, IndexFilter
from bokeh.layouts import row

p = figure(plot_height=750,
           plot_width=1520,
           match_aspect=True,
           tools='pan,tap,wheel_zoom',
           active_scroll="wheel_zoom")

default_line = MultiLine(xs='xs', ys='ys', line_color='blue')
selected_line = MultiLine(line_color='red', line_width=2)

vertices = ColumnDataSource({'x': np.array([]), 'y': np.array([])})
multiline_src = ColumnDataSource({'xs': [], 'ys': []})
view = CDSView(source=vertices, filters=[IndexFilter([])])

# data multiline
p.add_glyph(multiline_src, default_line, selection_glyph=selected_line, nonselection_glyph=default_line, level='overlay')
# data vertices
p.circle(x='x', y='y', color='black', size=5, level='overlay', source=vertices, view=view)


def select_polyline_radiogroup_click(attr, old, new):

    current_list = [0, 10, 12]
    # current_list = [43, 45, 46]
    print('filter works with the first list but not with the second!')
    print('changing from', old, 'to', new, 'using', current_list)
    view.filters = [IndexFilter(current_list)]


# vertices
vertices.data = {'x': np.array([476987.78843757, 477007.51431882,
                                477031.37197249, 477054.39660754, 477064.99260456, 476988.58813546,
                                477011.62943087, 477025.69078541, 477037.90283858, 477051.18115561,
                                477062.17700158, 477069.67416928, 476988.52982415, 477009.32196925,
                                477027.08192653, 477046.90777002, 477064.80101027, 477075.79685624,
                                476989.94595583, 477005.97323435, 477035.97856554, 477054.55488108,
                                477077.94604432, 476990.15421049, 477020.84261696, 477034.43748107,
                                477050.53140108, 477068.7495186, 477079.89530792, 476991.02888005,
                                477017.11902367, 477044.10882741, 477065.90059487, 477086.69273997,
                                476991.67863459, 477023.81649349, 477048.05733573, 477075.59693177,
                                477089.59164482, 476992.92816254, 477023.96643684, 477048.50716579,
                                477073.39776258, 477095.13954892, 477011.37857194, 476975.77004066,
                                476878.65586444]),
                 'y': np.array([6705993.6773539, 6706000.10825775,
                                6706008.13855738, 6706015.90229105, 6706019.56757304,
                                6705990.01207191, 6705997.47591887, 6706002.17414396,
                                6706006.30591639, 6706010.80421701, 6706014.60278198,
                                6706017.11849826, 6705988.4376667, 6705995.33506099,
                                6706001.23283291, 6706007.93030273, 6706013.96135764,
                                6706017.99316783, 6705984.62244135, 6705989.73717577,
                                6705999.88334273, 6706006.11432211, 6706014.36120659,
                                6705983.24796061, 6705993.29416534, 6705997.86743764,
                                6706003.36536062, 6706009.5380287, 6706013.33659367,
                                6705979.49937676, 6705988.09612906, 6705997.19269254,
                                6706004.73984136, 6706011.78717901, 6705975.85075514,
                                6705986.39677105, 6705994.54369329, 6706003.89016236,
                                6706008.78831192, 6705972.70194471, 6705983.24796061,
                                6705991.44486397, 6705999.99163515, 6706007.43882174,
                                6706081.63287486, 6706057.03134583, 6706035.98994098])}

print('we have', len(vertices.data['x']), 'vertices')

l_split = np.array([0, 5, 7, 6, 5, 6, 5, 5, 5, 3])
cumul_split = np.cumsum(l_split)
new_data = {'xs': [], 'ys': []}
for i in range(len(l_split)-1):
    new_data['xs'].append(vertices.data['x'][cumul_split[i]: cumul_split[i+1]])
    new_data['ys'].append(vertices.data['y'][cumul_split[i]: cumul_split[i+1]])
multiline_src.data = new_data

multiline_src.selected.on_change("indices", select_polyline_radiogroup_click)

main_row = row(children=[p])

# show both plots next to each other in a gridplot layout
layout = row(children=[p])
curdoc().add_root(layout)
show(layout)
```

**Comment by bryevdv** [comment] 2023-03-02 17:40
@Saifeddinebr There are to be no more updates for the Bokeh 2.x branch. It's possible any issue from Bokeh 2.x has since been resolved. Please try to reproduce this with latest Bokeh 3.0.3 (or even better a Bokeh 3.1 pre-release) and report back.

**Comment by Saifeddinebr** [comment] 2023-03-03 08:49
@bryevdv Thanks for your reply. With Bokeh 3.0.3 the problem still persists. However with Bokeh 3.1 pre-release it works fine.
Thanks for your help.

**Comment by mattpap** [comment] 2023-03-03 09:01
@Saifeddinebr, thanks for verification. This was probably fixed by PR #12859, but could have been also a different one. `CDSView` and related code used to have many issues. I will close this as a duplicate.

**Comment by Saifeddinebr** [comment] 2023-03-03 09:01
@bryevdv I think there is an other issue with Bokeh 3.1 pre-release. The vertices appear in black but they do not correspond to the selected indices. 

![expected_behaviour](https://user-images.githubusercontent.com/126808663/222677575-8cd61afb-a4ec-4e4b-92e2-301722a54f92.png)
![code_behaviour](https://user-images.githubusercontent.com/126808663/222677682-8fb307cf-3b40-430b-8102-2e8773a88761.png)

**Closed as completed by mattpap** 2023-03-03 09:01 UTC
Labels: reso: duplicate

**Comment by Saifeddinebr** [comment] 2023-03-03 09:03
The first image corresponds to the expected behaviour (using with matplotlib), the second is with Bokeh 3.1 pre-release.
