### ISSUE TITLE
Tooltips overlap and are unreadable when multiple renderers are hit by HoverTool

### ISSUE THREAD

**Issue by chesucr** [bokeh/bokeh#7573] opened 2018-02-26 23:03 UTC
I have plotted a `figure` with several Glyphs (drawn by `plot.circle`). The target is to select all the layers at the same time. I have applied a CDSFilter to each `circle`. I am using a `legend` as well to hide or show them. What I want to do is to select only the points of the glyphs which are visible.

    # [...]

    plot = figure(
        width=600,
        height=600,
        x_range=x_range,
        y_range=y_range,
        x_axis_label='X',
        y_axis_label='Y',
        tools='',                    # they are added later
    )

    for key in flags:
        view = CDSView(source=self.source, filters=[IndexFilter(flags[key])])
        
        g = plot.circle(
            x='X', y='Y',
            size=5,
            fill_color=colors[key],
            legend='FLAG {}'.format(key),
            line_color=None,
            selection_color='red',
            source=self.source,
            view=view,
        )
        g.nonselection_glyph = None  # avoids to alter the color of the nonselected points

    plot.legend.location = "top_left"
    plot.legend.click_policy = "hide"

    # [...]

    lasso_select = LassoSelectTool(
        # renderers=self.glyph_rends,       # default >> all renderers inside the plot, this is not working either
        select_every_mousemove=False,
    )
    tools = (
        wheel_zoom, pan, box_zoom, box_select, lasso_select,
        crosshair, tap, save, reset, hover
    )
    plot.add_tools(*tools)

[![enter image description here][1]][1]

As you can see in the image only the green points are selected, the blue points are not selected. The current selection is drawn with red color. If I hide the green points with the button on the legend then I can select the blue ones. If I use the Tap tool then it is working as expected, and even if I use Lasso Tool selecting only one point.

If I add an HoverTool the result is also bad, the tooltips are overlapped if the points of some glyphs are very close.

[![tooltips overlapping][2]][2]

I do not know if CDSView is thought to work like this or if this feature should be developed.

  [2]: https://i.stack.imgur.com/0DLja.png

  [1]: https://i.stack.imgur.com/wEzhc.png

**Comment by clairetang6** [comment] 2018-02-27 02:50
Hi @chesucr, I think your first issue was an old bug (issue [2136](https://github.com/bokeh/bokeh/issues/2136)) that was fixed, but then resurfaced, and is now fixed again in master. 

For your second issue with the HoverTool, are you saying that the tooltips are not correct or just that they are positioned badly?

**Comment by chesucr** [comment] 2018-02-27 08:58
Ah! OK, I am using the latest version 0.12.14. I hope it will be fixed in the next version.

The content of the tooltips are correct, but they are overlapped as you can see in the image. The normal behaviour should be to show all of them, three in that case, one above each other. So they are positioned badly.

**Comment by chesucr** [comment] 2018-03-14 10:07
@clairetang6 do you think the second part of this issue is a duplicated of the issue [2328](https://github.com/bokeh/bokeh/issues/2328)? Or this may have other reasons?

**Comment by secretaliasname** [comment] 2018-03-27 23:21
I too am experiencing this issue. In my case however i would like to display only the closest result rather than all the results with improved positioning. I could see utility in both behaviors depending on the use case.

Additionally it would be extremely useful to be able to make the 'hit window' bigger than the actual glyph an then either return the closest point or n points. I beleive this is documented on #2328 though it appears that issue never achieved traction.

**Comment by mattpap** [comment] 2018-03-27 23:31
This looks like a duplicate of #1512.

**Comment by bryevdv** [comment] 2018-03-28 00:14
Yes I agree

**Closed by bryevdv** 2018-03-28 00:14 UTC
Labels: tag: component: bokehjs, type: feature
