### ISSUE TITLE
Widgets not respecting the disabled state

### ISSUE THREAD

**Issue by GuyAllard** [bokeh/bokeh#4942] opened 2016-08-11 09:42 UTC
I have noticed that several widget types are not respecting the disabled state. Buttons and dropdowns become greyed-out and unresponsive as they should, but some of the other widgets such as sliders continue to operate as normal.

The following code was tested on bokeh 12.1 and demonstrates the issue. Clicking on the 'disable' toggle sets the 'disabled' state of all the other widgets.
Save this code as widgets.py
```
"""
An example of widgets not respecting the disabled state
Run using: bokeh serve widgets.py --host localhost:8888 --port 8888
then connect to http://localhost:8888 in a browser
"""

from bokeh.plotting import curdoc
import bokeh.models.widgets as widgets
from bokeh.layouts import widgetbox

# make some widgets
button = widgets.Button(label="button1")
dropdown = widgets.Dropdown(label="dropdown", menu=[("one","one"), ("two", "two"), ("three", "three")])
multi_select = widgets.MultiSelect(options=["one", "two", "three"])
radio_button_group = widgets.RadioButtonGroup(labels=["one", "two", "three"])
slider = widgets.Slider(start=1, end=3, value=1, step=1, title="slider")

# display them
widget_box1 = widgetbox(
    button,
    dropdown,
    multi_select,
    radio_button_group,
    slider
)

curdoc().add_root(widget_box1)


# make a toggle button to disable the other widgets
def on_disable(disabled):
    for child in widget_box1.children:
        child.disabled = disabled

toggle = widgets.Toggle(label="Disable")
toggle.on_click(on_disable)

widget_box2 = widgetbox(
    toggle
)

curdoc().add_root(widget_box2)
```

**Comment by bryevdv** [comment] 2016-08-11 16:36
duplicate of #4940

**Closed by bryevdv** 2016-08-11 16:36 UTC
