### ISSUE TITLE
box selection should be based on Range model(s)

### ISSUE THREAD

**Issue by lawremi** [bokeh/bokeh#4745] opened 2016-07-04 05:47 UTC
A common application of coordinated multiple views is to have an overview paired with a plot restricted to the region selected in the overview plot. Currently, this can only be done using a Javascript callback (I think). It would be nice if the box selection tool was based on a tuple of `Range1d` objects (which I guess would be a `Range2d`), so that we could use the range model as, e.g., the `x_range` on a plot. If this sounds reasonable, I could submit a PR.

**Comment by bryevdv** [comment] 2018-03-16 21:48
Sorry this got overlooked and went untriaged. I think at this point a new `RangeAnnotation` would be needed.

**Comment by bryevdv** [comment] 2018-05-11 19:59
I'd consider this a duplicate of https://github.com/bokeh/bokeh/issues/7795

**Closed by bryevdv** 2018-05-11 19:59 UTC
Labels: type: discussion
