### ISSUE TITLE
[BUG] CrosshairTool 

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#11988] opened 2022-02-06 11:22 UTC
### Software versions

Python version      :  3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:03) 
IPython version     :  8.0.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /opt/conda/envs/development/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  v17.1.0
npm version         :  8.1.2
Operating system    :  Linux-5.10.0-8-amd64-x86_64-with-glibc2.31

### Browser name and version

Chrome Version 98.0.4758.81 (64-Bit)

### Jupyter notebook / Jupyter Lab version

notebook: 6.4.7

### Expected behavior

I have two linked figures with different `width` and `height` with a `CrosshairTool`. The `xrange` and `yrange` is not the same of these figures, but they are overlapping.

My expactations is, that the `CrosshairTool` is drawn by the curser position with respect to the axis.

### Observed behavior

 The `CrosshairTool` is  draw with respect of the total figure size and not adapted to the ranges.

**Comment**

It is possible that this is the wanted behavior.

### Example code

```Python
from bokeh.plotting import figure, show, output_notebook
from bokeh.layouts import gridplot
from bokeh.models import CrosshairTool
output_notebook()

linked_crosshair = CrosshairTool(dimensions="both")

p1 = figure(width=100, height=100)
p1.line(list(range(10)), list(range(10)))
p1.add_tools(linked_crosshair)

p2 = figure(width=200, height=200)
p2.line(list(range(15)), list(range(15)))
p2.add_tools(linked_crosshair)

show(gridplot([p1, p2], ncols=2))
```

### Screenshots

In this example screenshot you can see, that the selected x and y values are different from the right plot.

![CrosshairTool](https://user-images.githubusercontent.com/68053396/152678184-3a57633a-2b6e-4fb5-8867-b51df559c74d.png)

**Comment by bryevdv** [comment] 2022-02-06 12:22
Linked crosshair has never been implemented and is still an open issue. Dupe of #3799

**Closed** 2022-02-06 12:22 UTC
Labels: TRIAGE
