### ISSUE TITLE
Plots containing arrows fail to render correctly with svg output backend.

### ISSUE THREAD

**Issue by Haptein** [bokeh/bokeh#8744] opened 2019-03-15 00:51 UTC
Also exporting a plot with output_backend='svg' when it contains arrows throws the following warning/exception:

WARNING:bokeh.io.export:The webdriver raised a TimeoutException while waiting for a bokeh:idle' event to signify that the layout has rendered. Something may have gone wrong.

It does not matter wether it is exported as svg or png, and the resulting image looks the same. Plot looks the same when using show() but no exception is shown.

Minimal example
```
from bokeh.io import export_svgs, export_png
from bokeh.models import Plot, Arrow, VeeHead, Range1d

plot = Plot( output_backend='svg',y_range=Range1d(-1,2),x_range=Range1d(-1,2))

plot.add_layout(Arrow(end=VeeHead(),
                      x_start=0, y_start=0,
                      x_end=1,   y_end=1))

plot.add_layout(Arrow(end=VeeHead(),
                      x_start=0, y_start=0,
                      x_end=0,   y_end=1))

export_png(plot,filename='svg_arrow.png')
export_svgs(plot,filename='arrow.svg')

```

Output with canvas backend.
![canvas_arrow](https://user-images.githubusercontent.com/11263395/54400375-14cd3480-4688-11e9-9cf4-131a1b2f18a1.png)

Output with svg backend.
![svg__arrow](https://user-images.githubusercontent.com/11263395/54400381-17c82500-4688-11e9-945c-4455d271b1d1.png)

Version Info
python: 3.6.8
bokeh: 1.0.4
selenium: 3.141.0
phantomjs: 2.1.1

**Comment by mattpap** [comment] 2019-03-15 22:11
Errors in JS console (this is why `idle` doesn't trigger):
```
canvas2svg.js:536 Attempted to apply path command to node g
canvas2svg.js:953 Uncaught DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
```
Possibly a duplicate of other SVG backend related issues, but this is the first time I see this DOMException.

**Closed** 2020-08-18 18:06 UTC
Labels: tag: component: bokehjs, tag: svg, type: bug
