### ISSUE TITLE
bokeh=0.11.x conda release packages are broken

### ISSUE THREAD

**Issue by ikalev** [bokeh/bokeh#5196] opened 2016-09-20 09:22 UTC
The latest version of conda (`conda=4.2`) introduces an explicit check for package integrity at link time. If a file cannot be linked, installation fails. This is the case with `bokeh=0.11.1`:

```
C:\Users\kalev> conda install bokeh=0.11
Fetching package metadata .............
The following packages will be UPDATED:

    bokeh: 0.9.0-np19py27_0 <unknown> --> 0.11.1-py27_0 defaults

Fetching packages ...
Linking packages ...
CondaOSError: OS error: failed to link (src=u'C:\\ANACONDA\\pkgs\\bokeh-0.11.1-py27_0\\Scripts/bokeh-script.py-server', dst='C:\\ANACONDA\\Scripts/bokeh-script.py-server', type=1, error=CondaOSError: OS error: win32 hard
 link failed
)
```

The problem is that `Scripts/bokeh-script.py-server` is _not_ found in the release package, but it is listed in the package metadata (`info/files`). Could you please fix the package and push a new build? I know that `bokeh=0.12` is the latest release, but unfortunately we cannot migrate to this version at the moment.

**Comment by mattpap** [comment] 2016-09-20 10:08
Just to note, this is a windows specific issue. I tried `conda install bokeh=0.11` under conda 4.2.7 and it installed bokeh 0.11.1 just fine (as far as I can tell on windows), though the error is still there, just it appears after conda completing installation. So, I can import bokeh and all scripts are in place. @ikalev, which exact version of conda do you use? Maybe something changed between conda `4.2.{x->y}`. With the output you showed, it looks like a lot of packages may be affected, so this might have been already dealt with by conda team. Pinging @csoja for feedback.

**Comment by ikalev** [comment] 2016-09-20 10:22
I am using the same version (``conda=4.2.7``) and seeing the same behavior as you - the package is installed, but potentially corrupt. It works, but this is pure luck because conda crashes at the very end of the process as the file in question is one of the last files listed in ``info/files``.

What is even more important is that conda crashes, which is a problem when building conda packages which depend on ``bokeh=0.11``. This is exactly our problem at the moment. ``conda-build`` calls ``conda.install`` internally and the latter throws an exception when trying to satisfy the dependencies of our package. As a result, the entire build fails.

**Comment by ikalev** [comment] 2016-09-20 10:29
Relevant change: https://github.com/conda/conda/issues/3182

**Comment by bryevdv** [comment] 2016-09-20 17:26
@ikalev are you saying you could upgrade to a new `0.11.x` point release (but not `0.12.x`) or that you need an identical point release, with only a new conda build number? One path is a question for us, and another path is more a question for the Anaconda distro folks.

**Comment by bryevdv** [comment] 2016-09-20 17:27
ping @ilanschnell @kalefranz

**Comment by ikalev** [comment] 2016-09-20 18:04
@bryevdv Either option is perfectly fine. You could rebuild ``0.11.1`` and increment the build counter, or you could make a brand new ``0.11.x`` release. The only thing we can't do at the moment is seamlessly migrate to the ``0.12.x`` line of releases.

**Comment by kalefranz** [comment] 2016-09-20 18:26
ACK

**Comment by bigreddot** [comment] 2016-09-20 18:56
@kalefranz how hard is it to do some "surgery" on an existing build and bump just the build number?

**Comment by bryevdv** [comment] 2016-09-21 17:34
@kalefranz alternatively is there a way to disable the checking that is described?

**Comment by PascalLesage** [comment] 2017-01-11 18:26
I have just upgraded anaconda (`conda upgrade anaconda`) and run into the same problem. The build failed, and now, Spyder is gone, iPython is gone, jupyter notebook is gone...
(1) Is there a workaround to this? I'd happily revert to an earlier build just to get my tools back!
(2) Is there a fix planned?
I'm on Windows10

**Comment by bryevdv** [comment] 2017-01-11 18:30
ping @ikalev

**Comment by bryevdv** [comment] 2017-01-11 18:33
@PascalLesage the reality is that we simply do not have the resources to go back and patch old releases (`0.11.1` is nearly a year old at this point) Is there a reason you need this version? The problem described should be fixed in newer (e.g. `0.12.x`) releases. I am not sure about the other Anaconda problems, @ikalev may be able to help

**Comment by kalefranz** [comment] 2017-01-11 18:43
Looks like I've visited this issue a couple of times, but kept getting pulled away.  I've had time to read the full issue now.  If the package is corrupt, it should be fixed.  Conda in 4.3 will be even more picky about corrupt packages (but with better error messages).

We actually *can* fix the package though without rebuilding it.  @ilanschnell may be able to help.  Just unpack the tarball, fix the metadata (i.e. remove the bad line in `info/files`), and pack it back up.  It's up to you if you want to bump the build number.  There are advantages both ways.  Ilan has instructions that if we ever replace a package in repo.continuum.io with a new package but the same name (different md5), to save the old versions of the package so that we ca go back and reference them in the future.

**Comment by kalefranz** [comment] 2017-01-11 18:44
@bryevdv Can you give us a list of tarball urls that are bad?

**Comment by PascalLesage** [comment] 2017-01-11 18:55
I wasn't aware I was using an old release. I ran `conda upgrade conda` and `conda upgrade anaconda`, expecting this would result in me installing the new releases. In any case, I just did what @wulmer suggested [here](https://github.com/conda/conda/issues/3477), with one small difference. After modifying `info\files` I couldn't `upgrade` anaconda - it was simply missing. I had to `install`. My conda version is 4.2.13. Bokeh is still at 0.11.1.

**Comment by PascalLesage** [comment] 2017-01-11 18:59
I just upgraded bokeh to 0.12.4, and everything seems to be working. Thanks all.

**Comment by bryevdv** [comment] 2017-01-11 19:02
The next release of Anaconda will have `0.12.4` so this problem should roll off into history

**Comment by ikalev** [comment] 2017-01-11 19:22
@kalefranz The missing file was `Scripts/bokeh-script.py-server`.

**Comment by ilanschnell** [comment] 2017-01-11 21:12
Yes, I can see that there are some inconsistencies in the Windows `bokeh-0.11.1` packages.  I don't know what caused these issues, though.  Maybe a flawed version of conda-build was when creating these packages.  How important is it to fix the packages?

**Comment by bryevdv** [comment] 2017-01-11 21:15
As I said the next imminent release of anaconda should move this to historical concern, unless someone specifically indicates that that absolutely must use those old versions. I would say it is a very low priority. (I'm going to close this issue, accordingly)

**Closed by bryevdv** 2017-01-11 21:15 UTC
Labels: type: discussion

**Comment by Bennoo** [comment] 2017-03-15 10:48
I need to use the Anaconda 4.0.0 version because of graphlab create package (https://turi.com/download/install-graphlab-create-command-line.html). 
It is an explicit dependence, to use it you have to use Anaconda 4.0.0..

So when I'm trying to create a conda env with anaconda 4.0.0.0 I have the exact same issue.
Is the modification of the info\files my only possible solution??

**Comment by bryevdv** [comment] 2017-03-15 13:25
I am afraid it is the best solution I an offer from the bokeh side this this point. I wish I had a better answer for you, but so much build machinery has changed since then that it would easily take days to try to go back and make changes there. 

@ilanschnell would you still be able to fix up the tarball in the repo "surgically" ?

**Comment by Bennoo** [comment] 2017-03-15 13:30
Ok, thanks, the removal of the line in the file worked for me so it is fine. It should be great to have the opportunity to deactivate the integrity check directly from conda when installing. With a parameter or something..

**Comment by ilanschnell** [comment] 2017-03-15 18:51
Ok, I just fixed `win-32/bokeh-0.11.1-py27_0.tar.bz2` (inplace), which for some reason had a wrong `info/files` listing.

**Comment by ilanschnell** [comment] 2017-03-15 18:54
I should note that the new MD5 sum of `win-32/bokeh-0.11.1-py27_0.tar.bz2` is 
`e17b2efd69ed871ed6abf02eb11ae53f`.

**Comment by iozzyi** [comment] 2017-03-20 13:02
The missing file is in there, but it's named wrong. Go to C:/User/<<Name>>/.conda/env/.pckg/bokeh-0.11.1/info and edit the "files" manifest file in notepad to find/replace:
Find: "bokeh-script.py-server"
Replace: "bokeh-server-script.py"
Then remove the environment in conda and create it again, it should work.
(I just tried it)

**Comment by bryevdv** [comment] 2017-03-20 13:13
ping @ilanschnell

**Comment by iozzyi** [comment] 2017-03-20 13:25
Oh I just realised you already gave that solution @ilanschnell . The problem is when we try to install this from conda command line it still has that file missing problem. Thanks anyway

**Comment by marcopulido08** [comment] 2017-12-02 02:22
"The missing file is in there, but it's named wrong. Go to C:\Users\<>\.conda\envs\.pkgs\bokeh-0.11.1-py27_0\info and edit the "files" manifest file in notepad to find/replace:
Find: "bokeh-script.py-server"
Replace: "bokeh-server-script.py"
Then remove the environment in conda and create it again, it should work.
(I just tried it)"
It works awesome. Many thanks.

**Comment by nurid** [comment] 2018-03-24 19:45
I have the same problem when creating an environment using this command to my newer/up-to-date conda environment:

`conda create -n gl-env python=2.7 anaconda=4.0.0`

I then used 
@iozzyi (thanks)
suggestion, and retry the above command, and (hope that)

it's done successfully. It's now processing (Verifying transaction: \|-/ | ).

I used GraphLab Create as recommended in a machine learning course of Coursera:
https://www.coursera.org/learn/ml-foundations/supplement/5HQGl/reading-getting-started-with-python-ipython-notebook-graphlab-create
