### ISSUE TITLE
[FEATURE] Full support to plot networkx directed graphs

### ISSUE THREAD

**Issue by andreacassioli** [bokeh/bokeh#8885] opened 2019-05-02 07:39 UTC
**Is your feature request related to a problem? Please describe.**
It appears bokeh does not plot arrows for networkx direct graphs.

**Describe the solution you'd like**
When a networkx `DiGraph` is passed to bokeh, arcs should have terminal arrows to show their direction.

**Describe alternatives you've considered**
No viable options in bokeh afaik.

**Comment by bryevdv** [comment] 2019-06-11 03:55
This is a dupe of #8129 which is to provide an arrow based glyph, not just an annotation

**Closed by bryevdv** 2019-06-11 03:55 UTC
Labels: TRIAGE
