### ISSUE TITLE
Vbar width not updating correctly when too many things updated through `push_notebook`

### ISSUE THREAD

**Issue by aiguofer** [bokeh/bokeh#5811] opened 2017-01-27 22:03 UTC
Running Bokeh 0.12.4, Jupyter 4.3 (but this also happened with 4.2), and it happens both on a 2.7 kernel and a 3.5 kernel.

I have a Jupyter notebook with some interactive charts based on a few filters. I created an example to illustrate the issue in [this gist](https://gist.github.com/aiguofer/927e9d71f6e1e8ea48ade18056ab3322):

In there, there's 2 notebooks. One that behaves as expected, and one that does not. Basically, I calculate the width for some vbars depending on how the data is grouped. The width is correctly updated when there's not too many objects being updated by `push_notebook`. It seems like it works if I have 1 figure with 2 vbars and one line, or if I have 1 figure with 2 vbars and a separate DataTable. However, if I have the 2 vbars, line, and DataTable I start seeing issues.

I tried looking at other bugs to see if they could be related, and it seems like https://github.com/bokeh/bokeh/issues/4911 might have something to do with it?

Here's an example of what I'm seeing even though the width for both bar glyphs is being set to the same value:

![selection_015](https://cloud.githubusercontent.com/assets/780934/22398697/aa49f704-e55b-11e6-8a43-635c08afdac8.png)

![selection_014](https://cloud.githubusercontent.com/assets/780934/22398700/afcab29a-e55b-11e6-8c0c-c4ca4cc1b492.png)

**Comment by bryevdv** [comment] 2017-02-01 15:31
I'm not sure it's a dupe of #4911. In #4911 the problem appeared to be due to an excessive update rate that BokehJS could not keep up with, but that does not seem to be the situation here. Some investigation will be required.

**Comment by aiguofer** [comment] 2017-02-02 20:43
I've been trying to trace through to see what I can find. 

It seems like `push_notebook` is sending the right message to `bokehjs`. The `VBar.width` is set correctly in `Document.apply_json_patch` but when `PlotCanvasView.render` gets called, the corresponding `VBarView` doesn't have the right width.

I tried to look around to understand where the view gets the width set from the model but I haven't found it. I may need to read up a bit more of the developer guide, although not sure if it goes into that much detail.

**Comment by bryevdv** [comment] 2017-02-02 21:16
That's interesting to know, maybe it is the same thing after all. My experience with the other issue (tentatively) was that somehow when there were multiple updates, some of them could get clobbered. There is not alot of info in the dev guide at this level of detail but I am happy to answer any questions if you do keep digging.

**Comment by aiguofer** [comment] 2017-02-03 13:57
From looking at `GlyphView` it seems like the only functions that would change the `_width` would be `set_data` (through `materialize_dataspecs`) or `map_data`. However, neither of these gets called when processing the `width` change in `apply_json_patch`, only when processing a `data` change.

If I sort the `events_json` so that `data` attrs are last in `apply_json_patch`, it seems to work correctly, since the `width` change will have been processed by the time it gets to the appropriate `data` change.

This makes me wonder, what happens when the only thing you change is the `width`? I might look into it later.

**Comment by aiguofer** [comment] 2017-02-03 14:06
Ahhh so it looks like if I only change the `width` nothing happens: [see gist](https://gist.github.com/aiguofer/98a4d9b31803038f843881d03bc1794c)

**Comment by bryevdv** [comment] 2017-02-03 16:43
@aiguofer all property sets should go through here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/core/has_props.coffee#L28

I guess it would be useful to confirm whether or not its getting that far

**Comment by aiguofer** [comment] 2017-02-05 02:19
If I set a breakpoint at `this.setv(name, value)`, I see it only gets called by `RangeId` and `LinearMapper` which seem to be rendering objects.

In the notebook with the `DataTable` I also see it get called when `DataTableView.updateGrid` emits the `change` event.

It seems like `materialize_dataspecs` needs to be called on a property update and not just in `set_data`... or maybe `set_data` needs to get called in `render`.

Adding `@glyph.set_data(@model.data_source)` [in the render function](https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/renderers/glyph_renderer.coffee#L120) seems to fix the issue, but I'm not sure of what other side effects this might have, especially on performance. 

Tests seem to pass, so that's good. I'll create a PR and we can discuss it there.

**Comment by bryevdv** [comment] 2017-02-06 00:23
I'm definitely a bit wary of calling `set_data` unilaterally in `render`, I would worry that performance would suffer in common cases, with non-tiny data sizes. I will try to think about this and see if there is a more precise way to make sure changes to dataspecs get properly registered. 

In the mean time, we could validate whether the performance concern is actually warranted or not. If you set the env var `BOKEH_LOG_LEVEL=trace` the JS console will emit fairly voluminous information, including timings for render calls. It would be good to see how those scale for different data sizes, from a new hundred to say 100k points, with and without the PR change.

**Comment by bryevdv** [comment] 2017-02-06 00:26
also ping @mattpap

**Comment by bryevdv** [comment] 2017-02-06 00:34
Also, here is a place that could be experimented with:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/renderers/glyph_renderer.coffee#L59-L76

As you can see, `set_data` is only triggered on data source changes. There is some additional quick and dirty code at the bottom to get updates to work when *visual* (e.g. line, fill) properties are changed. My guess now is that this quick fix was not general enough to catch things like width *value* changes. I do think a solution will be found by more carefully wiring up events. I think at this point a general and robust solution is needed, that does not add to the hacky "propchange" fix that's already there.

**Comment by bryevdv** [comment] 2017-02-06 00:38
A very quick solution might be for this line:
```
@listenTo(@model, 'change', @request_render)
```
to do more than just request a re-render. E.g. maybe it could call `materialize_dataspecs` and then request a render. I do think it's possible to be better / more fine grained than that, but maybe this would do for now.

**Comment by aiguofer** [comment] 2017-02-06 03:38
Yeah, I agree... I was definitely thinking it might have some negative impact on performance... I'll try to do some performance testing.

In the meantime, I took a look and it seems that the `change` event doesn't get fired when only a property changes. The `propchange` event does get fired though. Adding:

```
        data = @model.glyph.materialize_dataspecs(@model.data_source)
        extend(@glyph, data)
```

to the `propchange` callback seems to also do the trick, probably with a smaller impact on performance.

However, I still think there's a more elegant solution to this, although I don't yet feel familiar enough with the various events and handlers to take a stab at a more general solution.

**Comment by aiguofer** [comment] 2017-02-09 18:17
Well.. I've looked around a bit more.

The previous proposal is worse than doing it in render, since `propchange` gets called multiple times.

At a high level, I can think of 2 alternatives. 

1. On each prop change, it could check to see if it needs to update any visuals or dataspecs.
2. After processing each Model change, it could check which properties were changed and update any visuals or dataspecs.

For 1., it seems a little complicated to wire the events in a way that's possible to do that. For 2., it seems like this might be a bit easier, but I still haven't figured out where the best place would be (although right before render seems like a good place to do so).

**Comment by bryevdv** [comment] 2017-05-11 21:52
Happily, some recent foundational work has evidently fixed this as a side effect:

<img width="678" alt="screen shot 2017-05-11 at 16 51 07" src="https://cloud.githubusercontent.com/assets/1078448/25973549/2e786d58-366a-11e7-9397-1bee1a37c183.png">
<img width="591" alt="screen shot 2017-05-11 at 16 51 14" src="https://cloud.githubusercontent.com/assets/1078448/25973548/2e6f9f52-366a-11e7-845c-60d5c60cde04.png">

closing now

**Comment by bryevdv** [comment] 2017-05-11 22:15
Hrm maybe I was too hasty. I was looking for the obviously wrong image similar to the one at the top and not seeing it. BUt the bar widths are still not identical as they evidently should be. 

As an aside it's not possible to embed bokeh apps in notebooks directly and that is a much more robust solution in most cases.

**Comment by bryevdv** [comment] 2017-05-11 22:18
No, it is fixed! the only current problem is calling `get_width` twice instead of calling once and saving the result. If you do that:

<img width="532" alt="screen shot 2017-05-11 at 17 18 21" src="https://cloud.githubusercontent.com/assets/1078448/25974294/e0d7da62-366d-11e7-9ba2-de985a3cb025.png">
<img width="533" alt="screen shot 2017-05-11 at 17 18 28" src="https://cloud.githubusercontent.com/assets/1078448/25974293/e0d6ac14-366d-11e7-81ca-4a30779681c5.png">
<img width="603" alt="screen shot 2017-05-11 at 17 18 34" src="https://cloud.githubusercontent.com/assets/1078448/25974295/e0d8959c-366d-11e7-928e-eb8cffcb02e4.png">

**Closed by bryevdv** 2017-05-11 22:18 UTC
Labels: tag: component: bokehjs, type: bug

**Comment by bryevdv** [comment] 2017-05-11 22:20
To be clear I changed it to do this:
```
    width = get_width()
    r.glyph.width = width
    r2.glyph.width = width
```
I'm not sure why repeated calls were returning different values offhand, but that's a general python question, not a bokeh one

**Comment by aiguofer** [comment] 2017-05-12 21:55
Hey Bryan,

Thanks for looking into this. From what I remember, there was some sort of race condition. There are times when the width change gets processed before the dataspec changes, which causes it to correctly render the changes. However, sometimes that doesn't happen.

Although it's possible that some of the changes that were made now guarantee that width always gets set before dataspec updates, changing ONLY the width does not work (because nothing calls `materialize_dataspecs`): https://gist.github.com/aiguofer/98a4d9b31803038f843881d03bc1794c

**Comment by aiguofer** [comment] 2017-05-12 22:05
I'd like to point out that the above scenario works correctly with the change in https://github.com/bokeh/bokeh/pull/5849/commits/bf99e313816dc8b10ee19fba2836bcfc848a2687

**Comment by bryevdv** [comment] 2017-05-13 01:34
Unfortunately that change would have a detrimental impact on performance of every render, and I am also not sure it is a correct thing to do in all cases. I also note that if I do this:
```
width = get_width()
r.glyph.width = width
r2.glyph.width = width * 0.5
```
Then things render correctly with one bar half the width of the other. So it is *not the case* (at least not now or anymore) that setting multiple things is a problem, which was the original stated issue. 

The *only* time I can reproduce a problem is if I call `get_width` twice, basically in any configuration. Considering the complex interplay three mulit-language runtimes (bokeh, ipywidgets, and the notebook itself), I think this is some due to some interaction between the state that is smeared across notebook cells and the relative execution orders, and that is not really something I expect to be able to figure out. Given that there are two possible workarounds, either a real embedded app which will always be more robust than `push_notebook`, or saving the width in a var and re-using it (which I would consider better practice in general anyway), I don't think there is any more that I can do for this issue.

**Comment by bryevdv** [comment] 2017-05-13 01:35
I would also add, the internals have be refactored dramatically since the race condition conclusion, I would not necessarily expect anything learned before to hold anymore.
