### ISSUE TITLE
Range FactorRange is incompatible is Scale LinearScale for BokehJS

### ISSUE THREAD

**Issue by David-Herman** [bokeh/bokeh#6614] opened 2017-07-14 13:41 UTC
Hello,

I am using BokehJS 0.12.5 for development I have noticed in Chrome (Version 59.0.3071.115 (Official Build) (64-bit)) my vertical bar plot are being shown but in 0.12.6 I get the following error in Chrome and the graph is not displayed. Creating new issue as requested by @bryevdv .

    bokeh-0.12.6.js:sourcemap:11319 Uncaught Error: Range FactorRange is incompatible is Scale LinearScale
    at CartesianFrame.exports.CartesianFrame.CartesianFrame._get_scales (bokeh-0.12.6.js:sourcemap:11319)
    at CartesianFrame.exports.CartesianFrame.CartesianFrame._configure_scales (bokeh-0.12.6.js:sourcemap:11348)
    at CartesianFrame.exports.CartesianFrame.CartesianFrame.initialize (bokeh-0.12.6.js:sourcemap:11267)
    at CartesianFrame.exports.HasProps.HasProps.finalize (bokeh-0.12.6.js:sourcemap:1365)
    at CartesianFrame.HasProps (bokeh-0.12.6.js:sourcemap:1350)
    at CartesianFrame.Model [as constructor] (bokeh-0.12.6.js:sourcemap:7198)
    at CartesianFrame.LayoutCanvas [as constructor] (bokeh-0.12.6.js:sourcemap:1880)
    at new CartesianFrame (bokeh-0.12.6.js:sourcemap:11261)
    at PlotCanvas.exports.PlotCanvas.PlotCanvas.initialize (bokeh-0.12.6.js:sourcemap:19588)
    at PlotCanvas.exports.HasProps.HasProps.finalize (bokeh-0.12.6.js:sourcemap:1365)

Neither plot is displayed in IE 11 and the respective error are below.

    SCRIPT65535: Invalid calling object
    File: bokeh-0.12.5.js, Line: 4841, Column: 5

And in 0.12.6,

    SCRIPT5022: Range FactorRange is incompatible is Scale LinearScale
    File: bokeh-0.12.6.js, Line: 11319, Column: 21

I have built a Github page to display a minimal example, [Error Example](https://david-herman.github.io/Bokeh_error_example/)

For succintity I am including the HTML/JS code here in the issue used for both plots.

```html
<!DOCTYPE html>
<head>
  <link rel="stylesheet" type="text/css" href="https://cdn.pydata.org/bokeh/release/bokeh-0.12.6.min.css">
  <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.6.js"></script>
  <script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-api-0.12.6.js"></script>
</head>
<body>
<h1>Example of Bokeh 0.12.6 Error in Chrome</h1><br><br>
<div id="myplot" />

</body>

<script>
var source = new Bokeh.ColumnDataSource({
  data: {
      x: ['a','a','b','b'],
      y: [1,2,3,4],
      bottom: [0,0,0,0],
  }
		}); 
var xdr = new Bokeh.FactorRange({ factors: source.data.x.filter( onlyUnique ).sort() });	
var ydr = Bokeh.Range1d(0, 5);
var p = new Bokeh.Plot({
  title: "My Title",
  x_range: xdr,
  y_range: ydr,
  plot_width: 300,
  plot_height: 300
});
p.attributes["above"][0]['align']='center';  	
var xaxis = new Bokeh.CategoricalAxis({
  major_label_orientation: Math.PI / 3
});  
var yaxis = new Bokeh.LinearAxis({});
p.add_layout(xaxis, "below");
p.add_layout(yaxis, "left");
  
var xgrid = new Bokeh.Grid({ ticker: xaxis.ticker, dimension: 0 });
var ygrid = new Bokeh.Grid({ ticker: yaxis.ticker, dimension: 1 });
p.add_layout(xgrid);
p.add_layout(ygrid);  
var glyph = new Bokeh.VBar({
  x: { field: "x" },
  top: { field: "y" },
  bottom: { field: "bottom" },
  width: 0.8,fill_alpha:0.9,
});
p.add_glyph(glyph, source);
Bokeh.Plotting.show(p, document.getElementById('myplot'));   
  
function onlyUnique(value, index, self) { 
  return self.indexOf(value) === index;
};  
  
</script>
```

**Comment by mattpap** [comment] 2017-07-14 13:58
> SCRIPT5022: Range FactorRange is incompatible is Scale LinearScale

This is duplicate of https://github.com/bokeh/bokeh/issues/6576.

**Comment by mattpap** [comment] 2017-07-14 13:58
> SCRIPT65535: Invalid calling object
> File: bokeh-0.12.5.js, Line: 4841, Column: 5

This was fixed in 0.12.6 (see #6127).

**Comment by bryevdv** [comment] 2017-07-14 13:59
<img width="484" alt="screen shot 2017-07-14 at 08 59 42" src="https://user-images.githubusercontent.com/1078448/28215205-caf4c21e-6872-11e7-9b4a-bc8be50cdf9f.png">

Is this new? Where is the UI for it?

**Comment by mattpap** [comment] 2017-07-14 14:00
@bryevdv, it's the first time a I see this as well.

**Closed** 2017-07-14 13:59 UTC
Labels: reso: duplicate

**Comment by bryevdv** [comment] 2017-07-14 14:01
Oh I guess it parsed your comment

**Comment by mattpap** [comment] 2017-07-14 14:01
Yeah, according to gihtub's blog it was released today (along other new features).
