### ISSUE TITLE
[BUG] griplot merge_tools=True does not work with multiple similar tools

### ISSUE THREAD

**Issue by bevoorrading** [bokeh/bokeh#12158] opened 2022-06-03 08:56 UTC
### Software versions

Python version      :  3.9.12 | packaged by conda-forge | (main, Mar 24 2022, 23:25:59) 
IPython version     :  7.33.0
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /home/~/anaconda3/envs/bound/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.4.0-109-generic-x86_64-with-glibc2.31

### Expected behavior

It is possible to add multiple tools of the same type to a toolbar, e.g. a `BoxZoomTool()` which only zooms in the x-direction (`dimensions='width'`) and one which only zooms in the y direction (`dimensions='height'`). This can be very useful.

When making multiple plots in one layout with `gridplot` and `merge_tools=True` (which is also the default), it should merge the tools from the different plots, but still have two BoxZoomTools, one with `dimensions='width'` and one with `dimensions='height'`.

### Observed behavior

The BoxZoomTools get merged such that only one BoxZoomTool is left, which does not work on all plots and only works in one dimension. 

Note that this does not happen when setting `merge_tools=False`, so the error comes from merging the tools. Probably the code for merging the tools does not realize these tools from the same type are from the same toolbar and tries to merge them.

### Example code

```Python
from bokeh.plotting import figure, show
from bokeh.models import BoxZoomTool
from bokeh.layouts import gridplot

plot = figure(width=400, height=400, tools='reset')
plot.circle([1, 2, 3], [1, 2, 3], size=20)

plot.add_tools(BoxZoomTool(dimensions='width'))
plot.add_tools(BoxZoomTool(dimensions='height'))

plot2 = figure(width=400, height=400, tools='reset')
plot2.circle([3, 2, 1], [1, 2, 3], size=20)

plot2.add_tools(BoxZoomTool(dimensions='width'))
plot2.add_tools(BoxZoomTool(dimensions='height'))

show(gridplot([[plot], [plot2]],merge_tools=True))
```

**Comment by mattpap** [comment] 2022-06-03 09:15
This is a duplicate of issue #9763. This is fixed in bokeh 3.0-dev.6.

**Closed by mattpap** 2022-06-03 09:15 UTC
Labels: TRIAGE
