### ISSUE TITLE
Extensions do not render when using bokeh.embed.components / bokeh.embed.file_html APIs

### ISSUE THREAD

**Issue by arossi1** [bokeh/bokeh#5353] opened 2016-10-14 12:35 UTC
I'm attempting to generate HTML that includes extensions (LaTeX) using the `bokeh.embed.components` and `bokeh.embed.file_html` APIs.
http://bokeh.pydata.org/en/latest/docs/reference/embed.html#bokeh.embed.components

I used the LaTeX example in the documentation as a starting point:
http://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/latex.html#userguide-extensions-examples-latex

Please see the attached code ([latexTest.py.txt](https://github.com/bokeh/bokeh/files/529342/latexTest.py.txt)) that illustrates the issues below.

When using the `file_html` API, the extension code (LatexLabel) appears to be included in the resulting HTML/script section -- however, the figure does not render.  In the case of the `components` API, the extension code does not appear to be included, and as expected, the figure does not render and the following error message is displayed:

_Bokeh Error
Module `LatexLabel' does not exists. The problem may be two fold. Either a model was requested that's available in an extra bundle, e.g. a widget, or a custom model was requested, but it wasn't registered before first usage._

References:
https://github.com/bokeh/bokeh/issues/647 [Support latex labels]
https://github.com/bokeh/bokeh/pull/4914 [Add support for loading external resources in output template]
https://github.com/bokeh/bokeh/issues/3193 [desired_num_ticks not working when using custom x_range]

**Comment by bryevdv** [comment] 2016-10-17 15:34
ping @mattpap

**Comment by bryevdv** [comment] 2016-12-10 20:16
@mattpap is this a dupe of another existing issue?

**Comment by birdsarah** [comment] 2017-01-26 22:28
the code you are using doesn't use the new style of imports/exports if that's relevant?

some snippets

```js
TextInput = require "models/widgets/text_input"

class IonRangeSliderView extends TextInput.View

module.exports =
  Model: IonRangeSlider
  View: IonRangeSliderView```

**Comment by birdsarah** [comment] 2017-01-26 22:32
I have code that looks very similar to yours that has worked for me in the past - custom model + components.

I was running bokeh 0.12.2rc2

Not sure why you're having issues.

**Comment by arossi1** [comment] 2017-01-26 23:01
Are you using the `bokeh.embed.components` API?  If so, can you post your code?  I'm currently using 0.12.3 and the example I provided in my original post does not work.  Thanks!

**Comment by econoraptor** [comment] 2017-01-27 00:39
I am also having this issue in 0.12.4

**Comment by birdsarah** [comment] 2017-01-27 00:52
> Are you using the bokeh.embed.components API?

Yes

>  If so, can you post your code? 

- No, sorry. This wasn't a public project.

> I'm currently using 0.12.3

- Have you tried 0.12.2rc2

**Comment by econoraptor** [comment] 2017-01-27 00:53
I am also having this issue in 0.12.4.  I tried using the given example http://bokeh.pydata.org/en/latest/docs/user_guide/extensions_gallery/tool.html

But I get the error: Model `DrawTool' does not exist. This could be due to a widget or a custom model not being registered before first usage.

**Comment by arossi1** [comment] 2017-01-27 00:57
I have not tried 0.12.2rc2.  Are you seeing issues in 0.12.3 and not in 0.12.2.rc2?  If not, would you mind testing the code I provided in the original post?

According to @econoraptor, this is still an issue in 0.12.4.

**Comment by arossi1** [comment] 2017-01-30 16:29
I tested the script from my original post with Bokeh 0.12.3, the `bokeh.embed.file_html` API worked as-is. I spent some time digging into the `bokeh.embed.components` API issue, and wound up adding the corresponding LatexLabel javascript using `bokeh.resources.INLINE` (see attached script).  However, I'm not sure if this is correct / acceptable - maybe there is a better way to accomplish what I'm doing? Side note: the `bokeh/examples/embed/embed_multiple.py` example was very helpful. That said, depending on the Bokeh developers' level of satisfaction with this result, this issue could be closed.

Here is a complete example for everyone's benefit: 
[latexTest2.py.txt](https://github.com/bokeh/bokeh/files/739516/latexTest2.py.txt)

This next issue probably belongs in a separate thread, but now I'm faced with a label placement issue. The motivation for using the LaTeX rendering is for axis labels. I can't seem to come up with a generic method for label placement. Depending on the content of the label, plot size, etc., I get different results, and it looks bad (e.g., label overlapped with plot, lots of whitespace, etc.). I tried using a `bokeh.layouts.layout`, but I'm quickly faced with the fact that the `LatexLabel` is not a 'LayoutDOM item'.  I tried using 'data' and 'screen' x/y_units, but I can't find a solution that works well. In general, it would be great to do something similar to this with a `LatexLabel` (i.e., instead of a `Title`):

`p.add_layout(Title(text="Bottom Centered Title", align="center"), "below")`

However, LatexLabel does not have an 'align' attribute. Is this simply a matter of inheriting from a different bokeh base class, or implementing another interface?

Thanks for your help!

**Comment by bryevdv** [comment] 2017-01-30 16:40
@arossi1 Thanks for digging in to this. I am glad you found a solution that worked, but in general I don't think that using `INLINE` the way you have should be necessary (things should "just work") so I think this issue should remain open. 

Regarding latex axis labels, I would suggest either creating an issue to discuss adding an example that demonstrates this, or making a mailing list thread to talk about it. Right now, axis is one of the last remaining "monolithic" models. i.e it's not got a lot of sub-parts, but they are all managed internally, they are not composable. I'd very much like to break up axis into smaller more manageable pieces but no one ha had the opportunity to do so yet. For now I think your best bet is to subclass axis and override a few methods. But we can discuss details outside this issue.

**Comment by arossi1** [comment] 2017-01-30 20:56
Thanks for your reply, @bryevdv.  As requested, I added another issue regarding the label placement.  Thanks again!

**Comment by bryevdv** [comment] 2017-03-05 21:49
OK, some possibly good news? On current master, this updated code works:

```
""" The LaTex example was derived from: http://matplotlib.org/users/usetex.html
"""

from bokeh.models import Label
from bokeh.plotting import output_file, figure, show

import numpy as np

output_file('external_resources.html')

class LatexLabel(Label):
    """A subclass of `Label` with all of the same class attributes except
    canvas mode isn't supported and DOM manipulation happens in the coffeescript
    superclass implementation that requires setting `render_mode='css'`).

    Only the render method of LabelView is overwritten to perform the
    text -> latex (via katex) conversion
    """
    __javascript__ = ["https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js"]
    __css__ = ["https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css"]
    __implementation__ = """
import {Label, LabelView} from "models/annotations/label"

export class LatexLabelView extends LabelView
  render: () ->
    ctx = @plot_view.canvas_view.ctx

    # Here because AngleSpec does units tranform and label doesn't support specs
    switch @model.angle_units
      when "rad" then angle = -1 * @model.angle
      when "deg" then angle = -1 * @model.angle * Math.PI/180.0

    if @model.x_units == "data"
      vx = @xmapper.map_to_target(@model.x)
    else
      vx = @model.x
    sx = @canvas.vx_to_sx(vx)

    if @model.y_units == "data"
      vy = @ymapper.map_to_target(@model.y)
    else
      vy = @model.y
    sy = @canvas.vy_to_sy(vy)

    if @model.panel?
      panel_offset = @_get_panel_offset()
      sx += panel_offset.x
      sy += panel_offset.y

    @_css_text(ctx, "", sx + @model.x_offset, sy - @model.y_offset, angle)
    katex.render(@model.text, @el, {displayMode: true})

export class LatexLabel extends Label
  type: 'LatexLabel'
  default_view: LatexLabelView
"""

x = np.arange(0.0, 1.0 + 0.01, 0.01)
y = np.cos(2*2*np.pi*x) + 2

p = figure(title="LaTex Demonstration", plot_width=500, plot_height=500)
p.line(x, y)

latex = LatexLabel(text="f = \sum_{n=1}^\infty\\frac{-e^{i\pi}}{2^n}!",
                   x=35, y=445, x_units='screen', y_units='screen',
                   render_mode='css', text_font_size='16pt',
                   background_fill_color='#ffffff')

p.add_layout(latex)

show(p)
```

Note I switched to `INLINE` resources for the embedding to test off master. But then I also tried to use the latest dev build from CDN with this, which also worked:
```
    for x in CDN.css_files:
        f.write('\n<link rel="stylesheet" href=%r>\n' % x)

    for x in INLINE.css_raw:
        f.write('\n<style>%s</style>\n' % x)

    for x in CDN.js_files:
        f.write('\n<script src=%r></script>\n' % x)

    for x in INLINE.js_raw:
        f.write('\n<script type="text/javascript">%s</script>\n' % x)

    f.write(script)
```

So, I am not sure if it some recent work that made a change (maybe @jsignell other PR for ork on `components`?) or, if this has always been a usage problem due to the usage being complicated. 

I'm also not sure: given the code above, what is required as an action? Is this a documentation issue, with more guidance that demonstrates the above sort of usage needed? Or is there some change needed to the API / implementation itself to make this better somehow?

**Comment by bryevdv** [comment] 2017-03-05 21:51
Here is a gist of the full script (using CDN resources, will need to run off master to get latest dev build CDN resources) 

https://gist.github.com/bryevdv/7b3c0d40f3fa6fdd3fbc8c8e4cd64e1b

**Comment by bryevdv** [comment] 2017-03-05 21:57
Confirmed the above code works with `0.12.4` CDN resources. I think this may have just been a confusion over usage all along. We clearly need more/better documentation of this specific use case (embedding with custom extensions) but do we need any other changes?

**Comment by mattpap** [comment] 2017-03-06 22:00
> but do we need any other changes?

Yes. Custom models are treated as resources and this is a source of endless confusion and special handling in various places. I've been working on a branch where I move the weight of custom models' bundle from resources to embedding.

**Comment by arossi1** [comment] 2017-03-07 20:56
Thanks for the info, @bryevdv.  I realize this is somewhat unrelated, but the motivation for using custom labels is to include rendered LaTeX on plot axes.  We are still struggling with that over here:
https://github.com/bokeh/bokeh/issues/5824

If you have any pointers or can push us down a different path that might yield a solution, I would appreciate it... I'm really at a loss.  I don't mind spending time investigating / trying different approaches.  Thanks!

**Comment by bryevdv** [comment] 2017-03-07 21:18
@arossi1 are you saying the code I posted above does not work for you?

**Comment by arossi1** [comment] 2017-03-08 12:08
It does work, but there are still issues with the placement / layout of the custom (LaTeX) label, as we are trying to develop in #5824.  This is a show-stopper for me, and I think many others based on the comments in that issue, as we try to utilize the custom label capability.  Thanks for your help.

**Closed** 2017-03-20 15:47 UTC
Labels: tag: component: bokehjs, type: bug
