### ISSUE TITLE
Text font size as a function of Zoom In / Out ( Feature Request )

### ISSUE THREAD

**Issue by shassathe** [bokeh/bokeh#4336] opened 2016-05-18 00:01 UTC
##It would be great to have the text font change according to the extent of user zoom in or zoom out. I currently have a scatter plot with text labels for each data point. It would be a really great addition if there would be a way to increase the font size of the text when the user zooms in and conversely reduces the font size when the user zooms out.

**Comment by bryevdv** [comment] 2016-05-18 00:03
This is a dupe of #2439

**Closed by bryevdv** 2016-05-18 00:03 UTC
