### ISSUE TITLE
[FEATURE] Data Table

### ISSUE THREAD

**Issue by eflanigan00** [bokeh/bokeh#13531] opened 2023-11-16 03:57 UTC
### Problem description

The pyqt5 data table has a lot of nice features. I would love for Bokeh to have similar features. You can right click on a cell and trigger function calls. This includes changing values, selecting numbers, changing cell and/or text color. 

### Feature description

The pyqt5 data table has a lot of nice features. I would love for Bokeh to have similar features. You can right click on a cell and trigger function calls. This includes changing values, selecting numbers, changing cell and/or text color. 

### Potential alternatives

N/A

**Comment by bryevdv** [comment] 2023-11-16 04:54
@eflanigan00 The issue as given is way too vague to act on. You are going to need to expand your ask with alot more detail: 

* links to concrete examples of the behavior in other tools that you'd like to reproduce, so that we can compare, and be certain we understand what you actually want
* sample (pseudo-)code that you would like to be able to write, to express these things with Bokeh

Additionally some of the things you describe already seem possible:

* *"This includes changing values"* 
  You can change the value of any cell by updating the CDS that backs it

* *"selecting numbers"* 
  Bokeh data table's support row selections when clicking on any cell in a row. Do you mean access to the cell index in addition? This is a dupe of https://github.com/bokeh/bokeh/issues/13107
* *"changing cell and/or text color"* 
  Already possible with [`HTMLTemplateFormatter`](https://docs.bokeh.org/en/latest/docs/reference/models/widgets/tables.html#bokeh.models.HTMLTemplateFormatter) cell formatter, as far as I know. Please provide more details about exactly how it is not sufficient for your use case, if it is not sufficient.

**Comment by jbednar** [comment] 2023-11-16 15:32
Panel incorporates [Tabulator](https://tabulator.info) for building Bokeh apps including those sorts of capabilities, so if Panel is an option for you, it's [ready already](https://panel.holoviz.org/reference/widgets/Tabulator.html)!

**Comment by bryevdv** [comment] 2023-12-07 19:05
closing for lack of any follow-up or engagement.

**Closed as completed by bryevdv** 2023-12-07 19:05 UTC
Labels: type: discussion
