### ISSUE TITLE
Toolbar Improvements: Active is programmable

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#3816] opened 2016-02-04 15:09 UTC
Be able to programmatically set active on a toolbar widget.

**Comment by bryevdv** [comment] 2016-04-09 01:38
This is actually a dupe of #3054 There is more discussion and information there, so I am closing this issue in favor of that one

**Closed by bryevdv** 2016-04-09 01:38 UTC
Labels: type: feature

**Comment by bryevdv** [comment] 2016-04-09 01:41
@damianavila I suddenly wonder if duplicates ought never to have a milestone. Thoughts?

**Comment by damianavila** [comment] 2016-04-10 21:07
>@damianavila I suddenly wonder if duplicates ought never to have a milestone. Thoughts?

Maybe... not sure... the milestone is probably a quick reference about when this was closed a duplicate... and IIRC duplicates are removed from the changelog... so there should not be a problem, although I also understand your position... mmm... as I said, not sure...
