### ISSUE TITLE
`figure.circle` render jumps around x-axis when zooming

### ISSUE THREAD

**Issue by p5a0u9l** [bokeh/bokeh#8687] opened 2019-02-25 22:58 UTC
I'm a big fan of the library and have tried to be thorough in this bug report. Finding something like this might turn off people. If I'm doing science and the data appears to change while interacting, that breaks everything. 

HTH

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

* bokeh == 1.04
* python == 3.7.2
* Linux - Ubuntu 16
* Chrome browser

#### Description of expected behavior and the observed behavior

Time series data from two curves plotted on same figure, when zooming the x-values of one curve jumps left and right of the reference curve. Not sure if the actual values are changing (unlikely) but it's rendered position, relative to the reference curve jumps to the left and to the right or to the nominal position when zooming in/out. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure, output_file, save
from bokeh.models import ColumnDataSource, LinearColorMapper, Range1d, WheelZoomTool                                                                
from bokeh.layouts import column, row
import numpy as np
import pandas as pd


fig_kwargs = {
    "x_axis_type": "datetime",
    "width": 1900,
    "height": 400,
    "tools": "pan,save,reset,box_zoom,xwheel_zoom",
    "active_scroll": "xwheel_zoom",
    "output_backend": "webgl",
}
output_file(f"reproduce.html")

fig = figure(**fig_kwargs)

control = np.arange(100)

df = pd.DataFrame(
    {
        "time": pd.date_range(pd.datetime.now(), periods=100, freq="1s"),
        "ctrl": control,
        "test": control + 5 * np.random.randn(100),
    }
)

# control
fig.scatter(
    x=df.time,
    y=df.ctrl,
    line_color="red",
    fill_color=None,
    marker="cross",
    size=5,
    legend="control line",
)

# test - no worky
fig.circle(
    x=df.time,
    y=df.test,
    fill_color=None,
    line_color="black",
    size=5,
    legend="test - wierd",
)

# test - yes worky
fig.scatter(
    x=df.time,
    y=df.test,
    fill_color=None,
    line_color="blue",
    size=5,
    legend="test - normal",
)

save(column(fig))

```

#### Stack traceback and/or browser JavaScript console output
Possibly issue related to WebGL backend compatibility

![image](https://user-images.githubusercontent.com/4721335/53374509-672ef700-390d-11e9-9d89-62af21a92232.png)

## Working at 1st zoom-level when method is `scatter`
![image](https://user-images.githubusercontent.com/4721335/53374282-c2acb500-390c-11e9-8f52-317efc582c73.png)

## Working at 2nd zoom-level when method is `scatter`
![image](https://user-images.githubusercontent.com/4721335/53374304-cb9d8680-390c-11e9-9d0a-752855c17377.png)

## Not Working at 1st zoom-level when method is `circle`
![image](https://user-images.githubusercontent.com/4721335/53374453-377fef00-390d-11e9-94d4-7201254b19e3.png)

## Not Working at 2nd zoom-level when method is `circle`
![image](https://user-images.githubusercontent.com/4721335/53374472-44044780-390d-11e9-8ccf-ecafd38e3a4f.png)

**Comment by bryevdv** [comment] 2019-02-26 21:17
@p5a0u9l  It's possible this is a webgl issue, I would first suggest turning off webgl. The original maintainer of the webgl capability no longer contributes to the project so that whole codebase will probably need to be re-done in the future (or discarded). 

In any case, in order to investigate we would need you to provide a *complete* script to reproduce the occurrence, as well as detailed usage instructions and any ancillary data. Without this, there is no hope that we can do anything, since we cannot fix what we cannot reproduce. Without this, the issue will be closed as `norepro`.

**Comment by p5a0u9l** [comment] 2019-02-26 21:52
Updated initial post to include complete, standalone script that reproduces the issue. Can also confirm that the issue goes away when I remove `"output_backend": "webgl"`.

**Comment by sprousewd** [comment] 2019-03-12 16:19
I can confirm I've seen this as well. I can provide an additional standalone .html file if it is helpful.

**Comment by bryevdv** [comment] 2019-03-12 16:22
I can only suggest not using webgl for now, if it is not working for your use case. I don't know when we might have a maintainer for webgl again. If you have large datasets you might consider using holoviews (to render datahsader output with Bokeh)

**Comment by mattpap** [comment] 2019-03-12 17:05
This is very interesting because it goes in and out of match depending on zoom level, but this issue is not zoom tool exclusive, and can be also reproduced with at least pan tool. This is also not an issue with webgl backend directly, because, as warnings in JS console indicate, webgl backend doesn't support this kind of data and falls back to canvas renderer. This indicates the problem is with glyph initialization under this specific scenario (webgl is available and usable, but the backend doesn't support the kind of data used).

**Comment by mattpap** [comment] 2019-03-12 17:08
The difference between scatter circle and circle glyphs, is that the former doesn't have a webgl implementation whereas the later has.

**Comment by mattpap** [comment] 2019-03-12 17:30
Actually this is a problem with the backend, because in some cases webgl is actually being used and then the rendered glyphs are offset. I think I will disable webgl altogether for a particular glyph if the sanity checks fail at least once. Currently they are performed for every paining which results in this flood of warning messages.

**Comment by devjit** [comment] 2019-09-06 17:46
Would it be possible to prioritize getting a fix for this? I have an application that greatly benefits from using WebGL, and while datashader is a possibility, it seems to be a much more complex solution.

**Comment by bryevdv** [comment] 2019-09-06 18:06
@devjit We'd like to completely re-do WebGL support on top of some newer, nicely libraries. We are even seeking funding to support this specific work effort. But realistically, unless a new contributor decides to step up in a big way, this work will not happen until next year.

**Comment by devjit** [comment] 2020-06-19 15:40
I'm curious if work has started on this yet?

**Comment by bryevdv** [comment] 2020-06-19 15:46
@devjit There have been a few small improvements to webgl codepaths recently. It's possible this was fixed incidentally/accidentally as part of those—you'd just need to try a latest release and see. The large chunk of work I described above (re-writing the webgl backend) has not started yet (we did not get the CZI funding in 2019)

**Comment by devjit** [comment] 2020-06-20 03:24
FYI - unfortunately the issue does not appear to be fixed
![image](https://user-images.githubusercontent.com/2753950/85190212-d0f1b380-b26a-11ea-8bc3-874bfd356118.png)

**Comment by bryevdv** [comment] 2020-08-25 04:25
There was the start of a major re-work in 2.2 and as of that release I can no longer repro this issue, so I will close. If you can still see this issue with 2.2+ please provide a complete minimal reproducer to investigate. 

Note that there is a small unrelated issue where webgl does not like like None colors (I had to set `fill_color` to "white" e.g.)

**Closed by bryevdv** 2020-08-25 04:25 UTC
Labels: tag: component: bokehjs, tag: webgl, type: bug
