### ISSUE TITLE
[BUG] SVG Backend fails while rendering Arrows

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#10380] opened 2020-08-06 12:27 UTC
#### Software version info (bokeh, python)
Python: 3.6.10
Bokeh: 2.1.1

#### Description of expected behavior and the observed behavior
The export of a figure in svg format fails, if there is an arrow used in the plot.

#### Minimal Example
```
from bokeh.io import show, export_svgs
from bokeh.models import ColumnDataSource, Arrow
from bokeh.plotting import figure, output_notebook

output_notebook()

# the figure
p = figure(x_range=(0, 8), y_range=(0, 2), plot_height=100, tools='' )
p.xgrid.visible = False
p.ygrid.visible = False
p.xaxis.visible = False
p.yaxis.visible = False

# some data
source = ColumnDataSource(dict(x=[1,7], y=[1,1]))
# plot data as circle
p.circle(x='x', y='y', radius=0.3, alpha=0.3, source=source)
# add arrow
p.add_layout(Arrow(x_start=1.3, y_start=1, x_end=6.7, y_end=1))

show(p)

p.output_backend = "svg"
export_svgs(p, filename = 'Test.svg')

show(p)

```
#### Screenshots
If the figure is ploted in a JupyterNotebook for the first time it looks like this.
![show_1](https://user-images.githubusercontent.com/68053396/89530515-ed33ba80-d7ee-11ea-8d31-ec99b2aa7d49.PNG)
After the export to a svg format the streight line is not drawn anymore. Futhermore the 'bokeh' sign is disappeared. The figure below is a screenplot of the html-output in the notebook but the svg looks teh same.
![show_2](https://user-images.githubusercontent.com/68053396/89530534-f58bf580-d7ee-11ea-8bfe-0563c510d754.PNG)

#### Warning
There is one bokeh warning in the notebook:

> WARNING:bokeh.io.export:The webdriver raised a TimeoutException while waiting for a 'bokeh:idle' event to signify that the layout has rendered. Something may have gone wrong.

#### Errors in browser
In the conlose of ther browser two errors occoure.
> Attempted to apply path command to node g<

and
> Uncaught (in promise) DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

both in bokeh-2.1.1.min.js:359

**Comment by mattpap** [comment] 2020-08-06 13:28
Duplicate of issue #8744.

**Closed by mattpap** 2020-08-06 13:28 UTC
Labels: TRIAGE
