### ISSUE TITLE
Datatable editing broken between 0.12.10 and 0.12.11+

### ISSUE THREAD

**Issue by pmicheletty** [bokeh/bokeh#7368] opened 2018-01-03 23:55 UTC
Something in the `0.12.11` release (and all the releases after) broke the ability to edit cells in the datatable. 

When I change back to `0.12.10` everything works fine.

Running on windows 10 and using Google Chrome browser. Can test using the [GitHub Example](https://github.com/bokeh/bokeh/blob/53cd93bea4168f87d296ad8a0b9bcd7d18e886ae/examples/models/server/data_tables.py)

**Comment by bryevdv** [comment] 2018-01-03 23:57
This is a dupe of https://github.com/bokeh/bokeh/issues/7304 which was fixed in PR #7347

**Comment by pmicheletty** [comment] 2018-01-03 23:58
Great! Thanks- my search missed that

**Closed by bryevdv** 2018-01-03 23:57 UTC
