### ISSUE TITLE
[FEATURE] Loading indicator during session build-up

### ISSUE THREAD

**Issue by muendlein** [bokeh/bokeh#12198] opened 2022-06-25 22:26 UTC
### Problem description

Complex apps or apps with background overhead can take quite a long time to be ready upon session creation (5-10 seconds isn't uncommon). During this time a blank page is shown with no indication what is going on. This is pretty confusing for anyone not familiar with Bokeh, in particular as most web pages these days do not behave like that (i.e. text displayed before images). As a consequence this makes it rather difficult to share a Bokeh Webapp with a larger audience. 

### Feature description

Feature: Replace blank page with loading indicator that is displayed immediately. As soon as the session layout is ready the loading indicator will be replaced with the respective layout.

With a loading indicator it becomes it more obvious what is going on in the background. It may also be used to inform the user if the layout setup fails. In the future allowing the customization of the loading indicator may also be an option.

### Potential alternatives

-

**Comment by bryevdv** [comment] 2022-06-26 04:27
This is a dupe of https://github.com/bokeh/bokeh/issues/3393 and/or https://github.com/bokeh/bokeh/issues/4272

**Closed by bryevdv** 2022-06-26 04:27 UTC
Labels: TRIAGE
