### ISSUE TITLE
[FEATURE] LOGO Plot /  Watermark plot in final tiles plot .

### ISSUE THREAD

**Issue by sameerCoder** [bokeh/bokeh#9210] opened 2019-09-03 05:41 UTC
Hi,
I have a plot in holoview containing tiles , My plot is coming fine , now i am thinking to add watermark or logo image which will be at constant place where as my latitude and longitude will change i.e zoom function work fine. 
I want to put log or watermark in my plot.
Is there any way so that i can put logo image / watermark into my final plot.

**Comment by sameerCoder** [comment] 2019-09-03 05:52
# Few lines of my code are :-`

`

tiles = gv.tile_sources.Wikipedia
hmap1 = hv.HoloMap(allplot, kdims='Date and Time :')
hmap2 = hv.HoloMap(allplot2, kdims='Date and Time :')
tiles*rasterize(hmap1).options(**opts)*hmap2
`

**Comment by bryevdv** [comment] 2019-09-03 15:18
This is a dupe of https://github.com/bokeh/bokeh/issues/6813 (not implemented yet)

**Closed** 2019-09-05 02:43 UTC
Labels: reso: duplicate, type: discussion

**Comment by sameerCoder** [comment] 2019-09-13 13:49
Hi,
So there isn't any way i can have logo image or watermark ? 
:(

**Comment by bryevdv** [comment] 2019-09-13 14:45
At present, you can write a custom extension.

**Comment by sameerCoder** [comment] 2019-09-13 14:47
Hi ,
Can you elaborate little , how I can do with customs extension , which
function to use ?

**Comment by bryevdv** [comment] 2019-09-13 14:59
You should spend some time up front studying the existing documentation and examples for extensions first:

https://docs.bokeh.org/en/latest/docs/user_guide/extensions.html

Then take this question to the Discourse:

https://discourse.bokeh.org/
