### ISSUE TITLE
HoverTool showing canvas coordinates not data coordinates 

### ISSUE THREAD

**Issue by jcorb** [bokeh/bokeh#4861] opened 2016-07-22 11:52 UTC
I don't think this is mentioned in the other hover tool issues, but I might have missed it.

Using `$x, $y` in `HoverTool` displays the canvas coordinates, not the data coordinates as I believe it is supposed to.  Using  `$sx, $sy` displays the canvas coordinates as well.

e.g.

```
from bokeh.plotting import figure, output_file, show
from bokeh.models import HoverTool

output_file("hover.html")

hover = HoverTool(
            tooltips=[
                ("index", "$index"),
                ("data (x,y)", "($x, $y)"),
                ("canvas (x,y)", "($sx, $sy)")
                ])

TOOLS = [hover]

p = figure(plot_width=400, plot_height=400, title=None, tools=TOOLS)

p.circle([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=10)

show(p)
```

produces

![screen shot 2016-07-22 at 7 46 20 am](https://cloud.githubusercontent.com/assets/10410105/17056372/dc4f2fc8-4fe0-11e6-9294-46cd88ab6735.png)

**Comment by birdsarah** [comment] 2016-07-22 15:31
Thanks for the report. I actually thought `$x` was meant to give screen space, but I just looked at the docs (http://bokeh.pydata.org/en/latest/docs/reference/models/tools.html#bokeh.models.tools.HoverTool.tooltips) and you're totally right.

**Comment by bgbg** [comment] 2016-07-27 09:34
I can confirm this behavior on Mac -- in  Chrome and Safari.

**Comment by bgbg** [comment] 2016-07-27 12:50
A quick workaround: when referencing the column names using the "@" notation, the tooltips are presented correctly

```
from bokeh.plotting import figure, output_file, show
from bokeh.models import HoverTool

hover = HoverTool(
            tooltips=[
                ("index", "$index"),
                ("data (using $) (x,y)", "($x, $y)"),
                ("data (using @) (x,y)", "(@x, @y)"),
                ("canvas (x,y)", "($sx, $sy)")
                ])

TOOLS = [hover]
p = figure(plot_width=400, plot_height=400, title=None, tools=TOOLS)
p.circle([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=10)
show(p)
```

![image](https://cloud.githubusercontent.com/assets/506547/17175728/d59cf770-5411-11e6-9ac4-3461b346723e.png)

**Comment by Prikers** [comment] 2016-10-06 08:37
I had noted this issue as well. Even in the [documentation](http://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#basic-tooltips), the example shows the canvas coordinates, not the data coordinates. 
@bgbg thank you for the workaround. If it can be useful for anyone: when using bar chart `@y` references to the middle value of the bar, not the height of it. In that case it seems that `@height` works fine. 
I did not find the list of all supported keywords with the `@` notation. Did I miss it?

**Comment by bryevdv** [comment] 2016-10-06 14:08
@Prikers the `@` notation can be used to reference any column in the associated column data source. There is no set list, you can use any column name you like. 

This definitely seems like a bug introduced at some point. The hover tool logic is quite convoluted to handle all the different cases, I've been meaning to try and factor and simplify it but have not had the opportunity to yet. If anyone is interested in poking around, the relevant files are here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/core/util/templating.coffee

in particular it would seem `data_x` and `data_y` are what are getting set incorrectly as a first guess.

**Comment by bryevdv** [comment] 2016-10-06 14:10
I actually find this line suspicious:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/coffee/models/tools/inspectors/hover_tool.coffee#L281

**Comment by bryevdv** [comment] 2016-10-06 15:12
ping @mattpap too

**Comment by mattpap** [comment] 2016-10-25 17:57
> The hover tool logic is quite convoluted to handle all the different cases (...)

The logic may in fact be convoluted, but the syntax is pretty straightforward. `$` is used to reference special variables, i.e. something you won't find in a data source and `@` to reference column names. So, `$x` and `@x` may or may not be the same thing. For example, if there is a circle at `(0, 0)` with data radius of 1 and hover tool is set to follow mouse, then `@x` will be always 0 when hovering this point, but `$x` will vary in `[-1, 1]` interval. Otherwise, if mouse following is off, then `$x == @x`.

**Comment by dr-glenn** [comment] 2016-10-25 17:57
I find that with default settings, hover tool shows data coords for line objects, but shows canvas for patch or rect objects. Have not tried other types.

**Comment by mattpap** [comment] 2016-10-25 17:58
Anyway, the bug was trivial and boiled down to shadowing of variables. Fixed in PR #5406.

**Closed** 2016-10-25 19:29 UTC
Labels: tag: component: bokehjs, type: bug

**Comment by w1res** [comment] 2017-06-09 19:19
I'm running Bokeh 0.12.5, and I still seem have this issue on line plots. Here is an example:

```
import numpy as np
import bokeh.plotting as plt
import bokeh.models as pltm

x = np.arange(100)
y = x**4

fig = plt.figure()
fig.add_tools(pltm.HoverTool())
fig.line(x, y)
plt.show(fig)
```

Here is the result. You can see that I get two different values of y, depending on where my cursor is positioned. The way I understand it, canvas should give the position of the cursor, and the other value should display the value of the indicated data point.

![1](https://user-images.githubusercontent.com/2823875/26991077-f784a9b4-4d26-11e7-945b-af6f3fcacfb6.png)

![2](https://user-images.githubusercontent.com/2823875/26991078-fa307350-4d26-11e7-8031-0090d89f77eb.png)

**Comment by bryevdv** [comment] 2017-06-09 19:29
@w1res there might be something specific to lines which are more complicated due to their connectivity. However, please open a new issue to this can be tracked and prioritized independently.
