### ISSUE TITLE
graphs are not displayed when using runipy

### ISSUE THREAD

**Issue by vasimkachhi** [bokeh/bokeh#3540] opened 2016-01-05 11:09 UTC
I am trying to plot graphs though bokeh .It runs fine when i run it in jupyter and shows proper output.But when i run ipynb file using runipy though terminal it runs fine but output is  not displayed(i.e graphs not displayed)

**Comment by bryevdv** [comment] 2016-01-05 13:48
ping @damianavila does `runipy` use/replace `nbconvert`? If so I think this is a duplicate of this issue https://github.com/bokeh/bokeh/issues/2826 which is upstream and out of our control

**Comment by vasimkachhi** [comment] 2016-01-06 05:20
no i am only runing the runipy to run jupyter notebook ipynb file and capturing result in other ipynb file.
I am nowhere manually using nbconvert.

**Comment by bryevdv** [comment] 2016-01-06 06:29
Are there any errors in the java script console when you look at the output notebook?

**Comment by vasimkachhi** [comment] 2016-01-06 08:53
no it does not show any error but gives this warning
(/usr/local/lib/python2.7/dist-packages/bokeh/_legacy_charts/_chart.py:92: UserWarning: Instantiating a Legacy Chart from bokeh._legacy_charts
  warn("Instantiating a Legacy Chart from bokeh._legacy_charts"))

There some warnings on java script console but no errors. 

i am sharing files so that you get clear picture
When i run through runipy:
[output_on_runipynb](https://gist.github.com/vasimkachhi/9e0b700418244644750d)

**Comment by bryevdv** [comment] 2016-01-06 13:53
Wait, are you always viewing on GitHub? Because GH strips out all JavaScript, which means Bokeh plus will never render there.

**Comment by vasimkachhi** [comment] 2016-01-06 13:59
no i am viewing it on my jupyter hub ,i am no where using GitHub for viewing output.
i gave you GitHub link to share my code only.
Thanks for your time

**Comment by damianavila** [comment] 2016-01-06 14:31
@bryevdv AFAIK, runipy uses nbconvert under the hood...

Using the latest RC2 I am getting this when I "nbconvert" an ipynb:

```
Bokeh: BokehJS not loaded, scheduling load and callback at Wed Jan 06 2016 11:26:19 GMT-0300 (ART)
Linked%20panning.html:250 Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/dev/bokeh-0.11.0rc2.min.js
Linked%20panning.html:250 Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/dev/bokeh-widgets-0.11.0rc2.min.js
Linked%20panning.html:250 Bokeh: injecting script tag for BokehJS library:  https://cdn.pydata.org/bokeh/dev/bokeh-compiler-0.11.0rc2.min.js
Linked%20panning.html:433 Bokeh: ERROR: autoload.js configured with elementid 'be85dd0c-99f1-4852-bf11-6d256e598900' but no matching script tag was found. 
cdn.pydata.org/bokeh/dev/bokeh-0.11.0rc2.min.js:1 Bokeh: setting prefix to /
Linked%20panning.html:243 Bokeh: all BokehJS libraries loaded
Linked%20panning.html:278 Bokeh: BokehJS plotting callback run at Wed Jan 06 2016 11:26:20 GMT-0300 (ART)
cdn.pydata.org/bokeh/dev/bokeh-0.11.0rc2.min.js:3 Bokeh: setting log level to: 'info'
Linked%20panning.html:260 Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/dev/bokeh-0.11.0rc2.min.css
Linked%20panning.html:262 Bokeh: injecting CSS: https://cdn.pydata.org/bokeh/dev/bokeh-widgets-0.11.0rc2.min.css
Linked%20panning.html:220 Bokeh: all callbacks have finished
```

@mattpap ideas? Maybe related with your latest changes? 

This used to work some weeks ago, IIRC...

**Comment by philippjfr** [comment] 2016-01-06 14:37
@damianavila Seeing the same thing in an [example notebook](http://holoviews.org/Examples/HipsterDynamics) I was trying to put together just now (still using RC1):

```
Bokeh: ERROR: autoload.js configured with elementid '9d5f5ae2-bd62-4f9b-8415-44c560194158' but no matching script tag was found. 
Bokeh: ERROR: autoload.js configured with elementid '04c06e54-c86d-4800-a6c6-24b6d9a18942' but no matching script tag was found.
```

**Comment by mattpap** [comment] 2016-01-06 14:41
@damianavila, I will look into this now.

**Comment by mattpap** [comment] 2016-01-06 15:08
@damianavila, I will submit a hotfix in a few minutes.

**Comment by mattpap** [comment] 2016-01-06 15:17
@damianavila, PR #3558.

**Closed** 2016-01-06 16:26 UTC
Labels: type: bug

**Comment by caseyjlaw** [comment] 2016-03-25 14:39
An update from a related problem I encountered:

Rendering ipynb with an *untrusted* notebook will sanitize bokeh javascript and remove figures. This happened for figure set up with output_notebook. If you create a notebook with nbconvert or runipy and try to display it, you may need to select "trust notebook" first (or use command line "jupyter trust file.ipynb").
