### ISSUE TITLE
Loading Bokeh in Jupyter Notebook returns: TypeError: a.Operator is undefined

### ISSUE THREAD

**Issue by draperjames** [bokeh/bokeh#5814] opened 2017-01-28 15:33 UTC
# My system specs 

## Python 
    '3.4.5 |Continuum Analytics, Inc.| (default, Jul  5 2016, 14:53:07) [MSC v.1600 64 bit (AMD64)]'

## Jupyter Notebook

    # packages in environment at C:\Anaconda3:
    #
    notebook                  4.3.0                    py35_0  
    notebook                  5.0.0.dev                 <pip>

## Bokeh 
    Name: bokeh
    Version: 0.12.5.dev11
    Summary: Interactive plots and applications in the browser from Python
    Home-page: http://github.com/bokeh/bokeh
    Author: Continuum Analytics
    Author-email: info@continuum.io
    License: New BSD
    Location: c:\anaconda3\lib\site-packages\bokeh-0.12.5.dev11-py3.5.egg
    Requires: six, requests, PyYAML, python-dateutil, Jinja2, numpy, tornado

# Problem
When I try to run the following in a Jupyter Notebook cell:   

    from bokeh.io import output_notebook
    from bokeh.resources import INLINE
    output_notebook(resources=INLINE)

It returns this:    

    Loading BokehJS ...
    Javascript error adding output!
    TypeError: a.Operator is undefined
    See your browser Javascript console for more details.

Does anybody know what's going on? Is 0.12.5.dev11 working in Jupyter Notebook for everyone else?

**Comment by bryevdv** [comment] 2017-01-28 15:34
It looks like you have two versions of the notebook installed somehow, which are you actually using?

**Comment by bryevdv** [comment] 2017-01-28 15:34
ping @mattpap

**Comment by bryevdv** [comment] 2017-01-28 15:38
However, I can confirm things are working fine for me:

<img width="549" alt="screen shot 2017-01-28 at 9 37 08 am" src="https://cloud.githubusercontent.com/assets/1078448/22397712/6c8401b2-e53d-11e6-8434-cf521e987f36.png">

Created with this env:
```
$ conda create -n nbtest -c bokeh/c/dev bokeh notebook
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /Users/bryan/anaconda/envs/nbtest:

The following NEW packages will be INSTALLED:

    appnope:          0.1.0-py36_0
    bokeh:            0.12.5dev11-py36_0 bokeh/c/dev
    decorator:        4.0.11-py36_0
    entrypoints:      0.2.2-py36_0
    futures-compat:   1.0-py3_0
    ipykernel:        4.5.2-py36_0
    ipython:          5.1.0-py36_1
    ipython_genutils: 0.1.0-py36_0
    jinja2:           2.9.4-py36_0
    jsonschema:       2.5.1-py36_0
    jupyter_client:   4.4.0-py36_0
    jupyter_core:     4.2.1-py36_0
    markupsafe:       0.23-py36_2
    mistune:          0.7.3-py36_1
    mkl:              2017.0.1-0
    nbconvert:        4.2.0-py36_0
    nbformat:         4.2.0-py36_0
    notebook:         4.3.1-py36_0
    numpy:            1.11.3-py36_0
    openssl:          1.0.2k-0
    path.py:          10.0-py36_0
    pexpect:          4.2.1-py36_0
    pickleshare:      0.7.4-py36_0
    pip:              9.0.1-py36_1
    prompt_toolkit:   1.0.9-py36_0
    ptyprocess:       0.5.1-py36_0
    pygments:         2.1.3-py36_0
    python:           3.6.0-0
    python-dateutil:  2.6.0-py36_0
    pyyaml:           3.12-py36_0
    pyzmq:            16.0.2-py36_0
    readline:         6.2-2
    requests:         2.12.4-py36_0
    setuptools:       27.2.0-py36_0
    simplegeneric:    0.8.1-py36_1
    six:              1.10.0-py36_0
    sqlite:           3.13.0-0
    terminado:        0.6-py36_0
    tk:               8.5.18-0
    tornado:          4.4.2-py36_0
    traitlets:        4.3.1-py36_0
    wcwidth:          0.1.7-py36_0
    wheel:            0.29.0-py36_0
    xz:               5.2.2-1
    yaml:             0.1.6-0
    zlib:             1.2.8-3

Proceed ([y]/n)?

bokeh-0.12.5de 100% |#####################################################################| Time: 0:00:02   2.31 MB/s
#
# To activate this environment, use:
# > source activate nbtest
#
# To deactivate this environment, use:
# > source deactivate nbtest
#
```

**Comment by draperjames** [comment] 2017-01-28 15:39
@bryevdv I was using notebook 4.3.0 for this.

**Comment by bryevdv** [comment] 2017-01-28 15:40
What OS?

**Comment by draperjames** [comment] 2017-01-28 15:41
Windows 7 64-bit.

**Comment by bryevdv** [comment] 2017-01-28 15:47
I happen to have a VM laying around, I  can't reproduce on win7-64bit:
<img width="598" alt="screen shot 2017-01-28 at 9 46 33 am" src="https://cloud.githubusercontent.com/assets/1078448/22397775/c205f5e0-e53e-11e6-86ac-0b7e57e61134.png">

By way of adding some data points can you see if this is reproducible anywhere else for you?

**Comment by draperjames** [comment] 2017-01-28 16:08
So here is what I just tried;

1. activate nbtest 
2. launch jupyter notebook
3. tried to make a new notebook for nbtest test kernel but it is not visible. made a python [root] kernel notebook instead assuming that since I launched jupyter notebook in active nbtest env that it is the root. 
4. made a cell with the following;

```python
from bokeh.io import output_notebook
from bokeh.resources import INLINE
output_notebook(resources=INLINE)
```
I'm still getting:
```
Javascript error adding output!
TypeError: a.Operator is undefined
See your browser Javascript console for more details.
```

**Comment by bryevdv** [comment] 2017-01-28 16:10
Well, I was running 4.3.1, can you try that to see if if makes a difference? A root env seems suspect possibly, since that is not the env you installed bokeh into. What is the reported value of `bokeh.__version__`? of `repr(bokeh)` ?

**Comment by draperjames** [comment] 2017-01-28 16:24
If I install notebook inside nbtest is there a way to make jupyter call notebook from that env? Right now I think that I'm calling notebook from the parent Anaconda directory so I'm guessing that that is the Python [Root] that comes up regardless of what env I've activated.

**Comment by draperjames** [comment] 2017-01-28 19:05
So here is what I've done so far.:

1. Removed all envs
2. Removed all versions of notebook and jupyterlab through cond and pip.
3. Reinstalled nbtest by running the following:

```
conda create -n nbtest -c bokeh/c/dev bokeh notebook
```
 I get the following CondaError;

```
C:\Users\Lenovo>conda create -n nbtest -c bokeh/c/dev bokeh notebook
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment C:\Anaconda3\envs\nbtest:

The following NEW packages will be INSTALLED:

    bokeh:               0.12.5dev11-py36_0 bokeh/c/dev
    colorama:            0.3.7-py36_0
    decorator:           4.0.11-py36_0
    entrypoints:         0.2.2-py36_0
    futures-compat:      1.0-py3_0
    ipykernel:           4.5.2-py36_0
    ipython:             5.1.0-py36_0
    ipython_genutils:    0.1.0-py36_0
    jinja2:              2.9.4-py36_0
    jsonschema:          2.5.1-py36_0
    jupyter_client:      4.4.0-py36_0
    jupyter_core:        4.2.1-py36_0
    markupsafe:          0.23-py36_2
    mistune:             0.7.3-py36_0
    mkl:                 2017.0.1-0
    nbconvert:           4.2.0-py36_0
    nbformat:            4.2.0-py36_0
    notebook:            4.3.1-py36_1
    numpy:               1.11.3-py36_0
    path.py:             10.0-py36_0
    pickleshare:         0.7.4-py36_0
    pip:                 9.0.1-py36_1
    prompt_toolkit:      1.0.9-py36_0
    pygments:            2.1.3-py36_0
    python:              3.6.0-0
    python-dateutil:     2.6.0-py36_0
    pyyaml:              3.12-py36_0
    pyzmq:               16.0.2-py36_0
    requests:            2.12.4-py36_0
    setuptools:          27.2.0-py36_1
    simplegeneric:       0.8.1-py36_1
    six:                 1.10.0-py36_0
    tornado:             4.4.2-py36_0
    traitlets:           4.3.1-py36_0
    vs2015_runtime:      14.0.25123-0
    wcwidth:             0.1.7-py36_0
    wheel:               0.29.0-py36_0
    win_unicode_console: 0.5-py36_0

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(318): An error occurred while installing package 'bokeh/c/dev::bokeh-0.12.5dev11-py36_0'.
CondaError: Cannot link a source that does not exist. C:\Anaconda3\pkgs\bokeh-0.12.5dev11-py36_0\bin\bokeh

Attempting to roll back.



CondaError: Cannot link a source that does not exist. C:\Anaconda3\pkgs\bokeh-0.12.5dev11-py36_0\bin\bokeh
```

4. The nbtest env works. I activate it by running:
```
activate nbtest
```
5. I install notebook 4.3.1 using:

```
pip install notebook
```

6. I launch notebook:
```
jupyter notebook
```

7. I make a new notebook selecting the nbtest kernel. I ran the following in the first cell

```
from bokeh.io import output_notebook
from bokeh.resources import INLINE
output_notebook(resources=INLINE)
```
It returns this:

```
Loading BokehJS ...
Javascript error adding output!
TypeError: a.Operator is undefined
See your browser Javascript console for more details.
```

### CONSOLE OUTPUT
```
13:52:08.505 TypeError: a.Operator is undefined
Stack trace:
inline_js</Bokeh</<["core/layout/solver"]<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:99:19067
i@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:281
i/l@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:251
inline_js</Bokeh</<["core/layout/side_panel"]<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:99:15023
i@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:281
i/l@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:251
inline_js</Bokeh</<["models/annotations/annotation"]<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:119:28533
i@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:281
i/l@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:251
inline_js</Bokeh</<["models/annotations/arrow"]<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:119:29728
i@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:281
i/l@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:251
inline_js</Bokeh</<["models/annotations/index"]<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:120:20257
i@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:281
i/l@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:251
inline_js</Bokeh</<["models/index"]<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:126:25629
i@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:281
i/l@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:251
inline_js</Bokeh</<.base<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:459
i@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:281
i/l@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:251
inline_js</Bokeh</<.embed<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:119:21828
i@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:281
i/l@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:251
inline_js</Bokeh</<.main<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:119:26626
i@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:281
e@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:365
inline_js</Bokeh<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:66
inline_js<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:93:26
run_inline_js@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:608:9
@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:629:7
run_callbacks/<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:47:65
run_callbacks@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:47:5
load_libs@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:59:7
@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:627:5
@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314 line 20557 > eval:2:2
append_javascript@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:20557:13
OutputArea.prototype.append_mime_type@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:20501:32
OutputArea.prototype.append_display_data@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:20465:13
OutputArea.prototype.append_output@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:20251:13
OutputArea.prototype.handle_output@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:20165:9
CodeCell.prototype.get_callbacks/<.iopub.output@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:21820:21
Kernel.prototype._handle_output_message@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:23440:13
.proxy/i@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:87:5486
Kernel.prototype._handle_iopub_message@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:23467:20
Kernel.prototype._finish_ws_message@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:23304:24
Kernel.prototype._handle_ws_message/this._msg_queue<@http://localhost:8888/static/notebook/js/main.min.js?v=edbc43d9bb99b1be2585a121ed720314:23295:39
 1 main.min.js:20559:13
```

So at this point I thinking about backing up my system and trying to wipe my complete anaconda install dot files and all then reinstalling everything from scratch to see if that makes a difference. IDK any advice?

**Comment by bryevdv** [comment] 2017-01-28 19:07
@draperjames I am not sure offhand, pinging conda dev @kalefranz for more insight

Do you have any other systems/VMs that you could test on? That was more the spirit of my earlier question (tying to determine if it just *this system* or whether you can reproduce it elsewhere)

**Comment by draperjames** [comment] 2017-01-28 19:11
I suppose I could build a VM for testing. What type of linux do you recommend for the VM?

**Comment by bryevdv** [comment] 2017-01-28 19:18
> I suppose I could build a VM for testing. What type of linux do you recommend for the VM?

I'm not sure it should matter too much, any reasonably recent Ubuntu, CentOS, Debian, etc should be fine.

**Comment by kalefranz** [comment] 2017-01-28 19:23
> CondaError: Cannot link a source that does not exist. C:\Anaconda3\pkgs\bokeh-0.12.5dev11-py36_0\bin\bokeh

That error means that `bin/bokeh` is listed in the `info/files` manifest, but conda doesn't actually see it in the extracted directory `C:\Anaconda3\pkgs\bokeh-0.12.5dev11-py36_0`.

Does that help?

**Comment by draperjames** [comment] 2017-01-28 19:29
Thanks @kalefranz for taking the time to help. Is there a way that I can work around that?

**Comment by kalefranz** [comment] 2017-01-28 19:39
Yeah, I do have an immediate workaround that can help...

The issue is related to https://github.com/conda/conda-build/issues/1678

For a workaround, either remove the `info/paths.json` file in the package tarball itself (if you have access to it on anaconda.org), or remove it locally after it's been unpacked to

    C:\Anaconda3\pkgs\bokeh-0.12.5dev11-py36_0\info\paths.json

**Comment by bryevdv** [comment] 2017-01-28 19:41
@draperjames to be clear, I think you happen to have uncovered a separate, unrelated problem with our new build automation, I don't think this is the cause of your original problem

**Comment by draperjames** [comment] 2017-01-28 19:54
Thanks at @kalefranz I'll try to remove it locally. @bryevdv well I'm happy to be of service to the project I'll keep let you know if @kalefranz solution works. On a side note I'm downloading Unbuntu 16.04 for the VM build from their website it is very slow ☹️.

**Comment by bryevdv** [comment] 2017-01-28 19:58
@draperjames no worries or hurries, we will get  to the bottom of things in due time. My prediction is that it will work on the VM, but let's see...

**Comment by draperjames** [comment] 2017-01-28 21:53
![good-news-everyone](https://cloud.githubusercontent.com/assets/22569604/22400035/900b6194-e578-11e6-8be4-984a140642f0.jpg)

@kalefranz and @bryevdv removing the following file locally worked!:

```
C:\Anaconda3\pkgs\bokeh-0.12.5dev11-py36_0\info\paths.json
```
I think I'm going to give up on building the VM for now but I'm sure that it would have worked.
 
Thanks so much for your help guys!

**Comment by bryevdv** [comment] 2017-01-28 23:56
@draperjames I'm frankly surprised, I don't immediately see how there could be a connection. @kalefranz when that error message happens is it possible for packages to be left in a partially installed state or something?

**Comment by bryevdv** [comment] 2017-01-28 23:57
Also, I am closing discussion issue in favor of the bug issue I added to the milestone

**Closed by bryevdv** 2017-01-28 23:57 UTC
Labels: type: discussion

**Comment by kalefranz** [comment] 2017-01-29 01:11
> when that error message happens is it possible for packages to be left in a partially installed state or something?

Not at all.  When that error is raised, conda hasn't even begun mutating the file system yet.  It sees one of the packages involved in the operation as invalid, so it's not going to proceed.  And even if it did start mutating the filesystem and something like that happened (or a permissions issue or anything else), conda would roll back the whole operation.
