### ISSUE TITLE
[BUG] Spectrogram example does not work

### ISSUE THREAD

**Issue by harmbuisman** [bokeh/bokeh#9178] opened 2019-08-20 18:47 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh.version: 1.3.4
python: 3.7.3
OS: Windows 10
browser: all

#### Description of expected behavior and the observed behavior
When I run the [spectrogram example](https://github.com/bokeh/bokeh/tree/master/examples/app/spectrogram), I get no output in the screen.

#### Complete, minimal, self-contained example code that reproduces the issue

run: bokeh serve spectrogram --show
from the console

#### Stack traceback and/or browser JavaScript console output
connection.js:182 Error: property WaterfallRenderer.gram_length wasn't declared
    at WaterfallRenderer.e.setv (has_props.js:238)
    at WaterfallRenderer.e [as constructor] (has_props.js:44)
    at WaterfallRenderer.e [as constructor] (model.js:11)
    at WaterfallRenderer.e [as constructor] (renderer.js:62)
    at new WaterfallRenderer (spectrogram:155)
    at Function.t._instantiate_object (document.js:284)
    at Function.t._instantiate_references_json (document.js:300)
    at Function.t.from_json (document.js:548)
    at connection.js:148
(anonymous) @ connection.js:182
connection.js:183 [bokeh] Failed to repull session Error: property WaterfallRenderer.gram_length wasn't declared

#### Screenshots or screencasts of the bug in action
![image](https://user-images.githubusercontent.com/7702207/63374998-3515c380-c38b-11e9-9c47-656ea7cf4f83.png)

**Comment by bryevdv** [comment] 2019-08-20 18:54
@harmbuisman I just confirmed this example is working fine on OSX. Do you have access to check on other platforms? Compiling extensions requires NodeJS, my first guess is that you have a too-old version or something along those lines on your system. Please add the output of `bokeh info` to your issue.

**Comment by harmbuisman** [comment] 2019-08-20 20:07
@bryevdv 
Python version      :  3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)]
IPython version     :  7.7.0
Tornado version     :  6.0.3
Bokeh version       :  1.3.4
BokehJS static path :  C:\ProgramData\Anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  v10.16.0
npm version         :  6.9.0

**Comment by mattpap** [comment] 2019-08-20 20:09
It looks like it may be Windows specific issue.

**Comment by juhasch** [comment] 2019-08-20 20:13
Actually, I have the same issue here on my Mac:
Python version      :  3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 14:38:56)
IPython version     :  7.7.0
Tornado version     :  6.0.3
Bokeh version       :  1.3.4
BokehJS static path :  /Users/juhasch/anaconda3/envs/opencv/lib/python3.7/site-packages/bokeh/server/static
node.js version     :  v12.8.1
npm version         :  6.10.2

**Comment by bryevdv** [comment] 2019-08-20 20:16
Well, this will be hard to pin down unless we can find a way to reproduce it. @harmbuisman @juhasch I guess my next suggestion would be to try other custom extension examples, e.g. from the docs or `examples/custom` to see if they work for you. For reference, everything is working fine for me with this configuration: 

> (base) ❯ bokeh info
Python version      :  3.7.4 (default, Aug  9 2019, 12:36:10)
IPython version     :  7.7.0
Tornado version     :  5.1.1
Bokeh version       :  1.3.5dev2
BokehJS static path :  /Users/bryan/work/bokeh/bokeh/server/static
node.js version     :  v10.13.0
npm version         :  6.10.3

**Comment by juhasch** [comment] 2019-08-20 20:21
Running `python custom_tool.py` gives me
```

bokeh-1.3.4.min.js:31 Uncaught Error: property DrawTool.source wasn't declared
    at DrawTool.e.setv (bokeh-1.3.4.min.js:31)
    at DrawTool.e [as constructor] (bokeh-1.3.4.min.js:31)
    at DrawTool.e [as constructor] (bokeh-1.3.4.min.js:31)
    at DrawTool.e [as constructor] (bokeh-1.3.4.min.js:31)
    at DrawTool.e [as constructor] (bokeh-1.3.4.min.js:31)
    at DrawTool.e [as constructor] (bokeh-1.3.4.min.js:31)
    at new DrawTool (custom_tool.html:100)
    at Function.t._instantiate_object (bokeh-1.3.4.min.js:31)
    at Function.t._instantiate_references_json (bokeh-1.3.4.min.js:31)
    at Function.t.from_json (bokeh-1.3.4.min.js:31)
```
In the Chrome console.

**Comment by bryevdv** [comment] 2019-08-20 20:24
This is due to https://github.com/bokeh/bokeh/pull/9171 which was merged yesterday. In general I recommend using/checking out the version of examples that corresponds to your actual release, since `master` may get ahead, e.g. start to use new features that are newer than your installed version.

**Comment by bryevdv** [comment] 2019-08-20 20:29
@mattpap I was going to close this issue but I decided to check that back-combat was maintained and it does not seem to be (a fresh build on master cannot run the 1.3.4 version example)

**Comment by juhasch** [comment] 2019-08-20 20:30
Thanks for your explanation. I agree, I should have used current master.

I came from the examples link of the Bokeh documentation. Maybe it would make sense to link to a stable version instead of master.

**Comment by bryevdv** [comment] 2019-08-20 20:31
> I came from the examples link of the Bokeh documentation. Maybe it would make sense to link to a stable version instead of master.

@juhasch  We generally do, with a `:bokeh-tree:` sphinx directive we wrote just for that purpose. Can you state exactly where you encountered the generic link to master?

**Comment by juhasch** [comment] 2019-08-20 20:33
It was on this page:
https://bokeh.pydata.org/en/latest/docs/gallery.html#gallery
For example `surface3d` links to https://github.com/bokeh/bokeh/blob/master/examples/app/surface3d

**Comment by mattpap** [comment] 2019-08-20 20:38
@bryevdv, how exactly it fails? I can't run spectrogram example due to pyaudio failing, but other examples seem to work fine under the setup you described.

**Comment by bryevdv** [comment] 2019-08-20 21:35
@mattpap 

<img width="423" alt="Screen Shot 2019-08-20 at 2 33 16 PM" src="https://user-images.githubusercontent.com/1078448/63386331-a63b8380-c357-11e9-9d2e-bef9321b52ef.png">



<img width="838" alt="Screen Shot 2019-08-20 at 2 34 02 PM" src="https://user-images.githubusercontent.com/1078448/63386372-c1a68e80-c357-11e9-813b-abec88f0dacf.png">

**Comment by bryevdv** [comment] 2019-08-20 21:40
@juhasch Oh, that may be more difficult unfortunately. The demo site is maintained and run completely separately from the docs (since it requires real servers) and is manually updated from time to time but not on any specific schedule or event. Ideally we would point to the version that that demo site has deployed, but there is not a good way to know that from within the docs.

**Comment by mattpap** [comment] 2019-08-20 21:44
Looking at library versions, you are using bokehjs 1.3.5dev and bokeh (extensions compiler) 1.3.4. This will fail. Extensions are compiled for specific bokehjs version. Based on your earlier comment, I expected you to use 1.3.4 example and 1.3.5 bokeh + bokehjs.

**Comment by bryevdv** [comment] 2019-08-20 22:22
Ah, I forgot when when I switched branches for the example the develop mode install mucked up my running bokeh. Tested more carefully, all good. Closing now.

**Closed by bryevdv** 2019-08-20 22:22 UTC
Labels: type: discussion

**Comment by harmbuisman** [comment] 2019-08-21 08:18
> Ah, I forgot when when I switched branches for the example the develop mode install mucked up my running bokeh. Tested more carefully, all good. Closing now.

Nice, thanks!

**Comment by yueyericardo** [comment] 2019-08-24 02:07
I also has this problem

**Comment by yueyericardo** [comment] 2019-08-24 02:15
```
 f3947e1fe - Bryanv/revert rtd (#9166) (6 days ago) <Bryan Van de Ven>
```
after I 
``` 
git checkout f3947e1fe
```
This works. There must be some bug recently.

**Comment by bryevdv** [comment] 2019-08-24 16:30
@yueyericardo Please read the discussion above. There were new features added recently and the version in master is ahead of the latest release. You need to check out the version of the example *corresponds to the version you have installed*
