### ISSUE TITLE
[BUG] Bokeh 2.3 PolyDraw & PolyEdit tools break unrelated callbacks

### ISSUE THREAD

**Issue by nitrocalcite** [bokeh/bokeh#11076] opened 2021-03-17 18:18 UTC
If the PolyDraw or PolyEdit tools are enabled in a Bokeh 2.3.0 plot, unrelated callbacks will fail apparently due to some icon problem.
This is a new bug that does not affect Bokeh 2.2.3.  

Here's a demonstration mostly ripped from the Bokeh documentation (though I can make it more minimal if you'd like):
```
from bokeh.models import PolyDrawTool, PolyEditTool
from bokeh.events import Tap
# setup figure with polydraw and polyedit tools
p = figure(x_range=(0, 10), y_range=(0, 10), width=400, height=400,
           title='Poly Edit Tool')
p1 = p.patches([], [], fill_alpha=0.4)
p2 = p.patches([[1, 2, 3]], [[3, 5, 2]], fill_color='green', fill_alpha=0.4)
c1 = p.circle([], [], size=10, color='red')
draw_tool = PolyDrawTool(renderers=[p1, p2])
edit_tool = PolyEditTool(renderers=[p1, p2], vertex_renderer=c1)

# Line A
p.add_tools(draw_tool, edit_tool)

# Line B
p.on_event(Tap, lambda event: print(event))

# show figure
import panel as pn
pn.panel(p).show()
```

If you have just Line A but not Line B, it works fine: draw & edit tools work as expected.

If you have just Line B but not Line A, it works fine: no draw or edit tools, but a message in the console on every `Tap`.

If you have both Line A and Line B with Bokeh 2.3.0, the callback is not executed on `Tap`, and you get the stack traces below.  Bokeh 2.2.3 shows the expected behavior, where the draw & edit tools work, but you also get a message in the console on every `Tap`.

I reproduced this with `Tap` and `MouseWheel` on both Chrome & Firefox, so it doesn't look like it's anything marginal.  The stack trace says something about validating custom icons, but as you can see, I'm not trying to override any icons.

I haven't tried other edit tools, but it seems that either `PolyDraw` or `PolyEdit` on their own is sufficient to cause this error.  It isn't necessary to be actively using the toolbars to get this error either, just having either of those tools on the toolbars is enough.

I'm not too familiar with Bokeh internals, so any workaround suggestions would be greatly appreciated.  Please let me know if there's anything else helpful I can provide!

#### Software version info
`bokeh 2.3.0` only; not reproducible on `bokeh 2.2.3`
`panel 0.11.1`
`python 3.8.5`
Firefox & Chrome; Windows 10

#### Stack traceback and/or browser JavaScript console output

JS Console error
```
bokeh.min.js?v=53a5940fe1028de5b74a0dfa95ff5b5d:588 [bokeh] Unhandled ERROR reply to 212FA1FDB2084C3DB3E0954B4932C18A: ValueError("failed to validate PolyDrawTool(id='1050', ...).custom_icon: invalid value: None; allowed values are string filenames, PIL.Image.Image instances, or RGB(A) NumPy arrays")
```

Python traceback
```
ERROR:bokeh.server.protocol_handler:error handling message
 message: Message 'PATCH-DOC' content: {'events': [{'kind': 'MessageSent', 'msg_type': 'bokeh_event', 'msg_data': {'event_name': 'tap', 'event_values': {'model': {'id': '1002'}, 'sx': 298, 'sy': 338, 'x': 7.906976744186047, 'y': 1.1396011396011396}}}], 'references': [{'type': 'PanTool', 'id': '1021', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'description': None, 'dimensions': 'both'}}, {'type': 'WheelZoomTool', 'id': '1022', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'description': None, 'dimensions': 'both', 'maintain_focus': True, 'zoom_on_axis': True, 'speed': 0.0016666666666666668}}, {'type': 'BoxAnnotation', 'id': '1027', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': False, 'level': 'overlay', 'visible': True, 'x_range_name': 'default', 'y_range_name': 'default', 'line_color': 'black', 'line_alpha': 1, 'line_width': 2, 'line_join': 'bevel', 'line_cap': 'butt', 'line_dash': [4, 4], 'line_dash_offset': 0, 'fill_color': 'lightgrey', 'fill_alpha': 0.5, 'hatch_color': 'black', 'hatch_alpha': 1, 'hatch_scale': 12, 'hatch_pattern': None, 'hatch_weight': 1, 'hatch_extra': {}, 'top': None, 'top_units': 'screen', 'bottom': None, 'bottom_units': 'screen', 'left': None, 'left_units': 'screen', 'right': None, 'right_units': 'screen', 'render_mode': 'canvas'}}, {'type': 'BoxZoomTool', 'id': '1023', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'description': None, 'dimensions': 'both', 'overlay': {'id': '1027'}, 'match_aspect': False, 'origin': 'corner'}}, {'type': 'SaveTool', 'id': '1024', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'description': None}}, {'type': 'ResetTool', 'id': '1025', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'description': None}}, {'type': 'HelpTool', 'id': '1026', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'description': 'Click the question mark to learn more about Bokeh plot tools.', 'redirect': 'https://docs.bokeh.org/en/latest/docs/user_guide/tools.html'}}, {'type': 'Selection', 'id': '1064', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'indices': [], 'line_indices': [], 'multiline_indices': {}}}, {'type': 'UnionRenderers', 'id': '1063', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True}}, {'type': 'ColumnDataSource', 'id': '1035', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'selected': {'id': '1064'}, 'selection_policy': {'id': '1063'}, 'data': {'xs': [], 'ys': []}}}, {'type': 'CDSView', 'id': '1039', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'filters': [], 'source': {'id': '1035'}}}, {'type': 'Patches', 'id': '1036', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'xs': {'field': 'xs'}, 'ys': {'field': 'ys'}, 'line_color': {'value': '#1f77b4'}, 'line_alpha': {'value': 1}, 'line_width': {'value': 1}, 'line_join': {'value': 'bevel'}, 'line_cap': {'value': 'butt'}, 'line_dash': {'value': []}, 'line_dash_offset': {'value': 0}, 'fill_color': {'value': '#1f77b4'}, 'fill_alpha': {'value': 0.4}, 'hatch_color': {'value': 'black'}, 'hatch_alpha': {'value': 1}, 'hatch_scale': {'value': 12}, 'hatch_pattern': None, 'hatch_weight': {'value': 1}, 'hatch_extra': {}}}, {'type': 'Patches', 'id': '1037', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'xs': {'field': 'xs'}, 'ys': {'field': 'ys'}, 'line_color': {'value': '#1f77b4'}, 'line_alpha': {'value': 0.1}, 'line_width': {'value': 1}, 'line_join': {'value': 'bevel'}, 'line_cap': {'value': 'butt'}, 'line_dash': {'value': []}, 'line_dash_offset': {'value': 0}, 'fill_color': {'value': '#1f77b4'}, 'fill_alpha': {'value': 0.1}, 'hatch_color': {'value': 'black'}, 'hatch_alpha': {'value': 1}, 'hatch_scale': {'value': 12}, 'hatch_pattern': None, 'hatch_weight': {'value': 1}, 'hatch_extra': {}}}, {'type': 'GlyphRenderer', 'id': '1038', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'level': 'glyph', 'visible': True, 'x_range_name': 'default', 'y_range_name': 'default', 'data_source': {'id': '1035'}, 'view': {'id': '1039'}, 'glyph': {'id': '1036'}, 'hover_glyph': None, 'nonselection_glyph': {'id': '1037'}, 'selection_glyph': 'auto', 'muted_glyph': None, 'muted': False}}, {'type': 'Selection', 'id': '1066', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'indices': [], 'line_indices': [], 'multiline_indices': {}}}, {'type': 'UnionRenderers', 'id': '1065', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True}}, {'type': 'ColumnDataSource', 'id': '1040', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'selected': {'id': '1066'}, 'selection_policy': {'id': '1065'}, 'data': {'xs': [[1, 2, 3]], 'ys': [[3, 5, 2]]}}}, {'type': 'CDSView', 'id': '1044', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'filters': [], 'source': {'id': '1040'}}}, {'type': 'Patches', 'id': '1041', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'xs': {'field': 'xs'}, 'ys': {'field': 'ys'}, 'line_color': {'value': '#1f77b4'}, 'line_alpha': {'value': 1}, 'line_width': {'value': 1}, 'line_join': {'value': 'bevel'}, 'line_cap': {'value': 'butt'}, 'line_dash': {'value': []}, 'line_dash_offset': {'value': 0}, 'fill_color': {'value': 'green'}, 'fill_alpha': {'value': 0.4}, 'hatch_color': {'value': 'black'}, 'hatch_alpha': {'value': 1}, 'hatch_scale': {'value': 12}, 'hatch_pattern': None, 'hatch_weight': {'value': 1}, 'hatch_extra': {}}}, {'type': 'Patches', 'id': '1042', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'xs': {'field': 'xs'}, 'ys': {'field': 'ys'}, 'line_color': {'value': '#1f77b4'}, 'line_alpha': {'value': 0.1}, 'line_width': {'value': 1}, 'line_join': {'value': 'bevel'}, 'line_cap': {'value': 'butt'}, 'line_dash': {'value': []}, 'line_dash_offset': {'value': 0}, 'fill_color': {'value': 'green'}, 'fill_alpha': {'value': 0.1}, 'hatch_color': {'value': 'black'}, 'hatch_alpha': {'value': 1}, 'hatch_scale': {'value': 12}, 'hatch_pattern': None, 'hatch_weight': {'value': 1}, 'hatch_extra': {}}}, {'type': 'GlyphRenderer', 'id': '1043', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'level': 'glyph', 'visible': True, 'x_range_name': 'default', 'y_range_name': 'default', 'data_source': {'id': '1040'}, 'view': {'id': '1044'}, 'glyph': {'id': '1041'}, 'hover_glyph': None, 'nonselection_glyph': {'id': '1042'}, 'selection_glyph': 'auto', 'muted_glyph': None, 'muted': False}}, {'type': 'PolyDrawTool', 'id': '1050', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'description': None, 'custom_icon': None, 'empty_value': None, 'renderers': [{'id': '1038'}, {'id': '1043'}], 'vertex_renderer': None, 'drag': True, 'num_objects': 0}}, {'type': 'Selection', 'id': '1068', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'indices': [], 'line_indices': [], 'multiline_indices': {}}}, {'type': 'UnionRenderers', 'id': '1067', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True}}, {'type': 'ColumnDataSource', 'id': '1045', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'selected': {'id': '1068'}, 'selection_policy': {'id': '1067'}, 'data': {'x': [], 'y': []}}}, {'type': 'CDSView', 'id': '1049', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'filters': [], 'source': {'id': '1045'}}}, {'type': 'Circle', 'id': '1046', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'x': {'field': 'x'}, 'y': {'field': 'y'}, 'line_color': {'value': 'red'}, 'line_alpha': {'value': 1}, 'line_width': {'value': 1}, 'line_join': {'value': 'bevel'}, 'line_cap': {'value': 'butt'}, 'line_dash': {'value': []}, 'line_dash_offset': {'value': 0}, 'fill_color': {'value': 'red'}, 'fill_alpha': {'value': 1}, 'hatch_color': {'value': 'black'}, 'hatch_alpha': {'value': 1}, 'hatch_scale': {'value': 12}, 'hatch_pattern': None, 'hatch_weight': {'value': 1}, 'hatch_extra': {}, 'angle': {'value': 0}, 'size': {'value': 10}, 'radius': None, 'radius_dimension': 'x', 'hit_dilation': 1}}, {'type': 'Circle', 'id': '1047', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'x': {'field': 'x'}, 'y': {'field': 'y'}, 'line_color': {'value': 'red'}, 'line_alpha': {'value': 0.1}, 'line_width': {'value': 1}, 'line_join': {'value': 'bevel'}, 'line_cap': {'value': 'butt'}, 'line_dash': {'value': []}, 'line_dash_offset': {'value': 0}, 'fill_color': {'value': 'red'}, 'fill_alpha': {'value': 0.1}, 'hatch_color': {'value': 'black'}, 'hatch_alpha': {'value': 1}, 'hatch_scale': {'value': 12}, 'hatch_pattern': None, 'hatch_weight': {'value': 1}, 'hatch_extra': {}, 'angle': {'value': 0}, 'size': {'value': 10}, 'radius': None, 'radius_dimension': 'x', 'hit_dilation': 1}}, {'type': 'GlyphRenderer', 'id': '1048', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'level': 'glyph', 'visible': True, 'x_range_name': 'default', 'y_range_name': 'default', 'data_source': {'id': '1045'}, 'view': {'id': '1049'}, 'glyph': {'id': '1046'}, 'hover_glyph': None, 'nonselection_glyph': {'id': '1047'}, 'selection_glyph': 'auto', 'muted_glyph': None, 'muted': False}}, {'type': 'PolyEditTool', 'id': '1051', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'description': None, 'custom_icon': None, 'empty_value': None, 'renderers': [{'id': '1038'}, {'id': '1043'}], 'vertex_renderer': {'id': '1048'}}}, {'type': 'Toolbar', 'id': '1028', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'tools': [{'id': '1021'}, {'id': '1022'}, {'id': '1023'}, {'id': '1024'}, {'id': '1025'}, {'id': '1026'}, {'id': '1050'}, {'id': '1051'}], 'logo': 'normal', 'autohide': False, 'active_drag': 'auto', 'active_inspect': 'auto', 'active_scroll': 'auto', 'active_tap': 'auto', 'active_multi': None}}, {'type': 'Title', 'id': '1003', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'level': 'annotation', 'visible': True, 'x_range_name': 'default', 'y_range_name': 'default', 'render_mode': 'canvas', 'text_color': '#444444', 'text_alpha': 1, 'text_font': 'helvetica', 'text_font_size': '13px', 'text_font_style': 'bold', 'text_line_height': 1, 'border_line_color': None, 'border_line_alpha': 1, 'border_line_width': 1, 'border_line_join': 'bevel', 'border_line_cap': 'butt', 'border_line_dash': [], 'border_line_dash_offset': 0, 'background_fill_color': None, 'background_fill_alpha': 1, 'text': 'Poly Edit Tool', 'vertical_align': 'bottom', 'align': 'left', 'offset': 0, 'standoff': 10}}, {'type': 'BasicTicker', 'id': '1014', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'num_minor_ticks': 5, 'desired_num_ticks': 6, 'base': 10, 'mantissas': [1, 2, 5], 'min_interval': 0, 'max_interval': None}}, {'type': 'BasicTickFormatter', 'id': '1059', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'precision': 'auto', 'use_scientific': True, 'power_limit_high': 5, 'power_limit_low': -3}}, {'type': 'AllLabels', 'id': '1061', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True}}, {'type': 'LinearAxis', 'id': '1013', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'level': 'guide', 'visible': True, 'x_range_name': 'default', 'y_range_name': 'default', 'axis_line_color': 'black', 'axis_line_alpha': 1, 'axis_line_width': 1, 'axis_line_join': 'bevel', 'axis_line_cap': 'butt', 'axis_line_dash': [], 'axis_line_dash_offset': 0, 'major_tick_line_color': 'black', 'major_tick_line_alpha': 1, 'major_tick_line_width': 1, 'major_tick_line_join': 'bevel', 'major_tick_line_cap': 'butt', 'major_tick_line_dash': [], 'major_tick_line_dash_offset': 0, 'minor_tick_line_color': 'black', 'minor_tick_line_alpha': 1, 'minor_tick_line_width': 1, 'minor_tick_line_join': 'bevel', 'minor_tick_line_cap': 'butt', 'minor_tick_line_dash': [], 'minor_tick_line_dash_offset': 0, 'major_label_text_color': '#444444', 'major_label_text_alpha': 1, 'major_label_text_font': 'helvetica', 'major_label_text_font_size': '11px', 'major_label_text_font_style': 'normal', 'major_label_text_align': 'center', 'major_label_text_baseline': 'alphabetic', 'major_label_text_line_height': 1.2, 'axis_label_text_color': '#444444', 'axis_label_text_alpha': 1, 'axis_label_text_font': 'helvetica', 'axis_label_text_font_size': '13px', 'axis_label_text_font_style': 'italic', 'axis_label_text_align': 'left', 'axis_label_text_baseline': 'bottom', 'axis_label_text_line_height': 1.2, 'bounds': 'auto', 'ticker': {'id': '1014'}, 'formatter': {'id': '1059'}, 'axis_label': '', 'axis_label_standoff': 5, 'major_label_standoff': 5, 'major_label_orientation': 'horizontal', 'major_label_overrides': {}, 'major_label_policy': {'id': '1061'}, 'major_tick_in': 2, 'major_tick_out': 6, 'minor_tick_in': 0, 'minor_tick_out': 4, 'fixed_location': None}}, {'type': 'BasicTicker', 'id': '1018', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'num_minor_ticks': 5, 'desired_num_ticks': 6, 'base': 10, 'mantissas': [1, 2, 5], 'min_interval': 0, 'max_interval': None}}, {'type': 'BasicTickFormatter', 'id': '1056', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'precision': 'auto', 'use_scientific': True, 'power_limit_high': 5, 'power_limit_low': -3}}, {'type': 'AllLabels', 'id': '1058', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True}}, {'type': 'LinearAxis', 'id': '1017', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'level': 'guide', 'visible': True, 'x_range_name': 'default', 'y_range_name': 'default', 'axis_line_color': 'black', 'axis_line_alpha': 1, 'axis_line_width': 1, 'axis_line_join': 'bevel', 'axis_line_cap': 'butt', 'axis_line_dash': [], 'axis_line_dash_offset': 0, 'major_tick_line_color': 'black', 'major_tick_line_alpha': 1, 'major_tick_line_width': 1, 'major_tick_line_join': 'bevel', 'major_tick_line_cap': 'butt', 'major_tick_line_dash': [], 'major_tick_line_dash_offset': 0, 'minor_tick_line_color': 'black', 'minor_tick_line_alpha': 1, 'minor_tick_line_width': 1, 'minor_tick_line_join': 'bevel', 'minor_tick_line_cap': 'butt', 'minor_tick_line_dash': [], 'minor_tick_line_dash_offset': 0, 'major_label_text_color': '#444444', 'major_label_text_alpha': 1, 'major_label_text_font': 'helvetica', 'major_label_text_font_size': '11px', 'major_label_text_font_style': 'normal', 'major_label_text_align': 'center', 'major_label_text_baseline': 'alphabetic', 'major_label_text_line_height': 1.2, 'axis_label_text_color': '#444444', 'axis_label_text_alpha': 1, 'axis_label_text_font': 'helvetica', 'axis_label_text_font_size': '13px', 'axis_label_text_font_style': 'italic', 'axis_label_text_align': 'left', 'axis_label_text_baseline': 'bottom', 'axis_label_text_line_height': 1.2, 'bounds': 'auto', 'ticker': {'id': '1018'}, 'formatter': {'id': '1056'}, 'axis_label': '', 'axis_label_standoff': 5, 'major_label_standoff': 5, 'major_label_orientation': 'horizontal', 'major_label_overrides': {}, 'major_label_policy': {'id': '1058'}, 'major_tick_in': 2, 'major_tick_out': 6, 'minor_tick_in': 0, 'minor_tick_out': 4, 'fixed_location': None}}, {'type': 'Grid', 'id': '1016', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'level': 'underlay', 'visible': True, 'x_range_name': 'default', 'y_range_name': 'default', 'grid_line_color': '#e5e5e5', 'grid_line_alpha': 1, 'grid_line_width': 1, 'grid_line_join': 'bevel', 'grid_line_cap': 'butt', 'grid_line_dash': [], 'grid_line_dash_offset': 0, 'minor_grid_line_color': None, 'minor_grid_line_alpha': 1, 'minor_grid_line_width': 1, 'minor_grid_line_join': 'bevel', 'minor_grid_line_cap': 'butt', 'minor_grid_line_dash': [], 'minor_grid_line_dash_offset': 0, 'band_fill_color': None, 'band_fill_alpha': 0, 'band_hatch_color': 'black', 'band_hatch_alpha': 1, 'band_hatch_scale': 12, 'band_hatch_pattern': None, 'band_hatch_weight': 1, 'band_hatch_extra': {}, 'bounds': 'auto', 'dimension': 0, 'axis': {'id': '1013'}, 'ticker': None}}, {'type': 'Grid', 'id': '1020', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'level': 'underlay', 'visible': True, 'x_range_name': 'default', 'y_range_name': 'default', 'grid_line_color': '#e5e5e5', 'grid_line_alpha': 1, 'grid_line_width': 1, 'grid_line_join': 'bevel', 'grid_line_cap': 'butt', 'grid_line_dash': [], 'grid_line_dash_offset': 0, 'minor_grid_line_color': None, 'minor_grid_line_alpha': 1, 'minor_grid_line_width': 1, 'minor_grid_line_join': 'bevel', 'minor_grid_line_cap': 'butt', 'minor_grid_line_dash': [], 'minor_grid_line_dash_offset': 0, 'band_fill_color': None, 'band_fill_alpha': 0, 'band_hatch_color': 'black', 'band_hatch_alpha': 1, 'band_hatch_scale': 12, 'band_hatch_pattern': None, 'band_hatch_weight': 1, 'band_hatch_extra': {}, 'bounds': 'auto', 'dimension': 1, 'axis': {'id': '1017'}, 'ticker': None}}, {'type': 'Range1d', 'id': '1005', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'bounds': None, 'min_interval': None, 'max_interval': None, 'start': 0, 'end': 10, 'reset_start': None, 'reset_end': None}}, {'type': 'Range1d', 'id': '1007', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True, 'bounds': None, 'min_interval': None, 'max_interval': None, 'start': 0, 'end': 10, 'reset_start': None, 'reset_end': None}}, {'type': 'LinearScale', 'id': '1009', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True}}, {'type': 'LinearScale', 'id': '1011', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': [], 'syncable': True}}, {'type': 'Plot', 'id': '1002', 'attributes': {'tags': [], 'name': None, 'js_property_callbacks': {}, 'js_event_callbacks': {}, 'subscribed_events': ['tap'], 'syncable': True, 'width': 400, 'height': 400, 'min_width': None, 'min_height': None, 'max_width': None, 'max_height': None, 'margin': [0, 0, 0, 0], 'width_policy': 'auto', 'height_policy': 'auto', 'aspect_ratio': None, 'sizing_mode': None, 'visible': True, 'disabled': False, 'align': 'start', 'background': None, 'css_classes': [], 'outline_line_color': '#e5e5e5', 'outline_line_alpha': 1, 'outline_line_width': 1, 'outline_line_join': 'bevel', 'outline_line_cap': 'butt', 'outline_line_dash': [], 'outline_line_dash_offset': 0, 'background_fill_color': '#ffffff', 'background_fill_alpha': 1, 'border_fill_color': '#ffffff', 'border_fill_alpha': 1, 'toolbar': {'id': '1028'}, 'toolbar_location': 'right', 'toolbar_sticky': True, 'frame_width': None, 'frame_height': None, 'title': {'id': '1003'}, 'title_location': 'above', 'above': [], 'below': [{'id': '1013'}], 'left': [{'id': '1017'}], 'right': [], 'center': [{'id': '1016'}, {'id': '1020'}], 'renderers': [{'id': '1038'}, {'id': '1043'}, {'id': '1048'}], 'x_range': {'id': '1005'}, 'extra_x_ranges': {}, 'y_range': {'id': '1007'}, 'extra_y_ranges': {}, 'x_scale': {'id': '1009'}, 'y_scale': {'id': '1011'}, 'lod_factor': 10, 'lod_interval': 300, 'lod_threshold': 2000, 'lod_timeout': 500, 'hidpi': True, 'output_backend': 'canvas', 'min_border': 5, 'min_border_top': None, 'min_border_left': None, 'min_border_bottom': None, 'min_border_right': None, 'inner_width': 344, 'inner_height': 351, 'outer_width': 400, 'outer_height': 400, 'match_aspect': False, 'aspect_scale': 1, 'reset_policy': 'standard'}, 'subtype': 'Figure'}]} 
 error: ValueError("failed to validate PolyDrawTool(id='1050', ...).custom_icon: invalid value: None; allowed values are string filenames, PIL.Image.Image instances, or RGB(A) NumPy arrays")
Traceback (most recent call last):
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\server\protocol_handler.py", line 90, in handle
    work = await handler(message, connection)
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\server\session.py", line 67, in _needs_document_lock_wrapper
    result = func(self, *args, **kwargs)
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\server\session.py", line 261, in _handle_patch
    message.apply_to_document(self.document, self)
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 100, in apply_to_document
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\document\document.py", line 1198, in _with_self_as_curdoc
    return f()
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\protocol\messages\patch_doc.py", line 100, in <lambda>
    doc._with_self_as_curdoc(lambda: doc.apply_json_patch(self.content, setter))
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\document\document.py", line 394, in apply_json_patch
    initialize_references_json(references_json, references, setter)
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\document\util.py", line 88, in initialize_references_json
    instance.update_from_json(obj_attrs, models=references, setter=setter)
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\core\has_props.py", line 469, in update_from_json
    self.set_from_json(k, v, models, setter)
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\core\has_props.py", line 411, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\core\property\descriptors.py", line 623, in set_from_json
    return super().set_from_json(obj, self.property.from_json(json, models), models, setter)
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\core\property\descriptors.py", line 327, in set_from_json
    self._internal_set(obj, json, setter=setter)
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\core\property\descriptors.py", line 784, in _internal_set
    value = self.property.prepare_value(obj, self.name, value)
  File "C:\Users\jokasinski\Miniconda3\lib\site-packages\bokeh\core\property\bases.py", line 350, in prepare_value
    raise ValueError(f"failed to validate {obj_repr}.{name}: {error}")
ValueError: failed to validate PolyDrawTool(id='1050', ...).custom_icon: invalid value: None; allowed values are string filenames, PIL.Image.Image instances, or RGB(A) NumPy arrays

```

**Comment by mattpap** [comment] 2021-03-17 18:20
This is a duplicate of issue #11028. A fix will be available in bokeh 2.3.1.

**Closed by mattpap** 2021-03-17 18:20 UTC
Labels: TRIAGE
