### ISSUE TITLE
Line tooltip appears when hovering off the line

### ISSUE THREAD

**Issue by gogrean** [bokeh/bokeh#3004] opened 2015-10-17 09:11 UTC
I have a plot with different tooltips for multiple glyphs (inverted triangles, circles, line). Hovering over the triangles and the circles behaves as expected, with the tooltip appearing only when the mouse is over the corresponding symbol. However, the tooltip associated with the line shows up in certain areas of the plot where there are no glyphs. The plot is here:
https://rawgit.com/gogrean/BokehAstroMaps/master/Lx-P.html

In the top-right part of the plot, hovering over the line looks okay. But as you move towards the bottom-left corner, moving the pointer away from the line (e.g. at x=2, y=1) also shows the line tooltip. 

The code is here:
https://rawgit.com/gogrean/BokehAstroMaps/master/halos.py

I've also tested the code with linear axes. As expected, the difference between the various corners of the figure disappears, but the tooltip still appears when hovering near the line rather than over it. Also, the problem gets worse if the line is defined only by two points; in this case the tooltip will appear only when hovering near the ends of the plotted segment.

I'm using Bokeh 0.10.0.

I'm guessing this might related to [#3002](https://github.com/bokeh/bokeh/issues/3002).

**Comment by jaredsagendorf** [comment] 2016-02-09 23:59
I ran your code using 0.11.0 and the issue with the line tooltip seems to be fixed! I get a few warnings, but no weird hovering behaviour.

**Comment by bryevdv** [comment] 2016-04-08 20:20
Reported as fixed, so closing. Please re-open if the problem can still be reproduced on Bokeh later than  `0.11.1`

**Closed by bryevdv** 2016-04-08 20:20 UTC
Labels: type: discussion
