### ISSUE TITLE
Reuse plots from python into BokehJS standalone version.

### ISSUE THREAD

**Issue by tavinashb** [bokeh/bokeh#8205] opened 2018-09-03 12:34 UTC
I have exported JSON configuration of existing chart which is created using python base bokehjs library.
  
And want to import this same json configuration  into standalone BokehJS library to a create chart.

Is there any api/function to import this configuration?

Unable to find import api into standalone BokehJS library documentation.

**Comment by bryevdv** [comment] 2018-09-03 22:00
This is a duplicate of https://github.com/bokeh/bokeh/issues/5231

**Closed by bryevdv** 2018-09-03 22:00 UTC
