### ISSUE TITLE
Graphical bugs with webgl and time series data with NaN points

### ISSUE THREAD

**Issue by jnettels** [bokeh/bokeh#8489] opened 2018-12-07 12:52 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 1.0.2
Python 3.7
Windows 10
Edge, Firefox, Chrome

#### Description of expected behavior and the observed behavior

``webgl`` and ``canvas`` should show the same visuals. However, when using ``webgl`` in a time series line plot figure containing ``NaN`` points, two graphical glitches happen:

1. When zooming way out, some sort of "spikes" appear. The gradients in the line plot are somehow over-accentuated
2. Points before and after the ``NaN`` point are not visible (but the Hovertool still shows the tip over the invisible point!)

#### Complete, minimal, self-contained example code that reproduces the issue

This example shows ``webgl`` left and ``canvas`` right and starts zoomed out to show issue (1). To see the missing points (2), you need to zoom in. Removing the ``NaN`` points from the data prevents the issues.

```
# -*- coding: utf-8 -*-
import pandas as pd
from bokeh.plotting import figure, show
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.layouts import row

x_col = 'TIME'
df = pd.DataFrame(
        index=pd.DatetimeIndex(data=['2019-02-14 05:00:00',
                                     '2019-02-14 06:00:00',
                                     '2019-02-14 07:00:00',
                                     '2019-02-14 08:00:00',
                                     '2019-02-14 09:00:00',
                                     '2019-02-14 10:00:00',
                                     '2019-02-14 11:00:00',
                                     '2019-02-14 12:00:00',
                                     '2019-02-14 13:00:00',
                                     '2019-02-14 14:00:00',
                                     '2019-02-14 15:00:00',
                                     '2019-02-14 16:00:00',
                                     '2019-02-14 17:00:00',
                                     '2019-02-14 18:00:00',
                                     '2019-02-14 19:00:00',
                                     '2019-02-14 20:00:00',
                                     ],
                               name=x_col),

        data={'foo': [float('NaN'),  # No problem without the NaN points
                      89.59150207,  # Point is missing from p1 (with webgl)
                      90.13185525,
                      90.87019377,
                      91.50974425,
                      91.9689919,
                      92.37495685,
                      88.57351308,
                      91.43121534,
                      90.5798877,
                      89.56249558,
                      88.77421971,
                      88.30047269,
                      87.90554157,
                      44.65552427,  # Point is missing from p1 (with webgl)
                      float('NaN'),  # No problem without the NaN points
                      ],
              'bar': [60]*16,
              })

print(df)

# When zoomed way out, the webgl plot shows some strange "spikes"
x_range = (pd.Timestamp(2019, 1, 1), pd.Timestamp(2019, 12, 1))
p1 = figure(x_axis_type='datetime', x_range=x_range, output_backend='webgl',
           active_scroll='wheel_zoom', title='webgl')
p2 = figure(x_axis_type='datetime', x_range=p1.x_range, y_range=p1.y_range,
            active_scroll='wheel_zoom', title='canvas')

source = ColumnDataSource(data=df)
for y_col in df.columns:
    p1.line(x_col, y_col, legend=y_col+' ', source=source, name=y_col)
    p2.line(x_col, y_col, legend=y_col+' ', source=source, name=y_col)

hover1 = HoverTool(tooltips='$name: @$name')
hover2 = HoverTool(tooltips=[('$name', '@$name'),  # '$name' not supported
                             (x_col, ' @{'+x_col+'}{%y-%m-%d %H:%M:%S}')],
                   formatters={'TIME': 'datetime'})
p1.add_tools(hover1)
p2.add_tools(hover2)

show(row(p1, p2))

```

#### Screenshots or screencasts of the bug in action
![webgl_bug](https://user-images.githubusercontent.com/8526498/49647816-071e6800-fa24-11e8-8da4-c5f0fad42a21.PNG)

Now that I have written it, I realize this seems like a dublicate/summary of issues #7568 and #5939

**Comment by bryevdv** [comment] 2018-12-07 17:37
I agree this is a duplicate of both those issues, I am going to close the others and keep this one because it has the most useful MRE and description.

**Comment by bryevdv** [comment] 2020-08-25 04:34
Noting that the bad webgl line rendering was noticed again recently in a different context. The solution will hopefully be the switch to instanced line rendering with ReGL later this year

**Comment by ode45** [comment] 2020-09-08 16:07
> Noting that the bad webgl line rendering was noticed again recently in a different context. The solution will hopefully be the switch to instanced line rendering with ReGL later this year

Thanks, looking forward to that, because I still have the same issue as in #5939. I have slightly updated it's example below.

Inserting a single NaN messes up the time series after this NaN in a WebGL line plot, the values go outside the range of (-1,1). 

![image](https://user-images.githubusercontent.com/8698082/92500219-2354c780-f1fd-11ea-93a0-7b950e6fc68f.png)

```python
import bokeh
from bokeh.plotting import figure
from bokeh.io import output_notebook, show
from bokeh.layouts import column, row
import numpy as np

output_notebook()

bokeh.__version__

n = 1000
x = np.linspace(0, 1, n)
y = np.sin(400*x)
x_nan = x.copy()
x_nan[500] = np.nan

p_gl = figure(plot_width=450, output_backend='webgl')
p_gl.line(x, y)
p_gl_nan = figure(plot_width=450, output_backend='webgl')
p_gl_nan.line(x_nan, y)
show(row(p_gl, p_gl_nan))
```

**Closed** 2020-11-24 21:30 UTC
Labels: reso: completed, tag: component: bokehjs, tag: webgl, type: bug
