### ISSUE TITLE
App drop-downs under Firefox are the wrong size

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#1710] opened 2015-01-15 12:07 UTC
Looking at the `app/stock_applet/stock_app.py` example, the ticker symbol dropdowns/selection boxes in the top left are sized so the text is not visible using latest Firefox.  Looks fine in Chrome:

![screenshot 2015-01-15 07 05 15](https://cloud.githubusercontent.com/assets/293525/5757053/38fe31a8-9c85-11e4-9f15-3a12a8798477.png)

**Comment by damianavila** [comment] 2015-01-15 12:52
I have seen this before... can you report which version of firefox? Thanks

**Comment by mattpap** [comment] 2015-01-15 14:21
I can confirm in FF 34.

**Comment by mattpap** [comment] 2015-01-15 14:24
Also reloading page gives `ValueError: No JSON ...` and server gives `DeserializationError: Instance(PlotObject) failed to deserialize {u'type': u"SockApp", u'id': 'u'...'}`.

**Comment by bald** [comment] 2015-05-27 15:09
Same on FF 38 (Ubuntu).

**Comment by bryevdv** [comment] 2016-04-10 02:50
This is evidently still an issue with the latest `0.12dev` I believe the fix for this will fall out of the comprehensive layout worn in progress by @birdsarah

**Comment by birdsarah** [comment] 2016-05-28 16:37
Confirm as part of #4392

**Comment by bryevdv** [comment] 2016-06-09 00:56
current new Bokeh server version of this app working now on master, FF 47 / OSX

<img width="595" alt="screen shot 2016-06-08 at 7 54 20 pm" src="https://cloud.githubusercontent.com/assets/1078448/15915917/0382693e-2db3-11e6-97fb-ba572942fa62.png">

**Comment by bryevdv** [comment] 2016-06-09 00:56
Please re-open if the problem is found to persist

**Closed by bryevdv** 2016-06-09 00:56 UTC
Labels: plat: firefox, tag: component: examples, type: bug
