### ISSUE TITLE
IE11 dies when I click on items from MultiSelect

### ISSUE THREAD

**Issue by jungwu** [bokeh/bokeh#6537] opened 2017-06-26 11:17 UTC
Version:
OS: Windows 7
PC: 64bit
Browser: IE11, Chrome (59.0.3071.109)
Anadonda: Installed Anaconda3-4.4.0-Windows-x86_64  (but when I run "conda --versio", it prints out "conda 4.3.22"
Python: Python 3.6.1 :: Anaconda custom (64-bit)
Bokeh: 0.12.6 (Upgraded by using "conda install bokeh"

Problem 1:
I run the following code and IE11 is launched. The web page on IE11 renders OK initially but when I clicks on any one of items from MultiSelect widget, the browser dies. It works fine on Chrome browser. 

Problem 2:
I could not make a minimal version for this problem from the original version. The problem is that bokeh keeps throwing this kind of Warning:

Warning: ColumnDataSource's columns must be of the same length. Current lengths:
 ('ap', 10), ('color', 10), ('label', 10), ('pct', 20)
Warning: ColumnDataSource's columns must be of the same length. Current lengths:
 ('rate', 17), ('reason', 17), ('time', 34)

The pattern here is that one of ColumnDataSource length is always double the others. 

Initially I tried using bokeh 0.12.5, which is the version contained in  Anaconda3-4.4.0-Windows-x86_64 distribution but I ran into the same issue as https://github.com/bokeh/bokeh/issues/6127. So I upgraded bokeh to the latest 0.12.6.

Here is the minimal code:

```
from bokeh.plotting import figure
from bokeh.layouts import layout, widgetbox, row, column
from bokeh.models import ColumnDataSource, HoverTool, Div, ranges, LabelSet, DatetimeTickFormatter
from bokeh.models.widgets import Slider, Select, TextInput, PreText, MultiSelect
from bokeh.io import curdoc, output_notebook, show
from bokeh.models.ranges import FactorRange


model_group_sel = MultiSelect(title="Model Group:", value=[],
                           options=[(a, a) for a in ['M1', 'M2', 'M3']])


source_reason_pct = ColumnDataSource(data=dict(reason=[], percent=[], meaning=[]))
disc_reason_dist_p = figure(plot_height=300, plot_width=900, title="Distribution",
                            x_axis_label='Reason Code',
                            y_axis_label='Percent',
                            x_range=FactorRange(factors=[]),
                            y_range = ranges.Range1d(start=0, end=100)
                            )

disc_reason_dist_p.vbar(x='reason', top='percent', width=0.7, source=source_reason_pct)
disc_reason_dist_p.xaxis.major_label_orientation = 3.14 / 2


def update_disc_reason_dist(sel_data):

    source_reason_pct.data = dict(
        reason = [str(i) for i in range(69)],
        percent = [100*i for i in range(69)],
        meaning = [str(i) for i in range(69)]
    )
    disc_reason_dist_p.x_range.factors = list(source_reason_pct.data['reason'])
    disc_reason_dist_p.y_range = ranges.Range1d(start=0, end=100)


def update_on_model_group_sel(selected=[]):
    update_disc_reason_dist(selected)

update_on_model_group_sel()


model_group_sel.on_change('value', lambda attr, old, new: update_on_model_group_sel(selected=new))

sizing_mode = 'fixed'

inputs = column(model_group_sel,
                sizing_mode=sizing_mode)

graphs = column(disc_reason_dist_p,
                sizing_mode=sizing_mode)

l = layout([
    [inputs, graphs],
], sizing_mode=sizing_mode)

curdoc().add_root(l)
curdoc().title = "Plot testing"

```

Here is console output when IE11 crashed:

(C:\Users\admin\Anaconda3) C:\Users\admin\Documents\PythonProj\data_dashboard>bo
keh serve --show wifi_dashbd3_new.py
2017-06-26 20:15:38,999 Starting Bokeh server version 0.12.6 (running on Tornado
 4.5.1)
2017-06-26 20:15:39,044 Starting Bokeh server on port 5006 with applications at
paths ['/wifi_dashbd3_new']
2017-06-26 20:15:39,044 Starting Bokeh server with process id: 9856
C:\Users\admin\Documents\PythonProj\data_dashboard\wifi_dashbd3_new.py:65: UserW
arning: This pattern has match groups. To actually get the groups, use str.extra
ct.
  df = df[~df.ld_fwv.str.contains(patt)]
['6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6',
 '6']
DatetimeIndex(['2017-03-12', '2017-03-13', '2017-03-14', '2017-03-15',
               '2017-03-16', '2017-03-17', '2017-03-18', '2017-04-02',
               '2017-04-03', '2017-04-04', '2017-04-05', '2017-04-06',
               '2017-04-07', '2017-04-18', '2017-04-19', '2017-04-21',
               '2017-04-22'],
              dtype='datetime64[ns]', freq=None)
[0.03444021243495521, 0.03283375205752404, 0.02985674792661473, 0.02898348157560
3556, 0.0315353478301798, 0.035215637604716105, 0.027334500154432204, 0.08731265
249215754, 0.08863796753705011, 0.06499215070643642, 0.07381636666162457, 0.0415
92058555586967, 0.03550295857988166, 0.05408062930186824, 0.0326530612244898, 0.
045280799764775066, 0.11621621621621622]
<class 'list'>
<class 'list'>
<class 'list'>
update_access_point_distrib
['6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6', '6',
 '6']
DatetimeIndex(['2017-03-12', '2017-03-13', '2017-03-14', '2017-03-15',
               '2017-03-16', '2017-03-17', '2017-03-18', '2017-04-02',
               '2017-04-03', '2017-04-04', '2017-04-05', '2017-04-06',
               '2017-04-07', '2017-04-18', '2017-04-19', '2017-04-21',
               '2017-04-22'],
              dtype='datetime64[ns]', freq=None)
[0.03444021243495521, 0.03283375205752404, 0.02985674792661473, 0.02898348157560
3556, 0.0315353478301798, 0.035215637604716105, 0.027334500154432204, 0.08731265
249215754, 0.08863796753705011, 0.06499215070643642, 0.07381636666162457, 0.0415
92058555586967, 0.03550295857988166, 0.05408062930186824, 0.0326530612244898, 0.
045280799764775066, 0.11621621621621622]
<class 'list'>
<class 'list'>
<class 'list'>
update_access_point_distrib
2017-06-26 20:15:58,058 200 GET /wifi_dashbd3_new (::1) 17936.03ms
2017-06-26 20:15:58,447 101 GET /wifi_dashbd3_new/ws?bokeh-protocol-version=1.0&
bokeh-session-id=bAQBLxRxvfC6YYr9qFaa9nMK6YsSAxqYcVGw5dvlbdNY (::1) 0.00ms
2017-06-26 20:15:58,448 WebSocket connection opened
2017-06-26 20:15:58,448 ServerConnection created
C:\Users\admin\Anaconda3\lib\site-packages\bokeh\models\sources.py:91: BokehUser
Warning: ColumnDataSource's columns must be of the same length. Current lengths:
 ('rate', 17), ('reason', 17), ('time', 34)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.ite
ms())), BokehUserWarning))
C:\Users\admin\Anaconda3\lib\site-packages\bokeh\models\sources.py:91: BokehUser
Warning: ColumnDataSource's columns must be of the same length. Current lengths:
 ('ap', 10), ('color', 10), ('label', 10), ('pct', 20)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.ite
ms())), BokehUserWarning))
C:\Users\admin\Anaconda3\lib\site-packages\bokeh\models\sources.py:91: BokehUser
Warning: ColumnDataSource's columns must be of the same length. Current lengths:
 ('rate', 17), ('reason', 17), ('time', 34)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.ite
ms())), BokehUserWarning))
C:\Users\admin\Anaconda3\lib\site-packages\bokeh\models\sources.py:91: BokehUser
Warning: ColumnDataSource's columns must be of the same length. Current lengths:
 ('ap', 10), ('color', 10), ('label', 10), ('pct', 20)
  "Current lengths: %s" % ", ".join(sorted(str((k, len(v))) for k, v in data.ite
ms())), BokehUserWarning))
['6', '6', '6', '6', '6', '6', '6', '6', '6', '6']
DatetimeIndex(['2017-04-02', '2017-04-03', '2017-04-04', '2017-04-05',
               '2017-04-06', '2017-04-07', '2017-04-18', '2017-04-19',
               '2017-04-21', '2017-04-22'],
              dtype='datetime64[ns]', freq=None)
[0.08731265249215754, 0.08863796753705011, 0.06499215070643642, 0.07381636666162
457, 0.003848207834637012, 0.022559171597633137, 0.05408062930186824, 0.03265306
12244898, 0.045280799764775066, 0.11621621621621622]
<class 'list'>
<class 'list'>
<class 'list'>
update_access_point_distrib
2017-06-26 20:16:10,693 WebSocket connection closed: code=None, reason=None

**Comment by mattpap** [comment] 2017-06-26 12:04
> I run the following code and IE11 is launched. The web page on IE11 renders OK initially but when I clicks on any one of items from MultiSelect widget, the browser dies. It works fine on Chrome browser.

This is likely duplicate of #6333.

> Warning: ColumnDataSource's columns must be of the same length. Current lengths:

Looking at the code, it may be an issue with `vbar()` method. We need to investigate this.

**Comment by jungwu** [comment] 2017-06-26 13:26
I tried the same code on IE11  version 11.1358.14393, which I use at home and it works ok. I will check the version of IE11 used in my company, in which I found the above symptom.

**Comment by mattpap** [comment] 2017-06-26 13:32
> I tried the same code on IE11 version 11.1358.14393, which I use at home and it works ok.

Unfortunately to all of us, IEs can differ a lot between minor versions. We have had issues like this already.

**Comment by jungwu** [comment] 2017-06-27 01:34
Just for your information, IE11 11.0.9600.18697 shows the symptom.

**Comment by jungwu** [comment] 2017-06-27 01:51
Following #6333, I tried dev build (0.12.7dev3) but there is no improvement.

**Comment by bryevdv** [comment] 2019-03-08 00:29
This was a dupe of #6333 and as noted there things are working with recent builds (the code above also seems fine on Win10 / IE11)

**Closed by bryevdv** 2019-03-08 00:29 UTC
Labels: plat: ie, plat: windows, tag: component: bokehjs, tag: widgets, type: bug
