### ISSUE TITLE
[BUG] color.darken() triggers BokehDeprecationWarning as it uses HSL related methods internally

### ISSUE THREAD

**Issue by cirnod** [bokeh/bokeh#11845] opened 2021-11-30 10:14 UTC
### Software versions

Python version      :  3.8.10 (default, Sep 28 2021, 16:10:42) 
IPython version     :  (not installed)
Tornado version     :  6.1
Bokeh version       :  2.4.2
BokehJS static path :  /home/xxx/.virtualenvs/test/lib/python3.8/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.4.0-90-generic-x86_64-with-glibc2.29

### Expected behavior

Call to color.darken() does not produce BokehDeprecationWarning. 

### Observed behavior

Call to `color.darken()` produces `BokehDeprecationWarning`:
> BokehDeprecationWarning: HSL() was deprecated in Bokeh 2.3.1 and will be removed, use RGB() or named colors instead.

This is unexpected since I don't use any HSL related object/method when calling `color.darken`. As far as I understand, HSL related methods are only used inside `darken`. 

### Example code

```Python
from bokeh.colors.named import red
red.darken(0.2)
```

**Comment by g-parki** [comment] 2021-11-30 19:01
Thank you @cirnod. As you noted, it looks like HSL is still used internally for both `lighten()` and `darken()`. These should be replaced with an RGB equivalent. I believe this is a pure Python issue, and the RGB methods already exist, so I'll mark it as a Good First Issue.
### Here's where the issue is first found, among other places in the same file:
https://github.com/bokeh/bokeh/blob/69c578373d8d7a0aced34c2493ae4b3a7f072959/bokeh/colors/color.py#L87-L100

### Contributor guide:
https://docs.bokeh.org/en/latest/docs/dev_guide.html

### Required test to update:
_Note, the test should probably be completely overhauled to use RGB instead of HSL in the test itself_
https://github.com/bokeh/bokeh/blob/branch-3.0/tests/unit/bokeh/colors/test_color__colors.py

**Comment by g-parki** [comment] 2021-11-30 20:24
# Good first issue
This issue has been labeled “good first issue”. This means it should be especially well suited for new contributors. 

In general, good First Issues are:
* Self-contained: only involving limited aspects of Bokeh and optimally only requiring changes to one or two files
* Easily explainable: A potential solution can be described without going too much into the details of how Bokeh works

---

## Description of the issue

HSL has been deprecated in Bokeh, but was found to be internally used for darkening/lightening colors. Colors themselves can be defined without using HSL, so this deprecation warning is unexpected by the user.

This issue is important to fix so Bokeh can remain consistent use of HSL. If the users can't use it, neither should we!

A Pull Request resolving this issue should include:
- Updated `lighten()` and `darken()` methods in [code.py](https://github.com/bokeh/bokeh/blob/branch-3.0/bokeh/colors/color.py) to use RGB instead of HSL
- Updated tests in [test_color__colors.py](https://github.com/bokeh/bokeh/blob/branch-3.0/tests/unit/bokeh/colors/test_color__colors.py)

## Prerequisites

For this issue, you should have a basic understanding of Object Oriented Programming in Python.
Before getting started with a Pull Request, you need to set up a development environment. Please follow the step-by-step instructions in [Setting up a development environment](https://docs.bokeh.org/en/latest/docs/dev_guide/setup.html#contributor-guide-setup). 

## Solution walkthrough

These are the steps that will most likely get this issue resolved:

- Take a look at the code to see how the `Color` base class is used, as well as those classes which inherit from `Color`
- Replace the HSL methods in `lighten()` and `darken()` with RGB methods for an equivalent output
- Replace HSL use in the unit test mentioned above
- Run all unit and codebase tests

Once you decide to work on this issue, please leave a note right here in the discussion to make sure no one else is working on this issue at the same time!

## Getting help

Bokeh developers are usually monitoring active issues and pull requests. Feel free to ask questions anytime, here in this issue or your pull request! You also have the option to tag ``@bokeh/dev`` in your message.

Also, check the [Additional resources](https://docs.bokeh.org/en/latest/docs/dev_guide.html#additional-resources) section in our contributor guide for more information on the various resources you can use to get help with your contribution. 

Please keep in mind that Bokeh is an open-source project mostly run by volunteers. Therefore, it might take some time to get an answer to a question or feedback on a pull request!

---

## Other ways to support Bokeh

If you feel like fixing this issue is just not the right way for you to support Bokeh, take a look at other issues with the ["good first issue" label](https://github.com/bokeh/bokeh/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22). There are also many other ways to support Bokeh, see [More ways to contribute](https://docs.bokeh.org/en/latest/docs/dev_guide.html#more-ways-to-contribute) for some ideas.

**Comment by yanchenm** [comment] 2021-11-30 22:54
Hi I'd like to take a crack at this :)

**Comment by theebank** [comment] 2021-12-03 00:30
If this issue is still open I'm gonna give it a try

**Comment by cuevasm1** [comment] 2021-12-05 19:29
Me too

**Comment by axie1234** [comment] 2021-12-07 06:28
I would also like to take a crack at this!

**Comment by bryevdv** [comment] 2021-12-07 17:35
Hi @theebank @cuevasm1 @axie1234 @yanchenm Thank you all for your interest. If the issue is still open on GH, and there is no linked PR, then no one has yet submitted any work for the issues. We can only accept one PR for this issue, so I'd encourage everyone here to be as courteous and transparent as possible (if you have local work-in-progress, an a submission is imminent, please state that, or better yet, just submit a WIP PR so that others can know work is already underway).

We are working to identify and label more "Good First Issues" with the more detailed work template. In the mean time, there is another "open ended" issue that lots of people can pitch in on here: https://github.com/bokeh/bokeh/issues/11765

**Comment by cuevasm1** [comment] 2021-12-07 17:47
I’ve already fixed the issue and just doing the final unit test. Will be pushing shortly

**Comment by woocy50** [comment] 2021-12-08 03:24
The above PR (#11865) was developed in tandum with @cuevasm1

**Closed** 2021-12-15 17:18 UTC
Labels: type: task, good first issue
