### ISSUE TITLE
"lock" or "freeze" a plot would be really useful

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#2113] opened 2015-03-28 01:47 UTC
I am *constantly* scrolling through web pages with Bokeh plots on them and as the page scrolls by my mouse pointer, Bokeh catches the events and does crazy things with the graph.  Often this completely captures my mouse events, so I can't keep scrolling, so now I have two problems: messed up visual (it just scrolled onto the screen before being messed up, so I don't even know what it was "supposed" to look like) plus I can't keep scrolling

I bet everyone has had this very frustrating experience  Maybe daily.  Maybe hourly.

I'd recommend *an option*, and Bokeh plot creation time, that allows the author to freeze all mouse events pending some "release" action (lock icon, click on image, key press, etc.)

**Comment by bryevdv** [comment] 2015-03-28 02:44
dupe of #1450

**Comment by bryevdv** [comment] 2015-03-28 02:45
dupe of #1450

**Closed by bryevdv** 2015-03-28 02:44 UTC
Labels: reso: duplicate

**Comment by ijstokes** [comment] 2015-03-28 10:09
Could I ask for a quick clarification?  Does this mean what I'm asking for is already possible?  I still want to be able to interact with the plot "as normal" after taking some action that will "enable" normal interactivity.  So how, as the plot creator, to I achieve this?

Or is #1450 saying that you have agreed that "in the future" this capability should be possible?  #1450 is just too brief for me, as an outsider, to understand what it is saying or the implications are.

**Comment by bryevdv** [comment] 2015-03-28 13:05
@ijstokes Sorry. #1450 was changed from "discussion" to "feature" so it is intended to be implemented. However, this issue is open and not marked with a resolution, so it has not been implemented, yet. Issue and PR lifecycle management policy is described in https://github.com/bokeh/bokeh/wiki/BEP-1:-Issues-and-PRs-management
