### ISSUE TITLE
gulp test complains about "unknown edit variable"

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#5222] opened 2016-09-23 16:22 UTC
Tests are all green.

**Comment by birdsarah** [comment] 2016-09-24 05:08
dupe of #4539?

**Comment by birdsarah** [comment] 2016-09-24 05:09
In particular see my final guess on the issue:

It seems to be a glitch in stubbing the solver, and I would say a race condition given that it doesn't always happen. It seemed to happen more when the fixed mode performance improvement was added - which may be because there's less initialization time.

It's often plot_canvas.update_constraints that's triggering the call to update_solver; but not always.

**Closed** 2016-12-09 16:22 UTC
Labels: reso: duplicate, tag: component: bokehjs, tag: component: tests, type: bug
