### ISSUE TITLE
[BUG] could not resolve type DrawTool which could be due to a widget or a custom model not being registered

### ISSUE THREAD

**Issue by zcyounger** [bokeh/bokeh#13995] opened 2024-07-23 09:25 UTC
### Software versions

- Python version : 3.8.0(default)
- IPython version: 8.12.3
- Tornado version: 6.1
- Bokeh version: 3.1.1
- BokehJS static path: /path/to/lib/python3.8/site_packages/bokeh/server/static
- node.js version: v14.21.3
- npm version: 6.14.18
- Operating system: Linux-5.15.0-69-generic-x86_64-with-glibc2.27 

### Jupyter notebook / Jupyter Lab version

jupyterlab:3.2.4

### Expected behavior

Generate the same interaction diagram as in [(https://docs.bokeh.org/en/3.1.1/docs/user_guide/advanced/extensions/tool.html#ug-advanced-extensions-examples-tool)]

### Observed behavior

Javascript Error: could not resolve type DrawTool which could be due to a widget or a custom model not being registered

### Example code

```Python
from bokeh.core.properties import Instance
from bokeh.models import ColumnDataSource, Tool
from bokeh.plotting import figure, show
from bokeh.util.compiler import TypeScript

CODE = """
import {GestureTool, GestureToolView} from "models/tools/gestures/gesture_tool"
import {ColumnDataSource} from "models/sources/column_data_source"
import {PanEvent} from "core/ui_events"
import * as p from "core/properties"

export class DrawToolView extends GestureToolView {
  declare model: DrawTool

  // this is executed when the pan/drag event starts
  _pan_start(_e: PanEvent): void {
    this.model.source.data = {x: [], y: []}
  }

  // this is executed on subsequent mouse/touch moves
  _pan(e: PanEvent): void {
    const {frame} = this.plot_view
    const {sx, sy} = e

    if (!frame.bbox.contains(sx, sy))
      return

    const x = frame.x_scale.invert(sx)
    const y = frame.y_scale.invert(sy)

    const {source} = this.model
    source.get_array("x").push(x)
    source.get_array("y").push(y)
    source.change.emit()
  }

  // this is executed then the pan/drag ends
  _pan_end(_e: PanEvent): void {}
}

export namespace DrawTool {
  export type Attrs = p.AttrsOf<Props>

  export type Props = GestureTool.Props & {
    source: p.Property<ColumnDataSource>
  }
}

export interface DrawTool extends DrawTool.Attrs {}

export class DrawTool extends GestureTool {
  declare properties: DrawTool.Props
  declare __view_type__: DrawToolView

  constructor(attrs?: Partial<DrawTool.Attrs>) {
    super(attrs)
  }

  tool_name = "Draw Tool"
  tool_icon = "bk-tool-icon-lasso-select"
  event_type = "pan" as "pan"
  default_order = 12

  static {
    this.prototype.default_view = DrawToolView

    this.define<DrawTool.Props>(({Ref}) => ({
      source: [ Ref(ColumnDataSource) ],
    }))
  }
}
"""

class DrawTool(Tool):
    __implementation__ = TypeScript(CODE)
    source = Instance(ColumnDataSource)

from bokeh.plotting import figure
from bokeh.io import show output_notebook
import bokeh
from typing import get_args
with open("/path/to/jquery/jquery-3.1.1.min.js") as f:
    raw = f.read()
bokeh.io.notebook.publish_display_data(
    {bokeh.io.notebook.JS_MIME_TYPE: raw, bokeh.io.notebook.LOAD_MIME_TYPE: raw}
)

all_components = get_args(bokeh.resources.Component)
r = bokeh.resources.Resources(
    "inline", minified=True, log_level="debug", components=list(all_components)
)
output_notebook(resources=r, versbose=True, hide_banner=False)
)
source = ColumnDataSource(data=dict(x=[], y=[]))

plot = figure(x_range=(0,10), y_range=(0,10), title="Click and drag to draw",
              background_fill_color="#efefef", tools="")

plot.add_tools(DrawTool(source=source))

plot.line('x', 'y', line_width=3, source=source)

show(plot)
```

**Comment by bryevdv** [comment] 2024-07-24 16:30
@zcyounger This is a usage problem, not a bug. It's not clear what you are trying to accomplish, but you the result is that you are explicitly loading BokehJS in a manner that prevents the custom models from also being loaded. Doing things in the typical way, i.e. also the way that the example code in the docs demonstrates, works fine:

<img width="773" alt="Screenshot 2024-07-24 at 09 27 25" src="https://github.com/user-attachments/assets/c98f210f-463c-4699-aa2c-530ac889ab2c">


Since this is a usage issue, the proper venue to seek help is the community  [Discourse site](https://discourse.bokeh.org), so I will close this issue here. 

cc @mattpap in case you want to look for a post on the Discourse to comment on

**Closed as completed by bryevdv** 2024-07-24 16:30 UTC
Labels: type: discussion, reso: referred

**Comment by zcyounger** [comment] 2024-07-25 02:49
@bryevdv Thank you for your reply. The reason I explicitly loaded bokehjs was that previously, when I used output_notebook(INLINE), it would cause a "Javascript Error: jQuery is not defined," which prevented me from using bokeh.models.DataTable. Therefore, I used the workaround mentioned in https://github.com/bokeh/bokeh/issues/13337. After seeing your reply, I tried using output_notebook(INLINE) again, and strangely enough, the previous "Javascript Error: jQuery is not defined" disappeared, and I was still able to use DataTable. The custom DrawTool also worked correctly.

**Comment by zcyounger** [comment] 2024-07-25 06:21
@bryevdv After I explicitly loaded bokehjs in JupyterLab, even if I restarted the kernel, restarted JupyterLab, or restarted my Linux session, it didn't cause a "Javascript Error: jQuery is not defined" when I simply used output_notebook(INLINE) for a period of time, but it's not stable. Additionally, explicitly loading bokehjs after output_notebook(INLINE) also didn't cause an error with the custom draw tool. This is very strange. In issue [#1337](https://github.com/bokeh/bokeh/issues/13337), someone mentioned that this method of explicitly loading bokehjs is very fragile. @mattpap seems to have fixed the "Javascript Error: jQuery is not defined" error by updating @bokeh/slickgrid in issue [#13523](https://github.com/bokeh/bokeh/pull/13523). However, I don't know how to find the fixed version. Because many packages in my work environment require Python 3.8, I can only use versions of Bokeh below 3.1.1.

**Comment by bryevdv** [comment] 2024-07-25 13:03
That fix went into version 3.4

**Comment by zcyounger** [comment] 2024-07-25 13:15
@bryevdv It looks like that version 3.4 is not compatible with python3.8. Is there a way to use the fixed version under python3.8?

**Comment by zcyounger** [comment] 2024-07-25 13:19
@bryevdv By the way, inline extension seems to be able to change the jupyterlab. I did small modification on the extensions and restart the jupyterlab kernel and rerun the code, the result maitain the same as before.

**Comment by bryevdv** [comment] 2024-07-25 13:52
> Is there a way to use the fixed version under python3.8?

There is not, and FYI Python 3.8 itself reaches official End-of-Life [in just a few months](https://devguide.python.org/versions/). You may need to look at other tools and libraries besides Bokeh, if Python 3.8 is a hard requirement.

**Comment by zcyounger** [comment] 2024-07-29 03:12
Thank you!
