### ISSUE TITLE
bar chart hover display ???

### ISSUE THREAD

**Issue by Pierretherenard** [bokeh/bokeh#5538] opened 2016-12-12 07:03 UTC
`def test():
        ttnwwrd = [2,3,4]
        df = dict(`   
`  h=ttnwwrd
        )`
       
        p5 = Bar(data=df, values='h', color='dodgerblue', title="New Unique Words",
                 legend=False, plot_width=1000, plot_height=650,  
                 tooltips=[("total:", "@ttnwwrd")]) 
        show(p5)`
![screen shot 2016-12-11 at 11 00 17 pm](https://cloud.githubusercontent.com/assets/23002446/21090598/a61b562c-bff5-11e6-87c2-86fd36f64f1c.png)
I tried tooltips outside bar() and now inside bar() but even on a small test it does not display the hover values.
Thank you,
Pierre

**Comment by Pierretherenard** [comment] 2016-12-12 07:06
I changed "new words" in the picture to "total" in the code, please don't pay attention to that

**Comment by Pierretherenard** [comment] 2016-12-12 15:34
the other test:
`from bokeh.plotting import figure, output_file, show, ColumnDataSource`
`from bokeh.charts import Bar`
`ttnwwrd = [2,3,4]
        df = dict(
            h=ttnwwrd
        )
        sourcet5 = ColumnDataSource(data=dict(h=ttnwwrd))`
`p5 = Bar(data=df, values='h', color='dodgerblue', title="New Unique Words",
                 legend=False, plot_width=1000, plot_height=650,tools='hover', source=sourcet5)`

                 
  `hover = p5.select(dict(type=HoverTool))`               
`hover.tooltips = [("New words:", "@ttnwwrd"),]`
 ` show(p5)`       
     
Same it display ???

**Comment by Pierretherenard** [comment] 2016-12-13 05:51
reading  https://github.com/bokeh/bokeh/issues/2965

**Comment by Pierretherenard** [comment] 2016-12-13 15:53
i  guess bar chart must a chart that nobody use ;). i am going to be more creative then and place it with something cooler.

**Comment by bryevdv** [comment] 2016-12-13 15:57
@Pierretherenard `Bar` is currently useful for quick exploratory analysis, esp from Pandas dataframe. For anything more sophisticated, I'd currently recommend using `hbar` and `vbar`, etc. which take *slightly* more code but are much more flexible in that regard. 

I hope someday `bokeh.charts` can get renewed attention. Right now there is not any available person-power to devote it. If anyone is interested in becoming a new maintainer for `bokeh.charts` they would certainly be welcomed. I am going to close this issue as a dupe of #2695

**Comment by bryevdv** [comment] 2016-12-13 15:58
For reference, here is a nice bar chart example using `vbar` and `hbar`:

https://github.com/bokeh/bokeh/blob/master/examples/plotting/file/bar_chart.py

**Closed by bryevdv** 2016-12-13 15:57 UTC
