### ISSUE TITLE
Memory leak in javascript code with live streaming data

### ISSUE THREAD

**Issue by bkloppenborg** [bokeh/bokeh#2599] opened 2015-07-21 16:22 UTC
Greetings. I have found that the memory usage in both FireFox and Chrome slowly creeps up while viewing an animated graph generated by Bokeh. I let the script below run for about 20 minutes on each browser and each browser's memory usage increased from 147 MB at the start to 1.4 GB over that time period. Is there some other method I should be using to dynamically update the data?

```
import time
import numpy as np
from bokeh.plotting import figure, cursession, show, output_server

output_server("sine")

# setup the data
N = 100
x = np.linspace(0, 4*np.pi, N)
y = np.sin(x)

# configure the plot
p = figure()
p.line(x, y, color="#3333ee", name="timeline")
show(p)

renderer = p.select(dict(name="timeline"))
ds = renderer[0].data_source

time_step = 0.05
while True:
    x = x + time_step
    ds.data["x"] = x
    ds.data["y"] = np.sin(x)
    cursession().store_objects(ds)
    time.sleep(time_step)

```

**Comment by bryevdv** [comment] 2015-07-21 16:27
I believe this is a dupe of #2050 We are currently working on making BokehJS much more memory efficient by streaming data over binary web sockets directly into JS typed array, as well as more GC friendly. But this has just started and will involve some heavy lifting. I would like to have it for 0.10 in September but 0.11 is probably a more likely target.

**Closed by bryevdv** 2015-07-21 16:27 UTC
