### ISSUE TITLE
HTML file from bokeh (save) is too big (in size = 22Mb)to handle for any browser

### ISSUE THREAD

**Issue by Rakeshbart** [bokeh/bokeh#2157] opened 2015-04-08 20:43 UTC
bokeh._version.get_versions()
{'version': '0.8.2', 'full': 'da429b96a9e264ede4222470c1fdc4aa3088930b'}

I have 3 plots as VBox(s1, s2, s3)

s1 has 5 line plots
s2 has 4 line plots
s3 has 4 line plots

code:

        ap_new = pd.read_csv(self.ap_csv_filename, parse_dates=['tstamp'])
        sta_new = pd.read_csv(self.sta_csv_filename, parse_dates=['tstamp'])
        
        
        file_name = [[ap_new, sta_new],[self.ap_plot_filename,self.sta_plot_filename]]
        
        for i, b5 in enumerate(devs):
            
            self.plot_graph(file_name[0][i], file_name[1][i])
                    
    def plot_graph(self, new, plot_filename):

        new['tx_mac_thr'] = [x * 8e-6 for x in new['txbytes']]
        new['rx_mac_thr'] = [x * 8e-6 for x in new['rxbytes']]
        
        xvalues = new['tstamp']
        
        yvalue00 = new['rssi0']
        yvalue01 = new['rssi1']
        yvalue02 = new['rssi2']
        yvalue03 = new['rssi3']
        yvalue04 = new ['per']
        
        yvalue10 = new['evm0']
        yvalue11 = new['evm1']
        yvalue12 = new['evm2']
        yvalue13 = new['evm3']
        
        yvalue20 = new['txrate']
        yvalue21 = new['rxrate']
        yvalue22 = new['tx_mac_thr']
        yvalue23 = new['rx_mac_thr']
        
        TOOLS="resize,pan,wheel_zoom,box_zoom,reset,previewsave,hover"

        output_file(plot_filename)
        #xvalues1 = xvalues.map(lambda x: x.strftime()%X)
        source00 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["rssi0" for i in range(len(yvalue00))],
                    y = yvalue00
                )
        )
        
        source01 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["rssi1" for i in range(len(yvalue01))],
                    y = yvalue01
                )
        )
        
        source02 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["rssi2" for i in range(len(yvalue02))],
                    y = yvalue02
                )
        )
        
        source03 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["rssi3" for i in range(len(yvalue03))],
                    y = yvalue03
                )
        )
        
        source04 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["per" for i in range(len(yvalue04))],
                    y = yvalue04
                )
        )
        
        
        source10 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["evm0" for i in range(len(yvalue10))],
                    y = yvalue10
                )
        )
        
        source11 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["evm1" for i in range(len(yvalue11))],
                    y = yvalue11
                )
        )
        
        source12 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["evm2" for i in range(len(yvalue12))],
                    y = yvalue12
                )
        )
        
        source13 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["evm3" for i in range(len(yvalue13))],
                    y = yvalue13
                )
        )
        
        source20 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["tx_phy" for i in range(len(yvalue20))],
                    y = yvalue20
                )
        )
        
        source21 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["rx_phy" for i in range(len(yvalue21))],
                    y = yvalue21
                )
        )
        
        source22 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["tx_mac" for i in range(len(yvalue22))],
                    y = yvalue22
                )
        )
        
        source23 = ColumnDataSource(
            data = dict(
                    #x = xvalues,
                    name = ["rx_mac" for i in range(len(yvalue23))],
                    y = yvalue23
                )
        )
        s1 = figure(plot_width=1800, plot_height=300, x_axis_type='datetime', title='RSSI and PER', title_text_font_size= "15pt", tools= TOOLS, background_fill = "mintcream")
        s1.line(xvalues.get_values(), yvalue00.get_values(), line_color = "yellow", line_width= 2, line_join='round', legend = 'rssi0')
        s1.circle(xvalues.get_values(), yvalue00.get_values(), size=8, alpha=0, source=source00)
        s1.line(xvalues.get_values(), yvalue01.get_values(), line_color = "green", line_width= 2, line_join='round', legend = 'rssi1')
        s1.circle(xvalues.get_values(), yvalue01.get_values(), size=8, alpha=0, source=source01)
        s1.line(xvalues.get_values(), yvalue02.get_values(), line_color = "blue", line_width= 2, line_join='round', legend = 'rssi2')
        s1.circle(xvalues.get_values(), yvalue02.get_values(), size=8, alpha=0, source=source02)
        s1.line(xvalues.get_values(), yvalue03.get_values(), line_color = "orange", line_width= 2, line_join='round', legend = 'rssi3')
        s1.circle(xvalues.get_values(), yvalue03.get_values(), size=8, alpha=0, source=source03)
        s1.line(xvalues.get_values(), yvalue04.get_values(), line_color = "red", line_width= 2, line_join='round', legend = 'per')
        s1.circle(xvalues.get_values(), yvalue04.get_values(), size=8, alpha=0, source=source04)
        
        s2 = figure(plot_width=1800, plot_height=200, x_axis_type='datetime', title='EVM', title_text_font_size= "15pt", tools= TOOLS, x_range = s1.x_range, background_fill="mintcream")
        s2.line(xvalues.get_values(), yvalue10.get_values(), line_color = "yellow", line_width= 2, line_join='round', legend = 'evm0')
        s2.circle(xvalues.get_values(), yvalue10.get_values(), size=8, alpha=0, source=source10)
        s2.line(xvalues.get_values(), yvalue11.get_values(), line_color = "green", line_width= 2, line_join='round', legend = 'evm1')
        s2.circle(xvalues.get_values(), yvalue11.get_values(), size=8, alpha=0, source=source11)
        s2.line(xvalues.get_values(), yvalue12.get_values(), line_color = "blue", line_width= 2, line_join='round', legend = 'evm2')
        s2.circle(xvalues.get_values(), yvalue12.get_values(), size=8, alpha=0, source=source12)
        s2.line(xvalues.get_values(), yvalue13.get_values(), line_color = "orange", line_width= 2, line_join='round', legend = 'evm3')
        s2.circle(xvalues.get_values(), yvalue13.get_values(), size=8, alpha=0, source=source13)
        
        s3 = figure(plot_width=1800, plot_height=300, x_axis_type='datetime', title='Throughput', title_text_font_size= "15pt", tools= TOOLS, x_range = s1.x_range, background_fill="mintcream")
        s3.line(xvalues.get_values(), yvalue20.get_values(), line_color = "yellow", line_width= 2, line_join='round', legend = 'tx_phy')
        s3.circle(xvalues.get_values(), yvalue20.get_values(), size=8, alpha=0, source=source20)
        s3.line(xvalues.get_values(), yvalue21.get_values(), line_color = "green", line_width= 2, line_join='round', legend = 'rx_phy')
        s3.circle(xvalues.get_values(), yvalue21.get_values(), size=8, alpha=0, source=source21)
        s3.line(xvalues.get_values(), yvalue22.get_values(), line_color = "blue", line_width= 2, line_join='round', legend = 'tx_mac')
        s3.circle(xvalues.get_values(), yvalue22.get_values(), size=8, alpha=0, source=source22)
        s3.line(xvalues.get_values(), yvalue23.get_values(), line_color = "orange", line_width= 2, line_join='round', legend = 'rx_mac')
        s3.circle(xvalues.get_values(), yvalue23.get_values(), size=8, alpha=0, source=source23)
        
        hover_graph1 = s1.select(dict(type=HoverTool))
        hover_graph2 = s2.select(dict(type=HoverTool))
        hover_graph3 = s3.select(dict(type=HoverTool))
        
        hover_graph1.tooltips = [
            ("Name", "@name"),
            ("y", "$y")
        ]
        
        hover_graph2.tooltips = [
            ("Name", "@name"),
            ("y", "$y")
        ]
        
        hover_graph3.tooltips = [
            ("Name", "@name"),
            ("y", "$y")
        ]
        
        p = VBox(s1, s2, s3)
        save(p)

![screenshot from 2015-04-08 13 41 54](https://cloud.githubusercontent.com/assets/11843812/7054986/2a7fd332-ddf5-11e4-8083-6bd775bd8a76.png)

**Comment by bryevdv** [comment] 2015-04-13 19:38
Hi @Rakeshbart can you provide more information about how much data you are attempting to plot?

**Comment by bryevdv** [comment] 2015-09-09 18:52
No update, closing, please feel free to re-open with additional information.

**Closed by bryevdv** 2015-09-09 18:52 UTC
Labels: type: discussion

**Comment by mauhcs** [comment] 2016-10-18 06:44
Hi, 
I had similar behavior with Bokeh. 

The html output keeps getting bigger and bigger every time I run the output cell in a Jupyter Notebook. 

If I close Jupyter or reload the notebook and run all the cells again, it outputs a smaller html file. But then, it gets getting bigger and bigger until I have to reload it. 

It makes me feel that Bokeh is appending the JS to the file. But I am not sure. 

Any idea how to solve this?

The output _file is in the mode 'inline.'::
           output_file('file.html', mode='inline')

Maybe it is related?


Thank you.

**Comment by birdsarah** [comment] 2016-10-18 13:08
@mauhcs this issue is closed. Suggest you ask on the mailing list. But I'd also recommend searching first as your question has already been answered.

**Comment by web-rishi-shukla** [comment] 2018-05-22 23:53
My file is around 4.6M still takes chrome more than a minute to load the html file.


[4_6M_Html_file.zip](https://github.com/bokeh/bokeh/files/2028979/4_6M_Html_file.zip)

**Comment by bryevdv** [comment] 2018-05-23 00:32
Is closed because no code/data to reproduce was ever provided even though it was asked for. I will say:

* There are some suboptimal ways of using bokeh, but that's a support discussion, so should happen on the mailing list, not here

* There are some things that bokeh is just not b and will never be suitable for. If you have 100s thousands of points, you will need to use a bokeh server so binary transport is available, or down sample or prerender with something like datashader, or use a different tool altogether.

**Comment by web-rishi-shukla** [comment] 2018-05-23 18:21
Thanks for the pointers. Will post question on mailing list and also try datashader in the mean while.
