### ISSUE TITLE
BokehJS ColumnDataSource.change property doesn't exist

### ISSUE THREAD

**Issue by paddymul** [bokeh/bokeh#8686] opened 2019-02-25 20:09 UTC
The BokehJS example from the documentation doesn't work as expected.
I used the code from this example https://bokeh.pydata.org/en/latest/docs/user_guide/bokehjs.html#minimal-complete-example

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
BokehJS 1.0.4  
BokehJS 0.12.5

I can reproduce in Firefox and Chrome

#### Description of expected behavior and the observed behavior
Clicking on the "Add Some Data" button should cause the plot to update. 

#### Stack traceback and/or browser JavaScript console output
This seems to fail because ColumnDataSource.change doesn't exist as a property

#### Screenshots or screencasts of the bug in action
[CodePen 0.12.5 Example](https://codepen.io/paddy_mullen/pen/ZPEBma)
[CodePen 1.0.4 Example](https://codepen.io/paddy_mullen/pen/vPYgKO)

**Comment by bryevdv** [comment] 2019-02-25 20:49
Ah the URLs in the example just need to be updated to something newer (1.0.4 etc) AFAICT. @paddymul if you can push a quick PR that would be helpful

**Comment by paddymul** [comment] 2019-02-25 21:20
I'm happy to push a PR, but I don't think it will solve the issue.  If you look the [CodePen BokehJS 1.0.4](https://codepen.io/paddy_mullen/pen/vPYgKO) the AddPoint function still doesn't work properly.

I tried a couple of other methods in the commented out code including source.stream.  When using source.stream, points are added to the ColumnDataSource, and the plot ranges update, but the line renderer doesn't change.

**Comment by mattpap** [comment] 2019-02-27 00:15
> This seems to fail because ColumnDataSource.change doesn't exist as a property.

Every model has `change` signal:
https://github.com/bokeh/bokeh/blob/d1c5513ad690acf3a332298cda2d8c2325872534/bokehjs/src/lib/core/has_props.ts#L154

**Comment by mattpap** [comment] 2019-02-27 00:18
Nevertheless, bokehjs is somehow broken. When adding points, ranges are updated and plot repainted, however, it looks like data isn't remapped (or something along this line). It gets worse when glyph is changed to e.g. circle, because then plot isn't able to compute initial ranges after adding the first pair of coordinates.

**Comment by mattpap** [comment] 2019-02-27 01:19
The problem is that `CDSView` doesn't update indices, because `source` is set late and appropriate signals aren't connected. This isn't a problem in Python, because signals are connected after are property values are configured (`CDSView.source` in particular). I will fix this tomorrow.

**Comment by mattpap** [comment] 2019-02-27 22:17
In more generic terms this will be fixed in issue #8597.

**Closed** 2019-03-01 17:58 UTC
Labels: reso: completed, tag: component: bokehjs, tag: component: docs, type: bug

**Comment by paddymul** [comment] 2019-03-02 20:48
@mattpap Thank you.  Are there CDN JS resources for this new commit?

**Comment by mattpap** [comment] 2019-03-04 16:57
@paddymul, no, we only publish npm packages for releases. I suppose it would be good to publish at least for dev releases as well and optimally maintain `bokehjs@next`. I will start a new issue for this.
