### ISSUE TITLE
Server(..., io_loop=io_loop, num_procs=0) --> RuntimeError

### ISSUE THREAD

**Issue by jbrockmendel** [bokeh/bokeh#6439] opened 2017-06-12 02:26 UTC
From the [flask_embed](https://github.com/bokeh/bokeh/blob/master/examples/howto/server_embed/flask_embed.py) example:

```
bokeh_app = Application(FunctionHandler(modify_doc))

io_loop = IOLoop.current()

server = Server({'/bkapp': bokeh_app}, io_loop=io_loop, allow_websocket_origin=["localhost:8080"])
server.start()
```

`Server.__init__` takes a [kwarg](https://github.com/bokeh/bokeh/blob/master/bokeh/server/server.py#L81) `num_procs` that I'd like to set to 0 to fork a reasonable number of processes*.  But since the `IOLoop` has already been initialized, that raises:

```
RuntimeError: Cannot run in multiple processes: IOLoop instance has already been initialized. You cannot call IOLoop.instance() before calling start_processes()
```

Most of the examples I've seen calling `Server.__init__` pass an `IOLoop` object.  So is there another place `num_procs` is supposed to be passed?

\* As it is, only one request is getting served at a time.  That suggests that I'm somehow using Tornado wrong, but that's a question for StackExchange.

python2 .7.12 running on AWS linux.
bokeh 0.12.5

**Comment by bryevdv** [comment] 2017-06-12 12:39
Looking that the implementation of `__init__` it seems clear that you can currently either pass `num_procs` *or* and `IOLoop`, but not both. The relevant code:
```
        try:
            tornado_kwargs['extra_websocket_origins'] = _create_hosts_whitelist(kwargs.get('allow_websocket_origin'), self._port)
            tornado_kwargs['use_index'] = kwargs.get('use_index', True)
            tornado_kwargs['redirect_root'] = kwargs.get('redirect_root', True)

            self._tornado = BokehTornado(self._applications, self.prefix, **tornado_kwargs)
            self._http = HTTPServer(self._tornado, **tornado_server_kwargs)
            self._http.start(self._num_procs)
            self._http.add_sockets(sockets)

        except Exception:
            for s in sockets:
                s.close()
            raise

        # Can only instantiate the IO loop after HTTPServer.start() was
        # called because of `num_procs`, see issue #5524
        if io_loop is None:
            io_loop = IOLoop.current()
        self._loop = io_loop
        self._tornado.initialize(io_loop=io_loop, **tornado_kwargs)
```

The gist: The HTTP server *must* be started (with whatever `num_procs` value you want) *before* instantiating the ioloop. But `Server.__init__` doesn't offer any way to pass your own HTTP server, so this is not possible. 

Immediate solution for your situation: subclass `Server` and override `__init__` with one that is basically the same as the current code, except that it also accepts a passed-in `HTTPServer`. (Make sure not to call `super`)

Longer term: It would be great if you could submit a PR with that change to the current `Server.__init__`. The only slight wonkiness is that passing *both* a custom `HTTPServer` and `num_procs` can't be supported, so a little argument checking will be necessary:

* if neither is passed, create internal `HTTPServer` with `num_procs=1`
* if only `num_procs` is passed, use that when creating internal `HTTPServer`
* if only `http_server` is passed, use that instead of an internal one
* if both are passed, raise a `ValueError`

along with some tests to maintain this behavior.

**Comment by jbrockmendel** [comment] 2017-06-12 17:43
Thanks for the explanation.  I'll put that PR on my get-around-to-it list.  Don't want to mess with any server code until I get comfortable with Tornado, which may be a while.

**Comment by bryevdv** [comment] 2017-06-30 19:42
@jbrockmendel just an FYI I will probably try to close this issue next week, unless you let me know that you are still planning to work on it.

**Comment by jbrockmendel** [comment] 2017-07-01 01:18
It's on my eventual-to-do list.  Pretty much zero chance it'll happen in the next week.  Go ahead and close for now.

**Comment by bryevdv** [comment] 2017-08-11 01:44
@jbrockmendel This turned out to be more involved than I thought. In addition to making the API muddled, it seems that the demonstrated method of integrating Tornado and Flask using `WSGIContainer` is ***strongly*** discouraged. So I tried this instead (rest replace the end of the exiting example, srarting from `bokeh_app = ...`):
```
bokeh_app = Application(FunctionHandler(modify_doc))

@flask_app.route('/', methods=['GET'])
def bkapp_page():
    script = server_document('http://localhost:5006/bkapp')
    return render_template("embed.html", script=script, template="Flask")

if __name__ == '__main__':
    import threading

    def worker():
        server = Server({'/bkapp': bokeh_app}, num_procs=6, allow_websocket_origin=["localhost:8080"])
        server.start()
        server.io_loop.start()

    t = threading.Thread(target=worker)
    t.start()

    print('Starting Flask app with embedded Bokeh application on http://localhost:8080/')
    flask_app.run(port=8080)
```
This seems to work as desired: fires up 6 python processes, and interacting with different instances in different tabs shows activity on different python processes. I am not sure if there are an drawback to this approach. Can you evaluate and/or comment?

**Comment by bryevdv** [comment] 2017-08-11 02:04
This also seems to work using `gevent` which is presumably a more "production" style of running:
```
bokeh_app = Application(FunctionHandler(modify_doc))

@flask_app.route('/', methods=['GET'])
def bkapp_page():
    script = server_document('http://localhost:5006/bkapp')
    return render_template("embed.html", script=script, template="Flask")

import threading

def worker():
    server = Server({'/bkapp': bokeh_app}, num_procs=6, allow_websocket_origin=["localhost:8080"])
    server.start()
    server.io_loop.start()

t = threading.Thread(target=worker)
t.start()

import gevent
from gevent.wsgi import WSGIServer

http_server = WSGIServer(('', 8080), flask_app)
http_server.serve_forever()
```

**Comment by bryevdv** [comment] 2017-08-11 02:25
And this seems to work with e.g.`gunicorn -w 16 -b 127.0.0.1:8080 flask_embed:flask_app` but only with `num_procs =1`, gunicorn forks its own processes...

```
bokeh_app = Application(FunctionHandler(modify_doc))

import threading

server = Server({'/bkapp': bokeh_app}, num_procs=1, port=0, allow_websocket_origin=["localhost:8080"])

@flask_app.route('/', methods=['GET'])
def bkapp_page():
    script = server_document('http://localhost:%s/bkapp' % server.port)
    return render_template("embed.html", script=script, template="Flask")

def worker():
    server.start()
    server.io_loop.start()

t = threading.Thread(target=worker)
t.start()
```

**Comment by bryevdv** [comment] 2017-08-11 02:28
@jbrockmendel I'd definitely love to have some feedback. I *think* this might just need a documentation/new examples PR, which would be the best outcome

**Comment by jbrockmendel** [comment] 2017-08-11 15:58
This is great, thanks for following up.  I'll try this out and report back.

**Comment by jbrockmendel** [comment] 2017-08-12 04:41
Progress but still some speed-bumps.  I'm using the gunicorn variant.  AFAICT the trouble is with `autoload_server`.  Effectively I have:

```
@app.route('/app1')
def app1():
	script = autoload_server(
		model=None,
		url='http://%s:5007/app1' % localhost,
		)
	return flask.render_template("layout.html", script=script, template="Flask")

def init_app():
    app1_func = Application(FunctionHandler(func1))
    app2_func = Application(FunctionHandler(func2))
    bkserver = Server(
        {'/app1': app1_func, '/app2': app2_func},
        allow_websocket_origin=["localhost:5006", "localhost:5007"],
        port=5007,
        #io_loop=io_loop,
        num_procs=1
        )

    def worker():
        bkserver.start()
        bkserver.io_loop.start()

    return (bkserver, worker)

def main():
    (bkserver, worker) = init_app()
    thr = threading.Thread(target=worker)
    thr.start()
```

The non-gunicorn variant used the `io_loop` kwarg and did not have the `worker` func.  Other than that, this is unchanged from the previous (working, albeit one connection at a time) variant.

The non-gunicorn variant went through `if __name__ == "__main__":` following the flask_embed example.  In the gunicorn variant, I follow the example you gave above and unconditionally run `worker` in a thread.

With that hopefully clear, I'm getting a socket error:

```
gunicorn -w 4 -b 0.0.0.0:5009 web66:app

[2017-08-11 21:28:12 +0000] [19859] [ERROR] Exception in worker process:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/arbiter.py", line 515, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 122, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/base.py", line 130, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 65, in load
    return self.load_wsgiapp()
  File "/usr/local/lib/python2.7/dist-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
    return util.import_app(self.app_uri)
[...]
  File "/usr/local/lib/python2.7/site-packages/myapp/example.py", line 190, in init_app
    num_procs=1
  File "/usr/local/lib/python2.7/site-packages/bokeh/server/server.py", line 133, in __init__
    sockets, self._port = _bind_sockets(self._address, port)
  File "/usr/local/lib/python2.7/site-packages/bokeh/server/server.py", line 62, in _bind_sockets
    ss = netutil.bind_sockets(port=port or 0, address=address)
  File "/usr/local/lib/python2.7/site-packages/tornado/netutil.py", line 197, in bind_sockets
    sock.bind(sockaddr)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 98] Address already in use
```

Things that don't appear to make a difference:
 - gunicorn -w 1
 - `num_procs=0`
 - `port=0`

So my guess is that gunicorn is spawning multiple processes each of which is trying to spawn a server at port 5007.  I'll see if I can troubleshoot this any further tomorrow.

**Comment by bryevdv** [comment] 2017-08-12 17:46
> So my guess is that gunicorn is spawning multiple processes each of which is trying to spawn a server at port 5007. I'll see if I can troubleshoot this any further tomorrow.

That's exactly right, that's why I set `port=0` to get a new port for every (bokeh) server that gets started:
```
server = Server({'/bkapp': bokeh_app}, num_procs=1, port=0, allow_websocket_origin=["localhost:8080"])

@flask_app.route('/', methods=['GET'])
def bkapp_page():
    script = server_document('http://localhost:%s/bkapp' % server.port)
    return render_template("embed.html", script=script, template="Flask")
```

But although this "work" it is apparently not advised to start the existing ioloop on another thread. a Better solution would be to generate the new port explicitly and coordinate it between the autoload call and the thread explicitly. 

I am working on a PR but it will probably be next week before it's up. I don't want to change `Server` interface, but I am am working on a `BaseServer` parent class that lets users explicitly coordinate their own bokeh tornado app, htpp_server, and ioloop. Once that's done I will rework the examples to demonstrate this.

**Comment by jbrockmendel** [comment] 2017-08-12 19:19
OK.  I'll hack something together for the I-need-something-right-now problem, and will try to help with in-the-wild testing for the longer-term solution.

**Comment by jbrockmendel** [comment] 2017-08-19 18:15
An update on this: I've gotten it mostly working (locally at least...), but have had to massage it to find a variation of "localhost" that it will accept.  Specifically, allow_websocket_origin seems to need `"hostname.local:5006"` or else I get ERR_CONNECTION_REFUSED over in Chrome's Inspect Element tool (nothing indicating a problem in the server console).  None of `["127.0.0.1:5006", "localhost:5006", "Hostname.local:5006"]` get the job done.

**Comment by bryevdv** [comment] 2017-08-20 17:55
@jbrockmendel I've never encountered `hostname.local` what platform are you on?

**Comment by jbrockmendel** [comment] 2017-08-20 18:15
I was using "Hostname" as a stand-in for the actual hostname.  i.e. pretend that `socket.gethostname()` returns `"Hostname"`

**Comment by bryevdv** [comment] 2017-08-20 18:20
So, the web socket origin needs to be set to whatever will be the "Origin" header of the page that embeds the app. So if users navigate using the actual hostname, i.e. to `"foo:5006"` to view, then that's what needs to be set. If you want to have hostname, localhost, 127 all work you will need to set all of them in the list (i.e. I think what you are saying makes sense)

**Comment by bryevdv** [comment] 2017-08-20 18:26
So I am still not sure how or if "num_procs" can be made to directly inside a flask app. The issue is that  the Bokeh tornado app really has to be run on tornado's `HTTPServer` and starting that with num procs > 1 immediately forks. But then any subsequent starting of flask etc. results in multiple props listening n the same port. I don't see a way to make that work. But, using the PR, I did create this:

```
from flask import Flask, render_template
import yaml

from tornado.httpserver import HTTPServer
from tornado.ioloop import IOLoop

from bokeh.application import Application
from bokeh.application.handlers import FunctionHandler
from bokeh.embed import server_document
from bokeh.layouts import column
from bokeh.models import ColumnDataSource, Slider
from bokeh.plotting import figure
from bokeh.server.server import BaseServer
from bokeh.server.tornado import BokehTornado
from bokeh.server.util import bind_sockets
from bokeh.themes import Theme

from bokeh.sampledata.sea_surface_temperature import sea_surface_temperature

flask_app = Flask(__name__)

def modify_doc(doc):
    df = sea_surface_temperature.copy()
    source = ColumnDataSource(data=df)

    plot = figure(x_axis_type='datetime', y_range=(0, 25), y_axis_label='Temperature (Celsius)',
                  title="Sea Surface Temperature at 43.18, -70.43")
    plot.line('time', 'temperature', source=source)

    def callback(attr, old, new):
        if new == 0:
            data = df
        else:
            data = df.rolling('{0}D'.format(new)).mean()
        source.data = ColumnDataSource(data=data).data

    slider = Slider(start=0, end=30, value=0, step=1, title="Smoothing by N Days")
    slider.on_change('value', callback)

    doc.add_root(column(slider, plot))

    doc.theme = Theme(json=yaml.load("""
        attrs:
            Figure:
                background_fill_color: "#DDDDDD"
                outline_line_color: white
                toolbar_location: above
                height: 500
                width: 800
            Grid:
                grid_line_dash: [6, 4]
                grid_line_color: white
    """))

bkapp = Application(FunctionHandler(modify_doc))

bokeh_tornado = BokehTornado({'/bkapp': bkapp}, extra_websocket_origins=["localhost:8000"])
bokeh_http = HTTPServer(bokeh_tornado)

# This is so that if this app is run using something like "gunicorn -w 4" then
# each process will listen on its own port
sockets, port = bind_sockets("localhost", 0)
bokeh_http.add_sockets(sockets)

@flask_app.route('/', methods=['GET'])
def bkapp_page():
    script = server_document('http://localhost:%d/bkapp' % port)
    return render_template("embed.html", script=script, template="Flask")

def bk_worker():
    io_loop = IOLoop.current()
    server = BaseServer(io_loop, bokeh_tornado, bokeh_http)
    server.start()
    server.io_loop.start()

from threading import Thread
Thread(target=bk_worker).start()

if __name__ == '__main__':
    print('Opening Flask app with embedded Bokeh application on http://localhost:8000/')

    flask_app.run(port=8000)
```

This can either be run (with a single process) with` python flask_embed.py`, or it can be run `with `gunicorn -w 4 flask_embed:flask_app` in which case different loads of the page cause CPU spikes on different python process which seems to be the ultimate desire.

**Comment by bryevdv** [comment] 2017-08-20 19:16
@jbrockmendel you might check out the updated examples in the PR:

https://github.com/bokeh/bokeh/tree/9df363d7d856a1a2131b5e8f5facb03784e8510b/examples/howto/server_embed

**Comment by jbrockmendel** [comment] 2017-08-21 03:28
Trying to make this work... it looks like there is a `prefix` arg missing from the `BokehTornado`

**Comment by jbrockmendel** [comment] 2017-08-21 03:31
... and `BaseServer` doesn't appear to exist in 0.12.6.  I'll install 0.12.7 manually tomorrow and see how it goes.

**Comment by bryevdv** [comment] 2017-08-21 05:34
0.12.7 does not exist yet, you'd have to install from the PR branch. Can you elaborate on the other comment about prefix?

**Comment by jbrockmendel** [comment] 2017-08-21 15:44
> 0.12.7 does not exist yet, you'd have to install from the PR branch.

Yep!

> Can you elaborate on the other comment about prefix?
```
    bokeh_tornado = BokehTornado(apps, extra_websocket_origins=["localhost:8000"])
TypeError: __init__() takes at least 4 arguments (3 given)
```

**Comment by bryevdv** [comment] 2017-08-21 15:49
oh, in the PR branch `prefix` defaults to `None`

**Closed** 2017-08-21 16:41 UTC
Labels: tag: component: server, type: task

**Comment by bryevdv** [comment] 2017-08-21 16:43
@jbrockmendel FYI the PR has been merged, so installing from master will now work. Alternatively there will be a dev build soon. I am going to leave this issue as completed for now as I think I've made the best changes and guidance that I can for the moment. Any additional docs/examples can go in a follow on PR if you have suggestions.

**Comment by jbrockmendel** [comment] 2017-08-21 17:11
Great, thanks.  You've gone above-and-beyond in helping troubleshoot on this.  I'll keep passing along updates from the wild if they might be useful.
