### ISSUE TITLE
Implement --develop mode

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#4236] opened 2016-04-27 15:53 UTC
Also document what `--develop` does.

`tornado` does not seem to do a good job in tracking dependencies all the way to the bokeh app, and does not restart when the bokeh app source changes.

PS Why was `tornado` chosen as a web server in the first place? E.g. `flask` does a brilliant job at serving simple WSGI apps, doesn't to require the use of non-blocking event-loop paradigms, whereas `tornado` can be shown to becomes unstable when these paradigms are violated.

**Comment by bryevdv** [comment] 2016-04-27 16:35
`--develop` *is* the option for auto reload. It has not been implemented yet, and it's inclusion in the server CLI was an accidental oversight. I actually can't find an issue for it now though, so I am renaming this one.

**Comment by bryevdv** [comment] 2016-04-27 16:44
As for the server choice, I can only say that the first iteration of the Bokeh server *was* a Flask server, and it was ultimately a failure. The interactions between the client and the server are not captured by simple REST interfaces. We were never able to implement any kind of streaming interface, for instance, *nor even formulate a plan of how me might do that*. The new server, with its web socket protocol, is more performant, supports streaming and has a path to even better optimizations like binary array transport. The new server is horizontally scalable, and this scalability is demonstrated on the deployed gallery site. We were *never* able to demonstrate scalability with the Flask-based server. The old server required making specialized subclasses to make apps. For the new server you just write a simple script. It is also very *much* simpler for users to write apps for the new server. The new server is actually simpler conceptually and doesn't have difficult dependencies like Redis. It is better by any measure I can think of. But the proof is in the numbers: there is *vastly* more usage and interest in the new tornado server in a few short months than there every way in the old Flask server in almost *three years*.

**Comment by bryevdv** [comment] 2016-04-27 16:56
Or put another way: All the machinery that let's someone write 30 lines of simple python to stand up a reactive web app that backs widgets and tools with real python callbacks is mostly hidden from users' view. We could not have implemented all that machinery as WSGI app, which means going that route would increase users' burdens (and in fact that is exactly what the experience with the first server showed)

**Comment by bryevdv** [comment] 2016-04-27 16:57
> tornado does not seem to do a good job in tracking dependencies all the way to the bokeh app

I would appreciate if you can elaborate on this statement (preferably with code).

**Comment by birdsarah** [comment] 2016-10-18 12:56
@bryevdv can we remove develop mode placeholder and related documentation until it's an implemented feature. (another question on the mailing list today)

**Comment by bryevdv** [comment] 2016-10-18 13:56
Yes, that it is still there now is only an oversight.

**Comment by hiramf** [comment] 2017-09-18 21:17
Wondering if a potential solution for a dev instance of the server:
add an argument to `bokeh serve` such as `--dev`, which adds a button in the html that reloads the .py file when clicked?

**Comment by bryevdv** [comment] 2018-09-13 04:38
Despite initial enthusiasm form he core devs about adding this feature, there has been almost zero user interest expressed now after several years, so I am going to go ahead and close this. As for a button to force a reload, that could be done with existing APIs, CustomJS, CustomAction, etc.

**Comment by jensschroer** [comment] 2018-09-18 07:05
I was just looking for this feature as I am developing an app with bokeh. Maybe you guys can reconsider? I think this is a feature any web dev framework offers now a days.
Why there has been so little user request for this feature I can only speculate. Maybe the bokeh user audience has fewer people with a recent web dev history where such a feature is state of the art? Maybe this feature only appeals to people that write apps and majority of users uses bokeh in a jupyter environment that supports quick reload out of the box?
Anyhow, I would really appreciate to see this implemented.

**Comment by bryevdv** [comment] 2018-09-18 15:34
@jensschroer There is unfortunately just things that could possibly be done, than there are core devs to do them. Some things are only going to get done when/if interested new contributors decide to lead an effort. I would regard this idea as one of those things. I am happy to collaborate and provide guidance to anyone who wants to work on this.

**Comment by birdsarah** [comment] 2018-09-18 17:58
I am in favor of leaving this issue open. I've been developing bokeh apps lately and using my own watch hack to do a develop option. So I would definitely still like to see it as a feature. Even if it's not coming soon.

**Comment by bryevdv** [comment] 2018-09-18 23:49
I just don't see the utility of letting issues linger indefinitely. Other projects have policies to close out old issues, and that seems like a good thing. It's not like this can't be re-opened whenever someone expresses a clear intent to work on it, and that state of affairs is thoroughly documented in this discussion.

If it helps to entice someone to step up, this seems like a great potential task for a [NumFocus Small Development Grant](https://numfocus.org/blog/summer-2018-open-source-development-grants). I would love to craft an SDG proposal to fund anyone who wants to work on this. The current CFP round was just opened and runs through 2018-10-28.

**Comment by jensschroer** [comment] 2018-09-19 12:06
Just added a PR using tornado's auto reload feature.

**Comment by birdsarah** [comment] 2018-09-20 15:31
@bryevdv - I wanted to follow-up on closing of stale issues. 

Before I do, I want to say, that broadly speaking I think you can do whatever feels best for you. You have, among the many other things you do, been doing all the triage and all the issue management, so I want to be clear how grateful I am for that.

I think this issue is weird, it's a discussion and the original post is not ideal. And I think marking this as stale and looking again, I see why it was closed.

I think the lack of an open, proper, "feature" issue for "implement a develop mode" was an oversight. It was a need we could readily articulate, but just was super low priority

I would like to add some nuance to the closing of stale feature issues. 

Closing a feature issue, to my mind, signals that the core team is not interested in the feature. This is often a good thing to do: lots of features may be outside of the scope of what the project wants to do. But features that we think would be neat but are at the bottom of the bottom of the stack for priorities are different. Leaving them open signals to a motivated contributor that this feature would be great but we're not getting to it any time soon.

If, and I understand this sentiment, we want to close issues to keep the issue tracker manageable, might I suggest a tag for this case, so the distinction between these two types of feature issues being closed is clear for folks who come across issues. The tag could even be a source of issues for new contributors who want to work on a feature, but slowly and want to know it's not on a roadmap / milestone.

**Comment by bryevdv** [comment] 2018-09-20 15:51
Right I agree that the issue is that we don't do a good job (any job at all really) of distinguishing between feature requests:

1) merely proposed
2) proposed and rejected, would not accept any PR from anyone for it
3) not rejected but not a priority, would merge if someone submits a PR
4) a priority for core devs, *should* be done (by whoever gets to it first)

I would say this issue fell into that third category.

Currently 2) and 3) basically just get lumped together as closed discussions with no other indications. So for sure we can do better. We could add tags e.g. `reso: needs champion` and `reso: rejected`  to closed feature requests. We could also mark the `type` as feature instead of discussion in those cases. 

I guess something like that would be my preference, since I am definitely interested in keeping the tracker size more or less down to things that are useful for the heaviest users. Open to other thoughts though. (Perhaps on a new issue?)

**Comment by birdsarah** [comment] 2018-09-20 15:57
> Currently 2) and 3) basically just get lumped together as closed discussions with no other indications. So for sure we can do better. We could add tags e.g. reso: needs champion and reso: rejected to closed feature requests. We could also mark the type as feature instead of discussion in those cases.

Sounds good to me.

**Comment by bryevdv** [comment] 2018-09-21 02:56
@birdsarah OK I will plan to add and start using those tags after 1.0 (and update the BEP as well) I don't want to have to futz with the `issues.py` changelog script before the release.

**Closed** 2018-09-25 16:53 UTC
Labels: tag: component: server, type: feature
