### ISSUE TITLE
[BUG] BoxAnnotation crash with datetime or timestamp

### ISSUE THREAD

**Issue by henkluinge** [bokeh/bokeh#12681] opened 2022-12-14 16:44 UTC
### Software versions
Python version      :  3.9.15 (main, Nov 24 2022, 14:31:59)
IPython version     :  7.31.1
Tornado version     :  6.2
Bokeh version       :  3.0.2
BokehJS static path :  /home/hpc/anaconda3/envs/enstest/lib/python3.9/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-4.15.0-191-generic-x86_64-with-glibc2.27

### Browser name and version

Brave 1.46

### Jupyter notebook / Jupyter Lab version

The version of the notebook server is: 6.5.2

### Expected behavior

BoxAnnotation accepts datetime/timestamp, similar to previous versions of Bokeh.

### Observed behavior

When specifying a datetime to the left and/or right arguments of BoxAnnotations, I get a crash with the following error message:

ValueError: failed to validate BoxAnnotation(id='p6947', ...).left: expected an element of either Null, Float or Factor(Either(String, Tuple(String, String), Tuple(String, String, String))), got Timestamp('2018-01-01 00:00:00', freq='D')

### Example code

```Python
import pandas as pd
import numpy as np
from bokeh.models import BoxAnnotation
from bokeh.plotting import figure, show
from bokeh.io import output_notebook
output_notebook(hide_banner=True)

# Create dataframe
n_samples=20
df = pd.DataFrame(np.sin(np.linspace(0, np.pi, n_samples)), columns=('a',) )
df.index = pd.date_range(start='1/1/2018', periods=n_samples)

# Plot signal and boxannotation
p = figure(**{'x_axis_type': "datetime"})
p.line(df.index, df.a)

p.add_layout(BoxAnnotation(left=df.index[0], right=df.index[3]))
show(p)
```

### Stack traceback or browser console output

ValueError: failed to validate BoxAnnotation(id='p6947', ...).left: expected an element of either Null, Float or Factor(Either(String, Tuple(String, String), Tuple(String, String, String))), got Timestamp('2018-01-01 00:00:00', freq='D')

**Comment by bryevdv** [comment] 2022-12-14 17:07
Dupe of #12540

@henkluinge to my knowledge, annotations have never supported datetime values in the past. Support for datetime values was recently added (https://github.com/bokeh/bokeh/pull/12541), but is not in any release yet. It will be in the upcoming 3.1 release.

**Closed as completed** 2022-12-14 17:10 UTC
Labels: reso: duplicate
