### ISSUE TITLE
selecting a model via id in bokeh.embed.autoload_server returns model within nested layout and breaks sizing modes

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#5244] opened 2016-09-28 07:33 UTC
As part of writing a JupyterLab extension (https://github.com/dask/dask-labextension/pull/3) for the dask.distributed UI (https://github.com/dask/distributed), we attempted to use `bokeh.embed.autoload_server` with a specified model_id arg to select a desired model from a the distributed UI (a Bokeh server application with a layout structure of multiple plots). It was noted that the model that was returned and embedded in JLab still contained the layout objects as document.roots, which caused the resizing to the desired `sizing_mode` feature to not work.

specifically (via browser console):

``` javascript
var plot = Bokeh.index['bk-resource-plot']
plot.document._roots[0].children
[Row, Row, Row, Row]
```

when selecting a single plot from it's own app_route:

``` javascript
var plot = Bokeh.index['bk-resource-plot']
plot.document._roots[0].children
[Plot]
```

(i don't know why it's a reference to itself, but it doesn't break the resizing)

We have a short-term work around for the JLab stuff, but it'd be nice to resolve this core issue.

ping @birdsarah @havocp

**Comment by bryevdv** [comment] 2018-05-08 21:41
AFAICT this seems to be a duplicate of #4986, at least wrt ultimate intent, i.e. to templatize individual app components (PR in progress)

**Closed by bryevdv** 2018-05-08 21:41 UTC
Labels: type: bug
