### ISSUE TITLE
Hover tooltip with non-numeric axis

### ISSUE THREAD

**Issue by creynold** [bokeh/bokeh#2164] opened 2015-04-10 23:38 UTC
I'm trying to display tooltips with a non-numeric axis.

Simple example:

        x = list('abcde')
        y = [6, 7, 2, 4, 5]
        p = figure(title="simple example", x_axis_label='x', y_axis_label='y',
                   tools="wheel_zoom,box_zoom,reset,hover", x_range=x)
        p.circle(x, y, size=6, line_width=2)
        hover = p.select(dict(type=HoverTool))
        hover.tooltips = [
            ('(x,y)', '(@x, @y)')
        ]

The tooltips do work with x replaced with a list of numbers. Is there something wrong with this code?

**Comment by gene-telligent** [comment] 2015-04-13 18:46
I'm not able to reproduce this issue -- the expected hover tooltip is displaying appropriately for me:

![screen shot 2015-04-13 at 11 46 07 am](https://cloud.githubusercontent.com/assets/11700535/7122812/9e9fa784-e1d2-11e4-8232-f126b0ac844f.png)

Can you attach a screenshot of what results you're getting?

**Comment by bryevdv** [comment] 2015-04-13 18:52
I think this is fixed on master. Can you both report versions?

**Comment by creynold** [comment] 2015-04-13 18:55
I'm using v 0.8.2 currently

**Comment by gene-telligent** [comment] 2015-04-13 19:04
I'm using a fresh build of master, which would explain why it's fixed for me!

**Comment by bryevdv** [comment] 2015-04-13 19:10
@creynold it may also be fixed in the latest dev build if you care to install that, or else there will be another dev build later this week.

**Closed by bryevdv** 2015-04-13 19:10 UTC
Labels: type: discussion
