### ISSUE TITLE
Wheel Zoom not working with Bokeh Server?

### ISSUE THREAD

**Issue by tkchris93** [bokeh/bokeh#4762] opened 2016-07-06 21:30 UTC
I believe that the wheel scroll is not working. I ran the sliders.py example from demo.bokehplots.com and wheel zooming was not working. I have done some own projects with making standalone html files and the wheel zoom worked fine there.

**Comment by bryevdv** [comment] 2016-07-06 21:32
Are you saying it is not working for you here as well:

https://demo.bokehplots.com/apps/sliders

I think you must have a local configuration issue of some sort, I use the wheel zoom on server apps daily.

**Comment by tkchris93** [comment] 2016-07-06 21:34
Whether I host the example myself or go to the url you just posted, it isn't working for me.

**Comment by bryevdv** [comment] 2016-07-06 21:38
Can you try other browsers, and ideally other machines?

**Comment by bryevdv** [comment] 2016-07-06 21:44
The tool is not activated by default. When you click the icon to activate it, does the "underline" for activation show up next to the icon?

**Comment by tkchris93** [comment] 2016-07-06 22:02
I was using Chrome when it wasn't working. It does work for me in Firefox

**Comment by bryevdv** [comment] 2016-07-06 22:09
dupe of this I think https://github.com/bokeh/bokeh/issues/4354  I thought we had resolved that tho

**Comment by tkchris93** [comment] 2016-07-06 22:13
I'm using Bokeh 0.12.0 if that makes a difference.

**Comment by tkchris93** [comment] 2016-07-06 22:15
After reading through #4354, it's probably worth me mentioning I also have a touch screen laptop.

**Comment by birdsarah** [comment] 2016-07-22 16:08
@tkchris93 - does @4862 accurately describe your problem. If so, can we close this issue as this isn't a server problem.

@bryevdv #4354 may be related, but doesn't have to be.

**Comment by tkchris93** [comment] 2016-07-22 20:07
#4862 sounds like the exact same problem I was having. I didn't realize that pinch zooming was working until I tried it today. I have a Dell touchscreen laptop and am using Chrome.

**Comment by birdsarah** [comment] 2016-07-22 20:36
closing as duplicate

**Closed by birdsarah** 2016-07-22 20:36 UTC
