### ISSUE TITLE
[BUG] new circle glyphs from PointDrawTool not shown in gmap plot

### ISSUE THREAD

**Issue by jvanheugten** [bokeh/bokeh#11654] opened 2021-09-21 08:09 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh: 2.4.0
Python 3.8.6
Chrome: Version 93.0.4577.82

#### Description of expected behavior and the observed behavior
Observed:
Moving a circle glyph with a `PointDrawTool` in a `gmap` plot makes the circle disappear. Similarly when adding a new point, it doesn't show up. The new position does show up in the underlying ColumnDataSource.

Expected:
Circle glyph is shown in newly clicked/dragged position on gmap plot.

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.io import show
from bokeh.models import ColumnDataSource, GMapOptions, PointDrawTool
from bokeh.plotting import gmap

map_options = GMapOptions(lat=30.1255, lng=-100.8540, map_type="satellite", zoom=15)
API_KEY=<your_api_key>

p = gmap(API_KEY, map_options, title="Austin", tools='hover,wheel_zoom,reset,pan', active_drag='auto', active_scroll='wheel_zoom')

source = ColumnDataSource(
    data={'xlong': [-100.8540], 'ylat': [30.1255]}
)

circle = p.circle(x="xlong", y="ylat", size=15, fill_color="blue", fill_alpha=0.3, source=source)
draw_tool = PointDrawTool(renderers=[circle], empty_value="black")
p.add_tools(draw_tool)
p.toolbar.active_tap = draw_tool

show(p)
```

#### Stack traceback and/or browser JavaScript console output
The google maps API can probably be updated too. Might be nice to add it as a keyword option in `GMapOptions`.
```
Google Maps JavaScript API warning: RetiredVersion https://developers.google.com/maps/documentation/javascript/error-messages#retired-version
```

**Comment by mattpap** [comment] 2021-09-21 08:24
> Google Maps JavaScript API warning: RetiredVersion

This can be configured with `GMapOptions.api_version`, though we will update this to a more recent API.

**Comment by tcmetzger** [comment] 2021-09-21 20:38
I have been able to reproduce this with Bokeh 2.4 on Ubuntu (Firefox and Chromium). The api_version warning seems unrelated.

**Comment by bryevdv** [comment] 2021-09-21 20:51
Normally map plots use coordinates in meters (web mercator) not lat/lon. There is some special case path that makes lat/long "work" for GMap but I am guessing he way that PointDrawTool works doesn't take that into consideration somehow. They were added at different times, years apart.

**Comment by mattpap** [comment] 2021-09-21 21:12
Those tools have to be made aware of `use_map` and invert the projection before storing data in a data source.

**Comment by mattpap** [comment] 2021-09-22 23:21
Closing as a duplicate of issue #7775.

**Closed by mattpap** 2021-09-22 23:21 UTC
Labels: type: bug, reso: duplicate, tag: component: bokehjs
