### ISSUE TITLE
Heat Map Modifying Data Source

### ISSUE THREAD

**Issue by bmweiner** [bokeh/bokeh#4017] opened 2016-03-10 19:46 UTC
When I pass a pandas DataFrame to the Heat Map chart and set `stat=None`, the df is modified. This is not the case when I set `stat='count'` or `stat='sum'`. Can the heat map bin calculation work on a copy of the df instead? Here is a quick example:

    import pandas as pd
    from bokeh.charts import HeatMap

    data = dict(year=[1,1,1,2,2,2,3,3,3],
                        cat=['a','b','c','a','b','c','a','b','c'],
                        val=[1.2, 2.1, 3, 2, 1.2, 3.3, 4, 2.1, 1])
    df = pd.DataFrame(data)
    hm = HeatMap(data=df, x='year', y='cat', values='val', stat=None)
    df.values

    array([['a', '[1, 1.5]', 1, 1.2],
           ['b', '(2, 2.5]', 1, 2.1],
           ['c', '(2.5, 3]', 1, 3.0],
           ['a', '(1.5, 2]', 2, 2.0],
           ['b', '[1, 1.5]', 2, 1.2],
           ['c', '(3, 3.5]', 2, 3.3],
           ['a', '(3.5, 4]', 3, 4.0],
           ['b', '(2, 2.5]', 3, 2.1],
           ['c', '[1, 1.5]', 3, 1.0]], dtype=object)

**Comment by birdsarah** [comment] 2016-03-10 20:48
@bmweiner, thanks for the report, a fix for this was just merged, it'll be in the next release.

https://github.com/bokeh/bokeh/pull/3909

duplicate of: #3899

**Closed by birdsarah** 2016-03-10 20:48 UTC
Labels: reso: duplicate

**Comment by bmweiner** [comment] 2016-03-11 01:37
Great, thanks!
