### ISSUE TITLE
Plots disappear after zooming in/out in some browsers

### ISSUE THREAD

**Issue by mattpap** [bokeh/bokeh#4611] opened 2016-06-21 11:20 UTC
Toolbar is still visible though. To make plots appear on screen again, one has to press reset tool button, or reload the page. This happens across all examples with simple and complicated layouts. Reproducible at least in FF and Chrome.

**Comment by bryevdv** [comment] 2016-06-21 12:34
Zooming (specifically `meta-plus` and `meta-minus`) *do* work on Safari, which is probably why this was missed.  I don't zoom much ever,  and I use safari the most, the intersection of those two is even smaller. I will announce RC1 with a link to this known issue.

**Comment by HuntJSparra** [comment] 2016-06-21 14:38
Same issue with IE on Windows although was able to use most tools, for example dragging w/ pan, and was able to make the plot visible again.

**Comment by mattpap** [comment] 2016-06-21 14:53
It looks like `sizing_mode="fixed"` is only affected. Most likely #4493 caused this.

**Comment by mattpap** [comment] 2016-06-21 15:05
> Most likely #4493 caused this.

Confirmed.

**Comment by almarklein** [comment] 2016-06-21 15:06
Reproduced on Windows Chrome/FF/Edge

**Comment by almarklein** [comment] 2016-06-21 15:06
@mattpap let me know if you want me to have a look

**Comment by mattpap** [comment] 2016-06-21 15:07
> let me know if you want me to have a look

@almarklein, look at a PR? I'm far from it.

**Comment by mattpap** [comment] 2016-06-21 15:09
This raises a question why it works in Safari. It shouldn't. Perhaps `listenToOnce()` is broken there.

**Comment by almarklein** [comment] 2016-06-21 15:10
>  look at a PR? I'm far from it.

Yeah, unless you're already closing in on a solution

**Comment by bryevdv** [comment] 2016-06-21 16:28
OK this is a confusing conversation. :) Who is actively looking into a fix for this?

**Comment by mattpap** [comment] 2016-06-21 19:39
@bryevdv, I'm working on this, but I understand your confusion. At this point I'm not sure what @almarklein was referring to.

**Comment by almarklein** [comment] 2016-06-21 20:09
Hehe, sorry for the confusion. I was trying to say that if you wanted me to work on this, you could let me know :)

**Comment by bryevdv** [comment] 2016-06-21 20:47
@mattpap OK great, thanks. As soon as this is ready let's cut RC2

**Comment by mattpap** [comment] 2016-06-22 13:24
This is a pretty complex issue, which must be fixed at some point, but definitively is too big change just before release. The safest approach right now is to revert #4493. This will make rendering work, but the performance regression will persist. Given the impact of both issues, I think a localized performance regression is secondary concern and we should proceed with a revert.

**Comment by bryevdv** [comment] 2016-06-22 13:34
@mattpap can you make a PR that reverts #4493 for now? I tend to agree that's probably the safest route for the time being but I'd also like to try  it out.

**Comment by mattpap** [comment] 2016-06-22 13:35
@bryevdv, I'm doing so right now.

**Comment by mattpap** [comment] 2016-06-22 13:41
@bryevdv, #4625.

**Comment by bryevdv** [comment] 2016-06-22 14:45
checking it out now

**Comment by birdsarah** [comment] 2016-06-22 18:31
Maybe we want to open a new issue...but documenting here for now.

The underlying problem seems to be that when you window zoom in and out, a re-render to canvas is correctly called, but somehow the glyph re-renderers aren't called. 

Undoing the listenToOnce is a brute force way of handling this. I'm sure there's a more subtle listen to that we could add or something that we could add into plot_canvas.render but I couldn't find it quickly.

**Comment by birdsarah** [comment] 2016-06-22 18:57
I have a fairly tidy solution.

**Closed** 2016-06-23 04:58 UTC
Labels: tag: regression, type: bug
