### ISSUE TITLE
Bug in viridis colormap?

### ISSUE THREAD

**Issue by jbednar** [bokeh/bokeh#5184] opened 2016-09-19 14:25 UTC
On the current public web site, the 6-color version of viridis is reversed:

![image](https://cloud.githubusercontent.com/assets/1695496/18635198/ca4e63f6-7e49-11e6-8229-f4c3817854d1.png)

It was correct as of 0.12.1:

![image](https://cloud.githubusercontent.com/assets/1695496/18635395/8ff31ff2-7e4a-11e6-89b8-e528e28035a9.png)

I can't tell what the problem is, because the current source code looks correct in both Python and JS:

```
./bokeh/palettes.py:417:Viridis5    = ['#440154', '#3B518A', '#208F8C', '#5BC862', '#FDE724']
./bokeh/palettes.py:418:Viridis6    = ['#440154', '#404387', '#29788E', '#22A784', '#79D151', '#FDE724']
```

```
./bokeh/server/static/js/bokeh.js:28870:    Viridis5: [0x440154, 0x3b518a, 0x208f8c, 0x5bc862, 0xfde724],
./bokeh/server/static/js/bokeh.js:28871:    Viridis6: [0x440154, 0x404387, 0x29788e, 0x22a784, 0x79d151, 0xfde724],
```

I.e., all of these start and end with the same colors, so none of them are reversed.  ???

**Comment by bryevdv** [comment] 2016-09-19 14:27
dupe of #5170

**Closed by bryevdv** 2016-09-19 14:27 UTC

**Comment by jbednar** [comment] 2016-09-19 14:35
D'oh!  I searched the git log for anything mentioning viridis, but didn't see it in the issues list somehow.  Sorry for the noise.
