### ISSUE TITLE
[BUG] Log scale makes bars in vbarplot disappear

### ISSUE THREAD

**Issue by wittenator** [bokeh/bokeh#9105] opened 2019-07-21 13:34 UTC
## ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh - 1.2.0
Python - 3.6.8
Jupyter - 5.3.1
Run in a docker container - tensorflow/tensorflow:nightly-py3-jupyter

#### Description of expected behavior and the observed behavior

Once I select a log scale for the y axis in a vertical bar plot all bars disappear. This seems to have been solved in #3834, but maybe it got reintroduced. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
p = figure(plot_width=400, plot_height=400, y_axis_type="log", y_range=(0.001, 10**1), x_range=(0, 5))
p.vbar(x=[1, 2, 3], width=0.5, bottom=0, top=[1.2, 2.5, 3.7], color="firebrick")
show(p)

```
#### Screenshots or screencasts of the bug in action
![bokeh_plot(2)](https://user-images.githubusercontent.com/9154515/61591948-ca773980-abcc-11e9-9843-0ff5b66a7486.png)

**Comment by wittenator** [comment] 2019-07-21 13:51
Just saw the connection to #6536. Is there any known workaround for the moment?

**Comment by bryevdv** [comment] 2019-07-21 18:28
@wittenator I am going to close this as a duplicate of #6536 since it is a special case of that general problem. Apart from "very small value" the other workaround for now would be to create a custom `Mapper` class that handles the log scale with zero differently.

**Closed by bryevdv** 2019-07-21 18:28 UTC
Labels: TRIAGE
