### ISSUE TITLE
Bokeh Grouped Bar Graph Error (bokeh version 12.15)

### ISSUE THREAD

**Issue by immaculatePIE** [bokeh/bokeh#7727] opened 2018-04-02 19:08 UTC
This is in regards to the latest posted version of bokeh - 12.15

Noticed an issue with the bokeh example bar graph for Mean MPG by # Cylinders and Manufacturers charting. The code runs without error but the display is an empty tab. See the code and screenshot below.

Bokeh Issue URL - https://bokeh.pydata.org/en/latest/docs/user_guide/categorical.html

---------------------------------------------------CODE BEGIN--------------------------------------------------

```
from bokeh.io import show, output_file
from bokeh.models import ColumnDataSource, HoverTool
from bokeh.plotting import figure
from bokeh.palettes import Spectral5
from bokeh.sampledata.autompg import autompg_clean as df
from bokeh.transform import factor_cmap

output_file("bars.html")

df.cyl = df.cyl.astype(str)
df.yr = df.yr.astype(str)

group = df.groupby(('cyl', 'mfr'))

source = ColumnDataSource(group)
index_cmap = factor_cmap('cyl_mfr', palette=Spectral5, factors=sorted(df.cyl.unique()), end=1)

p = figure(plot_width=800, plot_height=300, title="Mean MPG by # Cylinders and Manufacturer",
           x_range=group, toolbar_location=None, tools="")

p.vbar(x='cyl_mfr', top='mpg_mean', width=1, source=source,
       line_color="white", fill_color=index_cmap, )

p.y_range.start = 0
p.x_range.range_padding = 0.05
p.xgrid.grid_line_color = None
p.xaxis.axis_label = "Manufacturer grouped by # Cylinders"
p.xaxis.major_label_orientation = 1.2
p.outline_line_color = None

p.add_tools(HoverTool(tooltips=[("MPG", "@mpg_mean"), ("Cyl, Mfr", "@cyl_mfr")]))

show(p)
```

--------------------------------------------------CODE COMPLETE----------------------------------------------

What SHOULD be displayed
(Data is categorized according to given criteria)
![categorical_plot](https://user-images.githubusercontent.com/38014480/38210858-9c84e8ae-3686-11e8-91bc-f6df58dd9849.PNG)

What is ACTUALLY displayed
(Actual plot does not display anything in either Internet Explorer **or** Google Chrome
![display](https://user-images.githubusercontent.com/38014480/38211063-433ef2d4-3687-11e8-8436-5362fdd7bbfe.PNG)

**Comment by bryevdv** [comment] 2018-04-02 19:13
@immaculatePIE I can't reproduce any problem with that code, I copied and pasted it into an editor and ran it and the expected output was generated. Please provide more information (all relevant system or browser versions, any browser console output) and please verify that there is not some installation or multi-environment issue (e.g running with a different version than intended)

**Comment by bryevdv** [comment] 2018-04-03 15:00
Closing, we can re-open if information to reproduce is provided.

**Closed by bryevdv** 2018-04-03 15:00 UTC
Labels: reso: norepro, type: discussion

**Comment by immaculatePIE** [comment] 2018-04-03 15:54
Sorry Bryan. Have been swamped at work and took me a bit to look into this deeper. Looks like I do have multiple versions of python on my computer so I'll have to look into this further. Safe to close in the mean time thanks a bunch.

Nick

**Comment by bryevdv** [comment] 2018-04-03 16:05
@immaculatePIE no worries, just trying to adopt a "close sooner, re-open later (if needed)" to get the tracker under better control. If you do find a reproducible please let us know and we will check into it.
