### ISSUE TITLE
BokehJS : log axis

### ISSUE THREAD

**Issue by svideau** [bokeh/bokeh#6330] opened 2017-05-26 01:56 UTC
When I use BokehJS to plot a figure with log axis, the plotted figure is not scaled. 

BokehJS :  0.12.5 (and 0.12.6dev6)
https://plnkr.co/edit/c1AFdnKk4zQFiidaI6KK

Basically, with the 0.12.5, i can't plot with   y_axis_type:"log"  without manually defining an y_range .
The 0.12.6dev6 makes it possible, but in both cases:
the axis ticks are correcly labeled, but their spacing is the same as in a continuous axis.

![bokeh_plot](https://cloud.githubusercontent.com/assets/17825517/26477631/5146aee0-41c7-11e7-8ccd-a015d2706d8c.png)

**Comment by bryevdv** [comment] 2017-05-26 02:01
ping @mattpap this also reminds me I'm not sure if the BokehJS API was updated for the recent `Scale` work or not

**Comment by bryevdv** [comment] 2017-06-30 21:06
@svideau I can't actually reproduce any issue, see e.g.

http://bokeh.pydata.org/en/0.12.6/docs/gallery/logaxis.html

which has both log ticks and places them as expected. I am going to close this since there is no complete minimal code to reproduce the problem. If you have code to reproduce a problem that you can share, please feel free to re-open with that included.

**Closed by bryevdv** 2017-06-30 21:06 UTC
Labels: type: bug
