### ISSUE TITLE
Bokeh Legend Glyph Styling Issue

### ISSUE THREAD

**Issue by eddy-ojb** [bokeh/bokeh#6329] opened 2017-05-25 22:37 UTC
I hope that this is an easy one to solve but Bokeh's default legend rendering is wrong. Specifically, the size of the glyphs in the legend should match that of those in the graph. My plots don't look right with them. I can see that I can edit the legend glyph size in pixels using 'glyph_height' attr but I don't want to hardcode it.

e.g.:

http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#legends

Ed

**Comment by bryevdv** [comment] 2017-05-26 14:52
@eddy-ojb There is nothing built-in currently apart from what you have linked to. The current `Legend` was designed for cases when it is reasonable to take a single abstract representative sample to represent many instances of a glyph. It doesn't copy or use the actual size of glyph because, in general, the glyph might be way to big or small to be usable in a legend. Bokeh has no way to know. 

I'm not opposed to thinking about features for to make other kinds of legends easier to create. But the thing that would help focus that is:

* some concrete examples
* proposed syntax for how to make those cases simple
* thoughts about how to make it hard or impossible to generate nonsense configurations

In the mean time, glyphs themselves together with text (or labels) can be used to create more sophisticated legends "by hand", e.g. as in 

http://bokeh.pydata.org/en/latest/docs/gallery/burtin.html

**Comment by bkfunk** [comment] 2017-09-17 16:29
This is related to a request I have: I'm making a bubble plot, but all my legends need to be outside the plot because of the amount of data. I would like to be able to add the minimum and maximum size of the bubbles with the corresponding value; so at least a user could get a sense of what a circle with size=2 means vs one with size=20. I'm thinking of the [ggplot size legend](https://www.r-bloggers.com/creating-and-tweaking-bubble-chart-with-ggplot2/).

**Comment by bkfunk** [comment] 2018-04-11 00:11
Here's another thing I'd love to be able to do: I have a lot of circles on a scatter plot, so I made them very transparent so that you can see the overlaps. But, now they are too transparent to be easily visible in the legend (there are different series with different colors). I'd love to be able to tweak the legend glyph alpha separately from the plot glyph alpha.

**Comment by bryevdv** [comment] 2018-07-03 16:02
dupe of #2603

**Closed by bryevdv** 2018-07-03 16:02 UTC
Labels: type: discussion
