### ISSUE TITLE
Histogram Chart showing bad count numbers on single value bins

### ISSUE THREAD

**Issue by rshield** [bokeh/bokeh#4335] opened 2016-05-17 23:05 UTC
It seems in sparse data sets that the y values directly convert to counts in the histogram plot.

With the following code, I get an interesting result.

```
import pandas as pd

some_array = pd.np.random.rand(100)
arr = pd.np.append(some_array, [10, -1, -3, -10])

df = pd.DataFrame({"testData":arr})
from bokeh.charts import Histogram, show

p = Histogram(df)
show(p)
```
![weirdbokehhistogram](https://cloud.githubusercontent.com/assets/657220/15342256/261fb4a6-1c51-11e6-9dae-1b128998523a.png)

As seen, there is only one value for 10, -1, -3, and -10 but the histogram shows them having high counts than they actually have.

I also added in another 10 to the array and the bin went down to the correct count of 2.

**Comment by dennisobrien** [comment] 2016-05-18 05:10
I think this is a duplicate of #3875 which should be addressed by PR #3988 

I believe this should be in the 0.12.0 release.  If you need it sooner you can build from one of the 0.12.0dev tags.

**Comment by damianavila** [comment] 2016-05-18 14:29
Seems to be a duplicate... @rshield can you test it with master? Alternative, we can put a devel build out there so you can try it quickly before the next 0.12 release...

**Comment by rshield** [comment] 2016-05-18 15:43
I agree.  My apologies for not doing a deeper dive on all of the histogram bug reports.  I was just look at titles that were somewhat phrased like mine.

Thanks.

**Closed** 2016-05-18 16:54 UTC
