### ISSUE TITLE
IPython 3 notebook: reimporting bokeh.plotting breaks plot controls

### ISSUE THREAD

**Issue by payne92** [bokeh/bokeh#2091] opened 2015-03-22 21:33 UTC
In IPython 3, re-executing the cell containing:

    from bokeh.plotting import *

breaks existing and subsequent plots.  See screen shot, below; the pan, zoom, resize etc. buttons are broken.  This also breaks "run all", which (I'm guessing) would be common way most people would run into the problem.

Details:
+ IPython 3 Github HEAD
+ Bokeh 0.8.1
+ Notebook server running behind nginx

![screenshot 2015-03-22 at 5 29 16 pm](https://cloud.githubusercontent.com/assets/638998/6771599/fe6cd20c-d0b8-11e4-868f-4f379ebeda9b.png)

**Comment by bryevdv** [comment] 2015-03-22 22:02
This issue is fixed in master and available in the latest dev build. Dupe of https://github.com/bokeh/bokeh/issues/2024

**Closed by bryevdv** 2015-03-22 22:02 UTC

**Comment by bryevdv** [comment] 2015-03-22 22:03
See http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds for instructions on installing dev build packages.
