### ISSUE TITLE
Bug when the middle area between two tabs is clicked

### ISSUE THREAD

**Issue by chesucr** [bokeh/bokeh#8611] opened 2019-02-01 11:34 UTC
Hello Bokeh Team!!

I am working on Windows 10 with Google Chrome version 71.0.3578.98 (Build oficial) (64 bits)

    Python version      :  3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bit (AMD64)]
    IPython version     :  7.1.1
    Tornado version     :  5.1.1
    Bokeh version       :  1.0.4
    node.js version     :  v10.13.0
    npm version         :  6.4.1

There is a small bug when I press in the middle of two tabs. This error is thrown in the js console:

    tabs.js:44 Uncaught TypeError: Cannot read property 'classList' of undefined

Here the GIF to show you the bug

![tab_bug](https://user-images.githubusercontent.com/11211829/52120750-98255000-261d-11e9-84e6-1193d77f40b4.gif)

And a minimal example:

    from bokeh.models import ColumnDataSource
    from bokeh.plotting import figure
    from bokeh.layouts import row
    from bokeh.io import curdoc
    from bokeh.models.widgets.panels import Panel, Tabs

    source = ColumnDataSource(dict(
        x=[1, 2, 3, 4, 5, 6],
        y=[1, 2, 3, 4, 5, 6],
        z=[6, 5, 4, 3, 2, 1],
        q=[16, 15, 14, 13, 12, 11],
    ))

    p = figure(
        plot_height=300,
        tools='lasso_select'
    )

    r1 = p.scatter(
        x='x',
        y='y',
        size=20,
        color='red',
        source=source,
        fill_alpha=1.0,
        line_alpha=1.0,
    )

    p2 = figure(
        plot_height=300,
        tools='lasso_select',
    )

    r3 = p2.scatter(
        x='x',
        y='q',
        size=20,
        color='blue',
        source=source,
        fill_alpha=1.0,
        line_alpha=1.0,
    )

    panel_list = []
    panel_list.append(Panel(child=p, title='A'))
    panel_list.append(Panel(child=p2, title='B'))

    tabs_widget = Tabs(
        tabs=panel_list,
        width=1250,
    )

    curdoc().add_root(row(children=[tabs_widget]))

**Comment by bryevdv** [comment] 2019-02-01 16:04
Good news is that I can't reproduce any problem with #8085, which is set to be merged to day (in fact there simply is no space "between" tabs anymore with that PR)

**Closed** 2019-02-01 16:18 UTC
