### ISSUE TITLE
[BUG] `export_png` does not work correctly when using a custom theme

### ISSUE THREAD

**Issue by jpmorr** [bokeh/bokeh#12683] opened 2022-12-14 21:40 UTC
### Software versions

Python version      :  3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:50:36) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.4.0
Tornado version     :  6.1
Bokeh version       :  2.4.3
BokehJS static path :  C:\Users\jm\Anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

Firefox / Edge

### Jupyter notebook / Jupyter Lab version

Jupyter lab 3.4.4

### Expected behavior

I've created a theme file to format high resolution figures in a notebook which I'm then exporting to png using `export_png`. I've created the following theme file:

```yaml
attrs:      
    Figure:
        width: 1600
        height: 1200
        background_fill_color: '#ffffff'
        border_fill_color: '#ffffff'
        outline_line_color: '#111111'
        
    Axis:
        axis_line_color: !!null
        axis_label_text_font_size: "32pt"
        axis_label_text_font_style: 'bold'
        axis_label_text_color: '#000000'
        
        major_label_text_color: "#000000"
        major_label_text_font: "Helvetica"
        major_label_text_font_size: "28pt"
        
        major_tick_line_alpha: 1
        major_tick_line_color: "#000000"

        minor_tick_line_alpha: 1
        minor_tick_line_color: "#000000"

        axis_line_alpha: 0
        axis_line_color: "#000000"       

    Grid:
        grid_line_color: '#666666'
        grid_line_dash: 'solid'
        grid_line_alpha: 1
        
    Legend:
        label_text_font: "Helvetica"
        label_text_font_style: "bold"
        label_text_color: "black"
        label_text_font_size: "28pt"
        border_line_color: "#666666" 
        border_line_width: 2
        location: 'bottom_center'
        click_policy: 'hide'
        glyph_width: 50
        glyph_height: 50
        spacing: 25
        orientation: 'horizontal'
    
    Title:
        text_color: "black"
        text_font_size: "36pt"
        
    Toolbar:
        autohide: True

```

which I load into the notebook using:
```python
from bokeh.themes import Theme
curdoc().theme = Theme(filename="./bokeh_theme.yml")
```

When I create a figure, which is sized and formatted as expected, I try to write to png:
```python
export_png(p1, filename="plot1.png")
```

This should create a png of the figure, as formatted with the same size and formatting as in the notebook.

![image](https://user-images.githubusercontent.com/10863809/207720212-b7afa6b6-8c3c-45b7-abed-ac9e74473d37.png)

### Observed behavior

The exported png completely ignores the formatting as defined in the theme and as displayed in the notebook and generates the png with the default formatting as a low res 600x600 png file which is not good enough quality for publication or presentations.

`export_png` creates high resolution, formatted images if all of the formatting is applied as the figure is created in the notebook instead of via the `theme.yaml` method.

![test](https://user-images.githubusercontent.com/10863809/207720535-72f18219-20a0-4ef7-a2d0-16aa7b2e7f2f.png)

### Example code

```Python
import numpy as np 

from bokeh.io import push_notebook, output_notebook, export_png
from bokeh.layouts import row, gridplot
from bokeh.plotting import figure, show, output_file, curdoc
from bokeh.models import HoverTool, Span
from bokeh.palettes import Category10 
from bokeh.themes import Theme
curdoc().theme = Theme(filename="./bokeh_theme.yml")

output_notebook()
TOOLS = "pan,wheel_zoom,box_zoom,zoom_in,zoom_out,reset,save,box_select, hover"

p1 = figure(title="Test - X-axis", tools=TOOLS)
p1.line(data_x, data_y, line_width=3.5, line_dash='dashed', color='red', legend_label="Test")

p1.xaxis.axis_label = 'Distance [m]'
p1.yaxis.axis_label = 'Value [-]'

p1.add_layout(p1.legend[0], 'below')

show(p1)

export_png(p1, filename="test.png")
```

**Comment by bryevdv** [comment] 2022-12-14 21:45
@jpmorr can you please confirm whether this is an issue for you with the latest release (3.0.3)? There will not be any more 2.x releases so that is what really matters to know.

**Comment by jpmorr** [comment] 2022-12-14 22:05
@bryevdv  I'm also using `holoviews` which has `bokeh` pinned at 2.4.3-2.5. I will try to create a new env with bokeh 3.0.3 installed and get back to you.

**Comment by mattpap** [comment] 2022-12-14 22:26
This is a duplicate of #10804 fixed in PR https://github.com/bokeh/bokeh/pull/12281.

**Closed as completed** 2022-12-14 22:27 UTC
Labels: reso: duplicate

**Comment by jpmorr** [comment] 2022-12-14 22:42
Thanks @mattpap and @bryevdv . I've installed `3.0.3` and `export_png` now works as expected, although I've got some other notebook issue now - the plot is not rendered in my notebook for some reason and the output is now:
`Javascript Error: e is not iterable`.

I'm not sure why this is happening or how the png can be rendered if the notebook isn't. Maybe it will sort itself out.

```
Python version      :  3.9.15 | packaged by conda-forge | (main, Nov 22 2022, 08:39:05) [MSC v.1929 64 bit (AMD64)]
IPython version     :  8.7.0
Tornado version     :  6.1
Bokeh version       :  3.0.3
BokehJS static path :  C:\Users\jmorrise\Anaconda3\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19044-SP0
```

**Comment by bryevdv** [comment] 2022-12-14 23:00
> some other notebook issue now

@jpmorr do you mean with pure Bokeh code? Or with HV/Panel code? If the former, please make sure the notebook output cells are cleared and that the `output_notebook` output shows the correct  version. If the latter, that's something to take up on a holoviz tracker. AFAIK they are still working on updating for 3.x

**Comment by jpmorr** [comment] 2022-12-15 10:08
@bryevdv Thanks! Yes, this is a test with pure Bokeh so clearing all the outputs from the cells restored functionality.
