### ISSUE TITLE
[FEATURE] Disabling the button inside the function launched by this button

### ISSUE THREAD

**Issue by PlatonB** [bokeh/bokeh#11582] opened 2021-09-10 21:35 UTC
**Preamble.**
I'm trying to find a very simple, well documented tool to build an uncomplicated GUI for my program, which simplifies interaction with MongoDB. Bokeh seemed like a perfect solution to me.

**Problem.**
As follows from the introduction, the program works with the DB, so the code can take a very long time to execute. I found that immediately after pressing the Run button it is possible to press it again and again. In the toy code example below, I unsuccessfully tried to lock the Run button while the main code is running.
```
import time
from bokeh.models import Slider, Button
from bokeh.plotting import curdoc
from bokeh.layouts import column

class Gui():
        def __init__(self):
                some_slider = Slider(start=1, end=10,
                                     value=5, step=1,
                                     title='Some slider')
                some_slider.on_change('value', self.upd_slider)
                self.some_slider_val = some_slider.value
                self.run_button = Button(label='Run')
                self.run_button.on_click(self.run)
                curdoc().add_root(column([some_slider,
                                          self.run_button]))
        def upd_slider(self, attr, old, new):
                self.some_slider_val = new
        def run(self):
                self.run_button.disabled = True

                #Any long-running task instead
                time.sleep(10)
                print(f'{self.some_slider_val} ^ 2 =',
                      self.some_slider_val ** 2)
                
                self.run_button.disabled = False
                
gui = Gui()
```

**Checking.**
To check if `disabled = True` works in general, I moved it to `__init__`. Only then the Run button became light.

**Conclusion.**
The problem is not very severe, because if one uses the interface carefully, it is possible to avoid multiplication of task execution. But it's better to have foolproofing. A small accompanying feature request: to prompt that the task is already in progress, could spinner widget ([example](https://python-gtk-3-tutorial.readthedocs.io/en/latest/spinner.html)).

**Comment by bryevdv** [comment] 2021-09-12 01:55
This is a duplicate of https://github.com/bokeh/bokeh/issues/3393

**Closed by bryevdv** 2021-09-12 01:55 UTC
Labels: TRIAGE

**Comment by PlatonB** [comment] 2021-09-12 10:03
@bryevdv The spinner I recommended only as an additional measure. The main suggestion is the possibility to _disable the button_ for the time the function is performed.

**Comment by bryevdv** [comment] 2021-09-12 15:12
Buttons are already disable-able

**Comment by PlatonB** [comment] 2021-09-12 20:33
@bryevdv I am using the latest stable version (2.3.3). The button in the example I provided is not able to disable.

**Comment by bryevdv** [comment] 2021-09-12 22:33
@PlatonB property sync only happens at the *end* of callbacks. To do something like this, you need to put the "remaining" work in a next-tick callback. There are questions with answers on SO and on the Bokeh Discourse. We re in the middle of prepping a release so unfortunately I cannot go into more detail right now.
