### ISSUE TITLE
Bokeh reloads page with default slider values after each button triggered update

### ISSUE THREAD

**Issue by jbrambleDC** [bokeh/bokeh#4154] opened 2016-04-11 02:55 UTC
I have a bokeh app with defined sliders, hover tools, and 4 figures defined using Figure not figure, that I will display in a 4x4 fashion. Everything looks fine and renders properly on initial load. I have a button that calls an update function when clicked. Upon click, it updates the data sources, updates the plots briefly and then immediately reloads the entire page with the default values.

here is a code snippet for my udate function and how the document is rendered:
```python
def update():
    begin_date = '{}-{}-01'.format(min_year.value, format_month(min_month.value))
    end_date = '{}-{}-31'.format(max_year.value, format_month(max_month.value))
    store_num = store_map[store_name.value]
    item_id = items[inventory.value]

    data = data_source(item_id, store_num, begin_date, end_date)

    ### Update titles
    p.title = 'Daily {} Usage @ {}'.format(inventory.value, store_name.value)
    p1.title = 'Usage Vs. Netsales for {} @ {}'.format(inventory.value, store_name.value)
    p2.title = 'Monthly {} Usage at {}'.format(inventory.value, store_name.value)
    #p3.title = 'Usage by day of week for {}'.format(inventory.value)

    ### Update axis sizes
    p.y_range = Range1d(0, np.max(data['y_avg']) + 100)
    p1.y_range = p.y_range
    p2.y_range = Range1d(0, data['usage_by_month']['daily_usage'].max() + 50)

    ### update data sources
    source1.data = dict(x=data['x_all'], y=data['y_all'], date=data['all_date'])
    source2.data = dict(x=data['x_avg'], y=data['y_avg'], date=data['avg_date'])
    source3.data = dict(netsales=data['netsales'],
                        usage=data['usage'],
                        day=data['day'],
                        store_name=data['storename'],
                        color=data['color'])

    source4.data = dict(x=data['x_mean'], y=data['y_mean'], date=data['avg_date'])
    source5.data = dict(posted_month=data['usage_by_month']['posted_month'].tolist(),
                        usage=data['usage_by_month']['daily_usage'].tolist())


controls = [store_name, inventory, min_year, max_year, min_month, max_month, button]
button.on_click(update)
inputs = HBox(VBoxForm(*controls), width=400)
update()
plots1 = HBox(p, p1, width=1200)
plots2 = HBox(p2, width=1200)
plots = VBox(plots1, plots2)
#res = gridplot([[p, p1], [p2]])
curdoc().add_root(HBox(inputs, plots, width=1200))
```

Desired functionality, would be for the update function not to cause the entire page to reload with default values. I am wondering if this is caused by some edge case with curdoc/add_root?

Let me know if app screenshots are needed?

I am using version 0.11.0

**Comment by bryevdv** [comment] 2016-04-11 04:31
This appears to be a dupe of https://github.com/bokeh/bokeh/issues/3895, fixed in #3925 currently in master.

**Closed by bryevdv** 2016-04-11 04:31 UTC
