### ISSUE TITLE
Bokeh v 0.12.4 repeating hover icon bug

### ISSUE THREAD

**Issue by koganm** [bokeh/bokeh#5802] opened 2017-01-26 20:55 UTC
Hey guys,

Firstly, great job with Bokeh - I've been a user for the last few years and have been loving it!
![screen shot 2017-01-26 at 3 48 52 pm](https://cloud.githubusercontent.com/assets/9089529/22349897/a8766660-e3df-11e6-9a4f-31075e314745.png)

I noticed a funny bug when going from v0.12.3 to 0.12.4: I have a Figure with a bunch of glyphs, each of which has hover capability, and looks like a hover icon is being added to the toolbar for each glyph. I've attached a screenshot below:

![screen shot 2017-01-26 at 3 48 52 pm](https://cloud.githubusercontent.com/assets/9089529/22349932/c289094a-e3df-11e6-83c4-caf90a3398ba.png)

Hopefully this is a simple fix. I will be removing the extra Hover icons with a custom jQuery call in the meantime.

Thanks

**Comment by bryevdv** [comment] 2017-01-26 20:57
This is a dupe of #5497

**Closed by bryevdv** 2017-01-26 20:57 UTC

**Comment by mattpap** [comment] 2017-01-26 22:13
@koganm, grouping of hover tool buttons is something we will restore, but how do you end up with so many hover tools?

**Comment by koganm** [comment] 2017-01-26 22:26
@mattpap i have a bunch of line and scatter Glyphs in my Figure that each have separate ColumnDataSources and HoverTools (i tried minimizing the number of Glyphs & CDSs but couldn't do so because I need the lines need to be different thicknesses at different points in time along the x axis)

**Comment by koganm** [comment] 2017-01-26 22:27
This hover icon bug is not critical for me at this time, just wanted to make sure you guys were aware of it.
