### ISSUE TITLE
Unable to Stack Multiple Twin Axis on Same Side

### ISSUE THREAD

**Issue by amy-ding** [bokeh/bokeh#2006] opened 2015-03-02 16:12 UTC
When I try to stack multiple axis on the same side, the image compresses, resulting in an x-axis with width 0.  

The below works fine, with a regular multi-line plot:
```
output_notebook()
plot = figure(title = 'test')
x = range(0, 10)
y = range(0, 10)
y2 = range(11, 20)
y3 = range(12, 20)
plot.line(x, y, legend = 'y', y_axis_label = 'y')
plot.extra_y_ranges = {}
plot.extra_y_ranges['y2'] = Range1d(start = 10, end = 20)
plot.extra_y_ranges['y3'] = Range1d(start = 10, end = 20)
plot.add_layout(LinearAxis(y_range_name = 'y2', axis_label = 'y2'), 'right')
plot.add_layout(LinearAxis(y_range_name = 'y3', axis_label = 'y3'), 'left')

plot.line(x, y2, legend = 'y2', color = 'red', y_axis_label = 'y2', y_range_name = 'y2')
plot.line(x, y3, legend = 'y3', color = 'green', y_axis_label = 'y3', y_range_name = 'y3')

plot.extra_y_ranges
```

However, when I change the plot.add_layout() to both be on the right side, you get an image like this:

![twin_axis](https://cloud.githubusercontent.com/assets/11274379/6444635/e16a2ae8-c0cc-11e4-949d-3aa9fafd2c41.png)

I'm using 0.7.1, but I don't think there were significant changes wrt the axis plotting, in 0.8. This is in follow-up to https://groups.google.com/a/continuum.io/d/msg/bokeh/S45Yy5VNczE/cpNe1jge_I8J

**Comment by bryevdv** [comment] 2015-03-02 17:54
When I try this on current master it works as expected: 
![screen shot 2015-03-02 at 11 53 31 am](https://cloud.githubusercontent.com/assets/1078448/6446776/d73600b4-c0d2-11e4-8e65-85bfddc53cca.png)
Can you provide more information about your system, versions, etc? Also if possible can you try installing the dev build from last Friday?

**Comment by silverorange05** [comment] 2015-03-02 18:11
Right, it works when you specify one to be on the left, and one to be on the right.  Try substituting in this:

plot.add_layout(LinearAxis(y_range_name = 'y2', axis_label = 'y2'), 'right')
plot.add_layout(LinearAxis(y_range_name = 'y3', axis_label = 'y3'), 'right')

I haven't been able to get this second version to work.  I'd expect to see the same plot, except with two levels of y-axis on the right side, but that's not the case.

**Comment by amy-ding** [comment] 2015-03-02 18:12
Right, it works when you specify one to be on the left, and one to be on the right. Try substituting in this:

plot.add_layout(LinearAxis(y_range_name = 'y2', axis_label = 'y2'), 'right')
plot.add_layout(LinearAxis(y_range_name = 'y3', axis_label = 'y3'), 'right')

I haven't been able to get this second version to work. I'd expect to see the same plot, except with two levels of y-axis on the right side, but that's not the case.

**Comment by bryevdv** [comment] 2015-03-02 18:28
Sure enough, must be a bug in the layout constraints specifications at a fairly low level.

**Comment by bryevdv** [comment] 2016-04-02 22:27
ping @birdsarah please just keep this example in mind as you work on layout, it may be something that falls out naturally from that work

**Comment by birdsarah** [comment] 2016-04-06 16:13
hah! on my current prototype you just get a blank screen - thanks for the headsup.

**Comment by birdsarah** [comment] 2016-05-04 09:18
Just ran into this again. This is specifically when multiple items are added on the right. The problem is that the width calculation appears to not take precedence and pull things to the right. Have confirmed the rightmost-right item is correctly stuck to the right of canvas, and the left-most right item is correctly stuck to the right of the frame.

**Comment by birdsarah** [comment] 2016-05-30 05:30
Confirm status in #4392. The last I recall, you could put two things on the right, but then two axes plus a title got confused.

**Comment by birdsarah** [comment] 2016-06-15 13:23
This has improved with #4343 but is not fixed in some general case:

* two right axes now works
* three right axes now works

* four right axes doesn't work and fails as above

<img width="777" alt="screen shot 2016-06-15 at 6 17 56 am" src="https://cloud.githubusercontent.com/assets/1796208/16081139/0f16816e-32c1-11e6-8b50-7f06dbbfbfb8.png">


* you seem to be able to have unlimited left axes with up to three right axes

<img width="777" alt="screen shot 2016-06-15 at 6 17 27 am" src="https://cloud.githubusercontent.com/assets/1796208/16081099/db8cfd64-32c0-11e6-95a2-006d36e8ca0b.png">

Similarly (but slightly different) you can only have three things on top axis. Two axes + title or three axes.

<img width="658" alt="screen shot 2016-06-15 at 6 21 24 am" src="https://cloud.githubusercontent.com/assets/1796208/16081198/67e650f8-32c1-11e6-80f5-cb1c3a22b354.png">

 A total of four and things break.

<img width="681" alt="screen shot 2016-06-15 at 6 22 00 am" src="https://cloud.githubusercontent.com/assets/1796208/16081224/800f8212-32c1-11e6-8ff3-20a45880a501.png">

Code for these tests is here: https://github.com/birdsarah/bokeh-miscellany/blob/master/new_layout_tests/test_titles.py

I'm going to close this because we've fixed the original bug. There's clearly an issue still left here, but it seems like a corner case and I'd rather wait to see if it affects someone before sticking in backlog.

**Closed by birdsarah** 2016-06-15 13:23 UTC
Labels: type: bug
