### ISSUE TITLE
pip installation instructions insufficient: 'Import Error: No module named 'yaml''

### ISSUE THREAD

**Issue by szeitlin** [bokeh/bokeh#4089] opened 2016-03-31 18:51 UTC
this is on ubuntu (vagrant on Mac) running Jupyter with python 3.4
bokeh.__version__: 0.11.1

followed instructions for making sure the installation worked. 

here's the traceback:

    from bokeh.plotting import figure, output_file, show 
    output_notebook()
    p = figure()
    p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=2)
    show(p)

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-47-a23edd017376> in <module>()
----> 1 from bokeh.plotting import figure, output_file, show
      2 output_notebook()
      3 p = figure()
      4 p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=2)
      5 show(p)

/home/vagrant/venv/lib/python3.4/site-packages/bokeh/plotting/__init__.py in <module>()
      1 
      2 # extra imports -- just things to add to 'from bokeh.plotting import'
----> 3 from ..document import Document; Document
      4 
      5 from ..models import ColumnDataSource; ColumnDataSource

/home/vagrant/venv/lib/python3.4/site-packages/bokeh/document.py in <module>()
     16 from .core.query import find
     17 from .core.validation import check_integrity
---> 18 from .model import Model
     19 from .themes import default as default_theme
     20 from .themes import Theme

/home/vagrant/venv/lib/python3.4/site-packages/bokeh/model.py in <module>()
     11 from .core.properties import Any, HasProps, List, MetaHasProps, String
     12 from .core.query import find
---> 13 from .themes import default as default_theme
     14 from .util.callback_manager import CallbackManager
     15 from .util.future import with_metaclass

/home/vagrant/venv/lib/python3.4/site-packages/bokeh/themes/__init__.py in <module>()
      6 from os.path import join
      7 
----> 8 from .theme import Theme
      9 
     10 default = Theme(json={})

/home/vagrant/venv/lib/python3.4/site-packages/bokeh/themes/theme.py in <module>()
      5 from __future__ import absolute_import, print_function
      6 
----> 7 import yaml
      8 
      9 from ..core.properties import HasProps

ImportError: No module named 'yaml'
---

Get a similar traceback from the `bokeh info` command:

(venv)vagrant@ubuntu:/vagrant$ bokeh info
Traceback (most recent call last):
  File "/home/vagrant/venv/bin/bokeh", line 5, in <module>
    from bokeh.command.bootstrap import main
  File "/home/vagrant/venv/lib/python3.4/site-packages/bokeh/command/__init__.py", line 15, in <module>
    _build_docstring()
  File "/home/vagrant/venv/lib/python3.4/site-packages/bokeh/command/__init__.py", line 10, in _build_docstring
    from . import subcommands
  File "/home/vagrant/venv/lib/python3.4/site-packages/bokeh/command/subcommands/__init__.py", line 29, in <module>
    all = _collect()
  File "/home/vagrant/venv/lib/python3.4/site-packages/bokeh/command/subcommands/__init__.py", line 17, in _collect
    mod = import_module("." + modname, __package__)
  File "/home/vagrant/venv/lib/python3.4/importlib/__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/vagrant/venv/lib/python3.4/site-packages/bokeh/command/subcommands/html.py", line 56, in <module>
    from bokeh.resources import Resources
  File "/home/vagrant/venv/lib/python3.4/site-packages/bokeh/resources.py", line 29, in <module>
    from .model import Model
  File "/home/vagrant/venv/lib/python3.4/site-packages/bokeh/model.py", line 13, in <module>
    from .themes import default as default_theme
  File "/home/vagrant/venv/lib/python3.4/site-packages/bokeh/themes/__init__.py", line 8, in <module>
    from .theme import Theme
  File "/home/vagrant/venv/lib/python3.4/site-packages/bokeh/themes/theme.py", line 7, in <module>
    import yaml
ImportError: No module named 'yaml'

If yaml is supposed to be supplied, this is a bug. If not, please provide instructions on how to install it (I tried pip and sudo apt-get, but they're not finding any distributions for yaml).

**Comment by mattpap** [comment] 2016-03-31 19:33
Module `yaml` is provided by `PyYAML` package, so `pip install PyYAML`. However, looking at bokeh's `setup.py`, everything seems to be configured properly and PyYAML should be installed as a dependency.

**Comment by mattpap** [comment] 2016-03-31 19:34
btw. @bokeh/dev, why do we need both `pyyaml` and `yaml` at build?

**Comment by bryevdv** [comment] 2016-03-31 20:21
Yah I don't understand why pip would not install pyyaml automatically. For build I would think just pyyaml would suffice? yaml is the c library but should be installed as a dependency

**Comment by bryevdv** [comment] 2016-04-07 21:32
@szeitlin Can you post your pip install logs? My current best guess is that pip installed the python binding for `pyyaml` for you, but that your linux system is actually missing the `yaml` C library. ` I guess I would have assumed that most linux distros would come with `yaml` installed but perhaps not. 

I can't exactly reproduce this on Ubuntu 14, when I pip install every thing, it turns out that `markupsafe` is missing (which I thought `Jinja2` should bring in as a dependency) but when install that, every thing works as expected. In my pip log I *do* see `PyYAML` get installed by pip. 

As an aside: while I do want to resolve this, I also have to suggest trying Anaconda/conda. I am admittedly biased in this regard, but it's also true that everything just works.

**Comment by szeitlin** [comment] 2016-04-07 21:39
Agreed that I prefer conda, can't use it in this case b/c I'm stuck inside a venv that was created for another project with pip. IME it's ok to use pip inside conda, but not the other way around. 

I checked with pip freeze and PyYAML was not there. So I tried pip install PyYAML, seems like you are correct that it 'installed' but did not compile. But it says "successfully installed" at the end. Sigh. I can try to see if bokeh magically works now... if not I can try to see if I can get what I need to make it compile. 

```
(venv)vagrant@ubuntu:/vagrant$ pip install pyyaml
Downloading/unpacking pyyaml
  Downloading PyYAML-3.11.tar.gz (248kB): 248kB downloaded
  Running setup.py (path:/home/vagrant/venv/build/pyyaml/setup.py) egg_info for package pyyaml
    
Installing collected packages: pyyaml
  Running setup.py install for pyyaml
    checking if libyaml is compilable
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include/python3.4m -I/home/vagrant/venv/include/python3.4m -c build/temp.linux-x86_64-3.4/check_libyaml.c -o build/temp.linux-x86_64-3.4/check_libyaml.o
    build/temp.linux-x86_64-3.4/check_libyaml.c:2:18: fatal error: yaml.h: No such file or directory
     #include <yaml.h>
                      ^
    compilation terminated.
    
    libyaml is not found or a compiler error: forcing --without-libyaml
    (if libyaml is installed correctly, you may need to
     specify the option --include-dirs or uncomment and
     modify the parameter include_dirs in setup.cfg)
    
  Could not find .egg-info directory in install record for pyyaml
Successfully installed pyyaml
```

**Comment by bryevdv** [comment] 2016-04-07 21:45
Ah, I think you need to `apt-get install libyaml-dev`

**Comment by szeitlin** [comment] 2016-04-07 21:53
actually, it seems to be working so far. thanks!

**Comment by bryevdv** [comment] 2016-04-07 21:58
@szeitlin glad to hear it, I will close this issue for now. If we hear other reports we can decide to add docs or investigate further.

**Closed by bryevdv** 2016-04-07 21:58 UTC
Labels: type: discussion

**Comment by MartinThoma** [comment] 2017-10-09 09:23
I had this problem because I installed it with

```
sudo pip install pyyaml --upgrade
```

instead of

```
sudo -H pip install pyyaml --upgrade
```

Uninstalling and re-installing pyyaml fixed the problem for me.
