### ISSUE TITLE
[BUG] ADocumentCallbackManager' object has no attribute '_change_callbacks'

### ISSUE THREAD

**Issue by comatrion** [bokeh/bokeh#11675] opened 2021-09-23 19:01 UTC
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### Complete, minimal, self-contained example code that reproduces the issue

```
# code goes here between backticks

```

#### Screenshots or screencasts of the bug in action

*Note: Everyone interacting in the Bokeh project's codebases, issue trackers, and discussion forums is expected to follow the [Code of Conduct](https://github.com/bokeh/bokeh/blob/master/CODE_OF_CONDUCT.md).*

**Comment by bryevdv** [comment] 2021-09-23 19:03
@comatrion I'm not sure happened but the report above is completely missing any of the information reqested in the template. Pklease update to include all the necessary info (versions, platform, and ***most especially***, a 
complete [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example))

**Comment by comatrion** [comment] 2021-09-23 19:11
intermittent cannot repro closing

**Comment by bryevdv** [comment] 2021-09-23 19:14
Please note that the *private* attribute `_change_callbacks` was in fact removed from `Document` in the 2.4 release. But I just verified that nothing in the current codebase refers to `Document._change_callbacks` any longer, so I don't think Bokeh itself could possibly generate this error, outside of some version/install mixup. If something outside Bokeh is relying on a private attribute, that is not a Bokeh issue, and is incumbent on whoever used a private attribute to make their own fix.

**Comment by philippjfr** [comment] 2021-09-27 08:12
This is a real issue as far as I can tell, basically `Document.callbacks.destroy` run `del self._change_callbacks` which gets rid of the attribute but then subsequent code may still try to access this. I don't have a reproducible example right now but I have also seen this after shutting down a server session.

**Comment by comatrion** [comment] 2021-09-27 15:45
Sorry I have tried to repro this but no success yet. It occurs for me like this
```
try:
   # ...
except ValueError:
   doc.add_next_tick_callback(...)
```
I suspect the exception is invoking `destroy` then the reported error is thrown in the `except`.

**Comment by philippjfr** [comment] 2021-09-27 15:51
Yes, that was what I found as well. It's probably fairly hard to reproduce since it's basically a race condition when a callback is triggered just after the `destroy`.

**Comment by bryevdv** [comment] 2021-09-27 21:41
The *only* places that make use of `DocumentCallbackManager._change_callbacks` are in `document/callbacks.py` (as should be be the case) so it should be simple to just condition those few places with a check. We could set `self._change_callbacks` to None to facilitate that. Or perhaps an empty dict would even suffice.

**Comment by bryevdv** [comment] 2023-04-10 04:41
Closing for lack of MRE. We can consider re-opening if/when additional information  is provided.

**Closed by bryevdv** 2023-04-10 04:41 UTC
Labels: type: discussion, NEEDS MORE INFO
