### ISSUE TITLE
With WebGL backend selected, the radius of circles change when zooming in close 

### ISSUE THREAD

**Issue by tkchris93** [bokeh/bokeh#6858] opened 2017-08-31 20:02 UTC
When the WebGL backend is active for a Figure, circles with a set radius start to shrink as you zoom in close.

I'm using Bokeh 0.12.7, MacOS, Google Chrome, python 2.7.13

```
from bokeh.plotting import Figure
from bokeh.io import output_file, show
from bokeh.layouts import row

output_file('webgl_bug.html')

fig1 = Figure(title='No WebGL (Proportions are maintained as you zoom)', 
        x_range=(-50, 50), y_range=(-50, 50), tools=['wheel_zoom', 'pan'], 
        active_scroll="wheel_zoom")
fig1.circle(x=[-10,0,10], y=[0,0,0], radius=5)

fig2 = Figure(title='With WebGL (Zoom affects proportions)', 
        x_range=(-50, 50), y_range=(-50, 50), tools=['wheel_zoom', 'pan'], 
        active_scroll="wheel_zoom", output_backend='webgl')
fig2.circle(x=[-10,0,10], y=[0,0,0], radius=5)

show(row(fig1, fig2))
```
Notice that in the code, the radii are all set to 5, but when WebGL is the backend, the circles are not drawn with radius 5.

<img width="1213" alt="screen shot 2017-08-31 at 1 49 43 pm" src="https://user-images.githubusercontent.com/10438787/29942927-c1d76a62-8e54-11e7-924d-80b02271893e.png">

**Comment by bryevdv** [comment] 2017-09-05 03:56
I am unable to reproduce this behavior on `master` with either Chrome or FF on OSX. @tkchris93 can you try a recent dev build?

**Comment by bryevdv** [comment] 2018-03-17 03:19
Closing for no followup, if there was an issue, the recent `match_aspect` might be the solution anyway.

**Closed by bryevdv** 2018-03-17 03:19 UTC
Labels: reso: norepro, type: discussion
