### ISSUE TITLE
Adding User Defined Layouts

### ISSUE THREAD

**Issue by brendancol** [bokeh/bokeh#3339] opened 2015-12-14 15:12 UTC
Currently extending `HBox` and `VBox` doesn't work because those classes do not appear in `main.coffee`.  Any reason why `widgets` as a whole are not registered in `main.coffee`?

**Comment by bryevdv** [comment] 2015-12-14 15:27
They are in the separate `widgets.coffee` that generates `bokeh-widgets.js` AFAIK. ping @mattpap

**Comment by mattpap** [comment] 2015-12-14 19:28
@brendancol, you register new widgets in `bokehjs/src/coffee/widget/main.coffee`, the same as you would do with core bokeh classes in `common/base`.

**Comment by brendancol** [comment] 2015-12-14 19:33
@mattpap So my issue was that to extend those widgets as User Defined Models, I think they need to be registered in `coffee/main.coffee`.  Seems like either the UDM logic needs to also check `widgets/main.coffee` OR widgets also need to be in `coffee/main.coffee`. As a start, I wanted to include `widgets/layout` in `coffee/main` so users could extend Layout.

**Comment by mattpap** [comment] 2015-12-14 19:36
User defined models don't need any manual registration.

**Comment by mattpap** [comment] 2015-12-14 19:37
In any case, @brendancol please show the code and then I can tell you more where the issue is.

**Comment by brendancol** [comment] 2015-12-14 20:23
@mattpap, yeah something like this:
```
from bokeh.properties import Dict, String
from bokeh.model.widgets import BaseBox

class StyleableBox(BaseBox):
    __implementation__ = '''
        _ = require "underscore"
        build_views = require "common/build_views"
        ContinuumView = require "common/continuum_view"
        BaseBox = require "widget/basebox"

        class StyleableBoxView extends ContinuumView
          tag: "div"
          attributes:
            class: "bk-vbox"

          initialize: (options) ->
            super(options)
            @views = {}
            @render()
            @listenTo(@model, 'change', @render)

          render: () ->
            children = @model.children()
            build_views(@views, children)
            for own key, val of @views
              val.$el.detach()
            @$el.empty()

            css_props = @mget("css_properties")
            if css_props? then @$el.css(css_props)

            for child in children
              @$el.append(@views[child.id].$el)
            return @

        class StyleableBox extends BaseBox.Model
          type: "StyleableBox"
          default_view: StyleableBoxView

          defaults: ->
            return _.extend {}, super(), {
              children: []
              css_properties: {}
            }

          children: () ->
            return @get('children')

        module.exports =
          Model: StyleableBox
          View: StyleableBoxView
        '''
    css_properties = Dict(String, String, default=None)
```

So this is a quick example of a CSS Styleable Box which extends `BaseBox`.  Since `widgets/basebox` is not in `coffee/main.coffee` this will not work.

**Comment by mattpap** [comment] 2015-12-14 23:25
So, it's not going to work right now because wrong `require()` is used in the module generated for the custom model.

**Comment by bryevdv** [comment] 2015-12-22 01:08
Marking as closed but please re-open if I am in error

**Closed** 2015-12-22 01:07 UTC
Labels: tag: bokehjs, tag: examples, tag: widgets, type: bug
