### ISSUE TITLE
Select widget on_change breaks figures in other tabs

### ISSUE THREAD

**Issue by watsonjj** [bokeh/bokeh#5466] opened 2016-11-16 12:04 UTC
I have two tabs, the first containing one figure, the other containing a different figure with a Select widget. When selecting a value in the Select widget, the figure in tab1 breaks (it seems to become extremely small), despite the widget only changing the figure in tab2.

This is with Bokeh version 0.12.4dev6.

A simplified example is below:
```
import numpy as np
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.layouts import WidgetBox, column
from bokeh.models.widgets import Select, Panel, Tabs


def create_fig(a, index):
    n_d2 = a.shape[1]

    x = np.arange(n_d2)
    y = a[index]

    print(a.shape)
    print(index)
    print(a[index])

    fig = figure(width=900, height=360)
    c = fig.circle(x=x, y=y, hover_color="red")

    return fig


def update(attr, old, new):
    group.children[1] = create_fig(array, select.value)

array = np.random.randint(0,1000,(10,5))
options = ['{:.0f}'.format(x) for x in range(array.shape[0])]

# Get figures
fig1 = create_fig(array, 0)
fig2 = create_fig(array, 1)

select = Select(title="i:", value='0', options=options)
wb = WidgetBox(select)

tab1 = Panel(child=fig1, title='1')
group = column([wb, fig2])
tab2 = Panel(child=group, title='2')
tabs = Tabs(tabs=[tab1, tab2])

select.on_change('value', update)

curdoc().add_root(tabs)
```

**Comment by bryevdv** [comment] 2016-12-10 20:04
There are definitely some known issues wrt to Tabs and layout. I expect this is related to those, and that layout for `Tabs` needs a fairly thorough going over to fix them all at once. I am going to mark this as a dupe of #5143 ("Tabs not working") but also leave an explicit reference and comment in that issue to make sure this is verified as fixed with any work for that issue.

**Closed by bryevdv** 2016-12-10 20:04 UTC
