### ISSUE TITLE
Ability to plot with multiple categorical axes

### ISSUE THREAD

**Issue by kmmueller** [bokeh/bokeh#3091] opened 2015-11-09 23:57 UTC
I am trying to use Bokeh for some financial analyses and am trying to find a way to do the following:
Plot two curves (trailing twelve month average and total per quarter) on the same graph.

The issues I'm having are the following:
1) My data comes with it's own labels (not datetime)
2) I need one categorical axis to compute and plot trailing twelve month average (months in categorical labels being x-axis1_
3) I need the ability to add a second categorical axis that represents the totals per fiscal year and quarter (FY-Q as a categorical set of labels, again not datetime)

I have seen that it is possible to add additional x axes using syntax like:
p3.extra_x_ranges = {"foo": Range1d(start=0, end=35)}
p3.add_layout(LinearAxis(x_range_name="foo",axis_line_color="green",major_label_text_color="green"), "below")

However is seems that the .extra_x_ranges only allows for a type of Range1d.

I would like to be able to add .extra_x_ranges of type categorical. 

How can this be done?

**Comment by birdsarah** [comment] 2015-11-11 08:28
@kmmueller I'm afraid it looks like this is broken.

Here's a notebook documenting the issue: http://nbviewer.ipython.org/github/birdsarah/bokeh-miscellany/blob/master/tests/%233091%20add%20multiple%20categorical%20axes.ipynb

**Comment by kmmueller** [comment] 2015-11-11 16:38
@birdsarah - thanks for confirming that this is a bug along with the example.  I hope it is something someone can take care of soon as I really want to use Bokeh for my application but this is causing me problems.

**Comment by kmmueller** [comment] 2016-03-29 20:48
Any update on this issue?  It seems to not have been assigned to anyone for correction although it is recognized as a bug.

Thanks!

**Comment by bryevdv** [comment] 2016-04-03 00:09
Hi @kmmueller at present there are 700+ issues in the tracker, which I would estimate at a few person-years worth of work (assuming no new issues, of course, which is not reasonable). It's encouraging that more people are becoming interested in and active in core development, since making the denominator bigger in `work / people` is the only long-term way to tame the issues list. But currently the group is still quite small, and further, everyone in it is also at best only available part-time to work on Bokeh. Perhaps some day we will be in a position to affirmatively "assign" issues to individuals, either when the major components that are the highest priorities are fully baked out, or when there are many more contributors, or both. Until then, I am afraid it is still largely the common OSS refrain: overtaxed devs choosing what itches they want (and can find time) to scratch. 

I realize that this is probably not the answer that you would like to hear. But please understand that while no one *wants* to leave bugs sitting, we are all human beings and only have so many hours in a day. If Bokeh is not suitable for your uses today, I hope you will give it another try in the future.

**Comment by bryevdv** [comment] 2017-08-21 22:18
As near as I can tell (as best as I can interpret from the minimal description) this is covered by the recent categorical work:

<img width="541" alt="screen shot 2017-08-21 at 17 16 47" src="https://user-images.githubusercontent.com/1078448/29540566-a62929d0-8694-11e7-8324-c4f2df26b9b0.png">

```
from bokeh.io import show, output_file
from bokeh.models import ColumnDataSource, FactorRange
from bokeh.plotting import figure

output_file("bars.html")

factors = [
    ("Q1", "jan"), ("Q1", "feb"), ("Q1", "mar"),
    ("Q2", "apr"), ("Q2", "may"), ("Q2", "jun"),
    ("Q3", "jul"), ("Q3", "aug"), ("Q3", "sep"),
    ("Q4", "oct"), ("Q4", "nov"), ("Q4", "dec"),

]

p = figure(x_range=FactorRange(*factors), plot_height=250,
           toolbar_location=None, tools="")

x = [ 10, 12, 16, 9, 10, 8, 12, 13, 14, 14, 12, 16 ]
p.vbar(x=factors, top=x, width=0.9, alpha=0.5)

p.line(x=["Q1", "Q2", "Q3", "Q4"], y=[12, 9, 13, 14], color="red", line_width=2)

p.y_range.start = 0
p.x_range.range_padding = 0.1
p.xaxis.major_label_orientation = 1
p.xgrid.grid_line_color = None

show(p)
```

So I am closing this as a dupe of #4369

**Closed by bryevdv** 2017-08-21 22:18 UTC
Labels: type: bug
