### ISSUE TITLE
[BUG] ColorBar with LogTicker is incorrect when range is < 1

### ISSUE THREAD

**Issue by thoralf-gutierrez** [bokeh/bokeh#9583] opened 2020-01-17 07:03 UTC
I noticed issues when using a `log_cmap` with a `ColorBar` and `LogTicker`. As soon as the range of my color map goes under 1, the LogTicker does not correspond to the actual color in the plot.

See this minimal example. Notice how the blue bins on the plot are counts = 1 but show up as < 1 on the color bar.

![image](https://user-images.githubusercontent.com/5640848/72590975-e4f84a00-38b3-11ea-95a5-f30eb46c5767.png)

And the code to generate the plot

```python
import numpy as np

from bokeh.io import output_file, show
from bokeh.plotting import figure
from bokeh.transform import log_cmap
from bokeh.util.hex import hexbin
from bokeh.models import ColorBar, LogTicker, HoverTool

n = 50000
x = np.random.standard_normal(n)
y = np.random.standard_normal(n)

bins = hexbin(x, y, 0.1)

p = figure(match_aspect=True, background_fill_color='#440154', toolbar_location="left")
p.grid.visible = False

# works
# cmap = log_cmap('counts', 'Spectral11', 1, max(bins.counts))

# doesn't work
# blue bins on the plot are count = 1 but show up as < 1 on the color bar
cmap = log_cmap('counts', 'Spectral11', 0.1, max(bins.counts))

h = p.hex_tile(q="q", r="r", size=0.1, line_color=None, source=bins, fill_color=cmap)

hover = HoverTool(
    tooltips=[('Counts', '@counts')],
    mode='mouse',
    point_policy='follow_mouse',
    renderers=[h],
)
p.add_tools(hover)

color_bar = ColorBar(
    color_mapper=cmap['transform'],
    location=(0, 0),
    ticker=LogTicker(),
)
p.add_layout(color_bar, 'right')

output_file("log_colormap.html")
show(p)
```

I'm using
* bokeh 1.4.0
* Chrome 79.0.3945.117 
* Python 3.5.6
* macOS 10.14.6

**Comment by bryevdv** [comment] 2020-01-17 19:09
This is a dupe of https://github.com/bokeh/bokeh/issues/8724 which was fixed on master in https://github.com/bokeh/bokeh/pull/8832 (yet to be released)

<img width="619" alt="Screen Shot 2020-01-17 at 11 09 19 AM" src="https://user-images.githubusercontent.com/1078448/72639159-d80e4180-3919-11ea-94a9-f2875dabc273.png">

**Closed by bryevdv** 2020-01-17 19:09 UTC
Labels: TRIAGE
