### ISSUE TITLE
DataTable performance

### ISSUE THREAD

**Issue by wabu** [bokeh/bokeh#8227] opened 2018-09-08 17:17 UTC
Performance with bokeh models containing data-table widgets is slow when the model gets updated (streaming data to it or changing widgets), adding up to some seconds of delay. When debugging it in the browser, Chromium warns about "Recalculate Style
Warning: Forced reflow is a likely performance bottleneck." (see screenshot below).

bokeh 0. 13.0
python 3.6.6 Anaconda
Chromium 66.0.3359.139
Debian 4.16.5-1
Linux 4.16.0-1-amd64

Here's an example, where adding a button cases the delay, but also had the problem when adding data to a plot with holoviews pipes

```python
import bokeh.io as bki
import bokeh.models as bkm
import bokeh.layouts as bkl

doc = bki.curdoc()

from datetime import date
from random import randint, choice

n = 20
data = dict(
        dates=[date(2014, 3, i%30+1) for i in range(n)],
        downloads=[randint(0, 100) for i in range(n)],
        foo=[randint(0, 100) for i in range(n)],
        bar=[randint(0, 100) for i in range(n)],
        baz=[randint(0, 100) for i in range(n)],
    )
source = bkm.ColumnDataSource(data)

columns = [
        bkm.TableColumn(field="dates", title="Date", formatter=bkm.DateFormatter()),
        bkm.TableColumn(field="downloads", title="Downloads"),
        bkm.TableColumn(field="foo", title="Foo"),
        bkm.TableColumn(field="bar", title="Bar"),
        bkm.TableColumn(field="baz", title="Baz"),
    ]

table1 = bkm.DataTable(source=source, columns=columns[:-1])#, editable=True)
table2 = bkm.DataTable(source=source, columns=columns[1:])#, editable=True)

action = bkm.Button(label="click me")
foo = bkm.Button(label="foo")
box = bkl.widgetbox([action, foo], sizing_mode='scale_width')

def act():
    #last = label = box.children[1].label
    #while label == last:
    label = choice(["foo", "bar", "baz", "bla"])
    foo = bkm.Button(label=label)
    box.children.insert(1, foo)
                    
action.on_click(act)

doc.add_root(bkl.column(box, bkl.widgetbox(table1, table2)))
```

![2018-09-08-112531_1364x719_scrot](https://user-images.githubusercontent.com/39164/45256499-5d352e00-b397-11e8-979d-807e531ba1f1.png)

**Comment by wabu** [comment] 2018-09-09 06:53
Here are some detailed js call trees with calls that generate performance warnings:

0 ms0 % | 39.5 ms100.0 % | Function Call |  
-- | -- | -- | --
0 ms0 % | 39.5 ms100.0 % | i.socket.onmessageconnection.js:61 |  
0 ms0 % | 39.5 ms100.0 % | t._on_messageconnection.js:189 |  
0 ms0 % | 39.5 ms100.0 % | ACK.t.msgtype._current_handlerconnection.js:242 |  
0 ms0 % | 39.5 ms100.0 % | t._steady_state_handlerconnection.js:255 |  
0 ms0 % | 39.5 ms100.0 % | t.handlesession.js:16 |  
0 ms0 % | 39.5 ms100.0 % | t._handle_patchsession.js:69 |  
0 ms0 % | 39.5 ms100.0 % | P.apply_json_patchdocument.js:674 |  
0 ms0 % | 39.5 ms100.0 % | u.setvhas_props.js:222 |  
0 ms0 % | 39.5 ms100.0 % | u._setvhas_props.js:183 |  
0 ms0 % | 39.5 ms100.0 % | e.emitsignaling.js:67 |  
0 ms0 % | 39.5 ms100.0 % | t.emitsignaling.js:50 |  
0 ms0 % | 39.5 ms100.0 % | (anonymous)widget_box.js:14 |  
0 ms0 % | 39.5 ms100.0 % | t.rebuild_child_viewslayout_dom.js:196 |  
0 ms0 % | 39.5 ms100.0 % | t.layoutlayout_dom.js:156 |  
0 ms0 % | 39.5 ms100.0 % | t.layoutlayout_dom.js:156 |  
0 ms0 % | 39.5 ms100.0 % | t._do_layoutlayout_dom.js:162 |  
0 ms0 % | 39.5 ms100.0 % | t._layoutlayout_dom.js:182 |  
0 ms0 % | 39.5 ms100.0 % | t._layoutlayout_dom.js:182 |  
0 ms0 % | 39.5 ms100.0 % | t._layoutlayout_dom.js:182
0 ms0 % | 39.5 ms100.0 % | e.renderdata_table.js:160 |  
0 ms0 % | 39.5 ms100.0 % | SlickGridslick.grid.js:35 |  
0 ms0 % | 39.5 ms100.0 % | initslick.grid.js:185 |  
0 ms0 % | 39.5 ms100.0 % | finishInitializationslick.grid.js:279 |  
0 ms0 % | 39.5 ms100.0 % | bindAncestorScrollEventsslick.grid.js:500 |  
39.5 ms100.0 % | 39.5 ms100.0 % | Recalculate Styleslick.grid.js:504


0 ms0 % | 39.5 ms100.0 % | Function Call |  
-- | -- | -- | -- 
0 ms0 % | 39.5 ms100.0 % | i.socket.onmessageconnection.js:61 |  
0 ms0 % | 39.5 ms100.0 % | t._on_messageconnection.js:189 |  
0 ms0 % | 39.5 ms100.0 % | ACK.t.msgtype._current_handlerconnection.js:242 |  
0 ms0 % | 39.5 ms100.0 % | t._steady_state_handlerconnection.js:255 |  
0 ms0 % | 39.5 ms100.0 % | t.handlesession.js:16 |  
0 ms0 % | 39.5 ms100.0 % | t._handle_patchsession.js:69 |  
0 ms0 % | 39.5 ms100.0 % | P.apply_json_patchdocument.js:674 |  
0 ms0 % | 39.5 ms100.0 % | u.setvhas_props.js:222 |  
0 ms0 % | 39.5 ms100.0 % | u._setvhas_props.js:183 |  
0 ms0 % | 39.5 ms100.0 % | e.emitsignaling.js:67 |  
0 ms0 % | 39.5 ms100.0 % | t.emitsignaling.js:50 |  
0 ms0 % | 39.5 ms100.0 % | (anonymous)widget_box.js:14 |  
0 ms0 % | 39.5 ms100.0 % | t.rebuild_child_viewslayout_dom.js:196 |  
0 ms0 % | 39.5 ms100.0 % | t.layoutlayout_dom.js:156 |  
0 ms0 % | 39.5 ms100.0 % | t.layoutlayout_dom.js:156 |  
0 ms0 % | 39.5 ms100.0 % | t._do_layoutlayout_dom.js:162 |  
0 ms0 % | 39.5 ms100.0 % | t._layoutlayout_dom.js:182 |  
0 ms0 % | 39.5 ms100.0 % | t._layoutlayout_dom.js:182 |  
0 ms0 % | 39.5 ms100.0 % | t._layoutlayout_dom.js:182
0 ms0 % | 39.5 ms100.0 % | e.renderdata_table.js:160 |  
0 ms0 % | 39.5 ms100.0 % | SlickGridslick.grid.js:35 |  
0 ms0 % | 39.5 ms100.0 % | initslick.grid.js:185 |  
0 ms0 % | 39.5 ms100.0 % | finishInitializationslick.grid.js:279 |  
0 ms0 % | 39.5 ms100.0 % | bindAncestorScrollEventsslick.grid.js:500 |  
5.1 ms100.0 % | 5.1 ms100.0 % | Layoutslick.grid.js:504


0 ms0 % | 34.7 ms100.0 % | Function Call |  
-- | -- | -- | -- 
0 ms0 % | 34.7 ms100.0 % | i.socket.onmessageconnection.js:61 |  
0 ms0 % | 34.7 ms100.0 % | t._on_messageconnection.js:189 |  
0 ms0 % | 34.7 ms100.0 % | ACK.t.msgtype._current_handlerconnection.js:242 |  
0 ms0 % | 34.7 ms100.0 % | t._steady_state_handlerconnection.js:255 |  
0 ms0 % | 34.7 ms100.0 % | t.handlesession.js:16 |  
0 ms0 % | 34.7 ms100.0 % | t._handle_patchsession.js:69 |  
0 ms0 % | 34.7 ms100.0 % | P.apply_json_patchdocument.js:674 |  
0 ms0 % | 34.7 ms100.0 % | u.setvhas_props.js:222 |  
0 ms0 % | 34.7 ms100.0 % | u._setvhas_props.js:183 |  
0 ms0 % | 34.7 ms100.0 % | e.emitsignaling.js:67 |  
0 ms0 % | 34.7 ms100.0 % | t.emitsignaling.js:50 |  
0 ms0 % | 34.7 ms100.0 % | (anonymous)widget_box.js:14 |  
0 ms0 % | 34.7 ms100.0 % | t.rebuild_child_viewslayout_dom.js:196 |  
0 ms0 % | 34.7 ms100.0 % | t.layoutlayout_dom.js:156 |  
0 ms0 % | 34.7 ms100.0 % | t.layoutlayout_dom.js:156 |  
0 ms0 % | 34.7 ms100.0 % | t._do_layoutlayout_dom.js:162 |  
0 ms0 % | 34.7 ms100.0 % | t._layoutlayout_dom.js:182 |  
0 ms0 % | 34.7 ms100.0 % | t._layoutlayout_dom.js:182 |
0 ms0 % | 34.7 ms100.0 % | t._layoutlayout_dom.js:182 |  
0 ms0 % | 34.7 ms100.0 % | e.renderdata_table.js:160 |  
0 ms0 % | 34.7 ms100.0 % | SlickGridslick.grid.js:35 |  
0 ms0 % | 34.7 ms100.0 % | initslick.grid.js:185 |  
0 ms0 % | 34.7 ms100.0 % | finishInitializationslick.grid.js:279 |  
0 ms0 % | 34.7 ms100.0 % | resizeCanvasslick.grid.js:1709 |  
0 ms0 % | 34.7 ms100.0 % | getViewportHeightslick.grid.js:1699 |  
0 ms0 % | 34.7 ms100.0 % | cssjquery.js:5047 |  
0 ms0 % | 34.7 ms100.0 % | getjquery.js:5079 |  
0 ms0 % | 34.7 ms100.0 % | cssjquery.js:5047 |  
0 ms0 % | 34.7 ms100.0 % | jebokeh-tables.min.js?v=204673f…:0 |  
0 ms0 % | 34.7 ms100.0 % | getPropertyValue |  
34.7 ms100.0 % | 34.7 ms100.0 % | Recalculate Stylejquery.js:4811





As I am only familiar with python, I can't get into the details of the issue myself.

**Comment by wabu** [comment] 2018-09-10 06:52
Inside the real-world use-case, adding 6 tables restricting the rows to only a single one will already add a delay of around 2 seconds, doubling when using full tables (20-50 rows).

**Comment by mattpap** [comment] 2018-09-10 08:03
There are two issues here. One is that currently data tables (and everything else) are excessively rendered. This is fixed in PR #8085. The other thing is that changing layout is an expensive operation on its own. However, you are changing a branch that's unrelated to data tables, so they shouldn't be affected. I will need to assert in #8085 that that's actually true.

**Comment by bryevdv** [comment] 2018-10-09 18:30
Hrm, on my current data table PR the buttons are added immediately with no delay, but it does not affect any layout things. I have not tried with master or the latest release to compare though

**Comment by wabu** [comment] 2018-10-11 07:28
I'll check it with #8085

**Comment by bryevdv** [comment] 2018-10-11 15:57
@wabu just to be clear, I was unable to reproduce a delay on master, which has not yet merged #8085

**Comment by wabu** [comment] 2018-10-12 15:32
I'll have a look, thanks for trying!

**Comment by wabu** [comment] 2018-10-18 10:14
Tested with fresh build of master and still having problems. Clicking the button something like 10-times in a row, the browser will use all CPU and will take some seconds to catch up.

Same happens with a bigger dashboard when streaming data into a bokeh plot with holoviews.

**Comment by bryevdv** [comment] 2019-01-31 03:14
checked with current iteration of #8085, pressed the butting ~30 times and every button added instantly

**Closed** 2019-02-01 16:18 UTC
Labels: tag: performance, type: bug
