### ISSUE TITLE
[BUG] FileInput accept-type '.txt' file-extension filtering does not work as expected

### ISSUE THREAD

**Issue by jeffreymonaco** [bokeh/bokeh#10888] opened 2021-02-03 15:25 UTC
**SUMMARY:** FileInput file-extension filtering of selectable files does not work as expected for '.txt' extension type; it allows files with .csv, .py, etc. to be chosen. However, if the extension is changed to some other type, .e.g. '.csv' or '.json', the selectable options are filtered as expected.

**VERSIONS:** Bokeh 2.2.3, Python 3.8.5, Mac OSX Big Sur

**Minimal Reproducible Example**

```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
"""
from bokeh.models import FileInput
from bokeh.io import curdoc

def file_input_cb(attr, old, new):
    if new:
        print("INFO attr {:} old {:} new {:}".format(attr, old, new))

ui = FileInput(accept='.txt', multiple=False)
ui.on_change('value', file_input_cb)

curdoc().add_root(ui)
```

**Comment by bryevdv** [comment] 2021-02-17 02:54
@jeffreymonaco Same as the other issue, I cannot reproduce any problem on OSX / Safari. Browser version and screen grabs would be helpful here.

**Comment by jeffreymonaco** [comment] 2021-02-17 03:14
Thanks for the follow-up.

File-extension filtering works with Safari on OSX Big Sur. Screen grab for comparison to later non-working case.

<img width="1175" alt="Screen Shot 2021-02-16 at 10 05 00 PM" src="https://user-images.githubusercontent.com/8784099/108150999-bd217a00-70a3-11eb-9a46-aa0a205e1c1b.png">

Accessing the same running server app with Google Chrome (Version 88.0.4324.150 (Official Build) (x86_64) shows different behavior. The file-extension filtering allows files that do not match the *.txt extension. Here's the equivalent screen capture to the Safari example above, showing that Yocto patch files are selectable as valid choices whereas they were not when using Safari.

<img width="1216" alt="Screen Shot 2021-02-16 at 10 06 03 PM" src="https://user-images.githubusercontent.com/8784099/108151196-2e612d00-70a4-11eb-8646-55be16165b4e.png">

**Comment by bryevdv** [comment] 2021-02-19 18:58
All we do is 
```javascript
this.dialogEl.accept = this.model.accept
```
Is this a bug in Chrome?

**Comment by mattpap** [comment] 2021-02-26 20:45
Filtering works in Chrome 88 on Linux (tested on PR #10963).

**Comment by jeffreymonaco** [comment] 2021-02-26 20:55
This still does not work for Chrome 88 on Mac OSX Big Sur. That said, it does work for other operating systems and browser combinations that I have tested.

It appears this is a Chrome/OSX specific issue and not related to bokeh. Thanks for investigating.

**Comment by bryevdv** [comment] 2021-02-26 21:36
@jeffreymonaco upstream problems are always unfortunate/frustrating. I will re-label this issue for a task to add a note to the docs about this platform-specific issue.

**Comment by bryevdv** [comment] 2021-02-26 21:36
cc @tcmetzger in case you have thoughts on verbiage

**Comment by tcmetzger** [comment] 2021-02-26 22:02
We could add a note to the docstring for [bokeh.models.widgets.inputs.FileInput.accept](https://docs.bokeh.org/en/latest/docs/reference/models/widgets.inputs.html#bokeh.models.widgets.inputs.FileInput.accept). I don't think a note in the user guide is necessary, since the [example there](https://docs.bokeh.org/en/latest/docs/user_guide/interaction/widgets.html#fileinput) does not even mention the `accept` property and instead links to the reference guide entry.

> Note:
> A bug in some versions of Chrome on MacOS Big Sur makes it currently impossible to set a file input filter for those users. See [this question on Stackoverflow](https://stackoverflow.com/questions/49154550/input-type-file-accept-property-does-not-work-in-chrome) for more information.

I'll open a pull request for the docs update, we can continue the discussion there.

BTW: Filtering with `accept='.txt'` works as expected for me on Win10 with Firefox 86 and Chrome 88!

**Comment by jeffreymonaco** [comment] 2021-02-26 22:13
> @jeffreymonaco upstream problems are always unfortunate/frustrating. I will re-label this issue for a task to add a note to the docs about this platform-specific issue.

Thanks. I certainly did not mean to convey frustration ... mostly just inquisitive. And to have a note at the ready if any of a handful of users for the specific software ever encounter the behavior.

Cheers

**Comment by bryevdv** [comment] 2021-02-26 22:43
>  I certainly did not mean to convey frustration

Well, they are definitely frustrating *to me* :) Thanks for your patience with this, I hope the issue in Chrome is resolved in a future Chrome release.

**Closed** 2021-02-28 03:22 UTC
Labels: reso: completed, tag: component: docs, type: task
