### ISSUE TITLE
[BUG] DataRange.renderers.append fails silently

### ISSUE THREAD

**Issue by florentbr** [bokeh/bokeh#11852] opened 2021-12-02 12:04 UTC
### Software versions

Python version : 3.9.7
IPython version : 7.28.0
Tornado version : 6.1
Bokeh version : 2.4.0

### Expected behavior

Calling `DataRange.renderers.append(item)` should append an item to the list.

### Observed behavior

The method is executed without error but the item is not present in the list.

### Example code

```Python
from bokeh.plotting import figure, show

p = figure(width=700, height=400)
pl = p.line([0, 1], [5, 5])

p.y_range.renderers.append(pl)
assert len(p.y_range.renderers) > 0, "Zero length"
```

**Comment by mattpap** [comment] 2021-12-02 14:35
The problem is again (see e.g. #11830) with composite property types, which don't propagate certain method calls. Removing `Either(...)` from `DataRange.renderers` and leaving only `List(GlyphRenderer)` "resolves" this issue.

**Comment by xaptronic** [comment] 2021-12-31 06:20
A way around this issue:
```
from bokeh.plotting import figure, show

p = figure(width=700, height=400)
pl = p.line([0, 1], [5, 5])

if len(p.y_ranges.renderers):
  p.y_ranges.renderers.append(pl)
else:
  p.y_ranges.renderers = [pl]
```

**Comment by mattpap** [comment] 2023-03-05 11:07
This seems to be fixed now. Regression tests are needed.

**Closed** 2023-06-07 17:00 UTC
Labels: type: bug
