### ISSUE TITLE
TapTool doesn't work properly for glyphs with shared data source in same figure (bokehJS)

### ISSUE THREAD

**Issue by jaredsagendorf** [bokeh/bokeh#5038] opened 2016-08-25 23:16 UTC
I'm using the Bokeh.Plotting API of bokehJS and I ran into what seems like a bug. I have several glyphs that are in the same figure which share a single ColumnDataSource between them (my motivation for this would require some explanation, but suffice it to say this makes a lot of sense for my application).

I want these glyphs to be linked - i.e. selecting one glyph from the figure would automatically select all the others with the same index which share the same DataSource.

This works, but only when selecting from the set of glyphs which were **last** added to the figure. The others are unselectable. 

I made a JSFiddle which shows a MWE in 0.12.1. 

https://jsfiddle.net/j7jojf1z/

The blue and red circles share a ColumnDataSource. Clicking on the blue circles selects the correct red circle, but the red circles can't be clicked on their own.

I'm assuming this is _not_ the intended behavior, correct? Is there a quick fix if so?

Thanks.

**Comment by birdsarah** [comment] 2016-08-26 09:12
@jaredsagendorf I took a quick look and I'm not sure - hopefully @mattpap has some suggestions.

**Comment by bryevdv** [comment] 2016-08-26 13:50
I think this might be a dupe of https://github.com/bokeh/bokeh/issues/2136 which is a general problem not just with the JS API

**Closed** 2016-08-26 14:51 UTC
Labels: reso: duplicate, type: discussion
