### ISSUE TITLE
[BUG] Message containing ModelChangeEvents for all properties sent back to server on initialization

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#11803] opened 2021-11-15 19:08 UTC
Starting in Bokeh 2.4.0 the frontend has started sending back ModelChangeEvents to the server containing basically all the changed model properties after initialization resulting in a huge dump of data being sent back to the server. In the worst case this message is larger than the allowed websocket size, breaking the application entirely. This can easily be reproduced by creating a plot with a decent amount of data and serving it, e.g.:

```python
import numpy as np

from bokeh.io import curdoc
from bokeh.plotting import figure

xs = np.linspace(0, np.pi, 20000)
sin = np.sin(xs*2)
cos = np.cos(xs*4)

p = figure()

p.line(xs, sin)
p.line(xs, cos)

curdoc().add_root(p)
```

In this example you can watch the websocket and see this huge event being sent back:

<img width="551" alt="Screen Shot 2021-11-15 at 8 02 29 PM" src="https://user-images.githubusercontent.com/1550771/141839115-28f7a51d-31e3-4673-9d3a-becaba2aa0de.png">

if you instead use Bokeh 2.3.x you see only a very small message being sent:

<img width="286" alt="Screen Shot 2021-11-15 at 8 03 16 PM" src="https://user-images.githubusercontent.com/1550771/141839213-fa441107-d6bb-41e5-b9a3-649ba074a5f7.png">

This seems like a **huge** regression causing a whole lot of unnecessary network traffic.

**Comment by bryevdv** [comment] 2021-11-15 19:19
@philippjfr will you be able to perform a bisection?

**Comment by philippjfr** [comment] 2021-11-15 19:21
Will do, absolutely first thing tomorrow. This is very high priority for us so I'll do my best to get this fixed asap with @mattpap's help.

**Comment by bryevdv** [comment] 2021-11-15 19:23
I will also try to look some tonight

**Comment by mattpap** [comment] 2021-11-15 20:36
The regression happened in PR #11194. The problem is that there are two equivalent, but not directly comparable JSON-like representations of ndarrays, one eager (with raw base64 encoded data) and one lazy (with a function producing base64 encoded data). We need the later to optimize performance where we need to do partial serializations, but avoid serializing data until it's really unavoidable. However, `Document._compute_patch_since_json()` naively compares raw JSON-like representations, in an attempt to detect changes, which makes `data` attribute always appear to change. I think that for 2.4.2 I will just assume that data doesn't change during initialization, which it should not (if it does we have bigger issues to deal with), and in 3.0 I will replace the algorithm with something more robust (e.g. take advantage of the properties system and compare  snapshots of properties' dirty state before and after initialization).

**Comment by bryevdv** [comment] 2021-11-15 20:52
Thanks for the quick diagnosis @mattpap if you can prioritize a fix for this I can resolve any outstanding backports and we can try to have a 2.4.2 in a few days or end of week at least.

**Closed** 2021-11-25 10:29 UTC
Labels: type: bug, tag: regression, tag: component: bokehjs, tag: component: server
