### ISSUE TITLE
Many charts raise warnings due to ColumnDataSource column lengths

### ISSUE THREAD

**Issue by fpliger** [bokeh/bokeh#2817] opened 2015-09-05 13:08 UTC
Many charts raise the following warning:

```
ERROR:/bokeh/bokeh/validation/check.pyc:E-1000 (COLUMN_LENGTHS): ColumnDataSource column lengths are not all the same: ColumnDataSource, ViewModel:ColumnDataSource, ref _id: 3dd80fc0-767a-41a6-8eaa-91c760f87faf
```

and will break in `0.10`

**Comment by bryevdv** [comment] 2015-12-21 21:55
dupe of #2491

**Closed by bryevdv** 2015-12-21 21:55 UTC
Labels: tag: charts, type: bug
