### ISSUE TITLE
Export PNG in notebook saves to environment location if no filename passed

### ISSUE THREAD

**Issue by hsparra** [bokeh/bokeh#6815] opened 2017-08-25 16:37 UTC
Running the new `export_png` function in a notebook results in the resultant PNG being saved to the conda environment location instead of the current directory if no output filename is passed.

ex.
```

from bokeh.plotting import figure, output_notebook  
from bokeh.io import export_png  
p = figure(plot_width=400, plot_height=400)  
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=20, color="navy", alpha=0.5)  
export_png(p)  
 
```

saves the file to `/anaconda/envs/bokeh_test/lib/python3.6/runpy.png` or wherever the user has their anaconda installation.

**Comment by hsparra** [comment] 2017-08-25 16:57
Should the output filename just be a required parameter?

**Comment by mattpap** [comment] 2017-08-28 20:55
This is a duplicate of #6560.

**Closed by mattpap** 2017-08-28 20:55 UTC
Labels: reso: duplicate
