### ISSUE TITLE
[BUG] ImageURL selection_glyph raises "TypeError: this.retries is undefined"

### ISSUE THREAD

**Issue by ghalter** [bokeh/bokeh#8889] opened 2019-05-03 08:25 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Windows 10
python 3.6
bokeh 1.1.0
firefox 66.0.3 (64-Bit)

#### Description of expected behavior and the observed behavior

Essentially I'm trying to hide all ImageURL glyphs, which are not selected. 
To do so, I'm using the the _global_alpha_ attribute of the ImageURL glyph, 
however, as soon as something gets selected in the data source, all images disappear, 
and I get a "TypeError: this.retries is undefined" in my browsers console. 

#### Complete, minimal, self-contained example code that reproduces the issue

```
from bokeh.plotting import figure, show
from bokeh.models.sources import ColumnDataSource
from bokeh.models import ImageURL


sample_url = "https://upload.wikimedia.org/wikipedia/commons/0/06/CIELAB_color_space_top_view.png"

ds = ColumnDataSource(data=dict(
    xs = [0,5,10],
    ys = [0,5,10],
    urls = [sample_url,sample_url,sample_url],
    hs = [50, 50, 50],
    ws = [50, 50, 50]
))

p = figure(title="Sample", tools=["tap"])


# Circle to select since images can't be selected
p.circle(x='xs', y='ys', size=20, source=ds)

renderer = p.image_url(url='urls', x = 'xs', y = 'ys', h='hs', w = 'ws', w_units="screen", h_units="screen", source=ds)

# We want to hide the non-selected image glyphs
selected_image = ImageURL(url='urls', x = 'xs', y = 'ys', h='hs', w = 'ws', global_alpha=1.0, w_units="screen", h_units="screen")
nonselected_image = ImageURL(url='urls', x = 'xs', y = 'ys', h='hs', w = 'ws', global_alpha=0.0, w_units="screen", h_units="screen")


renderer.selection_glyph = selected_image
renderer.nonselection_glyph = nonselected_image

show(p)

```

#### Stack traceback and/or browser JavaScript console output
TypeError: this.retries is undefined

**Comment by bryevdv** [comment] 2019-05-03 21:48
A quick fix for this is to add a check on `this.model.global_alpha` here 

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/glyphs/image_url.ts#L146

That immediately bails and returns if it is zero. But that is *only* a fix for the alpha=0 case. Fixing this more generally will take more effort due to the unavoidable async loading of images. 

@ghalter would you like to submit a small PR for the quick fix?

**Comment by ghalter** [comment] 2019-05-04 14:20
@bryevdv First of all thanks a lot for the very good documentation on how to setup the dev-environment, it worked like a breeze even on windows! 

Sure I can do such a pull request, however, I just tested your proposed fix and it doesn't seem to work, 
because the same error occures in the selected glyph (beeing the only one without a `this.model.global_alpha` == 0). 

Is the following test even necessary?
https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/glyphs/image_url.ts#161
```    
if (this.retries[i] == -1)
        continue
```

Because as it seems, the subsequent clause testing if the image is null will 
return false anyway if the image has not be retrieved. Or have I missed something?

If I remove the above clause, following code works as expected:

``` 
from bokeh.plotting import figure, show, output_file
from bokeh.models.sources import ColumnDataSource
from bokeh.models import ImageURL
from bokeh.plotting import figure
# from bokeh.resources import INLINE

import os
os.environ['BOKEH_DEV'] = "True"
os.environ['BOKEH_BROWSER'] = "windows-default"

plot = figure()
plot.circle([1,2], [3,4])

output_file("test.html")#, INLINE)

sample_url = "https://upload.wikimedia.org/wikipedia/commons/0/06/CIELAB_color_space_top_view.png"

# Creating a ds with one the last image being non-existent.
ds = ColumnDataSource(data=dict(
    xs = [0,5,10, 50],
    ys = [0,5,10, 50],
    urls = [sample_url,sample_url,sample_url, "non_existent.jpg"],
    hs = [50, 50, 50, 50],
    ws = [50, 50, 50, 50]
))

p = figure(title="Sample", tools=["tap"])


# Circle to select since images can't be selected
p.circle(x='xs', y='ys', size=20, source=ds)

renderer = p.image_url(url='urls', x = 'xs', y = 'ys', h='hs', w = 'ws', w_units="screen", h_units="screen", source=ds)

# We want to hide the non-selected image glyphs
selected_image = ImageURL(global_alpha=1.0, w_units="screen", h_units="screen")
nonselected_image = ImageURL(global_alpha=0.2, w_units="screen", h_units="screen")

renderer.selection_glyph = selected_image
renderer.nonselection_glyph = nonselected_image

show(p)

```

**Comment by bryevdv** [comment] 2019-05-04 16:51
@ghalter thanks for diving in to things! I am glad to hear the dev docs are in a  good state now

> Because as it seems, the subsequent clause testing if the image is null will
return false anyway if the image has not be retrieved. Or have I missed something?

That test is to limit the number of retries to `retry_attempts` otherwise if the image is not available it will keep trying forever. So, how about trying this then: move this assignment of `this.retries` here:

https://github.com/bokeh/bokeh/blob/master/bokehjs/src/lib/models/glyphs/image_url.ts#L55

from the `_set_data` method (which is not  called on the subordinate glyphs, the root cause of this issue) to the `initialize` method?

**Comment by bryevdv** [comment] 2019-05-04 16:55
Him, actually that probably won't work, for a few reasons... I'll have to think on it some this week, or if you find a solution that maintains `retry_attempts` let me know!

**Comment by bryevdv** [comment] 2019-05-04 17:32
@ghalter sorry, actually I think your suggestion might be fine after all, since the check to prevent loads is elsewhere. Please submit a PR when you can!

**Comment by ghalter** [comment] 2019-05-04 17:37
@bryevdv No Problem, I will do so soon!

**Closed** 2019-05-04 23:38 UTC
Labels: tag: component: bokehjs, type: bug
