### ISSUE TITLE
Import Issues with Bokeh Attributes

### ISSUE THREAD

**Issue by loganmackenzie** [bokeh/bokeh#7877] opened 2018-05-09 14:27 UTC
I am using Bokeh 0.12.15 with Python 3.6 on Windows 10 and I am having issues where if I import bokeh, I can use some of the bokeh methods, but some of them give me an attribute error. 

Example:

```py
import bokeh
# from bokeh import plotting
# from bokeh import embed

source = bokeh.plotting.ColumnDataSource({'x': [1, 2, 3, 4], 'y': [10, 4, 8, 2]})

p = bokeh.plotting.figure(title="example", x_axis_label='x', y_axis_label='y')
p.line('x', 'y', line_width=2, source=source)

html = bokeh.embed.file_html(p, resources=bokeh.resources.INLINE)

with open('example.html', 'w') as output:
    output.write(html)
```
Running this code gives me: `AttributeError: module 'bokeh' has no attribute 'plotting'`. And if I uncomment the line `from bokeh import plotting` then the plotting parts work, but I get `AttributeError: module 'bokeh' has no attribute 'embed'`. However, if I uncomment `from bokeh import embed` everything works just fine.

I do not know if this is my just not importing things properly, but `import bokeh` seems like it should be a clean way to import everything needed.

**Comment by mattpap** [comment] 2018-05-09 14:49
This is by design. bokeh is a large library, with many, often heavy, dependencies. If everything was imported in `bokeh` module, then its import time would be unbearable and would require installation of dependencies that you may actually not need (e.g. Tornado when not using bokeh's server). Thus you need to import major subsystems individually.

**Comment by bryevdv** [comment] 2018-05-09 14:52
I guess we could use the class module hack here to defer imports but I am not especially inclined to do so.

**Comment by mattpap** [comment] 2018-05-09 14:56
Also, `bokeh.embed` is not the most high-level API that one could use for the job, so it's hidden behind an additional import. If you don't have a good reason for using `file_html()`, you should use `save()`, which is available together with `bokeh.plotting`.

**Comment by loganmackenzie** [comment] 2018-05-09 15:17
Okay, I mostly wanted to know why I have to import the modules. Thanks for the explanation. Just one more question: Is there a reason for me to use `import bokeh` then? Instead should I just be using `from bokeh import plotting` and `from bokeh import embed` and other major subsystems?Or is there a different way that I should be importing bokeh or its major subsystems?

**Comment by bryevdv** [comment] 2018-05-09 15:35
The only thing I ever personally import `bokeh` for is to look at `bokeh.__version__`.  I guess `sampledata` and `license` could be accessed from there as well. 

For anything else is really a matter of style, there is no "correct" answer. I prefer this kind of style:

```
from bokeh.io import curdoc
from bokeh.models import ColumnDataSource, FactorRange
from bokeh.plotting import figure
from bokeh.layouts import column
```

i.e. I *much* prefer trade slightly more complicated imports, for cleaner/smaller code throughout module. But I gather some people seem to hate this style. I've seen people do things like this:

```
import bokeh.plotting as bkp
``` 
which is not something I would ever do, but if you prefer prefixes everywhere, it's certainly not unreasonable. 

I'm going to go ahead and close this, just because I don't think any specific actions will arise. It's perfectly reasonable topic of discussion, we could pick up on the mailing list: 

https://groups.google.com/a/continuum.io/forum/#!forum/bokeh

**Closed by bryevdv** 2018-05-09 15:35 UTC
Labels: type: discussion
