### ISSUE TITLE
The notebook file size increases when run the same cell multiple times.

### ISSUE THREAD

**Issue by ruoyu0088** [bokeh/bokeh#4231] opened 2016-04-26 02:10 UTC
Here is an example:

```
from bokeh.io import show, output_notebook, curdoc
from bokeh.plotting import figure
```

```
output_notebook()
```

run the following cell multiple times:

```
fig = figure()
fig.line([1, 2, 3], [4, 5, 6])
show(fig) 
```

Then check the document:

```
curdoc().roots
```

the output is:

```
[<bokeh.plotting.figure.Figure at 0xaf9e278>,
 <bokeh.plotting.figure.Figure at 0xad774a8>,
 <bokeh.plotting.figure.Figure at 0xaf9ea58>,
 <bokeh.plotting.figure.Figure at 0xafa3cf8>,
 <bokeh.plotting.figure.Figure at 0xafa35c0>]
```

The document accumulates all the created figures. If there are multiple figures in the notebook, the last figure output will contain all the figures in the `curdoc().roots`.

It slows down the output, and increases the notebook filesize.

Currently, I use `curdoc().clear()` before every new figure.

**Comment by bryevdv** [comment] 2016-04-27 22:03
I believe this is a dupe of #3671 (so closing) we are currently working on cleaning up various parts the API that have to deal with this, but it is a large effort that is still ongoing.

**Closed by bryevdv** 2016-04-27 22:03 UTC
