### ISSUE TITLE
[BUG] Wedge renderer has no impact on y-axis range

### ISSUE THREAD

**Issue by mosc9575** [bokeh/bokeh#11081] opened 2021-03-18 13:01 UTC
#### software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.3
Python 3.6

#### Description of expected behavior and the observed behavior
I created a minimal example to draw a cake plot. The x-axis seems to be connected to the wedge renderers but the y-axis is not.
In the picture below the radius is 1 but there is a gap between the horizontal lines of the grid for y eqauls 0 and 2 which both should be a tanget of the cirle.
![cake](https://user-images.githubusercontent.com/68053396/111628223-45ed1c00-87f0-11eb-9938-d1faeef6a355.PNG)

#### Complete, minimal, self-contained example code that reproduces the issue
```
df = pd.DataFrame({"Value":{"0":16.67,"1":33.33,"2":50.0},
                   "Start":{"0":0.0,"1":1.05,"2":3.14},                   
                   "End":{"0":1.05,"1":3.14,"2":6.28},
                   "Color":{"0":"#00497f","1":"#f39200","2":"#2ca02c"}}
                 )
plot = figure(plot_width=300, plot_height=300)
#plot.x_range = Range1d(-10,10)
#plot.y_range = Range1d(-10,10)

for i, row in df.iterrows():
    plot.wedge(x=[1], 
               y=[1], 
               radius=1, 
               start_angle=row['Start'],
               end_angle=row['End'], 
               color=row['Color']
              )
show(plot)
```
#### Screenshots
If I uncomment `plot.x_range = Range1d(-10,10)` the size of the cirlce changes, as expected. If I do the same with the line `plot.y_range = Range1d(-10,10)` there is no effect except that the ticks on the y axis change.

|set x_range|set y_range|
|--|--|
|![x_range](https://user-images.githubusercontent.com/68053396/111629713-e132c100-87f1-11eb-9ca0-09ade1cae76c.png)|![y_range](https://user-images.githubusercontent.com/68053396/111629793-f6a7eb00-87f1-11eb-9000-0aacdfe5f145.png)|

**Comment by bryevdv** [comment] 2021-03-18 16:11
dupe of #517 

@mosc9575 for any "circle-related" glyph with a radius in data-space coordinates, you will most likely want to set `match_aspect=True` on the `figure. Note that `match_aspect` only functions when default auto-ranging is used (i.e. if you *don't* set the ranges manually)

**Closed by bryevdv** 2021-03-18 16:11 UTC
Labels: TRIAGE

**Comment by bryevdv** [comment] 2021-03-18 16:25
That said, wedges don't yet participate in auto-ranging, so the best workaround is to add an invisible rect glyph with the same diameter to "kick" the auto-ranges:

```
plot = figure(plot_width=300, plot_height=300, match_aspect=True)

# WAR for wedges not yet auto-ranging
plot.rect(x=1, y=1, width=2, height=2, alpha=0)
```

<img width="341" alt="Screen Shot 2021-03-18 at 9 23 33 AM" src="https://user-images.githubusercontent.com/1078448/111660764-a158e300-87cb-11eb-962c-08ad0d4667bd.png">

The pie above correctly goes from (0,2) on both the x- and y- axes. 

Although I just realized that perhaps you want the circle to physically touch the axes too. If that's the case, you will need to account for the space that the axes and toolbar take up, in order to get a perfectly square central plot area. There's various ways to do that, but that is a support question, so should go on the [Discourse site](https://discourse.bokeh.org), not here.

**Comment by mosc9575** [comment] 2021-03-19 07:27
@bryevdv Thank your for your time, the very helpful work-around and the kind explanation  This solves my problem.
