### ISSUE TITLE
Implement_array_function method already has a docstring

### ISSUE THREAD

**Issue by taiwotman** [bokeh/bokeh#9539] opened 2019-12-23 17:17 UTC
After` pip install bokeh`, and using the _**import**_ statement:  

`from bokeh.plotting  import figure`

I got the _runtime_ error:

`Implement_array_function method already has a docstring`

Same error would occur if bokeh is downloaded while using the _**import**_ statement: 

`from .bokeh.bokeh.plotting  import figure`

**Comment by bryevdv** [comment] 2019-12-23 17:47
@taiwotman There is nothing called `Implement_array_function` anywhere at all in the Bokeh repo:

https://github.com/bokeh/bokeh/search?q=Implement_array_function&unscoped_q=Implement_array_function

I also can't reproduce any issue with a pip install into a clean conda env. There are ~800k pip installs of Bokeh each month with no other problems reported with basic usage. I think the most likely explanation is some problem on your local system. Do you have a "bokeh.py" module of your own any any chance?

**Comment by bryevdv** [comment] 2019-12-23 17:50
@taiwotman actually it appears this is actually an issue with Numpy under some circumstances:

https://github.com/numpy/numpy/issues/14384
https://github.com/numpy/numpy/issues/14012

Accordingly, I am closing this here, and marking as `upstream`

**Closed by bryevdv** 2019-12-23 17:50 UTC

**Comment by bryevdv** [comment] 2019-12-23 19:11
@taiwotman I would suggest it would be helpful if you could comment on https://github.com/numpy/numpy/issues/14384 with more details about how you ran in to this. Everything in that issue seems to indicate problems with numpy used in certain situations where the module is reloaded. If you can confirm or contradict that I am sure it would help the numpy devs

**Comment by taiwotman** [comment] 2019-12-23 19:27
Thanks. Followed your guide by downgrading `numpy` to `1.15.4` and the error disappeared...but then got a new one:  `error typing-extensions module not found`. There after, pip install the module and voila all went well with the example  [Components ](https://docs.bokeh.org/en/latest/docs/user_guide/embed.html#components)

**Comment by taiwotman** [comment] 2019-12-23 19:29
closes #9539

**Comment by bryevdv** [comment] 2019-12-23 19:36
@taiwotman I'm not sure about the typing extensions message. We are adding `typing_extensions` as a new requirement starting with version 2.0 but you would only need it got 2.0 pre-releases, not any any previous full release. Perhaps some other package in your environment was trying to pull it in? In any case thanks for the update and I am glad it's now working!
