### ISSUE TITLE
Upgrade to noUiSlider 11 to avoid Chrome 51 bug

### ISSUE THREAD

**Issue by jburgy** [bokeh/bokeh#7433] opened 2018-01-18 21:27 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)

Bokeh 0.12.9 to 0.12.13
Windows 7
Chrome 51

#### Description of expected behavior and the observed behavior

Slider handles are dragged in unison after their first selection. 

#### Complete, minimal, self-contained example code that reproduces the issue

Issue observed with [slider.py example](https://bokeh.pydata.org/en/latest/docs/gallery/slider.html)

Drag "Amplitude" handle then drag "Frequency" handle and observe that "Amplitude" moves in sync.

**Comment by bryevdv** [comment] 2018-01-18 22:01
Here is a reference to the nouislider issue: https://github.com/leongersen/noUiSlider/issues/805

**Comment by bryevdv** [comment] 2018-01-18 22:06
Quick check, unfortunately just merely updating the version is not sufficient:

<img width="337" alt="screen shot 2018-01-18 at 16 05 15" src="https://user-images.githubusercontent.com/1078448/35123839-78030b98-fc69-11e7-948c-f371d9d31998.png">

Dragging "works" but the slider does not actually move. 

So we'll have to investigate what updates we might need to make on our end to rev the version

**Comment by mattpap** [comment] 2018-01-18 22:10
They changed the structure of the npm package. There are no less files anymore.

**Comment by bryevdv** [comment] 2018-01-19 19:00
Ah I see, well I can remove the import in`bokeh-widgets.less` but what's the correct way to include the built css that nouislider ships now?

**Comment by bryevdv** [comment] 2018-01-19 19:12
I tried this:
```
diff --git a/bokehjs/src/less/widgets/nouislider.less b/bokehjs/src/less/widgets/nouislider.less
index 189126cb1..41b3d511d 100644
--- a/bokehjs/src/less/widgets/nouislider.less
+++ b/bokehjs/src/less/widgets/nouislider.less
@@ -1,6 +1,6 @@
 @noUi-css-prefix: bk-noUi;
-@nouislider: "../../../node_modules/nouislider/src";
-@import "@{nouislider}/nouislider.base.less";
+@nouislider: "../../../node_modules/nouislider/distribute";
+@import (inline) "@{nouislider}/nouislider.css";

 .@{noUi-css-prefix}-handle {
   cursor: grab;
``` 
which seems to include the CSS in Bokeh's CSS, but it does not render correctly:

<img width="525" alt="screen shot 2018-01-19 at 13 12 16" src="https://user-images.githubusercontent.com/1078448/35167255-655075ec-fd1a-11e7-8b6a-d168af7ceb2d.png">

**Comment by bryevdv** [comment] 2018-01-19 19:16
As an aside it seems like the build should error in the other cases that result in the CSS not being included (i.e. without `(inline)`)

**Comment by mattpap** [comment] 2018-01-19 19:16
@bryevdv, if you go this path, you also have to remove prefixing. That's the reason it doesn't work for you.

**Comment by bryevdv** [comment] 2018-01-19 19:19
Yes I just realized. Do you have another proposal?

**Comment by mattpap** [comment] 2018-01-19 19:23
There are three options:

1. They restore less files in the package.
2. We switch to github as the dependency source (version based on a tag).
3. We drop prefixing.

I think we should drop prefixing and admit defeat (and the fact that the tech is simply not there).

**Comment by bryevdv** [comment] 2018-01-19 19:25
I'm fine with dropping prefixing, some people might even prefer that the sliders be targetable with standard selectors. That said. dropping prefixing does not seem to work either:
```
diff --git a/bokehjs/src/coffee/models/widgets/abstract_slider.ts b/bokehjs/src/coffee/models/widgets/abstract_slider.ts
index a7575cade..6fcf0882d 100644
--- a/bokehjs/src/coffee/models/widgets/abstract_slider.ts
+++ b/bokehjs/src/coffee/models/widgets/abstract_slider.ts
@@ -51,7 +51,7 @@ export abstract class AbstractSliderView extends WidgetView {
       }
     }

-    const prefix = 'bk-noUi-'
+    const prefix = 'noUi-'

     const {start, end, value, step} = this._calc_to()

diff --git a/bokehjs/src/less/widgets/nouislider.less b/bokehjs/src/less/widgets/nouislider.less
index 189126cb1..886e27f8b 100644
--- a/bokehjs/src/less/widgets/nouislider.less
+++ b/bokehjs/src/less/widgets/nouislider.less
@@ -1,6 +1,6 @@
-@noUi-css-prefix: bk-noUi;
-@nouislider: "../../../node_modules/nouislider/src";
-@import "@{nouislider}/nouislider.base.less";
+@noUi-css-prefix: noUi;
+@nouislider: "../../../node_modules/nouislider/distribute";
+@import (inline) "@{nouislider}/nouislider.css";

 .@{noUi-css-prefix}-handle {
   cursor: grab;
```
<img width="782" alt="screen shot 2018-01-19 at 13 23 36" src="https://user-images.githubusercontent.com/1078448/35167735-2ae056aa-fd1c-11e7-9e79-4b86315beb58.png">

**Comment by mattpap** [comment] 2018-01-19 19:26
> As an aside it seems like the build should error in the other cases that result in the CSS not being included 

`@import "X.less"` shows a warning. Given this is a gulp plugin, I doubt there is anything we can do about making it more verbose than that. `@import "X.css"` is a CSS feature and is left as-is, without any processing. If you include any options, like `inline`, then it can give you some feedback.

**Comment by mattpap** [comment] 2018-01-19 19:28
> hat said. dropping prefixing does not seem to work either:

This will need more investigation. We customize the slider a bit, so it's not unexpected.

**Comment by bryevdv** [comment] 2018-01-19 19:29
`@import "X.css"` does not work though, the resulting `bokeh.css` does not include the noui CSS.

**Comment by bryevdv** [comment] 2018-01-19 19:30
> This will need more investigation. We customize the slider a bit, so it's not unexpected.

For sure, I will move on to other things for now. For grins I tried commenting out all of our customizations, and it still does not render correctly.

**Comment by mattpap** [comment] 2018-01-19 19:31
> (...) does not include the noui CSS.

As said before, it's a CSS feature and not LESS, so one shouldn't expect this to be included anywhere. This import is resolved by a browser at runtime. If you want any processing by LESS, you need to use appropriate import options (like `inline`).

**Comment by bryevdv** [comment] 2018-01-19 19:54
Actually, last observation. This works:
```@import "widgets/nouislider.less";
.bk-root {
  @import "widgets/bootstrap.less";
  @import "widgets/pikaday.less";
  @import "widgets/widgets.less";
}
```
I'd guess that this is not a good solution, though?

**Comment by bryevdv** [comment] 2018-01-19 19:57
nm I misunderstood `@import (less)` that actually fixes it

**Comment by bryevdv** [comment] 2018-01-19 23:23
@jburgy a new dev build is available with the updated version of *noUiSlider* bundled. Can you install it and try the `sliders.py` example locally to confirm whether the issue is resolved? Instructions for installing dev builds are here:

https://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

**Comment by bryevdv** [comment] 2018-01-19 23:39
@jburgy actually sorry it's much simpler, you can just go to the dev docs gallery online:

https://bokeh.pydata.org/en/dev/docs/gallery/slider.html

**Comment by bryevdv** [comment] 2018-01-20 00:09
Well, I fired up a VM, and managed to find a download link for Chrome 51 so that I could test. Unfortunately it does not seem to solve the issue. I did verify that noUiSlider version `11.0` is what got built into the BokehJS sources. Looking closer at the linked issue I see is still listed as "under development" so I don't think there is anything we can do until there is an upstream fix

**Comment by jburgy** [comment] 2018-01-22 15:30
I concur but wanted to thank you guys for the hard work.

**Comment by bryevdv** [comment] 2018-01-23 14:49
I'm going to close this as `upstream` unfortunately there's not really anything we can do until/unless noiuslider makes a fix

**Closed by bryevdv** 2018-01-23 14:49 UTC
Labels: reso: upstream, tag: component: bokehjs, type: task
