### ISSUE TITLE
'Bar and Categorical Data Plots' Tutorial `bokeh.sample.data` loading error.

### ISSUE THREAD

**Issue by biggstd** [bokeh/bokeh#8799] opened 2019-03-28 19:52 UTC
#### Software

I encountered this in tutorial 07, [Bar and Categorical Data Plots](https://hub.mybinder.org/user/bokeh-bokeh-notebooks-r5ok8y5r/notebooks/tutorial/07%20-%20Bar%20and%20Categorical%20Data%20Plots.ipynb). I see the error on my local machine and on 'binder'.

The versions reported by 'binder':  
```
IPython - 7.1.1
Pandas - 0.24.2
Bokeh - 1.0.4
```

#### Description

The sample data, `bokeh.sampledata.commits` fails to load, it throws a `TypeError`.

#### Reproducing

```python
from bokeh.sampledata.commits import data
data.head()
```

**In binder**:  
Launch the binder Bar and Categorical Data Plots and run the cells. The error occurs in the [Categorical Scatterplots](https://hub.mybinder.org/user/bokeh-bokeh-notebooks-r5ok8y5r/notebooks/tutorial/07%20-%20Bar%20and%20Categorical%20Data%20Plots.ipynb#Catgorical-Scatterplots) section.

#### Stack / Error output

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-18-7e0b67b4ad1a> in <module>
----> 1 from bokeh.sampledata.commits import data
      2 
      3 data.head()

~/anaconda3/lib/python3.7/site-packages/bokeh/sampledata/commits.py in <module>
     61 #-----------------------------------------------------------------------------
     62 
---> 63 data = _read_data()

~/anaconda3/lib/python3.7/site-packages/bokeh/sampledata/commits.py in _read_data()
     53     '''
     54     data = package_csv('commits', 'commits.txt.gz', parse_dates=True, header=None, names=['day', 'datetime'], index_col='datetime')
---> 55     data = data.tz_localize('GMT').tz_convert('US/Central')
     56     data['time'] = data.index.time
     57     return data

~/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py in tz_localize(self, tz, axis, level, copy, ambiguous, nonexistent)
   9395             if level not in (None, 0, ax.name):
   9396                 raise ValueError("The level {0} is not valid".format(level))
-> 9397             ax = _tz_localize(ax, tz, ambiguous, nonexistent)
   9398 
   9399         result = self._constructor(self._data, copy=copy)

~/anaconda3/lib/python3.7/site-packages/pandas/core/generic.py in _tz_localize(ax, tz, ambiguous, nonexistent)
   9375                     ax_name = self._get_axis_name(axis)
   9376                     raise TypeError('%s is not a valid DatetimeIndex or '
-> 9377                                     'PeriodIndex' % ax_name)
   9378                 else:
   9379                     ax = DatetimeIndex([], tz=tz)

TypeError: index is not a valid DatetimeIndex or PeriodIndex
```

**Comment by mattpap** [comment] 2019-03-29 08:51
This is a duplicate of issue #8585. The fix will be available in bokeh 1.1 (hopefully next week; one can use dev releases in the mean time). Alternatively you can downgrade pandas to a version below 0.24.

**Closed by mattpap** 2019-03-29 08:51 UTC
Labels: reso: duplicate, type: discussion
