### ISSUE TITLE
Warnings not available for `from bokeh.models import Callback`

### ISSUE THREAD

**Issue by jakirkham** [bokeh/bokeh#2791] opened 2015-08-31 21:55 UTC
So, I ran into an issue related to this change ( https://github.com/bokeh/bokeh/issues/2634 ) today. However, I am very happy to see that you have explained your rational and added this here. It was easy enough to fix the issue from the information there ( https://github.com/bokeh/bokeh/issues/2634 ). Also, I am glad to see you went to the effort to add a warning.

That all being said, in iPython I think the warning is being swallowed. Instead, I get a rather nasty exception. Here is a reproducer of the problem I am seeing ( https://gist.github.com/jakirkham/dfa04a13d5aa694c504b ).

This probably should go in a new issue, but I am putting it here for now.

**Comment by birdsarah** [comment] 2015-09-05 03:56
@jakirkham I hope you don't mind me changing the title here, this is not an ipython issue.

**Comment by birdsarah** [comment] 2015-09-05 17:34
Hi @jakirkham, I'm really sorry for the inconvenience caused by this, and I'll definitely work to make sure I don't introduce this kind of inconvenience again.

However, the next release of Bokeh is going to be 0.10, and as per the warnings and #2815, we're going to be removing the deprecations. So, any fix that would be made against this PR wouldn't make it into a release of Bokeh.

As a result I'm going to mark this as `wontfix` and, once again, please accept my apologies for any inconvenience caused.

**Closed** 2015-09-05 17:35 UTC
Labels: reso: wontfix, type: bug
