### ISSUE TITLE
[BUG] Incorrect version schema for development versions on the conda channel `bokeh/label/dev`

### ISSUE THREAD

**Issue by maximlt** [bokeh/bokeh#12927] opened 2023-03-08 10:31 UTC
### Software versions

NA

### Expected behavior

The `dev` versions of Bokeh pushed to the `bokeh/label/dev` since Bokeh 3 include a dot (`.`) after the patch number, but not the `rc` versions`.

    conda search -c bokeh/label/dev bokeh

```
...
bokeh                       3.1.0rc1            py_0  bokeh/label/dev
bokeh                       3.1.0rc2            py_0  bokeh/label/dev
bokeh                     3.1.0.dev1            py_0  bokeh/label/dev
bokeh                     3.1.0.dev2            py_0  bokeh/label/dev
bokeh                     3.1.0.dev3            py_0  bokeh/label/dev
bokeh                     3.1.0.dev4            py_0  bokeh/label/dev
bokeh                     3.1.0.dev5            py_0  bokeh/label/dev
```

Because of that installing a development version of Bokeh from this channel currently pulls a `devX` one instead of an `rcX` one.

### Observed behavior

`rc` should take precedence over `dev` versions.

### Example code

```Python
conda create -n foo -c bokeh/label/dev python=3.9 bokeh
```

**Comment by philippjfr** [comment] 2023-03-08 11:30
This is intentional and what [PEP440](https://peps.python.org/pep-0440/) prescribes:

`[N!]N(.N)*[{a|b|rc}N][.postN][.devN]`

**Comment by maximlt** [comment] 2023-03-08 11:52
Oh indeed. So that's a bug in conda? :(

**Comment by mattpap** [comment] 2023-03-08 13:22
Everytime I look at pre-release version numbers, I feel like there's something wrong there, but it's just that versioning scheme. I presume I can close this?

**Closed as not planned** 2023-03-08 13:29 UTC
Labels: reso: upstream, type: discussion

**Comment by bryevdv** [comment] 2023-03-08 14:47
I noticed that the RC seemed to have lower precedence the other day. I'm not sure what the issue is, but I agree with @philippjfr that we are currently doing what PEP440 specifies. It would be good to confirm that pip finds the RC as expected, and if so, open a bug report on the conda tracker.

**Comment by mattpap** [comment] 2023-03-08 15:13
Here's the relevant conda issue: https://github.com/conda/conda/issues/11721 (from internal slack).
