### ISSUE TITLE
Parameters for HoverTool to handle long strings (i.e. positioning the HoverTool box)

### ISSUE THREAD

**Issue by jolespin** [bokeh/bokeh#5311] opened 2016-10-05 21:24 UTC
When I use `HoverTool` on the left side of the plot it looks good:
![screen shot 2016-10-05 at 2 11 56 pm](https://cloud.githubusercontent.com/assets/9061708/19132154/202e4024-8b07-11e6-81a3-fb5ebd2ceeff.png)
but if I use it on the right side, then it is clipped:
![screen shot 2016-10-05 at 2 11 49 pm](https://cloud.githubusercontent.com/assets/9061708/19132162/29565c0e-8b07-11e6-98f3-a2732b90b171.png)

I looked at http://bokeh.pydata.org/en/latest/docs/reference/models/tools.html
and tried experimenting with the `anchor` argument but I couldn't seem to get it to work for what I was doing.

It would be cool if there was a scroll bar on it for long strings.  Defaulting to the very left of the `HoverTool` box would be really nice.

**Comment by jolespin** [comment] 2016-10-05 21:25
Note, if I resize it then it will work but if I send it to someone they might not know that right away.

**Comment by bryevdv** [comment] 2016-10-05 21:29
This is a dupe of #4930 which we have tried a few times, but not yet succeeded, to fix. That issue describes some possible alternatives (creating a fixed position hover of some sort, etc.)


(Very cool looking plot btw!)

**Closed by bryevdv** 2016-10-05 21:29 UTC

**Comment by jolespin** [comment] 2016-10-05 23:29
Thanks!  It's a microbial coabundance network.  I took the positions from `networkx` and plotted them w/ `circles`. Sorry about the duplicate, I looked around for a bit but I think my search terms were weak.

**Comment by bryevdv** [comment] 2016-10-05 23:53
np, it can be hard to search efficiently without institutional memory, knowing that something is a dupe is my job. :) 

BTW if you can share, and would interested in creating a very short blog post to show things off on bokeh.github.io we'd love to highlight your work

**Comment by jolespin** [comment] 2016-10-06 04:29
Yea I'll definitely put something together!  Basically a blog post on using `bokeh` for microbial networks?
