### ISSUE TITLE
Callback from data source not triggering when edits are made to data table

### ISSUE THREAD

**Issue by pmicheletty** [bokeh/bokeh#6582] opened 2017-07-03 20:48 UTC
I attempting to trigger python code when the data source is changed via a data table in a server app. I am was using the data_table.py example from [github](https://github.com/bokeh/bokeh/blob/master/examples/models/server/data_tables.py) to test. I had a discussion about this on gitter and Bryan Van De Ven gave me an updated script to try [here](https://gist.github.com/bryevdv/7dca3cbcba340af529435f6338f2a67f#file-data_update-py). The callback is properly triggered when he tests it but it doesn't trigger for me. 

Basicially we have a callback:
```
def on_data_change(self, attr, old, new):
    print(self.source.data)
```
Then update the data source using:
```
self.source.on_change('data', self.on_data_change)
```

That code is echoed in the gist link from @bryevdv. The update doesn't trigger on my system though.

I am running the bokeh server using the instructions on the [github](https://github.com/bokeh/bokeh/tree/master/examples/models). 

Here are some details about what I am running:
```backports                 1.0                      py34_0
backports_abc             0.4                      py34_0
bkcharts                  0.2                      py34_0
bokeh                     0.12.6                   py34_0    bokeh
bzip2                     1.0.6                    vc10_3  [vc10]
chest                     0.2.3                    py34_0
cloudpickle               0.2.1                    py34_0
colorama                  0.3.7                    py34_0
cycler                    0.10.0                   py34_0
dask                      0.9.0                    py34_0
decorator                 4.0.10                   py34_0
entrypoints               0.2.2                    py34_0
freetype                  2.5.5                    vc10_2  [vc10]
futures                   3.0.3                    py34_0
futures-compat            1.0                       py3_0
get_terminal_size         1.0.0                    py34_0
hdf5                      1.8.15.1                 vc10_4  [vc10]
heapdict                  1.0.0                    py34_1
icu                       57.1                     vc10_0  [vc10]
ipykernel                 4.3.1                    py34_0
ipython                   5.1.0                    py34_0
ipython_genutils          0.1.0                    py34_0
ipywidgets                4.1.1                    py34_0
jinja2                    2.8                      py34_1
jpeg                      9b                       vc10_0  [vc10]
jsonschema                2.5.1                    py34_0
jupyter                   1.0.0                    py34_3
jupyter_client            4.3.0                    py34_0
jupyter_console           4.1.1                    py34_0
jupyter_core              4.1.0                    py34_0
libpng                    1.6.27                   vc10_0  [vc10]
libtiff                   4.0.6                    vc10_3  [vc10]
locket                    0.2.0                    py34_1
markupsafe                0.23                     py34_2
matplotlib                1.5.3               np111py34_1
mistune                   0.7.2                    py34_0
mkl                       2017.0.1                      0
nbconvert                 4.2.0                    py34_0
nbformat                  4.0.1                    py34_0
nodejs                    4.4.1                         0
notebook                  4.2.1                    py34_0
numexpr                   2.6.1               np111py34_2
numpy                     1.11.3                   py34_0
openssl                   1.0.2h                   vc10_0  [vc10]
pandas                    0.19.2              np111py34_1
partd                     0.3.3                    py34_0
path.py                   8.2.1                    py34_0
patsy                     0.4.1                    py34_0
phantomjs                 2.1.1                         0
pickleshare               0.7.2                    py34_0
pillow                    4.0.0                    py34_0
pip                       8.1.2                    py34_0
prompt_toolkit            1.0.9                    py34_0
pygments                  2.1.3                    py34_0
pyparsing                 2.1.4                    py34_0
pyqt                      5.6.0                    py34_2
pyreadline                2.1                      py34_0
pyshp                     1.2.10                    <pip>
pytables                  3.2.2               np111py34_4
python                    3.4.4                         5
python-dateutil           2.5.3                    py34_0
pytz                      2016.4                   py34_0
pyyaml                    3.11                     py34_4
pyzmq                     15.2.0                   py34_0
qt                        5.6.2                    vc10_3  [vc10]
qtconsole                 4.2.1                    py34_2
requests                  2.10.0                   py34_0
scikit-learn              0.18.1              np111py34_1
scipy                     0.18.1              np111py34_1
seaborn                   0.7.1                    py34_0
selenium                  3.0.1                    py34_0    conda-forge
setuptools                23.0.0                   py34_0
simplegeneric             0.8.1                    py34_1
singledispatch            3.4.0.3                  py34_0
sip                       4.18                     py34_0
six                       1.10.0                   py34_0
ssl_match_hostname        3.4.0.2                  py34_0
statsmodels               0.6.1               np111py34_1
tk                        8.5.18                   vc10_0  [vc10]
toolz                     0.8.0                    py34_0
tornado                   4.3                      py34_1
traitlets                 4.2.1                    py34_0
vs2008_runtime            9.00.30729.1                  1
vs2010_runtime            10.00.40219.1                 1
vs2015_runtime            14.0.25123                    0
wcwidth                   0.1.7                    py34_0
wheel                     0.29.0                   py34_0
win_unicode_console       0.5                      py34_0
zlib                      1.2.8                    vc10_3  [vc10]```

**Comment by bryevdv** [comment] 2017-07-03 20:49
@pmicheletty first thing I notice offhand is tornado 4.3 Just to rule that out can you try with tornado 4.4 and/or 4.5 and see if things still don't work?

**Comment by bryevdv** [comment] 2017-07-03 20:52
Then, assuming that does not change anything, can you provide details about OS/browser versions?

**Comment by pmicheletty** [comment] 2017-07-03 21:06
@bryevdv Ok I updated my tornado to 4.4.2 and it's the same- no trigger. I am running on my work laptop with Windows 10 and Google Chrome: Version 59.0.3071.115 (Official Build) (64-bit). My work laptop could potentially have some funny firewall things, but I've been running bokeh stuff for a while and this seems to be the first issue.

**Comment by bryevdv** [comment] 2017-07-03 21:13
@pmicheletty OK thanks, marking this a `plat:windows` and `plat:chrome` for now. If you have the opportunity to confirm whether it's not working in any other configurations that would be helpful. In particular, different browsers on the same OS, and different OS with the same browser would be very valuable to narrow things down.

**Comment by pmicheletty** [comment] 2017-07-05 22:35
@bryevdv Ok - I was able to do a little more testing. Here's the update. I tested with Firefox and Microsoft Edge- same issue, callback was not triggering. I don't really have the opportunity to test with a different OS but I did have a co-worker test on her machine just to make sure my python environment wasn't the problem and she was having the same issue (no callback triggering). However, I then reverted back to bokeh version `0.12.5` and low and behold, the callback works as expected! So maybe that helps with the investigation.

**Comment by DuCorey** [comment] 2017-07-07 17:00
@bryevdv This is a duplicate of #6478. The python callback won't be triggered because the datasource on the python side isn't being modified after the editing the data on the JS side. The issue was resolved with #6483.
@pmicheletty This issue has been resolved and the fix should be working on the current dev version of Bokeh. You can also keep working on 0.12.5.

**Comment by pmicheletty** [comment] 2017-07-13 16:11
@DuCorey great thanks! I updated bokeh to the latest dev version and it seems to be working for me now.

**Comment by bryevdv** [comment] 2018-04-10 23:49
this should have been closed earlier

**Closed by bryevdv** 2018-04-10 23:49 UTC
Labels: plat: chrome, plat: windows, reso: completed, type: bug
