### ISSUE TITLE
Using multiple variation of tools causes a UserWarning

### ISSUE THREAD

**Issue by rs2** [bokeh/bokeh#5656] opened 2017-01-05 12:52 UTC
`bokeh` `0.12.3`

Repro:
* Add `tools='box_select,xbox_select,wheel_zoom,xwheel_zoom'` to `figure`.
* Get: `site-packages\bokeh\plotting\helpers.py:387: UserWarning: BoxSelectTool,WheelZoomTool are being repeated`

Expected behavior:
The code references the same classes, but instantiates them with different properties and expects different behavior. The warning should not appear in this case.

**Comment by mattpap** [comment] 2017-01-05 15:59
This is a duplicate of issue #5135.

**Closed by mattpap** 2017-01-05 15:59 UTC
Labels: reso: duplicate

**Comment by rs2** [comment] 2017-01-05 16:13
@mattpap Thank you! My bad (homework not done properly)
