### ISSUE TITLE
Setting min_border does not work

### ISSUE THREAD

**Issue by philippjfr** [bokeh/bokeh#3563] opened 2016-01-06 22:14 UTC
Setting the convenience attribute ``min_border`` does not appear to be working in 0.11. This small example should reproduce the issue.

```python
from bokeh.plotting import figure, output_notebook, show

output_notebook()

# create a new plot with a title
p = figure(plot_width=400, plot_height=400, min_border=0)
p.border_fill_color = "whitesmoke"
p.min_border = 0

p.circle([1,2,3,4,5], [2,5,8,2,7], size=10)

show(p)
```

Neither setting it in the constructor nor setting the attribute seems to make a difference. Only explicitly setting ``min_border_left/right/top/bottom`` actually applies it.

**Comment by hafen** [comment] 2016-01-06 23:56
I'm experiencing the same issue (putting 0.11 into rbokeh).  None of the border options seem to be working for me.

**Comment by bryevdv** [comment] 2016-01-07 00:11
@hafen Can you provide the JSON you are trying? `min_border_left` is working in the user guide generated plot here: http://bokeh.pydata.org/en/latest/docs/user_guide/styling.html#border

It is conceivable `min_border` has issues, our properties system had to undergo some changes recently, and that was kind of an odd duck. Will investigate.

**Comment by mmcdan** [comment] 2016-01-07 00:49
Would like to confirm that for 0.11.0, ```min_border=0``` does not work for me, but ```min_border_left=0, min_border_right=0, min_border_top=0, min_border_bottom=0``` does work.

**Comment by mattpap** [comment] 2016-01-07 01:14
Looking at `common/plot.coffee`, there is simply no logic for `min_border`. Otherwise the property is present and serialize properly. I can submit a fix tomorrow.

**Comment by mattpap** [comment] 2016-01-07 10:06
It's interesting to note that this originally used to work thanks to differences between property values in bokeh and bokehjs. As this gap was recently closed, as long as we want to keep numerical defaults for all five properties, there is no way to distinguish which of `min_border` and `min_border_*` was set intentionally and should take precedence. Currently the simplest solution would be to set the default value of `min_border` to `None`. Or we could introduce virtual properties. Alternatively, we could get rid of `min_border_*` altogether and set `min_border`'s type to `Instance(Rect).accept(Int, lambda v: Rect(v, v, v, v)` where `Rect` is a model with `top`, `right`, `bottom`, `left` properties (thought to do it right, we would need to introduce type parameterized models).

**Comment by mattpap** [comment] 2016-01-07 10:09
Actually setting `min_border` to `None` doesn't make sense. It's `min_border_*` which would need a change, but that defeats having default values at all.

**Comment by mtinti** [comment] 2016-01-10 12:16
I would like to add that  min_border_top does not work with GMapOptions. Thanks.

**Comment by jbednar** [comment] 2016-02-24 23:15
> Actually setting min_border to None doesn't make sense. It's min_border_* which would need a change, but that defeats the purpose of having default values at all.

Why doesn't setting min_border to None make sense?  The logic would then be something like:
```
left_border_to_actually_use = min_border_left if min_border is None else min_border 
```

This would still be a change in behavior from the docs, because the docs currently say that the min_border_X options override min_border, and this makes min_border override min_border_X.  Still, I think it makes more sense, and it would make this work properly.

Right now my code is filling up with min_border options, which is quite ugly, so I hope we can fix this before the next release.

**Comment by bryevdv** [comment] 2016-04-10 01:42
This is important and annoying, moving to `0.12`

**Comment by MulticastMatt** [comment] 2016-04-22 15:49
Mateusz - this is part of the layout work?  Yes.  
Bryan - this is a regression.  It worked at one time.
Mateusz - API changes?  

We have bokeh.plotting on the js side.  

Team estimate is 3 for simply addressing the issue.  We may make other issues to do add-on work.

**Closed** 2016-05-04 10:56 UTC
Labels: tag: component: bokehjs, type: bug
