### ISSUE TITLE
Circle renders as a slight oval

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#4956] opened 2016-08-12 23:59 UTC
This is the Bokeh code:

```python
p = figure(x_range=(-1.1, 1.1), y_range=(-1.1, 1.1))
p.circle(x=0, y=0, radius=1, fill_color=None, line_width=2)
```

This is what I see in Firefox:

<img width="684" alt="screenshot 2016-08-12 16 56 30" src="https://cloud.githubusercontent.com/assets/293525/17640021/d8366720-60ad-11e6-8474-3a734950aa35.png">

And this is what I see in Chrome:

<img width="651" alt="screenshot 2016-08-12 16 58 56" src="https://cloud.githubusercontent.com/assets/293525/17640046/216373b6-60ae-11e6-972b-28a1c08b064f.png">

This is from the "stream" example here: https://github.com/bokeh/bokeh-notebooks/blob/master/tutorial/08%20-%20server.ipynb

**Comment by ijstokes** [comment] 2016-08-13 00:01
FWIW, @bryevdv is presenting this and it looks fine on Chrome for him.  Here is my Bokeh info:

```bash
$ bokeh info   
Python version      :  3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:52:12) 
IPython version     :  5.0.0
Bokeh version       :  0.12.1
BokehJS static path :  /Users/ijstokes/anaconda/envs/bokehtut/lib/python3.5/site-packages/bokeh/server/static
```

**Comment by bryevdv** [comment] 2016-08-15 20:46
dupe of #517

**Closed by bryevdv** 2016-08-15 20:46 UTC
