### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by moomop** [bokeh/bokeh#10404] opened 2020-08-17 21:08 UTC
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Issue is seen using bokeh versions 2.1.1 or 2.1.0. Note that behavior appears correct in earlier versions (tested with 2.0.2 and 2.0.0)
Issue seems to be specific to iPadOS/iOS (seen using iPadOS 13.6.1 and iOS 13.6.1). It can be seen using either Safari or Firefox browsers on those platforms.
The fact that it is only seen in recent versions of Bokeh makes me think this is more likely to be a bug in Bokeh (or at least an issue you may want to investigate) rather than an issue related to the browsers (e.g. the javascript engine). 

#### Description of expected behavior and the observed behavior
Observed behavior when saving an image using the SaveTool (i.e. the "disc" icon in the toolbar) is that the downloaded image is cropped and doesn't show the whole plot area. Expected behavior (seen using bokeh 2.0.2) is that downloaded image should show the entire plot.

#### Complete, minimal, self-contained example code that reproduces the issue
I encountered this during use of bokeh, but noticed that the issue is evident for plots shown in the bokeh documentation, which I think will be the easiest way for you to reproduce the issue.
e.g. https://docs.bokeh.org/en/2.1.1/docs/user_guide/quickstart.html#userguide-quickstart   shows the issue
whereas https://docs.bokeh.org/en/2.0.2/docs/user_guide/quickstart.html#userguide-quickstart shows the expected behavior.

See screenshots of bug behavior below. Note that selecting download results in a cropped image being saved.

#### Screenshots or screencasts of the bug in action
![IMG_1834](https://user-images.githubusercontent.com/69820288/90443815-c4f06980-e0d4-11ea-8bd9-ee4f8cc9797f.JPG)
![IMG_1835](https://user-images.githubusercontent.com/69820288/90443845-ccb00e00-e0d4-11ea-8dd1-d6d4243c242d.JPG)
![IMG_1836](https://user-images.githubusercontent.com/69820288/90443723-a1c5ba00-e0d4-11ea-9aaa-81d4614f9314.JPG)
Example of saved image
![bokeh_plot 6](https://user-images.githubusercontent.com/69820288/90444108-3cbe9400-e0d5-11ea-814a-c009389fed6d.png)

**Comment by mattpap** [comment] 2020-08-17 21:21
This is a duplicate of issue #10249.

**Closed by mattpap** 2020-08-17 21:21 UTC
Labels: TRIAGE
