### ISSUE TITLE
[BUG] Scrolling to anchor unreliable

### ISSUE THREAD

**Issue by rynkk** [bokeh/bokeh#11133] opened 2021-04-05 14:52 UTC
If accessing bokeh's documentation by using a link with an anchor to a subtopic, I only rarely get sent to the right portion of a page.

Tested on [Google Chrome Version 89.0.4389.114] and on [Microsoft Edge Version 89.0.774.68].
I realize this might be not directly caused by the coding of bokeh.org but an external library or even the browser, but as it still impedes my usage of bokeh.org documentation and I can't pinpoint the source of the bug I put it here.

Exemplary link:
[https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#setting-the-active-tools](https://docs.bokeh.org/en/latest/docs/user_guide/tools.html#setting-the-active-tools)

I realized, that the page sometimes scrolls to the right anchor, but once bokeh-plots are drawn it gets offset by that amount.

I also noticed that if you visit the page for the first time, since you opened your browser, it sometimes goes to the anchor. If you scroll around a bit and then reload the page it will go to the part where you left the page at, not the anchor.

Here's a video: [https://gyazo.com/83b4e19820c1c10294b92b3b3b4ab3ab](https://gyazo.com/83b4e19820c1c10294b92b3b3b4ab3ab)

**Comment by bryevdv** [comment] 2021-04-05 19:40
I just noticed this issue was on the repo for the https://bokeh.org static site which is maintained separately from the documentation. I have moved to the main repo https://github.com/bokeh/bokeh

**Comment by mattpap** [comment] 2021-04-05 19:43
This is a duplicate of issue #10137. This is reproducible in Chrome but works in Firefox (on Linux).

**Comment by bryevdv** [comment] 2021-04-05 19:50
closed as `dupe`

**Closed** 2021-04-05 19:50 UTC
Labels: reso: duplicate
