### ISSUE TITLE
image_url glyphs missing when using export_png

### ISSUE THREAD

**Issue by JanLikar** [bokeh/bokeh#7312] opened 2017-12-11 18:44 UTC
Bokeh version: 0.12.13
Python version: 3.5.2

```
from bokeh.io import export_png
from bokeh.plotting import figure

f = figure(x_range=(0,1), y_range=(0,1))
f.image_url(['http://pngimg.com/uploads/cat/cat_PNG106.png'], x=0, y=1, w=1, h=1)

export_png(f, filename='cat.png')
```
When using the code above with `bokeh.plotting.show`, the following chart is shown:
![screenshot from 2017-12-11 19-36-07](https://user-images.githubusercontent.com/4228250/33847633-7c0072e8-deab-11e7-9ddc-fdd4071ff74f.png)

When trying to export the plot to png using `bokeh.io.export_png`, the glyph is missing.
![cat](https://user-images.githubusercontent.com/4228250/33847611-67ca4d12-deab-11e7-88ea-505c7226f540.png)

Browser console contains no errors or warnings.

**Comment by bryevdv** [comment] 2017-12-13 15:21
Suspect that, given how `ImageURL` has to wait to load URS asynchronously and then actually do the draw in a callback, that `idle` and "done" are being reported to early.

**Comment by mattpap** [comment] 2017-12-13 15:32
I also noticed on travis ci that image_urls are sometimes missing. Either the idle heuristic is incorrect or there was a recent regression.

**Comment by bryevdv** [comment] 2018-05-10 16:52
This is a dupe of https://github.com/bokeh/bokeh/issues/6303

**Closed by bryevdv** 2018-05-10 16:53 UTC
Labels: tag: component: bokehjs, type: bug

**Comment by peekxc** [comment] 2023-08-04 15:28
Please re-open, this is a simple test-case that indeed does not work on my machine.

Bokeh version: 3.2.1
Python version: 3.9.12

**Comment by bryevdv** [comment] 2023-08-04 15:39
@peekxc this issue is five years old and the Bokeh codebase is dramatically different. At this point you need to open a brand new issue with the full details required in the issue template.
