### ISSUE TITLE
Smooth transitions between views

### ISSUE THREAD

**Issue by ijstokes** [bokeh/bokeh#5257] opened 2016-09-30 12:50 UTC
I've often wanted to build Bokeh visualizations where there is some slider for one "axis", since data points from one view are linked to data points in other views (accessed via the slider).  Having a smooth transition between those views would be beautiful.  E.g. the gap minder bokeh version, or being able to construct something like this:

https://www.google.com/get/videoqualityreport/?v=ldfF6chin5s

I could imagine that with this capability one option for a plot configuration would be to automatically animate by either "scrolling" (and looping) through views at some pace, effectively creating an animation, or "rocking" back and forth (to avoid hard cuts from the end to the beginning) along some view axis.

**Comment by bryevdv** [comment] 2016-10-01 15:07
dupe of #128

**Closed by bryevdv** 2016-10-01 15:07 UTC

**Comment by ijstokes** [comment] 2016-10-01 16:34
@bryevdv is this the same thing as #128?  I didn't mean to focus on "animation" (though of course that would be awesome) which was the second part of my comment, but more on the first part: smooth transitions between states.  Maybe that is, effectively, the same thing.  @tonyfast figured out some way for that to happen here:

http://screencast.com/t/GqeyHZViHt

So maybe the capability is already present in Bokeh, and I just don't know how to leverage it.  It isn't clear to me if @tonyfast had to do anything special/magical to make those fancy smooth transitions happen.  The fact that the very cool Gapminder demo **doesn't** have smooth transitions made me assume that it was Tony-Magic for his multi-dimensional vis, and therefore **not** built in to Bokeh, but of course I could be wrong.

**Comment by mattpap** [comment] 2016-10-01 17:38
This isn't a duplicate of issue #128, though it would be useful/necessary to have this for transitions between frames.

**Comment by tonyfast** [comment] 2016-10-01 18:11
[This notebook](https://anaconda.org/tonyfast/principal-component-viewer/notebook) was used to create that interaction.  The coffeescript down the bottom creates the transition.  It uses a jinja template to pass bokeh objects to the client.

I am using parts of `underscore` from` bokeh` with `d3` transitions; the transitions could be removed easily.  I think the trick to this was creating the `ghost` data source which is only visible during the transition.

**Comment by bryevdv** [comment] 2016-10-01 18:33
This is a duplicate of #128. From the discussion there:

> This is about being able to script animations by defining a sequence of vis state "waypoints" that should occur at set times, with some transfer function to take the state from one to the next.

which is roughly exactly what @tonyfast did using `d3` transitions by hand.  Perhaps my wording there was unclear, the transfer function is meant to interpolate the states, i.e. provide smooth transitions. 

FWIW you since "smooth transitions" is completely equivalent to *more* data updates, you could certainly have smooth transitions in a bokeh server app today by simply interpolating in python yourself. #138 is about providing a way to declare the transitions you want and have them happen automatically.

**Comment by mattpap** [comment] 2016-10-01 19:40
> you could certainly have smooth transitions in a bokeh server

I doubt that. You can get finer granularity, but I think you won't be close to what you can get in d3 and/or you will get close to 100% CPU utilization (which I get anyway with animation examples in a VM). Thus I think #5257 and #128 are two related issues tackling different parts of the rendering pipeline. Also in #5257 there should be no state transfer between client and server, whereas in #128 there should be.

**Comment by bryevdv** [comment] 2016-10-01 19:56
I think we are talking at odds. I mention the sever as a potential immediate workaround. #128 predates the server I was not anywhere in mind. #128 is about client side interpolated transitions, sorry if my wording there is unclear.
