### ISSUE TITLE
bokeh plot in jupyter slides not rendered corretly

### ISSUE THREAD

**Issue by luoq** [bokeh/bokeh#4859] opened 2016-07-22 06:50 UTC
[bokeh export bug.zip](https://github.com/bokeh/bokeh/files/377621/bokeh.export.bug.zip)

The plot in slides generated by following command ('bokeh export bug.slides.html') is not rendered correctly.

```
jupyter nbconvert --reveal-prefix=http://lab.hakim.se/reveal-js/ --to slides 'bokeh export bug.ipynb'
```

It should behave like 'bokeh export bug.html' generated by

```
jupyter nbconvert --to html 'bokeh export bug.ipynb'
```

bokeh info:
Python version      :  3.5.2 |Anaconda 4.1.1 (64-bit)| (default, Jul  2 2016, 17:53:06) 
IPython version     :  4.2.0
Bokeh version       :  0.12.0
BokehJS static path :  /home/lq/.local/anaconda3/lib/python3.5/site-packages/bokeh/server/static

**Comment by bryevdv** [comment] 2016-12-10 21:16
ping @damianavila do you have any insights or comments?

**Comment by damianavila** [comment] 2016-12-12 14:17
I ca reproduce it, not sure why is failing yet. It is probably a confilct between reveal.js and bokeh... but I need to investigate further.

**Comment by bryevdv** [comment] 2017-05-12 04:20
@luoq @damianavila any updates on this?

**Comment by damianavila** [comment] 2017-05-12 13:44
We should probably test with latest Bokeh and latest nbconvert to see if the issue persist.

**Comment by luoq** [comment] 2017-05-15 02:13
This issue persists for bokeh 0.12.5

**Comment by 00krishna** [comment] 2017-05-22 18:20
+1 I have this problem when I try to export to pdf with nbconvert 5.1.1 and bokeh 12.5. The pdf gets generated but all of the plots are left out.

**Comment by luoq** [comment] 2017-05-24 02:31
@bryevdv you can try the zip file in first comment

**Comment by bryevdv** [comment] 2017-05-24 16:42
the plain HTML works, the slides do not. Presumably because that notebook has sub-slides and mine didn't actually have real slide cells define. Looking at the JS console, the proximate cause is clear:

<img width="587" alt="screen shot 2017-05-24 at 11 39 47" src="https://cloud.githubusercontent.com/assets/1078448/26414781/d213c448-4075-11e7-944d-d431049a6c90.png">

BokehJS is not getting loaded at all, which can also be confirmed by looking at the "sources" tab in the browser debug window. Unfortunately I have no idea why this would or could be, and probably c

**Comment by bryevdv** [comment] 2017-05-24 16:45
I will say, just to be clear, we don't currently and have not ever made any guarantees except for: in a running notebook, and in a plain HTML static rendered notebook. Obviously I'd love for things to work with reveal but if reveal and Bokeh don't work together that just may have to be noted as a known incompatibility.

**Comment by mansenfranzen** [comment] 2017-06-13 17:36
I just came across the same issue having **reveal.js** not showing **bokeh plots** in the **slide show** which is sad considering the great functionality that bokeh, reveal and jupyter provide in combination for interactive data visualization (thanks to all of you guys - I really appreciate it!).  

Fix via added bokeh.js import
-------------------------------------
Following @bryevdv comment about `BokehJS failed to load within specified timeout`, I manually added the the bokeh.js import `<script type="text/javascript" src="https://cdn.pydata.org/bokeh/release/bokeh-0.12.5.min.js"></script>` to the html header of `'bokeh export bug.slides.html'` after the file was generated via `jupyter nbconvert --to slides 'bokeh export bug.ipynb'`. 

This causes the bokeh plots to show up again. It indicates that the issue is somehow related to how bokeh.js is loaded/imported. 

Fix via slide type within Jupyter
---------------------------------------
After experimenting with the slide types of the jupyter notebook, I figured that the key is to **not skip** `output_notebook()` in order to have the plots showing up. The `output_notebook()` is required for the related import of bokeh.js. Therefore, do not set it's slide show relevant cell slide type to `skip`. This information might help for a fix here @damianavila.

In order to hide `output_notebook()` for the slide show anyway, you can simply use the slide type **notes**.

Test material
-----------------
For convenience, I added a [zip](https://github.com/bokeh/bokeh/files/1072281/bug_working.zip) with a working and non working version based on @luoq example notebooks.

Environment
----------------
I tested this with bokeh 0.12.5 and 0.12.6 with python 3.5.2 under ubuntu 16.4. with the newest jupyter and ipython packages.

**Comment by bryevdv** [comment] 2017-06-13 17:40
@mansenfranzen This is incredibly valuable information, thank you very much for taking the time to investigate and write things up. It had escaped my notice that `output_notebook` was hidden or missing. It is indeed required in order to load BokehJS (which in turn is required for bokeh plots to show up). 

Perhaps there is some other mechanism we can use to perform the work but otherwise hide the call, @damianavila any suggestions? Otherwise we can use this issue as a task to include this information in the documentation more prominently.

**Comment by damianavila** [comment] 2017-06-13 18:34
> Otherwise we can use this issue as a task to include this information in the documentation more prominently.

I think documentation is the key here... if you **skip** a cell and try to convert to html or slides, that specific cell and the output of that cell (containing the bokeh.js) is not "passed" to the final output, preventing the correct loading of the bokeh plots. Putting `output_notebook` into the **notes** slide type is a reasonable workaround if you want to hide it. Modifying things like nbconvert or bokeh to handle this better is probably to much cost compare with the benefits that could potentially bring into the table.

**Comment by bryevdv** [comment] 2017-06-20 18:00
I added a new section to the notebook chapter of the user's guide in https://github.com/bokeh/bokeh/pull/6506/commits/33d11cbfd7420271dd92564c3d633280bd4ba925 This issue will automatically close when that PR is merged. @damianavila if there is something more/better to say than what I have added in that commit please let me know.

**Comment by damianavila** [comment] 2017-06-20 20:01
> @damianavila if there is something more/better to say than what I have added in that commit please let me know.

LGTM as is.

**Closed** 2017-06-20 21:11 UTC
Labels: tag: component: docs, type: task
