### ISSUE TITLE
Title overlays on figure in 0.12.6rc4

### ISSUE THREAD

**Issue by mrocklin** [bokeh/bokeh#6432] opened 2017-06-10 13:16 UTC
In the transition from rc3 to rc4 one of the titles of one of my figures moved onto the main body of the figure itself.  See the bottom plot in the image below.  The text "Progress - total ..." is the title of the figure:

![image](https://user-images.githubusercontent.com/306380/27003037-45a4aaa4-4dbd-11e7-854f-238cdce87b6c.png)

cc @mattpap

**Comment by mattpap** [comment] 2017-06-10 14:25
@mrocklin, I need to reproduce this layout. Plots can be dummy, but the structure must be exactly the same (grid vs row/column, toolbar locations + stickiness, panels (axes, labels, legends, color bars)).

**Comment by mrocklin** [comment] 2017-06-10 14:35
Yes, I can see how that would be valuable.  I can try to get to this, but it probably won't be for the next few days.  If you'd like to proceed without me I produced this in the following way:

```
pip install git+https://github.com/dask/distributed
dask-scheduler
open localhost:8787/status
```

The bottom plot should have a title, but won't.  Relevant code for this particular plot lives here: https://github.com/dask/distributed/blob/master/distributed/bokeh/scheduler.py#L619-L721

**Comment by mrocklin** [comment] 2017-06-11 13:26
I was able to work around this by adding a title to my figure on creation.  Previously the figure didn't have a title when it was first created.  Perhaps the layout engine was saving space because it didn't think that a title would be present in the future (a fair assumption).

**Comment by bryevdv** [comment] 2017-06-11 13:38
@mattpap I am marking this as a regression, however as it only happens in some specific circumstances, with a particular usage, and there is a workaround I think there is not a huge pressure to fix this for the next release. 

@mrocklin it's definitely a bug, titles should always be accommodated regardless of when/how they were added.

**Comment by mattpap** [comment] 2017-06-11 21:30
> (...) by adding a title to my figure on creation.

Adding stuff like this after initial render is pretty much not supported. I would like to fix this in 0.12.7.

**Comment by bryevdv** [comment] 2018-03-17 02:06
@mrocklin can you comment if this is still an issue?

**Comment by mrocklin** [comment] 2018-03-17 03:09
No immediate comment on this.  I haven't thought about it since my workaround from earlier.  My backlog is long enough that I'm unlikely to get to this soon.  My apologies for raising an issue and then not following up.

**Closed** 2019-11-10 05:35 UTC
Labels: tag: layout, tag: regression, type: bug

**Comment by bryevdv** [comment] 2019-11-10 05:36
Probably since resolved, but without an MRE it's not possible to say or follow up on this.
