### ISSUE TITLE
Disappearing Toolbar

### ISSUE THREAD

**Issue by marcuskd** [bokeh/bokeh#7497] opened 2018-02-06 13:12 UTC
In the example below (the plot appears after the button is pressed), the toolbar disappears when the plot (or toolbar) is tapped. The problem appeared in 0.12.11 onwards.

Software versions...
Bokeh 0.12.13
Python 3.5.2
Firefox 57.0.4 (64 bit)
```

from bokeh.models.sources import ColumnDataSource
from bokeh.models.layouts import Column, WidgetBox
from bokeh.models.widgets import Button, Div
from bokeh.plotting import Figure
from bokeh.io import curdoc
from bokeh.events import Tap

fig = Figure()
line_src = ColumnDataSource(data={'x': [0, 1], 'y': [0, 1]})
line = fig.line('x', 'y', source=line_src)


def update_data(event):
    line_src.data['x'][1] = event.x
    line_src.data['y'][1] = event.y
    fig.renderers.remove(line)
    fig.renderers.append(line)

fig.on_event(Tap, update_data)


def update_plot():
    gui.children[1] = fig

btn = Button(label='Click to plot')
btn.on_click(update_plot)
gui = Column(WidgetBox(btn), Div())

curdoc().add_root(gui)

```

**Comment by mattpap** [comment] 2018-02-06 14:55
The problem here is a result of toolbar panel being created in bokehjs and added to `Plot.renderers`, which isn't synchronized properly between browser and server, so when line glyph is updated, bokehjs attempts to remove the panel and fails with that. The failure allows for rendering a panel that was destroyed, and this results in an exception. This is along standing problem that we allow internal bokehjs objects to interact with the server. Fixing this would likely fix a few dozen other issues.

**Comment by itaicaspi-intel** [comment] 2018-05-10 13:13
Is there any known workaround for this issue?

**Comment by mattpap** [comment] 2018-05-10 14:39
There are two options. If you want to keep the toolbar as part of a plot, then you will have to create a `ToolbarPanel` manually and add it with `add_layout()` to a plot. Alternatively you can have a toolbar detached from a plot, as an element of a bigger layout, like it happens with grid plots. In both cases the key is to set `plot.toolbar_location = None`, to disable creation of the default `ToolbarPanel`. Currently I don't have any code to verify this and show how this works in detail. I will be update this issue later on.

**Comment by itaicaspi-intel** [comment] 2018-05-11 07:17
That did the trick. Thanks!

For anyone interested, I created a `Toolbar` and assigned it to `plot.toolbar`. 
Additionally, I created a `ToolbarBox`, initialized it with the toolbar and finally added it to the page layout above the plot using a `column`

**Comment by ticktronaut** [comment] 2018-07-17 11:09
I have written a [python class that is capable of live plotting data in different graphs](https://github.com/ticktronaut/dynamic_live_plot/blob/master/bokeh/bokeh_live_plot.py). It is based on [python bokeh](https://bokeh.pydata.org/en/0.13.0/) and has been tested with python bokeh 13. Basically it is an abstraction of embedding bokeh server as a library and it is capable to dynamically add and remove figures and line glyphs during runtime. To make this happen in a non-blocking manner the main class extends multithreading.Thread. All codes can be found [here](https://github.com/ticktronaut/dynamic_live_plot).

An issue I encountered is that figures are not always rendered correctly. Often **Title and Toobar of the figures are not rendered**, as shown here (click on it to have a larger view on the gif):
![showcase](https://user-images.githubusercontent.com/1530795/42813376-13d12822-89c1-11e8-9649-fe2c5161063f.gif)

Following javascript Error is thrown in the debug console of the browser (google chrome):

> Uncaught TypeError: Cannot read property 'draw_legend' of undefined

To add figures during runtim I am using the code bellow, where _fig_ is a dictionary, which contains all figure objects in my projects and cds is a dictionary of all corresponding ColumnDataSource objects:

```python
        if not fig_name in fig:
            print('add fig ' + fig_name)
            # create plot
            TOOLS="pan,wheel_zoom,box_zoom,reset, save, tap, hover"
            fig[fig_name]=figure(plot_width=900, plot_height=280, tools=TOOLS, toolbar_location='right', logo=None, title=(fig_name), name=str(fig_name))
            cds[fig_name]=ColumnDataSource(data=dict(x=np.array([])), name=(fig_name+'_cds'))
            plt_col=doc.get_model_by_name('plt_ui_col').children
            plt_col.append( fig[fig_name] )
```
I posted the problem [on stackoverflow](https://stackoverflow.com/questions/50494352/python-bokeh-title-and-toolbar-are-not-rendered), but since this seems to be related to this issue (is this true?) I post all information ([including the sample code](https://github.com/ticktronaut/dynamic_live_plot)) in this post. Maybe it is helpful for tracking down the bug. Can I post some more information, that could help on this issue?

**Comment by Nicoowr** [comment] 2018-10-30 08:37
Just for those who might ask how to do what @itaicaspi-intel did, here is an example code (the doc is not clear about it):

      p = figure(....., toolbar_location=None)

      tools = [HoverTool(), BoxZoomTool(), ResetTool()]
      p.tools = tools
      toolBarBox = ToolbarBox()
      toolBarBox.toolbar = Toolbar(tools=tools)
      toolBarBox.toolbar_location = "above"

Then insert the toolbarbox in your layout :)

**Comment by renzop** [comment] 2018-10-30 15:18
About the workaround with ToolbarPanel. Does anyone have a code example (I can't ) get it woking. 

I had a working bokeh embedding with components with 0.12.16 but the toolbar disappeared when migrating to 1.0.0. Am I looking to the right issue or is only related to server documents? I don't use a layout at all.

**Comment by importpandasaspd** [comment] 2018-12-04 11:04
> ```
> 
> ```
> Then insert the toolbarbox in your layout :)

how do I insert the toolbarbox in the layout?
This:

```
from bokeh.models.sources import ColumnDataSource
from bokeh.models.layouts import Column, WidgetBox
from bokeh.plotting import Figure, output_notebook


output_notebook()

tools = [HoverTool(), BoxZoomTool(), ResetTool()]
fig = Figure(toolbar_location=None)
fig.tools= tools
toolBarBox = ToolbarBox()
toolBarBox.toolbar = Toolbar(tools=tools)
toolBarBox.toolbar_location = "above"

line_src = ColumnDataSource(data={'x': [0, 1], 'y': [0, 1]})
line = fig.line('x', 'y', source=line_src)

fig.add_layout(toolBarBox)
show(fig, notebook_handle=True)
```
gives me an error:
`ValueError: expected an element of List(Instance(Renderer)), got seq with invalid items [ToolbarBox(id='24697', ...)]`

**Comment by Nicoowr** [comment] 2018-12-04 11:19
@importpandasaspd 
In my case, I'm using tabs so I used this code:
`  tab = Panel(child=column(toolBarBox, p), title='Foo')`
I think in your case you need to first put the toolbar in a layout object such as a row or a column and then call add_layout

**Comment by importpandasaspd** [comment] 2018-12-04 11:56
@Nicoowr
great, thanks for the suggestion!
This worked: 
```
from bokeh.models.sources import ColumnDataSource
from bokeh.models.layouts import Column, WidgetBox
from bokeh.plotting import Figure, output_notebook, Column
from bokeh.layouts import layout, row

output_notebook()

tools = [HoverTool(), BoxZoomTool(), ResetTool()]
fig = Figure(toolbar_location=None)
fig.tools= tools
toolBarBox = ToolbarBox()
toolBarBox.toolbar = Toolbar(tools=tools)
toolBarBox.toolbar_location = "right"

# plot blue
line_src = ColumnDataSource(data={'x': [0, 1], 'y': [0, 1]})
line = fig.line('x', 'y', source=line_src, color='blue')

t=show(row([fig, toolBarBox]), notebook_handle=True)

# change --> red
line = fig.line('x', 'y', source=line_src, color='red')
push_notebook(handle=t)
```

**Comment by bryevdv** [comment] 2019-01-31 03:07
confirm fixed by #8085

**Closed** 2019-02-01 16:18 UTC
Labels: tag: component: bokehjs, type: bug

**Comment by marcuskd** [comment] 2019-02-12 16:55
Just re-ran the original example from the 1.1.0 dev2 build and it works fine, many thanks to the dev team for the continuing great work!

**Comment by tedbunny** [comment] 2020-01-22 19:58
Hey, I am having the same problem, but now the toolbar shows up as a blank div in my html page when rendering, anything wrong with my code?

from bokeh.models import HoverTool, ResetTool, SaveTool
from bokeh.models.tools import Toolbar,  ToolbarBox

    plt = figure(... , toolbar_location=None)
    tools = [HoverTool(),ResetTool(), SaveTool()]
    plt.tools= tools
    toolBarBox = ToolbarBox()
    toolBarBox.toolbar = Toolbar(tools=tools)
    toolBarBox.toolbar_location = "right"

[...]
   t_plt=column([plt2,toolBarBox])
    script4, div4 = components(t_plt)

**Comment by bryevdv** [comment] 2020-01-22 21:20
@tedbunny That sounds unrelated to this old issue. I would suggest making a new issue, to avoid confusing potentially unrelated things together. We need full version information, and more important than anything: *a complete, minimal reproducer* that we can run to investigate.

**Comment by tedbunny** [comment] 2020-01-22 22:04
Thanks for the advice!
