### ISSUE TITLE
Define a default muted glyph

### ISSUE THREAD

**Issue by GenevieveBuckley** [bokeh/bokeh#8390] opened 2018-11-01 06:31 UTC
The bokeh `plot.legend.click_policy = 'mute'` doesn't change the opacity of glyphs. 
(The `hide` click policy does work well though.)

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh version 1.0.1 (I also tried the development installation from master)
python version 3.7.1
OS: macOS Mojave version 10.14 (18A391)
Browsers:
* Chrome version 69.0.3497.100 (Official Build) (64-bit)
* Firefox version 63.0 (64-bit)
* Safari version 12.0 (14606.1.36.1.9)

##### Expected:
> ...clicking or tapping on the legend entries will hide or mute the corresponding glyph in a plot. These modes are activated by setting the click_policy property on a Legend to either "hide" or "mute".
https://bokeh.pydata.org/en/latest/docs/user_guide/interaction/legends.html

##### Observed: 
The legend click policy 'mute' does not alter the opacity of the glyphs in the plot. (The 'hide' click policy works well though). This happens to me in a jupyter notebook, standalone html file, and in the bokeh server. It also doesn't seem related to which browser I use to interact with the plots.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
import numpy as np

from bokeh.plotting import figure
from bokeh.layouts import row
from bokeh.io import show, output_file

output_file("bokeh_legend_behavior.html")

# Set up some dummy data
glyph_size = 7
n_samples = 100
x1 = np.random.random(n_samples)
y1 = np.random.random(n_samples)
x2 = np.random.random(n_samples)
y2 = np.random.random(n_samples)
x3 = np.random.random(n_samples)
y3 = np.random.random(n_samples)

# Create plots
plot1 = figure(title="Legend click_policy = 'hide'")
plot1.circle(x=x1, y=y1, color='red', legend='Group 1', size=glyph_size)
plot1.square(x=x2, y=y2, color='green', legend='Group 2', size=glyph_size)
plot1.triangle(x=x3, y=y3, color='blue', legend='Group 3', size=glyph_size)
plot1.legend.click_policy = "hide"

plot2 = figure(title="Legend click_policy = 'mute'")
plot2.circle(x=x1, y=y1, color='red', legend='Group 1', size=glyph_size)
plot2.square(x=x2, y=y2, color='green', legend='Group 2', size=glyph_size)
plot2.triangle(x=x3, y=y3, color='blue', legend='Group 3', size=glyph_size)
plot2.legend.click_policy = "mute"

obj = row(plot1, plot2)
show(obj)
```

#### Stack traceback and/or browser JavaScript console output
I'm not getting any python or javascript errors/warnings.

#### Screenshots or screencasts of the bug in action
In the screenshot I've clicked on a few of the legend items, and the corresponding glyphs are hidden in the left hand plot (as expected), but I *don't* see glyphs with muted opacity in the right hand plot.

<img width="1208" alt="screen shot 2018-11-01 at 5 22 11 pm" src="https://user-images.githubusercontent.com/30920819/47836029-c0bd6400-ddfa-11e8-9c81-9905a5819d99.png">

**Comment by jbednar** [comment] 2018-11-01 13:36
I can't get your example to run in my environment, but I'd try defining a different muted_color wherever you set the color, so that muted and regular colors will be distinguishable.

**Comment by jsignell** [comment] 2018-11-01 13:43
Yeah I think there is no default for `muted_color` and `muted_alpha`. Swapping in these lines works for me on latest master:

```python
plot2.circle(x=x1, y=y1, color='red', legend='Group 1', muted_color='red', muted_alpha=0.2, size=glyph_size)
plot2.square(x=x2, y=y2, color='green', legend='Group 2', muted_color='green', muted_alpha=0.2, size=glyph_size)
plot2.triangle(x=x3, y=y3, color='blue', legend='Group 3', muted_color='blue', muted_alpha=0.2, size=glyph_size)
```

It does seem like alpha 0.2 should be the default and I'm not sure if this is a regression. So I'll leave this open for now.

**Comment by jsignell** [comment] 2018-11-01 15:03
I updated the example to something that runs for me locally.

**Comment by jbednar** [comment] 2018-11-01 16:10
Thanks, that was helpful!  Ok, looks like yes, `color='darkred' muted_color='red'` works fine (without needing any change in alpha), but that `muted_color` does not default to `color` as I thought it did.

So my vote is to change muted_alpha to 0.2 by default; it's very confusing for it to be 1.0 by default.  Maybe there is some reason that I'm not aware of, but this is definitely something that has caused me trouble in the past.

Whether to define a muted_color as color by default is trickier, but I think I would also vote for that, i.e. for the default muting to be the same color as the glyph, but with an alpha of 0.2 (or so).

**Comment by GenevieveBuckley** [comment] 2018-11-01 23:16
> I think I would also vote for that, i.e. for the default muting to be the same color as the glyph, but with an alpha of 0.2 (or so).
This was more or less what I expected the default to be - I didn't realize I'd have to set several parameters to make it function. I do think "mute" implies a reduced alpha value, a default of 1.0 doesn't seem sensible in this case.

**Comment by birdsarah** [comment] 2019-02-06 03:02
I just ran into this and also assumed things were broken. @bokeh/core what about resolving this issue with `muted_color=color` and `muted_alpha=0.2` as default?

**Comment by GenevieveBuckley** [comment] 2019-02-18 04:54
I'm happy to make a pull request for this @birdsarah, but I'm having a hard time wrapping my head around the repo organization. Can someone point me to the file or class that needs updating?

**Comment by bryevdv** [comment] 2019-02-19 03:15
@birdsarah well, maybe. The issue is that there is currently no default at all. There is no `muted_glyph` set at all unless one of the `muted_X` values is supplied. So the options are:

* it is incumbent on users to set muted parameters they want (current situation)
* all glyphs unconditionally have to have and serialize and send a muted glyph, even if there is no need for them to
* we have to create and add a "post processing" step (that does not exist now) which can note which glyphs appear in a legend and adds a muted glyph just for them. This probably would not work with updates to the legend contents.
* add a validation rule to check for the absence of muted glyphs when the legend policy is to mute. This would only work up front and not catch problems later in callbacks, etc. 

Neither of middle two sound that appealing to me. I think I'd rather just add a new validation warning and some supporting documentation that users always need to choose their own muting parameters.

**Comment by birdsarah** [comment] 2019-02-19 10:28
@bryevdv to clarify your suggestion. In the case of legend policy having been set to mute, if muted glyphs are not set a validation warning is raised? I think that's a simple and helpful solution in light of your outlined problems with the available options.

@bryevdv where would we orchestrate a validation warning like this - it's a couple of things coming together? (@GenevieveBuckley with the answer to this question from @bryevdv it should be clear where we need to make an update).

**Comment by bryevdv** [comment] 2020-02-05 05:43
Well, this obviously slipped through my attention net. After (a long) while away, I think actually I've changed opinion and we should just do 
> all glyphs unconditionally have to have and serialize and send a muted glyph, even if there is no need for them to

This is exactly what we do with non-selection glyphs, and why they "work" and these "don't work".

**Comment by tony-bony** [comment] 2020-02-20 10:51
Related issue: https://github.com/bokeh/bokeh/issues/8852

**Comment by virajone** [comment] 2020-10-10 19:47
@bryevdv Hey, I would like to work on this issue. I wanted to know if any work is currently being done on this one ?

**Comment by GenevieveBuckley** [comment] 2020-10-11 22:48
It's been a while since there was any discussion here so I would guess that there isn't anything currently being worked on here. I'd go right ahead and give it a go @virajone

**Closed** 2021-08-05 04:54 UTC
Labels: good first issue, type: task
