### ISSUE TITLE
User-specified tick labels with FixedTicker

### ISSUE THREAD

**Issue by wiemerc** [bokeh/bokeh#3051] opened 2015-11-02 18:06 UTC
Is there any chance that you might add the possibility to specify the tick labels in addition to the tick positions with FixedTicker? This is possible with matplotlib and would be really helpful for me (and maybe for others as well).

Or is it already possible and I just couldn't figure out how?

Thanks.

**Comment by bryevdv** [comment] 2015-11-02 18:15
dupe of #1671

This would be a good feature certainly, and a nice "starter" PR for an interested new contributor.

**Closed by bryevdv** 2015-11-02 18:15 UTC

**Comment by wiemerc** [comment] 2015-11-02 18:29
Thanks for the quick reply and sorry for not checking for an existing issue.
