### ISSUE TITLE
[BUG] Graph shrink problem with Jupyter Notebook on Chrome, IE, Microsoft Edge.

### ISSUE THREAD

**Issue by dylanzxc** [bokeh/bokeh#10184] opened 2020-06-16 19:19 UTC
We are developing an open-source data preparation library(Dataprep https://github.com/sfu-db/dataprep) using bokeh. The original issue is reported here https://github.com/sfu-db/dataprep/issues/179. 

So for one of our functions, plot(df,x), all the graphs in each tab have been shrunk as shown below. 
![image](https://user-images.githubusercontent.com/56427336/84817984-a4b80780-afca-11ea-9335-c4479f40e944.png)
![image](https://user-images.githubusercontent.com/56427336/84818018-aeda0600-afca-11ea-806f-13b1965fe4d0.png)
![image](https://user-images.githubusercontent.com/56427336/84818050-b8fc0480-afca-11ea-9660-bf071d2acaab.png)
We suspected that the legend of the pie chart makes the pie plot small, and for some reason, Bokeh needs to make the same width for the plots in all tabs.

This problem happened with google chrome, IE, Microsoft edge on multiple PC and macOS. However, one of our colleagues who used safari didn't meet this problem on his Macbook.

Changing plot_width and plot_height in Figure() didn't solve this problem. 

The normal plots should be like these:
![image](https://user-images.githubusercontent.com/56427336/84818503-74249d80-afcb-11ea-8a85-586d3723d0c2.png)
![image](https://user-images.githubusercontent.com/56427336/84818511-771f8e00-afcb-11ea-8500-b86b1a770c41.png)

**Comment by bryevdv** [comment] 2020-06-16 19:21
Hi @dylanzxc to have any hope of investigating this we will absolutely need a minimal, compete, reproducer. Ideally a a small pure-bokeh exemplar.

**Comment by dylanzxc** [comment] 2020-06-16 21:17
Hi here is the code that can reproduce the problem. Thank you.

```
import pandas as pd 
import math
from math import pi
from bokeh.plotting import Figure,show, figure
from bokeh.transform import cumsum
from bokeh.models import (Legend,LegendItem,Panel,Tabs)
from bokeh.io import output_notebook
output_notebook()


# figure 1
df ={'col': {0: 'Others',
  1: 'Abbott, Mr. Rossmore Edward',
  2: 'Abbott, Mrs. Stanton (Rosa Hunt)',
  3: 'Abelson, Mr. Samuel',
  4: 'Abelson, Mrs. Samuel (Hannah Wizosky)',
  5: 'Adahl, Mr. Mauritz Nils Martin',
  6: 'Adams, Mr. John',
  7: 'Ahlin, Mrs. Johan (Johanna Persdotter Larsson)',
  8: 'Aks, Mrs. Sam (Leah Rosen)',
  9: 'Albimona, Mr. Nassef Cassem'},
 'cnt': {0: 881, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 1, 7: 1, 8: 1, 9: 1},
 'pct': {0: 98.87766554433222,
  1: 0.11223344556677892,
  2: 0.11223344556677892,
  3: 0.11223344556677892,
  4: 0.11223344556677892,
  5: 0.11223344556677892,
  6: 0.11223344556677892,
  7: 0.11223344556677892,
  8: 0.11223344556677892,
  9: 0.11223344556677892}}
df = pd.DataFrame(df)
df["angle"] = df["cnt"] / df["cnt"].sum() * 2 * pi
fig = Figure(
    plot_width=450,
    plot_height=400,
    )
# If we change the length of the text in legend, all the plots will be wider
# df['col'] = df['col'].map(lambda x: x[0:10])
pie = fig.wedge(
    x=0,
    y=1,
    radius=0.9,
    start_angle=cumsum("angle", include_zero=True),
    end_angle=cumsum("angle"),
    line_color="white",
    source=df,
)

legend = Legend(items=[LegendItem(label=dict(field="col"), renderers=[pie])])
legend.label_text_font_size = "8pt"
fig.add_layout(legend, "right")
fig.axis.major_label_text_font_size = "0pt"
fig.axis.major_tick_line_color = None


#figure 2
wordcloud_dict = {'word': ['miss','mrs','william','john','master','henry','james','charles',
                           'george','thomas','mary','edward','anna','joseph','elizabeth',
                             'johan','frederick','richard','samuel','arthur','margaret',
                           'alfred','maria','alexander','peter', 'robert','leonard','andersson','ernest','karl'],
                 'cnt': [182,129,64,44,40,35,24,24,24,22,20,18,17,16,15,15,15,14,13,13,12,12,11,11,11,10,9,9,9,9]}
fig2 = figure(
    x_range=list(wordcloud_dict["word"]),
    plot_width=450,
    plot_height=400,
    title="Words Frequency",
    toolbar_location=None,
)
fig2.vbar(x="word", top="cnt", width=0.9, source=wordcloud_dict)

tabs = []
tabs.append(Panel(child=fig, title="figure1"))
tabs.append(Panel(child=fig2, title="figure2"))
tabs = Tabs(tabs=tabs)
show(tabs)
```

**Comment by bryevdv** [comment] 2020-06-16 21:59
OK I can repro in OSX/safari on current main branch. @mattpap any quick thoughts? What's odd to me is that the canvas sizes are correct, and I am not really sure what mechanism could couple the frame dimensions  on two different plots like  this.

**Comment by mattpap** [comment] 2020-06-16 22:10
This is by design. Tabs with plots are treated like grids just with stacked plots instead of them being laid out next to each other. I suppose this may be counter intuitive in some situation, so we may want to make this configurable. A workaround is to wrap your plots in a layout (like a column or a row), this will prevent axis alignment to take place.

**Comment by dylanzxc** [comment] 2020-06-17 00:51
Thank you for answering and help. The row() works for our case. Cheers.

**Comment by bryevdv** [comment] 2024-08-15 23:44
Given there is a reasonable approach to avoid this (use row, not grid) I will close this

**Closed by bryevdv** 2024-08-15 23:44 UTC
Labels: type: discussion, tag: component: bokehjs, tag: layout
