### ISSUE TITLE
[BUG]  export csv column order not retain 

### ISSUE THREAD

**Issue by iisri-vu** [bokeh/bokeh#12012] opened 2022-02-18 16:45 UTC
### Software versions
Bokeh 2.3.3.

In the example:   bokeh/examples/app/export_csv/

The order of the column input into dataframe or  ColumnDataSource does not retain when export to csv.
Problem is at:    const columns = Object.keys(source.data)

regards

### Browser name and version

Chrome, firefox

### Expected behavior

Expected behaviour:  Column order should be the same to input.

### Observed behavior

Column changes place.

### Example code

```Python
bokeh/examples/app/export_csv/
```

**Comment by bryevdv** [comment] 2022-02-18 18:23
@iisri-vu There is no inherent order of columns in a CDS. It's probably not impossible to make the example more sophisticated, and retain some specified order passed to the `CustomJS`, at the expense of simplicity. Are you interested to submit a PR to do that? If not, I am inclined to close this as `working as intended`

**Comment by mattpap** [comment] 2022-02-19 01:24
> `const columns = Object.keys(source.data)`

This is actually ordered, as JS objects are insertion ordered. The loss of order may happen at the protocol level, see similar issue #11963. This is fixed in PR #11960 and will be available in bokeh 3.0.

**Closed by mattpap** 2022-02-19 01:24 UTC
Labels: TRIAGE
