### ISSUE TITLE
Strange behaviour with bins on Histograms

### ISSUE THREAD

**Issue by jhroy** [bokeh/bokeh#4642] opened 2016-06-22 19:53 UTC
Hi!
Some bins are shown as having a much higher count number than expected in a histogram I'm trying to make. The bars in the 800-1600 range aren't supposed to be there. Values in that range are very few:
![fugace moment capture le 2016-06-22 a 15 43 45](https://cloud.githubusercontent.com/assets/1175329/16281066/92016c72-3890-11e6-8ace-4e12b2134f99.png)

The same behaviour appears to happen [on Bokeh's website too](http://bokeh.pydata.org/en/latest/docs/user_guide/charts.html#number-of-bins):
![fugace moment capture le 2016-06-22 a 15 44 06](https://cloud.githubusercontent.com/assets/1175329/16281101/bc511eaa-3890-11e6-9272-0c294e53e617.png)

Thanks for a tremendous tool! 😄

**Comment by bryevdv** [comment] 2016-06-22 20:12
I believe this to be duplicate of #3875, addressed by PR #3988, available in recent dev builds and the upcoming `0.12` release.

**Closed by bryevdv** 2016-06-22 20:12 UTC

**Comment by jhroy** [comment] 2016-06-22 20:17
Oh yes it is a duplicate. Sorry about that. I had not gone back this far when I searched the issues. Thanks for your reply!
