### ISSUE TITLE
[FEATURE]allow TextInput to respond to <Enter>

### ISSUE THREAD

**Issue by richardxdubois** [bokeh/bokeh#9567] opened 2020-01-08 16:07 UTC
TextInput only responds to on_change. My use case is to provide a text field that will dynamically load a python module; the idea is that the user can modify the module and get it reloaded by just hitting <Enter> in the TextInput box. With on_change, nothing happens on <Enter>.

 My workaround is to provide a second button that would explicitly reload.

I had some discussion in discourse about adding a property to TextInput that would respond to <Enter>. 

https://discourse.bokeh.org/t/textinput-on-change-behavior/2239

**Comment by bryevdv** [comment] 2020-01-17 19:58
I don't think there is any reasonable way to make this work with `on_change`, since it is not a change, and making it "work" dilutes the clear meaning and explanation of `on_change` with special cases. So my other idea was perhaps an `<enter>` event that text fields could emit that could be responded to with `on_event` or `js_on_event`. 

Thoughts @bokeh/dev ?

**Comment by mattpap** [comment] 2023-03-04 21:21
This was implemented in PR #12782. I will treat this issues as a duplicate of #12772.

**Closed by mattpap** 2023-03-04 21:21 UTC
Labels: type: discussion
