### ISSUE TITLE
[BUG] JSON encoder doesn't serialise datetime values

### ISSUE THREAD

**Issue by dylanjmcconnell** [bokeh/bokeh#12854] opened 2023-02-25 10:38 UTC
### Software versions

Python version      :  3.11.0 (main, Dec  6 2022, 14:29:27) [GCC 11.3.0]
IPython version     :  8.7.0
Tornado version     :  6.2
Bokeh version       :  3.0.3
BokehJS static path :  /home/{home}/.pyenv/versions/3.11.0/envs/analysis/lib/python3.11/site-packages/bokeh/server/static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Linux-5.19.0-32-generic-x86_64-with-glibc2.35

### Expected behavior

Expected `serialize_json` function (from [bokeh.core.json_encoder](https://docs.bokeh.org/en/latest/docs/reference/core/json_encoder.htm))  to convert datetime values to floating point milliseconds since epoch.

### Observed behavior

Returns a type error:

```python
TypeError: Object of type datetime is not JSON serializable
```

(also tried np.datetime64 - same error message, but with ... `Object of type datetime64...`)

### Example code

```Python
import numpy as np
from bokeh.core.json_encoder import serialize_json
data = dict(b=np.datetime64('2017-01-01'), a = np.arange(3))
print(serialize_json(data))
```

**Comment by dylanjmcconnell** [comment] 2023-02-25 10:41
FWIW - the example code posted above is straight from the [docs page](https://docs.bokeh.org/en/latest/docs/reference/core/json_encoder.html#bokeh.core.json_encoder.serialize_json), and is a good minimal working example (but not what I was actually doing)

**Comment by mattpap** [comment] 2023-02-25 12:37
This is a duplicate of issue #12574.

**Closed as completed by mattpap** 2023-02-25 12:37 UTC
Labels: reso: duplicate
