### ISSUE TITLE
DataTable widgets are not rendering within Tabs

### ISSUE THREAD

**Issue by jl45621** [bokeh/bokeh#3007] opened 2015-10-19 16:42 UTC
First off, I can't thank you guys enough for putting this brilliant piece of software together. I am a huge fan. Noticed a minor issue and wanted to report it. Please let me know if it's not actually an issue and I'm just using the library incorrectly. Thanks.

If you put seperate DataTables into tabs, only the active DataTable will render properly in the browser. Here is a screenshot of the initially active tab working properly:
![selection_030](https://cloud.githubusercontent.com/assets/11338165/10584074/53d36f30-765e-11e5-9dd6-436f578483db.png)
Here is a screenshot of the other tabs which don't render:
![selection_031](https://cloud.githubusercontent.com/assets/11338165/10584106/69fcc41e-765e-11e5-9365-88b1d933d9b4.png)
![selection_032](https://cloud.githubusercontent.com/assets/11338165/10584114/720db1b8-765e-11e5-9072-a74583189634.png)

Also, here is a notebook with a simple example
![selection_033](https://cloud.githubusercontent.com/assets/11338165/10584134/857cd4c2-765e-11e5-94c7-5749b22522bf.png)

**Comment by jl45621** [comment] 2015-10-22 18:26
@bryevdv @birdsarah  hey guys i tried to follow the submission guidelines as best i could, but this is my first time using github. how do i tag this issue appropriately with correct label? thanks

**Comment by bryevdv** [comment] 2015-10-22 18:34
@jl45621 setting tags is our responsibility :) Thanks for the report!

**Comment by bryevdv** [comment] 2015-10-22 18:34
ping @mattpap

**Comment by RobMulla** [comment] 2018-06-22 19:17
I know this is an old one, but I'm experiencing the same issue. Fixes itself after scrolling.

```
>>> import bokeh
>>> print(bokeh.__version__)
0.12.7
```

**Comment by jl45621** [comment] 2018-06-24 00:11
I think the way I fixed it was by avoiding tabs entirely. BTW -- It might have even been this issue or another one that I didn't post, but at one point I got fed up and just bit the bullet of unproductivity for a week or so and made my own website framework instead. Here's how I would recommend it: Python App running your code, but following implementation at https://github.com/0rpc/zerorpc-python  ... then you would also need to launch a node JS server. (Anything that runs node is fine, I chose meteor.com, but I think you can do this with a million diff JS frameworks) This node instance communicates via zerorpc as well. The bet is that if you can figure out how to code in python, you should be able to figure out how to do some simple JS as well. And then this opens the door to a fully customizable HTML website. You want tables displayed? Use datatables.net . You want drag and drop ability? Use any of the numerous JS libs out there. You want to play friggin music and use the blinker HTML tag? Eff it. It's your site, you can do whatever you want with it. You worried about CSS/HTML design? Don't be. Goto wrapboostratp.com and buy the one you want for like 20-40 bucks and use it forever.  In my case, I was trying to use bokeh to display the data I would generate within python (usually starting via Jupyter and then migrating to it's own .py file). I started with bokeh but left back when it started requiring a server in the middle. I figured if we are going to have another hop between the web-browser and the data in memory in my python instance, I might as well commit to understanding that hop. So, I eventually outgrew bokeh and did the above work and I highly recommend it.

**Comment by jl45621** [comment] 2018-06-24 00:12
ProTip: Combine python multiprocessing.Queue module with zerorpc-python, so you can do interesting work in the background at the same time

**Comment by bryevdv** [comment] 2018-10-09 18:39
I believe this is a dupe of #7120, that issue has more discussion so closing this one in favor of it.

**Closed by bryevdv** 2018-10-09 18:39 UTC
Labels: tag: component: bokehjs, type: bug
