### ISSUE TITLE
vbar plots are empty when using log-scale

### ISSUE THREAD

**Issue by Gaudi19** [bokeh/bokeh#6671] opened 2017-07-25 08:03 UTC
#### Description 
Hi everybody, 
After updating from bokeh 0.12.5 to 0.12.6, I have encountered the issue, that vbar-plots are not shown anymore, if the axis-scale is set to logarithmic. This happens both, in browser as well as when exporting the plot via 'export_png()'.
Manually setting the y_range does not change this behaviour either.  

Maybe I have overseen an existing Issue, in this case I'm apologize for taking your time in advance. 

cheers 
Gaudenz
#### Packages
I've used following packages for the script below:
python: 2.7.13
bokeh: 0.12.6
browser: Firefox 54.0.1
IDE: PyCharm Community 2017.1.1

#### Code Example
```
from bokeh.plotting import figure, show
from bokeh.layouts import Row

y_data = np.array([1, 5, 10, 50, 100, 500, 1000])
x_data = np.array([1, 2, 3, 4, 5, 6, 7])

# Plotting with Log-Axis
plot_log = figure(width=400, height=400, y_axis_type="log", y_range = [10 ** 0, 10 ** 3])
plot_log.vbar(x=x_data, width=0.8, bottom=0, top=y_data)

# Plotting with Linear-Axis
plot_lin = figure(width=400, height=400, y_axis_type="linear", y_range = [10 ** 0, 10 ** 3])
plot_lin.vbar(x=x_data, width=0.8, bottom=0, top=y_data)

show(Row(plot_log, plot_lin))
```
#### Stack traceback and/or browser JavaScript console output
The console output of the browser seems to be fine for this example, no error is raised in python. 
```
[bokeh] setting log level to: 'info'  bokeh-0.12.6.min.js:2:9217
[bokeh] LogTickFormatter not configured with a ticker, using default base of 10 (labels will be incorrect if ticker base is not 10) bokeh-0.12.6.min.js:26:6986
```

#### Screenshots
![plot_result](https://user-images.githubusercontent.com/14757659/28561748-d210f4a4-711f-11e7-9a12-37037b998add.PNG)

**Comment by heatherbshapiro** [comment] 2017-07-25 16:53
I don't think you can set the bottom for plot_log to be 0, as there is no log(0). If you set it to 0.01 or something similar, you should see the graph. If you change the bottom in the below code, you will get the graphs below.

`plot_log = figure(width=400, height=400, y_axis_type="log", y_range = [10 ** 0, 10 ** 3])
plot_log.vbar(x=x_data, width=0.8, bottom=0.01, top=y_data)`

![log](https://user-images.githubusercontent.com/8547756/28583691-11308204-7138-11e7-9c09-5428a0caa6b4.PNG)

**Comment by bryevdv** [comment] 2017-07-25 17:04
This is a dupe of https://github.com/bokeh/bokeh/issues/6536 (which previously did not have a good title, I have updated it to be more descriptive)

**Closed by bryevdv** 2017-07-25 17:04 UTC
