### ISSUE TITLE
[BUG] Hover disapearing in full screen mode

### ISSUE THREAD

**Issue by adikte** [bokeh/bokeh#14140] opened 2024-11-05 17:19 UTC
### Software versions

Python version : 3.12
Bokeh >3.3.4
Operating system : windows 11

### Browser name and version

Mozilla 131

### Expected behavior

Hover of embedded graphs are disappearing in full screen mode since the version 3.3 of bokeh.
I tested 3.1.1 ==> works fine 
            3.2.2 ==> works fine 
            3.3.4 and above ==> hover disappearing in full screen mode
From what i understand the html object <div class="bk-Tooltip"> is created outside of the "bk-figure" since the version 3.3. Because of that .requestFullscreen() doesn't put the element on the screen.

### Observed behavior

The hover is not visible when the plot is in fullscreen

### Example code

```Python
from bokeh.plotting import figure, output_file, save
from bokeh.embed import components

# Créer un fichier HTML pour l'export
output_file("C:/users/adrien/desktop/embedded_graph.html")

# Créer un graphique simple
p = figure(title="Graphique avec Hover", x_axis_label='X', y_axis_label='Y', tools="hover", tooltips="@x, @y")

# Ajouter des données
p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=2, legend_label="Ligne", line_color="blue")
p.circle([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], size=10, color="red", alpha=0.5)

# Obtenir le script et le div pour l'intégration
script, div = components(p)

# Générer le fichier HTML
with open("C:/users/adrien/desktop/embedded_graph.html", "w") as f:
    f.write(f"""
    <html lang="fr">
    <head>
        <meta charset="UTF-8">
        <title>Graphique Bokeh</title>
        <link rel="stylesheet" href="https://cdn.bokeh.org/bokeh/release/bokeh-3.3.4.min.css" type="text/css" />
        <script type="text/javascript" src="https://cdn.bokeh.org/bokeh/release/bokeh-3.3.4.min.js"></script>
        <style>
            body {{
                display: flex;
                flex-direction: column;
                align-items: center;
            }}
            #myPlot {{
                width: 100%;
                height: 500px;
                margin-bottom: 10px;  /* Espace entre le graphique et le bouton */
            }}
            .fullscreen-button {{
                margin: 10px;
                padding: 10px 20px;
                font-size: 16px;
                cursor: pointer;
            }}
        </style>
        <script>
        function showFullScreen(id_target) {{
            const target = document.getElementById(id_target);
    
            if (document.fullscreenEnabled) {{
                target.requestFullscreen()
            }} else if (document.webkitFullscreenEnabled) {{
                target.webkitRequestFullScreen();
            }} else {{
                window.alert("Votre navigateur est trop ancien pour assurer un affichage plein écran.");
                }}
            }};
    
        </script>
    </head>
    <body>
        <button class="fullscreen-button" onclick="showFullScreen('myPlot')">Plein Écran</button>
        <div id="myPlot">{div}</div>
        {script}
    </body>
    </html>
    """)
```

**Comment by mattpap** [comment] 2024-11-06 20:37
This is a duplicate of issue #13885.

**Closed as completed by mattpap** 2024-11-06 20:37 UTC
Labels: reso: duplicate
