### ISSUE TITLE
Removing a callback twice (or after it's already been run) when several producers call add_next_tick_callback()

### ISSUE THREAD

**Issue by stark71** [bokeh/bokeh#7615] opened 2018-03-10 15:31 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
* bokeh (0.12.14)
* Python 3.6.3
* Chromium Version 64.0.3282.167 (Official Build)
  It happens with all browsers.
* Ubuntu 17.10

#### Description of expected behavior and the observed behavior
- I have several threads listening for updates/changes
- When there is an update, the listening thread calls add_next_tick_callback with partial(function_that_streams_the_change, change_value)
Eventually I get an error: "ValueError: Removing a callback twice (or after it's already been run)"

I would expect add_next_tick_callback to queue updates even if the callback uses the same update function (with distinct args)

#### Complete, minimal, self-contained example code that reproduces the issue

```
from functools import partial
from random import random
from bokeh.plotting import figure, curdoc
from bokeh.plotting import ColumnDataSource
import threading
from bokeh.embed import server_session
import time

doc = curdoc()
source = ColumnDataSource(dict(x=[1, 2], y=[1, 2]))
figure = figure()
figure.circle(x="x", y="y", source=source)

layout = figure
doc.add_root(figure)
server_session(layout, doc.session_context.id)

for i in range(10):
    def producer():
        while True:
            time.sleep(random() * 0.3)

            def stream():
                stream_data = dict(x=[random() * 5], y=[random() * 5])
                #print("producer %s, stream=%s" % (threading.current_thread().getName(), stream_data))
                source.stream(stream_data)
            doc.add_next_tick_callback(partial(stream))

    threading.Thread(target=producer).start()
```

#### Stack traceback and/or browser JavaScript console output
2018-03-10 16:26:43,905 Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fb2d04007b8>)
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.6/site-packages/tornado/ioloop.py", line 760, in _run_callback
    ret = callback()
  File "/home/user/.local/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/bokeh/util/tornado.py", line 135, in wrapper
    self.remove_next_tick_callback(callback)
  File "/home/user/.local/lib/python3.6/site-packages/bokeh/util/tornado.py", line 161, in remove_next_tick_callback
    self._remove(callback, self._next_tick_callbacks)
  File "/home/user/.local/lib/python3.6/site-packages/bokeh/util/tornado.py", line 156, in _remove
    self._error_on_double_remove(callback, callbacks)
  File "/home/user/.local/lib/python3.6/site-packages/bokeh/util/tornado.py", line 118, in _error_on_double_remove
    raise ValueError("Removing a callback twice (or after it's already been run)")
ValueError: Removing a callback twice (or after it's already been run)

No error in browser JavaScript console

**Comment by bryevdv** [comment] 2018-03-12 15:49
dupe of #7219

**Closed by bryevdv** 2018-03-12 15:49 UTC
