### ISSUE TITLE
[BUG] Poor resolution of Bokeh plot when displayed on web using FLASK

### ISSUE THREAD

**Issue by ncundeti** [bokeh/bokeh#10120] opened 2020-06-04 21:57 UTC
This is my first time posting issue on GIT, please bear with me. I was able to make a web based bokeh plot using flask and html, but the plot on the web page appears to have lower resolution (example Screenshot 1 - of original code) and reduced clarity compared to the one plotted via "show(fig) in Bokeh" (example Screenshot 2 - of original code). I have just upgraded my bokeh from 1.2.0 to 2.0.2 hoping this would change but, no luck.

google chrome: 83.0.4103.61 (64-bit)
python 3.7
bokeh 2.0.2

Below is my minimal code where i have plotted only one group please note: this is slightly different from the code in screenshot which has two groups
app.py
```
import numpy as np
from bokeh.plotting import figure
import pandas as pd
from flask import Flask, render_template, request, redirect
from bokeh.embed import components
from scipy.optimize import curve_fit
from random import randint
from bokeh.io import show

f_12 = pd.Series(['f1', 'f2'])
f_12 = f_12.repeat(50)

sample_df = pd.DataFrame(data={'x': [randint(100, 1000) for p in range(0, 100)]
                          ,'y': np.random.random(100)
                          ,'filter_12': f_12
                          , 'group': [randint(1, 2) for p in range(0, 100)]
                         })

f12_list = sample_df['filter_12'].unique().tolist()
group_list = sample_df['group'].unique().tolist()

def compute( f_12, group_f):
        small_df = sample_df.loc[(sample_df['filter_12'] == f_12) & (sample_df['group'] == group_f) ]   
        x = small_df['x'].values
        y = small_df['y'].values
        fig=figure(x_axis_label="x",y_axis_label="y")

        popt, pcov = curve_fit(lambda fx,a,b: a+b*np.log(fx),  x,  y)
        #popt, pcov = curve_fit(func,  x,  y)
        y_cal = popt[1]*np.log(x) + popt[0]       
        fig.line(x, y_cal, color='green', legend_label="Green_Line_fit")
        fig.circle(x, y, color='green', legend_label='A')

        return fig

app = Flask(__name__, template_folder='templates')
# Index page
@app.route('/')
def main():
   return redirect('/index')

@app.route('/index', methods=['GET'])
def index():
    return render_template('index.html', f12_list=f12_list, group_list=group_list)


@app.route('/plot', methods=['POST'])
def results():
    if request.method == 'POST':
        f_12 = request.form.get('f_12')
        if f_12 == None:
            f_12 = "f1"
        group_f = request.form.get('selected_group')
        if group_f == None:
            group_f = 1        
        plot = compute(f_12, int(group_f))
        show(plot)
                # Embed plot into HTML via Flask Render
        script, div = components(plot)
        return render_template("index.html", script=script, div=div, f12_list=f12_list, group_list=group_list)

if __name__ == '__main__':
    app.run(debug=True)

```
index.html
```
<html>
<head>
<meta charset="utf-8">
<link href="https://cdn.bokeh.org/bokeh/release/bokeh-2.0.2.min.css" rel="stylesheet" type="text/css">
<link href="http://cdn.pydata.org/bokeh/release/bokeh-widgets-2.0.2.min.css" rel="stylesheet" type="text/css">

</head>
<body>
<H1>Chart</H1>

<form action="/plot" method="POST">
<select name="f_12" id="f_12">
    {% for f12 in f12_list %}
        {% if f12 == f_12 %}
            <option selected value="{{ f12 }}">{{ f12 }}</option> 
        {% else %} 
            <option value="{{ f12 }}">{{ f12 }}</option> 
        {% endif %}
    {% endfor %}
</select>
<select name="selected_group" id="selected_group">
    {% for group in group_list %}
        {% if group == selected_group %}
            <option selected value="{{ group }}">{{ group }}</option> 
        {% else %} 
            <option value="{{ group }}">{{ group }}</option> 
        {% endif %}
    {% endfor %}
</select>
<input type="submit">
</form>
<div class="bokeh">
{{ div|safe }}
</div>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-2.0.2.min.js"></script>
<script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-2.0.2.min.js"></script>

{{ script|safe }}

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

</body>
</html>


```
screenshot 1
![1](https://user-images.githubusercontent.com/66444731/83814251-985bb280-a68c-11ea-8b81-f64886c491e0.PNG)

screenshot 2
![2](https://user-images.githubusercontent.com/66444731/83814255-985bb280-a68c-11ea-9c65-6f937bf3cedc.PNG)

**Comment by mattpap** [comment] 2020-06-04 22:47
This shouldn't happen and I can't reproduce this, at least on Linux. We will need some more information:

- is this reproducible in other browsers, especially Firefox?
- what's the platform (I presume Windows?)
- are there any warnings/errors etc. in JS console
- what's the output (in JS console) of:
```js
window.devicePixelRatio
```
and
```js
Bokeh.index[3170].canvas.pixel_ratio // replace 3170 with the actual ID (Chrome will auto-complete it for you)
```

**Comment by ncundeti** [comment] 2020-06-05 02:50
@mattpap  thanks for looking. Yes, i am using windows 10
output of  "window.devicePixelRatio" is 1 on js console. 
could you tell me how to get the "actual id" ? Bokeh.index[3170].canvas.pixel_ratio ? On JS console i see a message "Bokeh" is not defined

**Comment by ncundeti** [comment] 2020-06-05 16:34
an update: if i display the same plot on my laptop instead of monitor, the resolution is good. So i think the problem is with resolution of my monitor

**Comment by bryevdv** [comment] 2021-06-10 16:19
closing based on the above comment and also staleness

**Closed by bryevdv** 2021-06-10 16:19 UTC
Labels: NEEDS MORE INFO, type: discussion
