### ISSUE TITLE
Bug Report? DatePicker widget errors on changing dates

### ISSUE THREAD

**Issue by jbrambleDC** [bokeh/bokeh#4204] opened 2016-04-21 00:36 UTC
I am running a bokeh server app on 0.11.1. I am creating a DatePicker widget as follows:
```python
beginning = DatePicker(title="Begin Date", min_date=datetime(2014,11,1),
                       max_date=datetime.now(),
                       value=datetime(datetime.now().year,1,1)
                       )
```

I am running the app as follows:
`bokeh serve --show usage_app.py`

The DatePicker loads properly and displays as expected in the app. I have tested the default value, and it properly sets a default value of 2016-01-01, I have tried it using strings and datetime objects, both of which work. The issue is on changing dates. When I select a new date or try to change the month on the calendar display it immediately errors out and changes to a different, more primitive display.

<img width="321" alt="screen shot 2016-04-20 at 8 33 46 pm" src="https://cloud.githubusercontent.com/assets/6984748/14694543/4efce17a-0737-11e6-9275-1661b1c88b15.png">

In order to be exhaustive, I have tried declaring the object with and without mind and max dates. and I still reproduce the same error.

Here is the stack trace:

```
ERROR:bokeh.server.protocol.server_handler:error handling message Message 'PATCH-DOC' (revision 1): ValueError('expected a date, string or timestamp, got {}',)
DEBUG:bokeh.server.protocol.server_handler:  message header {u'msgid': u'6FA6441007BD454A9A19EB7098C41857', u'msgtype': u'PATCH-DOC'} content {u'references': [], u'events': [{u'new': {}, u'kind': u'ModelChanged', u'model': {u'type': u'DatePicker', u'id': u'538ca18f-efd5-4907-b770-c891f375f13a'}, u'attr': u'value'}]}
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/bokeh/server/protocol/server_handler.py", line 38, in handle
    work = yield handler(message, connection)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1008, in run
    value = future.result()
  File "/Library/Python/2.7/site-packages/tornado/concurrent.py", line 232, in result
    raise_exc_info(self._exc_info)
  File "/Library/Python/2.7/site-packages/tornado/gen.py", line 1017, in run
    yielded = self.gen.send(value)
  File "/usr/local/lib/python2.7/site-packages/bokeh/server/session.py", line 42, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "/usr/local/lib/python2.7/site-packages/bokeh/server/session.py", line 212, in _handle_patch
    message.apply_to_document(self.document)
  File "/usr/local/lib/python2.7/site-packages/bokeh/server/protocol/messages/patch_doc.py", line 85, in apply_to_document
    doc.apply_json_patch(self.content)
  File "/usr/local/lib/python2.7/site-packages/bokeh/document.py", line 862, in apply_json_patch
    patched_obj.set_from_json(attr, value, models=references)
  File "/usr/local/lib/python2.7/site-packages/bokeh/core/properties.py", line 733, in set_from_json
    prop.set_from_json(self, json, models)
  File "/usr/local/lib/python2.7/site-packages/bokeh/core/properties.py", line 371, in set_from_json
    models)
  File "/usr/local/lib/python2.7/site-packages/bokeh/core/properties.py", line 323, in set_from_json
    return self.__set__(obj, json)
  File "/usr/local/lib/python2.7/site-packages/bokeh/core/properties.py", line 453, in __set__
    value = self.descriptor.prepare_value(obj.__class__, self.name, value)
  File "/usr/local/lib/python2.7/site-packages/bokeh/core/properties.py", line 272, in prepare_value
    raise e
ValueError: expected a date, string or timestamp, got {}
```

My apologies if I am missing something with how to use this object. I was following the 0.11 reference on widgets.

**Comment by jbrambleDC** [comment] 2016-04-22 14:13
anybody else experience this?

**Comment by Shilpi27** [comment] 2016-04-25 08:18
Even I observe the same issue.

**Comment by canavandl** [comment] 2016-04-30 01:07
It appears that the bk- prefix is dropped on the click interaction, so that the css selectors don't match up.

before:
<img width="937" alt="screen shot 2016-04-29 at 8 05 13 pm" src="https://cloud.githubusercontent.com/assets/2198981/14932962/d378a05a-0e45-11e6-91ab-0b77ed8c6f67.png">

after:
<img width="934" alt="screen shot 2016-04-29 at 8 05 25 pm" src="https://cloud.githubusercontent.com/assets/2198981/14932965/dbf8872c-0e45-11e6-8b6d-30a8acfb3f4a.png">

**Comment by VeenitShah** [comment] 2016-05-17 19:32
I get the same error.

**Comment by savadhani** [comment] 2016-05-27 09:46
I too have the same issue :(

**Comment by bryevdv** [comment] 2016-05-27 14:41
Can someone post a complete minimal example that can be run to investigate this?

**Comment by jbrambleDC** [comment] 2016-05-27 15:32
@bryevdv I can gladly make one. I am traveling for a bit, and if no one has knocked this out on my return, I'll post one.

**Comment by bryevdv** [comment] 2016-05-27 15:34
@jbrambleDC I went ahead and made one. A pretty trivial change gets things working:

```
diff --git a/bokehjs/src/coffee/models/widgets/date_picker.coffee b/bokehjs/src/coffee/models/widgets/date_picker.coffee
index c5aab64..7b620d6 100644
--- a/bokehjs/src/coffee/models/widgets/date_picker.coffee
+++ b/bokehjs/src/coffee/models/widgets/date_picker.coffee
@@ -25,7 +25,8 @@ class DatePickerView extends BokehView
     return @
 
   onSelect: (dateText, ui) =>
-    @mset('value', new Date(dateText))
+    d = new Date(dateText)
+    @mset('value', d.toString())
     @mget('callback')?.execute(@model)
 
 class DatePicker extends InputWidget.Model
```

However, I still see the CSS styling disappear, and about that I have no idea. `render` is only getting called once, so it's a mystery. Any ideas @brendancol ?

**Comment by bryevdv** [comment] 2016-05-27 16:06
OK here's another diff that I think would be a pretty great improvement, it attaches the date picker to an input and only pops up the dialog when the input is interacted with:
```
diff --git a/bokehjs/src/coffee/models/widgets/date_picker.coffee b/bokehjs/src/coffee/models/widgets/date_picker.coffee
index c5aab64..788eb56 100644
--- a/bokehjs/src/coffee/models/widgets/date_picker.coffee
+++ b/bokehjs/src/coffee/models/widgets/date_picker.coffee
@@ -15,17 +15,19 @@ class DatePickerView extends BokehView
   render: () ->
     @$el.empty()
     $label = $('<label>').text(@mget("title"))
-    $datepicker = $("<div>").datepicker({
+    $input = $('<input type="text">')
+    $datepicker = $input.datepicker({
       defaultDate: new Date(@mget('value'))
       minDate: if @mget('min_date')? then new Date(@mget('min_date')) else null
       maxDate: if @mget('max_date')? then new Date(@mget('max_date')) else null
       onSelect: @onSelect
     })
-    @$el.append([$label, $datepicker])
+    @$el.append([$label, $input])
     return @
 
   onSelect: (dateText, ui) =>
-    @mset('value', new Date(dateText))
+    d = new Date(dateText)
+    @mset('value', d.toString())
     @mget('callback')?.execute(@model)
 
 class DatePicker extends InputWidget.Model

```
However, it is currently unsettled with these changes:

<img width="290" alt="screen shot 2016-05-27 at 11 04 54 am" src="https://cloud.githubusercontent.com/assets/1078448/15613776/e39f67f0-23fa-11e6-8625-bc209cb2b571.png">

@bokeh/dev @mattpap @brendancol if anyone knows how to make the styling apply I think this can be fixed and closed. With date range slider not working AFAIK we have to get at least this working for `0.12` (I've updated milestone)

**Comment by birdsarah** [comment] 2016-05-28 01:31
I believe that the source of the styling issue is because of the date picker initialization.

We went through a process of prefixing everything bokeh with bk- 

That means that the css in our widgets css is, for example bk-ui-widget-header.

I see a brief flash of the correct styling and then no styling. I believe what's happening is that we load it with the correct styling but then the js that drives the datepicker reverts the css classes to not having a bk- prefix.

HTH

**Comment by savadhani** [comment] 2016-05-30 03:54
@bryevdv  Sir, is my code expected to work if i go ahead and make those changes in the coffee script or is there any other compiling process process for changes to reflect within bokeh functionality? I tried running the same example code of yours with the changes to the date_picker.coffee script, but i got the same error of `expected a date, string or timestamp, got {}`

**Comment by bryevdv** [comment] 2016-05-31 02:59
@savadhani The CoffeeScript has to be compiled to JavaScript. Then you have to make sure to use the local resources you built, instead of the released version of BokehJS from CDN. There's instructions for all of that in the developer guide, but the diffs above were really provided for the benefit of anyone who would like to help fix the issue, rather than something that would be easily useful to general users. 

@birdsarah I suspected something like that, but I have no idea how to fix. Any ideas?

**Comment by savadhani** [comment] 2016-05-31 03:04
Oh alright!  Thanks a lot @bryevdv.  May I know when Bokeh update is going to be released?

**Comment by brendancol** [comment] 2016-06-01 20:51
@mattpap Notice the `ui-datepicker-div` below.  Does this need to be inside of `bk-root`?
<img width="755" alt="screen shot 2016-06-01 at 3 12 39 pm" src="https://cloud.githubusercontent.com/assets/433221/15725233/8cf6886a-2810-11e6-8921-54271e8b65ac.png">

**Comment by bryevdv** [comment] 2016-06-01 21:20
As an experiment I tried putting the date picker div in a `bk-root` div by hand and it just made the date picker disappear

**Comment by brendancol** [comment] 2016-06-01 21:21
yeah I think it is just a css prefix issue.  I'm experimenting now with calling build_views on the datepicker element

**Comment by bryevdv** [comment] 2016-06-01 21:24
copying the div into the existing `bk-root` makes it permanently show up, but also without styling

**Comment by birdsarah** [comment] 2016-06-01 21:30
@brendan, @bryevdv - it's not that.

If you add a style sheet that also has `ui-widget-header` along with the `bk-ui-widget-header` etc. then the styling will work I believe.

The datepicker is initially initialized with the bk- prefixes but then it seems to re-initialize itself and remove the bk- prefixes. I'll try and work up a patch tomorrow.

**Comment by bryevdv** [comment] 2016-06-01 21:34
@birdsarah just to be clear, with patch above, that attaches the date picker to an `input` (which seems much better) it does not even ever get initialized to `bk-`prefixed.

**Comment by bryevdv** [comment] 2016-06-01 21:37
I'll also add that adding the `bk-` prefix to all the divs and classes the date picker creates, by hand in the browser, has no effect.

**Comment by birdsarah** [comment] 2016-06-01 23:53
@bryevdv, I have an email from you that says:

> I'll also add that adding the bk- prefix to all the divs and classes the date picker creates, by hand in the browser, has no effect. 

I can't see that comment. But if that's still true, it's definitely surprising, and I'll look into it tomorrow.

**Comment by brendancol** [comment] 2016-06-02 14:37
@birdsarah Ah ok thanks.

**Comment by brendancol** [comment] 2016-06-03 23:05
@birdsarah hey any luck with this one?  I can help test after you look into it.

**Comment by bryevdv** [comment] 2016-06-13 23:57
Ok, I made #4489 which at least makes things work with an input that shows the selected date, and also has the date correctly available to a server callback. The date picker is still not styled, but we should merge this before `0.12` regardless.

**Comment by bryevdv** [comment] 2016-06-14 03:13
@jbrambleDC just  heads up what will probably happen for `0.12` is that #4489 gets merged as-is. That will provide a functioning, but not well-styled date picker.

**Comment by jbrambleDC** [comment] 2016-06-14 03:36
Should we close this issue post merge and then make a new issue for styling? or leave open? @bryevdv

**Comment by bryevdv** [comment] 2016-06-14 18:17
I'll open a new issue

**Closed by bryevdv** 2016-06-14 18:17 UTC
Labels: reso: completed, type: bug

**Comment by xexiyong** [comment] 2017-09-22 07:28
once the value of one DataPicker changed, another DataPicker appears.Anyone else encounter this case?

**Comment by bryevdv** [comment] 2017-09-22 12:44
@xexiyong I’ve never seen anything like that. In any case please open a new different issue with all the requested information especially full code to reproduce.
