### ISSUE TITLE
Bokeh 0.12 not displaying figures in Jupyter notebook

### ISSUE THREAD

**Issue by esvhd** [bokeh/bokeh#4719] opened 2016-06-30 22:42 UTC
Upgraded to version 0.12 earlier, plus Anaconda 4.1. For some reason `Bokeh` doesn't show figures embedded in notebooks anymore. However, `output_file()` does work. 

Environment: 
MacOS, Anaconda 4.1, Python 3.5.1, notebook server 4.2.1. See screen below.

<img width="700" alt="screen shot 2016-06-30 at 23 34 12" src="https://cloud.githubusercontent.com/assets/7330385/16506640/ab9c1b64-3f1b-11e6-8e91-6ed3b28feafc.png">

Used an example on the web for testing. 

```python
%matplotlib inline
from bokeh.plotting import figure, show, output_notebook
from bokeh.sampledata.iris import flowers

output_notebook()

colormap = {'setosa': 'red', 'versicolor': 'green', 'virginica': 'blue'}
colors = [colormap[x] for x in flowers['species']]

p = figure(title = "Iris Morphology")
p.xaxis.axis_label = 'Petal Length'
p.yaxis.axis_label = 'Petal Width'

p.circle(flowers["petal_length"], flowers["petal_width"],
         color=colors, fill_alpha=0.2, size=10)

# output_file("iris.html", title="iris.py example")

show(p)
```

The result I had was: 

<img width="724" alt="screen shot 2016-06-30 at 23 33 58" src="https://cloud.githubusercontent.com/assets/7330385/16506709/22d5eec6-3f1c-11e6-9f1c-e744a0557a77.png">

Did anything change in the way `Bokeh` shows figures in notebook? I checked the docs but didn't see anything new. 

Am I missing something here? 

Thanks.

**Comment by bryevdv** [comment] 2016-07-01 16:24
I believe this is a dupe of #3639

**Closed by bryevdv** 2016-07-01 16:24 UTC

**Comment by RenatoBMLR** [comment] 2018-10-31 01:11
any updates? I'm still having this issue, actually I'm running it in a Kaggle kernel..
