### ISSUE TITLE
Cannot Edit DataTable Elements

### ISSUE THREAD

**Issue by mccarthyryanc** [bokeh/bokeh#7407] opened 2018-01-12 21:40 UTC
Python 3.6 with Bokeh 0.12.13, installed via conda:
```bash
conda create -n bokeh-env bokeh python=3.6 -c conda-forge
```
Here is `main.py`:
```python
from bokeh.models import ColumnDataSource
from bokeh.plotting import curdoc
from bokeh.layouts import layout
from bokeh.models.widgets import TableColumn, DataTable, IntEditor

source = ColumnDataSource(data=dict(numbers=range(10)))

columns = [
    TableColumn(field="numbers", title="Nums", editor=IntEditor()),
]
data_table = DataTable(source=source, columns=columns, width=400,
                       height=400, editable=True, selectable=True)

curdoc().add_root(data_table)
```

When double clicking table element I get the following error:
![selection_113](https://user-images.githubusercontent.com/997120/34896282-0cdfc538-f79e-11e7-971a-2adb1a861d35.png)

Same error in both Firefox and Chrome.

**Comment by mattpap** [comment] 2018-01-12 21:59
This is a duplicate of #7304. The fix will be available in bokeh 0.12.14.

**Closed by mattpap** 2018-01-12 21:59 UTC

**Comment by isabelhurley** [comment] 2018-02-27 17:07
Running the above code with Bokeh 0.12.14 and Python 3.6, I'm still unable to edit cells. Double clicking will delete the cell contents but I can't then replace them.

**Comment by bryevdv** [comment] 2018-02-27 17:32
@isabelhurley I can't reproduce this:

![screenflow](https://user-images.githubusercontent.com/1078448/36744210-128b479c-1ba1-11e8-9b14-c5dc07124e43.gif)


Please open a new issue with complete information (versions, platform, browser, etc) and code to reproduce.
