### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yvechang** [bokeh/bokeh#11160] opened 2021-04-12 00:03 UTC
### FOLLOW THESE INSTRUCTIONS CAREFULLY

*ISSUES THAT DO NOT CONTAIN NECESSARY INFORMATION MAY BE CLOSED, IMMEDIATELY*

The issue tracker is NOT the place for general support. For questions and technical assistance, come join the [Bokeh  Project Discourse](https://discourse.bokeh.org).

For defects or deficiencies, please provide *ALL OF THE FOLLOWING*:

#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
bokeh 2.3.0
Django 2.2
python 3.8.0
The version of the notebook server is: 5.7.8，Python 3.7.3
OS Win 10
browser: Chrome 89.0.4389.82 

#### Description of expected behavior and the observed behavior
My expectation is  embeding a dynamically changing layout into html file., and  the data of this dynamically change plot is periodically updateplot from a postgresql database. My web server environment is Django+Bokeh. 

I think "django_embed" example might be very useful for my purpose. However I had the following trouble.

#### Complete, minimal, self-contained example code that reproduces the issue
My installing steps is as follows,
1. Build a new project from Eclipse.
2. Add each folder and files as "django_embed" example.
3. Run python manage.py runserver 0.0.0.0:8000 the server starts without any issues. 
4. When I then go to any of the app links:
http://127.0.0.1:8000/shape_viewer, http://127.0.0.1:8000/sea_surface, or http://127.0.0.1:8000/sea_surface_with_template
The tab says: '500 Internal Server Error Exception inside application. Daphne'
```
# code goes here between backticks

```

#### Stack traceback and/or browser JavaScript console output
Exception inside application: 'DocConsumer' object has no attribute 'scope'
Traceback (most recent call last):
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\channels\routing.py", line 71, in __call__
    return await application(scope, receive, send)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\channels\sessions.py", line 47, in __call__
    return await self.inner(dict(scope, cookies=cookies), receive, send)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\channels\sessions.py", line 254, in __call__
    return await self.inner(wrapper.scope, receive, wrapper.send)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\channels\auth.py", line 181, in __call__
    return await super().__call__(scope, receive, send)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\channels\middleware.py", line 26, in __call__
    return await self.inner(scope, receive, send)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\channels\routing.py", line 150, in __call__
    return await application(
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\asgiref\compatibility.py", line 33, in new_application
    instance = application(scope)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\bokeh\server\django\consumers.py", line 103, in __init__
    kwargs = self.scope["url_route"]["kwargs"]
AttributeError: 'DocConsumer' object has no attribute 'scope'
HTTP GET /shape_viewer 500 [0.72, 127.0.0.1:51442]

**Comment by bryevdv** [comment] 2021-04-12 00:03
dupe of https://github.com/bokeh/bokeh/issues/10800

**Closed by bryevdv** 2021-04-12 00:03 UTC
Labels: TRIAGE

**Comment by yvechang** [comment] 2021-04-12 00:26
Mattpap commented on 29 Dec 2020
"Django support in bokeh was designed for and tested with django 2.x. We would like to upgrade to 3.x, but we don't have resources for this currently." However, my django is 2.2, but the error still happens!

**Comment by bryevdv** [comment] 2021-04-12 00:45
My mistake, this is actually a dupe of https://github.com/bokeh/bokeh/issues/11148

**Comment by bryevdv** [comment] 2021-04-12 00:47
@yvechang you will also need to downgrade your Bokeh version to one known to work, I think 2.0.2 tho perhaps 2.1 may work. The reality is that there is not currently anyone maintaining django integration.

**Comment by yvechang** [comment] 2021-04-12 07:51
@bryevdv I had tried the suggestions of [#11148](https://github.com/bokeh/bokeh/issues/11148), and the following errors occurred.
-----------------------------------------------------
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "c:\users\yvechang\appdata\local\programs\python\python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "c:\users\yvechang\appdata\local\programs\python\python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\django\apps\config.py", line 255, in create
    return app_config_class(app_name, app_module)
  File "C:\Users\yvechang\webapps\virtualenv\django_embed\lib\site-packages\django\apps\config.py", line 38, in __init__
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: The app label 'bokeh.server.django' is not a valid Python identifier.
---------------------------------------------------
My current environment is:
1. Django 3.2
2. Bokek 2.02
3. panel 0.11.1
4. django-param 0.1.10

Maybe I missed something like:
1. I had Replace line 41 in site-packages/bokeh/server/django/apps.py by:
    name = 'bokeh.server.django'
    label = 'bokeh_server_django'
   But, I did not know where to replace
         apps.get_app_config('bokeh.server.django')
 by:
         apps.get_app_config('bokeh_server_django')
2. After django be upgraded to 3.2, the following error happened:
pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
django-param 0.1.10 requires django<2.3,>=2.2, but you have django 3.2 which is incompatible.
3. After bokeh be downgraded to 2.0.2, the following error happened:
  pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
panel 0.11.1 requires bokeh<2.4.0,>=2.3.0, but you have bokeh 2.0.2 which is incompatible.

**Comment by bryevdv** [comment] 2021-04-12 15:33
You will have to downgrade panel as well. That is what the message is telling you. In any case , the tracker is not he place for support discussions, please move this to the project Discourse:

https://discourse.bokeh.org
