### ISSUE TITLE
0.12.4 GMAP underflowing Bokeh figure

### ISSUE THREAD

**Issue by RobbiePritchard** [bokeh/bokeh#5801] opened 2017-01-26 19:11 UTC
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/4GaPygTvhC8

issue can be recreated(tested safari, and chrome on bokeh 0.12.3 and 0.12.4) with any gmap plot:

```
from bokeh.plotting import Figure, ColumnDataSource, show, vplot
from bokeh.io import output_file
from bokeh.models import (Slider, CustomJS, GMapPlot,GMapOptions, DataRange1d, Circle, Line)

import numpy as np
from bokeh.plotting import curdoc, figure
from bokeh.layouts import row, column, widgetbox
from bokeh.client import push_session



r = 0.000192
x1 = np.linspace(-1, 1, 100) * r
x2 = np.linspace(1, -1, 100) * r
x = np.hstack((x1, x2))
f = lambda x: np.sqrt(r ** 2 - x ** 2)
y1 = f(x1)
y2 = -f(x2)
y = np.hstack((y1, y2))
init_x = 40.233688
init_y = -111.646784
lon = init_x + x
lat = init_y + y

# Initialize data sources.

location = ColumnDataSource(data=dict(x=[lon[0]], y=[lat[0]]))
path = ColumnDataSource(data=dict(x=lon, y=lat))

options = GMapOptions(lat=40.233681, lng=-111.646595, map_type="roadmap", zoom=15)
fig = GMapPlot(x_range=DataRange1d(), y_range=DataRange1d(), map_options=options, api_key='x')

c = Circle(x='x', y='y', size=10)
p = Line(x='x', y='y')
fig.add_glyph(location, c)
fig.add_glyph(path, p)


layout = column(fig)
curdoc().clear()
curdoc().add_root(layout)
session = push_session(curdoc())
session.show()
session.loop_until_closed()
```

**Comment by bryevdv** [comment] 2017-01-26 19:20
Adding `overflow:hidden` to `bk-canvas-map` seems to fix the issue, why this has never been needed before, I have no idea.

**Comment by bryevdv** [comment] 2017-01-26 19:22
I spoke too soon, panning the map, removed the property I added by hand, and the problem returned. Will have to investigate adding it in the library next to see if that persists better.

**Comment by bryevdv** [comment] 2017-01-26 19:34
Unfortunately I can't reproduce this locally when running `maps.py`, so there is also apparently something about being embedding in a more complex document that also has bearing.

**Comment by bryevdv** [comment] 2017-01-26 20:07
I actually can't reproduce this with master. @RobbiePritchard do yo have the ability to build and test from source?

**Comment by RobbiePritchard** [comment] 2017-01-26 20:14
what is maps.py?

**Comment by bryevdv** [comment] 2017-01-26 20:19
it's under `examples/models` but let's use you code above as a baseline. Right now with that code  it seems to have the problem with `0.12.4` but not if I run from master, but I can I can't find anything that would account for that. On master `overflow: hidden` is present on the map div

**Comment by bryevdv** [comment] 2017-01-26 20:32
@mattpap I'm not sure what caused the sudden break in older versions, but after a bisection, the current "fix" seemed to happen your drop JQuery PR.

**Comment by RobbiePritchard** [comment] 2017-01-26 21:27
I threw    
```
     .bk-canvas-map{
            overflow: hidden;
        }
```
into the head of the html document I'm embedding the map into for another temp "fix"

**Comment by bryevdv** [comment] 2017-01-26 21:55
Well I think `overflow: hidden` might be the real fix, I just don't know:

* why it was not needed previously
* why it suddenly is necessary
* how started getting added as a result of @mattpap 's PR

**Comment by mattpap** [comment] 2017-01-26 22:07
>  the current "fix" seemed to happen your drop JQuery PR.

Something is missing in this sentence. Is my JQuery PR helping or not?

**Comment by mattpap** [comment] 2017-01-26 22:09
> `overflow: hidden;`

Assuming that JQuery is at fault, seeing this I can presume that this isn't the real fix and there is something wrong with computation of dimensions (box model differences, because jquery does a lot of magic in this area).

**Comment by bryevdv** [comment] 2017-01-27 03:41
Hi, dev build `0.12.5dev11` is available which appears to fix the issue:

http://bokeh.pydata.org/en/dev/docs/user_guide/geo.html

Several other outstanding GMap issues also fixed (reset tool, updatable map options, blanking on refresh)

**Comment by bryevdv** [comment] 2017-01-28 16:16
@RobbiePritchard can you confirm that `0.12.5dev11` is working for you?

**Comment by kgullikson88** [comment] 2017-02-09 02:16
I have this issue with some 0.12.3 plots that I'm currently displaying on my blog. Will the `overflow:hidden` thing fix the existing plots or do I need to regenerate them with the dev version of bokeh? As an html noob, where would I put the `overflow:hidden`?

**Comment by syonekura** [comment] 2017-02-15 20:38
I have the same issue on the [User Guide](http://bokeh.pydata.org/en/latest/docs/user_guide/geo.html) using Chrome:

![image](https://cloud.githubusercontent.com/assets/13004870/22994208/dcb7647c-f3a4-11e6-92da-eed451c73323.png)

sometimes the issue doesn't appear at first sight, but it happens after panning the GMap

**Comment by bryevdv** [comment] 2017-02-15 20:54
This issue is fixed in master,  in the latest dev builds as well, and will be in `0.12.5`. Unfortunately I don not have the bandwidth to do a custom re-deploy of existing docs. The latest dev docs, and the `0.12.5` docs will have working versions.

**Closed** 2017-02-27 17:33 UTC
Labels: type: discussion
