### ISSUE TITLE
SVG does not clip correctly

### ISSUE THREAD

**Issue by laserson** [bokeh/bokeh#7528] opened 2018-02-14 22:23 UTC
Compare this

```python
from bokeh.plotting import figure, show
p = figure(x_range=(2, 4), y_range=(3, 6))
p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=2)
show(p)
```

with this

```python
from bokeh.plotting import figure, show
p = figure(x_range=(2, 4), y_range=(3, 6), output_backend='svg')
p.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=2)
show(p)
```

Note how I change the output backend in the second one. You'll see that the figure no longer clips the lines at the data boundaries. Any workarounds?

Bokeh version 0.12.13. Just installed phantomjs, selenium, pillow on conda today, so should be fresh.

**Comment by openastexviewer** [comment] 2018-02-28 20:42
Also seeing this in 0.12.13.

My scenario is zooming in on plots with lines with overlaid circles. Circles clip correctly, lines draw out to boundary of figure area.

Please note on screen render and svg are both incorrectly clipped. Image below is screen cap of behavior in browser.

![image](https://user-images.githubusercontent.com/18349887/36811830-0dad7aac-1cc7-11e8-9cab-f626d38f383e.png)

Example in tornado handler.

Thanks, Mike

```
from bokeh.resources import CDN
from bokeh.embed import file_html
from bokeh.plotting import figure, show, output_file

import numpy as np

class BokehHandler(tornado.web.RequestHandler):
    def get(self):
        print bokeh.__version__
        N = 50

        x = np.random.normal(0, np.pi, N)
        y = np.sin(x) + np.random.normal(0, 0.2, N)
        x, y = map(list, zip(*sorted(zip(x, y), reverse=1)))
        output_file("scatter10k.html", title="scatter 10k points (no WebGL)")

        p = figure(width=400, height=400, title="Complex Plot", logo=None, output_backend='svg')
        p.line(x, y, alpha=1)
        p.circle(x, y, alpha=1)
        
        html = file_html(p, CDN, "my plot")
        self.write(html)
```

**Comment by bryevdv** [comment] 2018-02-28 20:46
> Please note on screen render and svg are both incorrectly clipped. Image below is screen cap of behavior in browser.

This is a confusing statement. When `output_backend='svg'` is set, then SVG rendering is used whether in a browser, or saved to file. It is the SVG rendering that is an issue, regardless of how the SVG is used.

**Comment by mattpap** [comment] 2018-02-28 21:49
This is likely a duplicate of #6787, which is a duplicate of #6345.

**Closed** 2018-02-28 21:50 UTC
Labels: reso: duplicate

**Comment by openastexviewer** [comment] 2018-02-28 22:35
I have tried to provide you with information to diagnose the problem.

It certainly wasn't obvious to me that the in browser rendering is also changed.

Anyway, hoping it can be fixed at some stage.

Thanks
