### ISSUE TITLE
Histogram unexpected count

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [bokeh/bokeh#4431] opened 2016-06-03 03:06 UTC
```python
from bokeh.io import output_notebook
from bokeh.charts import Histogram, show
from numpy import histogram

output_notebook()

aa = [0] * 10 + [10]
print(aa)
hist, edges = histogram(aa)
print(hist, edges)
p = Histogram(aa, bins=50, title='Duration distribution')
show(p)
```
Input data:
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 10]

Unexpected result for 10:
![image](https://cloud.githubusercontent.com/assets/8209940/15767356/25264b8e-28fc-11e6-9497-ee66e1541755.png)

Expected result (in agreement with Numpy):
(array([10,  0,  0,  0,  0,  0,  0,  0,  0,  **1**]), array([  0.,   1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.]))

Also unexpected mix between the axis (lower case ``a`` on X-axis, upper case ``A`` on Y-axis), suggestion to be consistent. I was surprised by the name 'a', I didn't put any name of the data that I'm displaying.

**Comment by bryevdv** [comment] 2016-06-03 03:09
I believe this is a duplicate of #3875, addressed by PR #3988

**Closed** 2016-06-04 01:08 UTC
Labels: reso: duplicate
