### ISSUE TITLE
Problems rendering slider_app.py example using bokeh-server

### ISSUE THREAD

**Issue by alejandrozf** [bokeh/bokeh#2163] opened 2015-04-10 19:57 UTC
Hi! 
I got in troubles rendering the sliders_app example 
( https://github.com/bokeh/bokeh/blob/master/examples/app/sliders_applet/sliders_app.py ) on my browser... it seems like some troubles loading css files so visualization is of slider is missing.

I'm using Bokeh 0.8.2 + Anaconda 2.1.0 + python 3.4.1 in win32

I'll attach an screenshot of my browser + js console
![consola-js](https://cloud.githubusercontent.com/assets/8377636/7095669/746916da-df89-11e4-9a15-9c40ab473f43.JPG)

**Comment by damianavila** [comment] 2015-04-12 20:44
@bokeh/core any idea why this could be happening in the server? I mean not loading correctly the css...

btw, I could not reproduce on linux and @fpliger test it successfully on a WIN machine, so maybe it is something in the middle affecting only to @alejandrozf, ideas?

**Comment by hhuuggoo** [comment] 2015-04-12 20:56
Can you verify that the CSS file is present in bokeh/server/static/css?

**Comment by alejandrozf** [comment] 2015-04-13 12:16
yes,  @hhuuggoo, I have two files om that folder (bokeh.css, bokeh.min.css) ...

**Comment by damianavila** [comment] 2015-04-17 12:06
@bryevdv @fpliger more ideas??

**Comment by bryevdv** [comment] 2016-04-02 22:39
Refers to old `bokeh-server`, closing (new sliders example has not had any problems in my experience)

**Closed by bryevdv** 2016-04-02 22:39 UTC
Labels: tag: component: server, type: discussion
