### ISSUE TITLE
[BUG] components() does not return dict with wrap_plot_info=False

### ISSUE THREAD

**Issue by ludehon** [bokeh/bokeh#8851] opened 2019-04-19 09:05 UTC
As advertised in the reference at [components](https://bokeh.pydata.org/en/latest/docs/reference/embed.html#bokeh.embed.components), the function should return html script and a dictionary containing modelid, elementid, docid (with wrap_plot_info=False) but instead I get a bokeh.embed.util.RenderRoot object (which does not contains all the ids). 
I hope i'm not misunderstanding the behavior, I am trying to update some code from 0.12.14 (to 1.1.0). Launching the same code with 0.12.14 correctly returns the dict.

#### Code :
```
keys = ["lc1", "lc2"]
self.select_lc = Select(title="lc:", options=keys, value=keys[0])
script, div = components(self.select_lc, wrap_plot_info=False)
print(str(type(script)))
print(str(type(div)))
```

#### Console :
<class 'str'>
<class 'bokeh.embed.util.RenderRoot'>

**Comment by bryevdv** [comment] 2019-04-19 14:55
@Loutchiano I believe the problem is in the docs, they were not updated when they should have been

**Comment by bryevdv** [comment] 2019-04-19 15:51
@mattpap can you comment on the changes here?

**Comment by bryevdv** [comment] 2019-04-21 05:03
@Loutchiano FYI the `RenderRoot` contains all the information necessary to embed the object. Bokeh itself does this:
```
<div class="bk-root" id="{{ obj.elementid }}"{% if obj.id %} data-root-id="{{ obj.id }}"{% endif %}></div>
```
(Here `obj` is ` `RenderRoot`)

The docid is an implementation detail inside the script; you should not need it for any reason.

**Comment by Loutchiano** [comment] 2019-04-22 13:18
@bryevdv The code I am updating is using components() to get the modelid of a Select object. The id is later used in a CustomJS code, containing `document.getElementById(modelid).value = smth`

The class [RenderRoot ](https://github.com/bokeh/bokeh/blob/master/bokeh/embed/util.py) provides elementid and id. Which one should I use for the JS code ?

**Comment by bryevdv** [comment] 2019-04-22 14:21
`RednerRoot.id` is the model id

**Comment by Loutchiano** [comment] 2019-04-22 15:08
Ok thank you very much ! 
By the way, the 0.12.14 code use components() to get the id and then add the Select to the doc with doc.add_root(). But it appears in the latest version of Bokeh this causes a crash 
> Models must be owned by only a single document, Select(id='1001', ...) is already in a doc
Does that mean the function already add the model to the doc ? How can I both get the id and add it to the document ?

**Comment by bryevdv** [comment] 2019-04-22 15:13
@Loutchiano I can't really say anything without seeing actual code, but this is veering into general support territory so I'd ask that we take further discussion to the mailing list.

**Comment by Loutchiano** [comment] 2019-04-22 16:08
The person coded something like that (short version) :
```
self.select_lc = Select(title="Load Case:")
self.select_lc_id = components(self.select_lc)[1].id
code = js code using self.select_lc_id
self.doc.add_root(self.select_lc)
```
When I test this, components() is causing the problem above in the latest version of Bokeh. So I thought the function's behaviour changed a bit through updates...

Anyway thank you for the help, I will close this issue since it's only documentation related.

**Comment by bryevdv** [comment] 2019-04-22 16:21
@Loutchiano let's leave it open as a reminder to update the documentation

**Closed** 2022-03-05 18:11 UTC
Labels: tag: component: docs, type: task
