### ISSUE TITLE
Export bokeh fig to png and svg fails in server app

### ISSUE THREAD

**Issue by resenganalytics** [bokeh/bokeh#7592] opened 2018-03-03 14:00 UTC
I created a minimal example to reproduce an issue I have with exporting bokeh figures to PNG and SVG files. My system config:
**Ubuntu 16.04, Python 3.6, bokeh 0.12.14, selenium 3.9.0, Chrome 64.0.3282.186 browser**

```
from bokeh.io import curdoc, export_png, export_svgs
from bokeh.layouts import row, widgetbox
from bokeh.plotting import figure
from bokeh.models.widgets import Dropdown

# prepare some data
x = [1, 2, 3, 4, 5]
y = [6, 7, 2, 4, 5]

# create a new plot with a title and axis labels
p = figure(title="simple line example", x_axis_label='x', y_axis_label='y')

# add a line renderer with legend and line thickness
p.line(x, y, legend="Temp.", line_width=2)

menu = [("PNG", "png"), ("SVG", "svg")]
save_drop = Dropdown(label="Save as:", button_type="warning", menu=menu)

def save_handeler(attr, old, new):
    title = p.title.__dict__["_property_values"]["text"]
    if new == 'png':
        export_png(p, filename="%s.png" % title)
    elif  new == 'svg':
        p.output_backend = "svg"
        export_svgs(p, filename="%s.svg" % title)  
save_drop.on_change('value', save_handeler)

curdoc().add_root(row(widgetbox(save_drop), p, width=800))

```

In the client's browser debugging I see the following two errors:
**session.js:85 [bokeh] Unhandled ERROR reply to D6CBE0DA3C2B491E86967143A0E21E99: TypeError('expected str, bytes or os.PathLike object, not NoneType',)
t._handle_error @ session.js:85
session.js:85 [bokeh] Unhandled ERROR reply to 957BCA633D8B45BDA28FA627582A05F0: TypeError('expected str, bytes or os.PathLike object, not NoneType',)
t._handle_error @ session.js:85**

In the sever command line I get the following after trying both save in PNG and save in SVG dropdown options:
**error handling message Message 'PATCH-DOC' (revision 1): TypeError('expected str, bytes or os.PathLikeobject, not NoneType',)
error handling message Message 'PATCH-DOC' (revision 1): TypeError('expected str, bytes or os.PathLikeobject, not NoneType',)**

**Comment by bryevdv** [comment] 2018-03-04 19:06
cc @mattpap any ideas? I thought there was an issue for this but I can't find it, maybe it was brought up on the mailing list. 

@resenganalytics this issue only affects Bokeh server appplications, I have updated the title accordingly. Also FYI, there is no need for this:
```
title = p.title.__dict__["_property_values"]["text"]
```
Just `p.title.text` will do.

**Comment by AzraelDD** [comment] 2018-03-05 07:38
Maybe you were looking for the issue https://github.com/bokeh/bokeh/issues/7168. Seems to be the same problem.

**Comment by bryevdv** [comment] 2018-03-05 21:09
Ah, the original issue reported in #7168 is not this one, it is different. But subsequent comments seem to be this issue, so it is appropriate to leave both open.

**Comment by bryevdv** [comment] 2018-03-05 21:12
Actually, I was thinking of #7312, this is in fact a dupe of #7168

**Closed by bryevdv** 2018-03-05 21:12 UTC
Labels: tag: component: server, type: bug
