### ISSUE TITLE
[BUG] Tick label misaligned

### ISSUE THREAD

**Issue by jmranger** [bokeh/bokeh#12482] opened 2022-10-10 21:40 UTC
### Software versions

Python version      :  3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
IPython version     :  (not installed)
Tornado version     :  6.2
Bokeh version       :  3.0.0.dev20
BokehJS static path :  C:\ProgramData\Miniconda3\lib\site-packages\bokeh\server\static
node.js version     :  (not installed)
npm version         :  (not installed)
Operating system    :  Windows-10-10.0.19044-SP0

### Browser name and version

Firefox 105.0.3

### Expected behavior

All tick labels on the X axis should be aligned with the relevant tick.

### Observed behavior

The leftmost tick label has slid to the right, therefore not being aligned with the tick it documents the same way the other labels are.

### Example code

```Python
import datetime
from bokeh.models import DatetimeTickFormatter, HoverTool
from bokeh.plotting import figure, show
from math import pi
import pandas

xpts = [ datetime.datetime.utcfromtimestamp(1664780000),
         datetime.datetime.utcfromtimestamp(1664790000) ]
ypts = [1,2]
df = pandas.DataFrame(data=ypts,
                      index=xpts,
                      columns=["pts"])

plot = figure()
plot.scatter(df.index, df["pts"])
line = plot.line(df.index, df["pts"])
plot.add_tools(
    HoverTool(
        tooltips = [ ("Date & time", "@x{%Y-%m-%d %H:%M:%S.%3N}"),
                     ("Value", "@y"),
                   ],
        formatters = {
                        'x' : 'datetime',
                     },
        renderers = [
                      line
                    ],
        toggleable=False
    )
)
plot.xaxis.formatter = DatetimeTickFormatter(
    microseconds = '%Y-%m-%d %H:%M:%S.%f',
    milliseconds = '%Y-%m-%d %H:%M:%S.%f',
    seconds      = '%Y-%m-%d %H:%M:%S',
    minsec       = '%Y-%m-%d %H:%M:%S',
    minutes      = '%Y-%m-%d %H:%M:%S',
    hourmin      = '%Y-%m-%d %H:%M:%S',
    hours        = '%Y-%m-%d %H:%M:%S',
    days         = '%Y-%m-%d %H:%M:%S',
    months       = '%Y-%m-%d %H:%M:%S',
    years        = '%Y-%m-%d %H:%M:%S',
)
plot.xaxis.major_label_orientation = pi/8

show(plot)
```

### Stack traceback or browser console output

Found while testing a possible migration of existing Bokeh 0.12.7 code to 3.0.0.
0.12.7 wasn't perfect either, but the label "looked" aligned with the tick. It no longer does.

Output of bokeh info for 0.12.7:
Python version : 3.6.1 |Continuum Analytics, Inc.| (default, May 11 2017, 13:25:24) [MSC v.1900 64 bit (AMD64)]
IPython version : (not installed)
Bokeh version : 0.12.7
BokehJS static path : C:\Users\JMR\Desktop\Miniconda3\lib\site-packages\bokeh\server\static
node.js version : (not installed)
npm version : (not installed)

### Screenshots

![0 12 7](https://user-images.githubusercontent.com/12662295/194956354-16cd2877-2297-4b3a-b2ea-4cfd1c4bfa37.png)
![3 0 0dev20](https://user-images.githubusercontent.com/12662295/194956356-3e7b3a92-dd45-472c-b0d2-8878551a1a89.png)

**Comment by bryevdv** [comment] 2022-10-10 21:44
@mattpap it looks like the label shifted to avoid drawing outside the canvas? I don't think that is appropriate. 

@jmranger I expect if you shorten the labels, or otherwise make room for them (rotate more vertically or add more left min padding) that that might be an immediate WAR

**Comment by mattpap** [comment] 2022-10-10 22:02
This may be a duplicate of https://github.com/bokeh/bokeh/issues/12069, but I need to confirm this.

**Closed** 2022-10-20 07:58 UTC
Labels: type: bug, reso: duplicate, tag: component: bokehjs
