### ISSUE TITLE
Plot.add_layout should be renamed Plot.add_guide

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#6150] opened 2017-04-17 14:53 UTC
It's confusing because:
* GuideRenders (and annotations) are added via this method
* Layouts are a different set of Bokeh models (Rows, Columns, etc) and don't use this method

**Comment by mattpap** [comment] 2017-04-17 20:26
* annotations aren't guides
* add_layout makes some sense, because this method is tightly bound to manipulation of canvas layout

**Comment by mattpap** [comment] 2017-04-17 20:28
The right approach would be to make side panels first class citizens, then you would just issue `plot.left.append(axis)`.

**Comment by bryevdv** [comment] 2017-04-24 00:01
`plot.left.append(axis)` would be great if it can be made to work.

**Comment by mattpap** [comment] 2017-04-24 12:17
It's doable, but even with #5976 it will be a major piece of work.

**Comment by bryevdv** [comment] 2018-03-17 02:02
this is a dupe of #5303

**Closed by bryevdv** 2018-03-17 02:02 UTC
Labels: type: task
