### ISSUE TITLE
Bokeh SVG Plot

### ISSUE THREAD

**Issue by anupamsobti** [bokeh/bokeh#6893] opened 2017-09-06 14:19 UTC
![fpsvstp_edited](https://user-images.githubusercontent.com/17028941/30116877-40ab6992-933c-11e7-947d-3f6725e10d93.png)

When using the export_svg function from bokeh.io, the legend is garbled when more than 2 lines/circles are plotted. Also, the axis overlaps with tick labels. This works fine when opening in the browser.

**Comment by bokeh-integrations** [comment] 2017-09-06 14:34
@anupamsobti please provide the complete code to generate and reproduce the image above.

**Comment by bryevdv** [comment] 2017-09-06 14:34
dupe of #6787

**Closed by bryevdv** 2017-09-06 14:34 UTC
