### ISSUE TITLE
[FEATURE]Policy to exclude invisible features from auto-ranging

### ISSUE THREAD

**Issue by DataFramed** [bokeh/bokeh#9242] opened 2019-09-25 18:57 UTC
I am developing a dashboard that uses CustomJS callbacks to show/hide different traces.  I noticed that auto-ranging scales the chart to accommodate all traces, whether visible or not.  I can see the argument for this behavior, but I think there is also a good use case to have charts auto-scale to only those traces that are visible (e.g. traces of different orders of magnitude).

I was hoping there might be some option that can be set in a figure or in its range objects that would allow for auto-scaling to optionally ignore invisible traces.

The only alternative I can think of is to create different range objects for the different potential combinations of traces and then use CustomJS to swap them out, but this seems rather onerous, particularly when there may be many, many potential combinations of traces.

Thanks!  Really enjoying learning Bokeh so far...

EDIT: Google led me here from another bug report, which prompted this request:
[https://github.com/bokeh/bokeh/issues/4975](https://github.com/bokeh/bokeh/issues/4975)

**Comment by bryevdv** [comment] 2019-09-25 19:38
Thanks for the kind words @DataFramed This is actually a duplicate of https://github.com/bokeh/bokeh/issues/9144 which is currently part of the 1.4 milestone

**Closed by bryevdv** 2019-09-25 19:38 UTC
Labels: TRIAGE
