### ISSUE TITLE
`gridplot` distorts circles

### ISSUE THREAD

**Issue by alexeymuranov** [bokeh/bokeh#6760] opened 2017-08-10 20:58 UTC
#### Description

When using `gridplot`, `circle` produces distorted circles (ellipses).

#### Example code that reproduces the issue

```python
from bokeh.layouts import gridplot, row
from bokeh.plotting import figure, output_file, save

output_file("out.html")

plot = figure( plot_height = 600,
               plot_width  = 600,
               title = "Distorted circle",
               x_range = [0, 30],
               y_range = [0, 30] )

plot.circle([15], [15], radius=[10], alpha=0.5)

display = row(gridplot([[plot]]), width = 600)

save(display)
```

#### Screenshots of the bug in action

![out](https://user-images.githubusercontent.com/712698/29191701-e533a5e8-7e1e-11e7-9676-704ca3cc9724.png)

#### Software version info

Python 3.5.3
Bokeh 0.12.3
OS: NixOS 17.03
Firefox 54.0.1

**Comment by bryevdv** [comment] 2017-08-10 21:11
@alexeymuranov it's actually the other way around. The circle is a perfect circle (in screen/pixel space) but the aspect ratios of between data-space and screen-space dimensions do not match. Until there is a way to explicitly control aspect ratios (open issue), you will have to do it indirectly by controlling things like: canvas size, border padding, label size/orientation, and setting the data bounds so that the data aspect matches the pixel aspect. 

Closing as a dupe of #517

**Closed by bryevdv** 2017-08-10 21:11 UTC

**Comment by alexeymuranov** [comment] 2017-08-10 21:18
@bryevdv, objection: according to the [documentation](http://bokeh.pydata.org/en/latest/docs/reference/plotting.html#bokeh.plotting.figure.Figure.circle), the radius is specified in data space units.
> **radius** (*UnitsSpecPropertyDescriptor*) – The radius values for circle markers (in “data space” units, by default).

**Comment by bryevdv** [comment] 2017-08-10 21:21
> objection: according to the documentation, the radius is specified in data space units.

That's exactly right, however out of necessity it has to be measured along *one* dimension or the *other*. When the aspect screen/data aspect ratios are not the same in both dimensions, then things will look different according to which dimension you use to measure.

**Comment by alexeymuranov** [comment] 2017-08-10 21:30
Then "out of necessity" this is a defect/bug.

**Comment by bryevdv** [comment] 2017-08-10 21:39
Please feel free to continue the discussion on #517

**Comment by bryevdv** [comment] 2017-08-10 21:49
> Then "out of necessity" this is a defect/bug.

I should add: this comment is neither helpful nor appreciated. He underlying browser API accepts one radius parameter (in pixels). We have no control and cannot change that. If you data/screen aspect ratios are not matched, then what you are seeing will always happen when drawing canvas circles. That is simply fundamental mathematics. Can't change that either. there are however things you can do:

* using something that scales in both dimensions (e.g. `p.ellipse` instead of circles)
* make the aspect ratios match up (a slight chore until an explicit control is available, but still doable)

And I have tried to be polite in suggesting them, because I want all users to be happy and successful, but your attitude is not making it easy.
