### ISSUE TITLE
Tabs only consisting of DataTables not drawn correctly

### ISSUE THREAD

**Issue by jhappa** [bokeh/bokeh#4829] opened 2016-07-18 14:35 UTC
Tabs and Datatables not playing along together in v 0.12.0 it seems (bug?).

v 0.11.1 - (Expected behaviour for v0.12.0) I can have multiple tabs that contain only DataTables.
v 0.12.0 - Two issues emerge: 1) the tab titles are not drawn, and 2) datatables are drawn one after the other, see pic below:
![issue-notab](https://cloud.githubusercontent.com/assets/4136576/16917429/7d8224b2-4cf9-11e6-8715-d6507cecc145.png)

Current workaround (it appears): I must have at least one other type of figure in place (in code example below I use a line figure). Ordering of the tabs does not matter. 
![workaround](https://cloud.githubusercontent.com/assets/4136576/16917584/1cb1bfca-4cfa-11e6-9030-b7875cc7875c.png)

I've reproduced the bug in a simple example below by combining the example code for "tab panes" and "datatable" from here: http://bokeh.pydata.org/en/0.12.0/docs/user_guide/interaction.html 

```
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn, Panel, Tabs
from bokeh.io import output_file, show
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure

from datetime import date
from random import randint

output_file("data_table.html")

p2 = figure(plot_width=300, plot_height=300)
p2.line([1, 2, 3, 4, 5], [6, 7, 2, 4, 5], line_width=3, color="navy", alpha=0.5)
tab2 = Panel(child=p2, title="line")

data = dict(
    dates=[date(2014, 3, i+1) for i in range(10)],
    downloads=[randint(0, 100) for i in range(10)],
    )
source = ColumnDataSource(data)
columns = [
    TableColumn(field="dates", title="Date", formatter=DateFormatter()),
    TableColumn(field="downloads", title="Downloads"),
    ]
data_table = DataTable(source=source, columns=columns, width=400, height=280)
tab3 = Panel(child=data_table, title="table")

data2 = dict(
    dates=[date(2014, 3, i+1) for i in range(10)],
    downloads=[randint(0, 100) for i in range(10)],
    )
source2 = ColumnDataSource(data2)
columns2 = [
    TableColumn(field="dates", title="Date", formatter=DateFormatter()),
    TableColumn(field="downloads", title="Downloads"),
    ]
data_table2 = DataTable(source=source2, columns=columns2, width=400, height=400)
tab4 = Panel(child=data_table2, title="table2")

tabs = Tabs(tabs=[ tab2, tab3, tab4])
show(tabs)
```

**Comment by bryevdv** [comment] 2016-07-18 15:27
@jhappa thanks very much for the reproducing code, that is an immense help to evaluating things. I just tried this on `0.12.1dev2` and it appeared to be working correctly. Can you try with this dev build as well? Perhaps it is an already-resolved issue. If not, perhaps it is platform specific in some way, and we will have to dig deeper. 

You can find instructions for installing dev builds here: http://bokeh.pydata.org/en/latest/docs/installation.html#developer-builds

**Comment by jhappa** [comment] 2016-07-18 16:04
Same issue present on both my ubuntu 16.04 vm and windows 8.1 host with 0.12.1dev2 installed. 

Instead of:
tabs = Tabs(tabs=[ tab2, tab3, tab4])

Try running:
tabs = Tabs(tabs=[tab3, tab4]) 

Any difference?

**Comment by bryevdv** [comment] 2016-07-18 18:33
OK well, I will have to try to reproduce on those platforms then. For reference, I was using OS X/Safari when I tried, and it appeared to be working.

**Comment by jhappa** [comment] 2016-07-22 17:40
Ah, ok. Had a colleague of mine try out on his OS X (Darwin) machine as well - same layout issue as me (alas). Am beginning to wonder though whether this is a configuration-of-libraries issue on our end, even if our installs are the basic "pip install bokeh" and the vm is as vanilla as it gets - with no obvious tinkering on the windows or OSX boxes. 

All three boxes have these libraries installed (if of help):
backports-abc==0.4
bokeh==0.12.1.dev2
certifi==2016.2.28
futures==3.0.5
Jinja2==2.8
MarkupSafe==0.23
numpy==1.11.1
python-dateutil==2.5.3
PyYAML==3.11
requests==2.10.0
singledispatch==3.4.0.3
six==1.10.0
tornado==4.4

Let me know if any other config info would be of use.

On a related note: I've noticed that if I use Tabbed Panes with DataTables in them - row_headers appears to be set to True for all DataTables in the Tabs (as can be seen in the screenshot above). Is this by design or another potential issue on my end? Setting it to False during creation however, makes it False even in the tabs fortunately. I.e. _"data_table = DataTable(source=source, columns=columns, width=400, height=280, row_headers=False)"_

**Comment by ianlcassidy** [comment] 2017-01-11 19:56
This definitely still seems to be a problem in v0.12.4.  I am using Windows 7 and it happens in my Jupyter notebook (hosted in Chrome) as well as in a Flask + Bokeh web app that I am building.  Adding a `figure` to the `DataTable` tabs does fix the issue just as @jhappa describes above.  Happy to provide more details if necessary.

**Comment by bryevdv** [comment] 2017-06-01 01:24
This seems to be working for me as of `0.12.6dev7`:

<img width="534" alt="screen shot 2017-05-31 at 20 23 10" src="https://cloud.githubusercontent.com/assets/1078448/26660658/00309f58-463f-11e7-80a2-9350117ada3e.png">
<img width="552" alt="screen shot 2017-05-31 at 20 23 13" src="https://cloud.githubusercontent.com/assets/1078448/26660659/003169a6-463f-11e7-9856-c03e3d214b08.png">
<img width="531" alt="screen shot 2017-05-31 at 20 23 18" src="https://cloud.githubusercontent.com/assets/1078448/26660660/00324614-463f-11e7-858e-d5dee7222d41.png">

@ianlcassidy @jhappa if you have the ability to test with 0.12.6dev7 and confirm this it would be apreciated

**Comment by ianlcassidy** [comment] 2017-06-01 13:13
@bryevdv I just tried it on my end using 0.12.6dev7 and the problem of the DataTables being stacked on top of each other when the tabs contain just DataTables appears to be resolved.

One slightly odd thing that I'm noticing (and this might just be a Jupyter Notebook issue) is that when I click on the last tab; i.e., "table2", several lines of whitespace seems to be added below the table.  I'm not sure if this actually affects the HTML though.  Below are some screenshots.

![untitled](https://cloud.githubusercontent.com/assets/6929405/26681210/58d53720-46aa-11e7-8c0c-26f8da169443.png)

![untitled2](https://cloud.githubusercontent.com/assets/6929405/26681217/5c8b4ec2-46aa-11e7-85a6-1c619884454c.png)

**Comment by jhappa** [comment] 2017-06-01 14:14
@bryevdv Thanks for the update. Just tried 0.12.6dev7. Appears to be resolved for me as well
for me as well. Thanks.

**Comment by bryevdv** [comment] 2017-06-01 14:46
Thanks for the updates! I will close this.

**Closed by bryevdv** 2017-06-01 14:46 UTC
Labels: tag: layout, type: bug
