### ISSUE TITLE
[BUG] Export Jupyter notebook to html will not render Bokeh figures if an specific cell exists

### ISSUE THREAD

**Issue by julioasotodv** [bokeh/bokeh#9222] opened 2019-09-12 01:07 UTC
Hi,

This is, by far, the weirdest and at the same time the most hilarious bug I have ever seen in my entire life. It's not like it is critical, but I find it very interesting nevertheless.

It turns out that if you have a Jupyter Notebook with Bokeh figures (any version of Bokeh and Jupyter >= 5.0), and in that same notebook you happen to have a Markdown cell where the only text is exactly `# Bokeh` (a Markdown header with the word Bokeh), when you export the notebook to html the Bokeh figures will not be displayed, and different browsers will raise different errors in the JS console. For instance, in Chrome:

```
Uncaught TypeError: Cannot read property 'embed_items_notebook' of undefined
    at embed_document (This one does not work.html:13535)
    at This one does not work.html:13539
    at This one does not work.html:13554
```

Please find attached a snapshot of two exported notebooks that contain exactly the same code, but one works and the other one does not due to the Bokeh markdown title in the second cell (unfortunately Github does not allow ipynb or html attachments)

![This one works](https://user-images.githubusercontent.com/20630819/64745868-cc44e580-d509-11e9-9b19-631cd4092abd.png)

![This one does not](https://user-images.githubusercontent.com/20630819/64745874-d1099980-d509-11e9-8fcd-c208a4df8693.png)

And yes, it took me like 3 hours to spot the exact issue.

Anyways, thank you so much for Bokeh. I really love this library 😊

**Comment by bryevdv** [comment] 2019-09-12 01:09
Well, that's amazing. @julioasotodv are there any errors reported in the JS console in the non-working case? 

cc @mattpap

**Comment by teebr** [comment] 2020-07-10 20:48
This also happens with a `# Jupyter` heading:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/23308704/87201732-14ce5a80-c2f7-11ea-85e7-c59617818b59.png">

```
Uncaught Error: Module name "base/js/events" has not been loaded yet for context: _. Use require([])
http://requirejs.org/docs/errors.html#notloaded
    C https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:8
    g https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:26
    requirejs https://cdnjs.cloudflare.com/ajax/libs/require.js/2.1.10/require.min.js:31
    <anonymous> http://127.0.0.1:8000/markdown-test.html:13266
    <anonymous> http://127.0.0.1:8000/markdown-test.html:13432
require.min.js:8:252
```

**Comment by bryevdv** [comment] 2020-08-25 05:26
This is a dupe of https://github.com/bokeh/bokeh/issues/10002 (there is much more analysis there)

**Closed by bryevdv** 2020-08-25 05:26 UTC
Labels: type: discussion
