### ISSUE TITLE
Plots in Tabs not working on a bokeh server. 

### ISSUE THREAD

**Issue by copperwire** [bokeh/bokeh#3796] opened 2016-02-01 09:52 UTC
Hi! 

I've run into a problem where setting up plots in tabs don't work when pushing to a bokeh server. 

[This pastebin](http://pastebin.com/4a9QmSvK) contains a script that replicates the issue. 

The  end result is the "tabs" in a list on the page. 

-Robert

**Comment by canavandl** [comment] 2016-02-01 19:02
going to close as duplicate of #3138 (proposed solution in #3650 )

Thanks for the report! We're currently debating how to be resolve this and other layout issues.

**Closed** 2016-02-01 19:02 UTC
Labels: reso: duplicate, tag: regression, type: bug
