### ISSUE TITLE
allow text glyph's text_font_size parameter to have a list passed in.

### ISSUE THREAD

**Issue by afonit** [bokeh/bokeh#1248] opened 2014-09-24 18:55 UTC
Doing the below:
```python
import bokeh.plotting as bp

bp.output_notebook()

stext = ['one','two','three','four']
x_pos = [1,2,3,4]
y_pos = [1,2,3,4]
fs = ['5px','10px','15px','20px']

bp.text(x_pos, y_pos, stext, 0, text_font_size = fs)

bp.show()
```
results in:
ValueError: expected a value of type str, got ['5px', '10px', '15px', '20px'] of type list

so changing:
```python
bp.text(x_pos, y_pos, stext, 0, text_font_size = fs)
```
to:
```python
bp.text(x_pos, y_pos, stext, 0, text_font_size = '12px')
```
works.

However, this does not allow the size of words to vary with the text points.
Looking in the userguide I see it does need to have specified:
     text_font_size - font size in px, em, or pt, e.g., '12pt', '1.5em'

so perhaps this could work:?
```python
bp.text(x_pos, y_pos, stext, 0, text_font_size = (fs,'px') )
```
Allowing a tuple could allow the list to be passed in and the designation of units (to avoid having to join them on the user's end and make a list comprehension concatenating values to get a list of 'str(int)px' values. 

I hope this request makes sense.
Ultimately it would be convenient to be able to pass in a list, and I think most conveniently would be a tuple of (list,units_specification).

 
I see the text glyph in here:
https://github.com/ContinuumIO/bokeh/blob/master/bokeh/glyphs.py
It looks like the parameters get passed into TextProps which I found here:
https://github.com/ContinuumIO/bokeh/blob/master/bokeh/mixins.py
I then see that it shows:
text_font_size = String("10pt")

I noticed that the x,y get passed to DataSpec, but beyond that I am not sure how to do the change to make this work as I am not following how that is working together - so I will just leave this as a feature request. 
https://github.com/ContinuumIO/bokeh/blob/master/bokeh/properties.py

**Comment by bryevdv** [comment] 2015-01-09 05:17
I am going to close this as a duplicate of #1426. When implemented that is a general solution that will include this as a special case.

**Closed by bryevdv** 2015-01-09 05:17 UTC
Labels: reso: duplicate, type: feature
