### ISSUE TITLE
Range objects on plots don't update in bokeh-server if replaced

### ISSUE THREAD

**Issue by othererik** [bokeh/bokeh#1056] opened 2014-08-25 02:43 UTC
Using bokeh==0.5.2-49-gf5a107a

Created a plot (using bokeh-server in this case)
```
         p = plotting.rect(...) 
```
Attempted to update the list without success,
```
        p.y_range = [-10, 10]
"ValueError: expected an instance of type Range, got [-10, 10] of type list"


```
Using a Range1d object sets but doesn't lead to the expected update on the plot
```
        p.y_range = Range1d(start=-10, end=10)
```

Stored the plot again.
```
        cursession().store_objects(p) 
```

In the bokeh-server run, the plot ranges were not updated. 

I am able to get around this by directly editing the existing range object, that is:
```
p.y_range.start = -10
p.y_range.end = 10
```
See:
https://groups.google.com/a/continuum.io/forum/#!topic/bokeh/j_xKiwth5Xw

**Comment by ahmadia** [comment] 2015-10-01 04:18
This issue is still active in 0.10

**Comment by nathanielatom** [comment] 2016-02-28 06:24
Is this a known issue using jupyter notebooks with ``push_notebook`` as well?

When I run 
    p.y_range.start = -10

followed by a ``push_notebook()`` the `p.y_range.start` value updates, but the plot itself does not.

**Comment by bryevdv** [comment] 2016-04-10 02:29
I think this is a dupe of #4014 Although that issue is newer, it has discussion more relevant to the current server and architecture, so I am closing this issue in favor of that one.

**Closed by bryevdv** 2016-04-10 02:29 UTC
Labels: type: feature
