### ISSUE TITLE
[BUG] Plot disappears in webgl backend while streaming

### ISSUE THREAD

**Issue by bmeatayi** [bokeh/bokeh#9577] opened 2020-01-14 11:32 UTC
#### Environment 
* python: 3.6.9
* bokeh: 1.4.0
* OS: Ubuntu 18.04
* Browser: Chrome
* Graphics card: Nvidia GeForce GTX 1650
* Graphics driver: Nvidia driver 435

#### Description of expected behavior and the observed behavior
In the [ohlc example](https://github.com/bokeh/bokeh/tree/master/examples/app/ohlc), when the backend is changed to webgl, the plot has weird behavior and disappears time to time.

 #### Screenshots or screencasts of the bug in action

![bokeh_streaming_bug](https://user-images.githubusercontent.com/35002731/72341063-a737cd80-36c9-11ea-910d-338b6f1c30cb.jpg)

![bokeh_streaming_bug_2](https://user-images.githubusercontent.com/35002731/72341073-ad2dae80-36c9-11ea-8e59-a681df4f524e.jpg)

#### Complete, minimal, self-contained example code that reproduces the issue

```
import numpy as np
np.random.seed(1)

from bokeh.layouts import row, column, gridplot
from bokeh.models import ColumnDataSource, Slider, Select
from bokeh.plotting import curdoc, figure
from bokeh.driving import count

MA12, MA26, EMA12, EMA26 = '12-tick Moving Avg', '26-tick Moving Avg', '12-tick EMA', '26-tick EMA'

source = ColumnDataSource(dict(
    time=[], average=[], low=[], high=[], open=[], close=[],
    ma=[], macd=[], macd9=[], macdh=[], color=[]
))

p = figure(plot_height=500, tools="xpan,xwheel_zoom,xbox_zoom,reset", x_axis_type=None, y_axis_location="right", output_backend="webgl")
p.x_range.follow = "end"
p.x_range.follow_interval = 100
p.x_range.range_padding = 0

p.line(x='time', y='average', alpha=0.2, line_width=3, color='navy', source=source)
p.line(x='time', y='ma', alpha=0.8, line_width=2, color='orange', source=source)
p.segment(x0='time', y0='low', x1='time', y1='high', line_width=2, color='black', source=source)
p.segment(x0='time', y0='open', x1='time', y1='close', line_width=8, color='color', source=source)

p2 = figure(plot_height=250, x_range=p.x_range, tools="xpan,xwheel_zoom,xbox_zoom,reset", y_axis_location="right", output_backend="webgl")
p2.line(x='time', y='macd', color='red', source=source)
p2.line(x='time', y='macd9', color='blue', source=source)
p2.segment(x0='time', y0=0, x1='time', y1='macdh', line_width=6, color='black', alpha=0.5, source=source)

mean = Slider(title="mean", value=0, start=-0.01, end=0.01, step=0.001)
stddev = Slider(title="stddev", value=0.04, start=0.01, end=0.1, step=0.01)
mavg = Select(value=MA12, options=[MA12, MA26, EMA12, EMA26])

def _create_prices(t):
    last_average = 100 if t==0 else source.data['average'][-1]
    returns = np.asarray(np.random.lognormal(mean.value, stddev.value, 1))
    average =  last_average * np.cumprod(returns)
    high = average * np.exp(abs(np.random.gamma(1, 0.03, size=1)))
    low = average / np.exp(abs(np.random.gamma(1, 0.03, size=1)))
    delta = high - low
    open = low + delta * np.random.uniform(0.05, 0.95, size=1)
    close = low + delta * np.random.uniform(0.05, 0.95, size=1)
    return open[0], high[0], low[0], close[0], average[0]

def _moving_avg(prices, days=10):
    if len(prices) < days: return [100]
    return np.convolve(prices[-days:], np.ones(days, dtype=float), mode="valid") / days

def _ema(prices, days=10):
    if len(prices) < days or days < 2: return [prices[-1]]
    a = 2.0 / (days+1)
    kernel = np.ones(days, dtype=float)
    kernel[1:] = 1 - a
    kernel = a * np.cumprod(kernel)
    # The 0.8647 normalizes out that we stop the EMA after a finite number of terms
    return np.convolve(prices[-days:], kernel, mode="valid") / (0.8647)

@count()
def update(t):
    open, high, low, close, average = _create_prices(t)
    color = "green" if open < close else "red"

    new_data = dict(
        time=[t],
        open=[open],
        high=[high],
        low=[low],
        close=[close],
        average=[average],
        color=[color],
    )

    close = source.data['close'] + [close]
    ma12 = _moving_avg(close[-12:], 12)[0]
    ma26 = _moving_avg(close[-26:], 26)[0]
    ema12 = _ema(close[-12:], 12)[0]
    ema26 = _ema(close[-26:], 26)[0]

    if   mavg.value == MA12:  new_data['ma'] = [ma12]
    elif mavg.value == MA26:  new_data['ma'] = [ma26]
    elif mavg.value == EMA12: new_data['ma'] = [ema12]
    elif mavg.value == EMA26: new_data['ma'] = [ema26]

    macd = ema12 - ema26
    new_data['macd'] = [macd]

    macd_series = source.data['macd'] + [macd]
    macd9 = _ema(macd_series[-26:], 9)[0]
    new_data['macd9'] = [macd9]
    new_data['macdh'] = [macd - macd9]

    source.stream(new_data, 300)

curdoc().add_root(column(row(mean, stddev, mavg), gridplot([[p], [p2]], toolbar_location="left", plot_width=1000)))
curdoc().add_periodic_callback(update, 50)
curdoc().title = "OHLC"

```

**Comment by bryevdv** [comment] 2020-01-17 19:12
@bmeatayi This is probably related to/duplicate of one of the several other webgl issues:

https://github.com/bokeh/bokeh/issues?utf8=✓&q=is%3Aissue+is%3Aopen+webgl

So we may close it as such at some point. As you can see there are lots of problems with our current webgl backend but the original developer of it has moved on. Our intention is to completely overhaul webgl support with a more robust third party webgl abstraction later this year. We could certainly use help with that effort to make it happen faster, if you are interested.

**Comment by mattpap** [comment] 2020-01-17 19:44
Hopefully this is just data mapping (or similar) issue (webgl backend does those on its own) and not a webgl issue in itself. If so, this should be (fairly?) easily fixable. @bmeatayi, can you submit a an actually self-contained test case (i.e. preferably a single plot with a single glyph setup)?

**Comment by bmeatayi** [comment] 2020-01-21 09:00
Thanks for the responses.

> Hopefully this is just data mapping (or similar) issue (webgl backend does those on its own) and not a webgl issue in itself. If so, this should be (fairly?) easily fixable. @bmeatayi, can you submit a an actually self-contained test case (i.e. preferably a single plot with a single glyph setup)?

Here you can find a minimal script for reproducing this issue.

```
import numpy as np
from bokeh.models import ColumnDataSource
from bokeh.plotting import curdoc, figure
from bokeh.driving import count

source = ColumnDataSource(dict(
    time=[], y=[]
))

p = figure(plot_height=500, output_backend="webgl")
p.x_range.follow = "end"
p.x_range.follow_interval = 200
p.x_range.range_padding = 0

p.line(x='time', y='y', source=source)


@count()
def update(t):
    y = np.random.lognormal(0, 1)
    new_data = dict(
        time=[t],
        y=[y]
    )

    source.stream(new_data, rollover=250)


curdoc().add_root(p)
curdoc().add_periodic_callback(update, 30)
curdoc().title = "test"
```
Interestingly, trying different values for `p.x_range.follow_interval` and `rollover`, it seems that this problem occurs when the `rollover` value is considerably larger than `follow_interval`. So, I think you are right and it might be a data mapping problem.

**Comment by ianthomas23** [comment] 2024-01-17 09:59
I have confirmed that this is fixed. The above minimal reproducer (with `plot_height` changed to `height`) works using `branch-3.4` for all 3 output backends (canvas, svg and webgl).

**Closed by ianthomas23** 2024-01-17 09:59 UTC
Labels: type: bug, tag: component: bokehjs, tag: webgl

**Comment by mattpap** [comment] 2024-01-17 11:03
This seems to work since at least `branch-3.0`, based on my cursory testing.
