### ISSUE TITLE
ColumnDataSource callback on_change issue in 0.13

### ISSUE THREAD

**Issue by bjonen** [bokeh/bokeh#8014] opened 2018-06-20 13:57 UTC
I have connected a `widgets.DataTable` with a `figure` by using the `on_change` method on the ColumnDataSource. 
``` 
source = ColumnDataSource(sub)
source.on_change('selected', table_select_callback)
```
This has stopped working in the latest release (0.13). Selecting rows in the table does not seem to trigger an event anymore.

**Comment by bryevdv** [comment] 2018-06-20 14:12
Please provide a complete minimal script that reproduces the issue.

**Comment by bryevdv** [comment] 2018-06-20 14:48
In any case, arguably, since the work to make `Selection` a proper Bokeh models earlier this year, the proper way to do this is
```
source.selected.on_change('indices', table_select_callback)
```

**Comment by bryevdv** [comment] 2018-06-20 14:56
cc @mattpap I guess in the past we were replacing Selections objects entirely:
```
def cb(attr, old, new):
    print(attr, old, new)

source.on_change('selected', cb)
```
0.12.6 prints this:
```
selected Selection(id='f72f9a72-7961-4832-bf31-6b2551ad1607', ...) Selection(id='015BD3F2F7D345609825BB3B557612F7', ...)
```
but offhand, now I don't think that is the case (i.e. we are just updating indices and keeping the selection). With `0.13.0` a callback on `source.selected.on_change('indices', cb)` works fine.

**Comment by bryevdv** [comment] 2018-06-20 15:02
Yes that's exactly the case:

https://github.com/bokeh/bokeh/pull/7982/files#diff-9a94b84e4d8bf61ef575c08f17519220L265

I don't think we can go back, though. Maybe `source.selected = source.selected` would work to restore the previous behaviour? Might be wasteful though. 

@bjonen this was not an explicitly intended breaking change, but it's not clear to me yet that its one that can be avoided, either. I'd recommend changing to the code I have above.

**Comment by bjonen** [comment] 2018-06-20 15:50
Sure, here we go. Based on https://stackoverflow.com/a/41308431
```
from datetime import date
from random import randint
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn

import bokeh.layouts as layouts
import bokeh.models.widgets as widgets
from bokeh.io import curdoc

# from bokeh.models.glyphs import Line
# from bkcharts import Line
import numpy as np
from bokeh.plotting import figure

data = dict(
    dates=[date(2014, 3, i + 1) for i in range(10)],
    downloads=[randint(0, 100) for i in range(10)],
)
d_source = ColumnDataSource(data)

columns = [
    TableColumn(field="dates", title="Date", formatter=DateFormatter()),
    TableColumn(field="downloads", title="Downloads"),
]

data_table = DataTable(source=d_source, columns=columns, width=400, height=280)
#data_table.row_headers = False


def table_select_callback(attr, old, new):
    selected_row = new['1d']['indices'][0]
    download_count = data['downloads'][selected_row]
    chart_data = np.random.uniform(0, 100, size=download_count)
    p = figure(title='bla')
    r = p.line(x=range(len(chart_data)), y=chart_data)
    root_layout.children[1] = p

d_source.on_change('selected', table_select_callback)

root_layout = layouts.Column(data_table, widgets.Div(text='Select Date'))
curdoc().add_root(root_layout)
```

**Comment by bjonen** [comment] 2018-06-20 16:21
Many thanks. With the above adjustment, the example is fixed. Thanks for the quick response! 
```
from datetime import date
from random import randint
from bokeh.models import ColumnDataSource
from bokeh.models.widgets import DataTable, DateFormatter, TableColumn

import bokeh.layouts as layouts
import bokeh.models.widgets as widgets
from bokeh.io import curdoc

# from bokeh.models.glyphs import Line
# from bkcharts import Line
import numpy as np
from bokeh.plotting import figure

data = dict(
    dates=[date(2014, 3, i + 1) for i in range(10)],
    downloads=[randint(0, 100) for i in range(10)],
)
d_source = ColumnDataSource(data)

columns = [
    TableColumn(field="dates", title="Date", formatter=DateFormatter()),
    TableColumn(field="downloads", title="Downloads"),
]

data_table = DataTable(source=d_source, columns=columns, width=400, height=280)
#data_table.row_headers = False


def table_select_callback(attr, old, new):
    # print 'here'
    # print new
    # selected_row = new['1d']['indices'][0]
    selected_row = new[0]
    download_count = data['downloads'][selected_row]
    chart_data = np.random.uniform(0, 100, size=download_count)
    p = figure(title='bla')
    r = p.line(x=range(len(chart_data)), y=chart_data)
    root_layout.children[1] = p

# d_source.on_change('selected', table_select_callback)
d_source.selected.on_change('indices', table_select_callback)

root_layout = layouts.Column(data_table, widgets.Div(text='Select Date'))
curdoc().add_root(root_layout)

```

**Comment by bryevdv** [comment] 2018-06-22 22:07
Noting that e.g. `selection_histogram.py` still works with `source.on_change('selected`, ...)` so I do think we need to figure out something consistent for users to expect.

**Comment by bryevdv** [comment] 2018-09-11 01:17
This (clarifying and better documenting exacfly how to use and interact with selection objects) is covered by the linked issue, I am going to close this in deference to it.

**Closed by bryevdv** 2018-09-11 01:17 UTC
Labels: type: discussion

**Comment by mrocklin** [comment] 2018-11-14 14:30
I found that as of Bokeh 1.0 the suggestion in https://github.com/bokeh/bokeh/issues/8014#issuecomment-398778550 seems to be mandatory.  If this is the case it might be worth raising an informative error to help others.

**Comment by mrocklin** [comment] 2018-11-14 14:30
(or at least this was anecdotally the case in my situation)

**Comment by mattpap** [comment] 2018-11-14 14:44
This was clarified on the implementation level in PR #8310, but it looks like it wasn't followed with any documentation changes.

**Comment by ahmedmdl** [comment] 2019-01-11 14:44
sorry for bargin in ,
could u update the documentation like the widget one for instance cause i have come across this page here after a full week of searching and trying
thanks
