### ISSUE TITLE
[BUG] BokehJS standalone initialization fails

### ISSUE THREAD

**Issue by pastewka** [bokeh/bokeh#13864] opened 2024-05-05 20:37 UTC
### Software versions

Bokeh version: 3.4.1
npm version: 10.5.0

### Expected behavior

I am using pure BokehJS for visualizing scientific data in a larger web application. I expect the interaction with BokehJS to work as described in the documentation, e.g. here: https://docs.bokeh.org/en/latest/docs/user_guide/advanced/bokehjs.html, without any additional initialization steps.

### Observed behavior

The behavior described below started with Bokeh 3.1.0. Bokeh 3.0.3 still works as expected. The behavior occurs using both the low-level and the `Plotting` interface. A minimal example, based on the examples found in the Bokeh documentation, can be found here: https://github.com/pastewka/bokeh-example

The browser throws a `TypeError: signal is undefined`. 

The code works again when calling `initialize` of each new instantiated instance of a Bokeh class in the example using the low level API provided here.

This also fixed the `signal is undefined` error in the high-level `Plotting` API code, but that code then throws `TypeError: this._plot_bounds is undefined`.

It looks to me like the initialization logic changed from 3.0.x to 3.1.x and this somehow broke the standalone API.

### Example code

```Python
import {ColumnDataSource, Grid, LinAlg, Line, LinearAxis, Range1d, Plot, Plotting} from '@bokeh/bokehjs';

// create some data and a ColumnDataSource
const x = LinAlg.linspace(-0.5, 20.5, 10);
const y = x.map(function (v) { return v * 0.5 + 3.0; });
const source = new ColumnDataSource({ data: { x: x, y: y } });

// create some ranges for the plot
const xdr = new Range1d({ start: -0.5, end: 20.5 });
const ydr = new Range1d({ start: -0.5, end: 20.5 });

// make the plot
const plot = new Plot({
    title: "BokehJS Plot",
    x_range: xdr,
    y_range: ydr,
    width: 400,
    height: 400,
    background_fill_color: "#F2F2F7"
});

// add axes to the plot
const xaxis = new LinearAxis({ axis_line_color: null });
const yaxis = new LinearAxis({ axis_line_color: null });
plot.add_layout(xaxis, "below");
plot.add_layout(yaxis, "left");

// add grids to the plot
const xgrid = new Grid({ ticker: xaxis.ticker, dimension: 0 });
const ygrid = new Grid({ ticker: yaxis.ticker, dimension: 1 });
plot.add_layout(xgrid);
plot.add_layout(ygrid);

// add a Line glyph
const line = new Line({
    x: { field: "x" },
    y: { field: "y" },
    line_color: "#666699",
    line_width: 2
});
plot.add_glyph(line, source);

Plotting.show(plot);
```

### Stack traceback or browser console output

Console output from Firefox.

```
Uncaught (in promise) TypeError: signal is undefined
    connect view.js:38
    connect_signals glyph_renderer.js:142
    build_views build_views.js:34
    build_renderer_views plot_canvas.js:593
    lazy_initialize plot_canvas.js:260
    _build_view build_views.js:7
    build_view build_views.js:11
    build_view view_manager.js:15
    render_view standalone.js:46
    render_model standalone.js:56
    add_document_standalone standalone.js:67
    show io.js:54
    async* lowlevel.js:43
``

### Screenshots

_No response_

**Comment by pastewka** [comment] 2024-05-05 20:40
Here is the stack traceback for the `_plot_bounds` error:

```
Uncaught (in promise) TypeError: this._plot_bounds is undefined
    update data_range1d.js:210
    _update_dataranges range_manager.js:92
    update_dataranges range_manager.js:124
    lazy_initialize plot_canvas.js:261
    _build_view build_views.js:7
    build_view build_views.js:11
    build_view view_manager.js:15
    render_view standalone.js:46
    render_model standalone.js:56
    add_document_standalone standalone.js:67
    show io.js:54
    async* plotting.js:40
``

**Comment by bryevdv** [comment] 2024-05-05 23:00
@pastewka I don't have any immediate answers for you, @mattpap will have to chime in. I will say that like most OSS projects, limited resources means that prioritization is unavoidable, and speaking plainly, the BokehJS APIs and docs do not currently get the same attention that other areas do. For certainty about current usage, I'd direct you to the BokehJS examples directory of the relevant branch, since these at least are maintained under CI. e.g. for 3.4.x releases:

https://github.com/bokeh/bokeh/tree/branch-3.4/bokehjs/examples

**Comment by pastewka** [comment] 2024-05-06 07:26
@bryevdv The examples indeed work, thanks for pointing those out. It looks like I am doing something wrong when integrating BokehJS into my project (via webpack). Any help would be appreciated.

**Comment by ianthomas23** [comment] 2024-05-06 07:33
Duplicate of #13732

**Comment by ianthomas23** [comment] 2024-05-06 07:36
@pastewka You are not doing anything wrong, this cannot work without significant restructure of the BokehJS object construction and initialisation code.

**Comment by pastewka** [comment] 2024-05-06 07:45
@ianthomas23 Thanks for pointing out issue #13732. Let me know if I can be of help fixing this.

**Comment by ianthomas23** [comment] 2024-05-08 07:09
@pastewka I am going to close this as it is a duplicate of #13732 and we like to have just one github issue open for each actual problem. We can continue the conversation over there.

**Closed as completed by ianthomas23** 2024-05-08 07:09 UTC
Labels: reso: duplicate

**Comment by pastewka** [comment] 2024-05-08 07:38
Sounds good
