### ISSUE TITLE
[FEATURE] allow multiple actions for TapTool

### ISSUE THREAD

**Issue by nlosacco** [bokeh/bokeh#13105] opened 2023-04-27 13:43 UTC
### Problem description

So far only a single action (e.g. ‘select’) and a single gesture (e.g. ‘tap’) can be defined for any TapTool. Multiple actions require multiple TapTools and clearly only one TapTool can be active at a given time 

### Feature description

It’d great if a TapTool could be endowed with multiple actions (e.g. select, OpenURL, etc.) each one corresponding to a different gesture (tap, doubletap) or even including key modifiers (e.g. shift + tap, alt + tap and so forth)

### Potential alternatives

I have no clue but maybe providing gesture/action as a single dict or a couple of lists could be a way

**Comment by bryevdv** [comment] 2023-05-11 04:22
@nlosacco I think your this use case is really already covered by existing features:

* if you only want taps to register when glyphs are "hit" then you can add `CustomJS` callbacks for selection, and then do whatever you want in the JS callback e.g. open multiple URLs, update other parts of the plot, whatever.
* alternatively, if you want taps to register at any location, regardless of ay glyph hit-testing, then you can add `CustomJS` callbacks for the general "tap" event. 

cc @bokeh/dev I am inclined to close this with `noaction`

**Comment by nlosacco** [comment] 2023-05-11 19:02
Hi @bryevdv
but, if I'm not mistaken, this doesn't seem to reflect my wished feature, i.e. obtain different results when hitting a given glyph with different gestures (e.g. tap, double-tap, key+tap, and so forth...)

**Comment by bryevdv** [comment] 2023-05-13 23:30
Unfortunately I don't think the current tap tool could accommodate anything like this. It already intercepts SHIFT modifiers for its own use, and its API already present single/double tap as an exclusive choice, so any change like this would necessarily be a (very) breaking change. 

A much easier option to contemplate might be to add modifier information to the "tap" event. Do you actually need to the selection/hit-testing functionality of the tap *tool*? Or do you just need to process tap events with their coordinates.

**Comment by bryevdv** [comment] 2023-05-16 16:51
Actually I think this is more or less a duplicate of https://github.com/bokeh/bokeh/issues/12532 At least, I think that *reporting* key modifiers as I described above, to let users do whatever they want with that information, is about the best we can offer. @mattpap has already opened #13132 to add that functionality.

**Closed as completed by bryevdv** 2023-05-16 16:51 UTC
Labels: reso: duplicate, type: discussion
