### ISSUE TITLE
[BUG] the spinner widget is not working in table cells.

### ISSUE THREAD

**Issue by duynguyen2411** [bokeh/bokeh#9025] opened 2019-06-22 17:53 UTC
I'm using Bokeh 1.0.4, the spinner widget is not working in table cells. I checked with Bokeh 1.2.0, i have a same problem

**Comment by bryevdv** [comment] 2019-06-22 17:58
@duynguyen2411 how is this not a duplicate of #9020 ?

**Closed** 2019-06-22 18:36 UTC
Labels: TRIAGE
