### ISSUE TITLE
Simple semi-log line chart fails to render with confused log scale

### ISSUE THREAD

**Issue by leopd** [bokeh/bokeh#5393] opened 2016-10-22 08:00 UTC
This should be a really straightforward log-linear plot.  But the presence of the number "0.001" causes whatever calculates the log scale range screws up, and I get an empty plot.  (Take out the 0.001 and it renders fine.)

```
import bokeh
import bokeh.io
import bokeh.plotting
bokeh.io.output_notebook()
y = [
 0.32348853,
 0.001,  # This one screws it up
 0.10001138,
 0.091036782,
 0.067185409,
 0.068456814,
 0.064294182,
 0.030406525,
 0.023713678,
 0.019225951,
 0.01715965]
x = range(len(y))
fig = bokeh.plotting.figure(y_axis_type='log')
fig.line(x,y)
bokeh.plotting.show(fig)
```

![screen shot 2016-10-22 at 12 57 02 am](https://cloud.githubusercontent.com/assets/193183/19617928/82c9b1ee-97f2-11e6-9df6-1b55621793aa.png)

If I zoom way out, I see the chart oddly upside-down.
![screen shot 2016-10-22 at 12 58 00 am](https://cloud.githubusercontent.com/assets/193183/19617933/a01abf36-97f2-11e6-85eb-b8c79f2eb411.png)

**Comment by clairetang6** [comment] 2016-11-11 05:15
This is a duplicate of issue [3834](https://github.com/bokeh/bokeh/issues/3834). @leopd, you're right that the problem is in the calculation of the log scale range. See [this comment](https://github.com/bokeh/bokeh/issues/3834#issuecomment-190495197) for a description of the problem and a workaround.

**Closed** 2016-11-11 05:17 UTC
Labels: reso: duplicate
