### ISSUE TITLE
Developer build can not be installed on windows

### ISSUE THREAD

**Issue by ajasja** [bokeh/bokeh#5857] opened 2017-02-10 18:56 UTC
Tried to install the developer build (since I need the fix  #5700:)

Conda install failed with the error `CondaError: Cannot link a source that does not exist. c:\bin\python\anaconda\pkgs\bokeh-0.12.5dev11-py27_0\bin\bokeh`

Here is the full output:
```
$conda install -c bokeh/channel/dev bokeh
Fetching package metadata .............
Solving package specifications: .

Package plan for installation in environment c:\bin\python\anaconda:

The following NEW packages will be INSTALLED:

    futures-compat: 1.0-py2_0

The following packages will be UPDATED:

    bokeh:          0.12.4-py27_0 --> 0.12.5dev11-py27_0 bokeh/channel/dev

Proceed ([y]/n)? y

ERROR conda.core.link:_execute_actions(330): An error occurred while installing package 'bokeh/channel/dev::bokeh-0.12.5dev11-py27_0'.
CondaError: Cannot link a source that does not exist. c:\bin\python\anaconda\pkgs\bokeh-0.12.5dev11-py27_0\bin\bokeh

Attempting to roll back.

CondaError: Cannot link a source that does not exist. c:\bin\python\anaconda\pkgs\bokeh-0.12.5dev11-py27_0\bin\bokeh
```

I'm using windows 8.1 64 bit with python 2.7 32 bit.

Output of `conda list` is [here](https://gist.github.com/ajasja/3fb9e37d1af5672d013eedbaf15f91ea)

**Comment by bryevdv** [comment] 2017-02-10 20:03
This is a dupe of #5818

**Closed by bryevdv** 2017-02-10 20:03 UTC

**Comment by ajasja** [comment] 2017-02-13 10:14
Thanks! 
Removing anaconda\pkgs\bokeh-0.12.5dev11-py27_0\info\paths.json indeed solved the problem.

**Comment by bryevdv** [comment] 2017-02-14 16:30
When #5870 is merged I will start a dev build and we can see if the new conda-build fixes the windows issues (it should)

**Comment by bryevdv** [comment] 2017-02-15 02:29
`0.12.5dev12` is available and should be working on windows

**Comment by ajasja** [comment] 2017-02-15 06:01
@bryevdv  Thanks, works great!
