### ISSUE TITLE
Hover doesn't work on scatter plot when x&y scales are very different

### ISSUE THREAD

**Issue by leopd** [bokeh/bokeh#6396] opened 2017-06-06 22:18 UTC
Using:
bokeh 0.12.5
python 2.7.11
jupyter 1.0.0
on Mac Chrome 58.0.xxx

#### Description of expected behavior and the observed behavior
Simple example code showing the bug.  Code to draw 3 related trivial scatter plots.
(Uncomment each "p.scatter" line to see the relevant example.)
```
import bokeh.plotting
import bokeh.io
bokeh.io.output_notebook()

p = bokeh.plotting.figure(tools='hover')
#p.scatter(x=[1,2,3], y=[1,2,3], radius=0.01)  # works
#p.scatter(x=[100,200,300], y=[100,200,300], radius=1)  # works
p.scatter(x=[1,2,3], y=[100,200,300], radius=0.01)  # doesn't work
bokeh.plotting.show(p)
```
In the third case, when the x&y scales are very different, the hover tool doesn't work.  I believe it's because the hover target becomes infinitely thin vertically.  Bokeh seems to automatically adjust the radius to apply to the smaller of the two scales, so the circles are actually round not oval shape, but I'm guessing the code for the hover target doesn't match this behavior properly.

**Comment by bryevdv** [comment] 2017-06-06 22:26
This is a dupe of #517

**Closed by bryevdv** 2017-06-06 22:26 UTC

**Comment by bryevdv** [comment] 2017-06-06 22:29
In the absence of an actual scaling transformation that turns circles into ellipses, then a non 1-1 aspect will always be a problem. However, the usual desired used case seems to be to plot circles as always-circles (i.e. scatter markers) in which case *some* dimension has to be chose to measure with. This is configurable by the user, however, in case the default choice is not preferred: http://bokeh.pydata.org/en/latest/docs/reference/models/markers/circle.html#bokeh.models.markers.Circle.radius_dimension

**Comment by leopd** [comment] 2017-06-07 17:21
Here's a workaround for my use case:

```
p.scatter(x=[1,2,3], y=[100,200,300], line_width=5)
```

Setting the line width makes the circles look bigger without needing to specify a radius in data units, which is what confuses the hit tester.
