### ISSUE TITLE
Hover panel hides under neighboring gridplot figures.

### ISSUE THREAD

**Issue by cyrusmaher** [bokeh/bokeh#1744] opened 2015-01-22 18:10 UTC
On my data, this seems to only happen when the panel calls out to the right, strangely enough.

**Comment by cyrusmaher** [comment] 2015-01-22 18:38
Actually, it appears the hover panels for a given figure hide under any figure drawn after (above/to the left OK, below/to the right not ok). This effect is consistent between ipython notebook and html file output.

**Comment by damianavila** [comment] 2015-01-22 19:07
Hi @cyrusmaher, can you post an example code to check the behaviour? Thanks!

**Comment by cyrusmaher** [comment] 2015-01-22 20:53
No prob. Here you go!

https://gist.github.com/cyrusmaher/cd238d55288633905b88

**Comment by bryevdv** [comment] 2015-01-23 19:59
Can confirm. Probably a simple z-index CSS fix.

**Comment by damianavila** [comment] 2015-01-23 20:40
OK, I will take a look...

**Comment by bryevdv** [comment] 2015-01-28 16:07
time estimate: 1hr

**Comment by bryevdv** [comment] 2015-02-06 18:44
Unfortunately after some investigation, this is not gong to be so simple after all. It is not just the `z-index` which is already being set. It can be made to work by manually updating the `z-index` of the grid plot container, but dynamically modifying the `z-index` seems a bit wonky. Another option would be to attach the tooltip to the `<body>` and then absolutely position but that will also be finicky and take work. Moving this back out to `short-term` for now.

**Comment by damianavila** [comment] 2015-02-06 18:48
OK, thx for research in to this... I did not have time to look at it yet...

**Comment by birdsarah** [comment] 2016-04-13 03:44
Confirmed this is still an issue.

**Comment by birdsarah** [comment] 2016-05-28 16:29
Just to note this was *not* fixed as part of layout.

**Comment by mattpap** [comment] 2017-10-16 15:12
> Another option would be to attach the tooltip to the <body> and then absolutely position (...)

Not necessarily `body`, but `bk-root`. This is actually the most robust solution that doesn't rely on any assumptions about DOM structure and CSS properties (`z-index`, `overflow`, etc.).

**Comment by bryevdv** [comment] 2018-03-16 19:59
As of `0.12.15` the tooltip does not appear *hidden*, but it does shrink and line wrap to the right:

<img width="306" alt="screen shot 2018-03-16 at 12 56 38" src="https://user-images.githubusercontent.com/1078448/37541971-bf578b5e-2919-11e8-80d8-d6edb0cc3749.png">

**Comment by bryevdv** [comment] 2018-03-16 21:57
this is a dupe of #4930 which is later, but has more information, so closing this one.

**Closed by bryevdv** 2018-03-16 21:57 UTC
Labels: type: bug
