### ISSUE TITLE
Scrolling over plot in html page stops scroll action

### ISSUE THREAD

**Issue by canavandl** [bokeh/bokeh#2520] opened 2015-07-06 20:17 UTC
SciPy 2015 complaint: While scrolling down an html page, if the cursor passes over a plot, it kills the scroll action. This is true even if the scroll tools are not active on the plot. The user complaint was that this was especially bad for mobile.

**Comment by mattpap** [comment] 2015-07-07 07:20
This is a duplicate of #1450.

**Closed by mattpap** 2015-07-07 07:20 UTC
Labels: reso: duplicate, type: discussion
