### ISSUE TITLE
[BUG] Graph nodes collapse when the data source is changed during selection

### ISSUE THREAD

**Issue by p-himik** [bokeh/bokeh#10474] opened 2020-09-07 14:39 UTC
#### ALL software version info (bokeh, python, notebook, OS, browser, any other relevant packages)
Bokeh 2.2

#### Description of expected behavior and the observed behavior
Started at https://discourse.bokeh.org/t/weird-problem-with-selection-on-change-callback-patching/6289
Seems like there's some race condition going on that specifically involves `GraphRenderer` and/or `StaticLayoutProvider`.
If you click on any of the nodes, the whole graph will be collapsed into a single node at `(0, 0)`. Or maybe just all nodes move to `(0, 0)`. The plot goes back to normal if you interact with it.

I tried reproducing it with just `plot.circle`, without any graph-related stuff - worked just fine.

#### Complete, minimal, self-contained example code that reproduces the issue

```python
from bokeh.models import GraphRenderer, StaticLayoutProvider
from bokeh.plotting import figure, curdoc

D = 40
gr = GraphRenderer()
gr.node_renderer.glyph.size = 10
ds = gr.node_renderer.data_source
ds.data = dict(index=[i for i in range(D * D)])

gr.layout_provider = StaticLayoutProvider(graph_layout={idx: (idx % D, idx // D)
                                                        for idx in ds.data['index']})


def update(attr, old, new):
    ds.patch(dict(index=[]))


ds.selected.on_change("indices", update)

plot = figure(x_range=(-1, D), y_range=(-1, D), tools="tap")
plot.renderers.append(gr)
curdoc().add_root(plot)
```

**Comment by mattpap** [comment] 2020-09-23 14:56
Duplicate of issue #10453.

**Closed by mattpap** 2020-09-23 14:56 UTC
Labels: reso: duplicate, tag: component: bokehjs, type: bug
