### ISSUE TITLE
[BUG] Bokeh: HoverTool doesn't work with muli_line

### ISSUE THREAD

**Issue by Yannikpy** [bokeh/bokeh#10641] opened 2020-11-06 14:27 UTC
Versions: Bokeh 2.2.3, Python 3.7.6, Windows 10.0.19041, Firefox 82.0.2

I am expecting for each line to show 'foo' on hover. It works on the single line, but not on multi_line.

Minimal example:
```
from bokeh.plotting import ColumnDataSource, figure, output_file, show
output_file("Hover_multiline.html")

x = [1, 2, 3, 4, 5]
y1 = [1, 1, 1, 1, 1]
y2 = [2, 2, 2, 2, 2]
y3 = [3, 3, 3, 3, 3]

source_line = ColumnDataSource(data=dict(x=x, y=y1))
source_multiline = ColumnDataSource(dict(xs=[x, x], ys=[y2, y3]))

p = figure(tooltips='foo')
p.line(x='x', y='y', source=source_line)
p.multi_line(xs="xs", ys="ys", source=source_multiline)

show(p)
```

This worked on previous releases (up until 2.1), but does not on 2.2 and newer.

Thank you for this awesome package btw :)

**Comment by mattpap** [comment] 2020-11-06 14:33
Duplicate of issue #10458.

**Closed by mattpap** 2020-11-06 14:33 UTC
Labels: reso: duplicate, type: discussion
