### ISSUE TITLE
Bug with datetime column when using BlazeDataSource?

### ISSUE THREAD

**Issue by ywang007** [bokeh/bokeh#2601] opened 2015-07-23 01:31 UTC
There seem to be a bug with handling datetime column from a BlazeDataSource in a bokeh server

below code following the example of  https://github.com/bokeh/bokeh/blob/master/examples/plotting/server/blaze_source.py
but using the "aapl" data which contains a datetime column "date"

```
from bokeh.plotting import figure, show, output_server
from bokeh.models import BlazeDataSource
from blaze.server.client import Client
from blaze import Data

output_server("blaze_source")
c = Client('http://localhost:5006')
d = Data(c)
source = BlazeDataSource()
source.from_blaze(d.aapl)

p = figure(width=800, height=400, x_axis_type="datetime")
p.circle('date', 'close', color='green', source=source) #this does not work 
#p.circle('open', 'close', color='blue', source=source) #this works fine

show(p)

```

server will complain:

(BAD_COLUMN_NAME): Glyph refers to nonexistent column name: close, date [renderer: GlyphRenderer, ViewModel:GlyphRenderer, ref _id: d0a1bf93-d128-4c82-a8a4-97b7bbcd108e]

**Comment by damianavila** [comment] 2015-07-27 16:37
I think the problem is not related with the column name... this validation output is also present in our example, and the plot can be see it...

I got this in the js console as well: `Bokeh: could not set initial ranges`

**Comment by bryevdv** [comment] 2016-04-10 02:14
Closing since `BlazeDataSource` is no longer in Bokeh

**Closed by bryevdv** 2016-04-10 02:14 UTC
Labels: type: bug
