### ISSUE TITLE
Linked Brushing works incorrectly with line glyph

### ISSUE THREAD

**Issue by waqarmalik** [bokeh/bokeh#2946] opened 2015-10-06 21:08 UTC
Consider the following modification to the code that shows linked brushing: 
The change is that the seconds glyph (right) has been changed to line. Now if the lasso tool is used to select some points, the line plot is broken into two disjoint sets

```
from bokeh.models import ColumnDataSource
from bokeh.plotting import figure, gridplot, output_file, show

output_file("brushing.html")

x = list(range(-20, 21))
y0 = [abs(xx) for xx in x]
y1 = [xx**2 for xx in x]

# create a column data source for the plots to share
source = ColumnDataSource(data=dict(x=x, y0=y0, y1=y1))

TOOLS = "box_select,lasso_select,help"

# create a new plot and add a renderer
left = figure(tools=TOOLS, width=300, height=300, title=None)
left.circle('x', 'y0', source=source)

# create another new plot and add a renderer
right = figure(tools=TOOLS, width=300, height=300, title=None)
right.line('x', 'y1', source=source)

p = gridplot([[left, right]])

show(p)
```

**Comment by bryevdv** [comment] 2017-05-09 21:46
As I understand it, this is a dupe of #515

**Closed by bryevdv** 2017-05-09 21:46 UTC
Labels: type: discussion
