### ISSUE TITLE
'Help' button doesn't seem to work on Windows

### ISSUE THREAD

**Issue by Maggie-M** [bokeh/bokeh#2097] opened 2015-03-23 19:41 UTC
I was testing on Windows 7 (64-bit), using the default browser, Internet Explorer.

Clicking the help button didn't open up a new page to the Bokeh docs.  Right clicking on the button itself didn't even offer the option to open the link in a new tab.

**Comment by Maggie-M** [comment] 2015-03-23 19:55
I've encountered this issue on 32-bit Ubuntu, as well.

**Comment by Maggie-M** [comment] 2015-03-23 19:58
I've also encountered this on 32-bit Ubuntu.

**Comment by bryevdv** [comment] 2015-07-03 19:56
So, I've seen this broken before but I am unable to reproduce it on 0.9.1 RC on any windows browser. Closing as invalid for now, please re-open if it is encountered again

**Closed by bryevdv** 2015-07-03 19:56 UTC
Labels: type: bug
