### ISSUE TITLE
Passing numpy array to FixedTicker causes unhandled error message

### ISSUE THREAD

**Issue by mikesmith1611** [bokeh/bokeh#6405] opened 2017-06-07 09:57 UTC
bokeh 0.12.5
Using 'bokeh serve' with the following code produces the following message in the console:

```python
from bokeh.plotting import figure, curdoc
from bokeh.models import FixedTicker
import numpy as np

x = np.arange(-10, 10, 0.1)
y = x ** 2

p = figure()
p.line(x, y)
p.xaxis.ticker = FixedTicker(ticks=np.arange(-10, 10, 1))

curdoc().add_root(p)
```
```
2017-06-07 10:48:15,669 error handling message Message 'PATCH-DOC' (revision 1): ValueError('The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()',)
```
Using --log-level debug the following traceback is found
```
Traceback (most recent call last):
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\server\protocol\server_handler.py", line 39, in handle
    work = yield handler(message, connection)
  File "c:\users\michael\anaconda3\lib\site-packages\tornado\gen.py", line 1015, in run
    value = future.result()
  File "c:\users\michael\anaconda3\lib\site-packages\tornado\concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
  File "c:\users\michael\anaconda3\lib\site-packages\tornado\gen.py", line 1024, in run
    yielded = self.gen.send(value)
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\server\session.py", line 48, in _needs_document_lock_wrapper
    result = yield yield_for_all_futures(func(self, *args, **kwargs))
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\server\session.py", line 218, in _handle_patch
    message.apply_to_document(self.document, self)
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\server\protocol\messages\patch_doc.py", line 44, in apply_to_document
    doc.apply_json_patch(self.content, setter)
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\document.py", line 352, in apply_json_patch
    self._initialize_references_json(references_json, references)
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\document.py", line 1005, in _initialize_references_json
    instance.update_from_json(obj_attrs, models=references, setter=setter)
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\core\has_props.py", line 394, in update_from_json
    self.set_from_json(k, v, models, setter)
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\core\has_props.py", line 336, in set_from_json
    descriptor.set_from_json(self, json, models, setter)
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\core\property\descriptors.py", line 565, in set_from_json
    models, setter)
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\core\property\descriptors.py", line 285, in set_from_json
    self._internal_set(obj, json, setter)
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\core\property\descriptors.py", line 713, in _internal_set
    self._real_set(obj, old, value, setter=setter)
  File "c:\users\michael\anaconda3\lib\site-packages\bokeh\core\property\descriptors.py", line 746, in _real_set
    unchanged = self.property.matches(value, old) and (hint is None)
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```
The tickers are nonetheless set correctly! If a list is passed to FixedTicker this message disappears. As a lot of bokeh now accepts numpy arrays it will be good to allow numpy arrays to be passed to FixedTicker without this message.

**Comment by mattpap** [comment] 2017-06-07 13:12
This is a duplicate of issue #6393.

**Closed by mattpap** 2017-06-07 13:12 UTC
Labels: reso: duplicate
