### ISSUE TITLE
compatibility with Jupyterlab-0.33.4 ?

### ISSUE THREAD

**Issue by stonebig** [bokeh/bokeh#8117] opened 2018-07-29 17:45 UTC
I get an error when trying to install bokeh-0.13.0 and jupyterlab-bokeh extension on Jupyterlab-0.33.4:

````
jupyterlab_bokeh-0.5.0.tgz
Incompatible extension:

"jupyterlab_bokeh@0.5.0" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab              Extension        Package
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/application
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/apputils
>=0.17.2 <0.18.0        >=0.16.0 <0.17.0 @jupyterlab/notebook
>=3.0.3 <4.0.0          >=2.0.0 <3.0.0   @jupyterlab/services
````
would it be possible to get a patch release ?

**Comment by bryevdv** [comment] 2018-07-29 19:04
dupe of https://github.com/bokeh/jupyterlab_bokeh/issues/47

**Closed by bryevdv** 2018-07-29 19:04 UTC
