### ISSUE TITLE
ResetTool not visible in combination with SaveTool and gridplot

### ISSUE THREAD

**Issue by lukasreichel** [bokeh/bokeh#4767] opened 2016-07-07 12:24 UTC
The reset tool is not visible anymore in the gridplot if I add the save tool.

-> It only happens in combination with gridplot
-> tested in bokeh-0.12.0 and bokeh-0.12.1.dev1

example code:
```
from bokeh.layouts import column, gridplot

from bokeh.plotting import figure, output_file, show

output_file("toolbar.html")

# Add hover to this comma-separated string and see what changes

# with this selection the reset Tool is visible
TOOLS = 'box_zoom,box_select,crosshair,reset'

# with that selection the reset Tool is NOT visible
TOOLS = 'box_zoom,box_select,crosshair,reset,save'

# create a new plot with the toolbar below
p1 = figure(plot_width=400, plot_height=400, title=None, tools=TOOLS)

p1.circle([1, 2, 3, 4, 5], [2, 5, 8, 2, 7], size=10)

p2 = figure(plot_width=400, plot_height=400, title=None, tools=TOOLS)

p2.circle([1, 2, 3, 3, 5], [2, 5, 8, 1, 7], size=10)

p = gridplot([[p1,p2]])
show(p)
```

**Comment by bryevdv** [comment] 2016-07-07 13:01
Duplicate of #4759 fixed in #4763

**Closed by bryevdv** 2016-07-07 13:01 UTC
Labels: reso: duplicate
